### ISSUE TITLE
A Suggestion for Better File Handling

### ISSUE THREAD

**Issue by PFCKrutonium** [project64/project64#1003]
Because of how Windows handles directory permissions since Vista, writing to your own folder in Program files is no longer supported. Perhaps you could take a page from Dolphin, and create a directory in "Documents" called "Project64" containing the Roms, Saves, and Plugins directories. Allow the user to change it from inside the application of course, but default to that. This would have a couple of consequences, in that plugins would be shared between multiple installs of Project64 by default after this, but I don't think that should/would be a huge issue. The install can continue to work as is, but when the emulator is run for the first time it would create the directory and copy the relevant files to the new location. OpenRCT2 also does this.

This would make the builds from @JunielKatarn more usable imo.

**Comment by PFCKrutonium** [comment]
![pj1](https://cloud.githubusercontent.com/assets/3945538/13058527/c7544e8e-d3f1-11e5-91a6-235419964709.PNG)
![pj2](https://cloud.githubusercontent.com/assets/3945538/13058528/c75764de-d3f1-11e5-9812-d8a6abfe7ba4.PNG)

**Comment by project64** [comment]
the installer already changes permissions so it can write to the save/config/log folder with out redirection. If you want to share directories that is fairly easy to do as most things are just a setting in the config file.

At the moment the emu acts like it is portable,which also makes it easier to find the saves instead of being all spread out over the computer

**Comment by PFCKrutonium** [comment]
That's fine, but lets take the ClickOnce version above as an example - It's rediculous trying to find the directory where it is installed (C:\Users\pfckr\AppData\Local\Apps\2.0\HPX7JH23.PWV\HK58MJK1.ERB\proj...exe_0000000000000000_0000.0000_none_06427ee73172c475) is kind of ridiculous, This would allow for easier setup for people who are using Git Builds and not the ridiculously old build that is on the Website.

**Comment by JunielKatarn** [comment]
@PFCKrutonium What ClickOnce version do you refer to?
I have also made a [ClickOnce](http://hyvart.com/download/project64/project64.application) version for my build bot, and use the local data folder to store configuration, so it can persist between updates.

Config files, regardless of the Windows version, get stored at `%LOCALAPPDATA%\Hyvart Software\Project64Dev\Config`. That location doesn't need any special privileges to write on it.
The same base location could be used for plugins or other relevant files that don't depend on a specific `Project64.exe` instance.

Also, it is a good idea to provide self-contained independent zips, so they can be "installed" (meaning, placed) wherever the user sees fit (see http://hyvart.com/download/project64/ci).

**Comment by project64** [comment]
there is self-contained independent zips at the forum http://forum.pj64-emu.com/forumdisplay.php?f=10

**Comment by JunielKatarn** [comment]
@project64 I meant publicly. Are the alpha builds available to everyone, or only us Alpha testers?

One unrelated question, by the way? Which VS version is being used for these builds?

**Comment by project64** [comment]
Any one who wants alpha builds can send me a private message on the pj64 forum and I will give them access. 

being built with VS 2008

**Comment by PFCKrutonium** [comment]
@JunielKatarn I was referring to yours. I didn't know you had done that.
