### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by Krutonium** [project64/project64#1006]
I want to make a PR with a readme and a licence file, what should I include in them?

Also, @project64 If I may suggest, perhaps you could set up one of the many free CI services? It would be able to tell if you a PR breaks building things, and could even provide an easy way to provide "Beta" builds (like https://openrct2.org/downloads) on http://pj64-emu.com/ .

**Comment by cxd4** [comment]
The intended license throughout the project is GPL version 2.

I suppose some sort of README file should be added as well to, if nothing else, silence those GitHub messages on the repository/forks suggesting to add a README.  However, I have no opinion of what should go in it.  Command-line instructions, how to use on Windows, "about this repo", how to contribute or whatever...many different things that could go in a README.  It would be up to @project64.

Ultimately he could just create a gh-pages branch so http://project64.github.io/project64 would be a working documentation website, but I gather he prefers doing everything on his own server space.  (Likewise for his custom buildbot he runs on the forum.)

**Comment by PFCKrutonium** [comment]
At the absolute very least, there should be a licence file. A lot of people will refuse to work on a project if there isn't one, because there is no clear licence (And since there is no readme saying what the licence it is, it's all that much worse.)

**Comment by JunielKatarn** [comment]
@PFCKrutonium I'd say just create the PR with a `LICENCE.txt` or `LICENCE.md` file, containing the GLPv2. Make sure it's v2 and NOT v3, though. The latter is nocive for heterogeneous open source.

Regarding the builds, if I recall correctly from some old discussion, zilmar prefers to keep the dev builds private-ish, providing access only on a per-request base.

**Comment by project64** [comment]
yes create a PR request with files as @JunielKatarn  says it is GPLv2 .. so I guess a a license file and a readme stating how to build/setup and about the license.

I am running jenkins as a build tool, it builds it then runs a script to package it and put it on the pj64 forum. Yes it is semi private any one that wants access can ping me on the pj64 forum and I will give them access. If you do break the build I am the only one will see it and as I was the one who approved the merge request then i am the one who should fix it.

**Comment by PFCKrutonium** [comment]
Fair enough @project64 - I am going to get to work then ;)
@JunielKatarn In what way is GPLv3 harmful to Open Source? (Also, I would have put GPLv2 anyway, since I am not in the business of relicencing ;))

**Comment by JunielKatarn** [comment]
@PFCKrutonium It's a broad topic, but the very first thing that comes to mind (and I think was one of the reasons the kernel of the Linux OS never switched from v2) is that it prohibits linking against non-Stallman's morals-complying software.

I'm no expert, but I'm thinking this could pose an issue with anyone wanting to play around with propietary plugins, like Jabo's GFX, which is even the current default.

**Comment by cxd4** [comment]
There's no right or wrong on this.

GPLv3 was created to fight against stuff Microsoft and other companies started doing to expose vulnerabilities in v2.  v3 maximizes the fight against those manipulations, just with some side effects that the Linux author found to be ironic and contradictory (not so dishonest as the approach itself on pushing/tricking people to do the switch).

It's really a matter of opinion on how strongly you, individually, feel about preserving "ethical" OSS.

>kernel of the Linux OS

The name of the kernel itself is Linux, though.

The operating system it's installed to doesn't really have any good names AFAICT.  "Linux" is repeatedly challenged, "UNIX" is even less accurate, and "GNU" I find to be kind of disrespectful.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
