### ISSUE TITLE
Command-line arguments?

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#1010]
Does anybody know if Project64 has any command-line arguments? I can't seem to find any documentation if there are any.

If not, would @project64 be willing to add some? This would make it easier for people using launchers, and could also make testing Project64 easier to test in some cases.

Specifically, starting in fullscreen and the "always on top" option would be best for these situations.

**Comment by project64** [comment]
the launcher can do most things by editing the config file, is there anything that can not be done by changing the setting before running?

**Comment by vgturtle127** [comment]
@project64 Can it launch in fullscreen via the config file? I wasn't aware of the option to do so if there is.

Maybe we should add some recommendations for launcher settings in the Wiki/documentation?

**Comment by project64** [comment]
```
    AddHandler(Setting_AutoFullscreen, new CSettingTypeApplication("", "Auto Full Screen", (uint32_t)false));
```
that setting will mean when starting will it stay windowed or go to full screen

**Comment by vgturtle127** [comment]
@project64 Is that the option "Auto Full Screen=1" in the config?

**Comment by project64** [comment]
```
[default]
Auto Full Screen=1
```

**Comment by vgturtle127** [comment]
@project64 OK. Are these documented anywhere? We should probably do that soon. Or I should, anyway. :wink: 

I have a lot of options in my config, but do you know all of them? Like, could you list them?

Like I said I think I have most of them in my config by now, but if I am going to write documentation or or create a new page on the Wiki, I would like to have all the available options that are in the config.

**Comment by project64** [comment]
if you look at 
```
CSettings::AddHowToHandleSetting
```
then you will see all the settings that the main emulator uses

**Comment by vgturtle127** [comment]
@project64 Gotcha, OK I will take a look at that. Thanks, Zilmar.
