### ISSUE TITLE
Level select is freezing on Star Wars - Shadows of the Empire

### ISSUE THREAD

**Issue by SigmaVirus** [project64/project64#1014]
This is a issue that have been bugging me for quite a while and frankly the only thing that's keeping me from switching to newer versions of Project64 altogether.

I'm on Windows 10 x64 and I'm currently using Project64 2.2.0.9999 (0.0.0.415) 32-bit from here:
http://hyvart.com/download/project64/ci/

As for plugins I use either Glide64 Final from May 2012 or the latest GLideN64 by Gonetz from here:
https://github.com/gonetz/GLideN64/issues/808#issuecomment-183673274

Azimer Xaudio2 latest Git (December 2015) and Nrage Input from here:
https://sourceforge.net/projects/nragev20/

Hardware wise I'm on a i7 4970K CPU, ASUS R9 380 GPU with latest AMD driver 16.1.1, 16GB RAM etc.

OK, now to the issue.

When I start the game, select my game file and about to select level it's as the level select freezes and I can't choose any level (Try going/scrolling up and down)
Instead I can only play the level the cursor stays/lands on which is the previous completed level and the funny thing is it looks unbeaten with no hi-score/status at all.

There is nothing wrong with the controls and control wise I'm using a genuine gray Nintendo 64 controller with an Mayflash USB adapter and to clear/stress things out, this issue does not occur/exist on Project64 1.7.0.50 rev23 which is the version of Project64 I'm currently sticking with/keeps falling back to.

ROM wise I'm using my own dumped PAL/Europe version of the game with the RDB entry:

[4D486681-AB7D9245-C:50]
Good Name=Star Wars - Shadows of the Empire (Europe)
Internal Name=Shadow of the Empire
Status=Compatible
Core Note=Swoop bike speed issue
RDRAM Size=8

I'm hoping I'm not alone with this issue and that it's an easy fix.

This is really the only thing holding me back these days from migrating to newer versions of Project64 since it's become much stabler.

Thanks in advance!

**Comment by JunielKatarn** [comment]
Hi. I don't have the European version of that ROM, so can't help you duplicating it.
Just in case it helps, there is a more recent, stable build which contains many changes since 0.0.415 (https://github.com/JunielKatarn/Project64CI/compare/7a638a3d7dc312c91486429c929fa347a2e079c4...master)
http://hyvart.com/download/project64/ci/0.0.0.421

If you prefer to get the latest version automatically (no stability guaranteed, though), you can use the ClickOnce installer http://hyvart.com/download/project64/project64dev.application . Custom plugins and everything outside the `Config` directory would be lost on each update, though.

**Comment by SigmaVirus** [comment]
Thanks for your reply @JunielKatarn!

I don't think you have to have specifically the European version of this game for it to happen, if you have any version just start the game, choose a save file and then try to choose a level by tilting/pushing the analog stick up and down.

On newer versions of Project64 it will freeze where on 1.7 it will work.
It might be working on 2.0 and 2.1 but it have definitely been broken since last year some time since autumn/pre winter.

As for the specific version of 2.2 (0.0.0.415) from http://hyvart.com/download/project64/ci/ that I'm using it's because I tried other/older versions and they gave me this error:
"Cannot open a ROM because plugins have not successfully initialized"

That error also happened on recent EmuCR builds too.

0.0.0.415 at least boots my games, but have this error with Shadows of the Empire.

**Comment by JunielKatarn** [comment]
0.0.0.421 includes the fix for plugin loading. I tested it myself.
I guess I'll create a new deployment channel containing only stable builds, when I get the time.

**Comment by SigmaVirus** [comment]
Glad to hear that error got fixed!

Between the (now solved) Transferpak ROM errors and the "Cannot open a ROM because plugins have not successfully initialized" error, 0.0.0.415 was the only recent build that worked that I could use at the point when I started testing newer versions of Project64 out.

Anyway, your builds seems to be the cleanest around, EmuCR seems to ship their builds with outdated plugins and what not.
I tend to use EmuCR as a last resort.

I should probably get 0.0.0.421, not that 0.0.0.415 have been unstable or anything.

But regarding this issue, I wonder what might be causing it?

1.7 works spot on and I know 1.5 and 1.6 worked in the past.

**Comment by vgturtle127** [comment]
@SigmaVirus Are you using the CPu recompiler or the CPU interpreter when you play?

**Comment by SigmaVirus** [comment]
Actually I was using CPU Recompiler which is the default option for this game, have been since at least 1.7

But I switched to CPU Interpreter once I saw your reply @vgturtle127 and now everything is working correctly!

While it solved my problem, I don't know if I should close this issue or not because the game have been working under Recompiler before.

As for CPU Interpreter, is it safe to assume it's more stable/accurate to use? Usually (at least for Dolphin) things tend to slow down when using Interpreter but this was not the case here as the game ran fullspeed.

**Comment by SigmaVirus** [comment]
Instead of changing CPU Recompiler to Interpreter in the GUI (which adds an entry to the .cfg file), I added this line to the RDB entry instead:

CPU Type=Interpreter

Now it looks like this instead:

[4D486681-AB7D9245-C:50]
Good Name=Star Wars - Shadows of the Empire (Europe)
Internal Name=Shadow of the Empire
Status=Compatible
Core Note=Swoop bike speed issue
**CPU Type=Interpreter**
RDRAM Size=8

which I think is a bit cleaner way to do it!

The game is working fine now on my end and I played through a couple of missions and I could select levels perfectly.

If something needs to be done I'll leave this issue open, otherwise I'll just close it.

**Comment by LegendOfDragoon** [comment]
>While it solved my problem, I don't know if I should close this issue or not because the game have been working under Recompiler before.

Keep it open, because the recompiler needs to be fixed.

**Comment by SigmaVirus** [comment]
@LegendOfDragoon

No problem, I'll just leave it open for now.

**Comment by vgturtle127** [comment]
@SigmaVirus I would say the interpreter is SOMETIMES more accurate. Sometimes it has issues, especially with certain instructions (tested using PeterLemon's N64 ROMs).

Overall though, the answer is yes for most interpreters vs recompilers (in regards to Project64, anyway).

**Comment by SigmaVirus** [comment]
Thanks for the info, then I had the right assumption on this at least.

**Comment by vgturtle127** [comment]
@SigmaVirus Sometimes there are weird CPU bugs, I haven't yet started my sync cores testing, but I have a feeling the CPU interpreter and recompiler will be much better once all the bugs are fixed.

**Comment by SigmaVirus** [comment]
Thanks for the information @vgturtle127 
I'm certainly looking forward to all these bug fixes and changes!

**Comment by vgturtle127** [comment]
@SigmaVirus Me too, that way we can actually use both interchangeably. :stuck_out_tongue:

**Comment by LegendOfDragoon** [comment]
Does this happen on (U) version?

**Comment by SigmaVirus** [comment]
That's what I would like to know too. My hunch is telling me that all versions of this game is affected by this.

This should be dead easy to test for anyone with a JAP or USA version of the game and it takes less than five minutes.

1. Start the game
2. Load game file/create a game file
3. Attempt to choose/select any level

4. Either success or failure

**Comment by LegendOfDragoon** [comment]
I was able to load a file without seeing any noticeable issues on both U and E. However, i did get a sync error exclusively in E version. @SigmaVirus can you try disabling Advanced Block Linking and see if that fixes the problem you have? Because disabling that, got rid of the sync error I get.

**Comment by SigmaVirus** [comment]
@LegendOfDragoon 

I disabled CPU Type=Interpreter in my RDB so it reverted back to Recompiler and then I disabled Advanced Block Linking like you suggested and it worked perfectly.

So either disabling Advance Block Linking or changing Recompiler to Interpreter seems to work and fix this problem.

**Comment by vgturtle127** [comment]
@SigmaVirus I think we can change both, if I remember correctly. Advanced Block Linking and the CPU emulation method, I mean.

**Comment by AmbientMalice** [comment]
@SigmaVirus ABL is a recompiler setting. When you're using the CPU interpreter, it isn't relevant. Quite a few games have rare problems with ABL. Resident Evil 2 & Star Fox to name some.

**Comment by LegendOfDragoon** [comment]
>Is there a significant problem related to this, or is it enough changing the RDB to either disable Advanced Block Linking or change Recompiler to Interpreter like I did first?

ABL is an important feature, so I'd like to see it get fixed for a few games rather than rely on disabling it. It's up to you whether you want to send a PR disabling it specifically for the E version, or just waiting for it to be fixed.

**Comment by SigmaVirus** [comment]
Hmm, I'll have to test the game for a few levels with ABL off and see if I can find anything else being wrong just in case it's related to turning it off.

If all is good, then we'll see if it's worth making a PR or not.

**Comment by SigmaVirus** [comment]
I did not find anything wrong with disabling Advanced Block Linking and the game worked fine so I went ahead and made a pull request to fix the PAL/European version with a simple RDB edit.

Should be good now!
