### ISSUE TITLE
Super Smash Bros. (Europe) is broken unless you change the RDB plus it's way to fast

### ISSUE THREAD

**Issue by SigmaVirus** [project64/project64#1015]
Just thought I would give you guys and gals a heads up regarding Super Smash Bros. (Europe)

If you attempt to play the game on newer versions (Project64 2.2.0.9999, 0.0.0.421 tested) where the entry in the RDB looks like this:

[93945F48-5C0F2E30-C:50]
Good Name=Super Smash Bros. (Europe)
Internal Name=SMASH BROTHERS
Status=Compatible
Culling=1
SMM-Cache=0
SMM-FUNC=0
SMM-TLB=0
ViRefresh=2200

you'll soon to find out that the game will be broken and all you see is a black screen with sound and pressing any buttons on the controller will do nothing.

To fix this, you'll have to add this line:

Counter Factor=1

Now the game starts and can be played but it's way to fast so in order to fix that you'll have to delete this line:

ViRefresh=2200

making ViRefresh defaulting to the value 1500 and the speed will be OK.

So for PAL/Europe owners of the game the RDB entry for Super Smash Bros. have to look like this:

[93945F48-5C0F2E30-C:50]
Good Name=Super Smash Bros. (Europe)
Internal Name=SMASH BROTHERS
Status=Compatible
**Counter Factor=1**
Culling=1
SMM-Cache=0
SMM-FUNC=0
SMM-TLB=0

I have edited my own personal RDB to this and the game is working perfectly.

If someone could fix this in the official/original RDB so that anyone owning a PAL copy can play this game it would be great.

Thanks in advance!

**Comment by cxd4** [comment]
Try clicking this if you are new to Git:
https://github.com/project64/project64/edit/master/Config/Project64.rdb

You can use this web interface to "edit" the RDB file with your suggested change of `Counter Factor = 1` being added in to it.  When you save the "edit" it should create a pull request to the repository, which zilmar can then review and/or merge to adopt your change.

**Comment by vgturtle127** [comment]
@SigmaVirus I went ahead and added it to #1017 , so you don't have to worry about it.

**Comment by SigmaVirus** [comment]
A big thank you for this guys!

However, @vgturtle127 

I don't know, and it's only a hunch but do you think the Australian version might be affected by this too since it's a PAL region?

Obviously the USA version works because I've seen screenshots from it on issues regarding GLideN64 and heard no one complain about it so far regarding this kind of issue.

I know I'm one of the few that emulates the European versions but that's where I'm from and I got my games.

Technically I could buy any Australian version/release of a game and it would work perfectly on my European N64 and vice versa.

If you feel I can close this, just let me know and I'll close it.

**Comment by vgturtle127** [comment]
@SigmaVirus Actually, all the games were affected somewhat. I updated the AUS, PAL, Japanese, and NTSC with new RDB settings. It fixed a few problems and improved performance a bit, so thanks for reporting this otherwise I probably wouldn't have noticed! Also, thanks to @LegendOfDragoon for his suggestions as well! :smile: 

As soon as the pull request is merged, you can close this issue! :wink:

**Comment by SigmaVirus** [comment]
Great work, I'm glad it solved so much!

I'll make sure to close it once it's merged.
