### ISSUE TITLE
Why so old Visual Studio version? Can't compile with VS2015

### ISSUE THREAD

**Issue by codingyourlife** [project64/project64#1016]
Wanted to try it but this old VS2008 project file makes it difficult to even compile it. I used VS2015. Is there a reason why noone upgraded?

**Comment by vgturtle127** [comment]
@codingyourlife There are two, one is for VS2008 and older versions, the other is for newer versions.

A few of our contributors have older operating systems and some just use older versions of Visual Studio.

**Comment by dsx-** [comment]
yeah ive never had a problem with 2013

**Comment by vgturtle127** [comment]
@dsx- Well, arguably if you are using the community version you should just keep it up to date. Community 2015 is out. Unless you are using Windows 8.1 or something. But yeah, anything after 2008 should work, in theory.

**Comment by JunielKatarn** [comment]
A while ago, I tweaked PROPS and VCXPROJ files so they build seamlessly in any Visual Studio version starting with 2010.

2008 and earlier don't use MSBuild, so they need a different makefile type (VCPROJ).

I have never heard of a single developer in this community who prefers VS 2008 or is unwilling to upgrade to more recent and free versions.

However, @project64 had mentioned he uses 2008 for "official" builds (both dev and release).
Months ago, binaries produced by 2010 or later had UI bugs on Windows XP. This is not the case anymore.

In my opinion, we should ditch 2008 and obliterate its makefiles, for they just add duplicate work when adding/changing files or projects. Again, VCXPROJ supports a fair range of VS versions, and will continue with future releases.

**Comment by JunielKatarn** [comment]
@codingyourlife, you might find this wiki entry useful:
https://github.com/project64/project64/wiki/Building

**Comment by codingyourlife** [comment]
The *.sln file looks like this:
![slnfile](https://cloud.githubusercontent.com/assets/10122382/13373525/4392d3e0-dd6a-11e5-8a56-c5adc9cd6453.JPG)

But now that I think about it I might have deselected C++ stuff on VS setup. I think we can safely close this. I didn't read the output window it's saying "Install Windows XP support for C++"
