### ISSUE TITLE
[RSP] Goldeneye wrong blood

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#1021]
With the PJ64 RSP the blood in Goldeneye's intro is wrong. RSP Recompiler/Interpreter makes no difference. Correct with cxd4 RSP
![1](https://cloud.githubusercontent.com/assets/7283660/13525704/25dae93a-e203-11e5-9aed-a4803673e958.jpg)

**Comment by LegendOfDragoon** [comment]
This seems to be due to the mfc0 exit implementation.

**Comment by cxd4** [comment]
@purplemarshmallow are you using either one of:  HLE audio or HLE graphics?

**Comment by purplemarshmallow** [comment]
No
LLE gfx, LLE audio

**Comment by cxd4** [comment]
So, if you switch to enable HLE audio does that affect the issue at all?  As weird as that sounds.

**Comment by purplemarshmallow** [comment]
Looks different but still incorrect
![1](https://cloud.githubusercontent.com/assets/7283660/13536323/81e7d008-e23f-11e5-8e09-1c05be99ce71.jpg)

**Comment by cxd4** [comment]
And, if you can compile with this hack removed:
https://github.com/project64/project64/blob/master/Source/RSP/Interpreter%20Ops.c#L313

Change it to some sort of false condition, like `if (0)` or whatever.

Does the modified RSP with the task reset hack removed still have the glitch, with audio HLE?

**Comment by purplemarshmallow** [comment]
I removed the hack and now the glitch is gone (audio HLE, RSP interpreter)

**Comment by cxd4** [comment]
I suppose I could PR my preferred implementation of task short-circuiting over to @project64's RSP, but in principle I have not really decided whether my method is worse or better.

I reconstructed my implementation for more technical problems I was facing than bugs in games.

**Comment by LegendOfDragoon** [comment]
I definitely think your method is better overall. I myself just write game specific code to deal with games that require this mfco exit code to run.

**Comment by cxd4** [comment]
It technically could be that his method is better, depending on how similarly other titles outside of Boss Games may also be particular about timing in response to signal and semaphore changes.  My method has the disadvantage of not doing this subtle (even where sometimes invisible) corrections to the order of updates made to the state machine.
