### ISSUE TITLE
Creating a save file in some games makes the emu lag

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1026]
Very noticeable in Mario Party 3.
Seems to be constantly writing to the hard disk during the process. This is inneficient.
Save files should be flushed to the hard drive after a couple of seconds, much like Dolphin does.

Related issue: #897 
@death-droid @project64

**Comment by death-droid** [comment]
Interesting, i might take a look into this.

**Comment by cxd4** [comment]
Is it this way with Project64 1.6 or older?

I haven't scrutinized all the changes with mempak/SRAM in Project64 2.2, but I can say that prior to this it usually was Mupen64 that took like 10+ seconds to finish writing/creating a save file to my overused slow USB flash drive.  So if Project64 is even slower than Mupen64 is with writing save files, you know some regression likely came in.

**Comment by oddMLan** [comment]
Not that I remember. Lemme check.

**Comment by cxd4** [comment]
The way I see it there are 2 ways to trace the exact change causing this regression.

One is to poke in calls to DisplayError(), printf() or other functions that will pop up some kind of message output to trace the time taken to finish executing in-between the lines of code here:
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/Eeprom.cpp

The other is to look at the Git history for that `Eeprom.cpp` file and do some `git checkout #######` commands on it until an old-enough commit not having the issue is stumbled upon:
https://github.com/project64/project64/commits/master/Source/Project64-core/N64System/Mips/Eeprom.cpp

**Comment by death-droid** [comment]
Main difference checking out what the eeprom code used to look like in project64 1.6 and early GIT copies is that the eeprom code for example made use if specific windows read/write functions rather then Zilmars CFile class

**Comment by project64** [comment]
tho the CFile class uses the windows functions so that should not matter

**Comment by oddMLan** [comment]
https://github.com/project64/project64/blob/1c585a93bd00f69e07290c784f37a0453778e09d/Source/Project64/N64%20System/Mips/Eeprom.cpp
Earliest source from the repo

Diff: https://www.diffchecker.com/c38mbhc1

**Comment by oddMLan** [comment]
ff4bd28e3ea867699ad5f733377c95d0a5346421 alleviates the issue to some extent, but it does not fix it. The emu still stutters horrendously while it's writing the save file to the disk.

Project64 1.7 doesn't lag at all while writing the file.

The key difference is that Project64 1.7 is not writing the file constantly to the disk, while Project64 2.x is. Either we should wait the game is done writing its changes to the save file and then flush the changes to the hard disk in single write, or just put a timer after the bytes changed are flushed to the disk. Anything but constantly writing for every byte changed by the game, that is overkill.

**Comment by project64** [comment]
if you get rid of 
```
MempakHandle[Control].Flush();
```
in Mempak::WriteTo - Source/Project64-core/N64System/Mips/Mempak.cpp

does that make a difference ?

**Comment by oddMLan** [comment]
Unfortunately I'm not in a computer with Visual Studio installed right now, so I can't test :crying_cat_face: 

But it does seem like it would make a difference, I'll check as soon as I can.

**Comment by Frank-74** [comment]
It's not just saving that has lots of lag, loading from the mempak is affected too.

In Monaco Grand Prix (U), save a Career, then load the Career.  Saving and Loading takes about the same time.

It wasn't like this a few months back.

**Comment by Frank-74** [comment]
I can confim removing the 'MempakHandle[Control].Flush();' command fixes it.  No stutter, lag or disc abuse at all.

**Comment by oddMLan** [comment]
>I can confim removing the MempakHandle[Control].Flush(); in Mempak.cpp fixes it. No stutter, lag or disc abuse at all. For both saving and loading from Mempak.

And does it still update the save file after a few seconds, like in Project64 1.7?
Or just during emulator close? Because if it's the latter, this has the potential of losing save data if the emulator or computer crashes. Imagine how terrible that would be if you made long progress in a game and then Windows decided to crash.

You can verify by opening a explorer window and if you see an update in file size. Or use HashTab and determine if the CRC32 is different after a few seconds.

**Comment by project64** [comment]
it will be cached and written when windows wants to, could be right away, maybe a few seconds, maybe a few minutes. If he process crashes it still be written, if blue screen then data loss can happen.

**Comment by Frank-74** [comment]
Windows hasn't crashed on me for 10 years.  Windows BSOD's are a thing of the past with me from XPSP3, now on Windows 8.1.

Unless you count a power supply bursting into flames on my old XP PC.  Though Windows kept on going until I unplugged from the wall.

**Comment by cxd4** [comment]
Windows 10 hasn't crashed on me for 0 years.

**Comment by JunielKatarn** [comment]
> Windows 10 hasn't crashed on me for 0 years.

Windows 10 has been out for 0 years :smile:

**Comment by cxd4** [comment]
Indeed.  It's also been on any of my computers for that long.
