### ISSUE TITLE
Why do games that don't require the memory pak at all create a mpk file?

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1027]
Very easy example: Conker's Bad Fur Day.
The game saves to the cartridge and never requires the memory pak for anything.
Funny thing is, I see, that it also creates a .eep file for the game. Then what's the purpose of the mpk file then? I opened the mpk with Nrage's Rawdata, and even after saving in the game all I see is an empty memory pack. 

The same goes for Banjo-Kazooie and Banjo-Tooie, the games never use the memory pak for anything, yet they create mpk files which are 1:1 to the empty one Conker creates (checked with an Hex editor).

~~Diddy Kong Racing also does this. Yet it never uses the mempak.~~ My bad. It does use it to save the ghost data. But IMO, the mpk should be created until the game attempts to save that ghost data. In other words, until the game actually attempts to write data to the Memory Pack, not before.
Not all the games do this, it seems an issue mostly with games developed by Rareware.

@death-droid I remember you made #194 which creates an individual mempak for each game. Probably this design issue was always there but not noticeable since the former behavior was to write to a single mempak file, although they never write a page to the mempak.

**Comment by death-droid** [comment]
This is odd as from memory i changed the code so it would only write to the mempak file (and also create the file) when a writeto command has been sent to the mempak.

**Comment by vgturtle127** [comment]
@oddMLan If it created an .eep file, that means it has a EEPROM save function on the cartridge, which is funny because I am not sure those games have EEPROM saving. I will have to check, but I don't think they use EEPROMs...

**Comment by AmbientMalice** [comment]
Diddy Kong Racing uses the mempak for storing ghost race data, and you can store your save files on the mempak for backup or transfer. If it is occuring in other Rareware games, it could be some sort of leftover from planned content such as being able to save to mem pak or EEPROM if you want, Perfect Dark-style.

**Comment by oddMLan** [comment]
>Diddy Kong Racing uses the mempak for storing ghost race data and you can store your save files on the mempak for backup or transfer.
Oh, my bad then. But I think the preferable behavior would be creating the mempak until actual data is attempted to be written in it.

>This is odd as from memory i changed the code so it would only write to the mempak file (and also create the file) when a writeto command has been sent to the mempak.

Maybe it needs additional checks? Like, don't write the mempak if it's empty.
A Bug's Life doesn't write the mempak right away but only after you get past the prompt saying "this game supports the Controller pak and Rumble pak".
With Conker, it happens right away, although it never officially supports the mempak.

>If it is occuring in other Rareware games, it could be some sort of leftover from planned content such as being able to save to mem pak or EEPROM if you want, Perfect Dark-style. It's possible Rareware left hooks in place to read/write from mem pak in those games for whatever reason.

That sounds very likely. I think during development they might have been using memory paks for testing and debugging cause it's cheaper and safer than buying memory chips. Only speculation though.

**Comment by death-droid** [comment]
Hmmm well the files written should have the freshly formatted mempak data which is basically just the information required for games to realise the memory pak exists.

The data you find in those mempak files should start with something like, even if no data has been saved to it.
0x81, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,

**Comment by oddMLan** [comment]
I get that, but is it meaningful to have it saved to the hard drive?
I think it would make more sense that, if the presence of the formatted memory pack file is absolutely necessary for the game to know it's there, keep it mapped in RAM but _don't _write it to the hard disk until the game actually writes data to it.
I test a lot of games and never save, yet, they create these unnecesary empty memory pack files. I think it's unnecesary. 35kb might not seem like a lot, but it creates fragmentation. And makes moving the Project64 folder slower because of that.

**Comment by cxd4** [comment]
I remember when I switched from Castlevania (U) to Castlevania (J), the Japanese release just used the 512 bytes save file stored to EEPROM, but apparently Nintendo of America wanted to make some more money off of selling the controller pak accessory for the USA release of the game, which used 2 pages 1 note = 512 bytes of mempak.

**Comment by death-droid** [comment]
The files are only saved to the disk when the write command has been triggered

```
void Mempak::WriteTo(int32_t Control, uint32_t address, uint8_t * data)
{
    if (address < 0x8000)
    {
        memcpy(&Mempaks[Control][address], data, 0x20);

        FILE* mempak = fopen(MempakNames[Control], "wb");
        fwrite(Mempaks[Control], 1, 0x8000, mempak);
        fclose(mempak);
    }
    else
    {
        /* Rumble pack area */
    }
}
```

**Comment by project64** [comment]
fopen/fclose is meaning that this is getting flushed to disk for every write, I do not know how frequent the write to is. I assume it would not be a lot, if that is the case not an issue, if it is written to a lot then it might be.

**Comment by vgturtle127** [comment]
@cxd4 Huh, that's interesting. Wasteful, but interesting.

@death-droid @project64 So if I am reading into this correctly, we can actually flush them to the disk whenever we want?

**Comment by project64** [comment]
when a file handle is closed all changes will be flushed to disk, with the windows API create file/write file, they are generally written to buffers that the OS will write back at a latter stage. So it can buffer multiple writes at one time, you can cause it flush by calling FlushFile. I know with logs just the amount of them if you flush all the time then you get a huge performance hit, where if you let the OS manage it is not much.

**Comment by vgturtle127** [comment]
@project64 Alright, that makes sense.

I know it doesn't matter to some people, but I am using an SSD and stuff like that matters to me, so eliminating writes wherever possible is a positive thing. :wink:

**Comment by oddMLan** [comment]
>The files are only saved to the disk when the write command has been triggered

I don't think this is enough, if games are triggering the write command even if they are just checking the presence of the memory pak, the algorithm needs additional checks. Don't write mpk if it's freshly formatted and empty. Lots of 35kb empty mpks with no meaningful data is wasteful.

**Comment by cxd4** [comment]
I guess the disadvantages to keeping the FILE stream open constantly (as long as emulation of ROM is open) are a) slightly more resource usage, and b) if you want to copy/read/write from Project64's save files while emulation is running, Windows Explorer or whatever may get denied access if the stream is hung open instead of fopen()/fclose()'d on a regular basis as-is the case now.

Advantage of course being that emulation can't be slowed down so miserably by constant SI access to the save chips or the controller pak file.

I don't know which way I prefer.  Real N64 probably wouldn't let you access save chips while the cart is plugged in anyway so maybe keeping the FILE streams/Win32 HANDLE file objects open constantly for performance reasons may be better and/or more "accurate" overall.

**Comment by oddMLan** [comment]
>if you want to copy/read/write from Project64's save files while emulation is running, Windows Explorer or whatever may get denied access if the stream is hung open instead of fopen()/fclose()'d on a regular basis as is the case now

not like you actually can with the current implementation

**Comment by cxd4** [comment]
That's curious then that some games using EEPROM would slow Project64 down by that much then.
Well unless it's simultaneously trying to access mempak alongside that.

**Comment by oddMLan** [comment]
ff4bd28e3ea867699ad5f733377c95d0a5346421 helps, I think? Diddy Kong Racing no longer creates a mpk file during first bootup and even after saving ingame. But it creates an mpk if you start it a second time.

Banjo-Kazooie creates MPK during first bootup, even if the game does not use it.
I think the changes in the commit are a step in the right direction, but there needs to be some sort of check that if the game just created a formatted memory pak with no meaningful data in it, it should be kept in RAM and not flushed to the disk, not until the game actually changes other bytes.

**Comment by bryc** [comment]
> Banjo-Kazooie creates mpk during first bootup, even if the game does not use it for anything.

I actually noticed this when doing MPK tests on hardware. Banjo-Kazooie ended up accessing the MPK to silently repair my intentionally corrupted (completely erased) Controller Pak. It's possible CBFD is doing something similar. They probably were initially using it during development before ultimately going with EEPROM but they left in some of the original MPK code.

**Comment by cxd4** [comment]
It's not really a MPK vs. EEPROM thing.  Whether a game tries to repair or invalidate corrupted save data is all the same--operations on memory buffers.  Whether it's ultimately stored to or read from MPK or EEPROM format is an entirely unrelated aspect.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
