### ISSUE TITLE
Loading a savestate using "Load... (Ctrl+L)" will freeze the emulator

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1032]
The only way to work around this is to load a previous savestate by pressing F7 (or if you don't have one, by pressing F5 and _then_ F7) and THEN using "Load... (Ctrl+L)".

Probably something isn't getting initialized when it should.
I can only speculate that something is not getting initialized and only gets initialized when you press F7, but not at the moment of selecting the "Load... (Crtl+L)" and that's why the emulator deadlocks and only loading a previous savestate by pressing F7 fixes it.

**Comment by oddMLan** [comment]
Very annoying bug, hinders testing action when loading savestates to reproduce bugs. I don't think this would be too complex to fix
@death-droid @project64 what do you think?

**Comment by project64** [comment]
I recently cleaned up the code to do with making it cross platform, does this still happen with the latest source code?

**Comment by LegendOfDragoon** [comment]
I can't reproduce.

**Comment by oddMLan** [comment]
Let me compile a new release. Also let me check if it happens with the builds from the buildbot.

**Comment by oddMLan** [comment]
My bad, was using a slightly out of date build. With the latest build it doesn't happen, probably it got fixed in the rewrites.

**Comment by project64** [comment]
yer a lot of that code I cleaned up and made a lot better, so does not surprise me that it is fixed
