### ISSUE TITLE
Pokémon Snap crashes while saving "Writing 0 to a flash ram command register" with Debugger enabled

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1034]
![pkmn](https://cloud.githubusercontent.com/assets/7278372/13905750/01a16884-ee86-11e5-9651-60daea665c94.PNG)
![pkmn0](https://cloud.githubusercontent.com/assets/7278372/13905751/037088de-ee86-11e5-9002-65569b8a3950.PNG)

Same thing happens in Paper Mario (tested E M4 version).

**Comment by cxd4** [comment]
I actually got this exact crash while trying to play the game on Linux via Mupen64 0.5.

**Comment by oddMLan** [comment]
Nah, I just checked, my build is 32-bit.

**Comment by LegendOfDragoon** [comment]
I assume this issue has been fixed. Can you test and confirm?

**Comment by oddMLan** [comment]
Fixed.
