### ISSUE TITLE
[PJ64Glide64] Some settings from the Glide64.rdb file are getting ignored (REGRESSION)

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1037]
E.g. Setting Point-based sampling `filtering=2` in any game doesn't work. Filtering gets set to automatic regardless.

On the other hand, settings such as `zmode_compare_less` are actually getting read and applied from the RDB.

I think this happens with every single setting that has a default parameter `game_setting_default` set in the emulator, confirmed by the code here https://github.com/project64/project64/blob/master/Source/Glide64/Main.cpp#L1584

**Comment by project64** [comment]
I will have a look at this tonight if I get the chance .. just to double check where is the filtering=2

 I assume in Glide64.rdb, but which file are you looking at the value written in to.

When it does GetSetting(Set_filtering) it should go through each location and go to the next if none exist  (game settings (.cfg)  -> game settings (Glide64.rdb) -> plugin global setting (.cfg) -> default  value).  Maybe one of the location checks is not working correct.

**Comment by oddMLan** [comment]
Yes, I'm placing it `filtering=2` in Glide64.rdb
I tried placing it Project64.cfg under the settings of the game, it made no difference.
Then placed it under the [Glide64] section, and it worked.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/ec23b073029faaa6039c3c0d27859a5b0c957d4d fix it?

**Comment by oddMLan** [comment]
Yes, but something is going wrong. I'll need a vid to explain it

**Comment by oddMLan** [comment]
http://webm.host/fccf3/vid.webm

Something funky is going on with the settings...

Also settings don't save between boots, but for that I'll reopen #1035

**Comment by project64** [comment]
this https://github.com/project64/project64/commit/723ecb80b384ede7e101e90f50fe6d6f882f1972 might fix the funky you were seeing in the video

**Comment by oddMLan** [comment]
Fixed!! :D
