### ISSUE TITLE
Cannot load a second game / another rom

### ISSUE THREAD

**Issue by Papermanzero** [project64/project64#1041]
Starting a rom is working without any issue, however if the user is selecting another rom, the screen goes white and stays white. So the emulator must  be closed and opened again, to select a new rom.

Plugins:
GlideN64 (https://github.com/gonetz/GLideN64)
AziAudio (https://github.com/Azimer/AziAudio)
CXD4/RSP (https://github.com/cxd4/rsp)
NRage 2.3c

**Comment by cxd4** [comment]
I can hypothesize that these are the same set of symptoms caused by https://github.com/project64/project64/issues/1030.

**Comment by Papermanzero** [comment]
To be honest I switched to project64 from mupen64plus due to gliden64.
The game based setting feature for gliden64 is still missing for mupen64plus, that's why I am currently using project64. However gliden64 relies on OpenGL and not on Direct3D.
But anyway, thanks for the workaround.

**Comment by cxd4** [comment]
What won't work is starting a ROM, end emulation, change plugins from GlideN64 to something else using OpenGL for Windows, then start any ROM.  This requires the window to be destroyed and remade.

What should work is starting a ROM with GlideN64, ending emulation, then starting another ROM.
If **that** doesn't work then it's the plugin's fault.  GlideN will need to be designed to not SetPixelFormat more than one time:  If GetPixelFormat already returns a valid GDI pixel format enumerator, then do not make a second call to set the pixel format when the currently fetchable one can be used instead.

**Comment by Papermanzero** [comment]
It's like you described.
Ending the emulation and starting a Rom is working.
However directly starting a new rom is not working.
So the user always has to end the emulation

**Comment by cxd4** [comment]
So you don't have to change between different OpenGL plugins to notice the problem?
Only the ROM being selected from the browser needs to change to see the issue?

**Comment by oddMLan** [comment]
Open a ROM (either from the ROM browser or using the _File > Open ROM_ option)
Once the ROM loads, don't press F12 to End Emulation, click the _File_ menu and select one of the recent ROMs in the list or _Open ROM_ and select another ROM.

Main window flashes white for a split second but ends up showing the ROM browser while emulation is still going in the background. Pressing F12 in this state to end emulation and then opening another ROM either through the ROM browser or the File > Open ROM option (or selecting a recent ROM from the list) works, no need to close the emulator to destroy the window.

This actually happens with **any** GFX plugin, this is a bug in Project64's side.

**Comment by cxd4** [comment]
Never mind then; this sounds like something totally different than the issue I referenced.

Sounds more like that thing zilmar keeps trying to do with making RomClosed never get called until right before the next RomOpen, under some argument I recall him giving about how the real N64 hardware never having the ROM removed just because the control deck shuts off, until taking the cart out of the thing or some other weird analogy he made.

**Comment by LegendOfDragoon** [comment]
I think this issue might be related to #921 . Some time during the refactoring, end emulation became less stable. Sometimes I hit end emulation and it won't end until several seconds later.

**Comment by vgturtle127** [comment]
@Papermanzero @cxd4 @LegendOfDragoon @oddMLan I actually have to restart the emulator every time I want to start a new game. I have a feeling this bug should be tackled soon, as it has been around for awhile and causes a lot of crashing.

I think it may actually be a combination of bugs, since I also have encountered bugs during loading ROMs, using the ROM browser, etc.

I think "End Emulation" is kind of useless if it doesn't properly end the emulation. :wink:

**Comment by LegendOfDragoon** [comment]
>I have a feeling this bug should be tackled soon, as it has been around for awhile and causes a lot of crashing.

If you want it fixed sooner, then you should track down the commit that causes the regression.

**Comment by project64** [comment]
if you download the archive from pj64 alpha forum and extract to a clean dir, do you see the issue with a clean version with out changing any settings?

**Comment by LegendOfDragoon** [comment]
>if you download the archive from pj64 alpha forum and extract to a clean dir, do you see the issue with a clean version with out changing any settings?

Looks like End Emulation is more stable. Now the game always seems to end right after pressing End Emulation. Although it still has the problem (issue # 921) that if you spam F12 right after booting a game, it can crash. I think it has to do with hitting F12 multiple times between the time of the first button press and the time the emulator closes. I'm curious as to why this wasn't an issue in earlier versions. Switching games while currently running a game also doesn't work.

**Comment by project64** [comment]
yes, there is potential issue with spamming f12, still need to try to clean it up, but it is not a huge issue, 

I always end emulation then use the rom browser to select the next game, but your saying if you open game from the menu while running it will break. If I get a chance I will look at that.

**Comment by vgturtle127** [comment]
@LegendOfDragoon I am currently mostly bed-ridden due to my health issues, otherwise I would.

The reason I couldn't initially find the issues was because of other bugs, which are mostly still present on my system. I get a lot of crashing and hangs, so I have to find the issues there and fix them and then I can tackle the other issues.

**Comment by oddMLan** [comment]
Just tried the latest master, the bug is still actual.
PS: Turtle, hope the pain is over soon.

**Comment by vgturtle127** [comment]
@oddMLan Thanks, man!

**Comment by project64** [comment]
end emulation/start a new game should work. Trying to open a new game while one is running should work as well but doesn't, that I need to spend some time to work out what is going on, but not something I have time for right yet.

**Comment by vgturtle127** [comment]
@project64 OK, thank you for confirming my issues at least somewhat. I feel like I'm losing my mind with all the things that I manage to mess up with Project64. Heh.

**Comment by JunielKatarn** [comment]
2.4 milestone?
@project64 What happened to 2.3 release? Is it going to be skipped?

**Comment by project64** [comment]
@JunielKatarn  no because I will probably want to release a 2.3 build before I get to around to fixing it and it does not need to be fixed for a 2.3 release, but I would like it fixed and no missed so I still gave it a milestone so it will not be forgotten

**Comment by vgturtle127** [comment]
@JunielKatarn With all the changes lately, we could probably skip to 2.5 and everybody would be OK with it. Heh.

@project64 Is there a projected approximate date for 2.3? I am working on a bunch of stuff, I just want to remain aware.

**Comment by project64** [comment]
@vgturtle127  I am guessing 3 weeks at the very min, most likely 6 weeks, maybe a bit more

**Comment by vgturtle127** [comment]
@project64 Oh, OK. I should probably hurry my lazy ass up then. hehe

**Comment by Frank-74** [comment]
Starting a new game from recent file menu while a game is running works here.  From GLideN64 to Jabo works, and in a new session, from Jabo to GLideN64 works.

But I get a black screen when trying to run a second game with PJ64Glide or GLideN64.  I get the same result with Recent files while a game is running, or End Emulation start another game with Glide.

**Comment by Frank-74** [comment]
Hmmm.  Now I cannot switch from Glide to Jabo.  Project64 just closes without an error.  GLideN64 to Jabo is ok.  PJGlide to Jabo is not.

I guess the moon and planets have to be aligned right or something.

Still, the games do load from the File > Recent list while a game is running.

Only PJ64Glide breaks things.

**Comment by project64** [comment]
the switching between plugins is a different issue then this one right?

**Comment by Frank-74** [comment]
Yes.

This issue seems fixed.  It only crashes when switching from a game with PJ64Glide to Jabo Gfx.  No matter how you do it.  Recent file, or End Emulation > run game, or changing plugin while game is running.

**Comment by LegendOfDragoon** [comment]
I think this can be closed now. I have 0 problems with switching games now.
