### ISSUE TITLE
Overall Expansion Pak Option 

### ISSUE THREAD

**Issue by Papermanzero** [project64/project64#1042]
Currently the expansion pak must be manually instered with every game.
Furthermore it is not obvious that the memory setting within each game setting is used for the expansion pack. An overall option to enable the expansion (4MB to 8MB storage) would be great, so that every game is using the expansion pak. Similar to the plugin menu, the user can enable or disable the expansion pak in the overall setting for every game, and optionally he can disable or enable the expansion via the game settings.

**Comment by cxd4** [comment]
>Similar to the plugin menu, the user can enable or disable the expansion pak in the overall setting for every game,

There is the "overall" plugin menu, but global plugin settings will be overridden by per-ROM plugins.

It was the same way with the expansion pak option in Project64 1.6 and older, back when we were able to set a default RDRAM size option for cases where the RDB didn't specify one.

**Comment by tony971** [comment]
This should probably be moved to #457

**Comment by LegendOfDragoon** [comment]
I believe the "defaults" section does what you're asking for.

**Comment by Papermanzero** [comment]
Yes

**Comment by LegendOfDragoon** [comment]
Can you close, then?
