### ISSUE TITLE
NRage Pj64 Analog Stick issue with Xbox360 Controller

### ISSUE THREAD

**Issue by Papermanzero** [project64/project64#1043]
Using the PJ64 Version of NRage, the left or right analog stick position of the Left Analog Stick on the Xbox 360 Controller cannot be used, although the plugin saved the setting. The xinput setting is not used in this scenario.

**Comment by tony971** [comment]
Why would you use the NRage setting for a 360 controller? xinput was designed specifically for 360 controllers.

**Comment by Papermanzero** [comment]
Why not? It is also a direct input controller. So it seems the direct input is not working correctly.

**Comment by death-droid** [comment]
NRage needs a decent bit of code cleanup and fixes, might look into this at some point as i do have an xbox 360 controller on hand.

**Comment by vgturtle127** [comment]
@Papermanzero It is primarily an XInput controller, though. If you run it in DirectInput mode, I wouldn't necessarily expect anything to work as intended.

This could be a bug with N-Rage, but why not just use the XInput setting?

**Comment by tony971** [comment]
I always wondered what my comments would look like if they were said by someone else.

**Comment by vgturtle127** [comment]
@tony971 Heh. Guess I didn't read that well.

**Comment by Frank-74** [comment]
@Papermanzero 
Try moving the deadzone to around 95-98%.  This apparently works for Retrolink controllers where the analog sticks don't work.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
