### ISSUE TITLE
Config folder in different location after PJ64 folder move

### ISSUE THREAD

**Issue by Papermanzero** [project64/project64#1044]
Starting the first time P64 creates a config folder within the PJ64 folder.
However if the user moves the PJ64 folder to a different location on the HDD, the config folder within the PJ64 folder will be ignored. Instead, a config folder in the root of the HDD will be created, if the user start PJ64 again.

**Comment by JunielKatarn** [comment]
I believe the only modifiable setting is the `Project64.cfg` location.
I have dealt with this when deploying the ClickOnce installer.

I'll open an issue to discuss creating secondary `Config` and `Plugins` folders called `UserConfig` and `UserPlugins`.
This way, "official" files like the RDB or Jabo's plugin can stay next to the executable, but custom/local plugins, input config and other CFG files can be located wherever the user wants.

**Comment by vgturtle127** [comment]
@Papermanzero Just so you are aware, Project64 really isn't a portable application. It rarely works if you move it around. It also uses the registry, so there is that potential problem as well.

I hope in the future, everything will be customizable and/or self-contained.

**Comment by project64** [comment]
@vgturtle127 it should work if you move it around, now if you have set a fixed folder in the cfg it will use that and break, but by default it is portable. Nothing in the default install uses registry (yes 1.6/1.6 plugins did). But all registry code has been removed from the project.

**Comment by vgturtle127** [comment]
@project64 Was that recently that that was changed, or has it been like that for awhile? I haven't been as active lately due to health problems, so sorry about that...

**Comment by project64** [comment]
@vgturtle127 since your posting again, I hope that means you are feeling better now?

it was one of the major changes I was working when i was doing the beta version, so from 2.0 on wards.

**Comment by vgturtle127** [comment]
@project64 Unfortunately, no I don't feel better. I am still in a lot of pain daily, and my doctor said I should go to a urologist to see what is the matter. You can read the whole story here:

https://www.reddit.com/r/emulation/comments/4dyy1b/hello_everybody_turtle_here/

Anyway, basically I am still trying to find out what is wrong so that I can feel better. My mobility is a little limited and I am in pain most of the day, as I said.

But I'm hopeful I will feel better soon. :smile:

**Comment by oddMLan** [comment]
Cannot reproduce
