### ISSUE TITLE
[Feature Request] NRage - Controller Pak Switch

### ISSUE THREAD

**Issue by Papermanzero** [project64/project64#1047]
An extension to macro for Nrage to switch between the different controller paks would be a good addition. To switch from memory pak to rumble pak and transfer pak.
So it would be great to cycle trough these paks.
Maybe a defintion per game (game setting) would be also a nice extension.
e.g. To use the rumble pak with Zelda OoT and the Transfer Pak with Pokemon Crystal inserted for Pokemon Stadium 2.

**Comment by vgturtle127** [comment]
@Papermanzero There are keyboard shortcuts for this...

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
