### ISSUE TITLE
Can't map ESC to quit in shortcut

### ISSUE THREAD

**Issue by Jayme65** [project64/project64#1049]
I want to map ESC to quite in key shortcuts.
For this, I first remove ESC from the 'Full screen' key shortcut and apply (or even restart)...but it won't never let me assign ESC to 'Quit' telling me that this ESC shortcut is already used for 'Fullscreen'

**Comment by vgturtle127** [comment]
@Jayme65 Remappable keyboard shortcuts would be a nice thing to have indeed.

**Comment by project64** [comment]
maybe there is a bug ... it should work. tho that does not help you. 

@vgturtle127  all keys that are used by project64 are remappable, now it would nice if I could map them to a controller, that would be really nice.

**Comment by vgturtle127** [comment]
@project64 I thought some were protected shortcuts you couldn't change like @Jayme65 said?

**Comment by project64** [comment]
no all short cuts are changeable, If it is being used already then it will complain and not you use the same key  for different actions, just one.

**Comment by vgturtle127** [comment]
@project64 Oh, OK. That makes sense.

**Comment by SigmaVirus** [comment]
**_"now it would nice if I could map them to a controller, that would be really nice."_**

antimicro allows you to do just that:

https://github.com/WAZAAAAA0/antimicro

**Comment by tony971** [comment]
I would love to be able to map save/load states to a controller.

**Comment by SigmaVirus** [comment]
@tony971 
I'm already doing that with antimicro today, you can too!

Yeah I can understand people not wanting to have 3rd party software for this but it works great.

**Comment by Jayme65** [comment]
"I want to map ESC to quite in key shortcuts.
For this, I first remove ESC from the 'Full screen' key shortcut and apply (or even restart)...but it won't never let me assign ESC to 'Quit' telling me that this ESC shortcut is already used for 'Fullscreen'"

"maybe there is a bug ... it should work. tho that does not help you"

@project64 Did you check by yourself if it works for you..or not? I've met other people complaining of the same bug on emu forums!
Do you intend to fix it?

**Comment by LegendOfDragoon** [comment]
Has this been fixed?

**Comment by project64** [comment]
I believe yes, closing, can re-open if need be

**Comment by leigh-au** [comment]
I have found a solution to this problem.
in settings>keyboard shortcuts; reset the page
Open Project64.sc3 file in the config folder (somepath\Project64\Config\Project64.sc3)
Find the lines beginning with 4173 and delete them; save the file
Open settings and you will be able to assign the esc key to anything you like.

27 is the ASCII keycode for esc 

From my brief look over the source code, there is nothing hard coded into the settings dialog to support game controller mapping.

**Comment by vaindil** [comment]
@project64 I downloaded Project64 yesterday and I'm having this issue. Trying to remap F9 from GS button to Load State, but even though I've removed the binding from GS button the program still claims that it's in use there.
