### ISSUE TITLE
Vigilante 8 ABL\timing Issue.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#105]
Neither Vigilante 8 game works with Advanced Block Linking enabled. (Enabling it will cause a freeze during level loading.) Also, disabling the frame limiter will result in the game's main menu not triggering correctly. The screen will be frozen just before the main menu until the frame limiter is enabled. A momentary pause, and then then the main menu appears. This appears to cause issues across all the major menus and loadscreens.

**Comment by project64** [comment]
if you enable ABL also change the self mod detection to just be protected memory and it should work.

With ABL on it is not detecting the code change with the current settings.

**Comment by AmbientMalice** [comment]
@project64 Changing self mod doesn't seem to help the level load freezes. Also, the lack of responsiveness when frameskip is enabled remains the same.

**Comment by AmbientMalice** [comment]
Changing self-mod doesn't help. Game is still unresponsive with frame limiter disabled.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
