### ISSUE TITLE
Mario Story 

### ISSUE THREAD

**Issue by theboy181** [project64/project64#106]
Settings in the RDB are incorrect.

Must choose CPU INTERPRETER
or turn of Register Caching.

unsure if this is a core issue or not, but several games require these type of settings for compatibility.

**Comment by exhalatio** [comment]
Disable 32 bit Engine same as paper mario settings are also stable.

**Comment by dsx-** [comment]
fixed in 78b74bc

**Comment by cxd4** [comment]
Only the (J) version needed this change?

Is that true @theboy181 ; this issue is fixed now?

**Comment by theboy181** [comment]
works too.. thanks.
