### ISSUE TITLE
Hey You, Pikachu! VRU Emulation Support

### ISSUE THREAD

**Issue by Ecksters** [project64/project64#1064]
Bliss-Box developers have offered support for the VRU, we need to get the interface working for them though.
See here:
[http://www.emutalk.net/threads/55279-Hey-You!-Pikachu-Possible-HLE-Implementation/page4](http://www.emutalk.net/threads/55279-Hey-You!-Pikachu-Possible-HLE-Implementation/page4)
[http://forum.pj64-emu.com/showthread.php?t=5652](http://forum.pj64-emu.com/showthread.php?t=5652)

If we can get the VRU working through BlissBox, an HLE implementation through any mic shouldn't be far behind. Issue is that I don't think the controller plugins currently have support for the VRU.

**Comment by Ecksters** [comment]
Relevant code used in the VRU communication process:
```
s32 osVoiceInit(OSMesgQueue *siMessageQ, OSVoiceHandle *hd, int channel);
typedef struct {
   OSMesgQueue	*__mq;		/* SI message queue */
   int			__channel;	/* Controller port No. */
   s32			__mode;	/* Used within the OS */
   u8			cmd_status;	/* Command status */
} OSVoiceHandle;
s32 osVoiceSetWord(OSVoiceHandle *hd, u8 *word);
s32 osVoiceClearDictionary(OSVoiceHandle *hd, us words);
s32 osVoiceSetWord(OSVoiceHandle *hd, u8 *word);
s32 osVoiceStartReadData(OSVoiceHandle *hd);
s32 osVoiceGetReadData(OSVoiceHandle *hd, OSVoiceData *result);
typedef struct {
   u16  warning;		/* Warning */
   u16  answer_num;	/* Candidate number (0~5) */
   u16  voice_level;	/* Voice input level */
   u16  voice_sn;	/* Relative voice level */
   u16  voice_time;	/* Voice input time */
   u16  answer[5];	/* Candidate word number */
   u16  distance[5];	/* Distance value */
} OSVoiceData;
s32 osVoiceStopReadData(OSVoiceHandle *hd);
 //Registered Words:
u8 *registration_word[] = 	{
"yakiniku",
"mario",
     .
     .
     .
"pikachu"
```

And a flowchart of how it works:
![Flowchart](http://level42.ca/projects/ultra64/Documentation/man/pro-man/pro26/gif/f26-08-05.gif)

**Comment by LegendOfDragoon** [comment]
They completed the HLE code right? Forgot how to set it up though.

**Comment by cxd4** [comment]
Get this VRU feature implemented NOW!!!  I need to hook up my microphone to Project64 and start mingling with chicks over NetPlay without using Hey You Pikachu to do it.

**Comment by Ecksters** [comment]
Raphnet's adapter works with the VRU:
[Footage of me playing it on PJ64](https://www.youtube.com/watch?v=RYBzgQvnhIs)

You need to use GLideN64 for the graphics to not be broken, and you'll use the[ pj64raphnetraw](https://github.com/raphnet/pj64raphnetraw) plugin to connect. You'll need the dual-controller version, and there's some lag from the controller plugin.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened

**Comment by loganmc10** [comment]
FYI: https://github.com/mupen64plus/mupen64plus-core/pull/873
