### ISSUE TITLE
Have all game saves in one dir

### ISSUE THREAD

**Issue by project64** [project64/project64#1065]
At the moment we have all the native saves in one directory and all instant saves in another. This will have every games native/instant saves all in the same directory.

I was thinking of having one save dir, then under that have one dir for each game %GameName%_%GameMd5% then the save with the same name under that directory. That way everything per game is self contained and if you run two different versions with the same GameName but are different, then it will have different MD5 and will not share the same save files.

The downside is that it means if you want to use existing saves you will have to move it to the new location.

What do you think?

**Comment by cxd4** [comment]
Huh.  I thought it was already instant saves + native saves in the same directory as it stood.  Guess I just haven't ran the Windows build for a long enough while now to have remembered/noticed a change.

>The downside is that it means if you want to use existing saves you will have to move it to the new location.

Well, another downside to it would be that on, say, my desktop machine (which I could not bring with me here), I have Project64 1.x, Project64 2.x, Mupen64 etc. all share the same install locations.  Therefore, they all access the shared "Save" subdirectory.  As it stands right now, Project64 2.3 names the contents of the /Save/ subfolder the same way as Mupen 0.5 does (not 1964 tho), so I liked that I could instantly replay from the same save file on either emu.

Not sure what the MD5 issue has to do with where to place both save types though.

**Comment by dsx-** [comment]
all saves already go into the same dir

**Comment by vgturtle127** [comment]
@project64 When you say native and instant saves, do you mean memory pak saves and the emulator's saves?

**Comment by project64** [comment]
at the moment you can configure instant and natives saves to there own directories, which at default settings go to the same save dir. I think I am going to add this as a configurable option and have it off by default. 

at the moment you could have something like
* save
  * SUPER MARIO 64.eep
  * ZELDA MAJORA'S MASK.fla
  * MARIOKART64.eep
  * MARIOKART64_Cont_1.mpk
  * Super Mario 64 (U).pj.zip
  * Super Mario 64 (U).pj1.zip

with my thoughts it would be
* save
  * Super Mario 64 (U) %md5%
    * SUPER MARIO 64.eep
    * Super Mario 64 (U).pj.zip
    * Super Mario 64 (U).pj1.zip
  * zelda majora's mask (U) %md5%
    * ZELDA MAJORA'S MASK.fla
  * Mario Kart 64 (U) %md5%
    * MARIOKART64.eep
    * MARIOKART64_Cont_1.mpk

**Comment by vgturtle127** [comment]
@project64 I like that much better, do it that way. That will make it easier to find what I am looking for in my huge save directory. :smile:

**Comment by project64** [comment]
have added an option to do this (https://github.com/project64/project64/commit/02d7ac014e17df0fd1b928393a28f5ae456c5f32), but it is off by default now.

I have a bug which stops it compiling, I will fix that tonight.

**Comment by vgturtle127** [comment]
@project64 Awesome! Thanks, Zilmar!

**Comment by wfowler1** [comment]
Would it also be possible to add an option for Mupen64Plus-style save file naming? As I understand it, Mupen simply uses the file name of the ROM instead of the internal name. It'd be great to be able to point PJ64 and Mupen at the same directory and have saves work between them without renaming files.

**Comment by project64** [comment]
I am sure the internals of a mupen save file would be different from pj64 save file, not just on the file name.

as this issue is done closing now.

**Comment by wfowler1** [comment]
Actually the save files seem to be 100% interchangeable between the two emulators. Tested with an MPK file and with GOLDENEYE.eep. The only barrier to seamless compatibility would seem to be the file names.

Anyway this should probably be filed in a separate feature request.

**Comment by baptiste0602** [comment]
Mupen64plus use GoodName, not FileName
As GoodName is an arbitrary value (not choosed by user and not coded in the ROM), I think it's better to ask mupen64plus developper to add an option to use InternalName
