### ISSUE TITLE
Zelda OoT / MM does not boot.

### ISSUE THREAD

**Issue by exhalatio** [project64/project64#1074]
I used Glide64 For PJ64 plugin.
It works fine on older build, but it does not boot a new build.
I think this issue was caused in ec23b073.
![zelda](https://cloud.githubusercontent.com/assets/7089513/14916500/f1107944-0e54-11e6-9c3e-c420a025f9e0.png)

**Comment by JunielKatarn** [comment]
I'm not able to reproduce the issue with the latest build.
Try http://hyvart.com/download/project64/ci/0.0.0.448/ (built from edced1f6e6c212be281a37b0fb58d4f2fa4fd6f5).

**Comment by exhalatio** [comment]
I tryed your build.
hmm, simply change plugin to Glide64, then I load the Zelda roms to reproduce the issue.
![plugins](https://cloud.githubusercontent.com/assets/7089513/14934999/06c84ff2-0efd-11e6-9bc3-fbb5834c4886.png)
![err](https://cloud.githubusercontent.com/assets/7089513/14935000/0a3772bc-0efd-11e6-866c-9d58101ed270.png)

**Comment by JunielKatarn** [comment]
You are right. It's likely a Glide64 bug, then.
I reproduced it with the latest master commit.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/4fa189ac33d38d521f4416e6feec88b2f0f366fa fix it?

**Comment by exhalatio** [comment]
Fixed by 4fa189a.
