### ISSUE TITLE
Where is m_Callback.find() ?

### ISSUE THREAD

**Issue by cxd4** [project64/project64#1117]
Now that Project64 (UI, core and all their dependencies) builds and runs, I have been left with investigating the usual segmentation faults we first get when running freshly ported things.

The crash that the Linux executable is having flows something like this:

```
CLI/main.c:
    main(argc, argv) --> AppCleanup()
Project64-core/AppInit.cpp:
    AppCleanup() --> CleanupTrace()
Project64-core/AppInit.cpp:
    CleanupTrace() --> g_Settings->UnregisterChangeCB(/*... anything */)
Project64-core/Settings/SettingsClass.cpp:
    CSettings::UnregisterChangeCB(...) --> Callback = m_Callback.find(Type);
```

Therefore, to be specific, the Linux build keeps crashing [here, at this line](https://github.com/project64/project64/blob/dd1cf6a154b7a1a2b193186b6a8cfda5934ea9dd/Source/Project64-core/Settings/SettingsClass.cpp#L1214).

So where or what is Callback.find(), and why do we really need this C++ for AppCleanup()?

If it matters to anyone, here is some code that I used to debug in `main.c`:

``` c
    init_success = AppInit(NULL, base_directory = "./", argc, &argv[0]);
    if (!init_success)
    {
        fputs("ERROR:  Calling AppCleanup().\n", stderr);
        AppCleanup(); /* crashes within sub-calls from this procedure */
        return -1;
    }
```

**Comment by project64** [comment]
AppInit is expecting the first param to be an interface, it should be checking if it is NULL and just failing if null is passed. You need to pass an interface to AppInit

**Comment by cxd4** [comment]
Your [example](https://gist.githubusercontent.com/project64/5fc3f0a93c22ef6b9160883a31ec88a6/raw/9c35737fac64caed49e44a89eb4bd0b04ec04d77/main.cpp) used some function called Notify().

This seems to require me to ...
```c
#include "NotificationClass.h"
```

When I do that I get errors:
```c
In file included from ./../../CLI/main.cpp:8:0:
./../../CLI/../Project64/UserInterface/NotificationClass.h:54:24: error: 'CMainGui' has not been declared
     void SetMainWindow(CMainGui * Gui);
                        ^
./../../CLI/../Project64/UserInterface/NotificationClass.h:61:23: error: 'CGfxPlugin' has not been declared
     void SetGfxPlugin(CGfxPlugin * Plugin);
                       ^
./../../CLI/../Project64/UserInterface/NotificationClass.h:67:5: error: 'CMainGui' does not name a type
     CMainGui   * m_hWnd;
     ^
./../../CLI/../Project64/UserInterface/NotificationClass.h:68:5: error: 'CGfxPlugin' does not name a type
     CGfxPlugin * m_gfxPlugin;
     ^
```

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
