### ISSUE TITLE
Project64 crashes everytime when trying to launch configuration settings

### ISSUE THREAD

**Issue by SigmaVirus** [project64/project64#1119]
I recently updated my old Windows 10 (10.0.10240) to the 1511 (10.0.10586) version which is updated to 10.0.10586.318 which is the latest non-insider build I think.

Anyway on the old Windows 10 version (10.0.10240) I had no problems configuring Project64 but now on the new version I can't even configure it because it crashes right as I click Settings.

I have tried the latest from here:
http://hyvart.com/download/project64/ci/

and it even crashes on Project64 1.7.0.50 rev23 so it doesn't matter which version or build of Project64 I'm using.

It's a clean install of Windows 10 using the April 2016 update ISO and then updated to .318 through Windows Update.

I can't even use Project64 because of this and I really don't want to go back to 10.0.10240

Don't know what to do here actually.

**Comment by JunielKatarn** [comment]
Did you try debugging?
I have the same Win10 version. I'll try it later.

On Monday, 6 June 2016, SigmaVirus <notifications@github.com> wrote:

> I recently updated my old Windows 10 (10.0.10240) to the 1511 (10.0.10586)
> version which is updated to 10.0.10586.318 which is the latest non-insider
> build I think.
>
> Anyway on the old Windows 10 version (10.0.10240) I had no problems
> configuring Project64 but now on the new version I can't even configure it
> because it crashes right as I click Settings.
>
> I have tried the latest from here:
> http://hyvart.com/download/project64/ci/
>
> and it even crashes on Project64 1.7.0.50 rev23 so it doesn't matter which
> version or build of Project64 I'm using.
>
> It's a clean install of Windows 10 using the April 2016 update ISO and
> then updated to .318 through Windows Update.
>
> I can't even use Project64 because of this and I really don't want to go
> back to 10.0.10240
>
> Don't know what to do here actually.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/project64/project64/issues/1119>, or mute the thread
> <https://github.com/notifications/unsubscribe/AETGtyEdQEj-FeYhfxsP6F9R9LWHz8XHks5qJAezgaJpZM4Iuz9t>
> .
>


-- 
- Julio

**Comment by SigmaVirus** [comment]
Thanks for your reply!

No I haven't tried to debug Project64 and I have never done it before either.
How do you do it?

For those with the same Windows version as I have (10.0.10586.318) it's pretty easy to re-produce:

1. Start Project64
2. Click Options
3. Click Settings

Now 2 things could happen here:

You can configure Project64 as usual and everything is OK or Project64 crashes and Windows tells you that Project64 have stopped working and needs to close.

**Comment by cxd4** [comment]
SigmaVirus, I recommend you [PM zilmar at the forum](http://forum.pj64-emu.com/private.php?do=newpm&u=2) and ask for access to his build-bot builds.

He hands out the permission for free so people can download his automatically compiled binaries.

That is, of course, unless you have Visual Studio already installed--in which case compiling is easy.

**Comment by JunielKatarn** [comment]
@SigmaVirus I just noticed that my CI builds are corrupt (probably some bug in my zip-assembling script).
The latest stable one is: http://hyvart.com/download/project64/ci/0.0.0.464/ which is not very recent.

I have removed broken builds an will submit an updated, cleaned one promptly.

**Comment by JunielKatarn** [comment]
@SigmaVirus also, if you have some time (and disk space), here are the building instructions.
Debugging should be rather easy after that:
http://pj64wiki.com/index.php?title=Building

**Comment by JunielKatarn** [comment]
@SigmaVirus I triggered another build and got clean results.
I have Windows 10, x64, 10.0.10586.318 build.
Project64Dev (my buildbot), build 476 (http://hyvart.com/download/project64/ci/0.0.0.476/).

> 1. Start Project64
2. Click Options
3. Click Settings

I couldn't find any issues.

**Comment by SigmaVirus** [comment]
@cxd4 
Thanks for your reply, I don't have Visual Studio installed at the moment but I can try it out as a last resort.

Would 2013 with Update 4 be sufficient?

@JunielKatarn 

Thanks for your help!

OK, so you say that build 476 seems to work, I'll have to try it once I get home from work.

I can say that every build that I had lying around have triggered the crash, Project64 1.7.0.50 rev23, a couple of your builds from March and some newer ones and every single one of them worked perfectly on the old TH1 version of Windows 10.

**Comment by cxd4** [comment]
2013 would be just dandy, again if you're up to installing it.

It would still be less work to just download zilmar's tarballs at the main PJ64 forum.  It does require sending him a PM first, but the files are less likely to crash from the configuration he uses.

That being said, I certainly won't discourage you from compiling it yourself either.

**Comment by JunielKatarn** [comment]
> files are less likely to crash from the configuration he uses

They are not. They crash the same. The only different configuration is the compiler version. Zilmar uses VC2008, I use VC2015.

On that note, @SigmaVirus, if you are willing to install a VC toolset, I'd suggest you install the latest version. It's as non-lightweight as 2013 anyways.

**Comment by cxd4** [comment]
They are less likely to crash from the configuration he uses.

Whether you find they crash for this particular test is another question.

**Comment by JunielKatarn** [comment]
What configuration does he use that would make them more crash-proof?
As far as I know, he just builds Win32 platform, with Release configuration.

Are you basing the "likeliness" on any collected data, or mere fandom?

**Comment by cxd4** [comment]
>any collected data

Mhmm. :)

**Comment by SigmaVirus** [comment]
Haven't been able to test the 476 build out yet that you mentioned @JunielKatarn 
I have time tonight though so hopefully I can say if it worked or not for me.

**Comment by SigmaVirus** [comment]
It works now!

And I know what caused it, GLideN64 which is this version to be exact:
http://www.emucr.com/2016/06/gliden64-git-20160603.html

If I removed GLideN64 from the GFX folder I could configure Project64 properly.

I haven't tested the one Gonetz built himself from here yet:
https://github.com/gonetz/GLideN64/issues/885#issuecomment-220839836

I don't know if it's related to Project64 or if it's just some iffy builds from EmuCR as usual but I'm not closing this just yet.

**Comment by cxd4** [comment]
Sounds good.  I haven't actually tried that plugin, but I know a couple others have reported crashes in newer versions of that plugin, after changes to the way it communicates with the core.

**Comment by SigmaVirus** [comment]
Well I can definitely say that I'm ****** Project64 wise as I can't get anything to load even with older plugins as Glide64 Final from May 2012 and such.

Nothing Project64 wise works for me on this version of Windows 10, YAY......not.

**Comment by MELERIX** [comment]
@SigmaVirus 

Project64 (this Win32 version: http://hyvart.com/download/project64/ci/0.0.0.478/) is working fine for me in Windows 10 Build 10586.318, and even in Build 14361 (Insider Preview) is working fine too.

**Comment by SigmaVirus** [comment]
@MELERIX 
Sorry but I have tried that build too with no luck.

I can configure Project64 and the plugins I chose just fine but as soon as I load a game it hangs.

I think I have to go back to the first version of Windows 10, 10.0.10240 soon if I can't get things to work.

Or I just have to wait and try newer builds out as they come.

**Comment by MELERIX** [comment]
@SigmaVirus 

any info about the crash in Windows **Event Viewer** ?

**Comment by SigmaVirus** [comment]
@MELERIX 

Yes there is in fact some information about the crash in the Event Viewer.

Faulty module name: atlthunk.dll, version: 10.0.10586.0
Faulty module path: C:\Windows\SYSTEM32\atlthunk.dll

That's the most relevant information I can get out of it.

**Comment by SigmaVirus** [comment]
This specific issue were iffy EmuCR GLideN64 build related.
Closed!
