### ISSUE TITLE
Emulator crashes on ROM load

### ISSUE THREAD

**Issue by JunielKatarn** [project64/project64#1121]
Steps to reproduce:
1. Build or download Project64 at commit 51aad1456fe3429a747d62053debf0674b69c86e (e.g. http://hyvart.com/download/project64/ci/0.0.0.477/).
2. Open Project64.
3. Load a ROM (Currently tested with OOT, Shadows of The Empire, Smash Bros, and Lem's Test ROM).

The application will stick at "Emulation started", but nothing will happen. Eventually, the frozen window will state "(Not Responding)" and you will have to close it.
![crach](https://cloud.githubusercontent.com/assets/4507319/15845444/01e48c06-2c28-11e6-98fd-3a2e4861e932.PNG)

**Comment by SigmaVirus** [comment]
Could all these crashes have something to do with newer versions of Windows 10?

I recently updated my computer from 10.0.10240 and so far Project64 is the only emulator that have been giving me problems as you seen in my issue #1119 

Seems Project64 is very sensitive these days.

**Comment by MELERIX** [comment]
don't think so, I tested Win32 build from here: http://hyvart.com/download/project64/ci/0.0.0.478/ and is working fine, even I'm using Windows 10 Build 14352 (Insider Preview).

**Comment by JunielKatarn** [comment]
Note, @SigmaVirus and I detected problems in actual RTM updates, not Insider Previews.
Ill try my latest build, nevertheless.

**Comment by SigmaVirus** [comment]
I'm having the same problem as you @JunielKatarn, everything hangs.

I can't get any game to load or run anything Project64 wise on this Windows build at all without getting different errors.

I'm starting to give up on ever getting stable N64 emulation at all and even the Libretro core have it's own share of issues, although the emulator works and the games run.

I don't know what I should do, even my old trusty Project64 1.7.0.50 rev23 version is giving me errors on this Windows version.

Maybe I should just wait for the Windows 10 Anniversary update Redstone to be RTM'ed or something.

**Comment by JunielKatarn** [comment]
@MELERIX I tested a very recent build of Windows (RedStone). The freeze/crash still happens. I have tested different computers, so don't think its hardware/driver related.

**Comment by project64** [comment]
download  v2.3-46-gd62a1c9.zip from forum.pj64-emu.com/showthread.php?p=65551#post65551
extract it to a new directory and run that with no changes, does it crash?

**Comment by MELERIX** [comment]
tested again in Windows 10 Build 10586.318 and is working fine.

![pj64win10](https://cloud.githubusercontent.com/assets/1040116/15915860/46ba80be-2dc3-11e6-9c5e-77ea9a47aae1.jpg)

**Comment by JunielKatarn** [comment]
Could you please share some hardware specs?
Grahpics card, RAM, maybe processor model?

**Comment by project64** [comment]
@JunielKatarn  can you try the version I posted above, as this is the actual build configuration that 2.3 will be released with.

**Comment by JunielKatarn** [comment]
> can you try the version I posted above

Thanks, @project64.
However, I encountered exactly the same result in both machines (Standard Windows 10, and some insider previewo build).
I'll try yet another Win10, different machine later tonight.

Note, I don't have any tweaks, or weird setup on those machines, nor "special" hardware.
I'll post software/hardware details on these, in case someone else runs into the same issue.

**Comment by JunielKatarn** [comment]
@project64 One more question:
I take it your official 2.3 version will be based on commit d62a1c94558c42fbdbfda0ff0eaa1d237efb48d2?
Did you use any special flags or treatment for building, other than your build CMD scripts?

**Comment by project64** [comment]
@JunielKatarn  no idea what the offical 2.3 commit will be based on, something not there yet. 

I still need to add all the android code in and there may be more changes before 2.3 is released. 

no special flags, I have little things like using "git describe --tags --long" to get the git version name I use in the file names, got to embed that in to the binary.

call:
```
"%WORKSPACE%\Source\Script\UpdateVersion.cmd"
"%WORKSPACE%\Source\Script\build.cmd"
"%WORKSPACE%\Source\Script\package_zip.cmd" "%GIT_DESCRIBE%.zip"
move "%WORKSPACE%\Bin\Release\Setup Project64 2.3.exe" "%WORKSPACE%\Package\Setup Project64 %GIT_DESCRIBE%.exe"
cscript.exe "%WORKSPACE%\Source\Script\upload_beta.vbs" ...
```

**Comment by SigmaVirus** [comment]
My specs are the following:
i7 4970K
AMD Radeon R9 380
16GB RAM

Project64 have never been a problem with these specs but now all the sudden hell have broken loose.

**Comment by RibShark** [comment]
I'm using the latest insider build, and this crash is occurring for me (when using the CI build in the original post). Specs:
i5 4690
NVIDIA GeForce GTX 970
8GB RAM

Occasionally after the initial hang the ROM will load without any "not responding" messages appearing, but most of the time it will stop responding.

**Comment by death-droid** [comment]
Im running into the same problem as well, only recently started happening oddly enough. Im running on the latest insider build as well.

**Comment by SigmaVirus** [comment]
I can confirm that this hang/issue problem is also occurring on my older Windows 10 (10.0.10240) version which I freshly installed a couple of hours ago.

I can configure Project64 (0.0.0.478) and the plugins just fine but as soon as I try to load a game nothing happens and the emulator hangs and I have to force close it.

Older versions of Project64 (which I had from March) seems to work fine but why wouldn't they as they worked back then.

I have no idea what could be causing this and why some can play games and some getting hangs and crashes.

**Comment by SigmaVirus** [comment]
Got an update on this.

Seems like 0.0.0.464 from the 14th of May somewhat works as I can configure Project64, the plugins and load games properly.

However, and this is a strange one and a new issue altogether I think.
The sound/music stops playing whenever I go to fullscreen (Alt+Enter) and it never returns even if I go out to windowed screen again.

And on top of that cake, Project64 always crashes whenever I try to end the emulation.

According to the Event Viewer the faulting module is ntdll.dll

This was tested on Windows 10 (10.0.10240)

So for this specific issue (1121) something must have happened between 0.0.0.464 and 0.0.0.478

**Comment by SigmaVirus** [comment]
I have returned to 10586 and updated to 10.0.10586.420 and it's still the same with this issue but I'm now using a build from March this year instead that seems to be super stable so I'm probably going to use that for a longer future.

I'm also using the stable AMD drivers 16.3.2 and everything is working perfectly sound wise too.

And with Gonetz latest from GLideN64 issue 885 the graphics department have never been better so it seems N64 wise I'm set.

**Comment by wfowler1** [comment]
I'm getting this issue as well on Windows 10. Just did a fresh build and it crashes when starting a ROM.

**Comment by AmbientMalice** [comment]
I can confirm a version of this. It doesn't crash, but sometimes when booting a game, nothing happens.

**Comment by cxd4** [comment]
Anybody have differences if setting games to use the interpreter core instead of the re-compiler?

**Comment by Frank-74** [comment]
I'm getting this with Windows 8.1.  It hangs on a black screen before emulation starts.  All games are affected.

Going into Edit Game Settings before running a rom seems to be a work around for the moment.

**Comment by Frank-74** [comment]
Seems to be fixed now.

**Comment by SigmaVirus** [comment]
@Frank-74 
Is it totally fixed? And what commit fixed it?

**Comment by Frank-74** [comment]
@SigmaVirus 
It never gets stuck on Emulation Started now.

Not sure which commit fixed it.  Maybe https://github.com/project64/project64/commit/febb99305b86ecaf1b539fc984fc8dcb531c4fd9 , or https://github.com/project64/project64/commit/433c76446bbd5f911d201858897ad6605209a597 ?

**Comment by SigmaVirus** [comment]
OK, cool!

Guess I'll try it out this weekend.

**Comment by MELERIX** [comment]
@Frank-74 @SigmaVirus 

maybe this: https://github.com/project64/project64/pull/1137

**Comment by SigmaVirus** [comment]
Wow, that commit change was really small but if it truly fixed the issue it doesn't matter how big or small it was.

Thanks!

**Comment by cxd4** [comment]
Smallest fix is always the best fix.

**Comment by SigmaVirus** [comment]
Can this be closed now? Anybody still got issues?

**Comment by JunielKatarn** [comment]
Woah, this was resolved ages ago (more like six months).
Closing...
