### ISSUE TITLE
CPU Recompiler regression. The World is Not Enough audio stuttering.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#1125]
The sound stutters with the CPU recompiler now. And it's much worse with fixed audio timing enabled.

**Comment by LegendOfDragoon** [comment]
Probably just ABL causing stuttering. You sure it's a regression though?

**Comment by AmbientMalice** [comment]
It only happens when Register Caching is enabled. I'm 99% sure it's a regression because this game has always used Fixed Audio Timing to help with its speech.

**Comment by LegendOfDragoon** [comment]
I see what you're saying. Only seems to affect Jabo's audio.

**Comment by AmbientMalice** [comment]
No other audio plugins are affected, as far as I can tell. It reminds me of the juddering audio in the text crawl of Rogue Squadron with Jabo that re-emerged a while back.

**Comment by LegendOfDragoon** [comment]
It probably is an issue with Jabo's audio plugin. The weird thing is that cpu Interpreter also has the stuttering, but like you said, disabling register caching gets rid of the problem. I'll try to spend a little more time to see if I can come up with a reasonable solution. If not, maybe I'll invest into writing an open source audio plugin for PJ64.

**Comment by oddMLan** [comment]
Only happens with Jabo's DirectSound, which is deprecated.
