### ISSUE TITLE
Input issue in Shin Nihon Pro Wrestling Toukon Road - Brave Spirits (J)

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#1126]
I can't get past this menu 
![image](https://cloud.githubusercontent.com/assets/10492645/16281574/de967a26-3879-11e6-9b5e-ab2058821177.png)

**Comment by Nekokabu** [comment]
No promrems.
Are you using what controller plugin?
![image](https://cloud.githubusercontent.com/assets/11252775/16357250/e102a712-3b2b-11e6-8359-8979f22871da.png)

**Comment by LegendOfDragoon** [comment]
I tried both Nrage 2.4 and Jabo 1.6.1

**Comment by exhalatio** [comment]
Check your game settings.
Set delay SI to past this menu.

**Comment by LegendOfDragoon** [comment]
Thanks, doing tat worked. I didn't think to try that setting since 1964 didn't require it.

**Comment by project64** [comment]
is the delay SI in the rdb ?

**Comment by LegendOfDragoon** [comment]
>is the delay SI in the rdb ?

It appears to be enabled in the rdb. Not sure why it was off for me.
