### ISSUE TITLE
Unhandled R4300i opcode in 64DD emulation

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#1138]
When enable Debugger, some error after N64 logo in 64DD emulation.
Error will be displayed in any disk image.

///////////////////////////
CX86RecompilerOps::LW_KnownAddress
Failed to translate address: A4600004
![e1](https://cloud.githubusercontent.com/assets/11252775/16653242/a122ce98-448a-11e6-83b5-51ea67886a75.jpg)

///////////////////////////
CX86RecompilerOps::SW_Const
trying to store AAAAAAAA in A5000520?

///////////////////////////
Unhandled R4300i opcode at: 80278BA0
mtc0 a0, Cause

Stopping Emulation !
![e2](https://cloud.githubusercontent.com/assets/11252775/16653250/acc46e46-448a-11e6-9545-49e3dabc921d.jpg)
![e3](https://cloud.githubusercontent.com/assets/11252775/16653252/adfcdac8-448a-11e6-9d92-55a9fd075b59.jpg)

///////////////////////////
Break point found at
N64System\Interpreter\InterpreterOps.cpp
2813
///////////////////////////
Break point found at
MemoryExceptionFilter.cpp
40
///////////////////////////

**Comment by Nekokabu** [comment]
Add 0x04600000-0x0460000C to LW.
https://github.com/project64/project64/pull/1153
Please check this implementation..:p

**Comment by Nekokabu** [comment]
Add some of the 64DD Registers to SW_Const https://github.com/project64/project64/pull/1156

**Comment by vgturtle127** [comment]
@Nekokabu So with those two fixes is the problem resolved, or does it need more to fix the issue?

**Comment by Nekokabu** [comment]
"Unhandled R4300i opcode at: 80278BA0" are not fix yet.

**Comment by vgturtle127** [comment]
@Nekokabu Does it work in the recompiler?

**Comment by cxd4** [comment]
If it happens in both you could probably nag @LuigiBlood to see if he cares to look into it.  I don't run DD.

**Comment by vgturtle127** [comment]
@cxd4 I checked the datasheet and can't find what it is pointing to, unless mtc0 is actually just a COP0 instruction? I thought that's how mfc0 was handled as well. *shrugs*

**Comment by LuigiBlood** [comment]
The issue is 64DD related, but it's not a 64DD issue. It's a CPU emulation issue. I don't fully understand MIPS yet so...

**Comment by cxd4** [comment]
>unless mtc0 is actually just a COP0 instruction?

Really?  Is it possible that mtc0 is just a COP0 instruction?

Gee, I really thought it could have instead been...hm...er, wait, what did you suppose it was?

**Comment by vgturtle127** [comment]
@LuigiBlood That's kind of what I was getting at.

@cxd4 Yeah, basically those instructions are handled the same, at least from what I recall about them. They aren't identical obviously, but from what I remember MTC0 and MFC0 utilize the COP0 in some way or something. I don't know, maybe I'm wrong. They move things to/from the coprocessor, I think.

**Comment by cxd4** [comment]
Let me know.  If you find out what those two instructions do you could make $1000000 emu.

**Comment by Nekokabu** [comment]
I reviewed this problem again.
It was fixed in the latest version.
(It was fixed by someone with a commit after #1156.)
Thank you, everyone:)
