### ISSUE TITLE
"Unknown memory action" at start with some games

### ISSUE THREAD

**Issue by baptiste0602** [project64/project64#1139]
PJ64 crash when I start some games : 
- 1080 Snowboarding
- F-Zero X
- Zelda Majora's Mask

No problem with other games such as Goldeneye, Banjo, Zelda OOT, ...

Tested with latest PJ64 (build by myself) and several graphics and rsp plugins.
I don't know when this bug happen for the first time (hard to find because #1121), but it was OK with "hyvart 0.0.0.464" build.

Project 64.log : 
2016/07/03 20:39:05.287 03172,Error,Exception Handler,CMipsMemoryVM::FilterX86Exception,Invalid memory adderess: 41BF0000
2016/07/03 20:39:05.287 03172,Error,User Interface,CNotificationImp::DisplayError,Unknown memory action

**Comment by LegendOfDragoon** [comment]
Looks like zilmar added some breakpoints to exception handler.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/ca9a85241a96d5f36e2b7ea780f18382d1fbb3e0 help?

**Comment by baptiste0602** [comment]
Yes, it's OK now.
Thanks !
