### ISSUE TITLE
Mempak missing/not loaded problem

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1141]
To reproduce follow these steps.  First you need to save a Career in Monaco Grand Prix.  Close Project 64.

Start Project 64.  Run GoldenEye.  End Emulation.  Run Monaco Grand Prix (U).  Try to load a saved Career.  No Save Game Found!

Start Project 64, Run Monaco Grand Prix first works fine.

I used latest Alpha v2.3-95-gcb6fd2a.

**Comment by Frank-74** [comment]
Another one.

Start PJ64, Start Goldeneye, End Emulation, Start TWINE, Load game and you get this?
![glide64_twine_01](https://cloud.githubusercontent.com/assets/11056843/16649720/2863cbf4-4432-11e6-99b5-4ec0a665347d.png)

Why would TWINE load the Perfect Dark MemPak?

**Comment by project64** [comment]
https://github.com/project64/project64/commit/676be8fcdc09ca37a6771ad1ef2f95e8178964bb does this fix it?

**Comment by Frank-74** [comment]
Yes, it's fixed.
