### ISSUE TITLE
Zelda OoT Unknown memory action

### ISSUE THREAD

**Issue by jjjustinleblanc** [project64/project64#1144]
Running any version of Ocarina of time (v1.0, v1.2, etc) gives "Unknown memory action" error when trying to load ROM. Switching to interpreter fixes the problem, but makes the game unplayably slow for me. Graphics is Intel HD4000. Tried numerous other ROMs and they all loaded fine; only having this error when trying to play Zelda OoT.

**Comment by Frank-74** [comment]
@jjjustinleblanc 

Turn Register caching off.

I'm not sure if the rdb should be updated with this yet.  As it may be a regression with register caching that needs fixing.

**Comment by LegendOfDragoon** [comment]
>I'm not sure if the rdb should be updated with this yet.

Definitely not. Register caching on, is generally more accurate than off, based on the current code.

>I only know of OoT and TWINE that has a problem with register caching so far. TWINE has stuttering audio with Jabo when register caching is on.

I'm almost certain the audio issue in TWINE is caused by Jabo's audio plugin. Jabo's has audio issues in multiple musyx games. Turning off register caching may solve the audio issue in TWINE, but not even using interpreter fixes it.

**Comment by oddMLan** [comment]
If you turn off Register Caching you might as well use an Interpreter, because RC is the optimization that provides the Recompiler with the biggest speedup.

**Comment by project64** [comment]
I believe I know how to fix this, will put a fix in tonight.

it should just be checking that g_DDRom is not null at: 
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Recompiler/x86/x86RecompilerOps.cpp#L3269

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/35c64e5d167c86de48922bb9372fec3f44b30779 fix it?

**Comment by Frank-74** [comment]
Yes, its fixed.

**Comment by jjjustinleblanc** [comment]
Anybody care to compile this and post a link for me to test and make sure it's fixed with my configuration?

**Comment by Frank-74** [comment]
@jjjustinleblanc 
Here you go: https://dl.dropboxusercontent.com/u/9498358/n64/project64.zip

**Comment by jjjustinleblanc** [comment]
Confirmed fixed on my end @project64 . Thanks for providing a copy to test @Frank-74
