### ISSUE TITLE
Rat Attack Interpreter crash/regression

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1145]
Starting Rat Attack with Interpreter (and debugger enabled) gives me this,
`Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Interpreter\InterpreterOps.cpp
1334`

Also using Recompiler, trying to change gfx plugin (Jabo 1.7 to Jabo 1.6.1) when the game is running gives me this,
`Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Recompiler\CodeBlock.cpp
465`
and,
`Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Recompiler\CodeBlock.cpp
232`
This error also happens if you try to run the game with Protect memory enabled.

**Comment by cxd4** [comment]
IIRC that ROM only worked on 1.6 if you hacked the counter factor to some specific thing or w/e.

**Comment by Frank-74** [comment]
Aren't games that work on a real console, but break emulation, the most useful to improving emulation?

**Comment by Frank-74** [comment]
Mind you, I'm not sure if the Rat Attack rom would work on a real N64 if dumped back to a cartridge.
The Good Name is Rat Attack (U) (M6) [!].  What does the M6 mean?  Has it been hacked in some way?

**Comment by project64** [comment]
the break point is shown when debugger is enabled, if you disable the debugger option how is it then?

**Comment by Frank-74** [comment]
Its ok with Interpreter and debugger off.

But still get the other 2 errors if Protect Memory is enabled, OR, when changing gfx plugin.

**Comment by cxd4** [comment]
>Aren't games that work on a real console, but break emulation, the most useful to improving emulation?

I have no doubt.  I just meant, pj64 1.6 was the only way I remembered this ROM ever working.

I'm sure it works on a real N64 as well; I didn't think it was hacked just because most emulators don't run it.

**Comment by oddMLan** [comment]
Duplicate #641
