### ISSUE TITLE
Ocarina of Time. Overlapping floor textures with Glide64. 

### ISSUE THREAD

**Issue by Yui12** [project64/project64#1149]
The video pretty much explains the issue. I'm using the latest build 32bit of Project 64. I don't know when this regression started. 

https://mega.nz/#!4MwxgbYD!0_ANb8rpHpEshucVR08RqDuVcc6pgADi8hSGXeCd-_o

Core i3-3200
Geforce GT 640

Just in case though I don't think it's my problem. I used default settings and so forth.

**Comment by Frank-74** [comment]
Just tested myself with latest build and default settings and plugins.

I don't get the same problem as your video.  It looks good here.

Here is my build, the only difference between this and the current master, is I've removed forced flushing saves to disc for all save types.  So that Windows handles it instead.
And I have my favourite plugins in the archive too.  The RDB in the root folder is for Jabo's 1.6.1 D3D plugin only.

https://dl.dropboxusercontent.com/u/9498358/n64/Project64.zip

**Comment by Frank-74** [comment]
The only thing I have is path textures disappear when I get near to them with Jabo.  But PJ64Glide is ok.

**Comment by Yui12** [comment]
I'm not worried about other plugins since they don't have this problem, but just Glide64. I tried your build and I still get the same problem. No I didn't overwrite it with mines either. I reported it since I thought it was a regression, but it is something going on on my end.

**Comment by Frank-74** [comment]
I've been running around for a while and found a spot where I get something similar.  But it's not as severe.
![glide64_the_legend_of_zelda_02](https://cloud.githubusercontent.com/assets/11056843/16709996/6f94cbf8-4618-11e6-8d60-518485c4787a.png)

It only happens to the path textures.  At certain angle/distance.  The path gets clipped.

**Comment by Yui12** [comment]
Yeah, that is what I was talking about. I think I wasn't clear enough.

**Comment by Frank-74** [comment]
It does appear to be a regression in PJ64Glide.  This never happens with Glide64Final.  I was at a spot with the path being clipped, and I went into options and changed plugin to Glide64Final.  Problem immediately disappeared.

**Comment by Yui12** [comment]
Glide64Final has a strange glitch where Link's hair has textures from the Deku Shield for some reason, but the only way to fix this is by turning off hardware framebuffer which will cause the sub-screen to delay when pausing. I'll post it in a second.

**Comment by Yui12** [comment]
This is from Glide64Final, so using Glide64final has it's issues as well.

![untitled](https://cloud.githubusercontent.com/assets/13986398/16710261/433e8912-45dd-11e6-91de-f1ca3d592c79.png)

**Comment by Frank-74** [comment]
Hmmmm, I don't get that with Glide64Final.  This is the same place.
![glide64_the_legend_of_zelda_03](https://cloud.githubusercontent.com/assets/11056843/16710302/9eed6370-4621-11e6-8e6d-567b1ac46b47.png)

**Comment by oddMLan** [comment]
Try enabling Software Depth Buffer in PJ64Glide. Does that fix it?
If so, it should be enabled in the RDB for this game (and all the regions) only.

**Comment by Yui12** [comment]
It has already been enabled.

**Comment by AmbientMalice** [comment]
I'm guessing it's probably caused by https://github.com/project64/project64/commit/5b82ca80da2386b962a8744001c0f6209e116365

That particular fix has some side effects. libretro has an additional per-game depth setting that is used as a workaround.

As for the ground, it's a quirk on the real N64. Road textures disappear when close to the camera. Most HW plugins have hacked their way around it.

**Comment by Yui12** [comment]
I played this game too many times to count on a real N64 and I don't remember this at all. Even the real N64 footage that I could find on youtube doesn't show this texture problem.

**Comment by Frank-74** [comment]
Yes, I reverted it and it's fixed the clipping issue in OoT.
https://dl.dropboxusercontent.com/u/9498358/n64/PJ64Glide64.zip

@Yui12 
Cheats have were disabled for all except PJ64Glide and Jabo plugins.  So I don't think the RDB subscreen cheat fix is working on Glide64 Final.  I think it will work if you edit the RDB entry and add Glide64 'Final' to the CheatPlugin0 entry for OoT.

**Comment by AmbientMalice** [comment]
@Frank-74 Do you wanna make a PR to revert it, or should I?

**Comment by Frank-74** [comment]
@AmbientMalice 
You can do it, I'm knackered, it's 2:20 am here.  Cheers...!

**Comment by Yui12** [comment]
Alright everyone. Thanks. That fixed everything. The revert, and adding Glide64 final to the Project64.rdb fixed all the problems I stated above.
