### ISSUE TITLE
save sate crash

### ISSUE THREAD

**Issue by theboy181** [project64/project64#115]
unable to load any save states with last updated .exe

getting Unknown memory option error msg.

using Azimers Audio v0.70. I have been informed that this audio breaks save states, but this plugin and the .exe from a few days ago there were no issues.

**Comment by project64** [comment]
is the state loadable in 2.1 ?

**Comment by LegendOfDragoon** [comment]
Not much can be done until Azimer's Audio 0.70 goes open source.

**Comment by cxd4** [comment]
Not really.  Azimer would most likely update the plugin himself assuming it really was his fault.

After all if it used to work in an older version of the EXE, then not all blame necessarily falls on him.

**Comment by project64** [comment]
well changing from azimers to another audio plugin, if save state have isssues then you know it is Azimer's Audio fault.

Is the issue in creating the save or in loading it, is it in all saves or just one with certain characteristics.

Can you load a save correctly that was made in 2.1, the save created in 2.2 does it load in 2.1.

is it all games, or just one in particular.

**Comment by cxd4** [comment]
If you haven't ever seen a more accurate plugin have a conflict with a less accurate core before then yeah sure I guess.

Who knows, it's possible.  I don't know the plugin either since none of us can look at it.

**Comment by theboy181** [comment]
Loading a a save state from SSB with AZIMER's AUDIO v0.70 and the release on 20th give an error. the release I compiled on the 16th does not. Im not sure what build that is sorry.
![capture1](https://cloud.githubusercontent.com/assets/9299743/6315836/78780230-b9c4-11e4-838f-ea13b8c90a0e.PNG)


I notice that SSB with the current RDB settings and AZIMER audio leads to a break error, where using Shun's doesn't.
![capture](https://cloud.githubusercontent.com/assets/9299743/6315841/97c6a66e-b9c4-11e4-92aa-bb75baa06182.PNG)

**Comment by project64** [comment]
what about with the default audio plugin ?

**Comment by theboy181** [comment]
working in both 1.7, and 1.6 audio.

But its still weird that the saves were working on the version I compiled on the 16? (except the new challenger break crash)

**Comment by Frank-74** [comment]
I think its because of the Rom Opened bug being fixed.  Azimer had trouble with the thread not being closed with 2.1, so attempting to start another game crashed Project64, so he made a workaround to stop it crashing, now the workaround is not needed its causing problems.

**Comment by theboy181** [comment]
Hmm.. Good observation. I think we need to hex edit that shit then.. :) Alternatively, would be nice to see Azimer back in action with an updated release, or even better ----   source code   ----

**Comment by LegendOfDragoon** [comment]
>Not really. Azimer would most likely update the plugin himself assuming it really was his fault.
After all if it used to work in an older version of the EXE, then not all blame necessarily falls on him.

It's just such a pain debugging stuff that you don't have the source to. So I feel it's not worth the time, since save states still work with other audio plugins. The most I'd be willing to do is test a few ideas.

So far, I was able to load save states with WIP2, but not WIP4.

**Comment by cxd4** [comment]
Interesting.  So it sounds like Azimer went to some last-minute lengths to cover up for some problems in the plugin spec's end.  I'm sure that's reversible for a later time, but he is busy now.

**Comment by LegendOfDragoon** [comment]
Looks like my commit was what caused the change. So for w/e reason, Azimer's XA2 WIP4 needs m_RomOpen to be false.

RSP's need it to be true, so there's a problem with the current plugin spec design.

**Comment by theboy181** [comment]
So this is a step forward in the emulator, but a step back for Azimer's audio plugin. Should I close this?

**Comment by cxd4** [comment]
http://rs2img.memecdn.com/wynaut_c_107405.jpg

**Comment by project64** [comment]
if it only effects just Azimer's Audio plugin.. then you probably can close it

**Comment by theboy181** [comment]
closing issue.  Hope that WIP 5 is in the works.
