### ISSUE TITLE
Last ROM is not highlighted in ROM Browser

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1157]
After End Emulation, the highlighted/selected ROM doesn't change.  Have to refresh the ROM list everytime.

**Comment by project64** [comment]
should be an easy fix, just not looking at it my self right now, but I do not want to forget it about it so marking it for 2.4

**Comment by Frank-74** [comment]
Fixed with latest master.

**Comment by Frank-74** [comment]
Damn, it worked ok the first time I ran the latest master.  After closing and reopening Project64, it's broke again.

**Comment by Frank-74** [comment]
This bug first appeared on the 14th April.
