### ISSUE TITLE
[Feature Request] NRage > Windows Calibrate Controllers

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1160]
Could a button be added to open joy.cpl?  So we can open the Windows Game Controllers control panel to test and calibrate the controller.

Windows 8 doesn't have a link to joy.cpl in my control panel.  I have to do a search for joy.cpl and run it from there.  Or manually create a shortcut to System32/joy.cpl.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
