### ISSUE TITLE
Monopoly (U) (M2) occasional freeze.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1161]
Sometimes near the end of a game, the display freezes.  Audio still plays, but video and controls are unresponsive.  Usually on a close up of an opponent about to make a turn/roll dice.

It doesn't happen very often.  Maybe 1 in 3 or 4 games.

Frozen savestate.
https://dl.dropboxusercontent.com/u/9498358/n64/Monopoly%20%28U%29%20%28M2%29.pj.zip

**Comment by project64** [comment]
does this happen with the interpter to?

**Comment by Frank-74** [comment]
I haven't tested too much.  Had the freeze happen about 3 times and found it annoying.

Will switch to interpreter and play a few games over the next couple of days.  Games can be long, and it doesn't allways freeze with default settings.

I'll know if it does it with interpreter after i've played 6 or 7 games.

**Comment by Frank-74** [comment]
Managed to play two full games using Interpreter CPU without a freeze.  Couldn't stand to play again at such a slow speed (25-30 VI's), so changed Recompiler to Virtual lookup table and unchecked all the self mod methods.  Six or seven games later, no more freezing.

Shall I do a PR to change the RDB settings?  Or leave this issue open and wait for a fix to the Physical lookup table and self mod methods?  Though narrowing down the cause to fix it is difficult.

**Comment by LegendOfDragoon** [comment]
>Shall I do a PR to change the RDB settings? Or leave this issue open and wait for a fix to the Physical lookup table and self mod methods?

I would hold off on doing that. I or @project64 could debug it and figure out a solution. If it's not fixed within a week or two, then perhas the rdb can be changed.

**Comment by project64** [comment]
@LegendOfDragoon I am not going to have any time to look at it for a while

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon I am not going to have any time to look at it for a while

Alright then. I guess i can briefly look at it myself then.

@Frank-74 what's the most consistent way to reproduce it? Idk how to play the game, so im just pitting 2 cpus against each other :smile: .

**Comment by Frank-74** [comment]
@LegendOfDragoon 
I couldn't find any way to reproduce it.  It allways happens randomly.  I had a save that was just before a turn where it froze.  But loading back the save state doesn't mean it will freeze again at the same place.  Could be another few moves or the game can finish before it happens.

Very frustrating trying to catch it just before a freeze.

Anyway, it allways happens after the CPU players animation, and just before a CPU player throws the dice.

**Comment by project64** [comment]
it could be memory has been modified and loading a save state will reset it so the self modifing method it has is wrong/needs something else.

**Comment by cxd4** [comment]
You can also try with register caching and advanced block linking disabled; those are both recompiler things.

**Comment by Frank-74** [comment]
I've not had any freezes with CPU vs CPU games.  Just played about 4 CPU vs CPU games with frame limiter off.

It seems to work well with Virtual lookup table and all self mods disabled.  It's getting very boring playing this game over and over again.

**Comment by LegendOfDragoon** [comment]
I kinda give up on trying to reproduce the issue :smile: . I think it's best not to change the rdb settings for the moment, because this could potentially be bug that needs to be fixed, rather than a settings issue. Let's at least wait until others can consistently reproduce the issue.

**Comment by Frank-74** [comment]
> I kinda give up on trying to reproduce the issue

Me too.

Incidentally, Monaco Grand Prix (U) sometimes freezes in the same way, after crossing the line to finish a grand prix and then pressing A when the times/position start to be displayed.

**Comment by LegendOfDragoon** [comment]
>Monaco Grand Prix (U) sometimes freezes in the same way, after crossing the line to finish a grand prix and then pressing A when the times/position start to be displayed.

Maybe I'll take a look at this game instead.

>I tried quick saveing between every turn, until the crash happened. On loading the save, it continued without the expected crash.

Hmm, That is interesting. I take it, you're using fixed audio timing right? Also what plugins are you using? Maybe i need to use specific plugins to trigger it.

**Comment by Frank-74** [comment]
I used PJGlide for gfx and default plugins everything else.  Default settings, fixed audio on, sync audio off, ai=0.

**Comment by Frank-74** [comment]
I zipped up a quick save after it froze here.
https://dl.dropboxusercontent.com/u/9498358/n64/Frozen_Monaco%20Grand%20Prix%20%28U%29.zip

Here's a quick save just before crossing the line.  The freeze above happened after crossing the line and then pressing A.  But it doesn't happen very often.
https://dl.dropboxusercontent.com/u/9498358/n64/Monaco%20Grand%20Prix%20%28U%29.pj.zip

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Maybe savestates are no help if the memory is reset upon loading a savestate.

Maybe the freezing is because of corrupt memory, and saveing/loading fixes/hides it.

Maybe this is relevant: http://forum.pj64-emu.com/showthread.php?p=66055#post66055

**Comment by project64** [comment]
most like some type of self mod happening, loading a save state reset recompiler code so it would fix the problem.

**Comment by Frank-74** [comment]
If I change Monaco Grand Prix to Virtual lookup, and switch off all the self mod methods, it throws an unhandled R4300i opcode error.  Enabling Protect memory and it works.

**Comment by Frank-74** [comment]
I've had no freezing issues for months.  Played Monaco Grand Prix lots, completed several seasons.  No more freezing issue.

Don't know what fixed it but it's no longer an issue.
