### ISSUE TITLE
1080 Snowboarding: Crowd static during Air Make course. Sometimes causes crash on platform jump.

### ISSUE THREAD

**Issue by Yui12** [project64/project64#1162]
Strangely, the problem goes away only first retrying then after playing the course the first time trying it again a second time. I hadn't tested any other sound plugins since I don't have anything else as of late. Jabo 1.6 sound plugin has the same issue, but without the chance of it crashing I think, but I could be wrong.

![1080 error](https://cloud.githubusercontent.com/assets/13986398/16932365/c5bd075a-4cfa-11e6-8e7c-3c1b66b54ded.png)

**Comment by LegendOfDragoon** [comment]
Still an isue?

**Comment by Yui12** [comment]
Had not tried the latest version of GlideN64 due to regressions that sound bad, but the problem seems to be gone after testing for 10 minutes. I'm using an older build. I think it is called rev. 41b0bffe. Should close it then .
