### ISSUE TITLE
Banjo-Tooie Always Freezes at Same Spot

### ISSUE THREAD

**Issue by HeroOfTheWastes** [project64/project64#1163]
I have been using Project 64 for a while, and have never had problems with Banjo-Tooie. Well recently, I have found that whenever I enter the Prison Compund in the Mayahem Temple level and walk about 5 feet foward, the screen freezes, but the audio keeps playing. My computer doesn't freeze, but the game's video does. I haven't went to any other levels but Mayahem Temple and everything else before it, but every other area I have gone to does not freeze but that one spot. I have tried messing with some plugin settings, but can't seem to get anywhere with it. So, at this point I have no idea what to do, and would greatly appreciate any help 

I forgot to mention that when I try to move my character when the freeze is happening, I don't hear footsteps like I usually do; the music just keeps playing like usual and that is the only noise. I can also reload a save state that I made just before the freeze, and the game plays like normal until I go to that spot again.

**Comment by HeroOfTheWastes** [comment]
Here is the save that is right before the prison compound: http://www.mediafire.com/download/o6qpd9xigt7377o/Banjo-Tooie_%28U%29.pj9.zip

Just in case you want to see what I'm seeing, I made a video: 
https://www.youtube.com/watch?v=z7F8A2IawUI

**Comment by Frank-74** [comment]
I cannot load the save.  I get fatal error, stopping emulation message.

When did saves change, so I can build an older version to load that save?

@HeroOfTheWastes 
Here is the latest version 2.3 from here.
https://dl.dropboxusercontent.com/u/9498358/n64/Project64.zip

If you can try the newer version and see if it freezes at the same spot.

**Comment by Frank-74** [comment]
I used a warp cheat to get to the Prison Compound in Mayaham Temple.  Made a quick save on entering.
https://dl.dropboxusercontent.com/u/9498358/n64/Banjo-Tooie%20%28U%29.pj.zip

No freezing here.

**Comment by LegendOfDragoon** [comment]
@HeroOfTheWastes can you confirm whether this is still an issue?
