### ISSUE TITLE
Problem with RSP Divide instructions

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#1164]
With PJ64's RSP interpreter it looks like this in Super Smash Bros
![image](https://cloud.githubusercontent.com/assets/10492645/17124728/0ed556e8-52a2-11e6-87f6-31b31f8dd541.png)

On the console after disabling antialiasing and dither, there's a dot on kirby. The dot is also present with RSPs that have a much different algorithm for the divides. Here's what it looks like with a different RSP.
![image](https://cloud.githubusercontent.com/assets/10492645/17124770/61ffb96c-52a2-11e6-84b0-3f2e0d1c5939.png)

Interestingly, the dot is never present when VI filters are enabled.

**Comment by project64** [comment]
which particular instruction .. maybe I can write a test for it

**Comment by LegendOfDragoon** [comment]
You can start with testing VRCP

**Comment by cxd4** [comment]
The filters totally interpolate with neighboring pixels' coverage levels, so it's not surprising.

>On the console after disabling antialiasing and dither, there's a dot on kirby.

How do you see that it's on the console if there are VI filters in the way?  After all, your screenshot is of an emulator, so looking at the game on a real N64 would not show you the dot.  Did you use a GameShark to grab the frame buffer or something?

**Comment by LegendOfDragoon** [comment]
>Did you use a GameShark to grab the frame buffer or something?

There are gameshark codes for disabling some VI filters.

**Comment by cxd4** [comment]
Well that's not what I idealized, but yes there are.

Barring retroben, who would post that kind of thing though?  Or did you test values of VI_CONTROL_REG in 32-bit searches using Project64?

**Comment by theboy181** [comment]
I did the testing on the real HW. Using http://retrorgb.com/n64blur.html suggestion to turn off the filters.

**Comment by theboy181** [comment]
Bump.

This is minor, but is it possible to investigate this ? Other RSP's have corrected this in their RSP's.

My testing looked accurate to the real HW. Unsure if the changes from the other developers are correct or not though.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
