### ISSUE TITLE
F3 Screenshots don't use ROM or Good Name anymore.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1165]
Screenshots are just called snap0000, snap0001 now.

Wasn't it better using the Good Name?

**Comment by cxd4** [comment]
Screenshot file names are controlled by `CaptureScreen()` in the graphics plugin calls from the core.

You probably don't change plugins very often and notice the default first-party plugin change from Jabo's Direct3D to some other thing (I guess Glide).
