### ISSUE TITLE
Android Recompiler Issue Collection

### ISSUE THREAD

**Issue by retrobenny** [project64/project64#1166]
Please post your issues here if we don't already have it listed so the devs can squash these bugs in a quicker fashion,I will start. Edits will come if other issues arise,which is very possible.
My test device is a **Shield TV Pro**.

**Recompiler**;

Banjo-Tooie (U): Runs,crashes randomly whenever it wants.
Conker's Bad Fur Day (U): Crashes to menu.
ClayFighter 63 1-3 (U): Runs well,End Emulation hanged once.
Donkey Kong 64 (U): Runs,crashed at DKTV.
Glover (U): Runs,oddly certain direction movement not working but can tap Z to cartwheel that way.
Glover 2 (U) (Beta):Runs,same issue as Glover but worse.
Kirby 64 The Crystal Shards (U): Runs,currently unplayable,needs d-pad for playing/further testing.
Legend of Zelda Ocarina of Time: Instant crash. ):
Paper Mario (U): Runs,crashes after talking to Princess Peach. ):
Rayman 2 - The Great Escape (U) (M5) [!]: Runs,menu gets stuck can't move up,random crashing,intro end crashing.
Super Smash Bros. (U): Runs,hangs on 4 players with stage music,1P Mode crashes after defeating Link.

**Interpreter Comparisons**; (simpler names to save time.

Glover: Same control issues,plugin or core problem?

**Comment by zminhquanz** [comment]
@retrobenny oh , i have tested on ASUS Zenfone devices , using Intel processor , it's crash randomly ( sometimes ) , and black screen but i hear the sound and i can't play the game

**Comment by cxd4** [comment]
Nah, just start another thread at the PJ64 cheat forums titled retroben's Android Bugs collection and post in that thread like you do with cheats; it'll work out.

**Comment by Frank-74** [comment]
Just downloaded it to my phone and tested Goldeneye.

Phone is Samsung J1 (cheapest Samsung made).  No crashes yet.  No graphic glitches that are not also in the Win Glide64.  It's just very slow framerate.  Which I expected on my cheap low spec phone.

I have a lynx10 android tablet which should run it much faster to test on next.

**Comment by retrobenny** [comment]
What's wrong with it being here?

Also,Banjo-Kazooie (U) v1.0 runs but PJGlide64 chews it up with the entire game having what's seen as the common object growing/stretching bug in all other games.

Even my really long session of Quest 64 crashless has the "Marionasty" enemy stretching weirdly with areas looking fine besides texture clipping for carpets and such.

Another thing,PJGlide64 really hates it when you reset a game,as many textures disappeared on Super Smash Bros. after the reset.

**Comment by Frank-74** [comment]
I can confirm the bug on restart in Goldeneye.  All text is missing/corrupted after restart, first noticeable on the first copyright screen.  End Emulation and reloading is ok though.

**Comment by retrobenny** [comment]
Make sure to read the top post every occasional time,I want to list all of it up there.
For example,Kirby 64's short results will be edited in.

**Comment by cxd4** [comment]
Dude, no one wants to re-read a collage of re-read text.

Just file new issues separate for each Android issue you find so they can be ticketed separately and discussed/answered separately.  I mean, I'm busy...I don't seriously care one way or the other which way you do it; it just sounds like common sense to do.  You don't have to try it.

**Comment by retrobenny** [comment]
Thanks for the suggestions,but I just didn't want the issues list to be flooded with x-game Android recompiler this/that or many of them not associating the proper info.

The worst part is that I have yet to try a handful in the Interpreter to see if they keep running compared to Recompiler's crashes.

**Comment by Frank-74** [comment]
It appears analog stick and c-pad movement works with 5 year old fingers.  But not my banana meat hooks.

**Comment by Frank-74** [comment]
How to change settings?

I only have enable/disable audio option.

**Comment by retrobenny** [comment]
Since you shared that tidbit,I mise well say that you can enable advanced mode by clicking the Project64 name in the about menu,just like you would do to enable Android's debug settings.

Besides,this would help from all other knowledgable users posting test results with log files to further assist on improving the emulator.

**Comment by zminhquanz** [comment]
end i have a problem with material design when i'm config through play game

**Comment by AmbientMalice** [comment]
>Just file new issues separate for each Android issue you find so they can be ticketed separately and discussed/answered separately.

That sounds like a terrible idea since the Android version is so catastrophically broken. It's going to flood the issues tracker.

**Comment by LegendOfDragoon** [comment]
>It's going to flood the issues tracker.

For this reason, I wouldn't suggest having a separate issue either.

**Comment by Frank-74** [comment]
Cannot install on Versus Touchpad 7.  Android 4.04.

On playstore , I get Error . Package file was not signed correctly.

Trying to install from the apk on the beta forum I get Application not installed.

**Comment by zminhquanz** [comment]
@Frank-74 i think Project64 on Android not support tablet at present , it only support on smartphone

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
