### ISSUE TITLE
Goldeneye Depot end of level old bug

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1171]
When walking into the train without shooting the soldiers in there, the end sequence shows bond shooting them and then pointing his gun in the air.  If you're holding a machine gun, it keeps firing an infinite amount of bullets.  The level doesn't end if you don't press A to skip, you can stare at the closed doors of the train for ages.

This bug has been around for years.  Anyone know why this happens?

![snap0000](https://cloud.githubusercontent.com/assets/11056843/17652874/86ab18f4-6280-11e6-9a66-9a7594271145.jpg)

**Comment by cxd4** [comment]
Could this be a bug in the game itself on the native machine?  I've played this level on a real N64 loads of times back in the day but can't remember if little quirks like this weren't a part of some endings or not.

Otherwise maybe switching emulators or changing to the interpreter will make it go away, though I doubt it.  Project64 has this weird issue with the Bomberman 64 credits:  On real hardware Bomberman runs down Green Garden, stage 3 for the credits to start rolling, but in Project64 he's just running into a wall indefinitely going nowhere and the credit screen never starts.  Have to load save states or end emulation to get out of it.

**Comment by Frank-74** [comment]
@cxd4 
It doesn't happen on my real N64 with one controller.  With a 2 controller, 1 player setup, you can aim up and shoot with the other controller.  Some endings do have extras, like in the Egyptian level, if you have a second controller, you can shoot Baron Samedi as he stands there laughing.  You need to use a 1 player, 2 controller setup, one for running, the other for aiming and shooting though.

It may be a controller issue.

**Comment by Frank-74** [comment]
Took a while, but I found a video from the real N64 which shows the ending of Depot with 1 controller used.
https://www.youtube.com/watch?v=GqsAXhPuPg0

**Comment by cxd4** [comment]
I know about the Baron Samedi thing, but forgot it was from using a second controller.

Maybe if you switch RawData on and off or toggle the other controllers in N-Rage on and off it will affect the issue.  Before you mentioned that, I thought fixed audio timing would help.

**Comment by Frank-74** [comment]
I setup the right analog stick to controller 2, and fire/aim on the 2 spare buttons on my PS2 controller.
Using controller profile 2.3 Domino in Goldeneye, and I can get the end to happen properly if I hold down fire on the second controller during the bond shooting the soldiers in the carriage phase.  Its still not right though.

**Comment by wfowler1** [comment]
The second controller firing a weapon during ending cinematics is not a bug in the emulator or any of its plugins. It does this on native N64 hardware with the 2.3 or 2.4 controller configurations.

Another quirk of ending cinematics: having some cheat codes on causes the cinematic at the end of Runway to cut off before the final note of the music is played. This also happens on N64 hardware.

I'm not sure what's happening in Depot in this case, I don't remember it ever happening on native hardware so I have to say it IS a bug in the emulator. I can't reproduce it right now, though, I just completed Depot and the ending cinematic played successfully.

**Comment by Frank-74** [comment]
@wfowler1 What controller config did you use in goldeneye?

Here, using a 1 controller profile, Bond doesn't put his gun away, and straighten his cuffs, after shooting the soldiers.  Instead bond points upwards, the doors of the carriage closes, and I have to press A to exit the sequence/level.

It works ok using 2.3 or 2.4 controller config.

Another quirk with Frigate.  Using NRage 2.3b, you occasionally have blue water instead of green water using Jabo's D3D plugins 1.6.1 or 1.7.
Happens only with NRage 2.3b version.  You may have to start the level several times to get the blue water with Jabo.

So there is something funky with controllers/pif.

**Comment by wfowler1** [comment]
Works fine for me using 1.2 Solitaire and only one controller "Plugged" in the N-Rage config, as well as 2.4 Goodhead with two controllers "Plugged". I'm using a build of 2.3 but I don't know how old it is. I'm also using GlideN64 instead of Jabo's.

**Comment by Frank-74** [comment]
@wfowler1 Did you shoot the soldiers before entering the carriage?  You have to leave them alive for this bug to happen.

I'm using latest build.  Though, this has always happened with all versions of Project64 for me.
I just tried it with GLideN64, Glide64, Jabo, z64gl, it's the same with all of them.  Probably a core issue.

**Comment by wfowler1** [comment]
I did not shoot the guards, so I watch Bond murder them before the doors close. What difficulty are you playing on? Any cheat options? Can you upload a save file we can try with?

**Comment by Frank-74** [comment]
Doesn't matter what difficulty, no cheats ever.

Save file:
https://dl.dropboxusercontent.com/u/9498358/n64/GoldenEye%20007%20%28U%29.pj.zip
Open the doors and run into the carriage without firing your gun.
Picture of doors closing with bond still aiming in the air.
![gliden64_goldeneye_000](https://cloud.githubusercontent.com/assets/11056843/20915771/b5158e2e-bb7f-11e6-8a32-bbb32d4dc6d7.jpg)

**Comment by Frank-74** [comment]
Slot 1 savestate just after I enter carriage.
https://dl.dropboxusercontent.com/u/9498358/n64/GoldenEye%20007%20%28U%29.pj1.zip

**Comment by wfowler1** [comment]
Hmmh, even when loading that savestate the ending plays just fine for me. We could go through all the settings the emulator has and pick apart the one that could be causing this issue.

**Comment by Frank-74** [comment]
Maybe it's my controller having 2 analog sticks, the unconfigured one doing it.  I'll test it tomorrow with keyboard, controller unplugged.

**Comment by Frank-74** [comment]
Nope, still does it with keyboard control.  Default settings.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
