### ISSUE TITLE
[Android] Use Controller

### ISSUE THREAD

**Issue by project64** [project64/project64#1172]
"it s possible to use my moga pro in you emulator"

Fix up android build to support it

**Comment by cxd4** [comment]
"**Make** it possible to use my Moga Pro controller in your emulator."

context:  http://forum.pj64-emu.com/showthread.php?t=5820

**Comment by vgturtle127** [comment]
Has controller support been implemented in the Android port? How many have been tested?

**Comment by project64** [comment]
yes I have controller support in android now ... does it possibly need more work maybe
