### ISSUE TITLE
Exception caught

### ISSUE THREAD

**Issue by Zedelot** [project64/project64#1178]
File: .\main.cpp
Line: 99

I have no idea what this is or how to fix it. I downloaded the source code and thought to put the main.cpp some where but still didn't fix it. I don't know if it's a bug

Project64 2.3

**Comment by Frank-74** [comment]
http://forum.pj64-emu.com/showpost.php?p=66131&postcount=31

Does it fix it?

**Comment by Frank-74** [comment]
Fixed with https://github.com/project64/project64/pull/1180.

**Comment by LegendOfDragoon** [comment]
i suppose this issue can be closed

**Comment by karl123g** [comment]
what do you mean i dont understand
