### ISSUE TITLE
Missing strings...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [project64/project64#1179]
Project64 2.3 (Public Release).

Here some missing strings to add : 

Press a key to be used as an accelerator. Cancel button
N64 ROMs (*.zip, *.7z, *?64, *.rom, *.usa, *.jap, *.pal, *.bin, *.ndd) --> *?64 or *.64 ?
All Files

![pj64_about](https://cloud.githubusercontent.com/assets/12481242/17836176/01aebc10-6789-11e6-8bec-9656bb376a30.JPG)
![plugins_about](https://cloud.githubusercontent.com/assets/12481242/17836177/04c30cd0-6789-11e6-9432-28fb7f78895d.JPG)

**Comment by BenjaminSiskoo** [comment]
Typos problem : 
 Windows Resultion  --> Windows Resolution ?

![typos](https://cloud.githubusercontent.com/assets/12481242/17836214/257bb188-678a-11e6-81e9-0eecc8590333.JPG)

**Comment by Frank-74** [comment]
*?64 should be *.?64 I think.
The '?' is an option/wildcard character.  There are v64, z64, n64 types.

Fixed the Glide64 "Windowed resolution".

The 'About' dialog for Jabo's plugins cannot be changed.  Closed source plugins.

**Comment by BenjaminSiskoo** [comment]
Ok, very nice. Thanks for the quick answer :)

**Comment by Frank-74** [comment]
Already done, resized 
![glide64dialog1](https://cloud.githubusercontent.com/assets/11056843/17848802/6df4d30e-684d-11e6-8f07-60c8b038d24b.PNG)

**Comment by BenjaminSiskoo** [comment]
Ok so I guess I can close :)
