### ISSUE TITLE
Urgency Request Android: Add option to change RDRAM size for SM64 hacks.

### ISSUE THREAD

**Issue by retrobenny** [project64/project64#1185]
Most SM64 hacks require 8MB size rdram to run and "The Last Impact" is getting closer to a release,so I hope that this simple task can be done soon fairly quickly along with Counter Factor (=1) to get it out of the way.
Besides,I wanted to see how Peach's Christmas Invitation runs and if it doesn't hang when entering levels.

Also,if PJ64 Android is 32bit,why not eventually have the other plugins ported such as Mudlord's Rice 6.1.4 since its the fastest plugin i've seen.
And GLideN64 is the obvious one to get as well since PJGlide64 is really buggy atm,maybe you can import that one from Mupen64Plus AE with the developers' permission.

**Comment by project64** [comment]
next version is really only going to focus on 2 things, recompiler to speed it up and controller.

Once those things are done I can look at what I am doing gfx wise. While it does not expose plugin choices it is still a plugin based emu, so adding different plugins should not be to hard. Would much prefer to see how to fix PJGlide64

**Comment by project64** [comment]
nearly all the settings are available to be changed if you modify the .cfg file, but yes there is no UI for lots of the options. 

The hacks you talking about are custom roms? If so are they in the RDB with the settings for windows?

**Comment by Frank-74** [comment]
Glide64 with Mupen64Plus FZ version is good for SM64.  Doesn't have the flickering/missing textures on doors/floors etc.

**Comment by project64** [comment]
while the code should be very similar, most likely there is some setting difference, something that should be on or off and I have the inverse. At some stage I will come back to gfx, but need to get the speed better first.

**Comment by fzurita** [comment]
Does the version of Glide64 in PJ64 for Android have the polygon offset hack? If it doesn't, you are going to see issues with missing textures.

**Comment by retrobenny** [comment]
Delayed response,but the SM64 hacks that are newer don't have the rdb setting customizations for obvious reasons when they are renamed to avoid clashing with the original game which also defaults to 4MB rdram.
And the difficulty is that updating the rdb is often neglected by users that stick to a set version of PJ64,especially when "x" version of PJ64 runs better on Windows 10 than "y" newer version.
The Peach's Christmas Invitation hack is pretty old now,so the rdb should've had it added by now with the required settings to boot/run correctly (8MB rdram,Counter Factor=1 for all SM64 hacks to run smoothly) and PJ64 is the main emu to use for SM64 hacks like this one from it being the only one that doesn't hang or crash in various spots.

**Comment by retrobenny** [comment]
Forgot to mention my results of Banjo-Tooie on Interpreter this recent time.
The tracks in Jinjo Village show up and get obscured correctly by the Jinjo houses,but the same shadow depth issue (shadow seen through walls and on top of grass) appears that Mupen AE also has with its Glide plugin,at least most polygons are correct on PJGlide where they are missing in Mupen AE's Glide plugin,I did see something go missing briefly on Banjo for one moment at a certain close distance.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
