### ISSUE TITLE
South Park crash with Debugger enabled

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1192]
Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Mips\MemoryVirtualMem.cpp
708

Disable the debugger and it runs ok.

**Comment by vgturtle127** [comment]
@Frank-74 Have you experienced the random crashes with the debugger in other games? I get crashes all the time with the debugger on, but if I turn it off they go away.

**Comment by LegendOfDragoon** [comment]
>Have you experienced the random crashes with the debugger in other games?

Crashes yes, but not random. Vigilante 8 still wont run in debugger.

**Comment by vgturtle127** [comment]
@LegendOfDragoon Does Vigilante 8: Second Offense have the same issue?

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon Does Vigilante 8: Second Offense have the same issue?

no

**Comment by Frank-74** [comment]
Ditto, crashes are not random.

**Comment by vgturtle127** [comment]
@LegendOfDragoon 

> no

*slams head against wall repeatedly*

@Frank-74 Yeah, that's what people tell me. 😄

**Comment by Frank-74** [comment]
This game doesn't crash anymore.
