### ISSUE TITLE
Jabo D3D 1.7 disable d3d syslog

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1194]
Calling @LegendOfDragoon 

Hi, could you decompress Jabo's Direct3D8 1.7.0.57-ver5 dll, so that I can disassemble it and disable the d3d syslog.txt from being written.

Some games can fill the memory in no time because the d3d syslog.txt is written to memory every interrupt and only flushed to disk after the rom/pj64 is closed.

As this was a debug feature, it should I believe be removed for the release version.  It only reports problems which will not/cannot be solved anyway.

**Comment by LegendOfDragoon** [comment]
I think you can unpack it using PE Explorer.

**Comment by Frank-74** [comment]
Cheers, PE Explorer unpacked it.  It's a modified UPX header.  Now I need to find a copy of W32Dasm 8.93 that isn't infected with a virus.

**Comment by oddMLan** [comment]
Why not just use Ollydbg?

**Comment by Frank-74** [comment]
Does Ollydbg allow you to get the calls to string references?

It's a 1 minute job to disable/bypass writing to the d3d syslog.txt with W32dasm.  I'm familiar with it.

**Comment by Frank-74** [comment]
To expand on why this is a problem, I have a  1.4Gb d3d syslog.txt filled with this:
```8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
8/31/2016 16:42:54 !- SetViewport failed 8876086C (0,91,801,415)
```

**Comment by LegendOfDragoon** [comment]
>Does Ollydbg allow you to get the calls to string references?

Yes it does, for API functions.

**Comment by Frank-74** [comment]
I just patched it.  I removed the conditional jump to CreateFile Kernel import function.  Re-packed with latest UPX.  No longer creates a d3d syslog.txt.

https://dl.dropboxusercontent.com/u/9498358/n64/Jabo_Direct3D8.zip

**Comment by oddMLan** [comment]
Even if it doesnt flush the file to the disk anymore, does it still generate it in memory?

**Comment by Frank-74** [comment]
> Even if it doesnt flush the file to the disk anymore, does it still generate it in memory?

I went back from the create file a few conditional jumps.  I'd imagine it might still be making the errors to be written to the file.  But I also imagine, there are dozens, if not hundreds, of places where it could send errors to the d3d syslog.

Without Jabo rebuilding the plugin without logging, I doubt anyone will bother trying to remove every instance where it could find an error.

**Comment by Frank-74** [comment]
@oddMLan 
After testing games which abused the d3d syslog, memory useage isn't much more than 1.6.1.  So I guess it's not generating the syslog in memory.
