### ISSUE TITLE
Armorines - Project S.W.A.R.M. (U)+(E) - TLB Write Miss with Recompiler+Interpreter

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1197]
2016/09/01 20:56:12.653 01844,Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Recompiler\x86\x86RecompilerOps.cpp
10002

Start the game, let the demo's run, after the 5th (I think) demo with the big spidery monsters, just before the next level demo starts.

Save state from spider demo.  Let it play, it will crash when about to start the next demo.

Hmm, I get this message trying to add the save ,"Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "

Savestate:
https://dl.dropboxusercontent.com/u/9498358/n64/Armorines%20-%20Project%20S.W.A.R.M.%20%28U%29.pj.zip

**Comment by project64** [comment]
ok so the game is doing a TLB Write Miss seems quite rare

does it work correctly in interpter?

**Comment by Frank-74** [comment]
I get this with Interpreter:

2016/09/01 21:21:49.010 01540,Error,User Interface,CNotificationImp::DisplayError,Break point found at
.\N64System\Interpreter\InterpreterOps.cpp
1254

**Comment by Frank-74** [comment]
Same error with (E) version as well.  Only difference was first time I ran (E) version without debugger enabled, it crashed with display error before the spider demo.  Enabled debugger, then it crashed at same place as (U) version.

**Comment by Frank-74** [comment]
Same with Indiana Jones.  I was getting crash with 8MB expansion enabled in MemoryExceptionFilter.cpp line 373.  Changed to 4MB and then get TLB write miss.

Start Indiana Jones and let it run through the demo's, it crashes when Factor5 is drawing with,
Error,User Interface,CNotificationImp::DisplayError,Break point found at
N64System\Recompiler\x86\x86RecompilerOps.cpp
10000

**Comment by Frank-74** [comment]
Getting more info with latest build.  On booting Armorines, with show TLB misses enabled, I get this:

2017/08/18 18:33:42.418 08168,Error,User Interface,CNotificationImp::DisplayError,R4300iOp32::LW TLB: 480004
2017/08/18 18:33:53.276 08168,Error,User Interface,CNotificationImp::DisplayError,R4300iOp32::LW TLB: 4846E8
2017/08/18 18:33:56.583 08168,Error,User Interface,CNotificationImp::DisplayError,R4300iOp32::LW TLB: 492004
2017/08/18 18:33:59.457 08168,Error,User Interface,CNotificationImp::DisplayError,R4300iOp32::LW TLB: 49627C
2017/08/18 18:34:00.540 08168,Error,User Interface,CNotificationImp::DisplayError,R4300iOp32::LW TLB: 490CF8

When it crashes starting the 6th demo, I get this:

2017/08/18 18:34:55.199 08168,Error,User Interface,CNotificationImp::DisplayError,Break point found at
N64System\Interpreter\InterpreterOps.cpp
1244
2017/08/18 18:34:57.810 08168,Error,User Interface,CNotificationImp::DisplayError,R4300iOp::SB TLB: 0

**Comment by LegendOfDragoon** [comment]
Would be nice to address some of these. Iirc, Turok 2 has some TLB error messages, when disabling 32bit engine and using CPU Interpreter. Acclaim made both of these games :smile: so I guess it's not a coincidence.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
