### ISSUE TITLE
2.3 crashes on open

### ISSUE THREAD

**Issue by Dogstalotl** [project64/project64#1205]
PJ64 2.3, when opened, displays the following when I load it:

Exception caught
File: .\main.cpp
Line: 99

**Comment by project64** [comment]
the released one or from source, you have any made any changes like adding any plugins, which dir is pj64 in?

**Comment by Dogstalotl** [comment]
It's in my G:// Drive (Boot is C://) and no I don't seem to have any added plugins (Except defaults, ask if you want the folder)

**Comment by project64** [comment]
there is a bug if the directory is the first directory in the tree which has been fixed in the source

**Comment by Dogstalotl** [comment]
It is in G:\Project64 2.1 if you get what I'm saying

**Comment by Frank-74** [comment]
Put it in G:\Project64\Project64 and it will work.

**Comment by Frank-74** [comment]
@project64 
Now would be a good time for a new public release.  Windows version has no further bugs than previous versions at the moment.  A lot has been fixed since the 2.3.0.210 release.

**Comment by project64** [comment]
I am trying to get a version ready to release for android, you think I should release a windows version to

**Comment by Frank-74** [comment]
Yes, a 2.3.2 for Christmas. :)

**Comment by project64** [comment]
most of the changes have been for android mostly the the arm recompiler, anything else you like to see in a 2.3.2 release, or just the current bug fixes.

**Comment by Frank-74** [comment]
Can't think of anything simple to do.  The floating point rounding, as it may fix Indiana Jones, Battle for Naboo.

The Armorines TLB Write Miss in both Interpreter and Recompiler.
Saved few seconds before it happens:- https://dl.dropboxusercontent.com/u/9498358/n64/Armorines%20-%20Project%20S.W.A.R.M.%20%28U%29.pj.zip

**Comment by project64** [comment]
those I want to work out still, but prioritizing android first, so it just might be a really low key 2.3.2 release, will probably do a another 2.3.1.x release on android before that tho just to get some feedback on all the recent work.

**Comment by project64** [comment]
is this fixed? I thought it was already?

**Comment by Frank-74** [comment]
@project64 Yes, this was fixed by myself some time ago.  Close this issue...
