### ISSUE TITLE
Plug in error with 2.2

### ISSUE THREAD

**Issue by BennyBeah** [project64/project64#121]
Decided to try out new version of project 64 2.2 but I cannot run any games as I keep getting this error

![error](https://cloud.githubusercontent.com/assets/6206508/6315689/1f716fa8-ba02-11e4-825a-73a0d308b943.jpg)

When I tried using no sound plug in it just stays on a black screen

**Comment by project64** [comment]
is that just with no audio, or what about with the default plugins?

are you using the version on the forum, or your own compiled version

**Comment by BennyBeah** [comment]
the screen shot is with all defaults & I downloaded it from here http://www.emucr.com/2015/02/project64-git-20150221.html

**Comment by project64** [comment]
I have no idea how it is being compiled or built on emucr. I do have a version I compiled that is on the pj64 forum ... just message me if you do not have access to the beta forum there

**Comment by BennyBeah** [comment]
I do not have access to the forum

**Comment by project64** [comment]
what issue do you have accessing the forum ?

**Comment by project64** [comment]
Use the one on pj64 forum I have no idea how emucr version is compiled or how they are building it.
