### ISSUE TITLE
PS4 Controller bluetooth on android

### ISSUE THREAD

**Issue by Marraz** [project64/project64#1212]
It's seems than project 64 can't map my ps4 controller connected throug bluetooth, this issue is on android 6.0.1.

**Comment by project64** [comment]
I now the controller stuff I use to map was originally based on mupen code since I had no idea how it worked.

Does it work with other n64 emus on android?

**Comment by Marraz** [comment]
I can't found any, I guess it is because all of them are based on mupen as well

**Comment by project64** [comment]
all the other n64 emus on android are just mupen clones .. controller and audio are the two things I did take from mupen as I figured it had been around long enough to and would have had those worked out. 

And we do share a gfx plugin tho that plugin is starting to change more from the original version

**Comment by project64** [comment]
does the controller work with other apps on android?

**Comment by Marraz** [comment]
yes, there are some games than work with it but just a few, it should work as a generic controller, then I guess I'm stuck either waiting to someone to give it support, mapped as another controller or give it support myself, for now looks like I'm struck with pc emulators if I want to use my control

**Comment by vgturtle127** [comment]
@Marraz It should be noted that the PS4 controller has limited functionality on Android due to Android not having the proper Bluetooth authentication for the DualShock 4. So in other words, don't be super suprised if it doesn't work for some things.

Have you tried an OTG cable? What device are you using?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
