### ISSUE TITLE
[Android] Add option for custom save directory

### ISSUE THREAD

**Issue by wfowler1** [project64/project64#1223]
It'd be great to be able to specify a custom directory for native saves on Android, like you can on PC. I use an app to synchronize save files to my devices from Google Drive, and I'd love to just point the emulator to the synchronized directory, like I can on the PC.

**Comment by project64** [comment]
It will probably not be in the next release, maybe the one after, it should not be hard to do as all the functionality is actually in, just needs the UI to be able to change it. 

It technically possible now with modifying the cfg file, but that is not a real solution.

**Comment by cxd4** [comment]
You could probably use Dropbox for that, but that vs. Google Drive probably doesn't affect this.

**Comment by wfowler1** [comment]
I could use any service that will sync files between my phone and the cloud, that's really not relevant...

**Comment by cxd4** [comment]
>It technically possible now with modifying the cfg file, but that is not a real solution.

Huh.  How is that not a real solution?

**Comment by cxd4** [comment]
>I could use any service that will sync files between my phone and the cloud, that's really not relevant...

Well, it **is** relevant if you get a service that lets you sync files between your phone and the cloud *without forcing you to group them away from Project64's directory*, because then you wouldn't need to change the default directory.

That was the only reason I mentioned that, but it's probably not readily available in Dropbox either.

**Comment by Frank-74** [comment]
What about a check if Cloud or Dropbox is installed, to give the user the option for Project64 to use an online storage for saved data.  Most apps check for other storage options on Android/Smart phones/tablets.  I've had lots of apps ask me to use dropbox or cloud.

Loading a save will be a lot slower though.  Having to download it first.

**Comment by wfowler1** [comment]
I actually could synchronize directly into pj64s directory, the app I'm using gives that option. And I would, except I'm using this for more than just n64 save games. I have gba (VBA-m) and gcn (Dolphin) saves as well as n64 (pj64) in different subdirectories inside the directory I'm synchronizing. Plus these saves are using the old pj64 way of storing saves (all in one directory, no subdirectories per-game), so we could probably use an option for that as well.

Where is the cfg file? I've looked all over my phone and can't find one anywhere, not even in data/data.

**Comment by Frank-74** [comment]
> Where is the cfg file? I've looked all over my phone and can't find one anywhere, not even in data/data.

If I can remember, it's something like, "data/emu.Project64/Config/".

**Comment by project64** [comment]
the default location when it initializes is that location, once initialized the UI then changes the location if it is not set (I need to double check) to the new easier to get to location.  At the first initialization it creates those directories.

Now maybe if the directory changes it should move the save folder. Or maybe the UI could just delete them, but considering uninstall will remove them and they are well buried from casual view I just ignored them.

**Comment by cxd4** [comment]
I go to my `/etc/` directory all the time to edit OS configuration files.

It's a requirement to even getting wifi to work.  Editing text config files is easier than a GUI.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
