### ISSUE TITLE
[Glide64] Unable to switch motionblur off/on

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1226]
There appears to be no way to switch this off or on.  Hotkeys are not working for me.  Alt+V or Alt+B should be FB READ ALWAYS  and MOTION BLUR.  But Alt and any key just makes windows make a sound instead.  I tried changing the Alt key to Control in the source, but that doesn't seem to work either.

**Comment by project64** [comment]
hmmm ... hot keys really should go through the UI and not a plugin. Is there a good reason these should be hotkeys instead of settings in the UI ?

**Comment by Frank-74** [comment]
Not really, settings in the UI is fine.

I restored the Filtering Mode backspace key ok, and it works.  Was a bit puzzled why that works and v+b doesn't.

**Comment by project64** [comment]
I do not mind them being hot keys, but I dislike a video plugin managing keyboard input. 

I guess these should be moved to the settings UI and the hot key code to be removed

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
