### ISSUE TITLE
[Android] Load savestate problem with tablet

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1230]
I tested 2.3.2.135 on my Samsung J1 phone, and savestates are loading perfectly there.

Tested on Versus Touchpad 7, Android version 4.0.4, Kernel version 3.0.8+.  Savestates do not load.

So the problem is device specific it seems.

Also both devices, cannot get to menu on Goldeneye.  It blackscreens after pressing A to skip the intro, and hangs there with no error.

**Comment by project64** [comment]
I am looking at a bug in jet force at the moment, once solved I will look at golden eye, I know I tested the intro well with GE but not going in to game.

What do you mean save states do not work? Is it the same save state that you know works perfectly or is it possibly the creation of the save state. Or just those particular save states.

I know I have limited devices to test with here so I am not sure soemthing I can reprodroduce

**Comment by Frank-74** [comment]
Just switched to Interpreter, and savestates load ok on my tablet.

Only getting fatal error emulation stopped with Recompiler.  Same savestates load with Interpreter.

**Comment by project64** [comment]
if you enable debugger in advanced settings then you should get a better error message. But it could just be the save state

**Comment by Frank-74** [comment]
Log file after trying to load a savestate with debugger enabled.

2016/12/02 22:18:33.603 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),Invalid memory adderess: A46EF010
2016/12/02 22:18:33.603 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),Program Counter 0x8027d7cc
2016/12/02 22:18:33.604 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[0] = 0x0
2016/12/02 22:18:33.604 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[1] = 0x0
2016/12/02 22:18:33.604 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[2] = 0x0
2016/12/02 22:18:33.604 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[3] = 0x0
2016/12/02 22:18:33.604 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[4] = 0x0
2016/12/02 22:18:33.608 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[5] = 0x0
2016/12/02 22:18:33.608 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[6] = 0x0
2016/12/02 22:18:33.609 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[7] = 0x0
2016/12/02 22:18:33.609 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[8] = 0x0
2016/12/02 22:18:33.609 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),m_LastSuccessSyncPC[9] = 0x0
2016/12/02 22:18:33.609 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),MemAddress = 0xa46ef010
2016/12/02 22:18:33.609 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r0 = 0x82841000
2016/12/02 22:18:33.610 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r1 = 0x500000
2016/12/02 22:18:33.610 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r2 = 0x6
2016/12/02 22:18:33.610 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r3 = 0x7
2016/12/02 22:18:33.610 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r4 = 0x10
2016/12/02 22:18:33.610 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r5 = 0x82841000
2016/12/02 22:18:33.610 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r6 = 0x500000
2016/12/02 22:18:33.611 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r7 = 0x78
2016/12/02 22:18:33.611 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r8 = 0x5b8bbd81
2016/12/02 22:18:33.611 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r9 = 0x19d210
2016/12/02 22:18:33.619 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_r10 = 0x100000
2016/12/02 22:18:33.620 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_fp = 0x1
2016/12/02 22:18:33.620 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_ip = 0x5b909d68
2016/12/02 22:18:33.620 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_sp = 0x80f62e30
2016/12/02 22:18:33.620 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_lr = 0x5b8b6675
2016/12/02 22:18:33.620 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),uc->uc_mcontext.arm_pc = 0x5b8299d0
2016/12/02 22:18:33.621 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),TypePos: 00 00 84 E5 00 00 50 E3 2C
2016/12/02 22:18:33.621 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode.Hex: 0
2016/12/02 22:18:33.621 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode.opcode: 0
2016/12/02 22:18:33.627 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode.rm: 0
2016/12/02 22:18:33.628 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode.rn: 0
2016/12/02 22:18:33.628 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode.rt: 0
2016/12/02 22:18:33.628 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32.Hex: E5840000
2016/12/02 22:18:33.628 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint16.opcode: 0
2016/12/02 22:18:33.628 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint16.rm: 4
2016/12/02 22:18:33.628 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint16.rn: 0
2016/12/02 22:18:33.629 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint16.rt: E
2016/12/02 22:18:33.630 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint16.imm2: 0
2016/12/02 22:18:33.630 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint32.opcode: E58
2016/12/02 22:18:33.630 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint32.rn: 4
2016/12/02 22:18:33.630 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint32.rt: 0
2016/12/02 22:18:33.630 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint32.opcode2: 0
2016/12/02 22:18:33.631 29290,Error,Exception Handler,static bool CMipsMemoryVM::FilterArmException(uint32_t, mcontext_t &),OpCode32->uint32.rm: 0
2016/12/02 22:18:33.631 29290,Error,User Interface,virtual void CNotificationImp::FatalError(const char *) const,Break point found at
jni/./Project64-core/MemoryExceptionFilter.cpp
Line: 430
2016/12/02 22:18:41.013 29290,Error,Exception Handler,static void CMipsMemoryVM::segv_handler(int, siginfo_t *, void *),Failed quiting now

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
