### ISSUE TITLE
[Glide64] Configure pause issue

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1231]
Opening/closing the Glide64 configure window, leaves PJ64 paused.  Open/close a second time while paused, resumes normally.

It alternates between leaving PJ64 paused and resumed, after closing the config.

Also, GLideN64 config doesn't pause emulation at all.  I tried to force pause on configure graphics option, but wasn't able to resume.

**Comment by Frank-74** [comment]
Also, when "Pause emulation when window is not active" is unchecked.  PJGlide64 config still pauses the emulator.

**Comment by LegendOfDragoon** [comment]
still an isue?
