### ISSUE TITLE
Crashes with exception when steam controller is plugged in 

### ISSUE THREAD

**Issue by komali2** [project64/project64#1237]
Version 2.3.0.210

From the log:

```
2016/12/25 20:32:27.731 09688,Error,User Interface,CNotificationImp::DisplayError,Exception caught
File: .\N64System\N64Class.cpp
Line: 545
```

If the steam controller is plugged in, any game I launch crashes with a popup saying

```
Exception caught
File: .\n64System\N64Class.cpp
Line: 545
```

Windows 10 64 bit. Let me know if I can provide more info. I have replicated the error with a bunch of different roms and have confirmed everything works fine if the steam controller is not plugged in.

**Comment by TheEssemCraft** [comment]
Have you tried any other controllers?

**Comment by vgturtle127** [comment]
@komali2 While it crashing like that shouldn't happen, you should always plug controllers in before you start the application you want to use with the controllers, for future reference.

The Steam controller uses virtual drivers, and simulates a keyboard and mouse, so it is somewhat expected that odd things will happen with it from time to time.

Not sure how to approach this problem, but it may not even be related to Project64...

**Comment by DTV96Calibre** [comment]
I'm also having this problem and had the controller plugged in before starting Project64. The steam controller acts as a keyboard and mouse for the project 64 ui but switches to emulating a controller when the game starts.

**Comment by vgturtle127** [comment]
@DTV96Calibre Really? That's kind of weird, I'm unsure of how it magically knows when the game is starting. 😆 

Maybe it detects OpenGL/DirectX or something? I wouldn't have thought the Steam controller would be so sophisticated. Or are you running it through Steam?

**Comment by DTV96Calibre** [comment]
Yeah, you pretty much have to use the Steam controller through Big Picture mode to get most of it's functionality (unless you use a certain open source alternative). The autodetection can be limiting at times but yeah, it detects when you're doing stuff with normal windows and stuff and when you're working with game windows. The steam controller is incredibly flexible, especially for emulation of console controllers so I'd love to see better support for it in project64, steam has an API for it I believe.

**Comment by DTV96Calibre** [comment]
I looked at the code where the exception is supposed to have occurred earlier today and I don't see how that line could have thrown the exception (the line just writes to the debugging logs "Done"). Someone with more understanding of how everything works and a steam controller is going to have to mess around with it if this is going to be considered a problem with Project64 and not something else.

**Comment by DTV96Calibre** [comment]
I was able to get the Steam controller to work by starting the game before turning on the steam controller.

**Comment by project64** [comment]
if logging has not been started and it is trying to use the logs that can cause an exception ...

I could add extra checks to the logging but in general I have tried to keep logging light as it is used a lot in time critical locations.

you can try adding a new definition of the WriteTrace if that is the issue.
just copy the few lines from path.cpp (line 20-25)
https://github.com/project64/project64/blob/master/Source/Common/path.cpp#L20

**Comment by vgturtle127** [comment]
@DTV96Calibre Which open-source alternative?

Also, if you are using Steam BPM, are you running Project64 separately or through Steam?

**Comment by DTV96Calibre** [comment]
I was talking about this one: https://github.com/ynsta/steamcontroller
It supports linux at the moment but there are a number of forks so maybe someone's worked out Windows support. I think I started Project64 through BPM but for sure it's added as a non-steam game.

**Comment by DTV96Calibre** [comment]
The logging fix did not prevent an exception from being raised, though it did move where the exception was supposedly being raised at (not superficially, the exception is somewhere else in code now). I don't have more details being away from my development computer but I'll look into it more when I have time.

**Comment by vgturtle127** [comment]
@DTV96Calibre Alright, much appreciated dude. This is a big help.

I have a feeling the reason the exception changed is because the debugger being active or something similar. Probably the same thing that's causing all the debugger crashes as well, maybe. Heh.

**Comment by komali2** [comment]
I wonder if this is at all related to https://github.com/project64/project64/issues/988 ?

**Comment by komali2** [comment]
This issue does not occur when I switch to using the https://github.com/KrossX/Pokopom Pokopom controller plugin, instead of NRAGE.

**Comment by vgturtle127** [comment]
@komali2 
Unfortunately there are a lot of unexplained crashes right now, and Steam definitely doesn't help. I will be diving into this soon, and way more in-depth than I have in the past.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
