### ISSUE TITLE
PJ 64 timing issue

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1242]
I have always noticed that PJ64 has had a rough time with getting 59.94 hertz to display at the 60 hertz on emulators. 

I have looked at several emulators and discovered that no one emulator is perfect. Their is a .06 difference on modern hardware. A couple of  Emulators manage to handle the timing as well as the real Nintendo 64 does on a modern 60 hertz TV. 1965 0.8.5, and Dolphin with vsync on do a great job. 

Using PJ64 if you watch the shadow of a character when hovering the hand on your character of choice, you can see the frames are somewhat erratic. As a work around you can use a vsynced video plugin; CF=1; and force screenhertz=61 in the  .cfg file to correct the timing.

Here is a recording I have captured of a few emulators to show the issue. 
https://www.youtube.com/watch?v=NNJo_U8hc4A

Other things that can effect the timing are, poor performance, and CPU throttling.  Throttling does not seem to impact Dolphin though.

I'm convinced that 1964 0.8.5 is handling the hertz correctly and it would be interesting to see if their method could be transposed into PJ.

Thoughts?

**Comment by Frank-74** [comment]
I've noticed whilst working on the timing in Azimer's 0.7 XA2, that the PJ64 frame limiter caps at 60, and can cause crackles in the audio because of a particular game wanting to run the audio at 61 VI's, with the frame limiter off, audio/video is silky smooth, but the VI's are at 61.  (with AziAudioXA2 doing the sync).

I've been messing with the timing in Azimer's to try and get games to be 59+ but under 60, to avoid crackles.

**Comment by theboy181** [comment]
Give 1964 0.8.5 a try, and see if you get the audio results you desire. Please report it too. I had a brief conversation with zilmar on this subject, but he seemed to think it was the plugins and not the PJ's core. 

I am convinced otherwise.

**Comment by Frank-74** [comment]
When I choose Azimer's XA2 in 1964 0.8.5, I get an immediate crash and have to close 1964.

**Comment by theboy181** [comment]
Test the Carnivorous version?  and play with the 
Goldeneye option in the settings window.

**Comment by LegendOfDragoon** [comment]
I think both the emulator and the plugins have room for improvement. What I have found is that having better performance always improves the experience. THat is why I strive to maximize my performance. Having excellent performance especially helps audio in difficult games like Body Harvest and Top Gear Rally. For example, with FAT enabled, the audio sounds awful if I use Glide64, but decent if I use Rice Video :smile: . FAT is inaccurate though, so I usually have it off for most games. It's only useful for netplay, debugging, and perhaps 1 or 2 dozen games.

Azimer's plugins are unstable on 1964. I wouldn't bother using his plugins on 1964.
