### ISSUE TITLE
Video Res Test: input not working

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#1243]
This is a testrom from libdragon. It should switch between resolutions when pressing the A button, but with PJ64 the input does not work. Correct with cen64
Here's the rom:
[VidResTest.zip](https://github.com/project64/project64/files/691637/VidResTest.zip)

**Comment by project64** [comment]
thanks for reporting this.

I will have a proper look later, trying to work out some other things first.

Now I am curious is it a gfx plugin issue, and switching to say glide64/gliden64 fixes it or is it a core bug and does not even work on the interpter

**Comment by purplemarshmallow** [comment]
It's very likely a core bug. Switching video plugins does not help.
I get the same results with recompiler and interpreter

**Comment by cxd4** [comment]
Never minding CEN64, are there any emulators that let you use the same graphics plugin that have the correct result where using Project64 with the same graphics plugin does not?

I'll test it tonight some time if I can get the software package for ZIP decompression downloaded in time.

**Comment by purplemarshmallow** [comment]
1964 and Mupen only give me a black screen

**Comment by cxd4** [comment]
Weird.  I don't suppose you're able to fire it up under other emulators using the spec, like Nemu64 0.8?  If that ROM's not using the RSP for anything graphics-related you should be able to change the graphics plugin in Nemu to see if that has a black screen as well.

**Comment by LegendOfDragoon** [comment]
I find it interesting that it seems to work in Nemu.

**Comment by purplemarshmallow** [comment]
very strange
Nemu64 switches correctly between resolutions. But it shows letters in the bottom left corner! There should be numbers

Project64 shows the numbers correctly but switching between resolutions does not work

**Comment by cxd4** [comment]
Maybe if you play with the nemu INI to use the interpreter core there is a difference?

@LegendOfDragoon I don't suppose you can play around with the 1964 INI to get it past just a black screen?  If it works in CEN64 perfectly I think this sounds like some kind of timing issue; maybe counter factor or in Project64's case VI Refresh needs to be toyed with.  I will test the ROM out in my 64-bit Linux fork of Project64 in a few hours though there is little to configure as far as timing settings are concerned, so I doubt the result can be changed based on that only.

**Comment by LegendOfDragoon** [comment]
I tried different settings and couldn't get it past black screen. Kinda reminds me of that Taz Express issue @purplemarshmallow referenced a while back. I wonder if it's related since it seems to be a graphical issue caused by core.

Is the source code available for this rom?

**Comment by purplemarshmallow** [comment]
I can test Nemu's interpreter later but I remember it's really buggy...

Yes this rom is open source 
libdragon: https://github.com/DragonMinded/libdragon
This rom: https://github.com/DragonMinded/libdragon/tree/master/examples/vtest

**Comment by retrobenny** [comment]
How about trying Azimer's ol' N64 emulator Apollo for the heck of it to see what happens on it?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
