### ISSUE TITLE
Manifest is broken (again)

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1245]
Project64 2.3 (release and latest code) appears to lack a manifest, so the program is displayed with a classic visual style.

This had happened in earlier versions and had been resolved. Why is it so hard to keep the manifest working properly?

**Comment by oddMLan** [comment]
I was the one who submitted a pull request to change it. Visual Studio generates the manifest for Project64 during build time. Project64.manifest was made redundant, thus I deleted the file. Building it with the newer solution works correctly and the buttons are properly themed, but the VS2008 solution doesn't seem to embed it for some reason. Zilmar to this day still uses VS2008 to build Project64 (allegedly due to higher compatibility/speed on older computers. That's highly debatable though).

#684 

The proper solution here is just to get rid of the VS2008 solution. ANGLE only builds with VS2015 onwards, so if it wasn't the time to get rid of it before, now it is @project64

**Comment by JunielKatarn** [comment]
> The proper solution here is just to get rid of the VS2008.

Agreed. I still haven't found any real benchmarks on which VC2008 compilers generate more performant code than the newer ones. The MSVC suite has gone through heavy refactoring and work, so I think the best approach is to deprecate 2008 support. The VCXPROJ makefiles support any version from VS2010 and later.

**Comment by project64** [comment]
vs2008 support will probaly dropped after the next release, as angle is only vs2015 .. so when the angle branch gets merged it will be dropped then.

**Comment by Frank-74** [comment]
Why is building the solution so slow with VS2015 compared to VS2008?  It's about 5 times longer on VS2015.

Also, compressed savestates do not work for XP on VS2015 build.

**Comment by oddMLan** [comment]
It takes like 3 minutes to build or less for me. Actually I think it's less.

**Comment by cxd4** [comment]
>as angle is only vs2015 .. so when the angle branch gets merged it will be dropped then.

Would not be a hindrance to you keeping it in VS2008 if you had just kept things organized into separate repositories, not everything all-in-one repository.  Then you could keep it to VS2008.

Not like it matters anyway.  If I still had Windows installed, I wouldn't put 2008 on it.  2013's good enough.

>Agreed. I still haven't found any real benchmarks on which VC2008 compilers generate more performant code than the newer ones.

You're not supposed to find them by searching through public company propaganda.

**Comment by JunielKatarn** [comment]
> You're not supposed to find them by searching through public company propaganda.

I don't. And you're not supposed to shitpost and reply with useless statements and spread ignorance, but you're basically famous for that :) . Again, no numbers, just bigot speculations regarding compiler speeds. Boring.

Back to not wasting my time..
@Frank-74, I'll look into the compilation times and compressed save files in XP.
My guess about the first issue is that the VCXPROJ-based solution ends up building more projects thant the VCPROJ one.

**Comment by JunielKatarn** [comment]
@Frank-74, The 2015 build IS slower, because its solution builds some Android modules too (unnecessarily?).

See the extract for the builds.
VS 2008:
```
Audio\Jabo_Dsound.dll
GFX\Jabo_Direct3D8.dll
GFX\PJ64Glide64_d.dll
Input\PJ64_NRage_d.dll
RSP\RSP_d 1.7.dll

Time: 01:03
```
VS 2015:
```
Audio\AndroidAudio_d.dll
Audio\Jabo_Dsound.dll
GFX\Jabo_Direct3D8.dll
GFX\PJ64Glide64_d.dll
Input\AndroidInput_d.dll
Input\PJ64_NRage_d.dll
RSP\RSP-HLE_d.dll
RSP\RSP_d 1.7.dll

Time: 01:22
```

In short, VS 2015 builds more modules, thus takes more time.
I wonder if we can omit the Android projects in windows build makefiles (Win32, x64).
@project64 Any comments?

**Comment by Frank-74** [comment]
Wow, 1:22, here it's half an hour compared to 5 minutes.

**Comment by cxd4** [comment]
>Again, no numbers, just bigot speculations regarding compiler speeds. Boring.

Yes, it is boring, I agree.  That's why you'll never know which compilers are faster. :)

And even if you did give numbers, the fact that you reach the premature conclusion that VC2008 has no latency improvements in any benchmarkable cases proves you do not know how to reach them.

**Comment by JunielKatarn** [comment]
> Also, compressed savestates do not work for XP on VS2015 build.

@Frank-74 I have verified this issue with any build produced by VS2010 or later (sadly, any VCXPROJ-compatible one). It looks like an issue with zlib.

I don't recall who, but someone suggested bumping the zlib codebase to a more recent, more secure and better performant one.

I'll look into this.

**Comment by Frank-74** [comment]
@JunielKatarn Has updating zlib fixed XP compressed savestates?

I think the suggestion was to update 7-zip from 9.20 to 16.04 here : #1089

**Comment by JunielKatarn** [comment]
@Frank-74 You are right. #1089 is not related to zlib.
Updating zlib doesn't fix the XP issue. As far as I've debugged, it seems pretty low-level (down to some assembly language method).

I'll create an issue for that bug for follow-up later.

**Comment by Frank-74** [comment]
@JunielKatarn 
> Updating zlib doesn't fix the XP issue. As far as I've debugged, it seems pretty low-level (down to some assembly language method).

Surely it's a compiler problem, and not a problem with libraries.  Otherwise why does it work fine with VS2008?  The problem appeared when 7-zip was added.

**Comment by JunielKatarn** [comment]
> The problem appeared when 7-zip was added.

Interesting! In runtime, only zlib source is involved in my test cases.
Maybe there is some duplicate code base between zlib and 7-zip? I'll check it out.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/2d09818eb22c9b2bee39b0af358fc30c0de8ae43 fix this issue?

**Comment by Fanatic-64** [comment]
@project64 Yes, the VS2008 build now has visual styles. Only one note; the About dialog currently appears as a standard window, whereas in earlier versions of PJ64 it had a custom background. Just checking whether that's intentional or if something else broke.

**Comment by oddMLan** [comment]
It was intentional. The custom backgrounds didn't adapt well over high-dpi displays (the text was being cut off).

**Comment by project64** [comment]
I can close this now?

**Comment by Fanatic-64** [comment]
Done for you.

**Comment by cxd4** [comment]
pwnt
