### ISSUE TITLE
ROM list improvements suggestions

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1247]
When a hacked ROM without a good name entry in the RDB, is in the list, all we see is a BAD ROM message.  It would be better if it could instead show the Internal Name instead, so we know what it is.

Also all hacked ROMS I've come across need 8MB memory.  Would it be a good idea to default to 8MB if an RDB entry doesn't exist?  As 99.99% of the time, a hacked ROM needs 8MB.

Also, there still exists the RDB Edit Mode.  Could part of it be enabled to edit the Good Name and Status etc. to add to the RDB if the ROM browser lists a ROM without an RDB entry?

**Comment by LegendOfDragoon** [comment]
I think these are good suggestions, although not sure about the 8MB assumption.

**Comment by cxd4** [comment]
I usually just have the Internal Name column added to the ROM browser anyway.

In fact the "Good Names" are sucky and have bad grammar anyway, so I leave that column out of my browser and prefer the File Name column to be added in its place.

**Comment by LegendOfDragoon** [comment]
Oh wow haha. Can't believe I never bothered to change that.. I guess it's because I don't use PJ64 that much anymore.

Yea file name is good enough imo.

**Comment by oddMLan** [comment]
This. This so much.

**Comment by project64** [comment]
why not add a n entry to the rdb?

**Comment by Frank-74** [comment]
Or how about just enabling Edit RDB from right-click menu in ROM browser, if a ROM doesn't have an entry?   It would make it much simpler.

**Comment by project64** [comment]
there is a mode to allow all edits via the UI to write to the RDB instead of the cfg file.

**Comment by cxd4** [comment]
I have no idea where it's written.  cfg file...rdb file...d/c it works, new ROM or not I never cared.

**Comment by Frank-74** [comment]
Put "Rdb Editor=1" under [default] section in Project64.cfg.  There's a slight bug, it writes a random number after the RDB entry on a new line.

**Comment by retrobenny** [comment]
I also mentioned the 8MB option from August 22nd in an issue I posted then for SM64 hacks on Android.
Still unable to see what SM64 Last Impact would do if I tried running it,even though its a waste because only Jabo can display the custom stuff correctly and currently many things crash still at random moments.
