### ISSUE TITLE
Mempak not found

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1250]
Just tried loading my career in Monaco Grand Prix and I get 'No save game found' message.

Mempak is in the Save folder.

Probably a problem with https://github.com/project64/project64/commit/1d7bdd2c270c5ebde20da8d426223f9352668a3d .

**Comment by Frank-74** [comment]
It appears to delete my saves from the mempak.

Original mempak:
![mgp1](https://cloud.githubusercontent.com/assets/11056843/22175370/2d7bf210-dfeb-11e6-9737-28115526233e.JPG)

Same mempak after trying to load in latest build:
![mgp2](https://cloud.githubusercontent.com/assets/11056843/22175375/414e1a2a-dfeb-11e6-864e-1ee6add95825.JPG)

**Comment by Frank-74** [comment]
I reverted https://github.com/project64/project64/commit/1d7bdd2c270c5ebde20da8d426223f9352668a3d , and it loads my mempak fine.

My Monaco Grand Prix mempak for testing, select Simulation and Load Career:
https://www.dropbox.com/s/oi5lsvo2sc1mykp/Monaco%20Grand%20Prix_Cont_1.mpk?dl=1

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/d5c43bfcba023bb949802e6fb8f6527fd31fc661 fix it now?

**Comment by Frank-74** [comment]
Fixed.
