### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by Catarax** [project64/project64#1254]
When a game is started 
"Emulation démarée" is not displayed very well, french accents are not supported.

**Comment by Frank-74** [comment]
Google translates Emulation Started to Émulation démarrée.

It looks ok here:
![emulationstarted](https://cloud.githubusercontent.com/assets/11056843/22293774/ca923dc8-e308-11e6-9402-b67aaf0bd50d.JPG)

**Comment by oddMLan** [comment]
Are you using the latest master?

**Comment by Frank-74** [comment]
I'm using the latest release, 2.3.2-202.

**Comment by oddMLan** [comment]
I was aiming the questio to @Catarax :P I know it works right in the latest master.
@Catarax  besides answering what version you're using, what Windows version are you using? What locale?

**Comment by Frank-74** [comment]
@oddMLan I thought you were talking to me, as there have been a few french language commits since the 202 release.

**Comment by Catarax** [comment]
Sorry for the lack of details, when you start in fullscreen by default (in Jabo D3D), it'll goes like this:
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22308827/e5038cee-e348-11e6-9e3a-1fbf711decc9.png)

Do this message could be disabled also? Thanks.

**Comment by Frank-74** [comment]
@Catarax 
Jabo's D3D is a closed source 3rd party plugin.  Nothing can be done about it.  No source code.

**Comment by Catarax** [comment]
Ok, so maybe when starting in fullscreen we could avoid the accents sent to jabo in order to fix the issue (or find the correct encoding).

**Comment by LegendOfDragoon** [comment]
@project64 is this something you could fix?

**Comment by oddMLan** [comment]
The text is displayed by Jabo, so I doubt that he could.

**Comment by project64** [comment]
unfortunately nothing I can do here since it is a bug in jabo's video plugin
