### ISSUE TITLE
Tony Hawk's Pro Skater 2/3 Blink Text in Black Background (Jabo)

### ISSUE THREAD

**Issue by Catarax** [project64/project64#1255]
When you play THPS2/3 in fullscreen and doing some scores.
Some text will blink in the black background. (out of the game screen)

Doing Alt+P reset the data but can come back.

Using Jabo D3D but not in GlideN64 (which I don't use, audio crackles on my side for that game).
And latest official build 2.3.2.202

**Comment by Frank-74** [comment]
Try setting a 4:3 fullscreen resolution, 1024x768, 1280x960.

**Comment by Catarax** [comment]
Can't run at thoses resolutions.
4:3 fullscreen not working.

Also, more information to execute the bug :
- You have to do a long combo, then when the text is large, the blinking text will be stored in background.

**Comment by Fanatic-64** [comment]
This happens on the real console as well, garbage is left in the overscan area: https://www.youtube.com/watch?v=hx6-wcC_OGc I believe Jabo's plugin has a hack for keeping the borders of games clean, but I guess it doesn't work on fullscreen or at certain resolutions.

**Comment by oddMLan** [comment]
Not to mention garbage is being masked by the VI filters on console

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
