### ISSUE TITLE
C-Input Xinput not displayed

### ISSUE THREAD

**Issue by Catarax** [project64/project64#1256]
I have configured the C-buttons to the "B", "Y" Xbox 360 controller and when I go back, theses values are not selected by default:
![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/22271886/4384328a-e297-11e6-8929-f236d84892b6.png)

I can always play using my previous config.
using latest official build 2.3.2.202

**Comment by Frank-74** [comment]
Maybe because you have D-Pad set to C Buttons.

**Comment by Catarax** [comment]
Not related, regression compared to the previous version.

**Comment by k6l2** [comment]
I can confirm this issue still is happening for me in the latest version, using an XBox-one controller.

**Comment by quincytynes** [comment]
Any progress on this, I can set the left and right c buttons fine (although they get reset when I open the config. but trying to assign the c-down just sets the button to 0 in the config.

**Comment by oddMLan** [comment]
fixed with #1626

**Comment by bernhard263** [comment]
Finally, thank you. You're such a god for fixing this.

**Comment by cody-tv-weber** [comment]
I am having this issue with 2.5.2.202.
