### ISSUE TITLE
Doom for N64 permanent loop

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#1259]
Don't confuse this with Doom64

Doom for N64 is a fan made port to the N64 using libdragon. More infos: http://assemblergames.com/l/threads/doom-for-nintendo-64.52471/

I built the Shareware version so I think it's legal to share the rom. If I'm wrong please let me know and I'll remove the rom. 
ROM: [DOOMSHAREWARE.zip](https://github.com/project64/project64/files/730434/DOOMSHAREWARE.zip)

With PJ64 I get the error message "In a permanent loop that cannot be exited...". Some numbers are displayed on screen (they should not appear at all). CPU interpreter does not help
Correct with CEN64 (fully playable)
PJ64:
![doom](https://cloud.githubusercontent.com/assets/7283660/22301144/3ce119c8-e32a-11e6-840d-f2f4b75a2069.png)

**Comment by oddMLan** [comment]
Did you try with Interpreter RSP? (cxd4's RSP or in-built PJ64's RSP set to interpreter)

**Comment by Frank-74** [comment]
I've tried LLE graphics, CPU interpreter, cxd4's static interpreter, with and without semaphore locking.
I get the same blue screen.

**Comment by AmbientMalice** [comment]
I've managed to boot this on one "normal" emulator. Can't remember if it was Mupen64 or PJ64. Had 8MB RAM, Angrylion's, etc. The game ran very fast and scrolled through menus randomly and then crashed.

Seems to work fine with Cen64, as mentioned.

**Comment by weinerschnitzel** [comment]
Would be nice to see this game and other libdragon ROMs supported.

**Comment by loganmc10** [comment]
Just FYI, these games (libdragon) don't use the RSP at all, they should work without any RSP plugin attached.

In mupen64plus, they work with the "pure interpreter" but not the cached interpreter or the dynarec, so it is probably something to do with the MIPS CPU emulation

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
