### ISSUE TITLE
PJ64_NRage controller not plugged in

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#126]
PJ64_NRage doesn't detect my controller, I start Goldeneye and get this screen.

![goldeneye 007 u snap0000](https://cloud.githubusercontent.com/assets/11056843/6317844/74fa1416-ba66-11e4-958b-e8dab6b7d8ea.jpg)

Jabo's and other NRage versions are fine.

Also default plugin overides per game plugin selection.  If PJ64_NRage is default, and I select Jabo in the Game Settings, I still get NRage.  Seems to happen with all the plugins.

**Comment by project64** [comment]
should be fixed in https://github.com/project64/project64/commit/d35846041f4b363c3681de04ba453dcedce56692

**Comment by Frank-74** [comment]
Its fixed now.
