### ISSUE TITLE
1080 Snowboarding (E) + (JU) Recompiler error.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1261]
Reported on the forum here:
http://forum.pj64-emu.com/showthread.php?t=7271

ver 2.3.2.202.
""Trick Attack" mode and "Contest" mode encounter a fatal error every time you are holding Z and Press A (Crouching and doing a jump)."

2017/01/26 12:16:39.473 05236,Error,User Interface,CNotificationImp:DisplayError,Break point found at
.\N64System\Recompiler\CodeBlock.cpp
693
2017/01/26 12:16:48.669 05236,Error,User Interface,CNotificationImp:DisplayError,Break point found at
.\N64System\Recompiler\CodeBlock.cpp
254 

First bp I think is in R4300i_COP1_BC.
No errors with Interpreter.

With (E) and (JU) ROM I can reproduce it by pressing A+B during Trick Attack.  Not with Z+A though.

**Comment by Fanatic-64** [comment]
With (JU) ROM on default settings I can reproduce it by pressing A+B (but not Z+A) as well. Disabling Advanced Block Linking OR changing the Self-Modifying Code Method to Protect Memory fixes it for me. Of the two, disabling ABL appears to have the least performance impact, and has the side benefit of eliminating the stuttering inherent to ABL.

**Comment by Frank-74** [comment]
Thanks.  Guess the RDB needs changing for now.

**Comment by LegendOfDragoon** [comment]
>Of the two, disabling ABL appears to have the least performance impact.

I'm pretty sure ABL + Protect Memory has better performance than No ABL w/o Protect Memory. At least that is the case with Pokemon Stadium 2, iirc.

**Comment by project64** [comment]
basically protect memory means it detects the changes to memory and handles the code change correctly. ABL disabled means that it compile the code early/miss by accident the changes.

ABL disable gets lucky, protect memory finds the right changes ... Protect memory should be the correct setting, unless there is a huge performance hit.

**Comment by LegendOfDragoon** [comment]
What's default settings? I cannot reproduce at all. I'm using (JU) rom and my MD5 is 10C93DD78B695CD32B6938534ED0EDD5. I even used Synchronize cores and never got an error.

**Comment by project64** [comment]
when I looked at it ABL had been disabled in the default settings, so I had to renable that to get the error

**Comment by Frank-74** [comment]
Protect Memory gave a bad performance hit, ABL disabled didn't affect performance hardly at all.  So I disabled ABL in the RDB.

**Comment by LegendOfDragoon** [comment]
What's a guaranteed way to trigger the issue? Having trouble consistently triggering it.

>Protect Memory gave a bad performance hit, ABL disabled didn't affect performance hardly at all.

That's odd, I get better performance with Protect Memory + ABL enabled than when I disable ABL & Protect Memory. I bet you're using GLideN64 :smile: .

**Comment by Frank-74** [comment]
> That's odd, I get better performance with Protect Memory + ABL enabled than when I disable ABL & Protect Memory. I bet you're using GLideN64.

Nope, using default settings and Jabo or PJ64 Glide plugins.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
