### ISSUE TITLE
Good Names missing from .cfg.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1263]
In 2.3.2-200, .cfg has Good Names.  But Good Names are disappearing in .cfg with 2.3.2-202, if I Edit game settings.  Good Name is no longer written at all to .cfg.

Guessing it's caused by https://github.com/project64/project64/commit/bf0ba50dc494f21b91a353c3ab9a926a5699d0d8.

**Comment by Frank-74** [comment]
Just reverted https://github.com/project64/project64/commit/bf0ba50dc494f21b91a353c3ab9a926a5699d0d8, and Good Names are written to the .cfg.

**Comment by project64** [comment]
the value it is writing matches the default .. so the new code matches the default and instead deletes it .. 

with good name we do not want to delete if it matches the deafult .. so it probably needs a check to say if it is good name then ignore the check for deletion
