### ISSUE TITLE
1080 Snowboarding won't start with 4 controls plugged in

### ISSUE THREAD

**Issue by millansoft** [project64/project64#1265]
Hello,

Just to report that the game 1080 Snowboarding won't start with 4 controls plugged in the Nrage window.

Thanks

**Comment by Frank-74** [comment]
Cannot reproduce.

I changed Controllers 1-4 to plugged, and 1080 snowboarding started normally.  Tested on (JU) version.

**Comment by pcca-matrix** [comment]
It does not happen if the fourth controller has no pack plugged , freeze only when rumble or mempak  on Ctrl 4

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
