### ISSUE TITLE
Project64 & .7z roms problem

### ISSUE THREAD

**Issue by millansoft** [project64/project64#1266]
Hello,

If you go to File / Open ROM you will see the *.7z extension as an option to open a rom file, like the .zip one.

But if you try to open a rom compressed with .7z you will get a blank window that just says error, hope it could be fixed.

![pj64error](https://cloud.githubusercontent.com/assets/25391883/22385155/58ddcb58-e4b0-11e6-9849-fb3562bc8e9a.png)

**Comment by JunielKatarn** [comment]
I have confirmed the error (latest build http://hyvart.com/download/project64/ci/0.0.0.549/).
Note, it doesn't happen if you open the rom from within the ROM browser.
![image](https://cloud.githubusercontent.com/assets/4507319/22387765/1769e512-e492-11e6-8283-63679ed24b51.png)

![image](https://cloud.githubusercontent.com/assets/4507319/22387751/09d11484-e492-11e6-92aa-9390d2e722fd.png)

**Comment by trumpetlicks** [comment]
I have this problem also.  It goes further.  I have many .7z files each with multiple .z64 files within (for multiple versions, etc...).  I am finding that when the browser algorithm goes through the folder of my .7z files, > 75% of my files don't ever show up in the list.  I have tried doing a single open of a file and get the same result here.  I do find that if I extract the .7z file into its own folder and turn on recursive folder search in the options, .7z files that resulted in no addition to the file browser, would show up after having decompressed them prior to refreshing the list.  I think what is going on here is that the algorithm opens the .7z file, searches the first file within and if it matches one of the checksums it continues.  If the first file doesn't match one of the known checksums it simply moves out of that .7z file and moves on.  If it is decompressed however, the .z64 files are there directly to be checked so it checks them all.

To be clear, I think that there is some condition that it choking the checking of ALL files within a compressed file.  In reality it should be checking ALL files within each compressed file.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened

**Comment by RinMaru** [comment]
this is still an issue
