### ISSUE TITLE
pjutil::DynLibCallDllMain() not needed?

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1271]
In source it says, jabo had a bug so I call CreateThread so his dllmain gets called again.

I commented out all instances of pjutil::DynLibCallDllMain(), and Jabo's 1.6.1 and 1.7 plugins are still working ok.  Was this just for original 1.6 plugins?

**Comment by project64** [comment]
it might even been from earlier than that .. it was he store the histance on dll main .. but then reset it somehow .. so adding a new thread temporarily reset his use of hinstance .. yes it might no longer be needed especially with the phasing out of jabos plugins
