### ISSUE TITLE
How to build the Android version?

### ISSUE THREAD

**Issue by TheEssemCraft** [project64/project64#1273]
I downloaded Android Studio, but I can't seem to be able to build PJ64. How do I do so?

**Comment by TheEssemCraft** [comment]
Anyone? It's been 3 months already.

**Comment by project64** [comment]
I need to fix up things for android studio .. I been using eclipse.

I need to write up proper instructions .. I guess I was expecting to move it to over android studio at some point so never have.

**Comment by TheEssemCraft** [comment]
@project64 Oh, ok. Thanks!
