### ISSUE TITLE
AziAudio integration

### ISSUE THREAD

**Issue by Azimer** [project64/project64#1277]
@project64 - If I were to fully integrate AziAudio into the Project64 workflow.  Would you accept the PR?

I am working hard to complete the plugin so I can move on to other things.  I believe Project64 is the only active Nintendo64 emulator that uses the plugin spec.  As such, once I cease active development, it will only make sense from my perspective to integrate and allow the only project to use it to maintain it going forward.

We can discuss more offline if you'd like.  I have been in the freenode IRC channel quite a bit lately.  If this doesn't interest you, let me know and close the issue.

Thanks!

**Comment by project64** [comment]
As discussed feel  free to create a pull request and I will merge it

**Comment by Azimer** [comment]
Will do when I get us to a release version.  Thanks!
