### ISSUE TITLE
Mario Party 2 Garbage Text

### ISSUE THREAD

**Issue by wildgoosespeeder** [project64/project64#1278]
- Windows 8.1 Pro 64-bit
- 12GB RAM
- Intel Core i5-3210M@2.5Ghz

- Project64 v2.3.2.202 or Project64 v2.2
--angrylion (June 2015), GLideN64 Public Release 2.0, or Glide64
--AziAudio 0.56 or default audio plugin
--NRage 2.3c or default input plugin
--HatCat RSP or _RSP 1.7.dll_

I verified them with GoodTools and they are good dumps ((U) [!]). Here's the error I am getting:
![garbage text](https://cloud.githubusercontent.com/assets/18543809/23336364/dad38f9a-fb93-11e6-8668-6c6aa6758efa.png)
![nmwe0000](https://cloud.githubusercontent.com/assets/18543809/23445494/75bac3f6-fe01-11e6-9836-cc9b2eeaca02.png)

MD5 for Mario Party 2:
BA248C51CFAC5CDECC9202772B1E1F73

All you have to do is select a board and wait for dialog to show up, such as to decide to take a fork in the game board path or when it is time to jump at the dice roll. Other dialogs display fine, such as during Chance Time or minigames. No settings change the outcome (interpreter vs. recompiler, plug-in switches, etc.). I tested this in Not64 for Wii (homebrew) and the text displays correctly, despite the flicker.

Mario Party 1 and 3 don't seem to have this problem.

**Comment by theboy181** [comment]
RSP issue? you test with zilmars yet?

**Comment by wildgoosespeeder** [comment]
[Mario Party 2 (U).pj.zip](https://github.com/project64/project64/files/809790/Mario.Party.2.U.pj.zip)
Save State

@theboy181 Yup, doesn't change anything.

**Comment by theboy181** [comment]
Was unable to load this save with my version ..

**Comment by wildgoosespeeder** [comment]
@theboy181 It's using Zilmar's RSP plugin. I found out elsewhere that his plugin has better compatibility than HatCat's.

**Comment by theboy181** [comment]
good to know!

**Comment by theboy181** [comment]
Tested with the better RSP.. crashed PJ.. 

not too sure whats going on..

**Comment by wildgoosespeeder** [comment]
I'll switch back over to HatCat's. It was more stable with save states despite better compatibility.

**Comment by wildgoosespeeder** [comment]
Custom config for _Project64.cfg_
[9EA95858-AF72B618-C:45]
HLE GFX=0
Plugin-RSP=RSP\RSP 1.7.dll

**Comment by theboy181** [comment]
Are you suing a current PJ that has been installed to an older PJ folder? 
reason I has is because Luigiblood added N64DD code, and it messed a few things up.. I would recommend that you start a fresh PJ dir.

**Comment by wildgoosespeeder** [comment]
This has been happening as early as v2.2, before N64DD became a thing for PJ.

**Comment by LegendOfDragoon** [comment]
I also can't get that save state to load.. I noticed your md5 checksum is diff than mine though.

Mine is 04840612A35ECE222AFDB2DFBF926409

**Comment by wildgoosespeeder** [comment]
@LegendOfDragoon What's your region? Mine is U.

**Comment by LegendOfDragoon** [comment]
Mine is U as well.

**Comment by wildgoosespeeder** [comment]
@LegendOfDragoon Used GoodTools and it says it's a verified good dump ([!]).

**Comment by wildgoosespeeder** [comment]
[Mario Party 2 (U).pj.zip](https://github.com/project64/project64/files/809830/Mario.Party.2.U.pj.zip)
Here's a different state using HatCat's RSP and in HLE Graphics mode. Use the first listed plugins up above for each type.

**Comment by theboy181** [comment]
Would love to link you to a good ROM . . However, is it possible you have faulty HW? RAM perhaps?

**Comment by wildgoosespeeder** [comment]
@theboy181 Doubt it.

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/23448250/af3774a0-fe04-11e6-962d-26b772084586.PNG)


Your hash doesn't match the good sets..

**Comment by wildgoosespeeder** [comment]
@theboy181 How so? I thought that is what [!] meant? Verified good dump?

**Comment by theboy181** [comment]
Second Save is working. 
and its got messed GFX. 
Are you always testing with a save, after changing plugins?

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/23448403/9e9d3aac-fe05-11e6-9660-18a9ed65f450.PNG)

**Comment by LegendOfDragoon** [comment]
@wildgoosespeeder sorry i didn't realize mupen's algorithm was different. Tried using PJ64's and it matches. So that means we do indeed have the same ROM.

**Comment by wildgoosespeeder** [comment]
@theboy181 I do save states and a fresh start (no save state) and the graphics don't change.

**Comment by theboy181** [comment]
[Mario Party 2 (U).pj.zip](https://github.com/project64/project64/files/809863/Mario.Party.2.U.pj.zip)
Test this state please..  I'm not getting this issue,

**Comment by wildgoosespeeder** [comment]
I can confirm the state to work and produce correct results.

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/23448703/5b92b960-fe07-11e6-8ea9-0914cccdf6b0.PNG)
can you confirm your settings are the same?

**Comment by theboy181** [comment]
Fresh PJ directory.. there is a bug in older PJ too.. it would destroy your config..

**Comment by wildgoosespeeder** [comment]
Settings don't affect anything (why would they?).

**Comment by theboy181** [comment]
OMG>. Good night. . Just use the save state I shared and close this thread.. ;)

**Comment by wildgoosespeeder** [comment]
Only works with Pirate Land. I need a proper fix somehow. Just not sure what is causing this bizarre issue. Probably need @project64 to diagnose this better or something.

**Comment by theboy181** [comment]
are you saying that if you exit the current game from the game and play a different land you have the issue? 

I'm not talking about rebooting the emulator via F1 here..  

Please quite the board you are on via the in game menu and load another one. 

I believe you have an incorrect core setting. When you load my save you would be loading my internal core settings too. (some of them)

**Comment by wildgoosespeeder** [comment]
No reset button pressed. Exit the game through the in-game menus, go to a different land, and the garbage returns.

**Comment by cxd4** [comment]
Saved states are hardly effective as a solution.

If you exit the game, go back to the same land as you were already on, the garbage probably returns.

What you need to know is theboy181 and RPGMaster are using the latest builds of Project64 from source, while you're using 2.2.  Interpreter operations have probably had some bug fixes issued since then.  You need to be able to see the correct result without saved states, and people troubleshooting this issue should be relying on exact steps from the point of boot or hard reset, not saved states.

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/23469908/defadc18-fe59-11e6-9517-236772c97777.PNG)


Sorry, I did test the highest version above. I think the issue is settings. Please try a fresh directory.

**Comment by LegendOfDragoon** [comment]
In the first post, it says that he tried "Project64 v2.3.2.202 or Project64 v2.2". I tried different builds I had kept around and could not reproduce the issue. I agree with theboy181's suggestion.

Also @wildgoosespeeder , perhaps you could upload your config file, if you don't mind.

**Comment by wildgoosespeeder** [comment]
@cxd4 No, I am using 2.3.2.202.

@LegendOfDragoon Which ones? There's many for both the emulator and plugins I use.

**Comment by Azimer** [comment]
Random thought -- not that I want to get too involved.  Do you have any cheats enabled?

**Comment by project64** [comment]
you could try protected memory .. might be a self mod problem

**Comment by wildgoosespeeder** [comment]
@Azimer Nope.

@project64 Doesn't work.

**Comment by project64** [comment]
hmmm my suggestion is not the best, better checking if interpter in the core (project64) and RSP are both set to interpter.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon Which ones? There's many for both the emulator and plugins I use.

@wildgoosespeeder sending your emulator cfg file would be sufficient :smile: .

**Comment by theboy181** [comment]
I checked your settings against mine, they are the same.

I'm at a loss at this point, and feel you should attempt a clean directory install. If this doesn't fix the issue, I would try another computer if possible.

I tested from a default install, with a fresh directory and have no issue.. you are having this issue with all plugins so I would think that the issue is some corrupt setting.

Let us know though. I'm intrigued.

**Comment by theboy181** [comment]
Hmm. I think I may have a clue. .
using an older version of Zilmars RSP and are always forcing it for that game.. 
2.3.2.202 should of been packed with 1.7.3.167 RSP.. 

Please re-download and start a fresh install, or change the RSP to use system then test other RSP plugins.

**Comment by cxd4** [comment]
>@cxd4 No, I am using 2.3.2.202.

Oh sorry.  I really didn't bother reading this entire thread; I pretty much just assumed you were using the latest official, pre-compiled release of Project64, instead of compiling it yourself.  No idea how you got 2.3.2.202.  EmuCR maybe, doesn't matter.

>Sorry, I did test the highest version above.

Sorry, you didn't pass elementary reading classes in school.

Don't throw in the word "not" where I never added a negative.  I said I thought you and RPGMaster are using versions newer than his, not you and RPGMaster are "not" using newer versions than his.  See, the difference is the added word "not", which I never used.  Damn you're ridiculous.

>I agree with theboy181's suggestion.

It's not bad to use saved states to jump into proving an issue exists somewhere, or reproducing it.

All I'm saying is it's not effective at debugging or solving the issue once you do see it.

And it's not simply theboy181's suggestion; I wasn't blaming him or "his" suggestion.  You suggested save states before he did in the RSP thread on PJ64.

**Comment by theboy181** [comment]
@wildgoosespeeder 

Sounds like @cxd4  is spending some time trying to insult us here. I guess I will let him support you on this issue. I don't want to waist my time having to read such garbage in this git post.  PM me with your findings though.. 

I'm sure you will figure it out.

chow.

**Comment by wildgoosespeeder** [comment]
@cxd4 http://forum.pj64-emu.com/showpost.php?p=68873

@project64 Does nothing to fix the problem.

@LegendOfDragoon Attached.
[Project64.txt](https://github.com/project64/project64/files/812945/Project64.txt)

**Comment by wildgoosespeeder** [comment]
New development. I think I know what is causing the issue. The *.eep. Question is why...

http://www.zophar.net/savestates/n64/mario-party-2.html

**Comment by cxd4** [comment]
Good find.

This happened with _Super Smash Bros._, too.  Even with angrylion's I had a margin full of garbage pixels all the way to the left right at booting into the intro, and changing the SRAM save file fixed it.  It might have been screen alignment settings or something else I set in the game options.

**Comment by cxd4** [comment]
LOL!  I just had a thought.

This is so ironic.  I was recommended not using saved states, but steps-to-reproduce from boot from a **save file** that will let you reach those boards in the game.  So even though I wasn't arguing this point to begin with, RPGMaster and theboy181 were wrong all along for taking the save state approach as far as that went as well.  Not what I was trying to argue...but just happened to be an extra reason on the side.

**Comment by LegendOfDragoon** [comment]
I was referring to "I think the issue is settings. Please try a fresh directory.", when I said that I agree with theboy's suggestion.

**Comment by cxd4** [comment]
Well you were; I wasn't.  You asked for a save state on the forum before theboy181 did in this issue.

**Comment by theboy181** [comment]
@wildgoosespeeder 

Great stuff man. I guess we would of had it sorted a little quicker if you tried a fresh directory sooner. How did you stumble up on the .epp file as being the problem?

**Comment by theboy181** [comment]
BTW did you use the link I sent for the private server? looking forward to adding you to the group.

**Comment by wildgoosespeeder** [comment]
@theboy181 I tried the same file and folder structure on a different computer and that didn't make a difference. Then I just deleted the save file only. I don't know how that idea came to me, but it just did. Your fresh directory suggestion wouldn't have pinpointed the issue being the save file right away (too many variables would have been altered, and not the programming kind :P ).

**Comment by theboy181** [comment]
I'm almost certain that a fresh directory would have proven that the issue wasn't PJ, and the thread could of been closed.

**Comment by wildgoosespeeder** [comment]
A fresh directory would have fixed the issue, sure, but it would still be uncertain what was causing the issue in the first place. I got lucky finding out the culprit and it was a particular and curious *.eep file from Zophar's Domain. It still needs to be evaluated if the save is corrupted or if PJ is handling saves improperly.

**Comment by project64** [comment]
can this be close?

**Comment by wildgoosespeeder** [comment]
Things aren't 100% verified. Leave open. Maybe someone else can see what's up with MP2's save from Zophar's Domain.

**Comment by celerizer** [comment]
I saw this problem and it was fixed by loading the European version of the game, setting the in-game language to English, then reloading the US version. The Zophar save was made for the EU version of the game, and the game is reading in garbage for translations of small strings that don't exist on the cart. You can even observe this by loading the save in the Virtual Console version.

I know this topic is ancient but I had the same experience trying multiple RSP plugins and scratching my head about it.

**Comment by wildgoosespeeder** [comment]
Thanks @celerizer for getting this issue cleaned up! I tried this myself and got things working again. I thought that there was an emulation mistake somewhere and somehow. I was wrong entirely. Just the save seems to have been set to Spanish with the NTSC-U having no such language option. Lesson learned.

This can be closed @project64.
