### ISSUE TITLE
F-Zero X Expansion Kit Doesn't Work

### ISSUE THREAD

**Issue by wildgoosespeeder** [project64/project64#1288]
- Windows 8.1 Pro 64-bit
- 12GB RAM
- Intel Core i5-3210M@2.5Ghz

- Project64 v2.3.2.202
--angrylion (June 2015), GLideN64 Public Release 2.0, or Glide64
--AziAudio 0.56 or default audio plugin
--NRage 2.5.2.202 or default input plugin
--HatCat RSP or _RSP 1.7.dll_

I verified them with GoodTools and F-Zero X is a good dump ((J) [!]).

I use @LuigiBlood 's method and settings to get F-Zero X Expansion Kit working with the Japanese F-Zero X and it doesn't work. The base game boots fine, just not with the EK. I tried a fresh install @theboy181 and that doesn't fix the problem. Everything else when it comes to 64DD emulation is working fine. I can play Mario Artist with no issues.

**Comment by LuigiBlood** [comment]
That doesn't say what's happening.

**Comment by wildgoosespeeder** [comment]
What more do you need?

**Comment by LuigiBlood** [comment]
Does it not detect the Expansion Kit? Is it just F-Zero X booting?

**Comment by wildgoosespeeder** [comment]
I thought I said that in the first post?

> The base game boots fine, just not with the EK.

**Comment by LuigiBlood** [comment]
Oh, so black screen?

**Comment by wildgoosespeeder** [comment]
No, just base game screen. I don't see course edit or machine edit.

**Comment by LuigiBlood** [comment]
That's the kind of detail I want, because until now, I had no idea what was really going on.

It just works by right clicking F-Zero X in the ROM browser of Project64 and select Load game with disk. And load in the EK disk... and make sure 64DD IPL 1.2 is loaded. But I assume you did that?

**Comment by wildgoosespeeder** [comment]
Yes.

**Comment by LuigiBlood** [comment]
Check F-Zero X (J) settings and see if the RAM size is 8MB. If it's 4MB, change it to 8MB and do it again.

**Comment by wildgoosespeeder** [comment]
Already done that.

**Comment by LuigiBlood** [comment]
Then I absolutely don't know what happened.

**Comment by wildgoosespeeder** [comment]
Is there any debug information I can send?

**Comment by LuigiBlood** [comment]
I have no clue D:
I'm not a N64 expert despite the impression I give.

**Comment by wildgoosespeeder** [comment]
But didn't you assist Project64 to be able to emulate the 64DD, code and all?

**Comment by LuigiBlood** [comment]
I literally just ported MAME code and improved it. That's all.

**Comment by wildgoosespeeder** [comment]
I have an idea: http://www.pj64-emu.com/downloads/func-startdown/125

Use that version and see if you get the same results as me.

**Comment by LuigiBlood** [comment]
The version I use currently is like, slightly before but there's no reason it doesn't work anymore... I'll try anyway but I doubt it won't work for me.

**Comment by wildgoosespeeder** [comment]
It's possible the code got broken somewhere during that time of improving Project64 further.

**Comment by LuigiBlood** [comment]
...actually nvm yes the code is broken.

**Comment by LuigiBlood** [comment]
So don't use that version use my build instead.

**Comment by wildgoosespeeder** [comment]
So I guess the version I am using introduced a regression?

**Comment by LuigiBlood** [comment]
Yup. Guess I gotta figure it out.

**Comment by LuigiBlood** [comment]
So after some checking, I can definitely say this is the root of the cause:
https://github.com/project64/project64/blob/4cf5a549997a33ce941703d8be373a45ff2606fb/Source/Project64-core/N64System/N64Class.cpp#L285

It would get rid of g_DDRom... except it shouldn't else it disables everything about the 64DD and makes F-Zero X + Expansion Kit not work.

**Comment by wildgoosespeeder** [comment]
Hope to see the necessary changes committed for the next Win32 binary release. 👍

**Comment by project64** [comment]
whoops sorry, I probably was trying to make sure things were freed .. and I guess in this case it shouldn't be .. either do a pull request or I will fix it up in like 5-6 hours.

**Comment by LuigiBlood** [comment]
I'll do a PR soon.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/81020b124951b44f68870686e970d99edf3caaa7 fix it?

**Comment by LuigiBlood** [comment]
Well since I didn't see it just now I was doing it myself but yes this should be enough.

**Comment by project64** [comment]
Can this be closed now?

**Comment by wildgoosespeeder** [comment]
Only if the code change makes FZXEK work as intended.

**Comment by LuigiBlood** [comment]
It does.

**Comment by LegendOfDragoon** [comment]
I guess this can be closed?
