### ISSUE TITLE
GUI stuff

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1295]
Unable to un-map Crtl-A from the hotkeys, and remap to another shortcut.

If you delete the hotkey from the lists and then try to remap it to "Always on top" (it's original mapping)  it will say its already mapped even know that the key is not in use, and was just mapped there.

**Comment by theboy181** [comment]
@LuigiBlood do you know it this is a regression from adding the new commands for DD items?

**Comment by LuigiBlood** [comment]
Try to delete Project64.sc3 and see what happens?

**Comment by theboy181** [comment]
![image](https://cloud.githubusercontent.com/assets/9299743/24335008/3e03943c-122a-11e7-9fe1-c8b37792c788.png)


Looks like removing that file, the issue still happens. 

Are you the guy that knows how to fix it? Any idea what is causing it?

**Comment by Frank-74** [comment]
Are you deleting the mapping from both fullscreen and windowed?

I raised the issue of having two sets of mappings causing this sort of problem before.

**Comment by theboy181** [comment]
@Frank-74 

removed both.. the funny part is you cant add it back..

**Comment by LegendOfDragoon** [comment]
@theboy181 are there still issues remaining?

**Comment by theboy181** [comment]
Guilty of not following up.. thanks..
