### ISSUE TITLE
Moar GUI stuff

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1297]
More of a request.

Would it be possible to have error boxes always top level? this would make them more efficient to deal with. I am unsure if this is handled by PJ64 of the plugins. 

Might not even be possible.

**Comment by project64** [comment]
always on top? What message box hide?

**Comment by theboy181** [comment]
They are the message boxes that plugins spit out, and the debug info when PJ has an issue..

**Comment by project64** [comment]
which particular message boxes?

**Comment by theboy181** [comment]
The debugger msg boxes can do this.
