### ISSUE TITLE
x64 build crashing on startup

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#1298]
Last working build that i have here is from 19 January, some change that happened between the days January 19 and 22 broke the x64 build, I can't say precisely which change because I only have one build from January 19 and another from January 22, the last build that works here is from January 19.

**Comment by grimpunch** [comment]
Hi, 
Can you confirm this still happens on a build from latest master?
Thanks.

**Comment by JunielKatarn** [comment]
Try this recent build: http://hyvart.com/download/project64/ci/0.0.0.575/Win64.zip

**Comment by superceleron** [comment]
same problem here even with newer builds!

**Comment by cxd4** [comment]
Worked fine here under WINE.

To be fair, though, it did fail to launch on native Windows.  I guess Microsoft just isn't as good at emulating "their" operating system as WINE is.

**Comment by project64** [comment]
once I get audio sorted out, I will be looking at bit more at 64bit

**Comment by Frank-74** [comment]
I built 64-bit and it launches fine.  For 64-bit build you need to delete the manifest or edit it for x64.  It's set to x86 which causes startup crash.

**Comment by oddMLan** [comment]
Just redo PR #720 and a proper manifest will be generated during compilation time depending on the processor architecture

**Comment by cxd4** [comment]
http://www.dictionary.com/browse/manifest

**Comment by oddMLan** [comment]
Cannot reproduce anymore
