### ISSUE TITLE
Glide64 2.2.0.999 has fullscreen problems

### ISSUE THREAD

**Issue by naddel81** [project64/project64#1300]
Hi,

just tested the newest version and it does not do fullscreen properly. games are cut off on the right side and the screen is not really centered. it does not occur on the previous version.

**Comment by Frank-74** [comment]
Just reproduced it with full screen set at 1366x768, the default max setting for my laptop.  Screen is stretched wider, and cut off on the right.
![glide64_twine_01](https://cloud.githubusercontent.com/assets/11056843/24414072/39e1d204-13d5-11e7-88b2-a4005d8d11a1.jpg)

It's ok at 1024x768.  Tested with TWINE and Monaco Grand Prix.

**Comment by naddel81** [comment]
thanks for testing! can we report that error to the creator?

**Comment by project64** [comment]
so much code cleaning needed for glide. I will hopefully look at this soon

**Comment by oddMLan** [comment]
Nice way to troll Zilmar lmao
But no, he rather wouldn't touch GLideN64 with a 10ft pole for god only knows what reasons 😛

There is already a bug report for that on GLideN64's bug tracker, here: https://github.com/gonetz/GLideN64/issues/867

**Comment by naddel81** [comment]
didn't want to offend anybody. sorry to zilmar if I did. just wanted to know what caused the graphical glitch and how to get rid of it.

**Comment by AmbientMalice** [comment]
@naddel81 Angrylion's plugin behaves the same way. It's probably supposed to look like that. A real N64 doesn't start outputting video immediately, so you see whatever is in the framebuffer at boot.

**Comment by project64** [comment]
I do need to do some more testing in to the VI registers to work out when the cfb should be shown .. yes this is showing memory that is the cfb buffer, where it shows blank on a real n64

**Comment by Frank-74** [comment]
@naddel81 Issue is fixed here now.  Full screen at 1366 x 768 now shows correctly.

**Comment by LegendOfDragoon** [comment]
@naddel81 can you test this? I'm guessing it's fixed.
