### ISSUE TITLE
GlideN64 Fullscreen showing black borders?

### ISSUE THREAD

**Issue by naddel81** [project64/project64#1302]
Hi,

I really love GlideN64 for its remarkable 16:9 feature. It works amazingly well in some games with minor pop-ins. But regardless of which mode I use, there are always those annoying black borders:

![img_5830](https://cloud.githubusercontent.com/assets/16635406/24664223/65346f0e-195a-11e7-8f88-5e3acbb85f27.JPG)

Those do not show in Glide64 or Jabos Plugin. How can I make GlideN64 stretch out to the full screen and use all its potential?

Best wishes!

**Comment by baptiste0602** [comment]
Hello, GLideN64 isn't develop by this team. please use https://github.com/gonetz/GLideN64 to report issues with GLideN64

**Comment by naddel81** [comment]
thanks! posted it there.

**Comment by oddMLan** [comment]
Please close this issue :p
