### ISSUE TITLE
Can't map Load State to F9

### ISSUE THREAD

**Issue by ZedM** [project64/project64#1309]
Currently, I've reassigned "Cheats" which was previously F9 to F11. F11 was previously Load State. I'm trying to make it so that F6 is Save, and F9 is Load, however, F9 isn't reassigning. It's continuing to say that F9 is bound to Cheats even though the only thing bound to Cheats is F11. | PJ64 2.1 | Don't suggest to reset PJ64, I've already reset it.

![wtfpj64-1](https://cloud.githubusercontent.com/assets/28122384/25509255/9ba2dbb0-2b85-11e7-8140-6a3905ed5b16.PNG)
![wtfpj64-2](https://cloud.githubusercontent.com/assets/28122384/25509258/9f22a8a6-2b85-11e7-9b29-3c36ad31c5ee.PNG)

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/0ed144f39d4d8d127ece2ceb4f896795d2725507 fix it?

**Comment by tony971** [comment]
> does 0ed144f fix it?
yes.
