### ISSUE TITLE
Glide64 2.2.0.999 crashing when changing settings

### ISSUE THREAD

**Issue by Legiaoday** [project64/project64#1310]
The plugin simply crashes when 'any' of the settings is changed.

![untitled](https://cloud.githubusercontent.com/assets/25484098/25553838/860fba06-2c94-11e7-8f1f-28aa2627e6af.png)

Even though the emulator crashes, when you restart the emulator the settings appear to be saved. It's annoying because every time you need to change any graphic setting, the emulator will crash.

**Comment by frankyfife** [comment]
I can confirm that. It's also impossible to enable fullscreen, no matter witch graphics plugin used.

Win10 Creators Update
Project64 Git (2017/04/29)

Error from Logfile

2017/04/30 13:13:28.620 05360,Error,User Interface,CNotificationImp::DisplayError,Fatal Error: Stopping emulation

**Comment by Legiaoday** [comment]
Frankyfife, while the emulator is running what happens when you press ALT + Enter?
For me it goes into full screen normally. I'm also using Windows 10 version 1607 build 14393.693.

Also, where can I see that log? The log located at "C:\Program Files (x86)\Project64 2.3\Logs\Glide64.log" is always blank to me.

**Comment by frankyfife** [comment]
ALT+Enter gives me an error message (the screenshot below). the logfile is located in the logs subfolder.

My Specs.

Core i7 7700k
Nvidia 1080 Ti
32 GB of RAM

![unbenannt](https://cloud.githubusercontent.com/assets/16177808/25565997/06a1e016-2dd2-11e7-89da-e260ea8ba420.JPG)

**Comment by Legiaoday** [comment]
Oh thanks, I was looking at the wrong log.
Mine always throws this exception 15 times, restarts the emulator and then throws another new exception, sometimes it's called 'Unhandled R4300i opcode at: 80000004 bnez 1, 0xA4000118 Stopping Emulation !', other times it's a different error.

![untitled](https://cloud.githubusercontent.com/assets/25484098/25566138/103b8960-2daa-11e7-9773-6ed42971f880.png)


But yeah, this plugin needs to be looked at, there's some weird quirks going on.
Aside from that, it's a pretty good video plugin, at least to me this version of Glide64 has the highest compatibility with games such as Jet Force Gemini, Excitebike 64 and Beetle Adventure Racing.

I compiled this latest PJ64 version using Visual Studio 2015, but I'm not a C++ programmer, so I can't do much other than report errors.

**Comment by Frank-74** [comment]
Plugin was renamed to Project64-Video on the 26th April.  Before 26th there was no crash.

It's a regression with making video plugin into one project it seems.

I get crash anytime I try to close the config dialog.  It's a gui rather than settings issue, as it crashes with not changing any settings and pressing cancel.

**Comment by Legiaoday** [comment]
Mine only crashes if I press 'Ok' or 'Apply'. 
If I press 'Cancel' or close it using the 'X' on top right of the window nothing happens.

Speaking of which, what GUI does PJ64 use, WTL?

**Comment by Frank-74** [comment]
Yes, PJ64 uses WTL.  And I cannot get rid of the error box re-appearing.  I have to Ctrl+Alt+Del and close Project64 from the task manager.

**Comment by project64** [comment]
ok https://github.com/project64/project64/commit/a308ce23ca5265a6568d654192fa7c3495f4fb80 should fix it

basically I added removing it registration of notification in the destructor. This is correct. The problem was the way the settings update was checking for changes would copy the settings object and then try to unregister, since it was a copy it never registered and was getting a break point on unregistering something that never registered.

**Comment by Frank-74** [comment]
It's fixed here with that commit.

**Comment by Frank-74** [comment]
I'm getting a crash going full screen.

**Comment by Legiaoday** [comment]
It fixed the error when saving the video settings, but now I'm getting this error when going full screen.
And now I'm also unable to save or load settings for the N-Rage Input v2 (XInput) plugin for some reason.

**Comment by Frank-74** [comment]
Crashes with Jabo when going full screen as well.  It was fine on the 27th April.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/a7fb56a3a6a05b25810950a610c8145effe28f56 may fix the fullscreen issue

**Comment by Legiaoday** [comment]
Very nice, now everything is working accordingly.
Graphic settings is being saved with no problems.
Full screen is working as it should.
My previous N-Rage settings problem is also gone.

**Comment by Frank-74** [comment]
Fixed here too.
@Legiaoday Issue can be closed now.

**Comment by Legiaoday** [comment]
If no one else has any problem, this issue is solved.
