### ISSUE TITLE
Patch for long WMI query caused by nrage input plugin - changes provided by Maniac

### ISSUE THREAD

**Issue by Squall-Leonhart** [project64/project64#1311]
Attached is a diff which ensures Xinput WMI query is performed only against game controllers and not against keyboards or mice.

https://gist.github.com/Squall-Leonhart/40eb4380d097fc9672df75ffa1f4d1d1

**Comment by Frank-74** [comment]
Why not just do a pull request?

**Comment by Squall-Leonhart** [comment]
i don't git.

**Comment by oddMLan** [comment]
well then




git gud

**Comment by Squall-Leonhart** [comment]
how about you both fuck off.

**Comment by cxd4** [comment]
Just like the good old days.

**Comment by Squall-Leonhart** [comment]
aye

**Comment by Squall-Leonhart** [comment]
closed by ManiacDC's pullrequest.

**Comment by LegendOfDragoon** [comment]
@project64 you can close this issue since it's fixed.

**Comment by theboy181** [comment]
Hey man, how are things?
