### ISSUE TITLE
(v2.3.2) 1080 Snowboarding (JU) Freezes During Stunt

### ISSUE THREAD

**Issue by BrendonIrwan** [project64/project64#1315]
**When**
This happens under the game's training mode.

**What**
When a stunt is performed successfully, the game freezes before the voice-over and text showing the performed stunt. The emulator itself is still alive; I can still fiddle around the GUI.

**Workaround**
Hard reset ([shift + F1]), turn to full screen anytime before the game's training begins. (Un)pausing the emulation does not work.

**Runtime**
The game was the first to load (no other games were loaded before this), and the workaround works at the first hard reset--if done correctly.

**Diagnosis**
The problem is reproducible with both Glide64 and Jabo's D3D8. I'm assuming it's either an issue with Jabo's DirectSound plugin or the core.

There are many other issues as well but I can't report them in details.

**Comment by Frank-74** [comment]
Already reported here: @1261

Disable advanced block linking in the options to fix it.

**Comment by Yui12** [comment]
Ah, this had to be been connected to that issue of the game freezing in the middle of the Air Make stunt course.
