### ISSUE TITLE
Project 64 crashes on loading any Rom

### ISSUE THREAD

**Issue by CLAV88** [project64/project64#1316]
I am assuming this must have to do with some of the most recent commits, as I don't see any mention of this issue with the the issue tracker. 

The problem is that, after a few good uses of project64 the program simply stopped working. It loads to the directory where my games are all found but when I try and load any one of those games the whole thing crashes. I've installed/re-installed/repaired several times. Can't get this issue fixed.

**Comment by JunielKatarn** [comment]
What version are you using?

**Comment by LostmanEX** [comment]
I've had this same problem on the latest release version, 2.3.2, I've tried a few things including disabling DEP. It says there's an error with ntdll.dll and the Project64.log says:
03436,Error,User Interface,WinMain,Exception caught (File: ".\main.cpp" Line: 87)
