### ISSUE TITLE
System Plugin overides Config:Game/Plugins selection.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#132]
Can no longer select different plugins for each game in 2.2.

I had Jabo's DSound 1.7.0.7 as default system plugin, selected Azimer's HLE Audio v0.60 WIP 2 for GoldenEye and checked HLE Audio.  When starting the game there is no sound, so I configue audio and its Jabo DSound that has loaded.

**Comment by AmbientMalice** [comment]
Likely PJ64 needs administrative rights.

**Comment by Frank-74** [comment]
No, I have full admin rights already.  If I run the 2.1 exe in the same folder as the 2.2.0.1 install, it works normally.  There's a regression in the current build.

**Comment by Lithium64** [comment]
I tested and the same issue happens here

**Comment by Frank-74** [comment]
Just compiled the branch from 19 February 2015, 00:03, and the same issue is there, have to go back further to see when it was introduced.

**Comment by Frank-74** [comment]
It was ok on the 10th Feb, https://github.com/project64/project64/tree/3e24a54130f74d69a0b19cefbe9b527b49d9b771

May have happened with this commit: Try to get dynamic plugin change working (https://github.com/project64/project64/commit/c973db8e350bb97797c5ed1d1d5727f22ffc14ca)

**Comment by Frank-74** [comment]
Yes, I can confirm this commit broke the config:Games/Plugins selection.
https://github.com/project64/project64/commit/c973db8e350bb97797c5ed1d1d5727f22ffc14ca

**Comment by project64** [comment]
changing it so we can dynamically change the plugins was a good fix .. but yes this side effect is not the best, I will be trying to work out why it has that side effect and the best way to fix it tonight.

**Comment by project64** [comment]
ok I made a change that helped a bit more with game plugins (https://github.com/project64/project64/commit/3fac386d550b4a1745388ded878d0ca503cf90d5). Does this fix your issue?

I only really did really basic testing so there could still be issue, if so what do you do to generate the issues.

**Comment by Frank-74** [comment]
Ok, cheers.  I'll compile and test.  I tried myself to fix it last night, but broke dynamic changing in the process.

**Comment by Frank-74** [comment]
Seems to be fixed now.  I tried to break it, but its all working. :)
