### ISSUE TITLE
Cannot start Mario Tennis with Recompiler

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1324]
Tested a few older builds I have.  27th April no errors.  30th April I get the error below, but it continues.  Today, I get error below but game doesn't start at all.

2017/06/17 01:50:28.441 05904,Error,User Interface,CNotificationImp::DisplayError,Does beqz	a0, 0x80032D5C effect Delay slot at 80032D54?
2017/06/17 01:50:30.831 05904,Error,User Interface,CNotificationImp::DisplayError,WTF

Branch
NextInstruction = 3
2017/06/17 01:50:32.642 05904,Error,User Interface,CNotificationImp::DisplayError,WTF

Branch
NextInstruction = 3

Only commit to PJ64 between no errors and error, is https://github.com/project64/project64/commit/26ab7f6b708671282167957076c5961db4a039e7.
Other commits are for Video.

Edit: It starts fine with Interpreter.  Same error above with Synchronize cores.

**Comment by Nekokabu** [comment]
It is similar to https://github.com/project64/project64/issues/670

**Comment by Frank-74** [comment]
@Nekokabu Same issue it seems, no errors with debugger disabled or ABL disabled.

**Comment by Frank-74** [comment]
Same as issue #670, closing...

**Comment by WinUser-Generic** [comment]
What fixed to me 
![image](https://github.com/project64/project64/assets/159548162/c359ed72-275d-48b7-a4c8-5b9a57547a89)

**Comment by Fanatic-64** [comment]
> What fixed to me ![image](https://private-user-images.githubusercontent.com/159548162/329694479-c359ed72-275d-48b7-a4c8-5b9a57547a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzg0MzYsIm5iZiI6MTcxNTM3ODEzNiwicGF0aCI6Ii8xNTk1NDgxNjIvMzI5Njk0NDc5LWMzNTllZDcyLTI3NWQtNDhiNy1hNGM4LTViOWE1NzU0N2E4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQyMTU1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2YyZGJjN2E5MTM5ODNlNGNlYjgyMDc3MGUyMWYwZmU4NjViMTg3NzE0NWEyMGMyYjJjNzU5ZjJiMWViMmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.isb2DXjbDrrfmMPmNtpe1I_qZ7icmBafvIOdLEGLVSA)

You're using Project64 1.6 (which is ancient, and has a known security vulnerability). This bug tracker is for the current latest version of Project64.

**Comment by WinUser-Generic** [comment]
If there is any newer version to use with kaillera tell it. Thats the only i found to make netplay.
