### ISSUE TITLE
Error opening GLideN64 gfx config with Jet Force Gemini

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1327]
I get this error as soon as I open GLideN64's graphics config in Project64, note I have debugger disabled:

2017/06/18 13:48:08.019 07220,Error,User Interface,CNotificationImp::DisplayError,Unhandled R4300i opcode at: 8DFC4200
Unknown	42 00 42 00

Stopping Emulation !

If I manually pause Jet Force Gemini, then open the graphics config, it's ok.

**Comment by Frank-74** [comment]
With debugger enabled I get these errors:

2017/06/18 13:56:39.145 07548,Error,User Interface,CNotificationImp::DisplayError,WTF

Branch
NextInstruction = 3
2017/06/18 13:56:43.532 07548,Error,User Interface,CNotificationImp::DisplayError,Unhandled R4300i opcode at: 8DFC4200
Unknown	42 00 42 00

Stopping Emulation !
2017/06/18 13:56:44.827 07548,Error,User Interface,CNotificationImp::DisplayError,Break point found at
N64System\Interpreter\InterpreterOps.cpp
2887

Not sure why there's a break in InterpreterOps, as it's set to Recompiler.  Have not changed any settings from the RDB.

If I switch to Interpreter I get this error:
2017/06/18 13:59:02.078 08760,Error,User Interface,CNotificationImp::DisplayError,Break point found at
N64System\Mips\MemoryVirtualMem.cpp
1297

**Comment by project64** [comment]
if you use a different gfx plugin does it have this issue?

I am thinking that it is corrupting the rdram which causes the cpu to die

**Comment by Frank-74** [comment]
It only happens with GLideN64 config.  All other gfx plugins are fine.  Pausing emulation before opening config is the only way to get into the config without it crashing.  Resume after closing and it's fine.

I suppose I should have put this in the GLideN64 issues.  Though Mupen 0.51, which uses zilmar spec, pauses the emulator when GLideN64 config is opened.  Project64 doesn't pause even when "Pause emulation when window is not active" is checked on opening GLideN64's config.

**Comment by LegendOfDragoon** [comment]
>if you use a different gfx plugin does it have this issue?

It's the plugin's fault, not the emulator. It crashes because it improperly skips DLists. It makes an incorect assumption that every game uses fullsync at the end of each DList.

**Comment by Frank-74** [comment]
> It's the plugin's fault, not the emulator.

It's a bit of both, emulator and plugin.

With Mupen64 0.51, I can run Jet Force Gemini and open the config in GLideN64 fine, because Mupen pauses emulation properly when it loses focus.

Also I can enter and exit full screen properly with GLideN64 and Mupen64 0.51.  Project64 exiting full screen I'm left with a black screen, have to CTRL+ALT+DEL and press Esc to get the desktop back, then close Project64.  Because ending emulation and trying to run with GLideN64 again results in a black screen.

No problems with Mupen64 0.51 at all.  And I don't know why...

**Comment by LegendOfDragoon** [comment]
>With Mupen64 0.51, I can run Jet Force Gemini and open the config in GLideN64 fine, because Mupen pauses emulation properly when it loses focus to GLideN64's config dialog.

I suppose that could be an issue (not pausing when configured to pause after losing focus). Imo it depends on whether zilmar intended for that to happen. Even if it's decided that pausing is the solution, the current code is still not good to use because it's still inaccurate. It's better to not skip DLists at all, than to make incorrect assumptions that cause issues.

>Project64 exiting full screen I'm left with full screen blackness, have to CTRL+ALT+DEL and press Esc to get the desktop back, then close Project64.

Didn't you say this doesn't happen with Glide64? Might be a driver issue because I can't reproduce this with GLideN64.

**Comment by Frank-74** [comment]
> Didn't you say this doesn't happen with Glide64? Might be a driver issue because I can't reproduce this with GLideN64.

Correct.  Glide64 is fine.

You use Intel HD Graphics?  What is your driver version so I can test?
My version is the latest available for Windows 8.1: 10.18.10.4425

**Comment by project64** [comment]
I know with some windows I will pause emulation on opening, and unpause on close .. glide64 has this internal to it, it will not process dlists if the cfg is open .. I could look at adding a pause at the start of the gfx gfx plugin and a resume at the end, but if it is not blocking in that function then that does not help

**Comment by Frank-74** [comment]
Should I just put in a request in GLideN64's issues to not process dlists if the cfg is open?

**Comment by LegendOfDragoon** [comment]
Lol I just remembered that Mupen64 ignores DP interrupts signaled by the graphics plugin anyway.

>Should I just put in a request in GLideN64's issues to not process dlists if the cfg is open?

That's what it's doing already and causes a crash because it doesn't do a proper job skipping the DLists. The crash is caused by firing an unconditional interrupt when it should be conditionally done.

>Thought it would be easier to build that and try fixing the fullscreen issue there, then transfer the fix to GLideN64.

glN64 is too buggy. I would not bother. I remember I had to disable compiler optimizations in order to even run Super Smash Bros. I would try downloading those static libs if possible and compile GLideN64.

>You use Intel HD Graphics? What is your driver version so I can test?

My hardware is newer, so I guess it has better drivers. My IGP version is Intel HD 530. Can't remember my driver version, but I should probably update as there seems to be a newer version :smile: . Intel really stepped up their game imo. Don't know why people seem to think otherwise.

@project64 , If pausing is to be implemented on the emulator's side, I hope it's optional, rather than forced.

**Comment by Frank-74** [comment]
@LegendOfDragoon I've downloaded those static libs after trying to build them, VS2015 still throws tonnes of errors I can't solve.  Apparently for a full environment I need to install lots of Quicktime  stuff that takes up 22Gb!  I built the freetype dependency and I built the Quicktime libraries, still couldn't build in VS2015.  I then saw boost libraries might be needed.  Pah!  Give up...

**Comment by project64** [comment]
one of the reasons I am using glide64, a lot less requirements .. generally I also try to include all the 3rd party requirements in the source as well so you do not have to install external source.

**Comment by Frank-74** [comment]
It'd probably be easier to remove the QT dependence from GLideN64 and make a gui from within Visual Studio using WTL.  The WIP threaded GLideN64 runs 2.5 times faster than the master in Perfect Dark here, almost as fast as Glide64 on my crappy Intel HD Graphics.  There's only a couple of VI/s difference.  2D framebuffer stuff is still very slow though.  Like in Star Wars - Shadows Of The Empire storyboard.

**Comment by project64** [comment]
that is what I did for glide64, tho it was not QT, but wx widgets, but same thing, re-did the cfg UI using WTL.

I refuse to touch anything QT stuff, not to mention it is making Gliden64 huge with it.

**Comment by Frank-74** [comment]
Been waiting for Azimer to finish the new plugin also.  It works great.  But to test you need to build with different settings, as the config doesn't work yet.
[img]https://www.dropbox.com/s/i77s7s14kcssdqa/azicfg1.JPG?dl=1[/img]

[img]https://www.dropbox.com/s/ki28jgc0hn359ys/azicfg2.JPG?dl=1[/img]

Once this is integrated into PJ64, and the settings can be controlled from the RDB or something, every game will have good crackle free sound.

**Comment by LegendOfDragoon** [comment]
>Pah! Give up...

I don't blame you. I never got that compiling successfully. I just figured the situation ought to be better by now, but perhaps i was just too optimistic. Long ago, I did have success building after disabling QT, but of course that meant no gui.

>one of the reasons I am using glide64, a lot less requirements ..

Yea easier to compile and much lower system requirements. I just hope someone successfully ports the T3DUX ucode :smile: , then perhaps I'll start using HLE more often.

**Comment by retrobenny** [comment]
I can confirm seeing small parts of memory within ASM changing on its own in a bizarre fashion of specific 4 byte sections and with Glide64 Final 2012.
When trying to get 60fps for real,I caught a glimpse at one point where an 0C01 instruction magically appeared in place of another set of values.

I and @theboy181 have both seen crashes on Recompiler and even without cheats used in random and consistent moments.
Mine was in the first area with it just randomly getting the same kind of Interpreter Ops breakpoint or a non-mapped space error one time.

He said that Interpreter worked fine in the consistent problem spot,but I don't know where that is.

**Comment by Frank-74** [comment]
Fixed, Project64 now pauses when opening config.
