### ISSUE TITLE
Emulation crashes when pressing ALT+TAB in fullscreen

### ISSUE THREAD

**Issue by bryc** [project64/project64#1328]
When I try to ALT+TAB to switch windows when in fullscreen, PJ64 switches back to windowed, and gives me two errors:
![image](https://user-images.githubusercontent.com/1408749/27262013-8811dbb8-541c-11e7-8d12-b04d8d106c4b.png)
![image](https://user-images.githubusercontent.com/1408749/27262014-8b71d3bc-541c-11e7-8540-43fa53699af8.png)

And my plugin config: 
![image](https://user-images.githubusercontent.com/1408749/27262018-a20548d4-541c-11e7-864e-aea41a656cf1.png)

It appears to be 100% reproducible on my build

**Comment by Frank-74** [comment]
RSP plugin should be "RSP Plugin 1.7.4.9999".

**Comment by Frank-74** [comment]
Delete your EmuCR-Project64-20170609-x86 directory, and extract the archive again.

Then make a new text document in folder with Project64.exe and rename it delete.bat.
Right click delete.bat and select Edit.
Copy and paste this into delete.bat.

rd Artwork /q /s
del Config\Project64.cfg
del Config\Project64.cfg.development
del Plugin\Audio\AndroidAudio.dll
del Plugin\Input\AndroidInput.dll
del Plugin\RSP\RSP-HLE.dll

This will remove everything not needed for windows version, and reset it.  Now when you run Project64.exe you will get to choose language at startup, and everything will be at the default settings like a new install.

**Comment by bryc** [comment]
Yep the EmuCR build, was curious to see the bleeding edge (compilation is beyond me, i'm a js guy), which i gotta say i'm impressed.  I did have to manually set the  plugins, there was no language select.. but the RSP-HLE doesn't seem to be the culprit. It seems that PJ64 doesn't like one to ALT+TAB out of fullscreen. No matter what video plugin is used, it switches back to windowed mode. It seems to be related to the new "Project64 Video Plugin", as GlideN64 and Jabo don't crash, albeit Jabo's window size doesn't get reset and keeps a large black area presumably from the fullscreen mode.

Are you able to ALT+TAB out of fullscreen using "Project64 Video Plugin" without the error occurring, and emulation stopping?

**Comment by Frank-74** [comment]
I can enter and exit fullscreen with "Alt+Return" or just "Esc", ALT+TAB is not the correct keys.  No problems whatsoever.  I tested with the EmuCR build and Project64-Video Plugin.  Jabo's is fine too.  I cannot exit fullscreen using GLideN64, but that's a problem with my Intel HD Graphics.

The RSP-HLE is for android, it doesn't work for the windows version.

If you delete the Config\Project64.cfg, Project 64 will return to default settings, plugins should be set and you can select language at first startup of Project64.exe.

What graphics card/chip do you have, and do you have the latest drivers installed?

**Comment by bryc** [comment]
ALT+TAB is what i used though to cause the crash. it switches between windows and usually leaves fullscreen apps just temporarily. esc works fine to toggle fullscreen.

**Comment by Frank-74** [comment]
@bryc I've tested the EmuCR version, against my own built version, and performance in EmuCR version is not as good as official or my own build.

It's dead easy to build from the source, just click a couple of buttons.
You'll need Visual Studio 2015 Community.  You'll have to select older versions, and login with your microsoft login (what you use to logon to Windows 8/10), to download VS2015.
Install it, make sure C++ is selected on installer.
Several hours later (install takes very long time), download project64-master zip from here.
Extract it somewhere.
Double click Project64.sln, it will open VS2015 and load the project after a while.
Change from Debug to Release (dropdown menu item).
Click on Build menu, select Build Solution.
Few minutes later you'll have it built.
Goto Source\Script folder, run package_zip.cmd.
Now in project64-master\Package folder, you'll have a zip with Project64 to extract and play.

No knowledge needed.  Easy peasy....

**Comment by bryc** [comment]
> I can enter and exit fullscreen with "Alt+Return" or just "Esc", ALT+TAB are not the correct keys. No problems whatsoever.

> @bryc I've tested the EmuCR version, against my own built version, and performance in EmuCR version is not as good as official or my own build.

Are you entirely sure we're talking about ALT+TAB and not ALT+RETURN/ESC? I'm not talking about toggling fullscreen mode. I'm talking about the [Task switch (Alt+Tab)](https://en.wikipedia.org/wiki/Alt-Tab)  keyboard command in Windows. In any other fullscreen game, like say Half-Life 2 or Age of Empires, or any game that runs in fullscreen, ALT+TAB allows one to temporarily go back to the desktop, with the game still fullscreen, and upon clicking the game in the taskbar will switch back into fullscreen mode.

This doesn't work in Project64. The task switch shortcut will terminate fullscreen mode under all plugins, and specifically in "Project64-Video Plugin", the emulation crashes with the errors I mentioned, which happen 100% of the time when I try it.

I have tried the latest version at pj64-emu.org, and the older PJ64Glide64.dll is not affected, yet Project64-Video.dll is. The EmuCR build I used was June 9,  I think, the one you mentioned. And I believe I got the latest master to compile following your instruction, and used the installer exe that got built. The Project64-Video.dll that ended up being installed was also affected with the ALT+TAB crash in my original post. 

Alright, it appears that this is a Windows 7 issue.  I tested on two Win10 machines, and they seem to be using a different fullscreen mode - instant, no stutter in the sound, but on Win7, it appears that the display mode is actually changing (even if I am using my native monitor's resolution), and there's a stutter in the sound, a bit of a delay.

**Comment by Frank-74** [comment]
ALT+TAB has no effect here in fullscreen.  I'm on Windows 8.1 x64.  My old XP machine used to show the icons of running apps if I held ALT+TAB, I held ALT and pressed TAB to switch the highlight to the app I wanted to focus on, then released ALT and it would switch to it.

I know how it's supposed to work, but that feature no longer works here in Windows 8.1.  I see nothing when holding ALT+TAB in anything fullscreen.

**Comment by Frank-74** [comment]
@project64 
I just had the RunRSP unknown memory action going full screen in Monaco Grand Prix.  First time it's happened to me.  Enabled debugger to get proper debug log, but now cannot reproduce it.
However I can reproduce the error with ALT+TAB when in full screen.  Probably related.

2017/06/20 16:08:45.427 11204,Error,Exception Handler,CMipsMemoryVM::FilterX86Exception,Invalid memory adderess: BD830008
2017/06/20 16:08:45.503 11204,Error,User Interface,CNotificationImp::DisplayError,Break point found at
MemoryExceptionFilter.cpp
43
2017/06/20 16:08:48.132 11204,Error,RSP,CN64System::RunRSP,exception generated
2017/06/20 16:08:48.203 11204,Error,User Interface,CNotificationImp::FatalError,CN64System::RunRSP()
Unknown memory action

Emulation stop

**Comment by oddMLan** [comment]
Confirmed, Alt-Tab_ing_ triggers a breakpoint error message, only with Project64-Video.

**Comment by wefalltomorrow** [comment]
Same issues here.

**Comment by cheamo** [comment]
This issue still around in 2.4

**Comment by bryc** [comment]
@cheamo can you try on latest dev builds: https://www.pj64-emu.com/nightly-builds and see if it still happens with some combination of plugins.

for now i'm closing issue because as i can't reproduce it anymore.
