### ISSUE TITLE
[Project64-Video] Desktop brightness problem.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1332]
Sometimes, when starting a game, the whole desktop gamma or brightness gets very bright.

Most times it resets back to normal, but occasionally it stays very bright, impossible to look at without getting a headache.  And it then has an effect on all gfx plugins being over bright.  Have to restart my laptop.

**Comment by LegendOfDragoon** [comment]
I think I experienced this issue as well. Never had to restart my laptop though. Just had to exit the emulator.

**Comment by Frank-74** [comment]
I may have opened the graphics config while it was changing brightness.  It then never reset.  Even media player and other games are effected.  It changes my gfx driver brightness globally with no way to reset it.  Tried restarting Project64 with same game again, but brightness never went back to normal.

**Comment by AmbientMalice** [comment]
This is caused by a flaw in how Glide64 handles gamma. It modifies the Windows gamma value. I used to have a tool for resetting the gamma values back to default. Can't remember what it was called though.

**Comment by Frank-74** [comment]
Just tested this again with latest build.

It only seems to be adjusting the gamma level of the desktop on starting TWINE.  Tried several other games and it never happens.

**Comment by Frank-74** [comment]
Mystical Ninja Starring Goemon makes the desktop bright for about 5 seconds.  When the Konami logo is playing on startup.
![glide64_mystical_ninja_04](https://user-images.githubusercontent.com/11056843/28625464-44ff1dd4-7214-11e7-85cb-b8ee96846519.png)

**Comment by project64** [comment]
I agree, it should not effect the system, I know I have been doing some code cleanup, if you know where the code is that changes the system I can look at it.

**Comment by Frank-74** [comment]
Not sure about the code, but this looks like it here: https://github.com/project64/project64/blob/master/Source/Project64-video/Renderer/OGLglitchmain.cpp#L1926

**Comment by project64** [comment]
I am guessing SetDeviceGammaRamp is causing it .. I do not understand all the gamma parts yet, still cleaning up the code, but it does seem wrong to effect the system

**Comment by LegendOfDragoon** [comment]
I believe it was originally intended to only activate when using fullscreen. It's a nice and cheap way to have gamma for games that use it like StarFox64.
