### ISSUE TITLE
regresion in recent cheat code changes

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1336]
The following code is for Super Smash Bros. (U) and is used to add new levels to the random function in multi player mode, however it causes the game to freeze when its enabled. 

SSB64 GameShark Code

SSB64
Random Level in MP game (needs Final Destination fix to fully function)

D1133BD8 2404
81133BDA 0010
D1133BE2 C6EB
81133BE0 0C02
D1133BE2 C6EB
81133BE2 9350
810A4D40 3C10
810A4D42 800A
810A4D44 0204
810A4D46 8020
810A4D48 8210
810A4D4A 4D54
810A4D4C 03E0
810A4D4E 0008
810A4D50 2002
810A4D52 0000
810A4D54 0001
810A4D56 0203
810A4D58 0405
810A4D5A 0607
810A4D5C 080D
810A4D5E 0E10
810A4D60 090C
810A4D62 0000

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/3549d199651b863db40a2778bf2b856625b56639 fix the issue?

**Comment by theboy181** [comment]
tested, and so far this appears to be working. BIG Thanks!
