### ISSUE TITLE
[Project64-Video] Recent regression

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1338]
Two days ago it was fine, but now the puddles in the rain in Monaco Grand Prix (U), look like this:

![glide64_monaco_grand_prix_01](https://user-images.githubusercontent.com/11056843/28649091-3cfe1580-726a-11e7-840f-dacc2e944591.png)

I loaded a savestate using Project64-Video from two days ago, and it displays fine.
Here's a savestate at the above position: https://www.dropbox.com/s/28veiydjpz29d0q/Monaco%20Grand%20Prix%20%28U%29.pj.zip?dl=1

**Comment by project64** [comment]
ok thanks, in general my current changes should just be code clean up, but it is easy to introduce an unintended change. I will see if I can work out what is going on soon.

**Comment by Frank-74** [comment]
I've traced the bug to this commit: https://github.com/project64/project64/commit/87efd0c25910ecad3d06882046c6a9abb2554b9e

**Comment by project64** [comment]
thanks knowing the commit helps a lot, looking though it is not obvious, mostly it is just name changed that should be the same ...

the only two logic changes I can see are:
https://github.com/project64/project64/commit/87efd0c25910ecad3d06882046c6a9abb2554b9e#diff-922497e018917171f854cdc6b190a09fL521

with ChooseBestTmu

and
https://github.com/project64/project64/commit/87efd0c25910ecad3d06882046c6a9abb2554b9e#diff-922497e018917171f854cdc6b190a09fL480

where gfxTexSource expects the first param to be a GrChipID_t but passes the tile in

**Comment by Frank-74** [comment]
I built from https://github.com/project64/project64/commit/4984db179c65e6609768302bb9f5adabcc407f4f and changed the gfxTexSource from tile to tmu.  It's the cause of the bug.  Changing back to tile and puddles display ok again.

I'm not sure how to fix it with the changes, as tile is an int, it needs to be changed to a gfxChipID_t I think.
This is the cause anyway:  https://github.com/project64/project64/commit/87efd0c25910ecad3d06882046c6a9abb2554b9e#diff-922497e018917171f854cdc6b190a09fL480

**Comment by project64** [comment]
I just started to look at it, but I suspected that is what is causing it as it is the only real change in behavior. The tile can be cast to a gfxChipID_t, seem wrong, like there is some other bug in the code that this hides/accidentally gets right.

i suspect I will do:
`gfxTexSource((gfxChipID_t)pTBuffTex->tile, pTBuffTex->tex_addr, GR_MIPMAPLEVELMASK_BOTH, &(pTBuffTex->info));`

while it seems wrong, probably have to go with the wrong answer till that code gets cleaned up properly

**Comment by Frank-74** [comment]
Just tested with:
'''gfxTexSource((gfxChipID_t)pTBuffTex->tile, pTBuffTex->tex_addr, GR_MIPMAPLEVELMASK_BOTH, &(pTBuffTex->info));
'''
It works fine.

**Comment by project64** [comment]
cool, I will change it to that tonight, unless you want to make a pull request

**Comment by Frank-74** [comment]
Created PR.
