### ISSUE TITLE
[Project64-Video] Another regression.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1340]
Just discovered OoT has a problem with the sky after the logo is displayed.
![glide64_the_legend_of_zelda_04](https://user-images.githubusercontent.com/11056843/28697938-92c6f770-7337-11e7-8514-56ec177ccca1.png)
The sky appears in the next camera change.

Going back to Project64-Video from the overclock branch, it's half broken at the same place.
![glide64_the_legend_of_zelda_01](https://user-images.githubusercontent.com/11056843/28697958-bbae6f88-7337-11e7-88f7-4edd0d5004cf.png)

It's fine before it became Project64-Video.
I'll try to find the commit that started it over the weekend.

**Comment by project64** [comment]
ok thanks

**Comment by Frank-74** [comment]
The first commit that introduces the sky bug is [video] remove grDrawPoint here: https://github.com/project64/project64/commit/c0413aeb66b73cf7bce5b19af772d795ceb1446f

After the half black sky, you get this in the sky as well:
![glide64_the_legend_of_zelda_05](https://user-images.githubusercontent.com/11056843/28745388-3bf23aac-746f-11e7-94e5-92d2436b5337.png)

**Comment by cxd4** [comment]
lol look at ol' zilmar removing a bunch of confusing graphics code until the codebase as a whole makes sense and doesn't even function he must be some kind of a noob at coding

**Comment by Frank-74** [comment]
While looking for when the sky went from half black to full black, the sky is perfect.
This commit sky is fixed.  Weird.
[Video] Remove GlideExtensions.h https://github.com/project64/project64/tree/452c21b8a3276e95d7b9056cb0f4dd062b8c5103/Source/Project64-video

**Comment by Frank-74** [comment]
The sky turns all black from this commit again:
[Video] Change GrChipID_t to gfxChipID_t https://github.com/project64/project64/commit/87efd0c25910ecad3d06882046c6a9abb2554b9e

It must be caused by the other logic change in that commit here:
https://github.com/project64/project64/commit/87efd0c25910ecad3d06882046c6a9abb2554b9e#diff-922497e018917171f854cdc6b190a09fL521

**Comment by Frank-74** [comment]
Fixed it by changing this line:
https://github.com/project64/project64/blob/master/Source/Project64-video/TexCache.cpp#L512
to tmu_1 = GFX_TMU1;
And this line:
https://github.com/project64/project64/blob/master/Source/Project64-video/TexCache.cpp#L524
to tmu_0 = GFX_TMU1;
