### ISSUE TITLE
PJGlide64 don´t save settings

### ISSUE THREAD

**Issue by Predator82Germany** [project64/project64#135]
When I for example set read every frame in PJGlide nothing changes in the Glide64.rdb
With Glide64 Final it works (fb_read_always=1 is shown)

**Comment by project64** [comment]
I will have a look, tho when are you checking the file, one of my thought is that it is not flushing the changes to disk untill you close them emu.

**Comment by Predator82Germany** [comment]
Checkek it with opened & closed emu

**Comment by project64** [comment]
Ok I will test and see if I can work out what is going on with it.

**Comment by project64** [comment]
with PJGlide settings should change in the .Project64.cfg file, in the Glide64 section. The Glide64.rdb are the default, to edit that file has to be by hand.

If you see the changes in Project64.cfg i think we can close this issue.

**Comment by Predator82Germany** [comment]
Ok, it saves "Glide64" settings in Project64.cfg (why not in the Glide64.rdb?)

**Comment by project64** [comment]
why is it not set in the rdb, no  idea I let other people set the settings, if it should be on do a pull request for it.

Glide64.rdb is for default settings, it is meant to be able to be updated. The cfg file overrides the settings so if you do update the rdb then it does not change the settings you made

**Comment by project64** [comment]
can I close this now?

**Comment by Predator82Germany** [comment]
Yes

**Comment by Fanatic-64** [comment]
>why isn´t fb_read_always=1 not set as standard for Mario Kart 64 (all)?

Because that option makes it unplayably slow on most computers.
