### ISSUE TITLE
Glide64 Issue 485

### ISSUE THREAD

**Issue by nburt95** [project64/project64#1352]
EDIT: Got it working by forcing the texture to be compressed.
I have spent hours trying to get HD textures working with Glide64. I finally got the ROM to load with HD textures and I keep getting this error.
"CN64System::EmulationStarting: Exception caught
File: .\N64System\N64class.cpp
Line: 485"

I thought it might have been an issue with RAM or something along those lines, used numerous patches ect and can't seem to find the problem! CAN ANYONE HELP ME PLEASE! I'VE BEEN AT THIS FOR 4 HOURS!

**Comment by daviborba** [comment]
eu tambem to com o mesmo error,_,

**Comment by Louizombie13** [comment]
I got it the same error, someone can help me please?
