### ISSUE TITLE
how do I add a custom entry to the RDB file?

### ISSUE THREAD

**Issue by lorecast162** [project64/project64#1354]
#i used GoodN64 to scan the roms but i don't know what to do afterwards. i wanted to add SM64: Last Impact to the RDB so that it at least says the right name

**Comment by lorecast162** [comment]
EDIT: i know part of it.
ex.
    CRC1          CRC2        ???
[C851961C-78FCAAFA-C:45]
    Name to display
Good Name=Pilotwings 64 (U)
           Internal Name that the info screen shows
Internal Name=Pilot Wings64
       text of Status coloumn
Status=Compatible
         text of Notes (plugin) coloumn
Plugin Note=[Glide64] broken shadows
                   Available cheats
Cheat0=D0263B41 0012,80263B41 00FF,D02643C1 0012,802643C1 00FF,D0264581 0012,80264581 00FF,D0263FC1 0012,80263FC1 00FF,D0263E81 0012,80263E81 00FF,D0263E41 0012,80263E41 00FF,D0264181 0012,80264181 00FF,D0264381 0012,80264381 00FF,D0264281 0012,80264281 00FF,D02639C1 0020,802639C1 00FF,D02640C1 0020,802640C1 00FF,D0264541 0020,80264541 00FF,D0264201 0020,80264201 00FF,D0263D81 0020,80263D81 00FF,D0263F81 0020,80263F81 00FF,D0263A81 0029,80263A81 00FF,D0264101 0029,80264101 00FF,D0263E01 0029,80263E01 00FF,D0264201 0029,80264201 00FF,D0264441 0029,80264441 00FF,D0263F81 0029,80263F81 00FF,D02647C1 0029,802647C1 00FF,D0264941 0029,80264941 00FF,D0264281 0029,80264281 00FF,D02639C1 003D,802639C1 00FF,D02641C1 003D,802641C1 00FF,D0263D41 003D,80263D41 00FF,D0263EC1 003D,80263EC1 00FF,D0263F01 003D,80263F01 00FF //Land Shadow Fix
CheatPlugin0=Jabo's Direct3D8,Glide64 For PJ64
        ???
Counter Factor=3
        ???
Culling=1

**Comment by lorecast162** [comment]
i don't know what's essential or not, can somebody help me?

**Comment by lorecast162** [comment]
maybe the :C-xx is the region?

**Comment by Frank-74** [comment]
Open Project64\Config\Project64.cfg with notepad.  Scroll down to find your SM64:Last Impact entry.
Copy and past it here, and I'll translate it to an RDB entry.

The config uses 1's and 0's, the RDB uses Yes/No, On/Off etc...

**Comment by lorecast162** [comment]
nevermind, i just figured what things were and it worked.
closing this.
thanks anyway dude
