### ISSUE TITLE
how to automatically set RAM to 8MB with command line

### ISSUE THREAD

**Issue by lorecast162** [project64/project64#1355]

**Comment by lorecast162** [comment]
i wanted to use Project64 with emulationstation but some roms i have use the expansion pack, making the emulator close if RAM is set to 4MB
i don't see any command line switch documentation though and also saw somewhere that command line switches were entirely removed with 2.0
any help?

**Comment by Frank-74** [comment]
Only hacked ROM's without an RDB entry, default to 4MB.

Either add an RDB entry with your settings for a game into Config\Project64.rdb, or install Visual Studio 2015/2017 and build from source after changing the default memory size option to 8MB.

**Comment by lorecast162** [comment]
do i add this line to the RDB?
RDRamSize=8388608

**Comment by Frank-74** [comment]
No, RDB uses just,
RDRAM Size=8

Project64.cfg will give you the entry to add, but certain options have different options in the RDB.  The cfg uses 1's and 0's, the RDB uses a combination of Yes/No, On/Off etc.

Look through the RDB to find the correct format.

**Comment by lorecast162** [comment]
thanks, it worked.
closing the issue
