### ISSUE TITLE
Extended feature

### ISSUE THREAD

**Issue by theboy181** [project64/project64#136]
Would like to see the ability to show the VI's and the DL's at the bottom of the screen at the same time. 

;)

**Comment by cxd4** [comment]
You could use Glide64 for that, which already is a part of PJ64.  Otherwise VI/s, pause, switch to DL/s.

**Comment by theboy181** [comment]
your missing the point. I would like to be able to select an option that will display both at the same time. This makes it easy to see what games slow down because of FPS or the Vi's, and not having to switch and restart just to observe the part with each setting.

**Comment by V1del** [comment]
That's exactly what glide allows you to, you can checkbox multiple values in its settings window and it will show all of them

**Comment by theboy181** [comment]
I don't use glide very often, and this is more about benchmarking all emulators, while paying attention to low FPS, and Vi's.

**Comment by V1del** [comment]
Yeah and glide allows you to use this on every emu even ones that don't implement a counter natively. Nothing wrong with the suggestion, just another possibility

**Comment by theboy181** [comment]
I updated my post. I meant plugins, while using PJ64. ;)

**Comment by cxd4** [comment]
> I would like to be able to select an option that will display both at the same time. 

So if you use Glide it should tell you both.

> This makes it easy to see what games slow down because of FPS or the Vi's,

Neither is a cause of games slowing down, just a different unit of measurement.  If you know VI/s is low then you also know FPS is low and vice versa.  A game never slows down "because of FPS or the VI's".

> I meant plugins, while using PJ64. ;)

Right, so your suggestion is that other plugins besides Glide64 should be able to do this; therefore this is a feature request for third-party plugins not Project64.

**Comment by cxd4** [comment]
While it's not as necessary as in the form presented, I think the idea is at least beneficial enough.  It could even help zilmar remove yet another option from Project64 (configure whether to show VI/s, FPS, % speed) by displaying at least 2 of these deducible measurements simultaneously.

So it's not that I dislike the feature itself, just some of the reasoning behind it.

**Comment by theboy181** [comment]
you could add a 4th option to show it, so its an addition not a subtraction.

**Comment by LegendOfDragoon** [comment]
DL/s isn't even accurate lol. W/e floats your boat I guess..

Glide's internal fps counter is more accurate Iirc.

**Comment by theboy181** [comment]
if the DL/s are not correct then you should open a new issue for that. Where are they not accurate?

**Comment by LegendOfDragoon** [comment]
Just tried Last Legion, DL/s > 60. I remember other games too, like Wipeout 64.

That's why I'd rather let zilmar focus on more important things, like fixing the protect memory issue, or fixing broken games like Battle For Naboo.

**Comment by vgturtle127** [comment]
I would think this wouldn't be that hard to add, but I would like to know why they are both there if they are essentially telling you the same thing?

Why not remove DL/s if it is inaccurate?

What are the differences?

I understand draw calls and frames per second, but VI is vertical interrupts, right?

I don't even know what DL/s are. I have never had a use for those measurements.

Anyway, why not just show draw calls, FPS, and CPU/RAM usage?

**Comment by cxd4** [comment]
DL/s is the number of Graphics Binary Command lists, also known as display lists, sent through from the RSP for the RDP to rasterize into the rendered frame buffer.  It basically means frames per second.

So if you want it to show FPS you have to ask it to show it as DL/s.

The old "FPS" counter prior to Project64 1.7 was a misnomer for actually the vertical interrupts per second, as you said VI/s.  That should be a refresh rate of 60 Hz on NTSC.

**Comment by vgturtle127** [comment]
OK, and PAL I assume is 50Hz. And Japanese consoles are also 60Hz.

Is Project64 locked to 50/60 FPS based on the region? Or is it unlocked like most emulators, and things like frame skipping and locking the framerate are options?

I'd check, but I am currently using a mobile device to do most of my GitHub work. And my PC is without a hard drive at the moment...

**Comment by cxd4** [comment]
Not FPS, but VI/s.  Normal video updating goes at that rate with an unfixed internal FPS speed, but the 60 or 50 VI/s limit could be removed by disabling the appropriate option in Project64 settings, which is on by defualt.

**Comment by Frank-74** [comment]
NTSC and PAL are autodetected from Project64.  Or it can be forced in the RDB with ScreenHertz= setting.

**Comment by vgturtle127** [comment]
@cxd4 OK, that makes sense. Thanks for the info. More hacking needs to be done, I suppose. :smile: 

@Frank-74 I figured. Most NTSC games run fine, but then PAL games seem to crash. When I run a PAL game at 60Hz it seems to run fine though. :confounded: 

By the way, why do some games crash when you change from 4MB RDRAM to 8MB RDRAM? Doesn't the actual hardware boot anything with 8MB RDRAM? Just wondering...

**Comment by LegendOfDragoon** [comment]
I guess this can be closed, now that it has been implemented.
