### ISSUE TITLE
NHL 99: Graphics corrupted

### ISSUE THREAD

**Issue by loganmc10** [project64/project64#1362]
I tested Jabo, Glide64, and GLideN64, all the same.

![capture](https://user-images.githubusercontent.com/848146/29585418-4593b378-8744-11e7-9d87-b3f95374228e.PNG)

This is what it looks like in mupen64plus:

![nhl_99-000](https://user-images.githubusercontent.com/848146/29585444-5be3449a-8744-11e7-8b9c-3f5efbde3dca.png)

I'm pretty sure I have a fresh config, but maybe someone else can test? Also, I'm not sure if this is fixed in the latest source, I tested 2.3.2

**Comment by Frank-74** [comment]
Just tested, I get the same with default RDB settings.

However, disabling 32-bit engine in PJ64 fixes it here.

RDB needs updating.

**Comment by loganmc10** [comment]
Awesome thanks

**Comment by LegendOfDragoon** [comment]
I thought all of those sports games had it 32bit engine disabled already lol..

**Comment by Frank-74** [comment]
@LegendOfDragoon Appears not.  None of the NHL games have 32-bit engine disabled.

I don't have any of them to test.  Never played them.

**Comment by LegendOfDragoon** [comment]
I guess it's because no one plays them :smile: . I could try testing a few games this week and the update RDB if necessary.

**Comment by Frank-74** [comment]
I just tested all of the above games out of boredom.  They all work fine with 32-bit engine.  NHL 99 is the only EA Sports endorsed game out of all of them.  32-bit engine seems to only affect EA Sports games.
