### ISSUE TITLE
The "controller plugged" checkbox doesn't work in real-time.

### ISSUE THREAD

**Issue by retrobenny** [project64/project64#1369]
Not even the "Plugged" option works for remedying "no controller" for quick access to a multiplayer menu without requiring me to close and re-open PJ64 to apply the changes.

Furthermore,its really frustrating that it requires me to close and re-open to update mapped inputs so they would actually work after saving them.
It would be most unfortunate if the long query slowdown fix for the NRage Plugin happens to be the cause of this issue.

The settings have already been applied before opening the settings a second time for this picture to show "Plugged" is checked for P2. A video would possibly be better.

![image](https://user-images.githubusercontent.com/16418716/30133074-160ca4ae-9318-11e7-98ab-c4372d913b1d.png)

**Comment by retrobenny** [comment]
Strange,it updated when I mapped Start on the same session just fine,must be flaky updates in some situations.

I did find out that simply reloading the game from the recents list allows P2's controller to work,but its still not faithful to the actual console because it doesn't happen in real-time for plugging in or unplugging controllers.

**Comment by oddMLan** [comment]
Duplicate #417
