### ISSUE TITLE
Logitech F310 not inputting in Project64

### ISSUE THREAD

**Issue by TheSomeoneXD** [project64/project64#1370]
Hey, I'm trying to get a Logitech F310 working with Project64. I am new to the emulator and the plugin is stock from Project64 2.3.2.202.

The controller used to half-work but after a few tinkers to get analog working, the thing doesn't work anymore at all.

The controller is fully working in Windows via Game Controller, and the controller is on XInput. I also tried switching it into the "d" state, but it doesn't make a difference as far as I know. I've also been getting error messages (possibly unrelated) that the Mem Pack was missing occasionally (most likely from playing around with that setting too occasionally). Plugged and XInput is all checked.

I am beyond frustrated right now. Help would be greatly appreciated.

Here is my profile:
@Controller Profile 2.2

Plugged=1
xInput=1
N64Mouse=0
RawData=0
PakType=1
RealN64Range=1
RapidFireEnabled=0
RapidFireRate=3
StickRange=66
MouseMoveX=0
MouseMoveY=0
AxisSet=0
KeyAbsoluteX=0
KeyAbsoluteY=0
PadDeadZone=5
MouseSensitivityX=100
MouseSensitivityY=100
RumbleType=1
RumbleStrength=80
VisualRumble=0
FFDeviceName=
FFDeviceNr=0
MemPakFile=
GBRomFile=
GBRomSave=
DInputName=Keyboard
DInputNr=0
Button=0 0 4D 0 5
Button=0 1 4B 0 5
Button=0 2 50 0 5
Button=0 3 48 0 5
Button=0 4 1C 0 5
Button=0 5 39 0 5
Button=0 6 2E 0 5
Button=0 7 2D 0 5
Button=0 8 20 0 5
Button=0 9 1E 0 5
Button=0 10 1F 0 5
Button=0 11 11 0 5
Button=0 12 12 0 5
Button=0 13 10 0 5
Button=0 14 CD 0 5
Button=0 15 CB 0 5
Button=0 16 D0 0 5
Button=0 17 C8 0 5

**Comment by Azimer** [comment]
I also have a F310.  I just plugged it in, assigned A, B and Start and it worked.  Try deleting your configuration or use a clean copy of the emulator.  See if that makes any difference.

**Comment by some1chan** [comment]
Oops, forgot about this thread. I restarted my PC with the controller plugged in and it works?
If I unplug it, and then plug it back in, it doesn't work. Welp.

Fixed!
