### ISSUE TITLE
Bomberman 64 - Gold Card Transparency

### ISSUE THREAD

**Issue by robert-skinner** [project64/project64#1372]
Each stage has 5 gold cards, and when you are at the stage select screen it should show them as transparent if you don't have them. They show as fully solid even though you don't have them yet.

Image of transparent cards, snipped from youtube: https://imgur.com/Z96h826
Image of solid cards: https://imgur.com/9pDophR

**Comment by Frank-74** [comment]
Only happens with Jabo.  Cards show transparent with PJGlide64 (Project64-Video).

![glide64__01](https://user-images.githubusercontent.com/11056843/30406568-86280d6e-98ea-11e7-9ba8-f2ab4e5dd665.png)

**Comment by robert-skinner** [comment]
Thanks! I'm new to emulation, didn't even notice it already had PJGlide64 included. It worked, issue resolved:

**Comment by cxd4** [comment]
It happens with any plugin really, in the absence of software depth buffer rendering.

Glide64 FINAL had it implemented.  Most other plugins didn't, but Jabo's let you emulate it without Direct3D if you enabled software rendering in the advanced options.
