### ISSUE TITLE
Regression PJ GUI Pause GLideN64

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1388]
When you enter the GUI of GLideN64 the emulator will pause, but not unpause until you either open the GLideN64 GUI a second time, or the PJ64 options GUI.

**Comment by Frank-74** [comment]
Caused by this commit: https://github.com/project64/project64/commit/226cfd8bf6b0f9d64b7bb3123aa2b4590ec75f34

**Comment by project64** [comment]
this would mean that  m_Control->DllConfig(hParent); never actually returns, which Sounds more like a bug in GlideN64. Granted it would be invisible before, and that change would make it visible

**Comment by theboy181** [comment]
Pass it along I guess. Makes all other version broken.

**Comment by Yui12** [comment]
Seems to be related to this one.

[https://github.com/gonetz/GLideN64/issues/1645]

**Comment by LegendOfDragoon** [comment]
this still an issue?

**Comment by LegendOfDragoon** [comment]
If this is a bug with gliden64, i think this can be closed
