### ISSUE TITLE
someone should make a fork of PJ64

### ISSUE THREAD

**Issue by crazyboy92** [project64/project64#1392]
somebody needs to make a fork of this emulator but with improvements and remove jabos plugins because they suck ass make gliden64 the default plugin with azimers 0.60 wip2 but keep nrage for pj64 as default plugin and i hope its windows xp compatible because i still use xp for gaming purposes

maybe if knew how to make a fork, even better :)

**Comment by andrebrait** [comment]
Feel free to fork it yourself, I guess?

If you bothered reading the other discussion topics here on GitHub you'd see that some of your complaints are being looked at, at this very moment. 

You could contribute to those rather than complain. Also, you shouldn't be using XP. It's been EOL'd by Microsoft for the past 3 years.

**Comment by crazyboy92** [comment]
I'll keep using windows XP whatever I want when I want, i just watch what i'm doing and i have never got infected at all since that day

**Comment by project64** [comment]
there is a button at the top of the screen to create a fork, so go ahead make a fork, but if you do not know how to do that I fear you will not make any meaning contribution. 

I have tried to keep XP working, tho I do not have any XP machines to test on so I can not validate that. 

But if there is any actual XP issue raise a ticket and we can see what can be done.

**Comment by cxd4** [comment]
Always meant to put XP 64-bit on one of my computers.  It's the last version of Windows (and the first version of 64-bit Windows) before the system dependency tree got all wacky in Dependency Walker.
