### ISSUE TITLE
Plugins not initialized

### ISSUE THREAD

**Issue by Jables97** [project64/project64#1415]
When I load a rom it says "Cannot open a rom pecause plugins are not initialized. I'm new here pls help

**Comment by Jables97** [comment]
![plugins not initialized](https://user-images.githubusercontent.com/34314143/33674032-6c350384-da7c-11e7-870d-6d8f8ce525dc.PNG)

**Comment by JunielKatarn** [comment]
Go to Options/Settings/Plugins, and check that all Plugin types have been set (no blank entries).

![image](https://user-images.githubusercontent.com/4507319/33696219-04ca8cca-dab6-11e7-8f65-0a9b8072b805.png)

**Comment by Jables97** [comment]
They are all blank

**Comment by Tagiru** [comment]
update your emulator, download from the official page... install vc_redist x86 2008 to 2015... download from Microsoft web

**Comment by vgturtle127** [comment]
@Jables97 You need to download the latest version from [HERE](https://www.pj64-emu.com/download/project64-latest).

After that, try again. You are using a version that is very out of date.
