### ISSUE TITLE
Project 64 Exception Caught Line: 377

### ISSUE THREAD

**Issue by Kaan3D** [project64/project64#1419]
I'm searching for hours now to fix this issue , I just can't find anything about it , it's like nobody has the same issue lol , anyways I'm trying to start up Zelda Ocarina Of Time but it just won't work , the full Exception name : Exception Caught File .\N64 System\N64 Class.cpp  Line: 377

**Comment by JunielKatarn** [comment]
What build are you using? Latest release? Nightly build from @project64's Patreon site?
My latest (pretty recent) nightly build works fine with that game: http://hyvart.com/download/project64/project64dev.application

**Comment by JunielKatarn** [comment]
Also, OS version / hardware specs might help.
