### ISSUE TITLE
[Request] Add the option to Overclock the N64 CPU

### ISSUE THREAD

**Issue by AngelSora** [project64/project64#1420]
I don't want to use any other emulator than this one to emulate N64 and i wish i could have no in-game frame drops possible.

**Comment by project64** [comment]
there is an overclock option already in the emulator (not in public release). 

I want to make sure this is better and on for some games for the next 2.4 relase

**Comment by AngelSora** [comment]
Where is that overclocking option ? I think i'm using latest build, and i searched everywhere.

**Comment by project64** [comment]
in the game settings there is over clock modifier, not sure it will stay there, but that is where it is currently

**Comment by AngelSora** [comment]
Thanks a lot :D
