### ISSUE TITLE
Can't compile due to missing WinXP component

### ISSUE THREAD

**Issue by jeffythedragonslayer** [project64/project64#1425]
When I try to build Project64 with Visual Studio 2017, I get this error

```
Project 'Common' could not be loaded because it's missing install components. To fix this launch Visual Studio setup with the following selections:
Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP
```

This remains even after installing Windows XP support for C++ in the visual studio installer.  I'm building on Windows 10 by the way.

**Comment by jeffythedragonslayer** [comment]
Possibility a visual studio problem: https://developercommunity.visualstudio.com/content/problem/174498/vs2017-community-missing-components-installed-but.html

**Comment by JunielKatarn** [comment]
That's odd.
Before trying to repair your installation, make sure you have the following individual components:
* Windows 8.1 SDK
* Visual C++ core features
* VC++ 2015.3 v140 toolset for desktop (x86, x64)
* MSBuild

**Comment by jeffythedragonslayer** [comment]
Yes, those are all installed.

**Comment by project64** [comment]
Do you have **Windows XP support for C++** installed?

**Comment by jeffythedragonslayer** [comment]
Yes I did.  (Reinstalling Visual Studio with all the above components now to see if that works)

**Comment by jeffythedragonslayer** [comment]
Uninstalled and reinstalled Visual Studio with all the above components, still hitting the same issue.

**Comment by project64** [comment]
https://developercommunity.visualstudio.com/content/problem/174498/vs2017-community-missing-components-installed-but.html

some one else with your issue

**Comment by project64** [comment]
there may be changes needed to the property sheet for visual studio 2017 .. I am not sure, I am currently using 2015 ..

**Comment by JunielKatarn** [comment]
@project64 Not quite. I use VS2017 exclusively for building Project64.
It should work fine out of the box.
It's likely an installation issue.

**Comment by project64** [comment]
there is probably something that can be fixed with installing/doing something different, especially since it works for you. 

That people are having issues and it is non obvious solution, then something should be fixed so people do not have this issue. I am just not sure what and I am not likely to be using VS2017 for a while.

**Comment by JunielKatarn** [comment]
@jeffythedragonslayer Can you maybe upload a build log?
Run the following command:
`MSBuild.exe Project64.sln /filelogger /v:diag`
This should produce a file named `msbuild.log`.
Also, make sure you use the MSBuild provided by VS2017 (`MSBuild.exe /version` should yield `15.x`).

**Comment by project64** [comment]
it might be to do with XP support, maybe I disable XP support for all VS versions > 2015 since the build bot is going to stay on VS 2015.

**Comment by jeffythedragonslayer** [comment]
I found the right version of MSBuild.exe (there are a ton) but am getting this exception:
```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

**Comment by jeffythedragonslayer** [comment]
They told me to open a new issue here: https://developercommunity.visualstudio.com/content/problem/190287/vs2017-cant-detect-installed-winxp-component.html

**Comment by jeffythedragonslayer** [comment]
Fix for this is now in lastest Visual Studio Preview release, guess I'll try again.

**Comment by click4dylan** [comment]
This problem happens regardless of what version of Visual Studio 2017 you install, on any and ALL machines. I have tested on fresh copies of windows and the same issue happens. It is NOT fixed in the newer VS 2017 preview release as I have 15.9.0 Preview 1 and it is still showing the same error. I have spent many, many hours trying to solve this issue to no end.

**Comment by JunielKatarn** [comment]
Unless you are planning to run on XP, you can just change this value:
https://github.com/project64/project64/blob/master/PropertySheets/Platform.props#L5

From `$(DefaultPlatformToolset)_xp` to `$(DefaultPlatformToolset)`.
