### ISSUE TITLE
Public release 3.0 bad resolution jumping.

### ISSUE THREAD

**Issue by retrobenny** [project64/project64#1426]
It keeps changing resolution at random constantly and it causes a multitude of problems such as black screen flickers and jumpy rendering when not blacked out.

Beetle Adventure Racing is a good example of this,I noticed it in a few other games but forget which.
Kinda hard to get it in picture form due to the type of bug it is.
It may be caused by setting the resolution when a game is already running but that is a really irritating reason if true.
When the issue happened,there was a noticeable gradient on the sky-box.

Interpreter seems to make it act up from the looks of it.
Ending and starting emulation seems to also help cause it.

**Comment by theboy181** [comment]
lol.. retroben is talking about GLideN64 -  I think he is tired.

**Comment by retrobenny** [comment]
oops

**Comment by theboy181** [comment]
CLOSE IT BEN!

**Comment by retrobenny** [comment]
Technically it is a PJ64 version issue as Gonetz didn't run into the problems on a 2.3 build.
Guess I will close it anyway until further notice.
