### ISSUE TITLE
Project64 Just Looks Messed Up

### ISSUE THREAD

**Issue by DJTHEDJ1620** [project64/project64#1427]
![64f](https://user-images.githubusercontent.com/36066891/35722071-b1901bda-07a9-11e8-8342-8dc8cd237e10.png)

Here is what all the roms I try to run look like, Pokemon Staduim, Kirby, everything (also I couldn't play minigames in Stadium, don't know why, could be the rom). I uninstalled/reinstalled, nothing. I'm new to emulation, so it could be settings I don't understand. Any help would be appreciated

**Comment by jeffythedragonslayer** [comment]
What video plugin are you using?
