### ISSUE TITLE
Super Mario Star Road - Crashes with latest developmental build of Project64-Video (Frame Buffer Emulation Bug?)

### ISSUE THREAD

**Issue by SuperToad64** [project64/project64#1436]
Every time I try to run Super Mario Star Road in GlideN64 I get a completely black screen. Once I disable Frame Buffer Emulation I get this:

https://cloud.githubusercontent.com/assets/4800879/7552485/2268820e-f6b7-11e4-848d-4359335a1a94.jpg

https://cloud.githubusercontent.com/assets/4800879/7552476/c4b3c2ae-f6b6-11e4-80d3-66de5ede6219.jpg

This happens with almost all of the Super Mario 64 Rom hacks. It seems it has been an issue since 2015. With new Super Mario 64 hacks on the rise, this should be fixed. The reason I am using GlideN64 is because it is the only plugin that I know of that lets you make a custom windowed size. I am trying to use the entirety of my screen in windowed mode while playing Super Mario Star Road.

I have tried all of the settings inside Project64's graphics settings within GlideN64, nothing makes the black textures go away. But disabling Frame Buffer Emulation gets rid of the black screen. It is unplayable with the black textures though. It works in Glide64 Final because they use software frame buffer emulation. If you added a software frame buffer emulation setting it would probably fix all rom hacks. Any help would be appreciated.

I am running Project64 version 2.3.2.202 and I have the latest public Release of GlideN64 which is 3.0. I have already tried the recent WIP version of GlideN64 and it still doesn't work.

Similar to issue 525 in GlideN64: https://github.com/gonetz/GLideN64/issues/525
but it was closed with no fix.

Since issue 1745: https://github.com/gonetz/GLideN64/issues/1745

 was closed without much discussion and not solved in the GlideN64 plugin, I am offering a different solution. Since we cannot play ROM hacks on GlideN64 because of the black screen issue and the black texture issues why not add custom windowed resolutions to the old Glide64 plugin? That way people who want Custom Windowed Resolutions can have them when playing ROM hacks. I wouldn't mind if you guys added all of the new graphic options to the old Glide64 Final plugin as well, if it's possible. Because there were some really great additions like Anti-aliasing, Internal Resolution Scaling, the new enhancement method 6xBRZ, and of course the most important of all Custom Windowed Resolutions. I think it would be a reasonable goal to include these in the old Glide64 Final plugin. Is there any way you guys could make this happen? if you want to see the reason why I want Custom Windowed Resolutions refer to issue 1745: https://github.com/gonetz/GLideN64/issues/1745.

So since I am at a loss with GlideN64 I tried to solve the issue with Project64-Video.

In the newest version of Project64-Video v2.4.0-668-gc506db5 that was built in 2nd March 2018 there is the same black screen issue if you turn frame buffer emulation off. But if frame buffer emulation is left on it crashes the rom with this message:

CN64 System::RunRSP()
Unknown Memory Action
Emulation Stop

Tracking down the cause I found out that the last build where everything works fine is the v2.4.0-509-g64bcfa1 built in 25th September 2017. It even runs with hardware frame buffer emulation which is very weird. Because in Glide64 Final it would crash the rom if you had hardware frame buffer emulation on. So this signifies that it is not the ROM at fault.

So all of the builds after the v2.4.0-509-g64bcfa1 built in 25th September 2017 have the same issues I am experiencing with GlideN64. So now the newest versions of Project64-Video don't even work because something was changed between the v2.4.0-509-g64bcfa1 built in 25th September 2017 and the v2.4.0-512-g8d60ef1 built in 26th September 2017. Sadly there is no build between these so I don't know what code messed up the frame buffer emulation.

Here is the project64 development builds site: https://www.pj64-emu.com/nightly-builds

Even the latest version of Project64-Video doesn't have the ability to add Custom Windowed Resolutions like GlideN64 does and it still has the weird crash from frame buffer emulation and the black screen issue. So some change in the code has made this weird glitch not the ROM files themselves. If there is any way you guys can find out the cause for this weird crash and black screen glitch it would be much appreciated. If you can't fix the bug with the Frame Buffer Emulation then consider adding Custom Windowed Resolutions like GlideN64 to Project64-Video, because this would eliminate my issues entirely as long as the black screen glitch is fixed when Frame Buffer Emulation is turned off in Project64-Video.

I would have used GlideN64 if they fixed the black textures issue. But they refuse to because they think that the ROM hack is at fault not the GFX plugin. But with the evidence that I have found with Project64-Video that is not the case. More testing is needed to find the direct cause of the bug.

**Comment by project64** [comment]
how does it look on real hardware ?

**Comment by SuperToad64** [comment]
I have no idea, I don't have a N64. But I think it doesn't, because people on reddit says it doesn't. No official videos though: https://www.reddit.com/r/emulation/comments/3dl3l6/does_super_mario_star_road_work_on_a_real_n64/

**Comment by gamemasterplc** [comment]
it has the same exact bug even if you fix the MIO alignment and other things

**Comment by SuperToad64** [comment]
Don't know what MIO alignment means. I tried all of the graphics settings with no luck if that's what you mean.

**Comment by gamemasterplc** [comment]
its the compressed block alignment. real hardware crashes if the blocks arent 2 byte aligned

**Comment by SuperToad64** [comment]
Hm . . . not really tech savy with how emulation works. But all I know is that the rom hack works with Glide 64 Final, and like I said the v2.4.0-509-g64bcfa1 built in 25th September 2017 is the last build where it was working correctly.

**Comment by SuperToad64** [comment]
But the thing is there is no build between v2.4.0-509-g64bcfa1 built in 25th September 2017 and the v2.4.0-512-g8d60ef1 built in 26th September 2017 one. So I don't know what piece of code is the culprit. But whatever is happening is bad, because it completely crashes the rom. 

Because with GlideN64 it just has a black screen with no crash. Until I disable frame buffer emulation, then the textures are all black after that. But with Project64-Video it just crashes. But if I disable frame buffer emulation there is just a black screen. No settings after that fix the black screen so I am stuck.

**Comment by DarthDub** [comment]
Basically, Project 64 is trying to be more hardware accurate and a lot of Super Mario 64 romhacks are not hardware compatible. Blame the romhack, not the emulator.

**Comment by SuperToad64** [comment]
That's what I thought. I am hearing this from a lot of people. I guess I will have to contact the ROM hack creator and see if he can fix it then. But it would be great if someone would add Custom Windowed Resolutions to Glide64 Final. Because that is my main problem. I wouldn't even need GlideN64 if I had that.

I am trying to run a LAN server on one computer and I want all four emulators to be windowed and have the window cover the entire screen. But there is no 1920 x 1080 resolution in the windowed dropdown menu. That is what caught my attention about GlideN64, it is the only GFX plugin that I know of that lets you have Custom Windowed Resolutions.

**Comment by SuperToad64** [comment]
BUUUT . . . I got a fix from Discord64!!! It turns out the problem was a bad 0xFC setcombine. So the ROM file was at fault. 

It looks like Last Impact will have some issues as well:
 

Quoted by Trenavix
> yeah last impact is pretty trashed on everything that's not jabo's because kaze hardly tested anything
> if you do the setcombine trick on it it's playable but has some bugs here and there

So with the same vaules you can fix Last Impact the same way.

Thanks to Trenavix, here is the solution, its called the setcombine trick. You must use a Hex editor and replace all the values of this:
![fix super mario star road](https://user-images.githubusercontent.com/37228863/37260295-d14e9060-2567-11e8-9a0d-6d3bc206abed.png)

Make sure you have the hex-values option checked. You must replace all instances of FC 12 7F FF FF FF F8 38 with FC 12 18 24 FF 33 FF FF. Then save the rom, it's that easy! Thanks again Trenavix!

**Comment by theboy181** [comment]
Amazed at how solutions can be found when you omit negativity!   Glad you got your help. Looks like the issue is the author of the MODs lack of attention to plugins outside of his library. :)

**Comment by SuperToad64** [comment]
It's all thanks to you! Thank you so much, If you weren't so positive and helpful I probably wouldn't have found a solution. You are the best!

**Comment by SuperToad64** [comment]
Yet again Trenavix saves the day! When I set the resolution to anything over 1600 x 1200 in windowed and fullscreen it does this:

![aspect ratio 1](https://user-images.githubusercontent.com/37228863/37312690-6a589804-2622-11e8-80d5-a6c8d86a24d5.png)

![aspect ratio 2](https://user-images.githubusercontent.com/37228863/37312696-6f0f50a4-2622-11e8-9f85-f49483dcc9cf.png)

So since Frame Buffer Emulation is disabled I cannot set the aspect ratio. So Trenavix presents us with a .bps patch that will fix all of that. It even fixes the black screen that is present when Frame Buffer Emulation is switched on with GlideN64! So now Super Mario Star Road has no problems whatsoever.

This new edition is called Super Mario Star Road Enhanced Edition. It even adds 3D spinning models of all the coins, they look like they are from Super Mario Sunshine. Here is what it adds:


> Readme By SuperToad64:
> 
> Super Mario Star Road Enhanced Edition
> Patch By Trenavix - Discord64 Developer
> 
> To be used on a 8mb sm64 rom, Usually the general rom used is Super Mario 64 (U) [!].z64. You can get it from here: https://sites.google.com/site/supermario64download/Home/download-super-mario-64
> 
> patch with Flips.exe (Floating IPS Patcher) Download it here: https://www.smwcentral.net/?p=section&a=details&id=11474
> 
> Use the Super_Mario_Star_Road_Enhanced.bps (Version 1.1) First, if you have any problems use Star_Road_Console_Test.bps (Version 1.0), which doesn't include the texture fixes for the coins.
> 
> Changelog:
> 
> Star_Road_Console_Test.bps (Version 1.0): I got rid of the metal wing textures (I don't think you can even see those in star road ever) and used their data for polygon data
> 
> Super_Mario_Star_Road_Enhanced.bps (Version 1.1):  Fixed some ambient/diffuse colours on the red and blue coins so they no longer look greyscale and all coins have shading. Also fixed rom name.

So there you have it, it fixes all of the issues I have had thus far and adds some sweet looking new 3D coins, how can I say no? Totally Awesome! You can download it from the attachment below, enjoy!!

[Super Mario Star Road Enhanced Edition.zip](https://github.com/project64/project64/files/1804787/Super.Mario.Star.Road.Enhanced.Edition.zip)

Screenshots:



![super mario star road enhanced](https://user-images.githubusercontent.com/37228863/37312953-69ac8432-2623-11e8-8252-9182c3f2dc46.png)

![super mario star road enhanced 2](https://user-images.githubusercontent.com/37228863/37312958-6e306aaa-2623-11e8-9839-da7ac0c7ebba.png)

**Comment by loganmc10** [comment]
Lol you shouldn't be posting links to illegal downloads (including the ROM hack) on the pj64 GitHub page

**Comment by GB-CG** [comment]
@SuperToad64 Is the console patch meant to actually work on console? I've tried this on my Everdrive and got a blank screen with messed up music. Are there any special conditions on patching the rom?

**Comment by theboy181** [comment]
This game doesn’t work on real hw if I understand the hack correctly

**Comment by SuperToad64** [comment]
@GB-CG I am not sure if it works on real Hardware. I am guessing it doesn't. But if you could try it out on a real N64 and then report your findings here that would be really helpful. Just make sure you patch the ROM like I did above, or download the included files.

**Comment by GB-CG** [comment]
Somehow I've only found this out now; macN64 tried to make it work on hardware and here's the result: https://youtu.be/ROgEQHsqSRM?t=12m15s
