### ISSUE TITLE
ROM Scan Hangs

### ISSUE THREAD

**Issue by Kolano** [project64/project64#144]
With v20150222 (and likely other revs) the ROM scanning process seems to frequently hang. Particular ROMs will be reached and then no progress will be made. If the archive with the ROM it's hung on is removed the scan will continue, but then gets hung again.

On a 7zip'd No-intro set it seems to consistently hang on:
* Mystical Ninja Starring Goemon (USA).n64

And then, if that is removed:
* Knockout Kings 2000 (USA).n64
* World Cup 98 (USA) (En,Fr,De,Es,If,Nl,Sv,Da).n64
* Powerpuff Girls, The - Chemical X-Traction (USA).n64
* Legend of Zelda, The - Majora's Mask (Europe) (GameCube Edition).n64

...and so on.

**Comment by death-droid** [comment]
Wait are you trying to get Project64 to load a zip/7zip file that contains more than one game?

**Comment by Kolano** [comment]
Does not occur with decompressed ROMs.

7zip using LZMA2.

**Comment by Lithium64** [comment]
@Kolano Project64 only support 7z LZMA1 compression

**Comment by Kolano** [comment]
OK, I can confirm that things seem to work out after converting the set to LZMA.

But...
* Use of LZMA2 probably shouldn't cause the hangs I was seeing.
* The LZMA2 mode is fairly stable at this point, and may be worth implementing (though it's improves compression by ~5Mb).
* The scanning of compressed ROMs seems quite slow. Can it be done based off the checksums that can be extracted from most compression schemes rather than by decompressing each archive?

**Comment by project64** [comment]
> The scanning of compressed ROMs seems quite slow. Can it be done based off the checksums that can be extracted from most compression schemes rather than by decompressing each archive?

with 7zip they are solid state zips which means you get really good compression but you need to extract it all to get the information from it. I do cache that information so the second time it is much faster. If they are just in a zip it should be able to just read the start of the file and not be to slow.

> The LZMA2 mode is fairly stable at this point, and may be worth implementing

I am just using a 3rd party library, I can see if there is an upgrade that supports this

**Comment by Kolano** [comment]
> with 7zip they are solid state zips

Though 7z supports solid archives, I am not using solid compression on my 7z's. At least it seems like the scan results are remembered between runs, so it's only slow the first scan.

> I am just using a 3rd party library, I can see if there is an upgrade that supports this.

I believe the default 7 dll does. http://www.7-zip.org/sdk.html

**Comment by project64** [comment]
extracting check sums, sure, but I am retiring data inside the file, which is not the same

**Comment by death-droid** [comment]
The LZMA SDK has change rather extensively since the release that Project64 uses. The Version project 64 uses is 4.21, current version is 9.38
Will need to change the way our interface with the library works to use it im fairly sure.

**Comment by cxd4** [comment]
"On the bright side there is a CPP version of the SDK now"

Oh nice, really?  I prefer 4.21 then.

**Comment by Lithium64** [comment]
What's new:

    9.38: Some bugs were fixed.
    9.36: Some bugs were fixed.
    9.35: Some bugs were fixed. AES code and SFXs modules were included to SDK.
    9.20: New small SFX module for installers.
    9.11: PPMd support.
    9.04: LZMA2 and XZ support.
    4.62: Some fixes. LZMA SDK is placed in the public domain.
    4.58: Speed optimizations. New ANSI-C code for LZMA compression.
    4.57: Speed optimizations. Some fixes.
    4.49: .7z ANSI-C decoder was improved. C++ code for .7z archive handling was included.

**Comment by death-droid** [comment]
Considering Project 64 is mainly C++ it would make sense to use C++ libraries.
Theres still a C version of the SDK.
And to note the reason for upgrading the library would be to add LZMA2 support more than anything. There are also speed improvements in the newer versions.

**Comment by project64** [comment]
ok I have upgraded the sdk (https://github.com/project64/project64/commit/2a583fd13c427dcdfb9fea9adc14517ff492a455) 

does this fix the issue?

**Comment by Lithium64** [comment]
@project64 7z compressed roms aren't loading at all now

**Comment by cxd4** [comment]
"Considering Project 64 is mainly C++"

Oh nice, really?  I prefer 1.4 then.

>@project64 7z compressed roms aren't loading at all now

I'll check it on IRC when I get a chance.  The new version of the SDK should work eventually.

**Comment by Lithium64** [comment]
LZMA2 is working fine now

This issue can be closed
