### ISSUE TITLE
Mario Party 2 text looks like crap

### ISSUE THREAD

**Issue by DimensionPizza** [project64/project64#1440]
Don't know if this is exclusive to PJ64 or not, but the text looks like crap in most places of the game.

![mario party 2 u - project64 2 3 2 202 3_20_2018 8_14_03 pm](https://user-images.githubusercontent.com/37603356/37690875-ce21b370-2c7b-11e8-9c9e-117f97215e0e.png)

Other places, like the Minigame Coaster and Sound Test, the text appears like it should.

![mario party 2 u - project64 2 3 2 202 3_20_2018 8_29_55 pm](https://user-images.githubusercontent.com/37603356/37691156-d33c1f10-2c7d-11e8-9005-5c78cca683c3.png)

Is there a fix for this? Is my rom bad?

**Comment by vgturtle127** [comment]
@DimensionPizza Can you give us more information like Project64 version, plugins used, ROM information, settings used, etc.?

**Comment by DimensionPizza** [comment]
@vgturtle127 

PJ64 Version: 2.3.2.202
ROM: Mario Party 2 (NTSC-U)
Plugins: Jabo's Direct3D8 1.7.0.57, Jabo's DirectSound 1.7.0.7, N-Rage for PJ64 2.5.2.202, RSP Plugin 1.7.3.202

Running 1366x768 on Stretch mode (but the issue persists in any other config)
Full Screen Sync: Double buffer V-Sync
All other settings are default

**Comment by vgturtle127** [comment]
@DimensionPizza Have you tried with Project64-Glide64 and GLideN64?

**Comment by gamemasterplc** [comment]
It's your graphics plugin forcing bilinear filtering for some reason. This texture actually should be nearest neighbor filter.
