### ISSUE TITLE
PJ64 [ROM Browser, and settings],  malfunctioning 

### ISSUE THREAD

**Issue by MelchiorGaspar** [project64/project64#1444]
Project64's ROM Browser settings are getting messed and or malfunctioning...
when I go to select to remove or add to the active column list for the ROM Browser.. it will afterward add ALL OF EM!..  but show nothing...  its just plain not working right...

idk why.. :-( X_x

**Comment by MelchiorGaspar** [comment]
probably related...

**Comment by project64** [comment]
did https://github.com/project64/project64/commit/bab9d93ebbee1f9991a3fe858c0e8e850c4e4c1b fix the issue?

**Comment by vgturtle127** [comment]
@project64 Not for me, unfortunately.

**Comment by project64** [comment]
ok, I will look in to it tonight, it is likely to be something similar to the mentioned change

**Comment by MelchiorGaspar** [comment]
ok THX Zilmar

**Comment by vgturtle127** [comment]
@project64 Alright, thanks, man.

**Comment by project64** [comment]
I can not seem to reproduce it with latest source. how am I meant to generate this issue

**Comment by MelchiorGaspar** [comment]
ok I reset parts of the PJ64 ini/cfg that deals with the ROM Browser by deleting it..
the original columns returned on next start.. but as soon as I added on more column and hit apply, 
the all disappeared the visible columns that is...... and when I restarted PJ64 and reopened the 
"ROM Selection"  settings. all columns were enabled BUT NONE are showing.. STRANGE!!??

**Comment by project64** [comment]
can you try to unzip v2.4.0-683-gbab9d93 to a new directory and see if it still does the same behavior for you?

**Comment by MelchiorGaspar** [comment]
I just saw build 683 so I a getting it now...
ok will do..

**Comment by MelchiorGaspar** [comment]
OK v2.4.0.683 is WORKING again!!
