### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by Rikimaruaxu** [project64/project64#1448]
There is a bug that when you enable any cheat in project64 and exit the window. it enables all cheats in the list. Makes it hard to use them without deleting everything.

**Comment by TradeDraft** [comment]
I have the Same Problem and Makes you can't play the Game with Cheats on as you get Graphic Bugs.

Video Showing what Happens:

https://www.youtube.com/watch?v=6Kbxp1DnMSs

**Comment by theboy181** [comment]
Should get fixed in next release.

**Comment by project64** [comment]
I worked out what is wrong, I will commit the changes tonight to fix it.

**Comment by TradeDraft** [comment]
Awesome.

Glad you found what the Problem is.

As it was/is a Major Problem when trying to play Games when using cheats

**Comment by project64** [comment]
https://github.com/project64/project64/commit/0f41a6459cb63576f51d0ca725b1b6d9efe6059d (v2.4.0-691-g5d7dc12) should fix the issue

**Comment by TradeDraft** [comment]
Just Tested the Latest Version you put up and the Problem is Fixed.

Thank you very much for fixing that
