### ISSUE TITLE
Gloabal variable in settings.

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1449]
@project64 Would it be possible to add [Global] to the project64.cfg

I was hoping that we could set overrides to all cfg settings.

Example:

[Global]
RDRamSize=16777216

This would help with debugging hacks that change CRC's every time they are updated.

**Comment by project64** [comment]
yes it should not be hard to add it to the settings system. Not sure about UI .. but that is probably doable as well.

What setting you want as a global configurable?

**Comment by theboy181** [comment]
Looking for anything that has to do with ROM settings. All would be helpful but at this time the request is more for Kaze and memory seems to be his flavour!

**Comment by project64** [comment]
well I am more just going to do the ones you want at this point instead of trying to get it more complete. Which is why I ask what you want.

**Comment by theboy181** [comment]
Expansion Memory
FAT
Sync Audio

Could be a great start.

**Comment by theboy181** [comment]
I forgot counter factor

**Comment by LegendOfDragoon** [comment]
Is there any missing features? Now i see a "defaults" which includes some of these options.

**Comment by project64** [comment]
yer this probably can be closed, still might be some bugs to be fixed, but we can open a new ticket for those fixes if we need a ticket
