### ISSUE TITLE
Pokemon Stadium GB tower petition

### ISSUE THREAD

**Issue by AlexN64gamer** [project64/project64#1461]
Dear Project64 team and users, I would like to ask for your help and kindness about this matter, when I was a child, I was a big pokemon fan (I was born when the first generation was recent) but at the time I couldnt afford a game boy, I had an N64 and pokemon red, but didnt have the transfer pak, so I was never able to play the game on the GB tower, sorry for telling my life... Ill go straigh to the point, I know there are many GB emulators nowadays and they can do most of the features the GB tower had, but, im asking this cause I could never see the actual game loading and being played on GB tower, PLEASE, Project64 developers, can I ask you, with all my humility, to try to make the GB tower functional for future builds of the emulator? if I can help anyway, just tell me, THANKS A LOT IN ADVANCE

**Comment by wfowler1** [comment]
Last time I tried, GB Tower was working, but it kind of sucked. It might not work in the latest released version, I think I was using a build from source code at the time.

**Comment by weinerschnitzel** [comment]
I think it would be helpful if you described the exact issues that exist with GB tower in the current builds from source or already compiled. Try testing with Angrylion's video plugin and compare with another emulator, or better yet the real hardware. What is Project64 failing to do? What's happening? How do you run into it?

**Comment by AlexN64gamer** [comment]
sorry if I wasnt enough clear about the issues, I know nothing about technical behavior of emulator and plugins, but I will do my best to describe it to you, also I forgot to tell in my original post that two of my greatest reasons to ask this is to see doduo and dodrio borders in the GB tower, which I couldnt as a kid :) I will test the GB tower with angrylions and GlideN64 lastest builds and send pictures and try to describe whats the problem, THANKS A LOT for your feedback guys ¡¡¡

**Comment by AlexN64gamer** [comment]
Ive just tested it with angrylions graphics plugin lastest update, and Project64 2.3.2, Nrage plugin included with the emulator and Pokemon Stadium NTSC-U and PK red gb with a save game in the pk center, when I try to play the GB tower it starts to load the game but just freezes about a minute after that... so, I guess theres no way to acces the GB tower for now, I kindly ask for this feature again :( would anyone with programming knowledge help me? please

**Comment by CrashOveride95** [comment]
![image](https://user-images.githubusercontent.com/40003130/41604163-94f86314-73ac-11e8-8a8f-a5955d97060d.png)
on latest build of PJ64 with Glide64 Final, it will detect game pak but gives this error when loading pokemon yellow.

**Comment by CrashOveride95** [comment]
![image](https://user-images.githubusercontent.com/40003130/41635525-3c9a8c68-7417-11e8-8d2a-7b533c21eb2e.png)
Pokemon Stadium 2's GB Tower will boot, but nothing will show, ill try with angrylion.

**Comment by CrashOveride95** [comment]
![image](https://user-images.githubusercontent.com/40003130/41635811-d444fa8e-7418-11e8-9be4-703ee3539555.png)
![image](https://user-images.githubusercontent.com/40003130/41635836-f5c199d8-7418-11e8-9369-add32e47bb67.png)
AngryLion works with stadium 2.

**Comment by AlexN64gamer** [comment]
What Project64 version are you using? and what Angrylion plugin version too?

**Comment by AlexN64gamer** [comment]
could it be possible to make it work with HLE plugin like glide64 or GlideN64 in Stadium 1? what I dont get is; does it has to do with the graphics plugin? input plugin? or just the emulator code? or a combination of everything? sorry if its a silly question

**Comment by weinerschnitzel** [comment]
If something works with Angrylion's but not your favorite video plugin, then your favorite video plugin has an issue. 

Stadium 1 looks like an issue with the core or input plugin.

**Comment by oddMLan** [comment]
Duplicate #964
