### ISSUE TITLE
Interpreter: DADDI opcode is missing from Interpreter

### ISSUE THREAD

**Issue by bryanperris** [project64/project64#1464]
In fork, I am testing every single instruction against PJ64 through a remote system.
I have encountered an error in the interpreter and I may provide the fix for this later too.

PIF ROM Note: I am indeed injecting assembly into that section after I had fixed the MMU mapping for PIF ROM itself.

Win32 Dialog
*************************
Unhandled R4300i opcode at: BFC00000
DADDI	V1, AT, 0x0004

Stopping Emulation !
*************************

I can confirm this instruction is indeed missing from the Interpreter in both versions: 32/64.

` Jump_Opcode[24] = UnknownOpcode;`

The DADDIU implementation looks wrong here but seems to be the more appropriate implementation for the DADDI instruction.

`void R4300iOp::DADDIU()
{
    _GPR[m_Opcode.rt].DW = _GPR[m_Opcode.rs].DW + (int64_t)((int16_t)m_Opcode.immediate);
}`

My quick solution is turning DADDIU into DADDI, and then DADDIU is the same operation but uses UDW instead of DW from the union.

HTH.

**Comment by theboy181** [comment]
Great bug hunting. Does the instruction work as it should while using recompiler?

**Comment by bryanperris** [comment]
I found that instruction listed in the assembler, but do not know if its supported or not. this would be a nasty instruction bug for games using the 64-bit ALU.

**Comment by theboy181** [comment]
Are there any games that support 64-bit ALU? Maybe a test ROM is needed?

**Comment by bryanperris** [comment]
I don't know about the games, but this repo has a lot of test ROMS for the real system: https://github.com/PeterLemon/N64/tree/master/CPUTest/CPU

What I do know is that the interpreter will throw an exception if anything hits it.  Once I do fix it, I will run my unit tests against it.  In my own project, I am comparing my own interpreter against the one in PJ64, so I will keep rolling with that, and post anything that crops up.

**Comment by theboy181** [comment]
Thanks for sharing, and good luck.

**Comment by bryanperris** [comment]
I can't name any benefits other than the interpreter now should be a little more accurate, except in the case of timing and exception management.

**Comment by theboy181** [comment]
still very cool!  You going to do a PR, or leave that up to @project64

**Comment by theboy181** [comment]
https://discord.gg/KWkZWw

**Comment by bryanperris** [comment]
Problem with a PR is I have made a lot of changes that aren't needed here, so I leave it for someone dedicated on the team to check in the patch and verify.

**Comment by theboy181** [comment]
Where are you hosting these changes?  Do you have a project I can follow?

**Comment by bryanperris** [comment]
https://github.com/bryanperris/project64

**Comment by project64** [comment]
DADDIU and DADDI should be basically the same since i am not looking at overflow at all in pj64. Mostly I just added ops as it was hit on games. At some stage I need to try to do more based off tests, not just what games do.

**Comment by bryanperris** [comment]
At some point I would like to collab with you on documenting the best MIPS test cases.  I already have offline a C# based unit test system which assembles an instruction, writes the binary into memory, do a core step, then checks the expected result (GPR, Lo, Hi, etc).  Also I check the exception state too, like if a reserved exception is thrown when executing a 64-bit ALU instruction while operating in 32-bit mode.  In the case of running against PJ64, I skip the exception check.

**Comment by project64** [comment]
what do you think is the best testing method.

something like cppunit that has small tests just on each op with creating scaffolding for the rest of the system.

Something like your suggesting where you write a binary to memory and execute that.

I like the idea of what peter lemon has in his tests. It might be good to be able to do something where I could on build, run Project64 with a test rom and verify it gets 100%.

**Comment by bryanperris** [comment]
I do like all these ideas.  I think the test roms are easy for you since you have a working RCP component, as compared to what I have working so far.  Also compiling a C++ unit test application that documents and tests the core system is plus too.  My main idea is getting out a document that lists each instruction, and then their expectations on how execution should happen, probably the slowest/longest process here and of course the format needs to be clean.  At least having somewhere a listing possible values to throw into execution and what the results should be.  Same for the RCP part in the future.  What I did in a PJ64 fork was add a JSON web service that listened and responded to commands issued by C# unit test, but probably the most complex solution here.

**Comment by project64** [comment]
closing this for now
