### ISSUE TITLE
JS API Usage

### ISSUE THREAD

**Issue by AWBuchanan7** [project64/project64#1469]
Hi! I admit I feel like a bit of a fool because I can't seem to figure this out. I've started writing some scripts for the JS API, and I can't seem to find a way to actually run the scripts to test them.

I've unhidden advanced settings and enabled the debugger, but I don't see anything along the lines of "Script Settings" am I just missing something? Any help would appreciated.

**Comment by theboy181** [comment]
you are talking about the scripts for the debugger?
![image](https://user-images.githubusercontent.com/9299743/42139373-5da0b706-7d41-11e8-8c4e-a1ed9bb8fe25.png)

I put them in that folder and make sure you have debugger turned on with int cpu on as well.

**Comment by AWBuchanan7** [comment]
My god, I finally figured out what my problem was, I simply had gotten mixed up with an older build of Project64, using the latest it seems to find my scripts and have script settings under the Debugger menu.

Thanks for the help though!

**Comment by theboy181** [comment]
Nom I’m interested on what your working on sorry I wasn’t more help.

**Comment by AWBuchanan7** [comment]
Oh! If you're interested, I'm working on a set of scripts that specifically target Zelda to create a sort of "mod support" layer! Sort of inspired by the work being done in github.com/MinecraftForge/MinecraftForge except, of course, for Ocarina of Time instead of Minecraft. So it's like there will be a "Camera" script that you can import to easily work with the game's camera, or an "Equipment" script you can import to easily work with equipment in the game.

In trying to develop this I'm trying to write "mods" that use these scripts as well. Right now I'm working with the game's default camera to create a mod that allows the player to control the camera with the mouse!

You can probably expect to see me ask more questions around here as I work on this because I seem to be having a variety of smallish problems with defining classes and such.

**Comment by theboy181** [comment]
I think you may find better support from scripting on one of the discord servers. Discord64 has the developer that built the scrupt engine  would you like an invite?

**Comment by AWBuchanan7** [comment]
That would be awesome! I'm not terribly active on discord but I could certainly use the connection!

**Comment by theboy181** [comment]
https://discord.gg/m3fqNBS

Just say high and read the rules for a role request.
