### ISSUE TITLE
Super Mario 64 freezes after 2.4.0.661-g1178b5c7

### ISSUE THREAD

**Issue by LuismaSP89** [project64/project64#1470]
Super Mario 64 freezes before the "Select savegame" screen. The latest build working that I found is "Project64 2.4.0.661-g1178b5c7"

Tested with "Project64 2.4.0.737-g93ab869c" and ahead (Current build is Project64 2.4.0.756-gf20dca31)

Tested with default and custom plugin/settings.

Windows 10 x64, 16 GB RAM, i7 4790k, GTX 970.

Note: Tested in project64 x32 builds.

**Comment by theboy181** [comment]
working here, clean install?

**Comment by LuismaSP89** [comment]
@theboy181 Yes, clean install. Sorry but, what version are you using?

I use the latest version (2.4.0.756-gf20dca31) you can download here: 

http://www.emucr.com/2018/05/project64-git-20180523.html

**Comment by theboy181** [comment]
im using 
![image](https://user-images.githubusercontent.com/9299743/42140249-be4b7f68-7d51-11e8-8175-fa64c5c7c566.png) I think its the most recent. 

Have you tested with different plugins?

**Comment by theboy181** [comment]
turn on the debugger in PJs options and see if you get an error message. 

I have been using PJs RSP with GLideN64 what is the MD5 of your ROM
49FBF9C744C458405F685D42B762A0BE

**Comment by theboy181** [comment]
One more thing, stay away from emucr, I don't think they build correctly, and the last official build does not match emucr's


![image](https://user-images.githubusercontent.com/9299743/42140344-0d8ca83a-7d53-11e8-9843-cb1b75db4929.png)

**Comment by theboy181** [comment]
Please test latest build, and close

**Comment by theboy181** [comment]
@project64 can you close this please, I think he is using bad builds. Maybe you need a disclaimer that says the GitHub doesn't support emucr builds.

**Comment by LuismaSP89** [comment]
@theboy181 I can´t download these builds, since it´s only for patreon users. You should have waited other users to test this problem, maybe works for you, but maybe is not for other users. I can´t understand why there´s all this hurry in order to close an issue...

**Comment by LuismaSP89** [comment]
Tested with official build from a patreon´s friend and still failing, the problem is that we use a spanish rom, and since that build "Officially from project64" can´t run this rom.

**Comment by LuismaSP89** [comment]
MD5 of the ROM: B84F6ACCA42F66A52FD802E9172730A4

**Comment by theboy181** [comment]
There is an official Spanish ROM, or its a hack. Try turning on 8MB ?

**Comment by theboy181** [comment]
I patched the Super Mario Spanish hack to an official ROM. You are correct it does not load into the save game area. I tested with altered settings, and there are no msg boxes with an error. 

A recent change that was made around this time (iirc) was the correction of r0 = zero - This hack may have used r0 inappropriately and is now suffering because of it. 

Since this is a hack, I'm not sure if this is the right place for support for it, However there are people here that are devoted to understanding things like this, and attempting to explain/fix them.

@LuismaSP89 - are you able to test other hacks, and official SM64 ROMs to see if any of the others have this issue? 


@LegendOfDragoon can you debug? 
@project64 do you think you should reopen?

**Comment by oddMLan** [comment]
I'm thinking more that it's this commit that made this hack stall at the save screen

https://github.com/project64/project64/commit/f0c9ea887e62712e411133e3b3c9e4629db5d9fe

Can anyone test the hacked ROM I'm real hardware and see if it crashes too?

**Comment by theboy181** [comment]
Just tested on real HW same issues. Sorry the ROM is the issues.

**Comment by LuismaSP89** [comment]
Yes, it´s a patched rom (USA) with spanish language. (EU version only have French, English and German)

I have other games with patches, like Ocarina of time (USA) and Conquer Bad fur Day (USA too) patched with spanish and all works ok, Super Mario 64 is the only game that doesn´t work.

Log file is 0kb since Project64 hangs before the save game area.

Memory dump attached (Sorry, i don´t know if this helps or you need something else)


[Memory.zip](https://github.com/project64/project64/files/2156370/Memory.zip)

**Comment by theboy181** [comment]
I am unsure if you read the posts above, the hack is the issue. As PJ64 gets more accurate, sloppy ROM hacks will not work. 

You will have to update the ROM hack, or use an older version.

**Comment by LuismaSP89** [comment]
Yes, I read the coments, sorry, I only wanted to look for an alternative solution. It´s a shame that all these Rom hacked games (Goldeneye, Ocarina of time, Conquer, etc) Works and this one can´t...

Thanks for your help, both of you.
