### ISSUE TITLE
Big texture pack problems

### ISSUE THREAD

**Issue by LuismaSP89** [project64/project64#1471]
Project 64 can´t boot OOT "And maybe other games" if you´re using one of the latest versions and a big texture pack "Links provided".

**Working in:** Project64 2.4.0.661-g1178b5c7 

**Last test in (Fails) :**  Project64 2.4.0.756-gf20dca31

Note: Using gliden64 with same options in both cases, the problem is with project64 latest versions.

Texture pack download:

https://emulationking.com/loz-ocarina-of-time-community-retexture/

http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7

**Comment by LuismaSP89** [comment]
![sin titulo](https://user-images.githubusercontent.com/12205048/42162193-12096adc-7dfe-11e8-89a2-d46be697a1e9.jpg)

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 Project64 now enables a compiler setting called large address aware. That might fix your problem.

**Comment by LuismaSP89** [comment]
It seems fixed, thanks a lot ; )
Closing.
