### ISSUE TITLE
Add SPECTRE mitigation to Project64

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1475]
Everyone's probably heard of the SPECTRE (and MELTDOWN) CPU vulnerability already. Hardware and OS vendors have been releasing updates for a while to mitigate this vulnerability. However, something important to keep in mind is that nearly all programs also need to be updated to mitigate the vulnerability, or they risk becoming attack vectors.

Mitigations can be added automatically by Visual Studio as described here: https://blogs.msdn.microsoft.com/vcblog/2018/01/15/spectre-mitigations-in-msvc/

So basically, Project64 should be configured to be built with the /Qspectre switch and tested for any issues that might arise. Theoretically, additional mitigations might also need to be added manually to the code, however that would require extensive analysis which is probably beyond reasonable.

(Third party plugins and libraries should also get the same treatment, by the way.)

**Comment by JunielKatarn** [comment]
It would also be a good idea to start building with Visual Studio 2017.
Tons of compiler improvements, and Spectre-ready libraries.

**Comment by oddMLan** [comment]
As already discussed in the Discord, I really see no point as Project64 doesn't store any sensitive information such as passwords or credit card numbers. Besides an updated Operating System/BIOS/Firmware already has these mitigations built in.  So it's only going to cause a performance penalty.

**Comment by bryanperris** [comment]
Interesting topic here, but here is the bottom line, PJ64 generates native code at runtime with its recompiler feature so the security checks in VS2017 would be useless at this point. The Javascript V8 is a good example of a system that recompiles code but involves a lot security checks including some of the Intel bugs.  

http://bt3gl.github.io/a-closer-look-at-chromes-security-understanding-v8.html
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/ssca

**Comment by Fanatic-64** [comment]
So, the recompiler would need extensive modifications to avert this vulnerability, and Project64 cannot access memory outside of its own process anyway. Is this correct? If so, this can probably be closed as a WONTFIX.

**Comment by project64** [comment]
not changing anything for this
