### ISSUE TITLE
OOT Rom Decompression Crashes on Death

### ISSUE THREAD

**Issue by gamemasterplc** [project64/project64#1477]
Using the http://www.mediafire.com/file/od4y72l0r57d7tl/newdec.7z program to decompress the OOT ROM makes project64 freeze when you die from anything. It happens on almost all video plugins except recent GlideN64 in HLE mode. The decompressor does work properly on console so its not a shitty hack bug.

**Comment by ata4** [comment]
[This is the line where the RSP is crashing.](https://github.com/project64/project64/blob/2cb00d34112c49c816ec96eb4fa851df09035fd7/Source/RSP/dma.c#L128)

**Comment by gamemasterplc** [comment]
If the emulator complains at all because some plugins dont complain and just silently crash.

**Comment by project64** [comment]
That it runs on a default rom, I am going to close this issue for now. If I can understand what exactly is causing it then I can come back and re-open this issue.  Does this hack actually change anything in the game?

**Comment by gamemasterplc** [comment]
It happens on the debug ROM too which was a leaked prototype of the game with decompressed assets.
