### ISSUE TITLE
Deticated GPU not getting selected and freezing the emulator. iGPU works fine.

### ISSUE THREAD

**Issue by RVOtakuMike** [project64/project64#1478]
I have a laptop that has integrated graphics (Intel HD 630) and dedicated graphics (NVIDIA GeForce 1050ti).
When I launch Pj64 with my iGPU enabled, it runs fine, but when I select my dedicated GPU (NVIDIA settings) Project 64 still thinks I'm using the iGPU (atleast according to Jabo's Direct3d8 plugin) and freezes on launch of any game.

I have tried all available plugins plus gotnez's GlideN64 and it still happens, which makes me think somethings messing up in Project64 itself.

I have also compiled the latest source and still have this issue.

Thanks for your time.

If I didn't explain the issue well enough, I can record the issue.

**Comment by Fanatic-64** [comment]
The discrete GPU can only be used by DirectX 9 and above and OpenGL applications. DirectX 8 and below applications will always use the integrated GPU. So you need to use a DirectX 9 or above or OpenGL video plugin, and configure Project64 to use the discrete GPU from the Nvidia control panel. If you use Jabo's plugin, it will always use the integrated GPU because it is DirectX 8.

**Comment by RVOtakuMike** [comment]
I have tried using Glide64, Project64 video, and GlideN64. All cause Project64 to hang. WHen running it in the debug mode it definatly throws an exception every time I launch a game: `Exception thrown at 0x781E0001 in Project64.exe: 0xC0000005: Access violation reading location 0x56AF0008.`

When I click break and click go to source  it highlights line 727 of RecompilerClass.cpp.

I am new to this stuff but I am willing to help you guys fix this.

**Comment by project64** [comment]
I have no clue how to fix this, or what to do with it, closing for now. If more info about what can be changed comes up I can reopen this issue.

**Comment by suerion** [comment]
I have not the same problem, but Project64 does not found my dedicated gpu.

in my laptop, there is intel hd3000 series. Low gpu and amd radeon hd 6300 series (legacy). But the amd dedicated gpu was not found. I had also switched from low voltage to high voltage gpu settings. It does not work.

is there a other plugin to use dedicated gpus?
