### ISSUE TITLE
Z-buffer issues with Jabo's video plugin on Intel iGPUs

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1482]
Jabo's video plugins (as well as other DirectX 8 and below plugins) have always had Z-buffer issues on Intel iGPUs (Intel GMA, Intel HD Graphics, Intel Iris Pro), causing graphics in close planes to not be rendered or to be rendered with Z-fighting (for example the shadows, the dirt paths and the holes in both Zelda games). This is an important issue because the vast majority of PCs sold nowadays come with Intel iGPUs, and even those that also come with discrete GPUs generally do not allow them to be used with DirectX 8 and below programs. It has previously been suggested to wait for Intel to fix the issue, and while other issues have been resolved with newer drivers and iGPUs, this one remains even with the latest hardware and drivers.

Below I outline some general possibilities for addressing the issue:

1. Replace Jabo's video plugin with a plugin that does not have this issue, such as the included Glide64 for PJ64.

2. Force the use of a 24-bit Z-buffer with all DirectX 8 and below video plugins. This can currently be done with external programs and does have the effect of fixing the Z-buffer issues on Intel iGPUs.

3. (Hack Jabo's plugin specifically to use a 24-bit Z-buffer. Maybe this can be done with reverse engineering and hexadecimal editing, but I don't know how feasible or technically legal it would be.)

**Comment by Fanatic-64** [comment]
GLideN64 should work with the Nvidia GPU if you configure project64.exe to use it in the Nvidia control panel. The problem concerns only DirectX 8 and below plugins which cannot use the Nvidia GPU even with the above procedure.

**Comment by bryanperris** [comment]
I wonder if you can bypass this DirectX 8 issue with WineD3D (https://fdossena.com/?p=wined3d/index.frag).  This library wraps the whole D3D8 API over OpenGL, so at the OpenGL level you should be able to make it render using the dedicated GPU.

**Comment by Fanatic-64** [comment]
I guess that would solve the problem in Linux, but we still need a fix for Windows...

**Comment by bryanperris** [comment]
WineD3D is for Windows.

**Comment by project64** [comment]
Can not change jabo's video plugin
