### ISSUE TITLE
Cic Chip for demo/development rom

### ISSUE THREAD

**Issue by xoorath** [project64/project64#1485]
I'm getting this CicChip for roms I build myself from source using the N64 SDK: `C92ADFE50A`, I got this value from the log.

Causes an error to pop up, but it can be dismissed.

**Comment by bryanperris** [comment]
If you are using a CIC seed not known by the emulator, the PC starts at 0xBFC00000 which is the MIPS's hardcoded start address, this in fact won't work in the emulator unless it has the IPL rom available.  Look in the N64Class.cpp for the support CIC types.

**Comment by xoorath** [comment]
Thanks @bryanperris, I'm still learning N64 development, wasn't sure the right way to get around this.

For the future, if anyone else runs into this, use makemask.

In your makefile add `makemask $(TARGETS)`, like so:
```
$(TARGETS):	$(OBJECTS)
		$(MAKEROM) spec -I$(NUSYSINCDIR) -r $(TARGETS) -e $(APP) 
		makemask $(TARGETS)
```

See: https://docs.google.com/document/d/1zONLHYZ8f09buku95ByM_vGxBZ2zGziJCXa47FtO0rU/edit
under the section "What is the CIC? How do I fix the error messages?"
