### ISSUE TITLE
[Suggestion] 2 button inputs for each button

### ISSUE THREAD

**Issue by MarkBlackWhite** [project64/project64#1487]
Note: i don't know if anyone has already asked for this, but i'm gonna ask anyway.

I think it would be neat to be able to have 2 inputs for each button. Also, for the Analog Stick, i think that would be cool if we could put 2 button inputs for different ranges. Lemme actually explain what i mean: pressing an button input once for the An. Stick for it moving to a range of 33%, and pressing the same input twice for a range of 66%. OR having 2 different inputs for different ranges for the Analog Stick.

**Comment by theboy181** [comment]
Interesting. What is the reason behind the multiple input ranges?  How would you activate different ranges with the same button.

**Comment by MarkBlackWhite** [comment]
First, i would like to state my reasoning for different ranges. In games like Super Mario 64, if you tilt the Analog Stick just a little, you can sneak behind enemies like Piranha Plants which are asleep, and in this way you don't wake them up. If you tilt the Analog a little more, you just slighlty walk. But if you tilt it completely, you run. I couldn't be able to sneak or walk in SM64 without having to change the Analog's range in the Controller options. Also, in games like Pokemon Stadium you have mini-games like Ekans' Hoop Hurl where you have to tilt the Analog at multiple ranges to throw at different distances. Of course, in this case you would have to just use a N64 controller, but for SM64 you can just put two inputs.
 Now for my explanation on to how to use different ranges. You know how there's [two configuration options for the Analog Stick?](https://i.imgur.com/DS8l6Ay.png) Well, what if we could ALSO change the ranges for each configuration AND be able to use them both simultaneously? I think that would work in some way. As for how you would activate different ranges with the same button (which is the question you've mainly asked), now that i look at it again, it sound farfetched. But i'll still try to show how can this be possible. Look at [this.](https://i.imgur.com/DzYG7OW.png) You see, my idea is that we could input the same button but pressed twice, so we could activate the other range. It's a poor explanation, but i THINK it could work if done right.
 BUT i would also like to state the possible problems with this. One, it could be broken and not work properly, and two, the emulator wouldn't be able to select the double button input. It's for you and others to decide.
 
 Also, while writing this, i had an idea. What if we could put 2 buttons for the same input. I mean, like using [Ctrl+W] or [Ctrl+A] etc. I thought that i would work for something like the Control Buttons. Let's say i use these inputs for the Analog: [W] for Up, [A] for Left, [D] for Right and [S] for Down. But if i wanted to use the Control Buttons, i would have to use the same inputs, but by also adding [Ctrl]. **sigh** Damn it sounds farfetched, but the idea is that we could put add two buttons for one input.

**Comment by Jj0YzL5nvJ** [comment]
You want two inputs to the same input, each one with different deadzone? Such feature may be useful for people with disabilities.
 But for people without disabilities, an approach similar to what [mupen64plus-input-sdl](https://github.com/mupen64plus/mupen64plus-core/issues/576) do is more convenient.

**Comment by MarkBlackWhite** [comment]
Well, it's a pointless idea, so i don't really care about it. But i still care about my idea for the Analog Stick. I think it would be cool, but i dunno.

**Comment by theboy181** [comment]
Some games use the double tap feature on the smoking stick so this would not be useful in those games.  The alt key feature do something that you want ?

**Comment by MarkBlackWhite** [comment]
If were still talking about the Analog, alternate keys for different ranges is what i'll go with. Nothing more.

**Comment by cxd4** [comment]
I have this implemented in my keyboard plugin already.

It is not affiliated with Project64.  The idea to use the Ctrl and Alt keys for 25% and 33% was a keyboard preference I saw in Hacktarux's input plugin that just made sense, so I adopted that.

**Comment by theboy181** [comment]
Not affiliated, or compatable Ryan?

**Comment by cxd4** [comment]
ExtremeDude2 says he is Ryan Collins.  Are you misreading my username or talking to him?

**Comment by MarkBlackWhite** [comment]
cxd4 Isn't Hacktarux's plugin for Mupen64?

**Comment by MarkBlackWhite** [comment]
Ah, i see.

**Comment by cxd4** [comment]
You can't reserve the Alt key though on Microsoft Windows because the emulator window on that operating system listens to the Alt key for menu bar and window switching interactions.

So I used Ctrl and Shift instead.  Shift has a range of 128/128 (100%), Ctrl has a range of 64/128, Ctrl+Alt has a range of 32/128, and the default range is 80/128 because that's the physical limit that a real N64 controller will let you push the analog stick out to.  So even though the binary maximum is 128, the stick on the real system only goes out to as far as 80.  So it's unwise to think of N64 control stick ranges in terms of percentages.

**Comment by MarkBlackWhite** [comment]
Oh, ok.

**Comment by cxd4** [comment]
You can press the R key for rapid automatic control stick rotation, too.  Useful for those games that make you rotate the control stick as fast as you possibly can, when I can just hold down the R key with my plugin instead.  Did not see that feature implemented in any other plugins; that was an applied trigonometry exercise I felt like endeavoring on my own.
