### ISSUE TITLE
Free cat nets!

### ISSUE THREAD

**Issue by cxd4** [project64/project64#1488]
https://cat.net/

OMG!!  Perfect fishing nets for trapping those stray cats that like to run amok and wreak havoc.  (Also apparently folds up into a computer server to host websites.)

**Comment by theboy181** [comment]
Please close. This is is not an issue.

**Comment by cxd4** [comment]
Heh.  Already an interested customer within just two minutes of posting.

**Comment by theboy181** [comment]
thanks.

**Comment by cxd4** [comment]
Don't thank me; I have no idea who gets money for those.
