### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by gerson1984** [project64/project64#1489]
https://github.com/project64/project64/blob/f20dca31fdc43e71fd50c4c0888352e4c78a36c2/Lang/Spanish.pj.Lang#L464

**Comment by oddMLan** [comment]
????? 
What ROM are you trying to play? You have not provided any information whatsoever, except for the error message.

By the way, this is not a help forum, this is a bug tracker, used to report bugs or suggest new features.

But if I were to guess, you are trying to play a Super Mario 64 rom hack, right? Make sure under "Options" Hide Advanced Config is unchecked. Then in rom list, right click the game you are trying to play, click "ROM properties" and you'll get another window, change RDRam Size to "8 MB" and save. 

You won't need to do this for Project 64 2.4 anymore (still in development) but if you use an older version, you'll have to do this.

If following this has fixed your issue, please close this ticket.

**Comment by oddMLan** [comment]
Can we close this issue?

**Comment by project64** [comment]
English only please, closing now
