### ISSUE TITLE
Switch Pro Controller Bug

### ISSUE THREAD

**Issue by OblivionWarp** [project64/project64#1493]
I have a problem when I try to use a Switch Pro Controller on Project64 1.6. When I try to move the analogue stick up or right, say to run, my controller doesn't register it as a full stick turn, and my character just walks, meanwhile left and down work fine. The deadzone is set at 25% and the range of the analogue stick is at 51%. (It was the same result even with 100%, the default.) This might be an issue with how I set it up, but nothing else is unusual. Thanks in advance to anyone who can help.

**Comment by Fanatic-64** [comment]
Project64 1.6 is ancient. Try with Project64 2.3.2 and see if the issue still exists (very unlikely since the input plugin is entirely different).

**Comment by OblivionWarp** [comment]
I did end up using the latest version and turned off "Real N64 Range" and it worked! It now works perfectly. Thanks!
