### ISSUE TITLE
Unable to read or load saves in Google Drive

### ISSUE THREAD

**Issue by raccoonmario3** [project64/project64#1496]
I am attempting to store my Project 64 Saves in my Google Drive so that I can access the same native saves from different computers. However, when I try to do this, I get this error when loading, "Failed to open EEPROM." If I set the save directory to anything else, it works fine. It seems to happen mostly with Super Mario 64 and its hacks, but a few other game have the issue as well. Some games work fine, though. Project 64 also generates a log file, which contains this:

```
2018/11/23 02:22:10.788 22568,Error,N64 System,CEeprom::LoadEeprom,Failed to open (C:\Users\[MYUSERNAME]\Google Drive\Project 64 Saves\SM64 Star Road-00F5BCDD597DBC575B8811D5430BB353\SM64 Star Road.eep), ReadOnly = 0, LastError = 5
2018/11/23 02:22:10.788 22568,Error,User Interface,CNotificationImp::DisplayError,Failed to open EEPROM
```

What does "LastError = 5" mean? It is also worth noting that I was able to successfully put the saves folder in the Google Drive on different computer, but the one I'm using now gives me this error. This happens whether or not I enable "Unique Game Save Directory" in Project 64. With this enabled, Project 64 does create a unique directory in the Google Drive, but with no files in it. I am using version 2.3.2.202 of Project 64, and the latest update of Windows 10 64-Bit.

(Note: I originally posted this on the Project 64 Forums, under the username, "Drybones99."

**Comment by project64** [comment]
LastError = 5 is likely to be access denied, that it does not have permission.

try running as admin might be permission issues.

**Comment by raccoonmario3** [comment]
I’ve already been running Project 64 as an Administrator. It doesn’t seem to have solved the issue.

**Comment by weinerschnitzel** [comment]
Access violation perhaps? Although I would expect that issue more when saving, not loading
