### ISSUE TITLE
PJ64 Exception on Startup attempt ends with as an exit of PJ64.

### ISSUE THREAD

**Issue by MelchiorGaspar** [project64/project64#1498]
Line 89, main.cpp is the exception info provided by PJ64.. 
this issue was not present in  (v2.4.0.697) or v706 only build 710 and so far build 712..

ask for any more info you need...
I'm running Windows 7 ULTIMATE SP1 x64
32GB of RAM
EVGA GTX 1070 Ti 8GB

**Comment by project64** [comment]
the line 89 is a catch all exception for the whole program, so it does not really help unfortunately. 

if you extract v2.4.0-712-g529b162 to a new empty directory do you see these issues with no change to the program?

**Comment by MelchiorGaspar** [comment]
yup its still occurring.. :(

**Comment by project64** [comment]
so this is as soon as you start or after running a game

**Comment by MelchiorGaspar** [comment]
one first run it creates the other directories... the exception pops up and I hit ok and it exits..
this was not happening in build706...
It does even load the main UI to run a game... it happens as soon as I run the exe.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/6c2c0d5dd64161a2394138651f0452009ad164be may fix it

**Comment by MelchiorGaspar** [comment]
it seems to have fixed it... :D thx @project64 
tested on LoZ OOT and it loads to in game...
so its fixed for now... lol ;-)
