### ISSUE TITLE
RSP Recompiler Break Point found LH opcode

### ISSUE THREAD

**Issue by exhalatio** [project64/project64#15]
Hello
use the LLE Video in F-ZERO X, an error occurs before the race start.
![f-zerox](https://cloud.githubusercontent.com/assets/7089513/5872932/127e747e-a334-11e4-9bc4-c929091d9b42.png)

**Comment by cxd4** [comment]
https://github.com/project64/project64/commit/a43207f52b2fc23f3300abe6d312e127f1d005e5
That looks like it may have addressed your issue with F-Zero X.

I do not have that game, so I can't test.  If you pull the latest code and build it and find the issue is solved you can close.

**Comment by exhalatio** [comment]
Thank you for your update, the issue is solved.
