### ISSUE TITLE
LLE graphics option broken from game settings

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1501]
No games run with LLE graphics, unless you change the new Default option.  If Default HLE=Yes, and game plugin setting is HLE=No, it's broke.  LLE graphics only works if Default HLE=No.

Broken from v2.4.0-710-gd531abc.  Ability to set default settings.

**Comment by Frank-74** [comment]
I couldn't find an easy fix for this.  Wondering if having HLE Gfx option is really needed as a configurable default.  Changes to the default are made in the rdb per game.  Or with custom game plugin setting.  As it was before it was made a configureable default setting.

I've commented out the line `cpp AddHandler(Default_UseHleGfx, new CSettingTypeApplication("Defaults", "HLE GFX", true));`.  Now rdb and game HLE GFX setting is applied, overriding the default.

**Comment by LegendOfDragoon** [comment]
Was there something wrong with the previous method? Seems like this breaks per-game settings now. I think maybe using Tri-state checkboxes would help. That way, the default setting for "Graphics HLE" would not override the per-game settings.

**Comment by Frank-74** [comment]
Fixed with https://github.com/project64/project64/commit/590119f4147a7670f83a3f7b520b0b3049dde0e0 and https://github.com/project64/project64/commit/e163ecd2f8a2667f291774ea26c162ef0ad9374d
