### ISSUE TITLE
As of last two updates golden eye no longer boots.

### ISSUE THREAD

**Issue by Crimsom13** [project64/project64#1503]
-As of the last two updates goldeneye seems to be broken.

Loads in to black screen no audio nothing, same thing happened with perfect dark but that was fixable by switch to physical lookup table golden eye how ever does not have the same fix.

Tried everything to get it to work must have been something broken in the new update.

**Comment by CrashOveride95** [comment]
🤔 what plugins are you using? is this a unmodded rom?

**Comment by Crimsom13** [comment]
Just the latest glide and I believe the rom is unmodded I've tried with two version at least one of them is unmodded... perfect dark is the same issue with out changing the file like I specified.

2.4.0.787-gad19a6fa and the version released a day before it.

I don't think it's possiable my rom just broke randomly as I don't generally mess around in the options files. the fact that PD died aswell with out changing something should prove its not just a rom issue.

**Comment by CrashOveride95** [comment]
"This has been fixed with v2.4.0-716-g5f39f3d, latest is v2.4.0-722-gad19a6f."
You tried updating?

**Comment by project64** [comment]
I am not sure what version your running as the build number is to high. It was broken and should be fixed as it has been mentioned. Download https://www.pj64-emu.com/nightly-builds from https://www.pj64-emu.com/nightly-builds, extract to a new directory and see if that version is broken.

**Comment by Crimsom13** [comment]
ok it's working now... I got the build from an EmuCR link... hopefully I don't have a virus from it... odd how the build numbers were so much higher. you can close this apologies.

**Comment by project64** [comment]
it was broken, so it is good you reported it.

I just do not trust emuCR build there seems to always be something wrong with them, you can just get them straight from the pj64 site now.
