### ISSUE TITLE
CN64System::RunRSP() on exit

### ISSUE THREAD

**Issue by raccoonmario3** [project64/project64#1504]
When exiting Project 64 from a hotkey, I get the error message, 

"CN64System::RunRSP()
Unknown memory action."

Afterwards, my entire Windows system begins to render certain graphical elements very slowly, such as the selection box on the desktop, or menus in applications. Logging out and back in again fixes it, but running and then exiting Project 64 again starts the cycle all over again. If I check the Event Viewer, I find that at the exact time I get the error, there is a warning which says, "Display driver igfx stopped responding and has successfully recovered." I have also received the error upon exiting full screen but while still leaving Project 64 open. What should I do? I am using Project 64 2.3.2.202 with the latest drivers. If it helps, the computer I am getting this error on is a GPD Win 2.

I am using the following plugins:

Video: Glide64 'Napalm' Public Release 1.22
Audio: Azimer's HLE Audio v0.56 WIP 2
Input: N-Rage For PJ64: 2.5.2.202
RSP: RSP Plugin 1.7.3.202

**Comment by oddMLan** [comment]
Try using the latest build from https://www.pj64-emu.com/nightly-builds and use PJ64Video with PJ64Audio and let us know if you still have the same issue.

**Comment by oddMLan** [comment]
I think this is the same issue as #1328
