### ISSUE TITLE
VI_V_SYNC_REG too big

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1505]
Noticed this yesterday when using GLideN64.  Getting lots of "VI_V_SYNC_REG too big" lines in gliden64.log.

The GFX plugin gets the value of VI_V_SYNC_REG from the emulator.  So opening the issue here.

**Comment by cxd4** [comment]
Those errors were copied from angrylion's plugin.  They never happen with any commercial games in general, so it would be wise to specify which ROMs they happen with.

**Comment by cxd4** [comment]
Have you tried the LLE mode of the plugin with a different emulator, like 1964?

VI_V_SYNC_REG really doesn't have much use within any plugins not doing any frame buffer reads or writes.  If you're just running the plugin in HLE mode without any software rendering emulation, do you also get the error in Project64?

**Comment by loganmc10** [comment]
I believe GLideN64 is using it to determine whether the game is PAL or NTSC, I'm not sure if it's used for anything else

**Comment by project64** [comment]
if VI_V_SYNC_REG is wrong then it is a symptom not a problem, all the changes are just when the game it self sets it.

**Comment by gamemasterplc** [comment]
Can you do an execute breakpoint on 0x80000180 and screenshot the VI Registers page of the debugger @Frank-74

**Comment by Frank-74** [comment]
@gamemasterplc I set the breakpoint while game was running (DK64).  On setting bp before opening, all regs were 0 when bp was triggered.
![bp80000180](https://user-images.githubusercontent.com/11056843/49322886-c7c7b700-f50b-11e8-8e59-82c424ecc4e0.jpg)

**Comment by cxd4** [comment]
>VI_V_SYNC_REG 000020D

Then your conjecture doesn't fit.  VI_V_SYNC_REG is not too big, and the problem is not in the emulator.

That's why I asked if running the plugin under the same mode in a different emulator like 1964 maintained the issue or not.  It's probably either just a regression in the plugin's DAC decoding formulae or just them not copying angrylion's code correctly or whatever.

**Comment by Frank-74** [comment]
It writes 15 lines of VI_V_SYNC_REG too big on startup of ROM, then no more.
I'll try getting an earlier bp.

**Comment by Frank-74** [comment]
Ok, then.  I'll close this and re-open the issue at GLideN64.
