### ISSUE TITLE
Latest Build Broke RDRAM location settings

### ISSUE THREAD

**Issue by theboy181** [project64/project64#1506]
Fixed Rdram Address=536870912

Cant seem to map the RAM for the debugger any longer.

**Comment by theboy181** [comment]
This moved to [Settings]

After update cfg file needed to be sorted. Can we add this to the GUI?

**Comment by project64** [comment]
ah yes that makes sense. 

I am not sure about the gui, I am happy to have it as an option but it is very niche, so not sure about it in the UI.

**Comment by theboy181** [comment]
Fixed Rdram Address is not working for me in current builds again, 

Anyone able to confirm?
