### ISSUE TITLE
PJ_Glide64 error on Doraemon 3 - Nobita no Machi SOS! (J)

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#151]
When starting Doraemon 3 - Nobita no Machi SOS! (J), I get this error using Glide64 For PJ64: 2.0.0.3.

![pjglideerror j](https://cloud.githubusercontent.com/assets/11056843/6403269/fa139666-be05-11e4-8de6-3c77d9521d1e.png)

Pressing Cancel it continues normally.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/8e912cb229fb1223dc8db59222f1494f88c3b0b7 fix this?

**Comment by Frank-74** [comment]
I haven't tried your fix yet, but I just fixed it with this.

In void CALL RomOpen (void) of Source/Glide64/Main.cpp, I changed this,
  wxString strRomName = wxString::FromAscii(name);
to this,
  wxString strRomName = wxString::FromUTF8(name);

**Comment by Frank-74** [comment]
https://github.com/project64/project64/commit/8e912cb229fb1223dc8db59222f1494f88c3b0b7 doesn't fix it.

I get this now from the current master branch build.
![pjglideerror j 2](https://cloud.githubusercontent.com/assets/11056843/6406971/5ed30bee-be2f-11e4-8ebd-e6b717248df0.png)

**Comment by project64** [comment]
ok, I will change it to your one latter tonight

**Comment by Frank-74** [comment]
Bug probably due to ROM Name: ÄÞ×´ÓÝ3 ÉËÞÀÉÏÁSOS!

**Comment by project64** [comment]
yes we are taking what ever is in the header, it does not have to be valid, I need to try and get it to not assert if it is not valid here

**Comment by project64** [comment]
is this issue now fixed with https://github.com/project64/project64/pull/181 ?

**Comment by Frank-74** [comment]
Yes, I forgot to close it, can be closed now...
