### ISSUE TITLE
Breakpoints cause exception spam if stack view has been opened

### ISSUE THREAD

**Issue by NarryG** [project64/project64#1515]
If you open the stack view then hit a break point, it will throw notifications of the form
![image](https://user-images.githubusercontent.com/3047793/49688228-d51d0c80-fadc-11e8-8e97-43acc4bd035d.png)
A large number of times (I haven't counted but maybe once for every entry in the stack?)
If you close them all, it does eventually break and you can see the state in the debugger or stack view, but then if you try and continue a crash occurs.  This only appears to happen if the stack window has been opened at least once. The debugger seems to work fine if that hasn't been opened. 
Adding a ping to @shygoo since I know he deals with the debugger.

**Comment by shygoo** [comment]
Is there a particular game and breakpoint address that triggers it? I'm having trouble reproducing this.

**Comment by NarryG** [comment]
DK64. 

Open the game
Open the stack view
Open the debugger
Add a breakpoint early on
Reboot the game
