### ISSUE TITLE
Sync using audio option broken

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1528]
Since this commit: https://github.com/project64/project64/commit/88386600ed6f9bfd0e8d898d05099a7e9a37c7ac , Sync using audio option is greyed out once a game is started.  And sync using audio is always off.

**Comment by project64** [comment]
hopefully https://github.com/project64/project64/commit/eddd90bbeb171efe68d7f6d39ce4f9193b521842 fixes it

**Comment by Frank-74** [comment]
Fixed, thanks.
