### ISSUE TITLE
Clone advanced option

### ISSUE THREAD

**Issue by Tagiru** [project64/project64#1545]
![imagen](https://user-images.githubusercontent.com/10904176/51069194-da93d800-15ef-11e9-9f99-02e48c19d294.png)
Just activate and deactivate "Hide Advanced Settings", normal speed

**Comment by project64** [comment]
hopefully https://github.com/project64/project64/commit/05ae250a01c5bdbaee752cc791160993064a52e7 fixes this

**Comment by oddMLan** [comment]
It does.
