### ISSUE TITLE
Configuration parsing for a filename instead of a hash of the rom

### ISSUE THREAD

**Issue by valandil** [project64/project64#1562]
I was wondering if it was possible to match a configuration section with a filename instead of a hash of the ROM. I'm developing a hack and it's kinda annoying to always change the configuration options.

For instance, I'd like to have a Project64.cfg file with the following section in it: 
```
[C:\msys64\home\Joey\n64dev\uss64\patch\uss64_U.z64]
Good Name=SUPER MARIO 64
RDRamSize=8388608
Counter Factor=1
```
instead of having to change these settings each time I compile the hack. 

Is something similar possible right now? If not, could you point me to the functions that parse this configuration files in the source tree? I could implement the change myself. I could also make it a PR if there is enough interest.

Thanks!

**Comment by Frank-74** [comment]
Latest builds should set 8Mb if ROM is not in RDB.  And you can set CF=1 under Defaults in latest builds.
Try latest nightly build: https://www.pj64-emu.com/nightly-builds

**Comment by oddMLan** [comment]
You could change the default settings for all roms (Options > Settings > Untick "Hide advanced settings" > Defaults". Also the current behavior is that if the ROM is not in the RDB, assume 8MB RDRAM.

**Comment by valandil** [comment]
Ok, cool! This is an issue on the pj64d side, then! I'll try to merge the upstream version of pj64 into pj64d to see if it still compiles. Thanks!

**Comment by theboy181** [comment]
Isn't PJ64's debugger more up to date?

**Comment by Frank-74** [comment]
@valandil shygoo's debugger is included in pj64 as well.

**Comment by theboy181** [comment]
the more you know. ;)

**Comment by Frank-74** [comment]
lol

**Comment by valandil** [comment]
Haha oops. I'll try the nightly build then to see if the debugger and stuff is up to date. There seems to be quite a lot of work done in shygoo's repo that's not in master (GH reports that shygoo's report is behind and ahead by hundreds of commits). 

Thanks for the info!
