### ISSUE TITLE
Window size incorrectly set when running a game with Jabo's video plugin

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1581]
When running a game in windowed mode, using any version of Jabo's video plugin (and possibly other plugins, haven't tested thoroughly), the window size is set slightly larger than the selected windowed resolution, resulting in black borders appearing to the right and below of the game picture. Changing the resolution or the level of FSAA while the game is running fixes it. This issue appeared between versions 2.2.0.3 and 2.3.2 of Project64. And while I realize Jabo's video plugin is mostly deprecated, I still decided to report this because it's a regression within Project64, and it might affect other video plugins.

~~While testing I also found another minor UI regression: when opening version 2.2.0.3 the window will appear in the foreground above any other opened windows, but when opening version 2.3.2 or latter the window will appear behind all other opened windows, requiring you to minimize those windows or use the taskbar to reach the Project64 window.~~

**Comment by LegendOfDragoon** [comment]
@Fanatic-64 I have a problem where i can't access certain options in jabo's video plugin anymore. Do you have that issue as well, on newer builds?

**Comment by Fanatic-64** [comment]
>Confirmed the black window border thing with Jabo's, the second thing I cannot reproduce, window opens in foreground always for me.

I can no longer reproduce the second thing either... might've been a fluke. Forget about that.

>@Fanatic-64 I have a problem where i can't access certain options in jabo's video plugin anymore. Do you have that issue as well, on newer builds?

That issue was caused by #bac6023a5c705cdbf810b053f0860488c3529e9e, Jabo's plugins look for Basic Mode= under the [default] section of Project64.cfg to determine whether to show advanced settings, but since [default] was replaced with [Settings], the plugins can no longer find the Basic Mode= line, and thus default to not showing advanced settings. A workaround for this is to manually add these lines to Project64.cfg, between the [Plugin] and [Settings] sections:
`[default]
Basic Mode=0`

**Comment by oddMLan** [comment]
I'm kinda conflicted. I don't know if accommodations should be made to Jabo's Direct3D since it's been relegated as a last resort if the other plugins don't have good performance. Someone with ASM skills could in theory, edit Jabo's Direct3D DLL to look for [Settings] instead of [default].

**Comment by project64** [comment]
I need to test, it possibly calls the emu to register the settings/find it. I can possibly interpret this and change it with out any hacking to the plugin.

**Comment by Fanatic-64** [comment]
This issue was introduced by this commit: https://github.com/project64/project64/commit/8ea091a78a4322b78902127128a33f67f141b622 Something about hiding the ROM list upon start of execution instead of upon ROM load causes the window size to be set incorrectly when using any version of Jabo's video plugin (and possibly others, haven't tested all plugins). Reverting this commit (by cutting line 240 and pasting it between lines 221 and 222 in MainWindow.cpp in current master) fixes the issue.

**Comment by project64** [comment]
since this is related to jabo's plugin and I can not change that, I will close the issue. If this is an issue that is the core effecting other plugins then I can look at what is wrong and see if I can fix it.
