### ISSUE TITLE
Glide64 "Final" Texture dump issue, Toggle key does nothing.

### ISSUE THREAD

**Issue by AverageArtist** [project64/project64#1597]
Trying to edit textures in DK64, and for whatever reason the textures do not dump. I know it says that "D" is the toggle but pressing it does nothing, no matter what I do. I tried reinstalling the plugin, using it on a different version of Project64 (Currently using 2.3) I even tried mapping the keys to the controller.

I've also tried other video plugins, but they have their own issues (GlideN64 just shows a black screen, and Mudman's Rice build's texture dump works, but the plugin bugs up my controls for some reason)

Any suggestions? Or, answers to what I'm doing wrong.

**Comment by oddMLan** [comment]
Unfortunately Glide64 is discontinued, so if it is a bug I doubt it'll ever get addressed. About the issue you're having, I honestly have no idea. I've never dumped textures with Glide64, for that I use Rice Video. Rice video should work just to dump the textures if you wanna use the texture pack in Glide64, since it supports the Rice format.

What are your computer specs?

**Comment by AverageArtist** [comment]
> Unfortunately Glide64 is discontinued, so if it is a bug I doubt it'll ever get addressed. About the issue you're having, I honestly have no idea. I've never dumped textures with Glide64, for that I use Rice Video. Rice video should work just to dump the textures if you wanna use the texture pack in Glide64, since it supports the Rice format.
> 
> What are your computer specs?

![1](https://user-images.githubusercontent.com/48771072/54743501-8245fd00-4b81-11e9-8e73-485f7471147d.png)
![2](https://user-images.githubusercontent.com/48771072/54743503-87a34780-4b81-11e9-9be5-8ca4c9fead9f.png)
Did I miss anything?

**Comment by AverageArtist** [comment]
Figured it out.
Re-installed the emulator and put everything in the correct folder.

**Comment by oddMLan** [comment]
What exactly was wrong the first time? So that if someone else has the same issue, I can point them to this ticket.

Also if the issue is resolved click "Close and comment"

**Comment by EGAMatsu** [comment]
^
