### ISSUE TITLE
Project64 Locks up and doesnt boot a game because the cheat menu opens on the first frame.

### ISSUE THREAD

**Issue by CrankySupertoon** [project64/project64#1598]
So for example i am using the AQZ Netplay Plugin. The plugin locks the emulator at the first physical frame. If i open the cheat menu during that first frame before the netplay plugin loads a ROM, it will lock up the emulator until further editing the cheats after it leaves this first frame

**Comment by oddMLan** [comment]
The plugin should be updated to account for the situation in which the cheat menu is opened before a netplay session.

**Comment by NailNatail64** [comment]
The dev told me is isn’t his issue it’s PJ65s

**Comment by theboy181** [comment]
is/isn't   which one?

**Comment by NailNatail64** [comment]
isn't

**Comment by theboy181** [comment]
If he followed the spec I’m sure it would work. What does he figure is actually wrong with PJ64. I don’t understand how his plugin is the only one facing this issue.
