### ISSUE TITLE
Automobili Lamborghini needs framerate cap cheat fix

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1604]
The NTSC versions of Automobili Lamborghini (AKA Super Speed Race 64) are capped at 40 DL/s, however at this framerate the game runs too fast, the proper speed is at 30 DL/s (confirmed by the game's timers actually counting one second per second at this framerate). With a Counter Factor of 2 the game runs at the proper framerate of 30 DL/s most of the time, but at some points in the tracks and during time trials it jumps to 40 DL/s. The PAL version bounces between 25 and 33.3 DL/s, with 25 being too slow and 33.3 being slightly too fast, I imagine on the real console it stays pegged at 25 DL/s and they just didn't correct the speed for PAL.

So, short of making the emulator cycle accurate, we need a GameShark code fix to set the framerate cap at 30 DL/s for the (U) and (J) ROMs and at 25 DL/s for the (E) ROM. @retrobenny seems to have experience with framerate codes, maybe he could help us out.

**Comment by retrobenny** [comment]
This appears to work; :wink:

Automobili Lamborghini (U)

Always 30fps
800013F7 0003
No longer does 40fps

Alternate 30fps Code
8000140B 0001
Prevents 40fps from happening.

Automobili Lamborghini (E)

Always 25fps
8000141F 0003
No longer an oddball fps.

Alternate 25fps Code
80001433 0001
Prevents oddball fps from happening.

Super Speed Race 64 (J)

Always 30fps
8000148F 0003
No longer 40fps.

Alternate 30fps Code
800014A3 0001
Prevents 40fps from happening.

**Comment by Fanatic-64** [comment]
Excellent, I've made a pull request with these fixes for the RDB.

By the way, we might need such codes for a few other games. Is there some place where I could later message you more directly @retrobenny ?

**Comment by retrobenny** [comment]
I am mainly on a Discord channel called Discord64 (and a handful of others) so you could reach me in real-time as long as I am actually online there which is usually for a good amount of time in the day on average from 2PM Central Standard Time onward until 10PM-12PM depending on the situation.

The fix for this game ended up being surprisingly easy to find because I got kind of lucky in this case with search results in memory and a quick write breakpoint took me straight to the resulting code/s ranges.

**Comment by oddMLan** [comment]
Shygoo's recently revamped memory search is godsent.

**Comment by Fanatic-64** [comment]
Do you have the link for Discord64? I've never used Discord before, so I don't know how to find it.

**Comment by retrobenny** [comment]
The invite link is also at;

http://n64dev.org

I don't know if its still active,let me know if its not.
I can't find any way to message you on github,so I guess it lacks that option.
