### ISSUE TITLE
Can't disable the frame limiter

### ISSUE THREAD

**Issue by DonelBueno** [project64/project64#1608]
The hotkey for disabling frame limiter is not working since november 2018. I've tried changing the hotkey (the default is F4), disabling vsync, changing video and audio plugins, but nothing works.

I use the builds posted on EmuCR.

Does anyone else have this issue?

**Comment by oddMLan** [comment]
I think it was done deliberately. You need to disable "Hide Advanced Settings" and it'll work.

I think binding this to either to the Tab or the Spacebar key to temporarily uncap the frame limiter would be a good idea  #1479

**Comment by DonelBueno** [comment]
Strange, it worked now and I always have "Hide Advanced Settings" disabled.

Thanks anyway.
