### ISSUE TITLE
Cannot load .n64 and .ndd combo, PJ64 crashes.

### ISSUE THREAD

**Issue by Chillius** [project64/project64#1610]
I don't know why but whenever I try to open F-Zero X with the Expansion Kit ndd the emulator crashes with the log file saying this:

> 2019/04/19 01:09:14.116 36052,Error,User Interface,WinMain,Exception caught (File: "main.cpp" Line: 86)

However, what's odd is that sometimes the emulator works and lets me play the game I was trying, but most of the time it just ends up crashing.

**Comment by oddMLan** [comment]
Should be fixed in latest builds
