### ISSUE TITLE
Latest Project64 builds crash on start when allocating too much text (?)

### ISSUE THREAD

**Issue by ZioMirko** [project64/project64#1611]
The ROM seems to work fine on every other emulator, I tested it even with CEN64 and an EverDrive64. It works fine in older versions of Project64 (1.6)  but it refuses to boot altogether on any version more recent than 1.6. I don't know what the issue is precisely so I'm just gonna give out the ROM file. I hope you can fix this soon. (It's a ROM Hack)

**Comment by oddMLan** [comment]
Try enabling Unaligned DMA in the ROM Options. It overrides the accurate behavior of the hardware, but it is what allows many ROM hacks to work. Also maybe enable 8MB RDRAM or run it in interpreter mode.

It's also not a good idea to post ROMs in the bug tracker, the repo might get DMCA'd.

**Comment by ZioMirko** [comment]
Tried that, it doesn't work. Plus as I already have stated it does work on console. Probably it's PJ64 that has an inaccuracy.

**Comment by CrashOveride95** [comment]
What is the error on boot?

**Comment by CrashOveride95** [comment]
![image](https://user-images.githubusercontent.com/40003130/56438062-a9dad300-62af-11e9-98fa-0a0d0439b68e.png)
I tried it, i got this.

**Comment by CrashOveride95** [comment]
What does the hack actually edit

**Comment by shygoo** [comment]
The checksums in the header are invalid. Running n64crc on it should fix it. Also @ZioMirko, please edit your post and remove the infringing link.

**Comment by ZioMirko** [comment]
The checksum is just OK, I already used rn64crc before. The only emulator that gives me errors is the latest version of Project64, every other emulator works (Mupen64, CEN64, Actual Hardware with Everdrive64...). I removed the rom.

**Comment by shygoo** [comment]
I sent him a better crc-fixing program over Discord and that fixed the problem (**r**n64crc seems to produce invalid checksums for 6103 roms). This can be closed.

**Comment by CrashOveride95** [comment]
what is this better CRC fixer?

**Comment by shygoo** [comment]
The one from here: http://n64dev.org/n64crc.html
http://shygoo.net/storage/n64crc.exe
