### ISSUE TITLE
Mario Kart 64 player 2 autoselect

### ISSUE THREAD

**Issue by SennaGitHub** [project64/project64#1621]
Hello, the second player, in version v2.4.0-961-gf51dabc, is selected only, in old versions, the one that has seen that it does not, is in version v2.4.0-902-geb2b1f0. Nobody has not reported it, and it's a game that I play with my friends. If you could fix it, please. Thank you.

**Comment by pcca-matrix** [comment]
same problem with v2.4.0-973-geace1a7 , player 2 cannot select a character , unable to move selection , locked on mario or luigi.
But if you keep mario or luigi you can play without trouble.

**Comment by theboy181** [comment]
Wut?  Are you saying that P2 character is stuck on selection?

**Comment by pcca-matrix** [comment]
yes, cannot select or back to menu with player 2  control (using xinput for 360 controllers )
All others games are working normally (didy kong racing etc..)

**Comment by theboy181** [comment]
I think this might be input plugin issue. You try older plugins or different ones?

**Comment by SennaGitHub** [comment]
In my case the player 2, selects luigi, and does not let me back down. It even selects it without configuring the second player.

**Comment by shadow5631** [comment]
I have the same issue, even when selecting different input plugins. If 3 or 4 players are selected the same things happens, where the default character is selected for that player and they cannot press any buttons after the character is selected.

**Comment by oddMLan** [comment]
There's a file in the Config folder of your Project64 install named "Project64.enh" if you delete it, that will fix the issue

This is obviously a bug that needs to get fixed, but in the meantime, this works as a workaround.

**Comment by oddMLan** [comment]
does https://github.com/project64/project64/commit/cabef36f918299780411724599e58a04d06e195e fix it? you can download the latest nightly from https://www.pj64-emu.com/nightly-builds

**Comment by pcca-matrix** [comment]
Issue fixed with https://github.com/project64/project64/commit/cabef36f918299780411724599e58a04d06e195e thanks
