### ISSUE TITLE
Can not build from the reppository

### ISSUE THREAD

**Issue by T931D** [project64/project64#1635]
Hello, 
i tried building the project with VS2019 but i always get this error Message:

- Error	MSB8020	The build tools for v142_xp (Platform Toolset = 'v142_xp') cannot be found. To build using the v142_xp build tools, please install v142_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	JniBridge	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	379	

Sadly when i rightclick the solution there is no option for retargeting. In other projects it's availaible but not in Project62.sln

**Comment by Azimer** [comment]
In the PropertySheets folder look for Platform.props and open it in your favorite editor.  Look at line 5 for "PlatformToolset".  If you remove _xp from $(DefaultPlatformToolset)_xp and save the props file it will now compile.  Alternatively, you can rerun the installer for Visual Studio 2019 and install 'Windows XP support for C++' from setup.  You can find more information on this at this link:  https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=vs-2019

**Comment by T931D** [comment]
Thx for your answer.
Sadly i'm still too stupid to get it done.
When building for release at Win32 or x64 i get the erorr message that Versions.h couldn't be opened. No such file or directory.

**Comment by Azimer** [comment]
I had this obnoxious issue too.  Unfortunately, you need to install the command-line version of git in order for that to work.  During the build process it calls this assuming it exists to build the version.h.  

I built a new computer recently and I need to get this installed on there to compile PJ64.  I will document the steps I took and respond if you end up needing further help.

**Comment by T931D** [comment]
Thx for the explaination.
Btw. thx for the nice emulator :) Despite it's getting my machine stuck sometimes and everytime when i try to use the screen connected via the dockingstation.

**Comment by Fanatic-64** [comment]
@Azimer As a workaround you can just search for Version.h.in and rename all such files to Version.h. Only side effect is that all version numbers will have .9999 at the end.

**Comment by belegdol** [comment]
VS 2019 appears not to support windows XP with v142 toolset:
https://docs.microsoft.com/en-us/cpp/porting/features-deprecated-in-visual-studio?view=vs-2019

Regarding the git, it also works by adding the git binary coming with VS 2019 to $PATH.

**Comment by JunielKatarn** [comment]
https://github.com/project64/project64/pull/1642 fixes this. Awaiting @project64 's approval.

**Comment by bonimy** [comment]
Suggest closing since #1642 has merged.
