### ISSUE TITLE
Breakpoint window right side cutoff

### ISSUE THREAD

**Issue by fig02** [project64/project64#1653]
The right side of the breakpoint window gets slightly cut off, which makes reading values in the registers on the right side pretty challenging. Changing the window size does not fix the issue.

This issue was introduced in the commit on April 22nd 2019 (v2.4.0-948-gb629c0e). My best guess is this specific commit here https://github.com/project64/project64/commit/2555485eb9d1eb03263ccbd6213bcc2082061bd3

If there's anything I can do on my end to prevent this from happening please let me know! Its also worth noting that this issue only happens on my laptop and not my desktop. An image is included below.

![example](https://user-images.githubusercontent.com/22045047/65634605-980f0180-dfac-11e9-9d48-8814702870fa.png)

**Comment by oddMLan** [comment]
that's an issue that only happens when using 125% dpi scaling unfortunately
but if i make the window wider to accomodate 125% scaling the window looks too wide in other resolutions (100,150,200)

**Comment by fig02** [comment]
Is there anything I can do to fix it on my end? I didnt even know my laptop was using 125% dpi scaling.

**Comment by oddMLan** [comment]
Yes, you could right click on your desktop> Display Properties > Scaling. Set it to 100% (or increase it to 150%)
Ideally I should find a way to fix this for 125% without having to do this...

**Comment by fig02** [comment]
Perfect, thank you! Scaling settings definitely works as a temp fix, but it does make my screen pretty uncomfortable to use. So I'm glad that a solution was found. I'll keep my eye on the nightly builds page for the fix.
