### ISSUE TITLE
Project64 not responding

### ISSUE THREAD

**Issue by STBigRed01** [project64/project64#1664]
Emulator worked for a good 4 hours yesterday before i stopped playing and today it wont work at all i have tried uninstalling and reinstalling even to other drives and still no luck, i don't get an error or anything like that its just stops responding almost as soon i as i try and launch the rom i have tried with other roms as well to no avail got any ideas?
![eKVPBgE](https://user-images.githubusercontent.com/31864732/67260837-9f221600-f46b-11e9-9bf9-de55fa740eff.png)

**Comment by oddMLan** [comment]
use the latest nightly build from https://www.pj64-emu.com/nightly-builds
extract the zip to a clean directory and run project64 from there
hopefully it doesnt lock up

**Comment by STBigRed01** [comment]
Alright i got going it took a couple of mins it said not responding then recovered and the game loaded i will report back if i have any further issues thank you

**Comment by molecula451** [comment]
It is not usual Project64 shows this Not Responding. Other elements on the OS might causing this conflict, not the Project64 client at all...

**Comment by Grillsen** [comment]
I am running into the same issue

**Comment by dftf-stu** [comment]
@STBigRed01 and @Grillsen: is this still an issue for either of you?

If so, download the ZIP of the latest stable release (3.0.1) from [here](https://www.pj64-emu.com/public-releases), and the ZIP of the latest unstable release (4.0.0.5871, at the time of writing) from [here](https://www.pj64-emu.com/nightly-builds).

Do your freezing issues still occur in those latest versions?
