### ISSUE TITLE
"Rom Info" crashes Project64

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#1667]
Steps to reproduce
1. Open any ROM
2. File > ROM Info...

Crashes 100% of the time.
It doesnt crash if you do right click  > Rom Info  in the ROM browser.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/e71598edaf44461895348e8e49a82d170082b390 should fix it

**Comment by oddMLan** [comment]
Fixed!
