### ISSUE TITLE
Unknown memory action in Ocarina of time (Project 64 x64)

### ISSUE THREAD

**Issue by LuismaSP89** [project64/project64#1669]
Ocarina of time can't be played, the emulator shows the next message:

"unknown memory action, emulation has stopped"

Tested with different roms of ocarina of time. This problem only exists in the x64 build of project 64 (Tested with some of the latests builds)

Specs:

Windows 10 x64
GTX 970
16 GB DDR3
Project 64 (64 bits build)

**Comment by IronYoshi64** [comment]
What version of Project64 are you using? And what game settings are you using for the rom?

**Comment by LuismaSP89** [comment]
@IronYoshi64 Tested with default and custom settings, with different ocarina of time roms, X64 build of project 64. I searched and I think this is a regression/ancient bug for project 64 running OOT, but this time only x64 build is affected.

**Comment by IronYoshi64** [comment]
@LuismaSP89 Ok. Did you get your build of Project64 from EmuCR? I saw some people saying these builds are not official and causes issues. I think it is best to only get newer Dev builds from here: https://www.pj64-emu.com/nightly-builds, they are only 32bit as well and I think these are the true official Dev builds.

**Comment by LuismaSP89** [comment]
@IronYoshi64 Yes, it´s from EmuCR, at this moment all builds are working ok. I never experienced issues  with the builds of that website.

I think the x64 builds are official from Project64, event if they provide only the x32 builds in their page. I think @project64  "Zilmar" is one of the creators of this emulator and the dev wo created the x64 builds time ago.

**Comment by oddMLan** [comment]
get official x64 builds from here
https://ci.appveyor.com/project/project64/project64

**Comment by LuismaSP89** [comment]
@oddMLan Same issue on the official builds you provided. Can't run OOT, other games runs well.

**Comment by IronYoshi64** [comment]
I completely forgot about that link. lol. I will download and try out some things later with Zelda Ocarina of Time on the latest X64 build from there, when I get back home.

**Comment by IronYoshi64** [comment]
Yeah, there is definitely something wrong with the X64 builds. I also noticed ''Always use Interpreter core'' is on by default? Why? I tried to turn that off, still nothing. Tried messing around with game settings, nothing. Tried changing to GLideN64 x64, still nothing. I barely was able to get anything to run actually. I have a theory that the plugins may not be getting initialized correctly or something? IDK?

**Comment by oddMLan** [comment]
> I also noticed ''Always use Interpreter core'' is on by default? Why?

Because there's no x64 recompiler yet

**Comment by LuismaSP89** [comment]
@IronYoshi64 Works fine with other games, at least in my case. (Using gliden64) the only problem for me is OOT.

**Comment by molecula451** [comment]
Have you been testing with any others ROM like so?. I play Ocarina of Time and had never any issues before

**Comment by LuismaSP89** [comment]
Yes, like I said, I tested with many roms and the oot is the only problem. Also tested with different copys of oot "usa and eu" note that this problem only happens in the x64 build of project 64.

**Comment by molecula451** [comment]
> Yes, like I said, I tested with many roms and the oot is the only problem. Also tested with different copys of oot "usa and eu" note that this problem only happens in the x64 build of project 64.

At least post screenshot on the happening issue

**Comment by LuismaSP89** [comment]
I don't see the point of posting a screenshot of an error textbox since I transcribed the content. But ok, I can record a video showing the problem.

**Comment by Mhowser** [comment]
Any progress on this? I tried running OoT and got the same error.

**Comment by Zerowalker** [comment]
Same issue here, has it really stayed on this long?

**Comment by project64** [comment]
why are you using x64, things are not designed for x64 build, a lot more work needs to be done for it to even be close to the 32bit version.

What self mod have you got set for zelda?

you can get the latest version from:
https://www.pj64-emu.com/nightly-builds

**Comment by LuismaSP89** [comment]
@project64 x64 builds has some advantages, for example can use more than 4Gb of ram (used for some graphic packs with a lot of files). x32 builds needs to be patched with the 4gbpatch program in order to do this.

Also, there are a x64 gliden64 build which performs better than the x32 build.

**Comment by project64** [comment]
I agree x64 has some advantages, mostly being able to load more textures. 

x32 builds already have the 4gb patch. 

so you trading a little speed benefit in the gfx plugin for a major speed lose in the core? 

but back to the main question about zelda,  what do you have as the self mod style for it?

if you take the latest zip from the nightly builds (https://www.pj64-emu.com/nightly-builds) unzip it to a new directory, do you have these problems?

**Comment by LuismaSP89** [comment]
I use the x32 builds since the x64 builds are a bit buggy and have speed issues with the core like you said. This issue is opened only to let the developers know that this game is not working. Is intended for the future development and improving of the x64 build.

Sorry, but I don't know what do you mean with "what do you have as the self mod style for it" can you please explain it? English is not my mother language and it's a bit confusing.

In the other side, I can't test the game with the latest build right now, but I think @Zerowalker did it and keeps failing.

**Comment by project64** [comment]
the game needs protected memory as the self mod style, otherwise you can get this error when it is running old code from what it should be. 

The defaults do not work, which is why it is changed in the rdb. So if the emu is not set up correct it can fail. This is why I ask.

actually it does not matter cause it x64 and the recompiler will not work anyway.

I am going to close this issue, when it comes to x64 everything is broken. When things are done on x64 and if it is an issue then, we can re look at it
