### ISSUE TITLE
Pilot Wings (U): Black square

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#167]
A big black square appears beneath the glider after a few seconds.
![pilotwings 64 u snap0000](https://cloud.githubusercontent.com/assets/11056843/6426752/d1218e9a-bf61-11e4-94c7-4a064789492c.jpg)
Doesn't happen in 2.1.

**Comment by cxd4** [comment]
You get the same result with 2.1 if you check "Disable Game Fixes" in the debugger?

**Comment by Frank-74** [comment]
Yes, forgot about Game Fixes being disabled.  I'll go hide under a rock now.......

**Comment by cxd4** [comment]
It's fine lol.  I forgot about it too when I was helping with Glide64 under RetroArch mupen64plus-libretro.  I had only just learned about the game fix cheat hacks, and every single plugin got it wrong except for angrylion.

This I think is more complicated than a frame buffer effect though...so...maybe @project64 might enable this particular game fix for both Jabo and Glide64?  Or maybe it should just be left as an error with Glide64 and the issue closed.

**Comment by Frank-74** [comment]
Looking at this more closely, I notice the game fix is in the RDB already.  Its set to enable for Jabo and Glide plugins only.  This commit https://github.com/project64/project64/commit/491377c2a4a68321023cbdf0a262f056afb7178c added the RDB option of selecting which plugins use cheats.  So I think it should be working but its not.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/2a528562bf2289decee3bfd718bbb0172309732d fix this issue ?

**Comment by Frank-74** [comment]
@project64 Yes, its working now.

The only trouble is when the cheatfix is enabled for Pilot Wings, then it needs Linking=Off and Use TLB=No.  Not sure if that could be handled automatically, an issues note would do I suppose.

**Comment by cxd4** [comment]
Need Linking=Off means the recompiler is incomplete in this case, though it's interesting that a cheat code would create another instance of this.  Normally the fixes are a) don't use cheat codes cause corruption or b) use the interpreter instead.  But I think the real issue here is that ABL needs to be fixed for yet another game here again, only this time because of a cheat code.  Sounds more like a separate issue though.

The TLB thing is more interesting.  Maybe fixing that could help something with Rat Attack.

**Comment by LegendOfDragoon** [comment]
Is it feasible to port code from GLideN64 to fix the shadows?

**Comment by Passingby1** [comment]
This is still happening in Retroarch 1.8.6 using the newest and bestest ParaLLEl-RDP Vulkan update.
