### ISSUE TITLE
how does the .htc archive work?

### ISSUE THREAD

**Issue by treymerkley** [project64/project64#1671]
I'm trying to figure out how to convert a folder of PNG files to HTC independently of PJ64 (Linux, folder size exceeds the 4GB limit). How does the format work? Where in the code is a folder converted, and how could I spin it out into its own program?

**Comment by oddMLan** [comment]
@project64 didn't implement HTC, @gonetz did for Glide64HQ. I think this is the wrong place to ask. Open a ticket in GLideN64's repository instead

**Comment by treymerkley** [comment]
Done, thanks.
