### ISSUE TITLE
The Turkish language option does not appear in the language menu.

### ISSUE THREAD

**Issue by gurkangullu** [project64/project64#1672]
I added the Turkish language file a few days ago. However, in the latest development builds, the Turkish language option does not appear in the language menu.

**Comment by Jj0YzL5nvJ** [comment]
Will it be perhaps by wrong codification?

`Windows CR LF` + `UTF-8 BOM` **vs** `Unix LF` + `UTF-8`
Try with this: https://0x0.st/zIOT.Lang

**Comment by gurkangullu** [comment]
Thanks. I changed the character encoding to **UTF-8 BOM** and it worked.
