### ISSUE TITLE
 PJ64 v2.4.0-1086: Games that use FlashRam Save Files no longer Load/Save Correctly!

### ISSUE THREAD

**Issue by IronYoshi64** [project64/project64#1687]
I test newer builds of 32bit PJ64 very soon when they get released on AppVeyor and/or PJ64 Dev downloads page.

On build v2.4.0-1086 (also tried 2.4.0-1087), I notice a very big problem with FlashRam saves. Games like Zelda Majora's Mask and Paper Mario that default to FlashRam Saves (.fla), are no longer compatible with older saves from previous builds OR even keep their saved data from the newer builds! Right when you save those games and either reset or exit the emulator, your save file is still there, but It will completely be wiped of any saved data!

Games that use EEPROM and SRAM seem to be not be affected.

**Comment by shygoo** [comment]
This issue does not exist on the master branch. The AppVeyor page includes open pull requests (i.e. work that hasn't been vetted), so you're bound to run into issues if you use builds from there.

**Comment by IronYoshi64** [comment]
> 
> 
> This issue does not exist on the master branch. The AppVeyor page includes open pull requests (i.e. work that hasn't been vetted), so you're bound to run into issues if you use builds from there.

Oh... Ok. I thought that builds from AppVeyor were literally code changes pushed directly to master. Ok, well that makes me feel a little bit better. Yeah that would be very bad if this issue was actually pushed to master. This would be a very bad regression. I do not really do any serious game playing on these builds anyways. I just get these to test stuff like certain settings in the Emu and Plugins configuration.

**Comment by IronYoshi64** [comment]
I am closing this because I think it was just a bad bug with unstable builds. Current latest stable/dev builds do not have this issue.
