### ISSUE TITLE
Problem with Protect Memory and CPU Recompiler

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#17]
When enabling both of these, it causes problems in certain games. The odd thing is that it may be unnoticeable on certain RSPs, but if you debug it, you can see that there's a problem.

The best way to reproduce the issue, is to enable RSP_SAFE_DMA, run the emulator in a debugger (MSVC), and set a breakpoint at the beginning of the loop in SP_DMA_WRITE. Use LLE graphics, and run Jet Force Gemini. The reason I suggest enabling RSP_SAFE_DMA is simply because it's more of a hassle to debug memcpy, rather than a generic for loop.

Basically, while stepping through instructions in MSVC, an error will happen after writing to the destination.

If you would rather not / can't debug with MSVC, then you can just do something like
        __try {
            SP_DMA_WRITE();
        }__except (EXCEPTION_EXECUTE_HANDLER) {
            DisplayError("Problem with SP_DMA_WRITE");
        }
inside of RSP_Cop0_MT and it will always expose the problem.

Also, Super Smash Bros does not work with Angrylion's or Shunyuan's plugin, with protect memory and cpu recompiler enabled. Fortunately, I don't think that game needs Protect Memory, but Protect Memory might be the default setting for Super Smash Bros. I can't remember ;/ .

**Comment by cxd4** [comment]
>Also, Super Smash Bros does not work with Angrylion's or Shunyuan's plugin, with protect memory and cpu recompiler enabled.

Wouldn't it fail with LLE graphics plugins in general and not just angrylion's then?

**Comment by cxd4** [comment]
Try testing with 8 MB expansion pak emulated.
That exception might be triggered off of an access violation when doing DMA, which could go up to a 16 MB address.

**Comment by LegendOfDragoon** [comment]
For Super Smash Bros, z64gl and Jabo 1.7 both work. When I try running Angrylion's for Super Smash Bros, I get an error message saying "Breakpoint found at N64 System\Mips\Memory Virtual Mem.cpp 1692".

Just tried 8mb and that didn't fix the problem either.

**Comment by LegendOfDragoon** [comment]
This is also a problem in Zelda OOT.

**Comment by cxd4** [comment]
^ That would be unfortunate since Zelda OOT actually requires memory protect.
There are self-mod method combos that make it "playable" without protect memory, but it may and very well can crash at some point or another.

**Comment by purplemarshmallow** [comment]
I investigated the crash during the intro cutscene in Jet Force Gemini with GLideN64 and the recompiler. It only crashes with the PJ64 recompiler, the interpreter works. With other emulators there's no crash. If I disable protect memory and use savestates I can get past the point where the emulator crashes.

If protect memory is enabled PJ64 gives GLideN64 the command to fill RDRAM but with completely wrong values. GLideN64 does this and the emulator crashes

**Comment by LegendOfDragoon** [comment]
When I debugged that game with GlideN64, I noticed that for some reason, GlideN64 has a problem with exception handling. The plugin doesn't work on my computer, so I have to debug it on a remote machine :disappointed: . If you can help me with getting it to compile for zilmar spec, I'd be willing to debug it again.

**Comment by purplemarshmallow** [comment]
There's a guide here: https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)
If you don't want to build qt you can download GLideNUI.lib here: https://drive.google.com/file/d/0B0YqMPjGo3B2Y1lfVi1yOENBV3M/view?usp=sharing
You can put it in src/GLideNUI/release. I've built the release build with debug information and used it for debugging because I didn't want to deal with Qt

>The plugin doesn't work on my computer, so I have to debug it on a remote machine :disappointed: 

I think it should be possible to make the plugin compatible with older hardware. It's based on glN64 and this plugin used to work on every gpu. On older GPUs some new features might need to be disabled. But the combiner can be problematic because it has been rewritten using GLSL 3.30.

**Comment by LegendOfDragoon** [comment]
>But the combiner can be problematic because it has been rewritten using GLSL 3.30.

That probably explains the strange colors I'm seeing. Anyway, I'll see about testing JFG with GLideN64 when I can.

**Comment by project64** [comment]
if a game has code in a block (4kb) the memory is protected against writes. If there is a write then you will get a crash yes, but the exception handler of pj64 should handle this, clear the recompiled code at this address and write to the memory. 

So the exception handler in what ever plugin needs to let the crash happen, so pj64 can handle it.

**Comment by LegendOfDragoon** [comment]
>If there is a write then you will get a crash yes, but the exception handler of pj64 should handle this, clear the recompiled code at this address and write to the memory.

The issue is that you exception handler doesn't handle certain x86 instructions. Although I don't know what GLideN64 is doing, so it is possible that it's doing something wrong for JFG. I just remember that when using Angrylion's RDP in Super Smash Bros with Protect Memory, it used to crash. I haven't enabled Protect Memory for that game in a long time, so I don't know if it's still an issue, but I'm fairly certain it never got fixed.

Maybe if I get around to testing, I'll let you know what the instruction was.

**Comment by project64** [comment]
if it is an unhanded x86 that should be easy enough to add in

**Comment by LegendOfDragoon** [comment]
Easy, but time consuming :smile: . Anyway, I just tried using SHunyuan's and it crashed with this instruction
`mov         word ptr [eax+ecx*2],si `

There's a lot more instructions to support though. Maybe I can review some of the stuff I wrote down a while back, if you're interested in adding more instructions.

**Comment by LegendOfDragoon** [comment]
I can't seem to get Zelda OOT to work anymore, on Protect Memory. Anyone else able to get it working? I was going to try fixing the debugger crash, but I can't even boot this game lol.

**Comment by LegendOfDragoon** [comment]
I would like to look into figuring out a good way to do self modifying code detection. Does anyone know where crashes happen in Zelda OOT when not using Protect Memory?

**Comment by LegendOfDragoon** [comment]
Thanks :smiley: . I'll try testing that out.

**Comment by gonetz** [comment]
@project64 please take a look: https://github.com/gonetz/GLideN64/issues/764
