### ISSUE TITLE
Strange ERET?

### ISSUE THREAD

**Issue by bryanperris** [project64/project64#1710]
@project64 
When running the mupen64 test rom, and maybe anything else that is compiled with the ultra64 SDK, I run into an ERET instruction that isn't used inside a handler.  This instruction is used to return from an exception handler and then resume normal operation.  However this is not the case.

This is the instruction: 800F7198 eret

~~The ERET instruction loads ERROR_EPC (0xFFFFFFFF) into PC which is an invalid address, but just before that instruction moves on, the MIPS interpreter jumps to the exception handler located at 0x80000180.  After servicing the exception, the PC is now loaded with the normal EPC value that isn't an invalid address, in fact the same instruction is called again inside of the handler.~~

EDIT: ERET loads in valid EPC value, I had the EXL and ERL fields mixed up.

Here is what I found in PJ64's interpreter for the ERET function 

```
void R4300iOp::COP0_CO_ERET()
{
    m_NextInstruction = JUMP;
    if ((g_Reg->STATUS_REGISTER & STATUS_ERL) != 0)
    {
        m_JumpToLocation = g_Reg->ERROREPC_REGISTER;
        g_Reg->STATUS_REGISTER &= ~STATUS_ERL;
    }
    else
    {
        m_JumpToLocation = g_Reg->EPC_REGISTER;
        g_Reg->STATUS_REGISTER &= ~STATUS_EXL;
    }
    (*_LLBit) = 0;
    g_Reg->CheckInterrupts();
    m_TestTimer = true;
}
```

This explicitly checks for interrupts, which could explain this behavior is known but that doesn't explain everything either. I am not finding anything that could be triggering this handler to fire except maybe for the MIPS timer event, but that is some seriously lucky timing and I highly doubt it.  

The RCP interrupt mask is 0 so its nothing from that side.  I know that the Cop0 Status register is 0xFF03 then becomes 0xFF01 after the service handler.

This issue is not about an actual issue with PJ64 itself but more about my own project but certainly looks like an ugly hack for the interpreter.

EDIT: Checked compare and count in PJ64, they aren't possibly going to throw any timer event.

EDIT: I checked upon the Cause register, PJ64 displays the label "Watch" ~~meaning the watch exception has been thrown... but this is a debugger feature for MIPS....~~ EDIT: This is just the default exception code upon boot

**Comment by project64** [comment]
I have no idea what you are saying is wrong or needs to be fixed.

Do you have a test rom that acts one way on a real n64 and acts different on pj64?

**Comment by bryanperris** [comment]
Sorry for the confusion.  

This isn't an about something being broken or wrong with PJ64 but the matter of how is your interpreter suddenly jumping to the handler right after an ERET that is being called in normal operation.

My point is that if the interrupt handler didn't fire, the emulator would crash but its saved by the exception handler in the nick of time and your logic checks the interrupts inside of ERET.

If you put an execute breakpoint at 800F7198, then step, the PC moves right into address 80000180 which is the standard location for the MIPS exception handler.

Also the main reason for this issue, why would ERET be used outside an exception handler in the first place?

In my project, I dumped a simple tracelog that starts from entry point to this ERET, same path of execution are found with PJ64 and mame but the only difference I found in certain branches for PJ64 was due to the emulated DD not returning zeros.  I did hack the DD branches and obtained the same GPR register states at PJ64 to really make sure nothing was off.

To make another note, Cause is always initialized to 0x0000005C thus "Watch" exception code being set and seen in the debugger label next to the Cause textbox.

When I get more time, I might just debug PJ64 itself and see what the actual trigger event is.

Here is the tracelog ending at ERET without DD support:  https://pastebin.com/HBPZ5fVS

Thanks!

**Comment by bryanperris** [comment]
So I had the error and exception level bits reversed, so PC is jumping to valid values from EPC and not the 0xFFFFFFFF one, so the emulator isn't going to crash then.  As for the who generates the interrupt, I don't know.  Also it doesn't explain the use case of ERET being used before some interrupt fired.

I still want to ask you why you decided to check for interrupts inside of ERET?

Thanks!

**Comment by project64** [comment]
while processing an exception handler interrupts have not been able to fire, once the eret executes interrupts can execute again. Check interrupts does not actually generate an interrupt it just checks if an interrupt should occur. So say there is a waiting AI interrupt or the any MI interrupt. Then that will fire on after the eret has occurred. If it should then it marks an event and it will get processed latter.

In pj64 I am just checking interrupt should occur at key points of time, but checking that flag all the time. Mostly cause it is quicker to check the flag then check then do the full test.

**Comment by bryanperris** [comment]
I didn't expect checking for interrupts would throw one but I wonder why the interrupt hasn't happened randomly before the ERET, after stepping the core, it always goes right into servicing interrupt, but perhaps the debugger is causing an observer effect.  Also I don't think the RCP mask was allowing anything yet at the time of the first ERET hit.  I also put a breakpoint for the service handler itself, but the ERET is always hit before the handler.  I don't see how 2 different working emulators both hit the service handler perfectly after that first ERET but nothing before.

Plus why does big N use the instruction in the first place instead of a normal jr?

**Comment by project64** [comment]
if you want to talk about this more feel free to message me in dicord

**Comment by bryanperris** [comment]
@project64 what is your discord tag?

**Comment by project64** [comment]
zilmar

**Comment by bryanperris** [comment]
Need the numerical code at the end too

**Comment by project64** [comment]
zilmar#6921

**Comment by oddMLan** [comment]
@bryanperris You could also join our N64 emulation Discord server if you like, zilmar is in it.
https://discord.gg/MFVhQf
