### ISSUE TITLE
"Failed to open Eeprom" under many games

### ISSUE THREAD

**Issue by naw9457** [project64/project64#1713]
I tried to play SM64 after a long day's work, but when I opened it, it closes/crashes and says "Failed to open Eeprom" and after a few seconds, it says exception caught and points me to a directory with the issue that is not there. Every time I restart my computer, I get to play a good few minutes and then booting up another game or closing SM64, doing something else (searching something, doing laundry, etc.), and coming back to it gives the same crash and two messages. What is this and why is it continually happening?

**Comment by CrashOveride95** [comment]
What build are you running

**Comment by naw9457** [comment]
1.7.0.49 is what it says at the top of the main window.

**Comment by IronYoshi64** [comment]
@naw9457 That build is super outdated and shouldn't really be used for daily playing. Where did you get a old build like that anyways? Try on the latest Dev build from here: https://www.pj64-emu.com/nightly-builds

**Comment by CrashOveride95** [comment]
there have been dumb rumors for years that 1.6/7 is supposedly "superior to newer versions of pj64

**Comment by IronYoshi64** [comment]
> 
> 
> there have been dumb rumors for years that 1.6/7 is supposedly "superior to newer versions of pj64

That is absolutely a fat lie. 1.6 is not bad but I wouldn't say its the ''best'' version. and for 1.7, no that is not good I believe. Wondering, did you hear these rumors from Mario 64 hack YouTubers/Streamers?

**Comment by CrashOveride95** [comment]
@IronYoshi64 I'm not saying it's the truth

**Comment by naw9457** [comment]
I just found it on a website out of the blue; that website you attached is blocked for me (courtesy of my school).

**Comment by naw9457** [comment]
I just want to continue to play without having these constant crashes.

**Comment by IronYoshi64** [comment]
Oh is it? Ok. How about this one: https://ci.appveyor.com/project/project64/project64/build/job/nn2fxdtr7dtxidta/artifacts That is another place to get them. So even with the newer builds, you still getting the crashes?

**Comment by naw9457** [comment]
That site is unblocked.
I'll try a newer build.

**Comment by naw9457** [comment]
Do you just have to extract it?

**Comment by naw9457** [comment]
Got it to work; thanks for the new build version!

**Comment by IronYoshi64** [comment]
Yes. Download it, extract it somewhere you like, then click the Project64.exe file. Setup the emulator how you like, you know, controls, paths, graphics, etc.

**Comment by IronYoshi64** [comment]
Ok cool! You are welcome! Have fun!

**Comment by naw9457** [comment]
My computer recognizes that something got plugged in, but Project64 does not notice it.

**Comment by djbnet** [comment]
> 

I know I'm late to the subject, but that 1.6 "rumor" comes from a majority of speedrunners requiring 1.6 for emulator submissions. 
perhaps it's the adware driving people away? 🤔 
I get that you're a contributor, but it's hard to imagine an entire community of speedrunners being "dumb" or even inefficient. Especially for a game like Super Mario 64.
I updated to a newer version due to this thread and your comment.. Only 3 minutes in and it locked up windows for a good 30 seconds. Even froze task manager.
Never ran into this issue with 1.6 to be honest. This Eeprom error was the first time I've ever had trouble with it.
