### ISSUE TITLE
Super Mario 64 Jumping Issue

### ISSUE THREAD

**Issue by naw9457** [project64/project64#1715]
Using the latest Project64 version (2.4.0), I booted up SM64 and found a small bug. When I long jump, Mario cancels the action and acts as if it is a regular jump. That is a tiny issue, but there is a bigger bug I found. When I jumped (not long jumped) into a star, he didn't do his default spin and peace sign. He just froze the music in place. The only way back out was to exit the level and reenter the star to try again. Mario normally has a fall animation programmed for when he collects a Power Star or dies in a level and gets removed from the painting. This fall animation is never triggered when I use this Project64 version. On the other hand, this never happened when I used Project64 v. 1.7. Someone please help me.

**Comment by CrashOveride95** [comment]
are your sure your SM64 rom isn't hacked in some way

**Comment by molecula451** [comment]
It would be helpful if you screen record reproduction issue

**Comment by naw9457** [comment]
@CrashOveride95  I am absolutely sure my rom is not hacked.
@molecula451 I need good and fast software for that, otherwise recording would take forever.

**Comment by molecula451** [comment]
Why would you need a fast software? What your current's PC specs are?

**Comment by molecula451** [comment]
What your current's PC specs are?

**Comment by naw9457** [comment]
@molecula451 Ok I don't need software for recording because I have OBS Portable from portableapps.com
I don't know what you mean by that question.

**Comment by molecula451** [comment]
I mean In which hardware you are running

**Comment by naw9457** [comment]
All I know is it's a Windows 10 laptop. I don't really know much else.

**Comment by naw9457** [comment]
[Link of Footage](https://drive.google.com/file/d/1BdIFgyjcpx5sI5JbjWsDVdmq8nfgkFUm/view)
If this link doesn't work, then tell me and I'll use my non-school account.

**Comment by molecula451** [comment]
Make that shared fully-public viewable, It needs permission to be view

**Comment by naw9457** [comment]
It is good now

**Comment by naw9457** [comment]
My bug popped back up, now I'm just about to delete my saves, cheats, and ROM.
I'll just download a new one.
