### ISSUE TITLE
Missing games from popular "No-Intro" set

### ISSUE THREAD

**Issue by JakedUp** [project64/project64#1716]
[FC70E272-08FFE7AA-C:45]
Good Name=Space Station Silicon Valley (U) (V1.1)
Internal Name=Silicon Valley
Status=Compatible
Plugin Note=[Glide64] missing TV noise
Culling=1
RDRAM Size=8

[96816CCD-0272EA8C-C:45]
32bit=No
Good Name=International Superstar Soccer 2000 (U) (Eng-Spa) (V1.1)
Internal Name=I.S.S.2000
Plugin Note=Test
RDRAM Size=8
Status=Compatible

[DF09D625-1791C87D-C:45]
Good Name=Madden NFL 99 (U) (V1.1)
Internal Name=MADDEN NFL 99
Status=Compatible
Counter Factor=1

[8F89ABA0-C34C2610-C:70]
Good Name=GameShark Pro (U) (V3.3) (UNL)
Internal Name=(C) MUSHROOM &NU09;5

[12678830-4E5AE439-C:38]
Good Name=GameBooster 64 (U) (V1.1) (UNL)
Internal Name=(C) MUSHROOM &

**Comment by CrashOveride95** [comment]
?

**Comment by IronYoshi64** [comment]
Yeah I believe you are correct. Also from my set, for the latest Dev build of Project64, these games are missing for me as well.

Action Replay Pro 64 (Europe) (v3.3) (Unl)
[A8D1DAF2-31206B53-C:80]
Good Name=(C) MUSHROOM &NU16;0

Batman of the Future - Return of the Joker (Europe) (En,Fr,De)
[259F7F84-7C9EED26-C:50]
Good Name=Batman of the Future - Return of the Joker (E) (M3)

BattleTanx - Global Assault (Europe) (En,Fr,De)
[0CAD17E6-71A5B797-C:50]
Good Name=BattleTanx - Global Assault (E) (M3)

Bomberman Hero (Europe)
[D85C4E29-88E276AF-C:50]
Good Name=Bomberman Hero (E)

GameBooster 64 (Europe) (v1.1) (Unl)
[12678830-4E5AE439-C:38]
Good Name=(C) MUSHROOM &

SpaceStation Silicon Valley (USA) (Rev 1)
[FC70E272-08FFE7AA-C:45]
Good Name=Silicon Valley

**Comment by JakedUp** [comment]
[125C6F53-865BD9CA-C:45]
Good Name=Super Mario Odyssey 64 (U)
Internal Name=SUPER ODYSSEY 64
RDRAM Size=8
Status=Compatible
Culling=1
Direct3D8-DesiredAspect=1

**Comment by project64** [comment]
how about making a pull request to get things merged instead of an issue
