### ISSUE TITLE
problems in translations files with UTF-8 encoding

### ISSUE THREAD

**Issue by MELERIX** [project64/project64#172]
translations files with UTF-8 encoding are not displayed properly.

**Comment by Lithium64** [comment]
I forgot to say to Zilmar, but they need to be encoded as ANSI to function properly.

**Comment by MELERIX** [comment]
I see, thanks.

I'll fix my translation later with ANSI encoding and few other changes.

**Comment by project64** [comment]
which particular language are you testing with and is looking wrong, is it in every string or only in certain parts of the UI ?

**Comment by MELERIX** [comment]
I tested with Spanish and Portuguese, but of course there are more language files affected.

an easy way to test, for example: open PJ64 -> open File Menu -> click in Language

and you will see this: http://i.imgur.com/d2s0Aea.jpg

**Comment by project64** [comment]
OK done two commits (https://github.com/project64/project64/commit/b6359831676ca51a80dc3510f75271553baedea9 and https://github.com/project64/project64/commit/71cc6def7b35f0d533d2b8a108834823834ac288), How is it looking for you now? Is there still issues that need fixing?

**Comment by MELERIX** [comment]
oh, I'll test in few minutes.

btw, can you commit this please ? https://github.com/project64/project64/pull/207 patch is updated now.

**Comment by MELERIX** [comment]
now is working fine ;)

translations in UTF-8 are displayed properly now.

thank you Zilmar.

**Comment by MELERIX** [comment]
well, I reopened this again, because now I've discovere some new issues.

for example in a clean start of Project64, when you select roms folder and it start to scan the roms, the status bar will show some weird characters:

![Text](http://i.imgur.com/qqCWWnL.jpg)

**Comment by project64** [comment]
ok I will have a look tonight, there could be other issues as well .. I am loading the strings as utf8, but all the windows functions for 8 bit treat it as ansi which does not work, so now I convert them all to utf16 once loaded and calling the W functions of windows .. so this is a case where I am most likely passing an 8 byte char array instead of 16 byte char array.

**Comment by Lithium64** [comment]
@project64 
![bug4](https://cloud.githubusercontent.com/assets/10705488/6501103/ecdf26da-c2f2-11e4-939e-bc8d84fa718b.png)

**Comment by MELERIX** [comment]
few more issues detected...

![Text](http://i.imgur.com/ANWoNt4.png)

![Text](http://i.imgur.com/uuybuGc.png)

![Text](http://i.imgur.com/fFHBuTz.png)

![Text](http://i.imgur.com/0YOLkVa.png)

**Comment by project64** [comment]
another commit (https://github.com/project64/project64/commit/0bd4b9deb9425254bee5c5690fd176bbd7bfe931) still more to fix up

**Comment by project64** [comment]
ok more code (https://github.com/project64/project64/commit/bd3fd85b990598ef0b5fe42c8e713e15c8726be8)

while I am sure there is more to do make sure everything is being translated, what is still worse compared to 2.1

**Comment by harlayzhou** [comment]
![1](https://cloud.githubusercontent.com/assets/8403754/6612737/cc2c71b6-c8bc-11e4-8b94-d5ce2eaf6152.jpg)

**Comment by project64** [comment]
@harlayzhou I can not read it, is it wrong ?

**Comment by MELERIX** [comment]
Its practically the same issue that I've posted above (in the last two pictures), is inside short cut options.

**Comment by project64** [comment]
is the items in that list wrong? I am not sure what exactly is wrong

**Comment by MELERIX** [comment]
for example in this picture...

![error](https://cloud.githubusercontent.com/assets/1040116/6614108/6d8d734e-c86c-11e4-8ae6-ab3fde23c843.png)

the text selected should say "Iniciar Emulación" but as you can see the character "ó" is not displayed properly.

I guess the whole tree menu is affected by the bug, but of course we can only notice the bugs in places where utf-8 text is used.

**Comment by harlayzhou** [comment]
@project64 The first levels item is right, but the second level items is wrong.

**Comment by project64** [comment]
ok does https://github.com/project64/project64/commit/b1d3a275390385258087488a5b0699e171d19b96 fix this issue with the keyboard shortcuts second level?

**Comment by MELERIX** [comment]
> ok does  b1d3a27  fix this issue with the keyboard shortcuts second level?

yes, now is ok (at least for me), thank you ;)

**Comment by MELERIX** [comment]
some more...

![more](https://cloud.githubusercontent.com/assets/1040116/6654281/93cea4e0-ca8f-11e4-81b2-91e1c6b406c9.png)

**Comment by project64** [comment]
ok another fix (https://github.com/project64/project64/commit/262c8ffe9de9f20a1ac4e4b1e6d8d0c741a98416) you might need to refresh the rom list for it to work correctly.

**Comment by MELERIX** [comment]
> ok another fix ( 262c8ff ) you might need to refresh the rom list for it to work correctly.

now is ok, thank you ;)

**Comment by project64** [comment]
@melerix is there any issues left in the current language display

**Comment by MELERIX** [comment]
@project64 at least in Spanish now is ok, but not sure about others langs.

**Comment by project64** [comment]
can I close this issue now?

**Comment by MELERIX** [comment]
ok, closed, I didn't noticed more UTF-8 issues.

**Comment by harlayzhou** [comment]
1

**Comment by Watilin** [comment]
Hi!
Apparently this still requires some work. I noticed this when using quick save in full screen with the french translation.
![pj64_encoding_fr](https://cloud.githubusercontent.com/assets/814349/9982526/0b858612-5fe0-11e5-97f4-1a6464baf752.png)
The output should be
> Sauvegarde effectuée

I didn't look into PJ64's source code yet, but I'm used to encoding issues so give me some time and I might be able to take care of the french translation myself :)

**Comment by cxd4** [comment]
Hi @Watilin .

That looks like a feature of Jabo's Direct3D plugin that he implemented for full-screen status notifications.  Technically speaking that isn't a part of the sources to Project64 (in part due to it being closed-source as a plugin), so the cause of your screenshot seems uncontrollable.

Now if you encounter anything like that while using the other plugins (like the PJGlide64 one whose sources are part of the PJ64 repository), then that can have something done about it.

**Comment by Watilin** [comment]
Ok, thanks for bringing that light on me. I'll see if I can find Jabo's sources.

**Comment by cxd4** [comment]
You're welcome to report anything you notice like this issue with the other plugins, too.

I would say the same thing for Jabo's except I believe his sources aren't publicly available.  It might not be able to get controlled, but if there's anything within Project64 core's side of things or in other plugins you notice feel free to say.

**Comment by Watilin** [comment]
With Jabo not around, things will be harder. I'm certainly not skilled enough to do reverse-engineering.
But I'll be glad to help with PJ64 :)
