### ISSUE TITLE
Game crashing popups

### ISSUE THREAD

**Issue by anonymous7002** [project64/project64#1721]
When a game crashes, it pops up an error: 

Application/Core Error
---------------------------
Fatal Error: Stopping emulation
---------------------------
OK   
---------------------------

Is it possible to disable these popup messages?

**Comment by anonymous7002** [comment]
Mupen doesn't have that kind of messages, and the game just keeps going while crashed.

**Comment by project64** [comment]
these happen when there is a crash, what do you want to happen instead

**Comment by project64** [comment]
the aim is probably better to try and fix why it crashes, then changing anything with this message. Why is it crashing on you.

**Comment by anonymous7002** [comment]
remember, **A** game, I don't want the crash to be fixed, because it is INTENTIONAL. Crash screens can be very colorful, and that's why I want an option to disable them.

**Comment by project64** [comment]
No it will not be disabled, they are there to show something needs fixing. I am happy to look at why it is crashing and looking how to fix that, I am not going to add an option to disable them

**Comment by anonymous7002** [comment]
When you enter the file select screen of SM64, then immediately click "Score" button, then click "Erase file" button, and select one of the two options for question "Do you want to erase file?", the game crashes. Also on console. That's because the game is trying to write to null. It's not a bug in the emulator, it's a bug in the game. If you fix it, you only make the emulator less accurate.

**Comment by anonymous7002** [comment]
Some error screens may show information about the crash, and stopping the game whenever detects a crash don't allow people to see the information error screen.

**Comment by anonymous7002** [comment]
Like whether the bug is in the game or in the emulator.

**Comment by flagrama** [comment]
I'd agree that if the game is crashing, PJ64 should keep running. If PJ64's emulator is crashing then an error makes sense. For example, when Ocarina of Time crashes, I should be able to open the crash handler with the following button combination 

    L + R, then while holding both press Z
    D-pad Up
    C-DOWN
    C-UP
    D-pad DOWN
    D-pad LEFT
    C-LEFT
    C-RIGHT
    D-pad RIGHT
    A + B, then while holding both press Start 
http://www.jaytheham.com/zcw/Ocarina_of_Time_-_Debug_Code

If I'm unable to do that I'd actually consider that an inaccuracy in PJ64.

**Comment by anonymous7002** [comment]
It's so inconvenient that I can't open the issue because project64 closed it.

**Comment by CrashOveride95** [comment]
can you please stop dragging these annoying nitpick non-issues
they were closed for a reason

**Comment by anonymous7002** [comment]
Emulator crashes and game crashes are a different thing.
And see, even another agrees with me.

**Comment by anonymous7002** [comment]
PU crash is not a non-issue, but a minor issue, that a very accurate emulator should emulate. The camera is fixed in 1 key tas so the game wouldn't crash when verifying on a console.
project64 doesn't get the thing: emulator crashes and game crashes are a different thing.

**Comment by flagrama** [comment]
I actually tested OoT using a known bug in OoT Rando. It crashed correctly, so I personally have no issue with how PJ64 is handling this.

![image](https://user-images.githubusercontent.com/634079/79138194-1e8d0400-7d82-11ea-95ad-9d1c293f350c.png)

**Comment by project64** [comment]
those popup are when something is not being handled in pj64, the issue that causes them need to be fixed. Not that there is a popup. This is why I closed it. A game crashing is fine and should act as close as possible to a real console. There is lots of cases where pj64 might not be generating an exception or handle an error case properly. In which case a test rom should be generated to demonstrate that and that should be fixed.

this bug is a error occurred and it told me. This gives no information and never fixable, hence why it is closed

you asked: 
Is it possible to disable these popup messages?

Answer:
No, it is not being changed, case closed

**Comment by anonymous7002** [comment]
List of crashes in SM64:
https://ukikipedia.net/wiki/Crash

**Comment by project64** [comment]
now if there is an issue with say Floating-Point Overflow that should be fixed to work like a real n64, but a single test is best for that, unless there is a clear case that makes it easy to test

**Comment by anonymous7002** [comment]
The Shindou version does not pop up the error message.
But it crashes as well, in the same way like in Mupen.
