### ISSUE TITLE
Allow to see the error screen information

### ISSUE THREAD

**Issue by anonymous7002** [project64/project64#1722]
When you enter the file select screen of SM64, then immediately click "Score" button, then click "Erase file" button, and select one of the two options for question "Do you want to erase file?", the game crashes. Also on console. That's because the game is trying to write to null. It's not a bug in the emulator, it's a bug in the game. If you fix it, you only make the emulator less accurate.
Some error screens may show information about the crash, and stopping the game whenever the emulator detects a crash don't allow people to see the information in error screen.
Like whether the bug is in the game or in the emulator.

**Comment by CrashOveride95** [comment]
what is the issue here

**Comment by anonymous7002** [comment]
It's a suggestion.

**Comment by CrashOveride95** [comment]
both of your "issues" just seem like super-low-level nitpicks

**Comment by anonymous7002** [comment]
It would be quite useful for Stryder7x and SM64 TASers.

**Comment by project64** [comment]
the emulator should act like the real console, if there is an exception it should be able to keep going. If you want something like generate a BP on exception, that opens a debugger that could be an option. 

but I have no idea what you asking, if you want to discuss things then do it on discord. This is more meant to track issues or as a place holder for a feature. This is neither.
