### ISSUE TITLE
OpenSSL legacy code breaking settings UI

### ISSUE THREAD

**Issue by boundingbox** [project64/project64#1723]
OpenSSL for some reason is being called in bringing up the settings menu. Running natively on Windows up to Win8, this isn't actually an issue-but when it comes to porting it onto other systems and running on Win10, it becomes an issue as modern systems do not always play nice with outdated code. 
Specifically, this is the instruction being called:
```
Flag: 0x000008000 (Vers. 1.0.2, 1.1.0 value) ; Updated to Flag 0x00000800U (Vers. 1.1.1 value)

SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS - SSL_OP_ALL? Yes - Disables a counter-measure against a SSL 3.0/TLS 1.0 protocol vulnerability affecting CBC ciphers, which cannot be handled by some broken (Microsoft) SSL implementations.
```

Note: It's the Vers. 1.0.2/1.1.0 value being called.

Is there any way to check how and why in the world OpenSSL is being called on to display the settings information? What is it supposed to do here?

**Comment by CrashOveride95** [comment]
Yes,check the source code

**Comment by project64** [comment]
I have no idea about what your talking about. Nothing uses the internet. 

Is this a clean install or you using some 3rd party plugin?

**Comment by dftf-stu** [comment]
@boundingbox: I'm able to run _Project64_ on my _Windows 10 Home_ and _Windows 10 Pro_ laptops without such issues.

Can you confirm which version of _Windows 10_ the affected devices are running, and which versions of _Project64_ are you using?  3.0.1 is the latest stable; 4.0.0.5871 is the latest alpha/beta release.
