### ISSUE TITLE
JavaScript API is broken

### ISSUE THREAD

**Issue by Dragorn421** [project64/project64#1725]
Unless I'm missing something, it just doesn't work.

Version: latest dev build at time of writing `v2.4.0-1132-gcb0472f`

Here's a script, mostly copy-paste from documentation

```js
console.print('3Loading...\r\n');

function onWriteAny(address)
{
	console.print(address + '\n');
}
events.onwrite(0x800137C7, onWriteAny);

events.onwrite(0x80013837, function()
{
    console.log('CPU is modifying 0x80013837')
})

const JR_RA = 0x03E00008 // 'jr ra' command
events.onopcode(ADDR_ANY, JR_RA, function(pc)
{
    console.log(pc.hex()) // log pc at every 'jr ra'
})
console.print('Loaded!\n');
debug.breakhere()
```

I can run it, both Loading and Loaded messages show up.

#### debug.breakhere()
The "Commands" window shows up from calling `debug.breakhere()` but most of the time emulation keeps going.

#### events.onwrite()
I can see in the "Memory" window that those addresses are being written to, yet the script doesn't print anything.

I would love to fix it myself but I have a hard time understanding how the code interacts with stuff, discovering Duktape at the same time isn't helping. Would it be ok to @ someone (who?) on the pj64 discord for help if I go back to trying?

**Comment by m000z0rz** [comment]
I haven't used the debug.breakhere() stuff yet, but my understanding is that needs to be called _inside_ the event handler where you want to break. So, to make it break at the 'jr 'ra', you would need something like
```js
const JR_RA = 0x03E00008;
events.onopcode(ADDR_ANY, JR_RA, function(pc)
{
    console.log(pc.hex());
    debug.breakhere(); // debug.breakhere() goes INSIDE the handler
})
console.print('Loaded!\n');
```

**Comment by jonathan25** [comment]
I was having the same problems with ``events.onwrite``.
Be sure to check where the CPU actually *starts* writing by using a breakpoint. You might be looking for a change in 1 byte or 2 but the CPU is writing 4 bytes or more, and the address you should be looking is a little behind.

**Comment by oddMLan** [comment]
That being the case, does it this need to be open then?

**Comment by Dragorn421** [comment]
Yes. Testing with latest nightly `v2.4.0-1225-gb9dac46` it's still very much broken.

Used about the same script, taking into consideration remarks about `debug.breakhere()` location (can't test in events because they don't trigger!) and instructions writing more than 1 byte:
```js
console.print('Loading...\r\n');

function onWriteAny(address)
{
	console.print(address + '\n');
}

events.onwrite(ADDR_ANY, onWriteAny);
events.onwrite(0x80013837, function(){
    console.log('CPU is modifying 0x80013837')
});
events.onwrite(0x80013838, function(){
    console.log('CPU is modifying 0x80013838')
});
events.onwrite(0x80013839, function(){
    console.log('CPU is modifying 0x80013839')
});
events.onwrite(0x8001383A, function(){
    console.log('CPU is modifying 0x8001383A')
});

const JR_RA = 0x03E00008 // 'jr ra' command
events.onopcode(ADDR_ANY, JR_RA, function(pc)
{
    console.log(pc.hex());
	debug.breakhere();
});

console.print('Loaded!\n');
debug.breakhere();```

Apart from the Loading Loaded messages, and sometimes the debugger Commands windows showing up, it does absolutely nothing. Memory viewer does show memory is being written to.

**Comment by project64** [comment]
Are you running on interpter or recompiler, it might be that some of these things only work on the interpter.

**Comment by Dragorn421** [comment]
I'm assuming this is the relevant option ![image](https://user-images.githubusercontent.com/5306619/84065760-2b665680-a9c5-11ea-9209-512aac1de545.png)

I was using recompiler but using interpreter doesn't seem to change anything for running this script unfortunately

**Comment by project64** [comment]
after you change the setting to interpter, restart the emulator and try again
