### ISSUE TITLE
SRAM Inaccuracy Using Recompiler, Stale Data Seems to Persist

### ISSUE THREAD

**Issue by flagrama** [project64/project64#1733]
This is something weird we run into a lot in the Ocarina of Time Randomizer.

Reproduction Steps:
1. Boot an Ocarina of Time 1.0 NTSC ROM. Once you get the intro with Link on the horse the save file should be created. Overall version of the ROM doesn't matter, but you'll need a 1.0 NTSC ROM to generate a rando ROM to recreate easily. (CRCs CD16C529 or EC95702D for U or D423E8B0 or B58E98BB for J, either language works, this was recreated with a EC95702D checksum ROM)
1. Go to https://ootrandomizer.com/seed/get?id=433902 browse to your 1.0 ROM for the Base ROM field, then click Patch ROM at the bottom to generate a rando ROM that is convenient for testing.
1. Load the rando ROM, start a new file, and load it.
1. Exit Kokiri Forest via the exit that normally goes to Hyrule Field. It will lead you to Kakariko Village from the entrance that normally goes to the Graveyard.
1. Play Sun's Song (you start with an ocarina and the required songs, so you don't have to find them) to make it night time.
1. Enter the Windmill.
1. Play the Song of Storms.
1. Wait for the cutscene of the well draining to fade to black.

Expected:
- You fade back in to the windmill in front of the windmill man.

Actual:
- The screen never fades back in. The game appears to have softlocked. The "debug code" for OoT doesn't seem to work at this point either, so it does not appear to be a game crash.

This does not occur following the same steps on an Everdrive 64 (I made sure both ROMs were named the same so that they used the same save file).

We are pretty certain that they do not happen on Wii Virtual Console either. However, the same kind of issues seem to appear in Dolphin's Wii VC implementation, though I'm unsure if this exact instance happens. I will have some people test these instances as well using these steps as well, however the fact that it does not occur on N64 hardware is good enough for me to make this report.

The core issue here has caused unending problems for people playing the randomizer, not just this specific instance. Randomizer modifies default SRAM flags, and those changes don't seem to be correctly interpreted by the emulator if an existing save is already there. This can cause issues even between randomizer ROMs as we set flags based off the settings someone selects in the generator.

- Using a unique game save directory is a workaround, and we even recommend it, however I would prefer if this issue was fixed on default settings.

- The issue does not seem to occur if using the interpreter instead of the recompiler.

- The issue does not seem to occur if Protect Memory is enabled.

**Comment by LegendOfDragoon** [comment]
Is protect memory enabled?

**Comment by flagrama** [comment]
These repro steps assume it is off, as that is the default setting. Enabling it fixes the issue as well.

**Comment by LegendOfDragoon** [comment]
The problem is that per-game settings aren't automatically applied to patched roms since the CRC changes.

**Comment by flagrama** [comment]
That's somewhat annoying. Since the save file name is based off of the header, it'd be nice if Project64 could use that as a backup identifier if the CRC didn't match any known ROMs.

**Comment by LegendOfDragoon** [comment]
I agree that it is annoying. There should be a good way to handle this, instead of having to manually edit settings every time there's a new updated patched rom.

**Comment by oddMLan** [comment]
Until #1729 is looked at there's no other way of addressing this but adding the OOT randomizer entries to the RDB. You can include a modified RDB with your distributives or make a pull request adding the entries to the current RDB.
I was thinking of a couple ways this could be addressed more seamlessly in the future.

**Comment by flagrama** [comment]
Rando isn't _a_ ROM Hack. It's effectively infinite ROM hacks. Nearly every of our 433,902 seeds generated on the website, and countless others generated with the offline builds are a completely new ROM with a distinct CRC.

**Comment by oddMLan** [comment]
I see, well there's a "Defaults" panel in Settings, however it doesn't have self-mod method as an option. Adding the ability to change the default would address the issue?

**Comment by flagrama** [comment]
If they have to modify the configuration anyway, just telling them to use the Unique Save Directory option is enough. I'd just personally prefer if as little configuration as possible was necessary for a new user to OoTR.

I suppose it doesn't matter too much since they already have to switch the default RAM size to 8MB to even run the ROM, but people tend to stop reading after the first thing "fixes" their problems, then run into this much later. In that case having the option to set this setting as default would be useful. But at the point they need to configure an emulator, most of the community is far more familiar with BizHawk and RetroArch so those get recommended instead quite quickly.

**Comment by oddMLan** [comment]
> they already have to switch the default RAM size to 8MB to even run the ROM

They don't need to. Unknown ROMs already default to 8MB RDRAM in the current dev builds

**Comment by flagrama** [comment]
Well, that's both a blessing and a curse.

**Comment by flagrama** [comment]
Thanks. While it's not ideal, at least it's better than nothing and is something simple to tell people to do.

**Comment by Nicholas-Steel** [comment]
> 
> 
> > they already have to switch the default RAM size to 8MB to even run the ROM
> 
> They don't need to. Unknown ROMs already default to 8MB RDRAM in the current dev builds

So... are Defaults now ignored when loading an Unidentified ROM? The Default defaults to 4MB but unidentified ROM's which have never previously been interacted with by PJ64 use 8MB creating a bit of a disconnect.

Alternatively the Default needs to be updated to default to 8MB.
