### ISSUE TITLE
Donkey Kong 64 Banana Fairy Freeze

### ISSUE THREAD

**Issue by SAIYAN48** [project64/project64#1734]
[System]
i7-8700K
Gigabyte Z370XP SLI
GTX 1660
16GB DDR4
PJ64 2.4.0.1159-gbdd1d1e

When taking a picture of the Banana Fairy in Gloomy Galleon, the game will softlock using the built-in version of GlideN64. When using GlideN64 4.0 or any other built-in plugins, the emulator will crash with a fatal error.

[Project64.log](https://github.com/project64/project64/files/4577590/Project64.log)

**Comment by IronYoshi64** [comment]
Wait this is closed? Is this no longer an issue on newer PJ64 or GLideN64 builds?

**Comment by SAIYAN48** [comment]
I fixed it by reloading the battery save on 1.6 and it just worked.

**Comment by IronYoshi64** [comment]
> 
> 
> I fixed it by reloading the battery save on 1.6 and it just worked.

Ok then. xD
