### ISSUE TITLE
Lower CPU Usage for Project64

### ISSUE THREAD

**Issue by P0W3** [project64/project64#1738]
I want Project64 to have the lower CPU usage.

**Comment by IronYoshi64** [comment]
> 
> 
> I want Project64 to have the lower CPU usage.

How much CPU usage are you getting? I believe its normal to get around 5-30% depending on your Plugin, the game, and how good your computer running Project64 is.

**Comment by project64** [comment]
I am going to close the issue, we can keep talking on it. I always try to get lower cpu usage where ever possible, but there is nothing directly that I can do directly for this issue.
