### ISSUE TITLE
Debugger: Execute breakpoint doesn't trigger

### ISSUE THREAD

**Issue by bryc** [project64/project64#1740]
In Perfect Dark, when I set a breakpoint to `80349070` it doesn't trigger. This also happens in Goldeneye at `800CF534`, which is temporarily the same function during boot (gets overwritten later). I know for sure that these instructions get executed, because a Gameshark code targeting these addresses produce tangible results.

In contrast, the same code exists in Banjo-Tooie (also only temporarily) at `80192844`, and that breakpoint _does_ trigger. The same code exists in Banjo-Kazooie at `8025C104` and it triggers as well. 

So we have 4 games that contain the same function, but breakpoints only work on two of them (the Banjo games). 
Is there some logic behind this, or is it a bug? It seems to happen in Nemu64 as well.

This makes the task of debugging things about 100x more difficult. :cry:

**Comment by project64** [comment]
I doubt this is a bug.

how do you know that code is actually executed at that address?

for games like goldeneye it executes code from the tlb, so while this might be the physical address that the code is located at. It does not mean that it actually executes at that location. The breakpoint is at the address it is executing from, not where that address translates to.

**Comment by bryc** [comment]
> how do you know that code is actually executed at that address?

I can "lock" some of those memory addresses to a specific value, but it's not reliable between boots, so I'm using Gameshark cheats to modify the code at that location:

These are the values I used to lock (which replace some load immediate's with zeros):
```
80349070: 3C0E0000 (LUI T6 0x8F80 ->0x0000)
80349074: 3C0F0000 (LUI T7 0x3108 ->0x0000)
8034908C: 35EF0000 (ORI T7 0xB3C1 ->0x0000)
80349090: 35CE0000 (ORI T6 0x9F47 ->0x0000)
```
And the Gameshark equivalent: (they only write the adjacent halfword to replace the constant used)
```
81349072 0000
81349076 0000
8134908E 0000
81349092 0000
```
You run this GS code during boot, and the generated EEPROM will no longer be the same because the checksum value gets modified:
![image](https://user-images.githubusercontent.com/1408749/81459816-a7c00c80-916f-11ea-9092-4ad26ce1bda7.png)

So we know that the code at `80349070` gets executed, because we can modify it with GS, but not breakpoint it.

**Comment by project64** [comment]
the code at that address might being executed. You can map multiple virtual address to a physical address, so while that virtual address might map to the code being executed. How do you know the n64 ever actually is executing at that virtual address.

**Comment by bryc** [comment]
> the code at that address might being executed. You can map multiple virtual address to a physical address, so while that virtual address might map to the code being executed. 

If you search the RAM in Perfect Dark for the instruction `3c0e8f80` (LUI T6 0x8F80), you get two results: `80348F34` and `80349070`. And only the second one seems to cause changes to the EEP when modifying it by 'locking' or using Gameshark code on that address. The physical address version of those also exist, but don't show up in the disassembler window. So I can only use virtual address it seems.

> How do you know the n64 ever actually is executing at that virtual address.

I'm only able to guess that it's executing there, based on Gameshark codes or Memory locks on that location, being able to change the way the game executes on boot.

> for games like goldeneye it executes code from the tlb, so while this might be the physical address that the code is located at. It does not mean that it actually executes at that location. The breakpoint is at the address it is executing from, not where that address translates to.

That could explain it, if Banjo games _don't_ use TLB but GE/PD do. Is there a way to access its true location in TLB to successfully apply a breakpoint?

**Comment by project64** [comment]
we can discuss it on discord and see if we come up with any solutions .. the biggest problem with say golden eye is that it does a dynamic memory manipulation, so the location might not be the same on each allocation.

https://discord.gg/PjKm3FW

**Comment by LegendOfDragoon** [comment]
>Is there a way to access its true location in TLB to successfully apply a breakpoint?

You can click on debugger->memory->tlb entries, then click on tlb rules. it will show you the current TLB memory map

**Comment by project64** [comment]
talking on discord, it does trigger a BP, it is using the address 7f129070 to execute.
