### ISSUE TITLE
Improper texture mapping

### ISSUE THREAD

**Issue by kivan117** [project64/project64#1741]
While working on a basic demo rom I noticed an error in the texture mapping when running with project64 (latest nightly at the time). The rom displays 3 spinning cubes. Each cube shares the same vertex and texture data.

The cubes have an extra 0.5 pixels of the texture visible in both dimensions compared to what they should have. They should show the top left 8x8 portion of a 32x32 texture, but instead show 8.5x8.5

Running on real hardware produced the desired result, not the additional half pixel in each dimension. Other emulators produced the desired result as well.

I compared with mupen64plus running the same GlideN64 version, attached is a screen shot:
![texture_map_error](https://user-images.githubusercontent.com/12374646/81464309-f7bec380-91af-11ea-9671-9cdefbe854ac.png)

**Comment by project64** [comment]
I am not sure how to even guess why that would be the case, if the version of GlideN64 is exactly the same, then the data passed to the plugin is different. Why it would generate different information is, is it possible that it is cause it defaulting to the 32bit engine, if you turn that off does it work correctly?

**Comment by kivan117** [comment]
Updated to latest commit of GlideN64. Whatever caused the issue is resolved.
