### ISSUE TITLE
Every single game crashing

### ISSUE THREAD

**Issue by anonymous7002** [project64/project64#1743]
Every single game I try to play on Project64 2.4.0.1168, crashes immediately:
Fatal error: Stopping emulation
2.4.0.1157 worked fine.
Plugins: GLideN64, shunyuan's audio, N-Rage.

**Comment by IronYoshi64** [comment]
I just downloaded the version, did almost nothing to it besides uncheck hide advanced settings and set gfx plugin to GLideN64. I loaded up SM64, OoT and Yoshi's Story. All was fine, and without any crashes. I think it is something on your end that is causing the issue.

**Comment by LegendOfDragoon** [comment]
it might be because of shunyuan's audio. it crashes with some versions of project64.

**Comment by project64** [comment]
if you extract v2.4.0-1168-gce233b0 (https://www.pj64-emu.com/nightly-builds) to a new directory does it still crash for you?

**Comment by dftf-stu** [comment]
@anonymous7002: please download the latest 3.0.1 ZIP from [here](https://www.pj64-emu.com/public-releases) and the latest alpha/beta release (4.0.0) from [here](https://www.pj64-emu.com/nightly-builds).

Are you able to get crashes still in both of those latest versions of the app?
