### ISSUE TITLE
Add support for N64 DD cartridge port save functionality.

### ISSUE THREAD

**Issue by xmat123x** [project64/project64#1744]
This is probably a huge amount of work but it'd be great if we could save our progress on PJ64 like the Everdrive can with the English translated F-Zero X DD cart hack.

**Comment by oddMLan** [comment]
For the gamecart hacks iirc you need to add to the project64.cfg file
For native N64DD images (.ndd) saving functionality is normally implemented

[CRC1:CRC2:CIC]
AllowRomWrites=1

**Comment by xmat123x** [comment]
Thanks for the quick reply. I've added that to my project64.cfg but the cart hacks still lose all progress when I end emulation. I really can't find much info about it online.

**Comment by Fanatic-64** [comment]
Try adding it to Project64.rdb instead.

(Also note that Project64 may be reading Project64.cfg from C:\Users\[Current User]\AppData\Local\VirtualStore\Program Files[ (x86)]\Project64 2.3\Config\Project64.cfg)

**Comment by xmat123x** [comment]
Seems like the Project64.rdb entry for "F-ZERO X + Expansion Kit (U) [CART HACK]" already contains "AllowROMWrites=Yes". I swapped it over for "AllowRomWrites=1" just in case that was it with no success.

I really think PJ64 lacks saving support with cart hacks, Luigiblood explains it himself here:
https://github.com/project64/project64/issues/470#issuecomment-106177912

**Comment by oddMLan** [comment]
I was told that AllowROMWrites only allows writes in RAM to the ROM area during execution and the changes are not permanent. So there's no way to play this on a emulator with persistent saving unfortunately. A workaround would be using savestates.

**Comment by xmat123x** [comment]
LuigiBlood has ported the translation over to the disk version and gotten it to work with a NTSC-U F-Zero rom so I guess there's no need to use cart hacks anymore.

**Comment by flagrama** [comment]
Can somebody fix this stupid renaming bs?
