### ISSUE TITLE
Rom browser fields don't display in x64 build

### ISSUE THREAD

**Issue by harlayzhou** [project64/project64#1745]
Only show Name and Status

![x64](https://user-images.githubusercontent.com/8403754/81894311-06f3a600-95e2-11ea-809c-1a862fafced8.jpg)

**Comment by Fortich** [comment]
I think this is already fixed

**Comment by harlayzhou** [comment]
Nothing changed in last dev build.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/a25e5ca4c03d5ca50b0041708a535c7320563917 should fix it
