### ISSUE TITLE
Can't add or edit cheats.

### ISSUE THREAD

**Issue by ReyVGM** [project64/project64#1758]
Hello. I'm using the latest dev build (v2.4.0-1185-g1c55653) and when I enter the cheat menu (CTRL+C), I am unable to edit or add cheats.

If I click on "New Cheat", add the codes and name, then click on "Add Cheat", nothing happens. If I try to edit a current cheat, and click on "Update cheat", nothing happens either. Even when I edit the cheat, and then try to select another one, a popup will appear asking if I want to save my changes and even if I hit yes, the cheat will still not be updated.

I checked the Project64.cht file and it's not read only.

I attached my config file, just in case.

[Project6 config.zip](https://github.com/project64/project64/files/4661481/Project6.config.zip)

**Comment by project64** [comment]
I need to look at it, I did a lot of work recently on cheats so I could have broken things.

When you add/edit/add a cheat it is meant to copy the cheats to the cfg file and use that, so the .cht file should not be modified.

**Comment by ReyVGM** [comment]
Thanks for the reply.

I understand, but I moved from PJ64 2.2 to this new 2.4 version. Previously I was able to add cheats just fine, so that's why I'm reporting it because I assume it's a bug.

But for now, I am modifying the .cht file to add the cheats I need. I know how to edit it properly, don't worry. :)

**Comment by project64** [comment]
ok I updated pj64, see if v2.4.0-1186-g8fbdf8f fixes it for you.

**Comment by ReyVGM** [comment]
Yup! Now I can add and edit cheats like before. Thanks for the fix!

**Comment by project64** [comment]
the original code could do that, when I was cleaning up I thought it was not necessary as I pause emulation automatically when opening the cheat window which was added latter, since that was there I thought the ability to run both together was not necessary, as you point out I was wrong with that. 

I will hopefully looking at fixing that up this week.

**Comment by oddMLan** [comment]
Would reverting commit 226cfd8 be enough?
Also I believe pausing on plugin config should not be a thing.

**Comment by project64** [comment]
for most users it is a good things and should be left in place. For users that are creating cheats tho I can understand the argument that want to make changes and be able to keep it open while it is still running, so it is a small group of users, both are important and if possible both need to be supported.

**Comment by ReyVGM** [comment]
Could an option be added to enable or disable the pause when the cheat window is open? 

That way both worlds will be happy. It could even be added as an advanced option if you don't want regular users messing with that.

**Comment by jdijf** [comment]
I am using beta v 4.0.0.6111-7c71ec2 and i have this issue as well!
