### ISSUE TITLE
Ending emulation while the emulator is paused takes a long time.

### ISSUE THREAD

**Issue by ReyVGM** [project64/project64#1762]
I'm using the latest dev version (but this has been happening since forever too).

Whenever I pause the emulator (System > pause) and then I end emulation (File > End emulation), it takes like 30 seconds to go back to the game list. However, if I end emulation without pausing, it goes back to the game list right away.

And if I close the emulator window while it's taking that 30 second break, the emulator crashes.

**Comment by project64** [comment]
ok I will have a look

**Comment by bryc** [comment]
this seemed to happen often when i was using the debugger, if i stayed paused on one moment, it sometimes did not want to step - could be related. ending emulation often took a long time to get back to the game list

**Comment by ReyVGM** [comment]
I do have the debugger enabled. I just disabled it, but the same thing happens.

It's not a deal breaker or anything, it's just that when it does happen, you either have to wait it out, or you crash the emulator by closing it down.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/8dc26cc3eb206bdc044470faf534e80344da8b52

should fix it

**Comment by ReyVGM** [comment]
Thanks!
