### ISSUE TITLE
Libretro Core please!

### ISSUE THREAD

**Issue by Tuscarorachief081** [project64/project64#1767]
A Libretro Core for Retroarch would be nice. Mupen64Plus is trash on RetroPie, Recalbox, Batocera. Project64 is way more optimized and mature and thus it would be a great alternative to being forced to use Mupen64Plus.

**Comment by slash0042** [comment]
Don't use the old mupen libretro core, use Mupen64Plus Next instead, it is already very well optimised for rpi 3/4

**Comment by Tuscarorachief081** [comment]
That's what I've been using and it still fails in comparison to Project 64.

**Comment by slash0042** [comment]
I'm not against the idea of a PJ64 libretro port but why not ask for help to the core author (which is quite responsive when it comes about Mupen64Plus Next) at libretro discord instead of calling "trash" his hard work?

**Comment by CrashOveride95** [comment]
^

**Comment by project64** [comment]
Project64 is well optimize for x86, for other processors it needs a lot of work, I appreciate you liking of this work, but I agree do not put down any other emulators work. To get anything working is still a lot of work.

As I am the main contributor to project64 and I still have a massive to do list, I can not see this ever being done unless some one else wants to step up and do it. Then again I do not see a point as mupen64Plus has already done it.
