### ISSUE TITLE
I cannot change any settings

### ISSUE THREAD

**Issue by BenPlusYT** [project64/project64#1786]
After figuring out the last issue I had, I ran into something else. I cannot change any of my settings no matter what I do. The way I found out this was when I tried to change the type of save. No ROMs would load because it would say that it "couldn't initialize flash RAM", so I tried to change the save type and nothing happened. So then, I realized there was no \Save\ directory, so I created one and that didn't work either. After that, I tried creating separate directories for all of the ones I could, and it wouldn't let me pick the directory. The only settings that are actually able to be saved are controller settings and ROM locations. What's going on? By the way, I also tried reinstalling.

**Comment by flagrama** [comment]
Did you use the installer? Or did you use the zip file? If you used the zip file, where did you unzip it to.

**Comment by BenPlusYT** [comment]
I used the installer, and I downloaded it from the official website

**Comment by CrashOveride95** [comment]
Is it a nightly build?

**Comment by BenPlusYT** [comment]
I don’t think I downloaded a nightly build, I’m using ver. 2.3.2.3.

**Comment by CrashOveride95** [comment]
I suggest uninstalling and getting a nightly build from the pj64 site

**Comment by IronYoshi64** [comment]
> 
> 
> I suggest uninstalling and getting a nightly build from the pj64 site

Yeah. Get the latest Windows Zip at the top from here: https://www.pj64-emu.com/nightly-builds
