### ISSUE TITLE
What are the long term goals with Project64?

### ISSUE THREAD

**Issue by RokkumanX** [project64/project64#1788]
Long story short: Been using Project64 on and off forever and have been using m64p and the paraLLEl libretro core occasionally in between.

Now that I'm back using Project64 again with Angrylion-RDP-Plus, cxd4 RSP, NRage input and Azimers audio plugin most of the games I have in my collection is working pretty much perfect.

But once you start scraping the surface you'll soon remember some of the issues that you completely forgot, like the issue with the Mos Eisley speeder stage in Star Wars - Shadows of the Empire.
And yes this issue is of course also present in the other emulators to that I mentioned above but not as bad as in Project64.

Move the analog stick to much and you'll fly away in what seems like rocket speed.

This particular issue have been around in Project64 for as long as I can remember and from what I can tell no fix is available to this day?

Looking at the commit history there doesn't seem to be many commits focusing on core and accuracy improvement.
Not that it's a bad thing or anything, I'm grateful that Project64 is so active and is working so great (it is one of the best N64 emulators after all)

So, what are the long term goals with Project64? What are the plans for the future so to speak?
Are core and accuracy improvements being worked on or is it planned?

Thanks in advance and thank you for an excellent emulator!

**Comment by project64** [comment]
This is not really the place to discuss this as this is meant more for issue tracking.

at a high level
2.4 enhancements/cheats
2.5 test/accuracy
2.6 Multi platform

**Comment by RokkumanX** [comment]
OK thanks for your answer, sadly I don't have discord and don't know what it is but at least I have a glimpse of what your plans are.

**Comment by project64** [comment]
it is basically a chat site/program there is a link to the project64 discord channel on the pj64 homepage
