### ISSUE TITLE
Project64 Emulator cannot found on google playstore

### ISSUE THREAD

**Issue by Gamemulatorer** [project64/project64#1793]
Why this app remove play google play?
![Screenshot_20200611-130112](https://user-images.githubusercontent.com/37603562/84346957-d2283e00-abe3-11ea-937f-86c1ae822c3e.png)
any apk link?

**Comment by project64** [comment]
cause google complained that I did not have a 64bit build, where it just built a 32bit version. I need to change to using android studio over the current way. I also need to do a lot of work on the recompiler to make this better. At some stage I will come back to this , but other things are taking priority right now. 

My current plan is that I will have multi platforms as the main focus of 2.6, so UI that can run on multiple platforms and work on different cpu's for the recompiler. With 2.5 focusing on accuracy.
