### ISSUE TITLE
CBFD ECTS build crashes on recompiler

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#18]
Steps to reproduce:

First, edit the Game Settings as follows:
-Disable 32 bit Engine
-Set Function lookup method to Virtual Lookup Table
-Uncheck every Self Mod Method

This is in onder to make the game able to start correctly on the Recompiler. (also to be consistent with the Retail ROM settings)

To reproduce the error:
-Start the game
-Wait a couple of seconds.

You'll see that even the N64 logo is scared of these cryptic error messages :p

![conker_ects_error](https://cloud.githubusercontent.com/assets/7278372/5886018/c4663e0a-a33f-11e4-9f40-6cf21334cc74.PNG)
![conker_ects_error2](https://cloud.githubusercontent.com/assets/7278372/5886017/c44a263e-a33f-11e4-8565-98a5f4a0d2b6.PNG)

Setting the RSP to interpreter doesn't make a difference.
It only works correctly if I set the CPU core style to interpreter.

(Just a note, the ROM will appear as "Bad ROM? Use GoodN64..." in the ROM browser. The actual ROM name is "CBFD ECTS")

**Comment by oddMLan** [comment]
@project64
Sent you an important PM related to this bug over the Project64 forums.

**Comment by LegendOfDragoon** [comment]
I think most games require at least 1 option from the Self Mod Method to be enabled.

Judging from the error message, it looks like that particular instruction was never implemented. I took a look at source, and I think zilmar shouldn't have trouble fixing it.

**Comment by project64** [comment]
yer I will have a patch later today for this, already have it fixed just got to fix up push. 

it does need to turn off 32bit as well.

**Comment by project64** [comment]
ok https://github.com/project64/project64/commit/a88d03a12d78388d50a941aca82ef302a7060ce7 should fix it

**Comment by project64** [comment]
if you can confirm it is fixed i will close this issue

**Comment by oddMLan** [comment]
Fixed.

**Comment by cxd4** [comment]
dat avatar tho.
