### ISSUE TITLE
Error when manually starting emulation after loading ROM

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1835]
On the latest build. if the option "Start emulation when ROM is opened" is disabled, a ROM is opened, and then File>Start Emulation is selected or F11 is pressed, emulation will fail to start with the following message:
>Break point found at
UserInterface\MainMenu.cpp
300

This also happens on release version 2.3.2.202 (albeit with a Break point found error pointing to line 262 of MainMenuClass.cpp), but not on 2.3.0.210 or earlier.

**Comment by vgturtle127** [comment]
Is this fixed with the merged PR?

**Comment by Fanatic-64** [comment]
Fixed.
