### ISSUE TITLE
Project64 doesn't start anymore

### ISSUE THREAD

**Issue by Emixam23** [project64/project64#1840]
Hey guys,

Quite weird to explain but, for some reason, since like a week, when I start project64, nothing append. I do have an invisible window running somewhere it seems, but nothing usable/accessible.

I am on windows 10, what could be the issue? Sorry if I don't put more details, II just don't know what details you need to feel free to ask :)

Thanks

**Comment by oddMLan** [comment]
This is not a support forum. The bug tracker is for reporting consistently reproducible bugs. Try asking in the Discord server linked in the main page of this repo.
Tho my suggestion is, either Ctrl+Right click > Move the Project64 window in the taskbar or delete Project64.cfg from the Config directory.

**Comment by Emixam23** [comment]
Ctrl+Shift+Right click worked... I didn't know about the discord tho, sorry for thinking I could contact you as you were the support :) next time I go on discord :) Thanks!
