### ISSUE TITLE
Project Power demo not working

### ISSUE THREAD

**Issue by superbonaci** [project64/project64#1843]
You can download the demo rom here:
https://www.4shared.com/zip/vOAsiPy4ea/ProjectPower_Demo.html

**Comment by CrashOveride95** [comment]
Is this a full ROM?

Why not just post a patch?

**Comment by CrashOveride95** [comment]
It seems to work fine for me, I don't think this is an issue

You haven't provided any details as to what "doesn't work"

**Comment by superbonaci** [comment]
After some seconds of Emulation Started throws this error:
````
Direct3D8
While processing graphics data an exception occurred
you may need to restart the emulator
````
![](https://i.imgur.com/zixkqpi.png)

**Comment by CrashOveride95** [comment]
try a nightly build of project64

**Comment by superbonaci** [comment]
With `Project64-v2.4.0-1364-gf4106c9.zip` and `GLideN64` works perfect. Thank you very much.
