### ISSUE TITLE
Include cxd4-rsp plugin with Project 64

### ISSUE THREAD

**Issue by Yersho** [project64/project64#1851]
Cxd4-rsp (https://github.com/cxd4/rsp) is a good plugin if you also want to use something like Angrylion-RDP-Plus to have a LLE N64 experience however cxd4-rsp is hard to compile for a user with little experience with compiling programs. Neither the 32bit or 64bit cmd files work if you have both MSYS2 or MinGW set up despite what they claim so getting an up to date version would probably be difficult for the average Project 64 user. Including it with Project 64 lets users easily access an RSP plugin that they otherwise wouldn't be able to use. If you don't want to include it with Project 64 then maybe a fork of it with a Visual Studio solution file so more inexperienced users can actually compile the plugin.

**Comment by oddMLan** [comment]
Project64's RSP works just as fine with Angrylion RDP Plus, if not faster 🤷‍♂️

**Comment by Yersho** [comment]
I was suggesting it as an option for a slightly more accurate LLE RSP plugin option. I am aware that the default RSP plugin would run faster but having options for those who have the processing power is always nice.

**Comment by project64** [comment]
Thanks for the suggestion, I try to include external plugins that are not maintained by Projet64 team to a very minimum, so people are free to use it, but it will never be added to a Project64 distribution

**Comment by theboy181** [comment]
Pride!
