### ISSUE TITLE
basics of a emulator need some advice

### ISSUE THREAD

**Issue by MecaTommy** [project64/project64#1852]
Hey, I am trying to make my own n64 emulator.
How, would a programmer make a n64 emulator?
Whats the basics you need to make one.

I'm just interested in the basic emulation of n64 nothing special no extra's
Any advice can you all give me.
Much appreciated.

**Comment by project64** [comment]
find a demo like n64 stars and work out to get it working. good luck

**Comment by oddMLan** [comment]
What's with people opening frivolous issue tickets as of late? Anyways this is not the right place, this issue tracker is for reporting bugs. Your question is more suited for a N64 Discord server such as https://discord.gg/PjKm3FW. I'll see you there if you're interested
