### ISSUE TITLE
Mario 64 Speeds Up insanely fast when audio muted checkbox ticked

### ISSUE THREAD

**Issue by CRD716** [project64/project64#1853]
The title explains it all, 2.4.0.1377-g8ed4a80. To replicate simply run Mario 64, then go to audio and click the checkbox (not drag the slider down), and watch the game go very fast.

**Comment by IronYoshi64** [comment]
Wow, you are right. I have never noticed before. Of course I literally never use the Mute box, but yeah, that is weird.
I also tried this with Zelda OOT, same thing happens. I also tried with Smash Bros, but it stays just muted. BUT, the weird thing is right after a unmute, the game runs at around 40-50 VI's?

**Comment by IronYoshi64** [comment]
This has been fixed in newer Dev builds of PJ64. I think this should be closed.
