### ISSUE TITLE
Memory view crashes when trying to display register values

### ISSUE THREAD

**Issue by Yoshimaster96** [project64/project64#1859]
What the title says. Whenever I try to change the address value in the memory view window to view the values at hardware register addresses (for debugging purposes perhaps), the entire emulation crashes, and I also get a ton of popups with the following text (the line value depends on the exact address):

Break point found at    
.\N64System\Mips\MemoryVirtualMem.cpp    
1243

This affects the following memory regions:

    00400000-007FFFFF: RDRAM Expansion (only works when 8MB is enabled)
    00800000-03EFFFFF: Unused
    03F00000-03FFFFFF: RDRAM Registers
    04002000-0403FFFF: Unused
    04040000-040FFFFF: SP Registers
    04100000-041FFFFF: DPC Registers
    04200000-042FFFFF: DPS Registers
    04300000-043FFFFF: MI Registers
    04400000-044FFFFF: VI Registers
    04500000-045FFFFF: AI Registers
    04600000-046FFFFF: PI Registers
    04700000-047FFFFF: RI Registers
    04800000-048FFFFF: SI Registers
    05000000-05FFFFFF: DOM2 Address 1 (uncached version works, but cached doesn't)
    06000000-07FFFFFF: DOM1 Address 1 (uncached version works, but cached doesn't)
    08000000-0FFFFFFF: DOM2 Address 2
    10000000-1FBFFFFF: DOM1 Address 2 (uncached version works, but cached doesn't)
    1FC00000-1FC007BF: PIF ROM
    1FC007C0-1FC007FF: PIF RAM
    1FC00800-1FCFFFFF: Unused
    1FD00000-1FDFFFFF: DOM1 Address 3 (uncached version works, but cached doesn't)

RDRAM from 00000000-003FFFFF seems to work fine.

From what I can gather from the code, it seems to be due to trying to read registers outside the valid range. This is because the memory view displays 256 bytes at once, while the memory regions for these hardware registers are much smaller. Thus, when setting the address value in the text box to, say, 0xA4400000, the first 0x38 bytes will render fine, but once it tries to display anything after that, it errors out.

I'm on version 2.3.2.202 BTW

**Comment by oddMLan** [comment]
> I'm on version 2.3.2.202 BTW

Try using the [latest nightly build](https://www.pj64-emu.com/nightly-builds)

**Comment by Yoshimaster96** [comment]
Never mind, it works in nightly build.
