### ISSUE TITLE
I need a solution for this urgently....

### ISSUE THREAD

**Issue by AlexN64gamer** [project64/project64#1867]
I have a problem where ALL the roms i tried I get the same fatal error.... "Unknown memory action Emulation Stopped" im using the SAME setup I was using before formatting my SSD drive, Project64 2.3 last stable version, angrylion rdp plus 8, Azimers audio plugin 0.70 WIP 10, Nrage Input 2.4, and the default RSP plugin, my specs Intel I7 9700K, MSI RTX 2060, 32gb ram DRR5, Ive just changed my Drive and installed Windows 10 again, NEVER had this issue with Project64

**Comment by project64** [comment]
this is not a support forum, try asking in discord, or try taking the zip from nightly build (https://www.pj64-emu.com/nightly-builds) to a fresh directory and make sure it is working with out adding extra plugins in with default settings
