### ISSUE TITLE
[Question] Why is there no core for retroarch?

### ISSUE THREAD

**Issue by Eleazar001** [project64/project64#1878]
Hello everyone, first of all I wanted to thank the great work done on this project, which has made me enjoy countless hours of fun for many many years.

I have seen that the emulator has been "rebuilt" to support 64-bit processors and I have also seen that the code has been organized by separating the core into a directory. For all this, I have doubted why a core compatible with retroarch has not been made, since I consider this emulator to be the best existing Nintendo 64 emulator and I do not want to deprive myself of it when I use retroarch on other systems outside of PC.

Thank you very much for your work and I hope that day by day, and little by little, the project continues to live and grow to achieve the emulator with the best compatibility and performance that we could imagine. Greetings.

**Comment by project64** [comment]
cause I have nothing to do with retroarch, my aim is to make the best emulator I can, not to improve someone else's emulator.

The source is all released under GPL, if some one wanted to make a version that can work with retroarch they are free to, but I am not going to.
