### ISSUE TITLE
Saves not being recognized on newer Nightly builds

### ISSUE THREAD

**Issue by fanboy01** [project64/project64#1883]
For some odd reason, my save data is not being recognized starting from v2.4.0-1397-g5704fe5

Any Nightly build after v2.4.0-1397-g5704fe5 doesn't recognize my saves.

v2.4.0-1394-g25dde67 was the last Nightly build to recognize my saves.

I did not change the default save directory.

**Comment by IronYoshi64** [comment]
I probably know why. In newer Dev builds, they made it so Unique Game Saves is on by default. Literally do Options > Settings > Advanced > uncheck Unique game save directories. Click Apply then OK. Then boom, they should be back! :D

**Comment by fanboy01** [comment]
Hey, that did that trick! Thanks!

Btw, what is the "unique game saves" feature?

**Comment by project64** [comment]
the emulator general uses the game hash and country code to differentiate roms. The hash is only looking at the first 1 mb of the file so if the user uses slightly different versions of the game then it can cause issues. The unique game dir will create a md5 of the whole file and use that in the file name.
