### ISSUE TITLE
wine settings problem

### ISSUE THREAD

**Issue by fastrizwaan** [project64/project64#1887]
Hi, 
There is a bug report at winehq about Project64 which is pending for many years. If you could kindly look into it, Linux users can also use Project64 2.3 version.

under wine, the Settings dialog does not show anything on the right side:
![Screenshot from 2020-12-28 15-41-07](https://user-images.githubusercontent.com/1161682/103207002-3bbf2e00-4923-11eb-9ed5-dd87445f44f0.png)

https://bugs.winehq.org/show_bug.cgi?id=38651#c13

https://bugs.winehq.org/show_bug.cgi?id=38651#c14

https://bugs.winehq.org/show_bug.cgi?id=38651

Thank you!

**Comment by fastrizwaan** [comment]
in Linux (I'm using Fedora),
`wine Setup\ Project64\ v2.3.2-202-g57a221e.exe` will install PJ64

**Comment by nsivov** [comment]
If it works correctly on Windows, I suggested closing this, as it should be fixed in Wine instead, with information from a linked bug report.

**Comment by project64** [comment]
try with the nightly release:
https://www.pj64-emu.com/nightly-builds

you could try v2.4.0-1437-g4a4b0b2

**Comment by fastrizwaan** [comment]
Thank you, the settings are visible in  v2.4.0-1437-g4a4b0b2.
