### ISSUE TITLE
gliden64 plugin release 4.0?

### ISSUE THREAD

**Issue by fastrizwaan** [project64/project64#1888]
https://gliden64.blogspot.com/2019/04/public-release-40.html
https://github.com/gonetz/GLideN64/releases/tag/Public_Release_4_0

Could we include glideN64 plugin 4.0, as it has better support in Linux too.

**Comment by Rosalie241** [comment]
[the development builds](https://www.pj64-emu.com/nightly-builds) already contain GLideN64

**Comment by fastrizwaan** [comment]
Thanks.
