### ISSUE TITLE
audio plugin not showing up

### ISSUE THREAD

**Issue by aloshTM** [project64/project64#1890]
the audio plugin in pj64 won't show up and it is also blank
![image](https://user-images.githubusercontent.com/74996153/103238210-99e21600-490f-11eb-97c4-db79c3d24b97.png)
![image](https://user-images.githubusercontent.com/74996153/103238253-b7af7b00-490f-11eb-86f1-0754d0443c94.png)

**Comment by oddMLan** [comment]
Try a nightly build https://www.pj64-emu.com/nightly-builds

**Comment by theproblemmaker** [comment]
> Try a nightly build https://www.pj64-emu.com/nightly-builds

nope, still the same issue

**Comment by IronYoshi64** [comment]
Also please try the Windows Zip download, top most option. Please extract the zip file to a spot where you have full control over and permissions. Also please extract to its own folder, and make sure that Project64-Audio.dll file is in Plugin > Audio folder.

**Comment by theproblemmaker** [comment]
> Also please try the Windows Zip download, top most option. Please extract the zip file to a spot where you have full control over and permissions. Also please extract to its own folder, and make sure that Project64-Audio.dll file is in Plugin > Audio folder.

so i have extracted it, i see the plugin file, but in the actual pj64, its not showing up
![image](https://user-images.githubusercontent.com/74996153/103240222-54c0e280-4915-11eb-923b-828d0de2a22e.png)

**Comment by oddMLan** [comment]
Try uninstalling your audio driver and reinstalling it from the vendor's website.

**Comment by theproblemmaker** [comment]
> Try uninstalling your audio driver and reinstalling it from the vendor's website.

nope, I don't know what is causing this

**Comment by Squall-Leonhart** [comment]
current vc runtime files are necessary for plugins to work.

The video plugin that you show as working does not require VS2017 like the rest of the emulator currently does, this may be your issue.

**Comment by dftf-stu** [comment]
@aloshTM: since you first raised this issue on _Project64_ version 2.3.2, then 2.4.0, version 3.0.1 is the current stable, and 4.0.0 is the current unstable (development) release.

If you download the latest stable ZIP from [here](https://www.pj64-emu.com/public-releases) and the latest unstable ZIP from [here](https://www.pj64-emu.com/nightly-builds) do you still get the same problem?
