### ISSUE TITLE
Problem with reading audio sequences address

### ISSUE THREAD

**Issue by TheRealHootHoot** [project64/project64#1898]
I discovered a problem with audio sequence addresses in newer PJ64 version. It only reads addresses ending on an even hex character, if it encounters an odd character the audio is silent.

Is this intended? 

Can confirm it has been working in 2.2.0.3. also with odd numbers.

Definitely happens with 2.4.0.1426 and the newest 1450. This happens with all video and audio plugins I tested, so should be something emulator related.

**Comment by project64** [comment]
do you know what happens on a real console, is there a test for this?

**Comment by TheRealHootHoot** [comment]
No, sadly don't have the hardware anymore.

**Comment by oddMLan** [comment]
@TheRealHootHoot Enable "Unaligned DMA" under the rom settings. Does it work now?

**Comment by TheRealHootHoot** [comment]
Now it is working. So this function is optional now. What does it do?

**Comment by oddMLan** [comment]
It helps old romhacks targeting innacurate emulators. The N64 expects addresses to be 16 bit aligned.
"DMA transactions for data in ROM must use 16 bit aligned addresses."
Otherwise it gets tossed out.

**Comment by TheRealHootHoot** [comment]
Thanks for explaining and for your help. I think we can close this now.
