### ISSUE TITLE
Killer Instinct LLE will not boot unless interpreter is selected

### ISSUE THREAD

**Issue by theboy181** [project64/project64#19]
When using LLE GFX plugins Killer Instinct will not load. Changing to CPU interpreter fixes the issue, but I imagine at a cost of speed.

**Comment by cxd4** [comment]
It works if I disable Register Caching (both V1.0 and V1.2 ROMs).
That usually makes the recompiler as slow as the interpreter though.

**Comment by theboy181** [comment]
Don't see that as a real solution, but I will give that a try. 

I'm wondering if this issue is causing any other consequences in other games.

**Comment by LegendOfDragoon** [comment]
Oh wow, I didn't know it works if you disable register caching. I'll try investigating.

**Comment by theboy181** [comment]
Had time to test. Interesting that disabling register caching allows this game to boot. The performance is about the same as CPU interpreters performance too.

**Comment by cxd4** [comment]
It was the same with Conker's and Indy Jones before they were fixed IIRC.

**Comment by LegendOfDragoon** [comment]
Odd. On my machine, recompiler w/o register caching was still significantly faster than interpreter, for Killer Instinct.

**Comment by theboy181** [comment]
Are you using lle RDP? When I tested with mupen the speed was about the same as both scenarios too. At the menu where the fire starts I get an average of 29Vi/s

**Comment by LegendOfDragoon** [comment]
Still saw a noticeable difference with Pixel Accurate RDP. 17.8 vs 19.42.

When testing performance, it's best to get rid of bottlenecks that aren't related to what you're testing.

**Comment by project64** [comment]
ok I will do some testing with it on the sync core and see if I can find anything

**Comment by project64** [comment]
Made some commits https://github.com/project64/project64/commit/304aebbdd482828ccb7e63a22bb3baaa35bf7cb0 and https://github.com/project64/project64/commit/bbd45d45ba89254f68c5b44731d28abaed7ac8a7 does this work better for you now ?

**Comment by LegendOfDragoon** [comment]
@project64 Yes it works! Gj on fixing it. How did you track this down?

**Comment by project64** [comment]
running sync core then looking at why it does not stay in sync

**Comment by LegendOfDragoon** [comment]
Wow sync core is really effective! I'll try doing that next time I run into a cpu recompiler issue. You can close now.

**Comment by project64** [comment]
I would like to add something like that for the RSP where it runs the RSP interpreter in sync with the recompiler and checks the output.

That is more something for 2.3 tho, as I would need things to be broken up more in to small blocks and most likely will convert the RSP to use c++.
