### ISSUE TITLE
make sure all UI is translatable

### ISSUE THREAD

**Issue by project64** [project64/project64#190]
I do not think the config windows are all translated, make sure all text string that appear go though the language translation code.

**Comment by Lithium64** [comment]
@project64 Untranslatable places on UI
![bug1](https://cloud.githubusercontent.com/assets/10705488/6500862/e5c21720-c2ef-11e4-8ac3-938ef8f1b4e2.png)
![bug3](https://cloud.githubusercontent.com/assets/10705488/6500863/eb81d1e6-c2ef-11e4-89f3-709315811dc8.png)
![bug2](https://cloud.githubusercontent.com/assets/10705488/6500866/f082a3b4-c2ef-11e4-9bb5-2ee89881aec0.png)

**Comment by samuelyuan** [comment]
I have made a lot of the strings translateabled. #280

**Comment by MELERIX** [comment]
some more...

![more](https://cloud.githubusercontent.com/assets/1040116/6683359/7f2224cc-cc5b-11e4-87aa-60360dea5669.png)

**Comment by samuelyuan** [comment]
I understand what you mean. It's just that some of the strings aren't in the translation files, so there's no way to translate most of the text shown above (for example there's no string "frame rate display" in the English string file, so how would I know its translation in say Spanish?). 

I just made a pull request #285 which should translate "OK" and "Cancel"

**Comment by MELERIX** [comment]
@samuelyuan I see... anyway thanks for the work you have made ;)

I hope that zilmar or somebody else can later add these missing strings, and then we'll be able to translate them.

**Comment by harlayzhou** [comment]
![1](https://cloud.githubusercontent.com/assets/8403754/6750312/eb5bac0a-cf33-11e4-9c41-605c4a383cef.jpg)
![2](https://cloud.githubusercontent.com/assets/8403754/6750324/064c36ba-cf34-11e4-8d84-b26a3123a116.jpg)

**Comment by samuelyuan** [comment]
I have updated my pull request at #285.  
![pj64](https://cloud.githubusercontent.com/assets/5633676/6760425/c028cc62-cf1e-11e4-8760-ea2a5ba737bf.png)
![pj64-2](https://cloud.githubusercontent.com/assets/5633676/6760426/c1b22ab0-cf1e-11e4-971e-0fc94964d3ae.png)

@harlayzhou Are you using the Simplified Chinese version? I noticed that your version seems different from mine. Also PI DMA is translated as PI DMA.

**Comment by harlayzhou** [comment]
@samuelyuan Yes, I'm using Simplified Chinese that translated by myself.

**Comment by toehead2001** [comment]
Here are a few more hardcoded strings in the UI.
![aboutconfig](https://cloud.githubusercontent.com/assets/11582193/6840236/1cc3e320-d33a-11e4-82b3-c13b576489c2.png)
![rominfo](https://cloud.githubusercontent.com/assets/11582193/6840237/1cd53b34-d33a-11e4-8a39-87b4facf8e24.png)
![pj64statusbar](https://cloud.githubusercontent.com/assets/11582193/6840263/778f5fc8-d33a-11e4-8a45-15b7472d4a1b.png)

**Comment by samuelyuan** [comment]
Made a pull request at #349 
I have fixed everything except for what you showed in the bottom screenshot. Some of those settings you would just leave as is.

**Comment by harlayzhou** [comment]
@samuelyuan You foget this.
![image](https://cloud.githubusercontent.com/assets/8403754/7087811/d4492f44-dfc1-11e4-86e7-062036cb2d7e.png)

**Comment by samuelyuan** [comment]
I just updated my pull request, check if it works now.

**Comment by project64** [comment]
is this all done now? or is there other things here?

**Comment by Lithium64** [comment]
@project64 I haven't found untranslatable lines currently

**Comment by oddMLan** [comment]
I think this is done.
#188 is related but not the same issue. 

This can be closed.
If new incongruencies/unstranslated lines are found, smaller bug reports could be opened.
