### ISSUE TITLE
English language not working

### ISSUE THREAD

**Issue by DJRM2021** [project64/project64#1903]
I am using Project64-v2.4.0-1461-gd1223d1 on a Windows 10 PC.
Upon running Project64.exe for the **first time**, the English option is not available.
English.pj.Lang file is present in Project64-v2.4.0-1461-gd1223d1\Lang\ and not read-only.
![image](https://user-images.githubusercontent.com/77593544/104864475-0c28a200-5974-11eb-9ec6-e001de5c0a83.png)

This issue happens every time. 

I also tried to edit the Project64.cfg file, but it did not work:
[Plugin]
Audio Dll Ver=Project64 Audio Plugin: 1.0.1.1461-gd1223d1
Controller Dll Ver=Project64 Input Plugin: 1.0.0.1461-gd1223d1
Graphics Dll Ver=Project64 Video Plugin: 2.2.0.1461-gd1223d1
RSP Dll Ver=RSP Plugin 1.7.4.1461-gd1223d1

**[Settings]
Current Language=English**

**Comment by project64** [comment]
should be working now

https://github.com/project64/project64/commit/fb2025508cb830341fc9f740a95da45cd7bd0e32

the BOM header was removed

**Comment by Squall-Leonhart** [comment]
my bad
