### ISSUE TITLE
Possible COP0 register bugs

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1917]
I have started the initial testing for the Project64 audit and there may be bugs in the COP0 registers. I'm not 100% sure on this since Project64 itself doesn't give me breakpoints or any other error messages.

This is what it looks like:
![Glide64_COP0_register_test_01](https://user-images.githubusercontent.com/3183676/108318105-e108bc80-7184-11eb-8aaa-8c801cd25622.png)

It should look closer to this:

![COP0Register - after overflow](https://user-images.githubusercontent.com/3183676/108318282-2af1a280-7185-11eb-8ba8-5b53f6c7c4f2.png)

The test ROM used was this one:

https://github.com/PeterLemon/N64/tree/master/CPUTest/CP0/COP0Register

Contained in the repo is source code for the ROM and some images with expected output.

Running the latest development build of Project64 and the test ROM.

**Comment by vgturtle127** [comment]
It should be noted that some of the other CPU bugs may be the cause of this, I will open separate issues for them and will mention them if applicable.

**Comment by LegendOfDragoon** [comment]
Do you have 32bit engine disabled?

**Comment by vgturtle127** [comment]
I had it enabled. Disabling it only makes it fail an additional test instead of that failed test just not being run.

It should also be noted I get the same result on the CPU recompiler and interpreter.

**Comment by LegendOfDragoon** [comment]
Always disable 32bit engine for these test roms.

**Comment by vgturtle127** [comment]
OK, I changed the default to disabling it. Is there a specific reason?

**Comment by project64** [comment]
it is designed as an optimization that most games are compiled in c++ as 32bit .. but for accuracy it is best to have it off

**Comment by vgturtle127** [comment]
OK, gotcha. I thought maybe it might have to do with the address bus or something, but good to know!

The remainder of my tests were done with it off as well, just so you guys know. I also reran all the tests again just in case and I got the same results.

Thanks for letting me know though! :D

**Comment by bryanperris** [comment]
The accuracy of the results may not be too important, the test performs overflows on COP0 registers which is something a game shouldn't care too much about.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
