### ISSUE TITLE
Norton Auto Protect deletes setup

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#192]
This is what I get in Norton when building setup project64 2.2.exe.

>setup project64 2.2.exe (Suspicious.Cloud.9.B) detected by Auto-Protect,Quarantined,Resolved - No Action Required,d:\project64-master\project64-master\bin\release\setup project64 2.2.exe

Maybe the inno setup can be updated to the latest?

**Comment by project64** [comment]
now maybe it is picking up the ad code, but you also at times have issues with AV's where a file is new and so it has no reputation on it's cloud interface so it is more stronger looking at heuristics.

I do not think it has anything to do with inno

**Comment by MELERIX** [comment]
imho Binno Adware code should be completely removed from github.

there is no sense to have adware in an Open Source Project xD

**Comment by vgturtle127** [comment]
Just disable it until you're done installing, or add it to your whitelist.

I think we can close this issue now.
