### ISSUE TITLE
Possible issues with CP1 timing?

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1923]
The recompiler gives me an error and the interpreter fails all tests, perhaps something to be looked into?

Recompiler gets the following error messages:

![Project64_0g8BHR9I4r](https://user-images.githubusercontent.com/3183676/108327072-98ef9700-7190-11eb-9fa9-c3401c3e1d8f.png)

![Project64_bXgQYbepGg](https://user-images.githubusercontent.com/3183676/108327075-98ef9700-7190-11eb-94f7-33a150d35666.png)

Interpreter outputs this:

![Glide64_CPU_TEST_CP1_TIMING_01](https://user-images.githubusercontent.com/3183676/108327174-b15fb180-7190-11eb-95a6-9667d4e4a195.png)

Test ROM used: https://github.com/PeterLemon/N64/tree/master/CPUTest/CP1/TIMINGNTSC

Source and binaries are provided there.

Used the latest development build of Project64 and the test ROM.

**Comment by vgturtle127** [comment]
Small update: Now sometimes the ROM fails the tests and then gives me an error about the DADDI opcode, so could be that it needs that opcode for running this ROM.

**Comment by bryanperris** [comment]
The timing is going to be impossible to pass as the whole emulator would have to be completely cycle-accurate.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
