### ISSUE TITLE
DDIVU opcode gives error message and soft locks

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1926]
The interpreter and recompiler give me an error message after running into this opcode.

![Project64_WRsQb5NxEU](https://user-images.githubusercontent.com/3183676/108459415-381d9880-723c-11eb-81ec-8a51d0cf3745.png)

This is the error message I receive after running this test ROM: https://github.com/PeterLemon/N64/tree/master/CPUTest/CPU/DDIVU

Running the latest dev build of Project64 and the test ROM.

**Comment by bryanperris** [comment]
MIPS does allow x / 0, no exceptions are thrown in any case, however there is a specific side-effect that occurs as the result.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
