### ISSUE TITLE
Virtual memory error when testing RSP

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1934]
![Project64_yonGvT1FWB](https://user-images.githubusercontent.com/3183676/108587413-0af2e800-7319-11eb-90cc-7dda9806efe5.png)

This test ROM causes a virtual memory error, which should be investigated.

https://github.com/PeterLemon/N64/tree/master/RSP/DCT/FastZigZagQuantizationBlockDecode

Used latest test ROM and Project64 development build.

**Comment by vgturtle127** [comment]
It should also be noted that this happens with the CPU interpreter as well as the CPU recompiler.

**Comment by bryanperris** [comment]
make sure all HLE stuff are off.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
