### ISSUE TITLE
Memory leaks in Settings Class.cpp

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#195]
Default plugins selected, Jabo D3D8, Jabo DSound, PJ_NRage.
Open project64.exe
Start Emulation then close project64.

Memory leak detected.

>Order, Source File, Line Number, Mem Size
2065,.\Settings\Settings Class.cpp, 401, 8
2051,.\Settings\Settings Class.cpp, 401, 8
2081,.\Settings\Settings Class.cpp, 401, 8
2059,.\Settings\Settings Class.cpp, 418, 112
2061,.\Settings\Settings Class.cpp, 418, 112
2063,.\Settings\Settings Class.cpp, 418, 112
2067,.\Settings\Settings Class.cpp, 420, 112
2068,Unknown, 0, 32
2069,Unknown, 0, 32
2074,Unknown, 0, 32
2077,.\Settings\Settings Class.cpp, 401, 8
2073,.\Settings\Settings Class.cpp, 420, 112
2075,Unknown, 0, 32
2079,.\Settings\Settings Class.cpp, 420, 112
2083,.\Settings\Settings Class.cpp, 420, 112
2085,.\Settings\Settings Class.cpp, 401, 8
2049,.\Settings\Settings Class.cpp, 418, 112
2053,.\Settings\Settings Class.cpp, 420, 112
2071,.\Settings\Settings Class.cpp, 401, 8
2055,.\Settings\Settings Class.cpp, 418, 112
2057,.\Settings\Settings Class.cpp, 418, 112
2087,.\Settings\Settings Class.cpp, 420, 112
2089,.\Settings\Settings Class.cpp, 401, 8
2091,.\Settings\Settings Class.cpp, 420, 112
2092,Unknown, 0, 32
2093,Unknown, 0, 32
2095,.\Settings\Settings Class.cpp, 401, 8
2097,.\Settings\Settings Class.cpp, 420, 112
2099,.\Settings\Settings Class.cpp, 401, 8
2101,.\Settings\Settings Class.cpp, 420, 112
2102,Unknown, 0, 32
2103,Unknown, 0, 32
2105,.\Settings\Settings Class.cpp, 401, 8
2107,.\Settings\Settings Class.cpp, 420, 112
2108,Unknown, 0, 32
2109,Unknown, 0, 32
2111,.\Settings\Settings Class.cpp, 418, 112
2112,Unknown, 0, 32
2113,Unknown, 0, 32
2120,.\Settings\Settings Class.cpp, 446, 112
2121,Unknown, 0, 32
2122,Unknown, 0, 32

Don't think this has anything to do with Glide

**Comment by Frank-74** [comment]
I see you've fixed this 10 minutes after I posted the issue.  Lightning quick...

**Comment by cxd4** [comment]
He's crazy that way.  Sometimes reads through everything, every issue/commit blazing fast, other times doesn't get through it for quite a while.
