### ISSUE TITLE
RSP opcode CP2 VAND fails a few tests

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1954]
A few tests from the RSP test ROM CP2 VAND fail:

![image](https://user-images.githubusercontent.com/3183676/108958965-57039c80-7639-11eb-91dc-9a2b862a52d0.png)

https://github.com/PeterLemon/N64/tree/master/RSPTest/CP2/VAND

Tested with CPU interpreter/recompiler and RSP interpreter/recompiler. Same results for all.

Tested using latest Project64 dev build and test ROM.

**Comment by LegendOfDragoon** [comment]
Do you have 32bit engine disabled? I can't imagine PJ64 actually failing a test rom for VAND.

**Comment by vgturtle127** [comment]
Yes, it was disabled when I ran the tests.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
