### ISSUE TITLE
Plugin change on restarting a rom

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#196]
After Ending Emuation, changing game plugin, restarting rom.  Plugins don't change.

This condition in Project64\Plugins\Plugin Class.cpp, breaks plugin changes when restarting a rom.
```cpp
void CPlugins::PluginChanged ( CPlugins * _this )
{
	if (g_Settings->LoadBool(Game_TempLoaded) == true)
	{
		return;
	}
```
Game_TempLoaded is always true after ending emulation.
Removing the condition fixes it.

**Comment by LegendOfDragoon** [comment]
Is this still an issue?

**Comment by Frank-74** [comment]
Yes.

End Emulation, goto Edit Game Settings and change plugins, restart same game, plugins don't change.

Changing plugins via Options/Settings/Config:Game works ok.  Edit Game Settings doesn't work.

**Comment by Frank-74** [comment]
No longer an issue.
