### ISSUE TITLE
RSP test CPU XOR fails a few tests

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1987]
A few tests from the RSP test ROM CPU XOR fail:

![image](https://user-images.githubusercontent.com/3183676/109286578-04b4ae00-77e8-11eb-9502-868c5cb5a2f7.png)

https://github.com/PeterLemon/N64/tree/master/RSPTest/CPU/XOR

Tested with CPU interpreter/recompiler and RSP interpreter. Recompiler fails these tests, but same results for the rest.

Tested using latest Project64 dev build and test ROM.

**Comment by bryanperris** [comment]
They all pass here for me for both interpreted and recompiled.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
