### ISSUE TITLE
RDP test CPU causes error

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1990]
![image](https://user-images.githubusercontent.com/3183676/109288080-03848080-77ea-11eb-92c0-ee995348e2ef.png)

RDP test CPU ROM causes a virtual memory error. I'll be honest, I spent a lot of time on this error and I can't figure it out. I probably need to take a break from it and come back to it with a fresh mind.

Anyway, an RDP test called "test CPU" that causes a virtual memory error is somewhat hard to diagnose, unless I'm stupid and don't get it (which is plausible since I do all of this testing at 2-4AM because who needs a sleep schedule).

https://github.com/PeterLemon/N64/tree/master/RDPTest/CPU

Tested with CPU interpreter/recompiler and RSP interpreter/recompiler. Same results for all.

I also tried using Angrylion's plugin, Angrylion's RDP Plus fork, GLideN64, and of course the included default plugin.

Tested using latest Project64 dev build and test ROM.

**Comment by bryanperris** [comment]
problem seems to be related to the DPC registers, the default case throws a breakpoint, some important regs are missing from the switch:

        0x0410 0000 to 0x0410 0003  DPC_START_REG
                 DP CMD DMA start
           (RW): [23:0] DMEM/RDRAM start address
        0x0410 0004 to 0x0410 0007  DPC_END_REG
                 DP CMD DMA end
           (RW): [23:0] DMEM/RDRAM end address
        0x0410 0008 to 0x0410 000B  DPC_CURRENT_REG

https://github.com/project64/project64/blob/a7b9872c85cb9df24b9a77d95122d7625cd07aca/Source/Project64-core/N64System/Mips/MemoryVirtualMem.cpp#L1267

**Comment by bryanperris** [comment]
Actually test works for me, make sure Audio/Graphics HLE are both disabled, then use angrylion RDP, and I also forced interpreter mode too.

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
