### ISSUE TITLE
RDP test RSP causes an error

### ISSUE THREAD

**Issue by DerekTurtleRoe** [project64/project64#1991]
![image](https://user-images.githubusercontent.com/3183676/109288851-0633a580-77eb-11eb-985d-127414dff596.png)

RDP test RSP ROM causes a virtual memory error.

https://github.com/PeterLemon/N64/tree/master/RDPTest/RSP

Tested with CPU interpreter/recompiler and RSP interpreter/recompiler. Same results for all.

I tried using Angrylion's plugin, Angrylion's RDP Plus fork, GLideN64 (LLE and HLE), and of course the included default plugin.

Tested using latest Project64 dev build and test ROM.

**Comment by vgturtle127** [comment]
Also (this is mostly a note to myself, but also to you guys) I am done with the CPU and RSP testing for now. RDP tests were run that specifically tested CPU or RSP specific functions, and I encountered some errors. These could be related to the graphics plugin (which is a separate issue from Project64 itself) but I brought them up so we could investigate and discuss. Hopefully the testing was thorough enough that it helped. :D

**Comment by DerekTurtleRoe** [comment]
I am going to retest all of the Peter Lemon ROMs as well as other tests and put it all in one issue.
