### ISSUE TITLE
Conker's Bad Fur Day no longer launches anymore on latest Dev

### ISSUE THREAD

**Issue by IronYoshi64** [project64/project64#2009]
A User on the PJ64 Discord let me know that apparently Conker's Bad Fur Day doesn't load anymore on latest Dev build of Project64, currently 2.4.0.1555. I also tried to load it myself, and yup, got same result they did. 

Here is what pops up when trying to load Conker:
![Screenshot 2021-03-11 085021](https://user-images.githubusercontent.com/57850880/110806349-98a26300-8247-11eb-9091-31563ce93dee.png)

This doesn't seem to be an issue on the Dev build 2.4.0.1537 however, so something after 2.4.0.1537 broke Conker.

**Comment by flagrama** [comment]
Looks like cheats with "??XX" at the end aren't properly parsed as cheats.

**Comment by IronYoshi64** [comment]
> Looks like cheats with "??XX" at the end aren't properly parsed as cheats.

Wait, is that what is causing it? I looked into it, and there are no cheats or enhancements on by default for Conker...

**Comment by flagrama** [comment]
Doesn't have to be on, just has to exist. Seems to be something to do with the new Enhancements stuff where if it's not a gameshark code, it's assumed to be an enhancement code instead?

**Comment by IronYoshi64** [comment]
> Doesn't have to be on, just has to exist. Seems to be something to do with the new Enhancements stuff where if it's not a gameshark code, it's assumed to be an enhancement code instead? but it isn't actually one so causes an issue.

Wow really? Hmm...? OMG! I literally just made a new folder, moves the Cheats, Cheats-User, Enhancement, and Enhancement-User folders inside that, loaded the game and boom, it loaded. What the heck?! So yeah, that needs to be fixed.

**Comment by IronYoshi64** [comment]
So pretty much, all you need to do is this for the cht file for Conker:

$Access All\Characters & Weapons In Multi Race
810E9D02 ????
FFFF All Characters & Baseball bat
FBFF All Characters & Frying Pan
F3FF All Characters & Bones
