### ISSUE TITLE
Latest nightly release, 1688, has a problem staying in full screen mode (default GLideN64).

### ISSUE THREAD

**Issue by CCrashCup** [project64/project64#2026]
## Expected behavior
Full screen.
## Actual behavior
Either reverts to windowed mode or crashes.
Edit: I have not been able to reproduce it again. Not sure why.
## Steps to reproduce the problem

  1. Just run Zelda OoT
  2. Let the title sequence play.
  3. Go full screen.
  4. When the video sequence changes to a different camera, the glitch happens.

## Specifications

  - Windows version: 10
  - Project64 version: v2.4.0-1688-ge230133
  - Plugins used: GLideN64

**Comment by vgturtle127** [comment]
This is a GLideN64 issue, so not much we can do to fix it, best to report it to the GLideN64 repo instead.

Which version of GLideN64 are you on?

**Comment by CCrashCup** [comment]
The default GLideN64 that comes with Project64.
I see no point in reporting, like I edited my original post to reflect, I am no longer able to repeat the glitch.
Time to move on.
