### ISSUE TITLE
Mystical Ninja Starring Goemon Blank Screen

### ISSUE THREAD

**Issue by flayer6** [project64/project64#2037]
When in the Ghost Toy's Castle, after taking the 2nd elevator, (it goes up) and leave the elevator room, the next room is blank.  Sound still plays but you can't control character or see anything.  I tried latest build 4/26/21, public release 2.3.2 and 2.4.0.1100-g617db96.  I tried native graphic plugin, Glide, Jabo and Project64 plugin.  I have Intel 5500.  Any help/suggestions?  Can anyone replicate?

## Specifications

  - Windows version:10
  - Project64 version:various; see above
  - Plugins used:various; see above

**Comment by LegendOfDragoon** [comment]
Try using protect memory.

**Comment by flayer6** [comment]
Using the recent dev version, I enabled protect memory and it fixed the issue I encountered.  

Is protect memory hidden in one of the public releases?  If so, where? 

Lastly shouldn't there be something in notes field of these public and older releases that this game isn't truly playable, like it does for Iggy's Reckin' Balls, for example?  Thanks!

**Comment by DerekTurtleRoe** [comment]
In the RDB is SMM-Protect that same option of protect memory? If not never mind, but if so I can add that to the RDB at some point for this game (until it's unnecessary).

**Comment by LegendOfDragoon** [comment]
> Is protect memory hidden in one of the public releases? If so, where?

By default, advanced options like Protect Memory are hidden.

> Lastly shouldn't there be something in notes field of these public and older releases that this game isn't truly playable, like it does for Iggy's Reckin' Balls, for example? Thanks!

Mystical Ninja is playable, but its just that no one submitted the settings to the rdb.

**Comment by flayer6** [comment]
I don't see protect memory in 2.3 or 2.3.2, even when enabling advanced options.

**Comment by LegendOfDragoon** [comment]
In rom browser, right click the game -> Edit game settings -> Recompiler -> Protect Memory. Its in the Self mod methods section. If you don't see it, then it's because advanced options was disabled. You go to Options -> Settings -> Hide Advanced Settings. Make sure that checkbox is disabled.

**Comment by flayer6** [comment]
Re: 2.3
That did it! Although, right-click didn't work for me, going into settings after the game is loaded, allows access to recompiler, etc. for the game itself.  I never needed to access these settings once a game was loaded, so I didn't think to go there.  

There was one other spot this happened.  After using Yae's flute to ride the dragon and choosing Zazen town, entering the main town blanked out the screen.  That's fixed too.
Thank you, LoD

**Comment by LegendOfDragoon** [comment]
You are welcome. I submitted the setting change so now any user who downloads the latest nightly will not experience this crash. You can close this issue now.
