### ISSUE TITLE
Assign more functions to shortcut keys

### ISSUE THREAD

**Issue by dml360** [project64/project64#2062]
it would be interesting to assign some more functions like "save state" "load state" "change slot" because through the Project64.sc3 file, it is extremely difficult

**Comment by IronYoshi64** [comment]
> it would be interesting to assign some more functions like "save state" "load state" "change slot" because through the Project64.sc3 file, it is extremely difficult

Why you doing it through the file? You can easily do this through the Keyboard Shortcuts option of PJ64. Options > Settings > Keyboard Shortcuts. Make sure to have Hide advanced settings off and Apply and OK that for it to pop up on left side.

**Comment by dml360** [comment]
> > seria interessante atribuir mais algumas funções como "salvar estado" "carregar estado" "alterar slot" porque através do arquivo Project64.sc3, é extremamente difícil
> 
> Por que você está fazendo isso através do arquivo? Você pode fazer isso facilmente por meio da opção Atalhos de teclado do PJ64. Opções> Configurações> Atalhos de teclado. Certifique-se de ter a opção Ocultar configurações avançadas desativada e Aplicar e OK para que apareça no lado esquerdo.

it's true man, after your message I went through it and found that there is a window above with 3 options "game not playing" - "game not playing window" - "gaming not playing full screen"
I had never thought of that.
Thank you very much
