### ISSUE TITLE
NRage 2.5.2.202 won't save Xinput bindings

### ISSUE THREAD

**Issue by sephdotmp3** [project64/project64#2064]
simple as that. when i try to edit controller bindings with the Xinput setting on, it will not save my bindings. furthermore. trying to save said bindings to a .cfg file and loading them just wipes the settings clean, although once you "save" the controller settings, everything just goes back to the default.

**Comment by sephdotmp3** [comment]
addendum: i just noticed there were two "save" buttons: an upper one, which i assume to be for the current controller tab, and a lower one, which is for the entire controller configuration. trying to save the controller layout with the upper save button does apparently nothing (cosmetically), and then saving with the lower save button closes the window. when i go back to the controller plugin settings window, it just replaces what i changed (mapping the xbox b button to c-down and y to c-left) to none.

**Comment by IronYoshi64** [comment]
NRage 2.5.2.202 is very old now. Using NRage included in newer Project64 and Dev versions should have a way more updated versions. Also yeah, in order to save the XInput bindings, you have to click Save above the cancel button, Then Save at bottom.
Like this:
![2021-06-13 14-10-21](https://user-images.githubusercontent.com/57850880/121819161-43fcf280-cc51-11eb-8fb7-ecce9ef11dd2.png)

**Comment by sephdotmp3** [comment]
that's exactly what i described doing in my addendum i posted after the original issue submission. i tried a second time, and the selected button options don't show up after being saved, closing the plugin window, then reopening the controller plugin configuration window. however, my configuration is still working despite the actual options not showing up.

**Comment by Squall-Leonhart** [comment]
WFM, check your folder and file permissions.

**Comment by amoliski** [comment]
There should be a notification (or just auto save) that button (1) in that image wasn't clicked, I had to come here to find out why it wasn't saving my changes.

**Comment by sephdotmp3** [comment]
why on earth is this issue still open? i don't even think my original installation of p64 exists and i don't think my current one is giving me the same issues, so i think i have the authority to finally close this darn issue after two years.
