### ISSUE TITLE
Resizable window and fake fullscreen.

### ISSUE THREAD

**Issue by y0nd0** [project64/project64#2068]
The window should be resizable and the fullscreen should not be native. The fullscreen should just a borderless window in full screen size. The content should fit the window. 

The current behavior feels very obsolete. Fixed window size and native fullscreen which really changes the graphics card resolution. It's annoying. 

Flexible window and borderless window fullscreen is the modern way to do that.

**Comment by Squall-Leonhart** [comment]
you might not have noticed, but none of the plugins use dxgi/d3d11 so your request is presently unfeasible.

**Comment by y0nd0** [comment]
Why does the plugin matter? I thought it's just rendered in the window of Project64. So you can do everything you want with the window. But I don't know how Project64 works. Comes the window from the graphic plugin? Or does the plugin just renders the picture inside the Project64 its own window?

Personally I don't use Project64 anymore. I liked the render quality and performance, but the window resize / fullscreen issue is really annoying. So I use RetroArch now. In this case the n64 emulators are just cores rendered in the RetroArch window. 

I'm pretty sure that my english is not the very best, so it's a bit hard to explain. Do you really know what I mean with the fake fullscreen / borderless fullscreen. It's like in modern games. You can switch between native fullscreen and borderless window fullscreen. Native means, it changes the resolution of the graphics card output / display. But the borderless "fake" fullscreen is just a full sized window without the border (title bar, etc.) and covers the whole screen (incl. the taksbar). It looks like the native fullscreen, but does not change the screen resolution. Instead, you can change the internal resolution. 

Why using borderless "fake" fullscreen? It's hassle free. The screen does not change the resolution or frequency (Hz). It's awesome when playing on e.g. TV. Because TVs has a limited supported resolution range. The native resolution is the best choice. In my case, the TV is 4k (3840 x 2160). It can also render 1920x1080, but the image quality sucks hard in this case. It's not just a smaller resolution, it's just ugly. Less color and slighly flickering, etc. Anyway... You would love the fake fullscreen mode.

If Project64 cannot control this render windows, it's ok. You can close this issue. But it's a really weird and obsolete behavior. It's like Windows 95 program. ^^  No offence.

Is there a graph how Project64 works? To understand it. For example who provides the render window? Who sets the properties like resizable, etc.

Anyway, I'm out... You can think about this issue. Probably it helps you to find a great solution. Or just close it like I've never been here. ^^

**Comment by Rosalie241** [comment]
> Why does the plugin matter?

each plugin has to implement window stuff including fullscreen on their own, see GLideN64's implementation [here](https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/windows/windows_DisplayWindow.cpp).

**Comment by Squall-Leonhart** [comment]
> But the borderless "fake" fullscreen is just a full sized window without the border (title bar, etc.) and covers the whole screen (incl. the taksbar). It looks like the native fullscreen, but does not change the screen resolution. Instead, you can change the internal resolution.

It's implemented via DXGI Swap chains.

https://walbourn.github.io/care-and-feeding-of-modern-swap-chains-3/

**Comment by y0nd0** [comment]
Ok, interesting info / stuff. Thanks. 

If I understand it correctly. Project64 cannot change it since the plugin has to implement the render window and all the stuff how it's behave (fullscreen).

I am not a CPP or DX developer. Just a full stack developer. TypeScript, C#, Lua, GDScript, etc. So please be considerate. Bitty knowledge. 😄 

A rendering plugin should pass the image stream instead of creating own window. I don't know how RetroArch and its cores works. Do you know RetroArch? The cores are all rendered in the RetroArch window. And AFAIK the "Mupen64plus-next" core uses the latest GlideN64 renderer. So I guess it's possible to implement it. But I afraid that this requires a huge change of Project64. ... It would be great if Project64 is available as a core in RetroArch. Anyway...

> each plugin has to implement window stuff including fullscreen on their own

But why is the rendered image inside the Project64 window? Including the Project64 menu strip / bar and status bar. Ok the window completly reloads when starting a ROM. But the image is inside the window.

![window](https://user-images.githubusercontent.com/68586847/124188140-250ab700-dabf-11eb-9598-be0514c5bd80.jpg)

If the plugin creates its own window, I expected a foreign window without the Project64 stuff. But idk...
Do plugins need to implement the menu and status bar of Project64? Or comes this window from Project64 and just displays the rendered image from the plugin? 

Ok, the plugin can set the window size and fullscreen resolution, etc. But the window it self could just be unlocked and scale the content to fit the window size. (Keep aspect ratio.) It's maybe not trivial as I wrote. Because of issues like smoothness etc. ...

Again, feel free to close this issue. I have a guessing that this is a huge one. Maybe something for v4. ...

**Comment by Rosalie241** [comment]
> Do plugins need to implement the menu and status bar of Project64?

no, maybe I was a bit unclear but I meant that the video plugin has to implement certain things on their own, like resizing and fullscreen, they don't have to make the entire window from scratch, it's made by Project64 and certain events are sent to the video plugin (like when you click on the fullscreen button, or configure a different resolution in the settings window of the video plugin(the settings window + applying of such settings is ofcourse completely handled by the plugin)).

**Comment by y0nd0** [comment]
Ok, so it's possible to enable window resize, maximize button and implement a kind of a fake full screen like just disable the border and scale to fit the screen with always on top or somethink like that to also hide the taskbar. But these are technical details...

But the window content should be scaled with the window size. It makes no sense if only the window is changing it's size and the content keeps as it is. For the first step ignore image smoothing (scale filters). In RetroArch there are scale options like "integer scale" (1x, 2x, 3x, 4x, etc. closest to the available space / resolution for pixel perfect scaling.) and "Bilinear Filtering". But I prefer a pixelated optic. I also think that pixel perfect scaling is not necessary for N64. So no filtering. I would keep it as simple as possible for the first step...

How is the image rendered / drawn into the Project64 window? Is there an element like a canvas which can be scaled? 

Can the P64 window unlock the fixed size? Enable resizing and maximize button? So that the window can resized either by the mouse or Windows Aero Snap? And how does the window content (rendered image) behave when the window get resized? 

Note, I know that the graphics plugin has it's own resolution and fullscreen features. But the window is from P64, as you wrote. So you can do what you want with it. For example: If you maximize the window and scale the image to fit the window, the image resolution is the still the same as the plugin renders it. The plugin doesn't need to know what is happening to the canvas.

I cannot find related code. But where does the magic happend? The plugin renderes the image and where is it drawn? I guess either in a canvas / image / bitmap (aliases / aka) element. (Like in C# or HTML.) Or is it passed directly to the window context? I just have some experience with C# and rendering with GDI etc. But it's maybe a bit similar P64 / CPP. ... If the image is drawn directly, it's might be bit complicated to scale the content with keeping the aspect ratio. We could wrap it, and draw it in a seperate UI element. So that the element can be docked to the whole window. ... 

At first I would test what happens to the image when the window get resized. EIther it just keeps it size or scales 100% to the window, without respecting the aspect ratio. Because it does not yet know it.

Now if you say I am completely wrong and still do not get it, you can really close this issue. 😄 But it's hard to understand. Because why does this work in RetroArch using the Mupen64 core, which also uses GlideN64 for rendering. I'm pretty sure that Project64 can handle it. I really don't want to be presumptuous. I'm sure you are much more experienced in this stuff. So it's ok if you say that this is impossible for Project64.

**Comment by project64** [comment]
Project64 creates a raw window with the title, menu and status bar and passes the handle to the plugin and let the plugin resize and render to it. It has it as a blank canvas that it can resize and handle full screen. 

It leaves to the plugin how to do fullscreen, load the rendering engine (d3d, opengl, vulkan). Basically it leaves all gfx decisions to the plugin to give the most amount of flexibility.

**Comment by Squall-Leonhart** [comment]
if it really  bothers you that much, you  can override the plugins capabilities by using DGVoodoo, it'll always create a dxgi compatible borderless window if you configure it to do so.

Downside to that is you're stuck with Direct3D plugins.

**Comment by y0nd0** [comment]
P64 passes the window handle to the plugin, but P64 still has access to modify properties like resizable etc., right? Anyway, I doubt that will help us. But it would be interessting what happens to the rendered image if we resize the window. I won't test it, since I have to setup CPP build, etc.

I gonna close this now. It's not fixed and I think that this feature is possible to realize in this repo (not plugin), since other N64 emulators with GlideN64 can also do it. But it sounds like this is somewhat for the next major versions 4+ of Project64. So feel free to reopen or file new issues about that. I'm out. ... Thanks anyway. ... I stay on RetroArch. You could also consider to transform or provide Project64 core for RetroArch, which will also fix this problem here. :)

**Comment by Jj0YzL5nvJ** [comment]
**Non-exclusive Fullscreen Mode** (Fullscreen Borderless Window Mode) [_Borderless window maximized always on top, fullscreen in name only_]

Workaround: gonetz/GLideN64#1852

gonetz/GLideN64#2410

> you might not have noticed, but none of the plugins use dxgi/d3d11 so your request is presently unfeasible.

GLideN64 can get indirect support with Direct3D* by simply implementing [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)#Level_of_OpenGL_ES_support_via_backing_renderers), but that would only be relevant for using [HDR](https://github.com/gonetz/GLideN64/issues/1962).

**Comment by Squall-Leonhart** [comment]
don't need angle, just OpenglDxInterop and create a DXGI surface, then draw into this surface.

Supposedly PFD_SUPPORT_COMPOSITION in the PIXELFORMATDESCRIPTOR of ChoosePixelFormat/SetPixelFormat can be used for borderless window in opengl, i've never seen it done though.

**Comment by Jj0YzL5nvJ** [comment]
> i've never seen it done though.

You never heard of [mpv](https://mpv.io/), right?

```
mpv --no-config --no-border --gpu-api=opengl --pause https://avatars.githubusercontent.com/u/1098176?v=4
mpv --gpu-api=help
mpv --gpu-context=help
```

P.S: To close use the `q` key, double click for "Non-exclusive Fullscreen Mode".
