### ISSUE TITLE
Analog range problem in Buck Bumble

### ISSUE THREAD

**Issue by MateusAuri** [project64/project64#2072]
So... I'm tied between a couple of problems regarding controller plugins, but this one seems more relevant to report since I saw no mention to it here.

I'm using Project64 Dev-4.0.0.5665-a7b9872 (latest nightly build at the time) and its corresponding default input plugin, with an XInput controller. 

Buck Bumble is one of the rare games that won't register full analog signals (which are usually not reachable with an official N64 controller). If you push the stick all the way to the edge, the game gets confused and doesn't register the input.
Neither activating nor deactivating the "Analog Stick - Real N64 Range" option solves this issue.

The same thing happens on N-Rage, as its XInput mode offers no range slider.
DirectInput mode does offer that option, but I can't use that because of the annoying "Keyboard: ???" bug (as seen in #1875 ).

On a semi-related note, this "Keyboard: ???" issue seems to be inherent to P64, since I read other people report to have had it with other plugins besides N-Rage. Fixing that bug would potentially solve this issue.
Otherwise, fine tuning the "Real N64 Range" option might do it (although I'd rather use N-Rage, since it is much more feature-rich).

Potentially related issues: #1875 #1916 #1791 #1763

**Comment by Squall-Leonhart** [comment]
use xinput plus and reduce the output scale from 100% to 70%

**Comment by MateusAuri** [comment]
Wait, my dumbass completely missed the range slider under the analog stick mappings, I'm so sorry.
I'll check if that solves it and properly close this issue if it does.

EDIT: It doesn't. I'll try @Squall-Leonhart's suggestion now.

**Comment by Squall-Leonhart** [comment]
dll to save / rename to is xinput9_1_0.dll

xinput1_3.dll will not be loaded.

**Comment by MateusAuri** [comment]
Thanks for the tip! Still haven't got it to work, though. :/
I've set everything accordingly in XInput Plus, applied the config with the x86 version of xinput9_1_0.dll to Project64.exe, but no cigar.

Also tried the other versions and their x64 variants just in case. Still nothing, unsurprisingly.

I'll try to tinker with it again tomorrow and see if I get it to work somehow.

Either way, thanks for letting me know about XI+. It seems to be more feature-rich and user-friendly than Durazno.

**Comment by Squall-Leonhart** [comment]
the UI needs to expose sliders that allow the setting of a percentage of N64_ANALOG_MAX which is incorrectly set to 127 in the plugin.

(brand new)N64 controllers only manage to hit 92 (no where close to 127) and most games clamp anything beyond.

Buck Bumble seems to have a design flaw where the return value starts to decline beyond particular point before returning 0 at the far edges of a control that does hit 127.

I have a dirty code change that hard defines the left stick as 88 while keeping the right stick at 127 (the stick as c pad code is a disgrace and buttons only react if the range is default)

For whatever reason the analog max definition is applied to both sticks rather than just the stick defined as Analog Stick in the plugin settings.

**Comment by MateusAuri** [comment]
Awesome! You probably hit the nail right on the head there.

I used to think the Range options were tied to this N64_ANALOG_MAX value, but I was probably wrong.

EDIT: I tried making a build based on the source from your pull request to quickly test it, but couldn't because I am not quite experienced with Visual Studio yet and my build comes out without an executable file, probably my own fault. 
For now, I'll wait for it to be merged and grab the next nightly build. Thanks!

**Comment by Squall-Leonhart** [comment]
https://ci.appveyor.com/api/buildjobs/f46qur40s8u849xf/artifacts/Package%2FDev-4.0.0-5667-5902349a-Win32.zip
https://ci.appveyor.com/api/buildjobs/cijb8u2eiqed0wxv/artifacts/Package%2FDev-4.0.0-5667-5902349a-x64.zip

**Comment by MateusAuri** [comment]
Oh, many thanks!
Confirmed, Buck Bumble does work perfectly on that build.

**Comment by ICEREG1992** [comment]
Sorry for the bump, but I just ran into this issue myself and wanted to solve it without updating (and losing my saves and configs). For those running older builds of pj64, [Shunyuan's DirectInput plugin](http://forum.pj64-emu.com/showthread.php?t=4017) is the only input plugin for 2.3 I've found that addresses and fixes this issue out of the box, so give that a shot if you run into the same problem.

**Comment by Squall-Leonhart** [comment]
the issue is already fixed in nrage

**Comment by MateusAuri** [comment]
@ICEREG1992 interesting, although it's fixed already
I was going to DL it just to keep as a backup, but the PJ64 forums require login for downloading attachments, and registering seems to be disabled. If anyone needs it, it's [here](https://emulationrealm.net/downloads/file/3114-shunyuan-s-directinput-plugin) as well.

Anyway, as far as I know, updating is pretty simple. I just did it by extracting the [newest nightly release](https://www.pj64-emu.com/nightly-builds) into the same directory (although the previous version I had was also a relatively new nightly zip), and I don't think I lost anything.
You could also try updating over a copy of the directory just to test it first. Or else, just start anew in other folder and copy your saves over.
