### ISSUE TITLE
Blank error message

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [project64/project64#2074]
Hi. I was trying to load my SM64 hack but all I get is a blank error message. I tried several solutions on the internet (such as changing directories), but that didn't work either.

**Comment by CrashOveride95** [comment]
Does your hack work on console? perhaps it was made to work on older PJ64 versions that were more inaccurate

**Comment by LucianoTheWindowsFan** [comment]
I don't have a real N64, but never mind, since I got it to work after remaking the hack from scratch. Turns out the checksum was bad.

**Comment by kebien6020** [comment]
For anyone searching this error on google:

I got the blank error message when I moved my ROMs Folder and forgot about it, so Project64 was looking on the old place. I realized what was the problem when I refreshed the ROM list (F5).

**Comment by gdandsm64fan123** [comment]
I have the same problem but with an old zelda beta recreation, how do i make it work??????
