### ISSUE TITLE
N-Rage Input Plugin

### ISSUE THREAD

**Issue by CCrashCup** [project64/project64#2089]
The current version for Project64 is 2.3c. The link in the README.txt file for the source is broken. I tracked down the source repository, and the last version it has was 2.3d from 2017. The changes were not that extensive, but you might want to include them anyway. Here is the new link:
https://sourceforge.net/p/nragev20/code/HEAD/tree/trunk/

**Comment by Squall-Leonhart** [comment]
That was just this https://sourceforge.net/p/nragev20/code/77/

and its included in the pj64 nrage source anyway.
