### ISSUE TITLE
mk64 inaccurate emulation of startup logo

### ISSUE THREAD

**Issue by MegaMech** [project64/project64#2090]
Hello,

For some reason project 64 does not correctly display the nintendy logo in Mario Kart 64 (Vertex positions are all wonky). It would be nice if this could be fixed as decomp requires accuracy while testing certain elements.

This could be due to mk64 allegedly using a beta version of gbi.h (the graphics api). This version of the api was likely a development api and as such we do not have access to it. Some aspects of the gfx commands differ from other games such as sm64 or newer. It's possible that gsSPLine3D(), caused this issue as mk's variation appears to be a quadrangle command yet sharing the same gfx op code.

Please see the decompiled byte-matching vertex and gfx source code for the startup logo here as a reference.
https://github.com/n64decomp/mk64/blob/master/src/startup_logo.inc.c

**Comment by MegaMech** [comment]
Project 64 inaccurate emulation:
![image](https://user-images.githubusercontent.com/7255464/129473450-de16fed5-6678-406e-9f8d-ceeffa660962.png)

Actual n64:
![image](https://user-images.githubusercontent.com/7255464/129473468-c7e4e8f4-5f9b-4193-9732-ccb1fcd09756.png)

**Comment by project64** [comment]
what video plugin are you comparing with?

are you using a lle software renderer?

**Comment by Squall-Leonhart** [comment]
This is a PJ64Video GFX plugin issue and has nothing to do with the emulator core or RSP, use GlideN64 nightly, shunyuan or angry lion and you'll see theres no issues.

**Comment by MegaMech** [comment]
Yes it's PJ64 video. The startup_logo.inc.c file is the only file in the repo (afaik) that has this weird use of the quadrangle command (it's loading the byte data from differing positions). So that's possibly why this is happening. If you check out mk64's gbi.h you can compare with sm64's.

**Comment by project64** [comment]
not going to fix ... moving more to a lle plugin as I work with lle, I will see if I eventually replace the current Pj64 video or how I move forward once I get the LLE video going, but I am unlikely to use the current video code as a base, if your got an easy fix or know how to fix it then you can make a pull request otherwise I a going to close this with not going to fix

**Comment by MegaMech** [comment]
Which file(s) would I investigate to find the issue?
