### ISSUE TITLE
Found a problem... No Chinese simplified language...

### ISSUE THREAD

**Issue by Rosalina129** [project64/project64#2091]
I am using 3.0.1.5664,
Languages List no "简体中文"
![QQ截图20210801122646](https://user-images.githubusercontent.com/66776522/127759300-25fd1169-e595-455c-8f76-46c7a985df15.png)
But there are language files in the language folder inside the software...
![QQ截图20210801123051](https://user-images.githubusercontent.com/66776522/127759332-e7da8ca1-95fa-42af-965c-d689b139a255.png)

**Comment by project64** [comment]
https://github.com/project64/project64/commit/e5e55df4c58c84cc3cfb56b32d53fda97e4a23d6 should fix it, the Chinese simplified did not have the BOM marker

**Comment by Squall-Leonhart** [comment]
my bad!

**Comment by Rosalina129** [comment]
Okay, I used the Dev 3.0.1-5663 and found it, thanks.
![QQ截图20210801200504](https://user-images.githubusercontent.com/66776522/127770216-f18019ef-59a5-4a7f-80d6-65ac9b2d31ab.png)
