### ISSUE TITLE
VI Refresh Rate should be 1500 by default

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#21]
The current default of 2200 makes many games run too fast, a prime example being Perfect Dark. 1500 runs at the correct speed in all these games. The default should be 1500, and if any game benefits from a higher value it should be set in the RDB.

This is a trivial change and I've actually made it in the source (despite not actually knowing how to program, lol), but I'm still setting up git and so I can't make a pull request yet. Would somebody please take care of it?

**Comment by cxd4** [comment]
It used to be 1500; I think it was squall's idea to zilmar to have it changed to 2200 in alpha testing.

I don't know where in the source to take care of it.  You could probably send a pull request without installing Git and just use GitHub's fork feature, then use GitHub online code editor to edit the change over the web on your forked repo, then click the button on GitHub for sending a pull request, all without knowing how to use Git.  (I have not done this in practice though, so probably shouldn't recommend it.)

**Comment by Fanatic-64** [comment]
Commit with fix has been merged.
