### ISSUE TITLE
Support Project64 windows blocks windows functions.

### ISSUE THREAD

**Issue by louist103** [project64/project64#2101]
Right now when the "Support Project64" windows is open the user can not open minimized windows from the task bar.

**Comment by project64** [comment]
nothing with the support windows controls windows or stops this happening. It is just opening a standard dialog, so there is nothing that I now of that could be causing this issue or how I should be changing it so windows works correctly.

**Comment by Squall-Leonhart** [comment]
i've testedi this quite extensively, the task bar is not locked, you can open task manager or alt tab to it, the OS all works fine.
