### ISSUE TITLE
Project64 3.0/4.0 still creates a start menu folder called "Project64 2.3"

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#2103]
What it says on the title, plus the uninstall shortcut is still called "Uninstall Project64 2.3". Also, there is a shortcut called "Support" which leads to forum.pj64-emu.com, which no longer accepts registrations. The version numbers and the support shortcut should be updated, or alternatively the folder and the support and uninstall shortcuts could be eliminated (since there are support links within the application and uninstalling can be done from Add or Remove Programs), and just have the shortcut to Project64 on the top level of the start menu.

**Comment by Squall-Leonhart** [comment]
program group and uninstaller name shouldn't include version number at all,

**Comment by Squall-Leonhart** [comment]
shortcuts should never be on the top level of the start menu

**Comment by Fanatic-64** [comment]
> 
> 
> shortcuts should never be on the top level of the start menu

Plenty of programs have shortcuts on the top level of the start menu (as in, not within a program group). In mine there's: Acrobat Reader DC, Epic Games Launcher, Firefox, Google Earth Pro, etc. (and plenty of Microsoft apps).

**Comment by Squall-Leonhart** [comment]
plenty of programs are created by monsters, pj64 doesn't need to be one of them.

**Comment by Fanatic-64** [comment]
I guess you consider Microsoft to be monsters then :P. It's no big deal tho, I'll let zilmar decide how he wants to do it.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/54ef913eaf6a85a2574eeea997c6099a1cd56e4e
https://github.com/project64/project64/commit/400f110fc546ced40e302f8fb9c1d6902b5edf35
