### ISSUE TITLE
Project64 1.6 won't start 

### ISSUE THREAD

**Issue by DonLennox25** [project64/project64#2111]
Project 64 1.6 won't start.

I downloaded, reinstalled and installed several times, the 1.6 version (important for speedruns) won't start. Before I changed my cpu (before I had a ryzen 5 3600x, now I have an ryzen 7 5800x) it worked fine for me. Now if I click it, it tries to load and shows up for a second in the task manager, but after this nothing happens. Newer versions work for me, but I need 1.6, otherwise my speedruns are not legit. Any tips from you? I tried

Run as administrator
All different compatibility versions (win xp ect)
Reboot
Undervolt my cpu
Open the Programm with sandboxie

Nothing helped so far.

**Comment by CrashOveride95** [comment]
1.6 is not supported by this repository as it is not even included in the commits, nor even officially available for download. If speedrunners require 1.6 then that's their problem

**Comment by Squall-Leonhart** [comment]
update the motherboard bios.

**Comment by DonLennox25** [comment]
Hi there! My motherboards bios is in the newest version, but still won't start. Any other ideas? Greetings from Germany -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.09.21, 14:42 schrieb Squall Leonhart ***@***.***>:

   
  update the motherboard bios.
