### ISSUE TITLE
Some of the ROMs i have won't launch and give me an error.

### ISSUE THREAD

**Issue by J-man-witdaplan** [project64/project64#2113]

**Comment by project64** [comment]
this is not a support forum and there is no details that could even guess as a way to help, if you want help ask on discord some one there might have an idea

**Comment by J-man-witdaplan** [comment]
How do I ask discord

**Comment by DerekTurtleRoe** [comment]
@J-man-witdaplan https://discord.gg/9YYwt7Yj
