### ISSUE TITLE
Pokemon Puzzle League black screen

### ISSUE THREAD

**Issue by embeddedmz** [project64/project64#2115]
Hi,

Pokemon Puzzle League is unplayable with P64. The only thing that works are video cutscenes. For the rest, there's a black screen but commands and sound are working.

I tried to run this game with an Android Nintendo64 emulator : the videos are not visible but the rest is. The game is unplayable since the blocks are not visible, the cursor that swaps the blocks is visible.

**Comment by Squall-Leonhart** [comment]
use a different video plugin.

**Comment by embeddedmz** [comment]
I restored video settings to defaults and that fixed my problem ! I don't know how to use a different video plugin !

I have to play in a small window though :( full screen is broken.
