### ISSUE TITLE
Force feedback not working on Razer Raiju Ultimate controller

### ISSUE THREAD

**Issue by heikadog** [project64/project64#2116]
I'm using the Razer Raiju Ultimate controller on Windows 10 (Controller Hardware Id VID_046D&PID_1004). Rumble works on other games and emulators. 

### Expected behavior
- Rumble works
- Testing rumble works
- The controller shows up in force feedback, if using the NRage plugin, or just works with the DInput plugin.

### Actual behavior
- The controller no longer shows up in force feedback and doesn't work on the latest DInput plugin either

### Steps to reproduce the problem

  1. Use the Mori Force Feedback drivers, double-checking your Hardware Ids are used in the joy.reg file (and it's saved.). 
  2. The controller doesn't show up under Force Feedback in NRage and the rumble doesn't function under the DInput plugin.

### Error messages you received
- N/A. Project64 crashes when testing rumble on the NRage plugin if 2.3b is used; the controller shows up, but any version after that doesn't show the controller.

### Specifications

  - Project64 version: 4.0.0.5704-d72242d

### Plugins used while the issue occurred:

  - Input plugin: Tried both defaults which came with the latest dev build

**Comment by Squall-Leonhart** [comment]
Just you.
![image](https://user-images.githubusercontent.com/1098176/134792070-51a038ff-395d-47df-87e9-4536e64f2f6d.png)

**Comment by heikadog** [comment]
Do you have any suggestions for me to fix this? A version I should roll back to, something similar? I'm not sure what to do next.

**Comment by Squall-Leonhart** [comment]
theres been no changes to the emulator that would introduce this across both plugins.

**Comment by Squall-Leonhart** [comment]
i would try reinstalling Mori incase something has messed up the original clsid

**Comment by heikadog** [comment]
Tried reinstalling Mori, no dice—however, found x360ce by sheer luck. Case closed, it works now. Guess it was cause it was a Playstation 4 controller?

**Comment by Squall-Leonhart** [comment]
that could be it, the mori driver translates FFB intoxusb/xbusb compatible vibration, it will only work with controllers that present as a common class or xbox peripheral.
