### ISSUE TITLE
Project64 has major issues on the latest AMD drivers.

### ISSUE THREAD

**Issue by techflashYT** [project64/project64#2117]
On the latest AMD Drivers (at least in my testing, 21.8.? and 21.9.1), on my hardware, which never had issues with this emulator before hand, now has severe issues.  
1. Severe flickering  
2. Can't stay running for longer than like, 5 seconds before causing a driver timeout  
3. Sometimes completely locking up my PC until I do a hard reset.  

I have heard horror stories of some change that was made in these driver versions that MURDERS some programs, something about Vulkan I think?  I have tried with every graphics plugin I have, they all have the same issue.  Any suggestions would be appreciated!

Edit: Forgot to include my hardware!

Hardware+Software:
CPU: Intel Core i5-7400
RAM: 16GB
GPU: AMD Radeon RX 560
Project64 version: Latest dev as of 8:59, 9/25/2021 UTC-7
Windows version: Latest Windows 11 Developer build (OS Build 22458.1000 according to winver)

**Comment by Squall-Leonhart** [comment]
Tell it to AMD, not pj64's bug.

PS: in dev OS's are not supported.

**Comment by Squall-Leonhart** [comment]
amd may have addressed this with 21.10.2
