### ISSUE TITLE
Aleck64 ROMs stops the Rom Listing

### ISSUE THREAD

**Issue by LuigiBlood** [project64/project64#2121]
I just noticed that putting Super Real Mahjong VS Aleck64 ROM (and conversion) just stops the Rom Browser listing.
Any file after that one alphabetically do not appear in the list. (To give an idea I have Super Smash Bros. ROM after that one and it doesn't appear at all).

This is definitely a bug.

**Comment by LuigiBlood** [comment]
Uh... I haven't done much and it's not happening anymore. I'm not sure what happened.

**Comment by dftf-stu** [comment]
@project64: looks like this could be closed?
