### ISSUE TITLE
[JS Script API] Using events is a lot slower with the v2 API

### ISSUE THREAD

**Issue by Dragorn421** [project64/project64#2123]
For example with Ocarina of Time 64, the title screen runs fine at 20 fps without any script running, then just having this one-line script running:

```js
events.onread(0, function(){});
```

brings the fps down to 3.

I do not even have a bad laptop, it looks like the API is so slow it will be unusable in practice unfortunately.

In a Pj64 3.0.1 version (with the "old" api) running OoT64 title screen with the same script, I can't see any slow down.

**Comment by Dragorn421** [comment]
There may actually be more to this performance decrease than just using scripts, it looks like the JS API rewrite may have hit the interpreter core performance with debugger enabled (a combination which is most likely to happen if using interpreter at all).

I downloaded from https://www.pj64-emu.com/nightly-builds for comparison:
Dev-4.0.0-5699-f9597fc (the newest version without the API rewrite)
Dev-4.0.0-5703-5ef0bad (the oldest version with the API rewrite)

Still using the OoT64 title screen as a test for benchmarking, I made both versions run side by side in interpreter core with debugger on and "Limit FPS" off.
Rough time from first fade-in transition to first fade-out transition:
Dev-4.0.0-5699-f9597fc - 60 seconds
Dev-4.0.0-5703-5ef0bad - 110 seconds

(and this is without any script running!)
so it may be that **the API rewrite made interpreter core 80% slower** (but I'm well aware this is far from being exhaustive testing)

I'll make sure to try the version with your speed fixes when it gets built, hopefully it helps reduce the gap significantly.

**Comment by shygoo** [comment]
With #2125 it looks like baseline interpreter+debugger performance is actually better than it was with the old API. Performance with one event is also acceptable, however I'm noticing now that multiple events still slows it down quite a bit -- @project64 we can leave #2125 open for now and I'll see if I can add another commit to address this.

Rough speed tests at spot00 in MQ:

Baseline:
```
old api 180%
#2110   107%
#2125   214%
```

`events.onread(0, function(){})`:
```
old api 131%
#2110    22%
#2125   111%
```

`events.onread(0, function(){})` x2:
```
old api 130%
#2110     8%
#2125    93%
```
