### ISSUE TITLE
Cheats Turn Themselves Off.

### ISSUE THREAD

**Issue by mm132** [project64/project64#2126]
The cheats disable themselves after a while.

**Comment by foreverpyrite** [comment]
I know this is likely too late, but all you have to do is disable advanced options, and then click on the `Advanced` tab under `General settings` then check `Remember selected cheats`, than you should be good to go!
![image](https://user-images.githubusercontent.com/51493121/171969119-62bfd4fb-dc58-4941-a76e-dc89b17a2158.png)
![image](https://user-images.githubusercontent.com/51493121/171969121-ecd9ac60-d8a5-475d-82ae-74ebf06b72c1.png)

**Comment by dftf-stu** [comment]
@ForeverPyrite: this is similar to the number of users who ask "how can I turn-off the Status Bar", which is also hidden until you un-tick "Hide advanced settings".

While I appreciate why the PJ64 team wish for certain settings not to be shown by-default, I can't help but feel they should re-consider _which_ ones they hide, as it seems to just generate unnecessary support tickets here...
