### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by CCrashCup** [project64/project64#2128]
Removing the hotkey for [End Emulation] in [Game playing (full-screen)], also removes it from [Game playing (windowed)]. Even when you [Assign] the same default F12 key back to both modes, it never work correctly again for full-screen. Either the game locks up, or the emulator closes. I did test the F12 hotkey once, before I did any changes, and it worked properly. I think there are other issues with setting hotkeys, but this one should be easy to duplicate, and might well be the same underlying cause for the other issues.

**Comment by dftf-stu** [comment]
@CCrashCup: can you test this with both the most-recent stable 3.0.1 release, and the latest 4.0.0 Dev releases and confirm if there is still an issue?

If you download the ZIP versions of both, any changes you make won't affect the install you are currently using; all the settings will be separate to each folder.
