### ISSUE TITLE
My Greensreen rom wont open!! please help!!

### ISSUE THREAD

**Issue by somemariorecolor** [project64/project64#2129]
ive been trying to do something recently and i need my greenscreen rom to open so i can continue off that, but ever since i tried to put in a "cheat code" in to remove the HUD, my rom never opens, it works for other normal roms like your everyday SM64, but for some reason it just doesnt work here, even when i uninstalled and reinstalled it, and i tried gliden64, and that just made it worse since it has errors with the bits or something.

**Comment by somemariorecolor** [comment]
![Screenshot (5)_LI](https://user-images.githubusercontent.com/93088283/138601814-c9e53794-6e1c-47d0-bcfd-c44182a118d6.jpg)

**Comment by somemariorecolor** [comment]
![Screenshot (5)_LI](https://user-images.githubusercontent.com/93088283/138601885-b2b9c787-a5d4-4b0d-ad2d-cd9e4fcbb4c5.jpg)
this to

**Comment by IronYoshi64** [comment]
No need to post different posts for just pics, you can just drag and drop them onto the box and it will upload them.

Also try to turn on Unaligned DMA for the greenscreen rom. Do Options > Configuration. Uncheck Hide advanced settings, click Apply and OK. 

Now either right click the rom from rom browser, pick Edit Game Settings, or open it up then do Options > Configuration. On Left side, you should see Config: game title here, Check Unaligned DMA. Apply and OK that and reload PJ64 and try to load back up game.

**Comment by somemariorecolor** [comment]
yeah, im trying right now and it closes like INSTANTANIESLY, so is there another solution?

**Comment by TorutheRedFox** [comment]
run in interpreter mode

it usually gives a more detailed error message

**Comment by DerekTurtleRoe** [comment]
@project64 We can close this since this is more of a development help thing and not a Project64 issue.
