### ISSUE TITLE
Glide64 for PJ64 Resident Evil 2 regression

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#213]
This regression already existed on PJ64 2.1

Glide64 for PJ64
![glide64_resident_evil_ii_01](https://cloud.githubusercontent.com/assets/10705488/6501482/add38800-c2f7-11e4-970b-7893ddf39b05.png)

Glide64 Final
![glide64_resident_evil_ii_05](https://cloud.githubusercontent.com/assets/10705488/6501483/addfc75a-c2f7-11e4-935b-5f1edcfd9bdc.png)

Glide64 for PJ64
![glide64_resident_evil_ii_02](https://cloud.githubusercontent.com/assets/10705488/6501498/d766e522-c2f7-11e4-988f-541dac36df0f.png)

Glide64 Final
![glide64_resident_evil_ii_06](https://cloud.githubusercontent.com/assets/10705488/6501499/d77721ee-c2f7-11e4-8159-4369c4238a48.png)

Glide64 for PJ64
![glide64_resident_evil_ii_03](https://cloud.githubusercontent.com/assets/10705488/6501506/f4dbdffe-c2f7-11e4-8aea-05688d5ca4fe.png)

Glide64 Final
![glide64_resident_evil_ii_07](https://cloud.githubusercontent.com/assets/10705488/6501507/f4e820de-c2f7-11e4-9df2-90b1fff2c413.png)

**Comment by AmbientMalice** [comment]
This is caused by "Software depth buffer rendering" being disabled. I'm trying to figure out the correct command to re-enable it, then I'll add it to the Glide64.rdb

**Comment by Lithium64** [comment]
@AmbientMalice This didn't work the bug is still occurring

**Comment by Lithium64** [comment]
@project64 Please re-open this issue

**Comment by cxd4** [comment]
@Lithium64 , you are the creator issue and should be able to administrate the status of the issue (whether it's open or closed) without having to wait on project64 to re-open it.

This is no longer vBulletin forums; people can decide the status of their own issues.

**Comment by Lithium64** [comment]
@cxd4 you cannot re-open your own issues if a repo collaborator closed them

http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by cxd4** [comment]
onice !!!

**Comment by project64** [comment]
ok

**Comment by cxd4** [comment]
ExtremeDude2, dsx, AmbientMalice and I have all gotten this fix to work.

@Lithium64 has also gotten it to work on IRC after testing it on a different video card.  So this is a regression in Glitch64 during the integration with Project64, that affects lithium's older AMD video drivers for OpenGL, as we have reached.

**Comment by Lithium64** [comment]
@cxd4 I found a Mesa driver version 10.4.4 build for windows, but project64 crash when I try use it

This build works fine on others emulators

![mesa](https://cloud.githubusercontent.com/assets/10705488/6540697/523c22be-c48b-11e4-9dc3-2f0380eddd1c.png)

**Comment by LegendOfDragoon** [comment]
Has anyone tested this recently?

**Comment by cxd4** [comment]
IIRC @Lithium64 said on IRC that zilmar's Glide64 backports fixed all issues like this he was having.

**Comment by Lithium64** [comment]
@cxd4 yes, it fixed all regressions for me.

**Comment by LegendOfDragoon** [comment]
Can you close this issue then @Lithium64 ?

**Comment by Lithium64** [comment]
@AmbientMalice Ok
