### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by hugok79** [project64/project64#2131]
This text does not appear for translation in the "ROM browser tab" options

![Captura de ecrã 2021-11-04 144212](https://user-images.githubusercontent.com/16929048/140337436-3ed22242-85b5-45eb-8b2c-57a2ec6668e3.png)

**Comment by dftf-stu** [comment]
@hugok79: as a workaround for now, close _Project64_, then go into the folder which has your _Project64_ app inside, then go into the "Lang" folder and find the file with a name matching your language (in my case, "English.pj.Lang").  Open a _Notepad_ window, and then drag that file into the middle of the _Notepad_ window and you'll see all of the phrases used around the interface.

Find the one that hasn't been translated, amend it yourself, then save the file.

OR there have been some language-file updates for both Spanish and Portuguese (apologies, but I'm not entirely-sure which one you use) in the latest v4.0.0 releases, so you could also consider downloading the latest ZIP file from [here](https://www.pj64-emu.com/nightly-builds).

**Comment by hugok79** [comment]
@dftf-stu  Meanwhile, that string is already translated in commit: https://github.com/project64/project64/commit/90510c030826de812ad89ab026f7b8c77c0325af

But in the meantime I noticed that the translation is too long and does not fit completely in the window...

![Captura de ecrã 2022-08-05 174051](https://user-images.githubusercontent.com/16929048/183122672-553da251-2c7f-4d15-aba0-6c14972c9d75.png)


In response, I use Portuguese

**Comment by dftf-stu** [comment]
That's a pity.

As there are only two tick-boxes there, hopefully someone could move the right-hand one underneath the left-hand one in a future update to help resolve that issue...

**Comment by project64** [comment]
https://github.com/project64/project64/commit/8a01017ef5c872f63f145b41f5622dc242cf45ea

I moved the controls to there own line
