### ISSUE TITLE
I have a problem starting a game error CN64system::EmulationStarting: Exception caught File: N64system\N64system.cpp Line: 680

### ISSUE THREAD

**Issue by CosmicJaxx** [project64/project64#2148]
When i start a game i get an error and i dont know how to fix.

the error is: 
CN64system::EmulationStarting: Exception caught
File: N64system\N64system.cpp
Line: 680

I hope you guys can help me !

**Comment by Squall-Leonhart** [comment]
nobody can help you.

**Comment by dftf-stu** [comment]
@CosmicJaxx: if you want assistance, you'll need to provide a bit more information!

For example:
- What _Windows_ is on your computer?
- What version of _Project64_ are you using?
- Does this affect every game you try, or only certain ones?

**Comment by project64** [comment]
this is not a support forum, try discord
