### ISSUE TITLE
N-Rage lock mouse

### ISSUE THREAD

**Issue by Predator82Germany** [project64/project64#215]
When I´m in game & then go to input-settings & finish that with click on ok the message with "Mouse is locked" appears

Fixable?

**Comment by AmbientMalice** [comment]
Press TAB to toggle mouse lock.

**Comment by Predator82Germany** [comment]
I know how to toggle
Only automatic lock bothers me

**Comment by Frank-74** [comment]
When I click TAB to unlock, it only makes the mouse viewable outside the project64 window.  From then on, the mouse is still invisible in project64.  Makes using the menus next to impossible with an invisible mouse.

**Comment by oddMLan** [comment]
The hotkey should be changeable through the Project64 `Keyboard Shorcuts` config panel.

#336 
If this gets implemented this would solve the issue

But still I agree the default hotkey should be changed or disabled.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
