### ISSUE TITLE
1964 Demo by Steb (PD) :: Address Error

### ISSUE THREAD

**Issue by cxd4** [project64/project64#217]
_1964 Demo by Steb_ raises constantly the "Address Error" MIPS exception with the interpreter.

```
[5C450380-4B5CB6E6-C:0]
Good Name=1964 Demo by Steb (PD)
Internal Name=1964 test rom
Status=Unsupported
```

Switch to Interpreter, of course.

**Comment by cxd4** [comment]
Possibly related, as it is the same exact error:  https://github.com/project64/project64/issues/352

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
