### ISSUE TITLE
Boot Emu by Jovis (PD) hung up with no feedback

### ISSUE THREAD

**Issue by cxd4** [project64/project64#218]
At the very least, the debugger should have some kind of feedback.  I'm unfamiliar with any internals of CIC boot code though, but if some sort of peripheral or serial communication is attempted that isn't being emulated there could at least be an error for it.

Instead it's just a black screen with any settings and running everywhere.  Using my version of angrylion, I can see that no vertical interrupts have been sent, and no DMAs have ever been made to update any VI registers.

```
[2D15DC8C-D3BBDB52-C:0]
Good Name=Boot Emu by Jovis (PD)
Internal Name=h¼
Status=Unsupported
```

Daedalus console yields:
![jovis_bootemu](https://cloud.githubusercontent.com/assets/1396303/6510887/fc63428c-c336-11e4-9c5c-b62a48f84bfc.png)
Enter `go` in the console to start the audio thread past the boot code, and the debugger resumes:

```
0/51 variables identified
Reading directly from PI ram: 0xbfc007fc!
Reading Control Byte 0x00000000
Writing directly to PI ram: 0xbfc007fc:0x00000008!
Writing to Control Byte
[hung up at this point]
```

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
