### ISSUE TITLE
Deleting an Enhancement does not work

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#2180]
Steps:
- Open a game, then Go to Enhancements
- Right click -> Add Enhancement...
- Name it whatever you want
- Now try to right click, Delete

Result: Nothing will happen
Expected: The Enhancement will be deleted from the list.

**Comment by project64** [comment]
does this fix it for you?
https://github.com/project64/project64/commit/05bf0f9fb49263708c57568bde65f3462bef3d5e

**Comment by oddMLan** [comment]
Yes!
