### ISSUE TITLE
Windows 7 'GetSystemTimePreciseAsFileTime' error

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#2188]
![IMG_20220207_101230_884](https://user-images.githubusercontent.com/7278372/152837558-7c817058-6d42-4d97-90a2-995a20aafe37.jpg)

I suspect #2110 is what broke Windows 7
https://github.com/latex-lsp/texlab/issues/101 mentions this problem having to do with the Duktape library.

**Comment by Squall-Leonhart** [comment]
whats broken exactly?, its fine here.

**Comment by oddMLan** [comment]
> whats broken exactly?, its fine here.

Might need to enable the debugger first. And using the latest nightly build.
