### ISSUE TITLE
No "Nintendo 64" on Ocarina of Time 1.0

### ISSUE THREAD

**Issue by Alexn64gamer0712** [project64/project64#2201]
![image](https://user-images.githubusercontent.com/100775660/156363796-b4ed0815-8d47-4503-bcc6-37ca724fe48f.png)

this is what I see when loading the Ocarina of Time NTSC 1.0 rom in Project64 last dev version. its only the "N" but theres no "Nintendo 64" in the logo I tried at least 3 roms, what causes that?

**Comment by Squall-Leonhart** [comment]
No reproduction.

**Comment by Squall-Leonhart** [comment]
You're not even using a build from this month.

**Comment by Alexn64gamer0712** [comment]
> You're not even using a build

??? what?

**Comment by Alexn64gamer0712** [comment]
This is with GlideN64....

![image](https://user-images.githubusercontent.com/100775660/156368788-a95cf29e-1eec-49b6-9388-9cade56323ec.png)

**Comment by Alexn64gamer0712** [comment]
and this

![image](https://user-images.githubusercontent.com/100775660/156369353-0da7c7e0-eb13-4aa6-a272-32a8707790ef.png)
 
whit the default Project64 video plugin...

**Comment by Squall-Leonhart** [comment]
Please stop opening bugs for technical support involving unbundled plugins and configuration issues.

**Comment by Alexn64gamer0712** [comment]
Ok, do not solve the bugs then, and let the emulator in a shitty state for everyone..... thanks

**Comment by flagrama** [comment]
You're reporting for a version of the emulator that is probably going to have massive changes because it is focusing on improving accuracy. Things will break for a while.

Beyond that, you just seem to have hardware that doesn't agree with the built in plugins. Angrylion, Glide64 and Gliden64 require at least passable OpenGL driver support. If your hardware is too old to use them that's a you issue and you should use Jabo instead. Even though it has its own problems, it's old enough that most older hardware will run it.

**Comment by Alexn64gamer0712** [comment]
> You're reporting for a version of the emulator that is probably going to have massive changes because it is focusing on improving accuracy. Things will break for a while.
> 
> Beyond that, you just seem to have hardware that doesn't agree with the built in plugins. Angrylion, Glide64 and Gliden64 require at least passable OpenGL driver support. If your hardware is too old to use them that's a you issue and you should use Jabo instead. Even though it has its own problems, it's old enough that most older hardware will run it.

MSI RTX 2060 ti, Intel I7 9700k 4,0 (overclocked) 8 cores, 8 threads, 64mb Ram ddr4 corsair vegeance, corsair SSD MP600 2tb, does that counts as hardware "too old"

**Comment by Squall-Leonhart** [comment]
you would have to be rendering on the 9700k's IGP to be experiencing whatever the nightmare is in that PJ64 Video screenshot.

**Comment by flagrama** [comment]
Agreed. Windows installs terrible drivers for Intel integrated cards. You have to manually download a driver update to actually get decent OpenGL support on them. Probably better to ensure Windows is using the correct GPU for PJ64 instead.

**Comment by Alexn64gamer0712** [comment]
> Agreed. Windows installs terrible drivers for Intel integrated cards. You have to manually download a driver update to actually get decent OpenGL support on them. Probably better to ensure Windows is using the correct GPU for PJ64 instead.

I dont use the integrated graphics chipset, I use the Nvidia RTX 2060 ti, which supports OpenGL 4.6 with no problem at all

**Comment by Squall-Leonhart** [comment]
you clearly aren't using the geforce, because all those screenshots are issues specific to buggy intel drivers.

**Comment by Alexn64gamer0712** [comment]
> you would have to be rendering on the 9700k's IGP to be experiencing whatever the nightmare is in that PJ64 Video screenshot.

nope, using RTX 2060 ti all the time, I have never used the IGP since I bought my pc

**Comment by Alexn64gamer0712** [comment]
> you clearly aren't using the geforce, because all those screenshots are issues specific to buggy intel drivers.

as said before, never ever have used the integrated graphics, only the RTX 2060 ti

**Comment by flagrama** [comment]
Windows uses hybrid graphics. You are usually using the IGP whenever you're not running games. Sometimes games don't properly start using the dGPU.

**Comment by Alexn64gamer0712** [comment]
> Windows uses hybrid graphics. You are usually using the IGP whenever you're not running games. Sometimes games don't properly start using the dGPU.

I have set in the MSI Z490 MotherBoard the RTX as the only graphics device, deactivating the onboard Intel Graphics, so.... is there any way its still using those after doing that?

![image](https://user-images.githubusercontent.com/100775660/156389907-23143891-a767-4d4a-8362-67b86759b6a1.png)

**Comment by Squall-Leonhart** [comment]
if it still shows in device manager, yes.

**Comment by Alexn64gamer0712** [comment]
> 

im calling MSI support right now to ask about that

**Comment by project64** [comment]
> Ok, do not solve the bugs then, and let the emulator in a shitty state for everyone..... thanks

if the issue is the emulator then there is something I can fix, if it is an issue with the plugin then the plugin needs to fix it there is nothing I can do about it.

If there is a bug in someone else's plugin it is not going to change the state of the emulator.

**Comment by DerekTurtleRoe** [comment]
> Ok, do not solve the bugs then, and let the emulator in a shitty state for everyone..... thanks

Like Zilmar said, if the issue is with plugins that we don't have control over, then we can't do anything about it.

I'm willing to help you diagnose your problem if you would like, but a GitHub issue probably isn't the place for that. The Discord would be a better place to ask for this kind of help I think.

Also make sure Windows and your graphics drivers are updated before testing to make sure it isn't one of those causing issues as well.
