### ISSUE TITLE
FastSP\SP Hack in RDB?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#221]
Although I can disable this setting in PJ64's game setting menu, altering the configuration file, I can't get the change to apply to the RDB directly. I wonder whether something is broken there?

I've tried SP Hack=False\No\0 and also FastSP=False\No\0

**Comment by Frank-74** [comment]
It should be 'Fast SP', with value Yes or No.
Maybe this will help.

'''
RDB Option		  Default Value|Other Value(s)
Good Name		=
Status			=
Core Note		=
Plugin Note		=

// Config:
RDRAM Size		= 4|8
Save Type		= First Save Type|4kbit Eeprom|16kbit Eeprom|FlashRam|Sram
Counter Factor		= 2|1|3|4|5|6
ViRefresh		= 2200|?
AiCountPerBytes		= 500|?
32bit			= Yes|No
Use TLB			= Yes|No
Delay DP		= Yes|No
Delay SI		= No|Yes
Fixed Audio		= 1|0
Sync Audio		= 1|0
Audio Signal		= No|Yes
ScreenHertz		= 60|50

// Recompiler
Cpu Type		= Recompiler|Interpreter|SyncCores
FuncFind		= 1|2			// 1=Physical 2=Virtual
Reg Cache		= Yes|No
Linking			= On|Off
Fast SP			= Yes|No

// Self Mod Methods
SMM-Cache		= 1|0
SMM-PI DMA		= 1|0
SMM-TLB			= 1|0
SMM-FUNC		= 1|0
SMM-Protect		= 0|1
SMM-StoreInstr		= 0|1

// Plugins
HLE Audio		= 0|1
HLE GFX			= 1|0
Culling			= 0|1
Direct3D8-Direct3DPipe	= 0|1
Direct3D8-DesiredAspect	= 0|1
Direct3D8-2xSai		= 0|1
Direct3D8-ForceFilter	= 0|1
Direct3D8-Brightness	= 0|0-30
Dsound-SyncAudio	= 0|1

// Other
Rom In Memory		= 0|1
TLB: PAddr Start	= 0|?
TLB: Vaddr Len		= 0|?
TLB: Vaddr Start	= 0|?'''

**Comment by AmbientMalice** [comment]
"Fast SP=No" works a treat. Thanks a lot, @Frank-74
