### ISSUE TITLE
[Bug]: Project64-Dev-4.0.0-5759-80d8e6e and higher has major issues with Resetting

### ISSUE THREAD

**Issue by IronYoshi64** [project64/project64#2211]
### Expected behavior?

Pressing F1 or doing a Soft Reset and/or Hard Reset should reset and not completely crash/freeze the emulator.

### Actual behavior?

When using Project64 Dev build 4.0.0-5759-80d8e6e or higher, Resetting any game freezes/crashes Project64.

### Steps to reproduce the problem

1. Just load up any game with Project64-Dev-4.0.0-5759-80d8e6e or higher.
2. Try to do a soft reset or hard reset.
3. Project64 will completly freeze/crash the game that is running.

### Error messages?

No error messages.

### What game were you playing?

Title: Super Mario 64 Zelda, any game

Nintendo 64 game or Nintendo 64 Disk Drive: N64

### Specifications and build details

Project64: Project64-Dev-4.0.0-5759-80d8e6e 32bit

OS: Windows 10 21H2

CPU: Ryzen 7 3800X

RAM: 16GB (2x8) 3200

Graphics: GeForce GTX 1650 OC

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): GLideN64, every plugin I tried
Audio plugin: Project64 Audio
Input plugin: Default input and NRage
RSP plugin: default RSP

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment]
@IronYoshi64 I can soft and hard reset all day in all of the games in my collection and it works fine. Have you tried a fresh install?

EDIT: Never mind, it's happening to me too.

**Comment by Squall-Leonhart** [comment]
Confirmed, with default plugins the Vi/s accelerate into infinity (or as fast as the cpu allows)
with Azimer audio, and audio sync it stays at 60Vi/s but never boots.

**Comment by DerekTurtleRoe** [comment]
Yeah, for me it softlocks when soft or hard resetting the console at any point, plugins don't matter. Console then sits at 100% CPU usage on a black screen infinitely.

My guess is one of the recent core updates has broken resetting the emulated console.

**Comment by Squall-Leonhart** [comment]
Most likely the changes to Source/Project64-core/N64System/Recompiler/x86/x86RecompilerOps.cpp

![image](https://user-images.githubusercontent.com/1098176/158043759-170c922a-3582-4c57-8fc6-4b433aa25743.png)

**Comment by IronYoshi64** [comment]
Yeah I even did a fresh clean spot right from default. and Yeah still does it. and what i did is just put the Project64.exe from 5758, and it worked fine.

**Comment by project64** [comment]
this should fix it
https://github.com/project64/project64/commit/df422238c9635ffbccb5832bc2dac2d7cdf84e8f

**Comment by project64** [comment]
@Squall-Leonhart  is correct where the code is wrong, it is passing TempValue, but using the value from m_TempValue

**Comment by Squall-Leonhart** [comment]
confirmed fixed

**Comment by IronYoshi64** [comment]
Awesome job guys! I grabbed Project64-Dev-4.0.0-5767-d7e732a bundle and it is now fixed! I guess I can Close this now. Thanks.
