### ISSUE TITLE
[Bug]: Project64 doesn't run any ROMs since installation of Windows 11

### ISSUE THREAD

**Issue by SirBobb** [project64/project64#2213]
### Expected behavior?

Be able to use the emulator to play N64 games like I did for the past few months

### Actual behavior?

Used to be able to run Super Mario 64 on Project64 2.3 a few months back on Windows 10. Then updated to Windows 11 and I can't opens ROMs anymore.

Tried changing installation directory, having it in portable mode, switching video plugin, changing options in video settings and using different ROMs, using different Project64 versions

Didn't change any hardware from when Project64 worked to now

Tried 2 different Super Mario 64 ROMs and tried a Mario Kart 64 ROM. Gives me an error every time I open the ROM. Tried Project64 public 2.3, 3.0.1 and the latest development version

### Steps to reproduce the problem

1. Open Project64 on Windows 11
2. Click Open ROM
3. Choose the ROM
4. Get Error and a Black Screen in the program

### Error messages?

![image](https://user-images.githubusercontent.com/35657425/158247711-786217ac-c305-4fd2-9015-b1c7c7d1c8e7.png)

### What game were you playing?

Title:

Nintendo 64 game or Nintendo 64 Disk Drive:

ROM information: (File > ROM info, or context menu > ROM information in the ROM
list)

Save type: (Attach game save or save state here)

Original or modified ROM?:(attach patch here)

### Specifications and build details

Project64: 3.0.1-5664-2df3434 and Dev-4.0.0-5767-d7e732a and I don't know which 2.3 version I had before. It uses 32-bit but I didn't really get a choice and don't know how to change it to 64-bit

OS: (include version and OS build number using WinVer): Windows 11 Pro 21H2 Build 22000.556

CPU: Ryzen 5 3600

RAM: 12GB (8GB 2666MHz, 4GB 2133MHz)

Graphics: Radeon RX 580

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): 
![image](https://user-images.githubusercontent.com/35657425/158248901-4296dc6f-64ea-4f5c-b5c0-af945f23ba28.png)
Audio plugin: 
![image](https://user-images.githubusercontent.com/35657425/158248943-ba025136-e1c1-4e25-af8a-16202a1fb7d7.png)

Input plugin: 
![image](https://user-images.githubusercontent.com/35657425/158248993-5792930f-2ed6-4d58-a587-7f31fdd16ab6.png)

RSP plugin: 
![image](https://user-images.githubusercontent.com/35657425/158249029-937a1922-cc24-4479-a1b7-2114c594441e.png)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
don't mix ram, get 2 sticks of equivalent size.

Windows 11 is just windows 10 in a new skin and stupider uefi restrictions, i can think of no reason it wouldn't run pj64 that doesn't involve a system fault.

**Comment by DerekTurtleRoe** [comment]
@SirBobb Have you tried a development build?

**Comment by SirBobb** [comment]
@DerekTurtleRoe I did, but don't worry the issue fixed itself after updating Windows
