### ISSUE TITLE
[Bug]: Frequent crashes in Paper Mario on Windows 11 due to TLB entries not working

### ISSUE THREAD

**Issue by MrCheeze** [project64/project64#2218]
### Expected behavior?

Jumping on enemies should not show the in-game crash screen.

More specifically: When Mario lands on the ground after hitting an enemy with a jump attack, a dust particle loads, This creates a TLB mapping for address E000C000-E000CFFF, and then jumps to some TLB mapped code at E000C160, which executes without any problems.

### Actual behavior?

In-game, the crash screen appears:

![image](https://user-images.githubusercontent.com/6541413/160011665-8ee76524-26b3-4715-a8b6-3d06738bbbef.png)

The behaviour in the game is exactly what it would be if the TLB mapping had not been created at all - it behaves as if E000C000 isn't mapped to anything. I also see the same thing in the memory viewer window, it acts like there is no mapping.

Strangely, the TLB debugger *does* show the mapping that was supposed to be created, even though the ingame behaviour and memory viewer behave as though it doesn't exist.

### Steps to reproduce the problem

~~Play the game normally through the prologue, using Mario's jump attack and Goombario's bonk to attack enemies. Some of the time (not too rarely) the crash screen will show.~~ EDIT: Just wait on the title screen instead, it will always crash during the demo battle with the Monty Moles.

It does at least seem to be deterministic - I've made a savestate right before the crash happens, and loading the state always leads to the crash.

There are reportedly many other ways that the crash can happen, though the visible result will always be a crash screen with "PC: E0XXXXXX" in the top left.

### Error messages?

Only the ingame crash.

### What game were you playing?

Paper Mario (USA)

The issue also happens frequently in rom hacks for the game.

### Specifications and build details

Project64: 3.0.1.5664-2df3434 32 bit

OS: Windows 11 21H2 (OS Build 22000.556)

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

(default)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment]
@MrCheeze Can you try this on the latest development build of Project64?

**Comment by MrCheeze** [comment]
Downloaded Project64-Dev-4.0.0-5775-1eda1bb . The issue still happens, in fact it always happens just from waiting on the title screen for the battle demo to play. So it's much faster to reproduce the issue than I originally thought. (The demo crashes in 3.0.1 too.)

![image](https://user-images.githubusercontent.com/6541413/160026132-93c07b3f-8e13-4c2d-a6a6-a59a6e72049d.png)

From what I've heard, the problem is supposedly specific to Windows 11, though.

**Comment by DerekTurtleRoe** [comment]
@MrCheeze Was this with the CPU recompiler or can this be reproduced with the CPU interpreter as well?

**Comment by MrCheeze** [comment]
Still happens after switching to interpreter.

**Comment by DerekTurtleRoe** [comment]
@MrCheeze Hm, I have heard of issues with the TLB in Project64 so its definitely possible there is a bug.

Lemme do some testing and I'll report any info I find.

**Comment by DerekTurtleRoe** [comment]
@MrCheeze Hm, In can't reproduce this issue on Windows 10. I tried many plugins, different region ROMs, etc.

Do you have Windows hardware GPU scheduler enabled?

**Comment by MrCheeze** [comment]
It was enabled, but after turning it on and rebooting, the issue is still there like before.

In the likely case that the issue can't be triggered without Win11, is there something I can test on my machine to determine what exactly is going wrong?

**Comment by DerekTurtleRoe** [comment]
@MrCheeze I only can test Windows 10, and in every test case that I tested the issue didn't occur. My educated guess is that it has something to do with Windows 11. Either that, or perhaps Data Execution Prevention and/or some of the Windows 11 kernel changes.

If you have access to a Windows 10 machine or could create a VM and test it there, then that might help shed some light on the issue being exclusive to Windows 11.

But I tested everything on Windows 10 and had no issues.

Further adding to my belief of this is that other emulators and projects have had other strange behaviors that only exist on Windows 11. Most of the time they weren't able to "fix it" necessarily, but sometimes it could be worked around depending on the exact cause. Windows 11 has a lot of CPU security mitigations, kernel changes, and more security and hardware-level requirements, so any of those could contribute to issues with software meant to run on systems without any of those things, or even just in general.

**Comment by MrCheeze** [comment]
Managed to launch Project64 with a debugger and I think I have some insight into what's going on here, now.

In [MemoryVirtualMem.cpp](https://github.com/project64/project64/blob/1eda1bb/Source/Project64-core/N64System/Mips/MemoryVirtualMem.cpp), m_TLB_ReadMap and m_TLB_WriteMap contain (presumably for performance reasons) a map of the value that should be added to a *N64 vaddr* to get the *actual PC address* of the backing memory. These arrays use 0 as a special value meaning "invalid".

The logic error is that 0 is also a perfectly valid value for the read/write maps to contain when there *is* a TLB mapping. In my case...

1. Project64/Windows allocates m_RDRAM at PC address DFE70000
2. Paper Mario sends a TLB request saying to map N64 vaddr E000C000 to N64 physical address 0019C000
3. From Project64's perspective, this means it should map N64 vaddr E000C000 to PC address DFE70000+19C000 = E000C000. These values in totally unrelated address spaces are the same, by sheer coincidence!
4. Project64 stores E000C000-E000C000 = 0 into m_TLB_ReadMap and m_TLB_WriteMap. Because the value is zero, Project64 therefore immediately forgets that it did this and thinks the TLB mapping doesn't exist.

The logic error was (I think) always present, but I guess memory allocation behaviour happens to be different on win11 for this unfortunate coincidence to happen more often in practice?

![image](https://user-images.githubusercontent.com/6541413/160049996-b0d9b1da-8ef7-4fad-85a2-9e87065fdb81.png)

**Comment by Squall-Leonhart** [comment]
RMA your cpu, it's defective.

**Comment by DerekTurtleRoe** [comment]
@MrCheeze What hardware are you running, actually?

**Comment by MrCheeze** [comment]
CPU shouldn't matter but it's an Intel i7-10750h. I do have 16GB of ram, which is presumably more relevant.

The difference in behaviour between Windows 10 and 11 is, I assume, related to what addresses [VirtualAlloc](https://github.com/project64/project64/blob/b0b6c03eea6ea3ef5bddca32de5fdebd94b0be7e/Source/Common/MemoryManagement.cpp#L54) returns in practice when allocating space for m_RDRAM. Remember the bug manifests when (real PC address of a RDRAM page) == (N64 vaddr that should be mapped to that page). 

The logic bug in MemoryVirtualMem has always been there and should probably be fixed for all platforms. Still, one more thing I did try doing was compiling with LargeAddressAware=false to see what happened. Unsurprisingly, m_RDRAM allocated at a lower address (4D4A0000 instead of DFE70000) and so it didn't end up overlapping with the N64 Vaddrs that Paper Mario uses, and the game didn't crash. Not really a proper fix though.

**Comment by DerekTurtleRoe** [comment]
@MrCheeze Hm, alright. I'm not sure how to properly fix this if I'm being honest. In the meantime as we investigate and research the issue we'll keep this open for sure.

@project64 Do you happen to have an idea for a solution?

**Comment by ethteck** [comment]
> RMA your cpu, it's defective.

this is an insane way to respond here in a legitimate issue discussion thread

**Comment by Squall-Leonhart** [comment]
nobody asked you, butt out and rack off.

**Comment by ethteck** [comment]
It's clear that 0 isn't a good value here to mean "invalid", so a couple of ideas for how to better fix this:
* Use -1 instead of 0 as the indicator for "invalid" (should never collide with anything since tlb mapped addresses are 16-byte aligned),
* Use a separate data structure to keep track of the invalid (or valid) mapping

> nobody asked you, butt out and rack off.

It was a rude, unhelpful, and totally irrelevant reply (as is the one you just made). Is this considered acceptable discourse for discussions in this project @project64 ?

**Comment by Squall-Leonhart** [comment]
> It does at least seem to be deterministic - I've made a savestate right before the crash happens, and loading the state always leads to the crash.

a save state is a snapshot of memory so anything that already has gone wrong is part of the state.

> @MrCheeze I only can test Windows 10, and in every test case that I tested the issue didn't occur. My educated guess is that it has something to do with Windows 11. Either that, or perhaps Data Execution Prevention and/or some of the Windows 11 kernel changes.

Windows 11 hasn't changed anything where DEP is concerned, it is only applied to essential windows apps and services that opt-in to the feature.

Cannot replicate this at all, either its already fixed from the OS end, or the cpu is flipping bits.

**Comment by ethteck** [comment]
This is a legimate problem that multiple people including myself have reproduced. If you're actually saying you think our cpus are "flipping bits", I'm stunned. MrCheese explained the issue thoroughly and it seems like all the information given is just being completely ignored

**Comment by Squall-Leonhart** [comment]
debugging on questionable hardware has no value.

The fact that LAA off changes the behavior is suspicious because for LAA to matter you would actually have to approach 2GB's of virtual addressing in the first place, it doesn't change the mapping behavior of bits below 2GB, the compiler setting changes a single bit

**Comment by ethteck** [comment]
How is a modern windows computer "questionable hardware"?

**Comment by Squall-Leonhart** [comment]
> How is a modern windows computer "questionable hardware"?

If it hasn't been put through a week Memtest and IBT, nothing is guaranteed "OK"

**Comment by ethteck** [comment]
It happens for everyone in the paper mario modding community who tries to play this game on Windows 11. You're saying you won't consider this issue valid until every single person runs thorough hardware tests, despite all the facts clearly laid out here? Absolutely ridiculous.

**Comment by MrSapps** [comment]
> debugging on questionable hardware has no value.
> 
> The fact that LAA off changes the behavior is suspicious because for LAA to matter you would actually have to approach 2GB's of virtual addressing in the first place, it doesn't change the mapping behavior of bits below 2GB, the compiler setting changes a single bit

I am confused, are you trolling? The issue is clearly that x-y = 0 and 0 is used to mean "not mapped" just because you think that the value of y can never be equal to x doesn't mean there is no bug.

IMO unless its a massive performance issue its safer and more obvious to have a separate flag for the mapped/valid check.

**Comment by Squall-Leonhart** [comment]
Nothing is clear until appropriate testing is performed with the Kernels memory manager setup to identify an issue.

@DerekTurtleRoe 
Behavior that changes based on whether LAA is enabled or not can usually be picked up by changing the Kernel memory allocator to Top-Down mode.

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management]
"AllocationPreference"=dword:00100000

**Comment by ethteck** [comment]
the `LargeAddressAware=false` was just a debugging step from MrCheeze - it wasn't a theory as to the root cause of the issue

**Comment by MrSapps** [comment]
> Nothing is clear until appropriate testing is performed with the Kernels memory manager setup to identify an issue.
> 
> @DerekTurtleRoe Behavior that changes based on whether LAA is enabled or not can usually be picked up by changing the Kernel memory allocator to Top-Down mode.
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management] "AllocationPreference"=dword:00100000

What is clear is that there is a bug when VirtualAlloc returns an address that when subtracted from the read/write location results in 0, when offset 0 in the allocated space is in fact valid. You can actually request VirtualAlloc to allocate at a specific address (although that can fail) which would easily reproduce the problem on any version of Windows. I don't think you understand the previous information as given by MrCheeze.

**Comment by MrCheeze** [comment]
Squall - Project64 already allocates with MEM_TOP_DOWN, presumably for the purpose of catching large address bugs such as this one. But of course the bug is there anyway, this is just the reason we can reliably reproduce it.

I agree with the earlier comment, that either having a separate table of "is the TLB mapping valid?" flags, or using a sentinel like -1 that's impossible to get naturally, would make sense.

**Comment by ethteck** [comment]
I created a PR which fixes the issue with the "-1" solution proposed above.

**Comment by project64** [comment]
m_TLB_ReadMap[VAddr >> 12] + VAddr = Memory Ptr
m_TLB_ReadMap[VAddr >> 12] I treat as a random value in essences

the problem is when Memory Ptr -  VAddr  == 0

so moving the memory at all will hide the problem, having it -1 probably will fix the problem cause I use values aligned to the bottom 2 bits being 0.

Since I allocate the memory for the map at start up, it would be very constant on machines that show this problem, and near impossible to reproduce on other machines.

**Comment by ethteck** [comment]
@project64 I'm unfortunately seeing this again on latest development build as well as my own debug build locally on the latest commit:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/2985314/217504683-1cd69504-86fa-4a05-8c7f-641edb4322b0.png">
Is there any further info I can provide to help with debugging? I'll keep scouring the source code to see if I can remember how I debugged this last time.

**Comment by ethteck** [comment]
oh wait a minute. the version I'm running in that screenshot is extremely old...am I maybe building the wrong branch or something? disregard for now

**Comment by Squall-Leonhart** [comment]
develop should get you 4.0

**Comment by DanteCoder** [comment]
Are you guys still working on this? I tried playing Paper Mario 64 on Windows 11 and this bug is very annoying. Playing on version 2.3.2.202 does the trick but I really miss the new graphic options and enhancements on v3.0

**Comment by JoshTheMadLad** [comment]
Dont mean to be a guy that necros, however as stated above, this is also happening for me on v 3.0.

Did the exact same thing as before and just waited for the mole rats in the intro scene and its a 100% replicable crash.

![image](https://github.com/user-attachments/assets/b27287be-1ae2-4a52-84e8-f6695a7d6853)

**Comment by flagrama** [comment]
Yes, 3.0.1 has the issue. You need to get one of the 4.0 versions that work to have that fixed. dftf-stu has been keeping track of which ones work for him here: https://github.com/project64/project64/issues/2382#issuecomment-1971453666
