### ISSUE TITLE
[Bug]: White Screen

### ISSUE THREAD

**Issue by simatalk** [project64/project64#2229]
### Expected behavior?

So I want to play some SM64 roms, they are weegeepies but I can't get them to load, I'm pretty sure it's not a rom problem because I tried multiple

### Actual behavior?

<img width="315" alt="image" src="https://user-images.githubusercontent.com/92042656/164943618-205bb32d-3175-41a6-bd61-6969591c2063.png">

### Steps to reproduce the problem

1. Run A SM64 rom
2. Wait for the Big Mario head that tells you to start
3. press start
4. bug
...

### What game were you playing?

Title: SM64 Pack from WeeGeePie

Nintendo 64 game or Nintendo 64 Disk Drive:

ROM information: (File > ROM info, or context menu > ROM information in the ROM
list)

Save type: (Attach game save or save state here)

Original or modified ROM?:(attach patch here)

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)

OS: (include version and OS build number using WinVer):

CPU:

RAM: 16 GB

Graphics:

### Using included plugins

- [ ] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE):
Audio plugin:
Input plugin:
RSP plugin:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment]
@simatalk Please fill out the rest of the information in the issue form so we can better assist you.

**Comment by Squall-Leonhart** [comment]
needs expansion pack set for most mario64 hacks.

**Comment by dftf-stu** [comment]
@simatalk: to expand upon what Squall-Leonhart advised, encase you're unsure what to do, right-click on one of the ROMs you're having an issue with, then click "Edit Game Settings" and change the "Memory Size" dropdown from "4MB" to "8MB", then click [OK].

Then try the ROM again -- might help to also close, then re-open, the _Project64_ app after making the changes, as you might have a crashed one still running in the background.
