### ISSUE TITLE
[Bug]: Majora's Mask saves not working

### ISSUE THREAD

**Issue by GhostlyDark** [project64/project64#2230]
### Expected behavior?

Majora's Mask should save and load files.

### Actual behavior?

Regression caused by 2f1074a28718b55b01aa789045950c216dc4a1b5
Loading an existing .fla save doesn't work. Without an existing save, creating a new file (e.g. File 1) and restarting the game reveals that the save isn't loading, as File 1 is going to be empty again.

### Steps to reproduce the problem

1. Boot up Majora's Mask (USA)
2. Create File 1
3. Restart the game
4. Be angry about File 1 not existing

### What game were you playing?

Title: Majora's Mask (USA)

Nintendo 64 game or Nintendo 64 Disk Drive: N64

ROM information:
MD5 - FC39208428BCAE70508E633451C11CC0

### Specifications and build details

Project64: Dev-4.0.0-5787-2f1074a
(Dev-4.0.0-5786-1975a99 works as intended)

OS: Windows 10 x64 21H1

CPU: Ryzen 9 3900X

RAM: 128 GB RAM

Graphics: Nvidia GTX 1080 Ti

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin: GLideN64 HLE
Audio plugin: Default
Input plugin: Default
RSP plugin: Default

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by project64** [comment]
the dma was getting the wrong length and since it was unaligned was not trying to write, but the complaint only appeared with debugger enabled.

this should fix it:
https://github.com/project64/project64/commit/4f07f52fed445f666325954b31c179c36a5cf50d

**Comment by GhostlyDark** [comment]
Confirmed. Thank you for the quick bug fix.

**Comment by project64** [comment]
Sorry about breaking it .. while I am changing things, I am trying to keep the changes small and trying to make sure I do not break things, tho I failed this time.
