### ISSUE TITLE
[BUG]: PAL (European) games broken in latest v4.0.0.5802 (Dev) release

### ISSUE THREAD

**Issue by dftf-stu** [project64/project64#2235]
### Expected behavior?

I have downloaded the latest Dev build of Project64, from https://www.pj64-emu.com/nightly-builds
At this time, that is **Dev-4.0.0-5802-d25314c** released on 16 May 2022

I expected that every ROM I currently have would work without issue, just as they did in the previous Dev build, "Dev-4.0.0-5795-718d7e0", released on 9 May 2022

### Actual behavior?

In the latest **Dev-4.0.0-5802-d25314c** build, released 16 May 2022, _every single_ European (PAL) ROM I tested now crashes

Those same ROMs all continue to work fine in the previous build, Dev-4.0.0-5795-718d7e0, released 9 May 2022

I made-sure to extract the latest Dev release into its own folder, so there are no old settings leftover, and have tried rebooting my PC.  As the ROM files work fine in the previous build, I cannot see that they are the issue, but some-sort of change that has happened in the code between this Dev release, and the previous one

Also, two things to note:

- **The only USA ROM I currently have WORKS FINE**, that being _Banjo-Kazooie_.  ONLY PAL (European) ROMs cause the latest Dev release to crash.
- As a workaround, if you go into Options > Configuration > Advanced and tick "Always use interpreter core" this then allows ALL the PAL (European) ROMs to work-again in the latest Dev release without-issue, but obviously w-a-y slower, which is not ideal.

### Steps to reproduce the problem

1. Download the latest ZIP file of the v4.0.0.5802 (Dev) build of Project64
2. Extract to a folder where you have full-write permissions
3. Choose "Project64 (for older PCs)" as the graphics type
4. Do not change any default setting
5. Test a PAL (Europe-territory) ROM
6. Observe that _Project64_ crashes
7. Repeat the same steps on the previous version, v4.0.0.5795 (Dev), using the exact-same ROM files
8. Observe that _Project64_ DOES NOT crash

### Error messages?

Error messages vary by-game; some have no error, others either show "Unknown memory action" or "Fatal error"

Screenshot:
![Project64_Testing](https://user-images.githubusercontent.com/83965343/169285499-e41b1c0e-5c5e-4511-b9f1-879d42432403.png)

### What game were you playing?

Titles:
**Banjo-Kazooie (USA)** (MD5: D3E08495AACF2A9DC3B4BA0BA4093516)
**Banjo-Tooie (EUR)** (MD5: 53DC9E0A785E36D724555D046AD23E68)
**Gex 3 - Deep Cover Gecko (EUR)** (MD5: A50E8217CC0B14EF942770E3FDE87D49)
**Gex 64: Enter the Gecko (EUR)** (MD5: 80C6CF55C59F5DA2FC9A139DFB803AB4)
**Tax Express (EUR)** (MD5: E53B8573D54E5B4694A77FD1DD3FFFB0)

### Specifications and build details

**Project64**: v4.0.0.5802 (32-bit) and v4.0.0.5795 (32-bit)
**OS**: Windows 10 Home Version 21H2 (OS Build 19044.1706) - AMD64 kernel version; non-ARM
**CPU**: Intel Core i3
**RAM**: 8GB
**Graphics**: Integrated-graphics only

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): Project64 Video Plug-In, "Graphics HLE" checked
Audio plugin: Project64 Audio Plug-In
Input plugin: Project64 Input Plug-In
RSP plugin: RSP plugin Dev-4.0.0.5802-d25314c

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by dftf-stu** [comment]
On a per-game basis, on Project64, v4.0.0.5802 (Dev), with "Always use interpreter core" unchecked:
- **Banjo-Kazooie (USA)**: works fine
- **Banjo-Tooie (EUR)**: status-bar says "Emulation started", but screen is just black with no sound; no crashes, but no game
- **Gex 3 - Deep Cover Gecko (EUR)**: immediately goes to "Fatal Error: stopping emulation", game doesn't even start
- **Gex 64 - Enter the Gecko (EUR)**: immediately goes to "Fatal Error: stopping emulation", game doesn't even start
- **Tax Express (EUR)**: after the language-select screen, "Unknown memory action, Emulation stopped" error

All "EUR" games above ONLY work in v4.0.0.5802 (Dev) if "Always use interpreter core" option is checked, but much-slower.

All the "EUR" games above continue to work without-issue in the previous v4.0.0.5795 (Dev) release of _Project64_.

**Comment by Squall-Leonhart** [comment]
cannot confirm, all games working here.

**Comment by dftf-stu** [comment]
> cannot confirm, all games working here.

Okay, well, thanks for confirming, but that obviously doesn't help me much.  Any troubleshooting you can suggest I can try? As I've said, I have downloaded a fresh ZIP file of the current Dev version, and the previous one, and extracted both to their own folders, so there are no leftover settings.  I'm using the same ROM files, and all four of the European (PAL) ones crash in the latest Dev release (_unless_ "Always use interpreter core" is ticked) but not in the previous one.

The changelog for the most-recent version says the following changed between v4.0.0.5795 and v4.0.0.5802:
- Core: have MemoryValue32 be able to read from rom
- Core: X86 recompile modularize loading address in store/load ops
- Core: make memory reads/write to go through new CMipsMemoryVM::MemoryPtr
- Core: If SMM_PIDMA, clear physical memory code before doing the dma
- Core: x86RecompilerOps rename m_TempValue to m_TempValue32
- Update Japanese translation
- Add config for generic DK64 rom (DK64 Randomizer)

I'm not a developer or coder, so most of them mean nothing to me... how am I to know what is causing the issue?

Thanks

**Comment by Squall-Leonhart** [comment]
I spotted a suspect in one of the recompiler files, it would cause problems with certain games but not others.

**Comment by dftf-stu** [comment]
The **Glide64.log** and **Project64-audio.log** files are both empty, but for **Project64.log** these are the contents:

> 2022/05/19 13:00:30.619 02192,Error,Exception Handler,CMipsMemoryVM::FilterX86Exception,Invalid memory address: 201C001B
> 2022/05/19 13:00:30.619 02192,Error,User Interface,CNotificationImp::DisplayError,Unknown memory action
> Emulation stopped
> 2022/05/19 13:00:58.415 01480,Error,User Interface,CNotificationImp::DisplayError,Fatal Error: Stopping emulation
> 2022/05/19 13:01:33.047 07280,Error,User Interface,CNotificationImp::DisplayError,Fatal Error: Stopping emulation

Not sure if any of that will help, but that's the only log information I can see created.

**Comment by Squall-Leonhart** [comment]
it narrows it down to 1617e63b848f4c9d0c7a1aa55d37e3b173386ff2

**Comment by dftf-stu** [comment]
> it narrows it down to [1fe8fd1](https://github.com/project64/project64/commit/1fe8fd1299871ffae539e341a1e2c8e1513ed411)

Thanks, though I'm afraid code doesn't mean very-much to me, so for-now I'll just continue using the v4.0.0.5795 release as a workaround, given I have no-issues there when running games in "windowed" mode.

Does the change you're linking to mean this is a bug in the code, or an intentional-change that means only newer PCs are now supported?  Is version 4.0.0.5795 now the final one that will be compatible with my system?

**Comment by Squall-Leonhart** [comment]
its a bug in the code, nothing there is affected by system specs.

**Comment by dftf-stu** [comment]
> its a bug in the code, nothing there is affected by system specs.

Okay, thank-you.  I wonder why turning-on "Always use interpreter core" in v4.0.0.5802 works-around the issue?

As an update, I thought I would try unticking "Graphics HLE" (with "Always use interpreter core" also unticked, as is the default) but all the games still crash, so that option _doesn't_ help as a workaround.

**Comment by Squall-Leonhart** [comment]
interpreter doesn't use virtual mem.

**Comment by dftf-stu** [comment]
Have to log-off my PC for a while now, but if any of the developers need me to test anything and report-back, or attach any files, (maybe in _Task Manager_ wait until a crash occurs then right-click on _Project64.exe_ and do "Create dump file" or something), please let me know and I can do this later today.

@Squall-Leonhart: a little off-topic, but just out-of-interest -- when you log a bug-report on here it asks whether you are using the 32-bit or 64-bit release of _Project64_.  Is there actually a 64-bit release available?  I know _DuckStation_ is available for AMD64 and ARM64, and PCSX2 has Intel32 and AMD64 builds, but as far as I was aware, _Project64_ is only available in 32-bit builds?

[Update, March 2024: _PCSX2_ is now 64-bit only; the v1.7.2484 "Dev" build (19 March 2022) was the final 32-bit one -- I wasn't aware they'd dropped-support at the time of writing my comment above.  _DuckStation_ is still supporting ARM64 and AMD64 on _Windows_, and as-of now, _Project64_ still recommends NOT using their 64-bit release.]

**Comment by Squall-Leonhart** [comment]
Eventually there will be.

**Comment by project64** [comment]
this may fix it
https://github.com/project64/project64/commit/f95c0f7ef14eb1cd2159e4f8e88e171b2c49060b

part of the changes in all the changes to memory handling is to remove the usage of structured exception handling, this needs to be done to be able support 64bit version

**Comment by dftf-stu** [comment]
I have just downloaded **Dev-4.0.0-5803-f95c0f7** (20 May 2022) and can confirm all the PAL (European) ROMS now appear to be working again.  Thanks!

**Comment by amergin6699** [comment]
A multitude of European games no longer work again ! 
tested on  Dev-4.0.0-6350-290040d 
exemple : Destruction Derby, Banjo Tooie, Banjo Kazooie, Aerogauge only give emulation started and a black screen. 
The US versions of the same games work
Using the interpreter instead of recompiler allows the games to start, but it's slow on my computer.

**Comment by dftf-stu** [comment]
@amergin6699: the most-recent version that fully-works on my main PC is v4.0.0-6213 from 7 Sep 2023 -- you can [click here](https://www.pj64-emu.com/file/project64-dev-4-0-0-6213-002f2e1) to download it in ZIP format.  Then simply extract the contents of that ZIP into a folder, then double-click "Project64.exe" to run it.

Note that your PC needs at-least Windows 7 or later.  The recent versions don't work at-all on _Vista_, but for _XP_ you can open the file "Project64.cfg" in Notepad, find the line "Enable Discord RPC=1", change it to "Enable Discord RPC=0", then save the file.  I don't think anyone on the development-team still tests on XP though, so there's no guarantee it will work on there fully.

**Comment by Squall-Leonhart** [comment]
These are linked back to the 32bit - Engine optimzation which has been known busted for a good while and already mentioned on #2300
