### ISSUE TITLE
[Bug]: Graphical error during capture

### ISSUE THREAD

**Issue by JerrytheRat** [project64/project64#2239]
### Expected behavior?

Emulator working as expected without attempting capture through discord screen sharing
![noncapture](https://user-images.githubusercontent.com/106937425/172078462-d3af2ef5-e12f-4f3e-933a-0280f4889e05.png)
.

### Actual behavior?

Upon attempting to capture program to share through discord streaming the game appears to mirror its image
![capture](https://user-images.githubusercontent.com/106937425/172078615-404ff4cc-6f7e-49b8-969b-f6b72ecb540e.png)
.

### Steps to reproduce the problem

Version: Project64 Dev-4.0.0.5811
Video Plugin: ParaLLEI
Audio Plugin: Azimer's Audio
Input Plugin: N-Rage
RSP Plugin: ParaLLEI RSP
Graphics and Audio HLE disabled
ParaLLEI settings set to 1280x960 window, 4x native upscale, 1/2 downscale
Problem happens upon immediate startup during capture.

### What game were you playing?

Yoshi's Story (U) (M2), also tried Kirby 64 - The Crystal Shards (U) and got the same problem.

### Specifications and build details

Project64: Dev-4.0.0.5811, unsure on 32-bit or 64-bit version

OS: Windows 10 Home 64-bit, build 19043.1706, version 21H1

CPU: AMD Ryzen 5 3600

RAM: 32.0GB Dual-Channel

Graphics: AMD Radeon RX 5700

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): ParaLLEI LLE
Audio plugin: Azimer's Audio
Input plugin: N-Rage
RSP plugin: ParaLLEI RSP

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment]
@JerrytheRat This is most likely something on Discord's end, so we may not be able to do anything about it just so you are aware. Are your graphics drivers fully updated?

**Comment by flagrama** [comment]
The currently known workaround to streaming issues with PJ64 on Discord is to enable cropping/overscan in GLideN64 and using that plugin while streaming on Discord.

**Comment by JerrytheRat** [comment]
@DerekTurtleRoe I was worried that may be the case. Checked and my graphics driver is fully up to date.

@flagrama Used GLideN64 plugin and capture does work fine. It's unfortunate I won't be able to use ParaLLEI though, performance was a lot better especially when running Yoshi's Story.

**Comment by project64** [comment]
sounds like a 3rd party plugin issue not actually a bug in project64.

Can I close this?

**Comment by JerrytheRat** [comment]
@project64 Go ahead, able to use GLideN64 as a suitable workaround for now.
