### ISSUE TITLE
[Bug]: Bug Reporting Instructions incorrectly suggest File > ROM Info

### ISSUE THREAD

**Issue by JasonGross** [project64/project64#2247]
### Expected behavior?

I expect the instructions for "What game were you playing?" to work with the latest version of P64.  That is, I expect there to be a "ROM info" under the File menu, or I expect it to not be mentioned as in

> ROM information: (File > ROM info, or context menu > ROM information in the ROM
list)

### Actual behavior?

![image](https://user-images.githubusercontent.com/396076/178165502-6011a24a-9de3-4c35-94c7-00c282d5ae22.png)

### Steps to reproduce the problem

Click File

### Error messages?

N/A

### What game were you playing?

N/A

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)
3.0 64-bit, also Project64-Dev-4.0.0-5830-3576bb2 (Windows zip)

OS: (include version and OS build number using WinVer):
Windows 10 Version 21H2 Build 19044.1766

CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 2304 Mhz, 4 Core(s), 8 Logical Processor(s)

RAM: 16GB

Graphics:
Name	Intel(R) UHD Graphics
Adapter Type	Intel(R) UHD Graphics Family, Intel Corporation compatible
Driver Version	30.0.101.1191
Resolution	1920 x 1080 x 59 hertz

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

N/A

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment]
Did you go to options > configuration and untick "hide advanced settings"?

I should probably clarify that in the issue template.

**Comment by JasonGross** [comment]
Ah, neat, now I see the option.  Yes, updating the issue template with this instruction would be good.

**Comment by Squall-Leonhart** [comment]
Rather, the rom info shouldn't be part of advanced settings, it isn't a setting.

**Comment by dftf-stu** [comment]
Even when "Hide advanced settings" is enabled, "ROM Information" is always available in the right-click menu for a ROM:

![RCM](https://user-images.githubusercontent.com/83965343/179963840-8fd93626-6951-4e73-a43e-fe0c6f24d39d.png)

As such, I'd suggest amending the template from this:
- ROM information: (File > ROM info, or context menu > ROM information in the ROM list)
to this:
- ROM information (right-click on a ROM, then choose "ROM Information")

**Comment by DerekTurtleRoe** [comment]
> Even when "Hide advanced settings" is enabled, "ROM Information" is always available in the right-click menu for a ROM:
> 
> ![RCM](https://user-images.githubusercontent.com/83965343/179963840-8fd93626-6951-4e73-a43e-fe0c6f24d39d.png)
> 
> As such, I'd suggest amending the template from this:
> 
>     * ROM information: (File > ROM info, or context menu > ROM information in the ROM list)
>       to this:
> 
>     * ROM information (right-click on a ROM, then choose "ROM Information")

This is true, I will update the instructions to be a bit more specific.

**Comment by dftf-stu** [comment]
There's been a [recent commit](https://github.com/project64/project64/commit/4b60f4f3e9dba7cbe249d3c80370100c2fce35c3) made around this request, but I'd suggest it's not working as expected:

- When you open _Project64_, "ROM Info..." can be found on the **File** menu, but it is greyed-out
- It only becomes available to click once you have started a ROM
- However: while a ROM is active, if you go to **File** then **End emulation**, then "ROM Info..." remains available in the **File** menu, but no-matter which ROM you select (highlight) in the _ROM Browser_, after you click "ROM Info..." it will always be for the last ROM you started, not the currently highlighted one, which is confusing

If you right-click a ROM in the list, then choose "ROM Information", it always displays the info for the ROM you clicked on

I'd suggest amending this change to one of the following:
1. Make "ROM Information..." in the **File** menu only active while a ROM is active; or
2. Make it show the information for the currently-selected (highlighted) ROM in the ROM Browser list, not the most-recently started ROM
