### ISSUE TITLE
Project64.cfg becoming corrupted.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#225]
I'm getting this in the Project64.cfg after changing settings.

```
[Main Window]
                          Left=444
        ounter Factor=1
Left=561
Top=174

[55D4C4CE-7753C78A-C:45]
        ounter Factor=1
Counter Factor=1
Dsound-SyncAudio=1
Good Name=Battlezone - Rise of the Black Dogs (U)
```
Edit:  Also getting duplicate entries in the Project64.rdb for 1.6 plugins in the main folder.

**Comment by project64** [comment]
you got any steps to reproduce this using the version on the pj64 forum?

**Comment by Frank-74** [comment]
Can't reproduce it at all with the version on the pj64 forum.

And now I can't seem to reproduce it on the build that caused it.  Which was your merge update from yesterday.  But I have changed a few things in the source since I first built the project64-master.zip.  I removed Game_TempLoaded from Settings Class.cpp/Settings.h/Plugin Class.cpp and I think Gui Class.cpp.  Trying to cleanup the plugin loading.  Trying to track down the mem leak in Glide that only happens when Glide is selected as an 'Edit Game Settings' plugin.

I only just noticed it today, I never usually check the Project64.cfg file.  One thing I did notice that is confusing.  The 'Fast SP' rdb setting, is called 'SP Hack' in the .cfg.

I'll keep checking the .cfg file from now on.

**Comment by AmbientMalice** [comment]
I had a cfg where "Fixed Audio" was truncated to "Audio". So you're not the only one. My PJ64 was compiled two or three days ago.

**Comment by cxd4** [comment]
std::string is 4 nubz

lel std's are bad mk

**Comment by project64** [comment]
now I can see this happening if there is a bug, or if there is a crash and the buffer did not get flushed correctly. Or if your debugging and you just stop the process with out letting it terminate. 

I assume it is a bug or something that can be done better, like forcing a flush to disk at a certain point might be needed.

**Comment by Frank-74** [comment]
I've just managed to reproduce this.  I just downloaded and built the current master to test the plugin cheat fix, and it happened straight away.

I started Pilot Wings straight away without touching any settings other than selecting my language and ROM directory.  It started up in 640x480.  I End Emulation after seeing the fix worked.  Goto Configure Graphics Plugin and change the resolution to 1024x768.  This also changes the ROM browser window size.  I restart Pilot Wings, then a crash, PJ64 just exits, and this happened.
```
[Main Window]
         Top=214
Left=362
Top=170
```

**Comment by LegendOfDragoon** [comment]
I'm using a build from about a week ago. I would randomly have the emulator crash and it would corrupt my cfg file. This has happened a few times now. So I went and manually cleaned up the cfg file, and cannot seem to reproduce it anymore.

**Comment by project64** [comment]
I set auto flush on by default in ini (https://github.com/project64/project64/commit/8afe84f315839aafe9230872216dc85994c71e30) this might fix it.

**Comment by Frank-74** [comment]
It still corrupts randomly.  Can't pin it down.  It has something to do with the size/position of the Main Window.

The corruption problem seems to have started since this :- https://github.com/project64/project64/commit/8388db4ac40ecb511580955d48a0769dbe4c4ca0

It always starts in [Main Window] section.

**Comment by cxd4** [comment]
He's got a bunch of corrupt bits in the CFG, starting at the very top:
```
[Main Window]
   32bit=1
e=1
Glide64-detect_cpu_write=1
Glide64-fb_smart=1
Glide64-lodmode=2
Glide64-read_back_to_screen=1
Good Name=Hybrid Heaven (U)
```
... and continuing later ...
```
[4DD7ED54-74F9287D-C:45]
      32bit=1
e=1
Glide64-detect_cpu_write=1
Glide64-fb_smart=1
Glide64-lodmode=2
Glide64-read_back_to_screen=1
Left=0
o Full Screen=0
Remembered Rom Dirs=8
Top=0
```
which set the wrong good name for the wrong CRC/rom

**Comment by Predator82Germany** [comment]
This config is alive with a strong AI, please kill this bitch ;)

**Comment by cxd4** [comment]
Maybe it just needs the cleaner C++ code.




k i tried, so it wasn't that funny.

**Comment by LegendOfDragoon** [comment]
I believe this issue was fixed recently. You guys should test and make sure. if it's fixed then feel free to close :) .

**Comment by Frank-74** [comment]
Ok, haven't had any corruption for a while.

**Comment by Predator82Germany** [comment]
Then comes a new build soon?
