### ISSUE TITLE
[Bug]: N64 frezzes when setting fullscreen on a SMART TV 4K

### ISSUE THREAD

**Issue by Calabronx** [project64/project64#2259]
### Expected behavior?

 The option "Open in fullscreen" with the game already running, used to frezze when this option was choosed , and game went fullscreen.

### Actual behavior?

This issue Only Happens tryng to use full screen in a big SMART TV ej: Hitachi CDH-LE504KSMART22 LED 4K 50"

I had a laptop with Windows 10 running n64, extending a second screen that was a Smart TV Hitachi . Where i was tryng to play the game, the option "Open in fullscreen" with the game already running, used to frezze when this option was choosed and game went fullscreen.
Strange thing is that in my laptop the fullscreen works perfect, even in a monitor "30, also works great.
Maybe a TV with "50" , could overflow the pixels of resolution screen that the program can manage? I would like to indagate the code that manages the screen functions, if i can contribute with a little help in that.

I had to set resolution of screen in windows 10 config to 800 x 600 and play game in window on the center of the tv, that work but no FULLSCREEN.

### Steps to reproduce the problem

1.Connect a Computer to a big smart tv screen , preferebly with windows 10 that was my case.
2.Extend the screens to reproduce the game in the TV.
3.Open a ROM and choose "Open in Fullscreen".
4. Game frezzes , and you have to close project n64 .

### Error messages?

No error messages, just game stops

### What game were you playing?

Title: Mario Party 2 (USA)

Nintendo 64 game or Nintendo 64 Disk Drive: game.z64

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field): 
Save type: (Attach game save or save state here)

Original or modified ROM?:(attach patch here)

### Specifications and build details

Roms work in 60 FPS and more, no down rates, runs perfect with this specifcs.

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)

OS: (include version and OS build number using WinVer):

CPU: Intel I7-7500U 2.70Ghz(4 CPUS) , 2.9 Ghz 

Drive: SSD

RAM: 20 GB

Graphics: Nvidia Geforce 940mx

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE):
Audio plugin:
Input plugin:
RSP plugin:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by flagrama** [comment]
Physical dimensions of a device have no effect on software. The issue is more likely the resolution or the fact it is a secondary monitor and it doesn't like the way it is oriented.

**Comment by DerekTurtleRoe** [comment]
You didn't fill out a lot of the most pertinent information, so we can't really help you unless you tell us more information.

We would need to know:

Project64 commit number and versions
Plugins you used and the versions
Windows version

It would also be nice to know:
Laptop model
Driver versions for the Nvidia graphics

Otherwise I'm going to recommend we close this.

**Comment by Squall-Leonhart** [comment]
This is an intel driver bug and there is nothing that can be done from the software to fix it.

The only workaround is to not use Vsync.

see https://github.com/PCSX2/pcsx2/issues/5326

**Comment by Calabronx** [comment]
Thank you for the responses, probably is the driver Vsync that was causing the issue.
