### ISSUE TITLE
[Bug]: Snowboard Kids is freezing every time in the same place

### ISSUE THREAD

**Issue by dezraj** [project64/project64#2271]
### Expected behavior?

The program wasn't supposed to freeze in that part. It is not possible to advance in the game with the emulator presenting this current issue.

### Actual behavior?

The emulator freezes every time in the same place.

### Steps to reproduce the problem

1. Load the game
2. Go to Board Shop
3. Enter Buy Board
4. Press B to return to shop or select "Return to shop" and press A
5. The emulator should freeze now
...
Short video-clip of the issue being reproduced:
https://drive.google.com/file/d/1z22cphg1crzowNA5wPnslwh4OnlcKiyY/view?usp=sharing

### Error messages?

None.

### What game were you playing?

Title: Snowboard Kids

Nintendo 64 game or Nintendo 64 Disk Drive: Snowboard Kids

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
![image](https://user-images.githubusercontent.com/27839354/183834372-df7a66f1-997c-46c5-a689-71c906b9a0a8.png)

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)
Project64-Dev-4.0.0-5872-f36e7cb

OS: (include version and OS build number using WinVer): Windows 10 1809 Build 1763.3287

CPU: i5-10400

RAM: 16gb

Graphics: GTX 1660 Ti

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

All the default plugins which come embedded with this version of the emulator. 

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Confirmed, breakpoint found exception

**Comment by project64** [comment]
this should hopefully fix it
https://github.com/project64/project64/commit/a640ecfbc0b50eb4f83f9b510b150fe95120069d

**Comment by Squall-Leonhart** [comment]
Confirmed fixed
