### ISSUE TITLE
[Bug]: Dev build 4.0.0.5889 and higher no-longer work on my PC; 4.0.0.5884 last to work

### ISSUE THREAD

**Issue by dftf-stu** [project64/project64#2282]
### Expected behavior?

To be able to play N64 games on my old laptop using the "Project64 Video (for older PCs)" plug-in option, which I have been able to do until just-recently

### Actual behavior?

- Version **Dev-4.0.0-5884** (released 15 Aug 2022) is the most-recent version that works
- Version **Dev-4.0.0-5889** (released 22 Aug 2022) loads any ROM I've tested to a blank, black screen and the "Percentage of full speed" counter in the Status Bar updates rapidly, with values into the high hundreds or even six-digits!
- Version **Dev-4.0.0-5895** (released 29 Aug 2022) and later don't work at-all; loading any ROM just gives the "Unknown memory action, Emulation stopped" error

Note: each release was unzipped into its own folder, so no previous settings were inherited.  Each was setup from scratch

Screenshot:

![PJ64_ISSUES](https://user-images.githubusercontent.com/83965343/188148565-f748fc6f-f41f-44e0-b531-7d2c82e288e4.png)

### Steps to reproduce the problem

I simply downloaded and tested each of the later versions of Project64 from [here](https://www.pj64-emu.com/nightly-builds), with each release extracted into its own folder (so there were no leftover settings; each was configured from-scratch).

### Error messages?

There is no error-message for **4.0.0.5889**, but the "Percentage of full speed" in the Status Bar runs at crazy speeds: for _Banjo-Kazooie_ (USA) it is in the high 100s; for _Banjo-Tooie_ (Europe) it gets into six-digits!

The two most-recent versions, **4.0.0-5895** and **4.0.0-5898** both give this error, and do not load any ROM:
> Unknown memory action
> Emulation stopped

Contents of the "Project64.log" file for the 4.0.0-5895 version:

> 2022/09/02 13:20:07.294 08988,Error,Exception Handler,CMipsMemoryVM::FilterX86Exception,Invalid memory address: 201C0005
> 2022/09/02 13:20:07.295 08988,Error,User Interface,CNotificationImp::DisplayError,Unknown memory action

### What game were you playing?

Title: Banjo-Kazooie
Nintendo 64 game or Nintendo 64 Disk Drive: N64 only
ROM information: MD5=D3E08495AACF2A9DC3B4BA0BA4093516 | REGION=USA | CRC1=0xA4BF9306 | CRC2=0xBF0CDFD1 | CICChip=CIC-NUS-6103 
Save type: N/A
Original or modified ROM?: Original

Same issue with Banjo-Tooie (Europe region) also

### Specifications and build details

Project64: Dev-4.0.0-5889-52a30b7 (22 Aug 2022) and higher versions (32-bit build)
OS: Windows 10 Home 64-bit (non-ARM) Version 21H2 OS Build 19044.1889
CPU: Intel Core i3 330M ([details...](https://www.intel.com/content/www/us/en/products/sku/47663/intel-core-i3330m-processor-3m-cache-2-13-ghz/specifications.html))
RAM: 8GB DDR3
Graphics: Intel HD integrated, driver version: 8.15.10.2900, driver date: 26/11/2012

- Dev-4.0.0-5884-cc2aa47 (15 Aug 2022) is the most-recent version I can get to work

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): "Project64 (for older PCs)", HLE, default
Audio plugin: default
Input plugin: default
RSP plugin: default

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by dftf-stu** [comment]
**UPDATE**: all three of the latest versions do work correctly if the option "Always use Interpreter Core" is turned-on... albeit with the usual penalty of _severely_-reduced performance.  But just thought I'd mention it in-case it helps diagnose anything!

(I did also try leaving the "Interpreter Core" option off (aka the default setting), but changed the video plug-in to Jabo's DirectX one, but that makes no-difference and each version still crashes in the manors outlined in the original report.)

**Comment by Squall-Leonhart** [comment]
PJ64 is in the middle of a core overhaul, the break is expected.

**Comment by project64** [comment]
not really expected, more uprising. 

I am trying to make things better, but with changing code and moving things bug can be added or old bugs not visible can cause problems.  I am trying to keep changes small to reduce things breaking, but with how much I am changing it is not uprising that I break things.

I will try to fix it over the next couple of days, thanks for pointing it out

**Comment by project64** [comment]
hopefully: https://github.com/project64/project64/commit/a5c6f25ee3e4627169114e291b3d0ca4c10dc548 fixes the issue

**Comment by Pear1st** [comment]
> hopefully: [a5c6f25](https://github.com/project64/project64/commit/a5c6f25ee3e4627169114e291b3d0ca4c10dc548) fixes the issue

It did fix the MUST "Always use Interpreter Core" check issue, thx a lot!

But another issue from Version Dev-4.0.0-5823 was the way still.

![image](https://user-images.githubusercontent.com/78216520/188529795-d1bcef16-f967-4fa7-9967-a327ac6635c9.png)

Conker's bad fur day (U) , Nintendo logo is missing
RE2 , zombie and leon are invisable

please help

**Comment by Squall-Leonhart** [comment]
those are plugin issues.

**Comment by dftf-stu** [comment]
I'm not sure which recent version has fixed the issue, but I've just downloaded version "Dev-4.0.0-5911-a640ecf" (5 Sep 2022) from [here](https://www.pj64-emu.com/nightly-builds) and can confirm that ROMs are working normally in it on my PC
