### ISSUE TITLE
[Bug]: Conker's bad fur day (U) working on Dev build 4.0.0.5823 and higher did not show the nintendo logo and more

### ISSUE THREAD

**Issue by Pear1st** [project64/project64#2283]
### Expected behavior?

To play N64 games with the "GlideN64" plugin on my PC accuracy

### Actual behavior?

Version Dev-4.0.0-5819 (released 6 Jun 2022) is the most-recent version that works
Then from
Version Dev-4.0.0-5823 (released 22 Aug 2022) 
to 
latest Version Dev-4.0.0-5911 (released 5 Sep 2022) loads ROM normally, but shows no Nintendo logo anymore!

Note: each release was unzipped into its own folder, so no previous settings were inherited. Every setting is by default, including plungins.

Screenshot
v5819
![image](https://user-images.githubusercontent.com/78216520/188826033-6c32edb8-17f6-47ab-b38b-7bd9c22f0de6.png)
![image](https://user-images.githubusercontent.com/78216520/188826676-77cbfc24-c512-4243-9e3c-c93d9d882ad7.png)

v5911
![image](https://user-images.githubusercontent.com/78216520/188827429-9e8b2512-bd25-4c2a-9aca-d9417c0b52cc.png)
![image](https://user-images.githubusercontent.com/78216520/188841514-f291e597-0de4-4c0a-a8b6-ea51ba48e743.png)

### Steps to reproduce the problem

I downloaded and tested each of the later versions of Project64 from [here](https://www.pj64-emu.com/nightly-builds), with each release extracted into its own folder (so there were no leftover settings; each was configured by default).

### Error messages?

Nothing

### What game were you playing?

![image](https://user-images.githubusercontent.com/78216520/188842126-4fb9fb6f-cc5a-4258-8172-8ad4dbd53d81.png)

### Specifications and build details

Project64: Dev-4.0.0-5823-cec55c7 (13 Jun 2022) and higher versions (32-bit build)

OS: Windows 11 Pro 21H2 22000.918
CPU:Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz   3.50 GHz

RAM:16.0 GB

Graphics:GeForce RTX 2070 SUPER 8GB

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE):HLE, default
Audio plugin:default
Input plugin:default
RSP plugin:default

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Reproduced it, issue occurs in Interpretter as well.

most likely https://github.com/project64/project64/commit/f0760ff1cf0bff3a5cc5c5f1cc53ecd0d33260a4

**Comment by Pear1st** [comment]
> 

Yeah exactly

**Comment by Squall-Leonhart** [comment]
Fixed by https://github.com/project64/project64/commit/21b193152a7c3765a92c5b8a18a53e11b3d080b5
