### ISSUE TITLE
[Bug]: Crash in Return To Yoshi's Island 64 DEMO

### ISSUE THREAD

**Issue by xiartic** [project64/project64#2286]
### Expected behavior?

Project64-Dev-4.0.0-5921-0c07804 & Real N64:
![GLideN64_YOSHIS_ISLAND_64_000](https://user-images.githubusercontent.com/78692485/195945568-ac29abfc-2704-424a-81a4-6326be632922.png)

### Actual behavior?

Project64-Dev-4.0.0-5926-8391cda & Current dev build Dev-4.0.0-5945-9b824a7:
![GLideN64_YOSHIS_ISLAND_64_0000](https://user-images.githubusercontent.com/78692485/195945775-088aadd7-f103-4aaf-9a74-1721c46f2331.png)

The game crashes when throwing a bomb underwater.

### Steps to reproduce the problem

1. Throw a bomb underwater by hitting the B button and you get an in-game crash screen.

### What game were you playing?

Title: Return To Yoshi's Island 64 DEMO (Super Mario 64 Hack)

Nintendo 64 game or Nintendo 64 Disk Drive: Nintendo 64

ROM information: (YOSHIS ISLAND 64 / Return To Yoshi's Island 64 DEMO.z64 / B5826DE51FCF2A892508B5AA5459FA3F)
Save state: ([Return To Yoshi's Island 64 DEMO.pj.zip](https://github.com/project64/project64/files/9790080/Return.To.Yoshi.s.Island.64.DEMO.pj.zip))

Original or modified ROM?: modified ROM 
(Patch: https://mega.nz/file/3aQA3JCZ#hhBrChFE2xvAy9kFBCa2Vm9xCSgxz2ZWDvK0lY4hMC0)

### Specifications and build details

Project64: Project64-Dev-4.0.0-5926-8391cda

OS: Windows 11 Home 21H2

CPU: Intel Core i5-3350P

RAM: 8 GB DDR3

Graphics: Nvidia Geforce GTX 1060

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin: GLideN64 rev. 2973f53 HLE
Audio plugin: Project64 audio plugin Dev-4.0.0.5926-8391cda
Input plugin: Project64 input plugin Dev-4.0.0.5926-8391cda
RSP plugin: RSP plugin Dev-4.0.0.5926-8391cda

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by xiartic** [comment]
Crash no longer happens in Project64-Dev-4.0.0-5966-0503f32.

**Comment by project64** [comment]
presumable https://github.com/project64/project64/commit/65bbc375b985ea88654a648095a7523128fdcb06 fixes the issues
