### ISSUE TITLE
Can't load any roms in WinXP

### ISSUE THREAD

**Issue by harlayzhou** [project64/project64#229]
Can't creating rom list after delete Project64.cache3.
But it's work fine in Win8.

**Comment by project64** [comment]
if you just take the version from the pj64 forum extract it to clean directory do you have this issue?

**Comment by harlayzhou** [comment]
I can't find any bin file from pj64 forum.
It's all failed with both emucr and compile myself from https://github.com/project64/project64.git
It's black screen that if I open the rom directly.

**Comment by Frank-74** [comment]
This happens when you try to run VS2013 compile on XP.  Use the VS2008 compile with XP.

**Comment by MELERIX** [comment]
VS2013 build are fully compatible with XP as I know, make sure you have installed this: http://www.microsoft.com/en-us/download/details.aspx?id=40784 and also make sure to update Direct X using this: http://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by project64** [comment]
it runs on XP but it has some issues with debugging I probably can fix it, but I am just going to release the VS2008 version

**Comment by Frank-74** [comment]
I'm yet to be able to run a VS2013 build.  I've already installed the VS2013 runtimes and directx from microsoft.  Still the ROM browser never works, stays blank, plugins don't initialise, opening a rom from File menu gives directx error and plugins failed to initialise, black screen but emulation hasn't started.

**Comment by MELERIX** [comment]
is your Windows XP SP3 will all the updates from Windows Update ?

**Comment by Frank-74** [comment]
Yes XP SP3 fully upto date.  Other VS2013 compiled programs work fine.  Azimer's 0.7 for example was built with VS2013.  I got the VS2013 runtimes back when WIP4 came out.  I have a ZX Spectrum emulator that was built with VS2013, also works fine.  But PJ64 no workio for me yet.

**Comment by project64** [comment]
yes it should work, but doesn't. I may care after 2.2 but 2..2 will be built using vs2008.

**Comment by MELERIX** [comment]
Frank-74 & harlayzhou can you check if this build works for you ? http://www30.zippyshare.com/v/WDfLkOBI/file.html

**Comment by Frank-74** [comment]
>Frank-74 & harlayzhou can you check if this build works for you ? http://www30.zippyshare.com/v/WDfLkOBI/file.html

Doesn't work, ROM list never loads, doesn't even attempt to read the directory it seems.  Plugins fail to initialize.

**Comment by harlayzhou** [comment]
Doesn't work for me either.

**Comment by MELERIX** [comment]
@harlayzhou @Frank-74 this fixes PJ64 Builds with VS2013: https://github.com/project64/project64/pull/302

**Comment by cxd4** [comment]
I'm surprised if that was all there was to it that's left.

**Comment by MELERIX** [comment]
for loading roms not idea what thing could be causing the issue.

**Comment by JunielKatarn** [comment]
#627 Fixes this issue.
Awaiting for approval.

**Comment by JunielKatarn** [comment]
Hi @harlayzhou. This issue has been resolved. Builds made with versions of Visual Studio from this decade work fine on XP. The latest dev bits can be installed from here:

http://hyvart.com/download/project64/ci/project64.application

You can close this issue now.
