### ISSUE TITLE
[Bug]: Issue with N-Rage's Input Plugin

### ISSUE THREAD

**Issue by xiartic** [project64/project64#2294]
### Expected behavior?

The emulator should keep having working input after closing the Configuration menu.

### Actual behavior?

In the latest stable release & dev releases. Opening up Configuration menu causes inputs to not work after closing it unless you open Input Plugin settings.

### Steps to reproduce the problem

1. Use N-Rage
2. Open a game
3. Open Configuration 
4. Close Configuration
5. Nothing does anything unless you open Input Plugin and close it
...

### Specifications and build details

Project64: Project64 3.0.1.5664-2df3434

OS: Windows 11 Home 21H2

CPU: Intel Core i5-3350P

RAM: 8 GB DDR3

Graphics: Nvidia Geforce GTX 1060

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): GLideN64 HLE
Audio plugin: Project64 audio plugin
Input plugin: N-Rage for Project64: 3.0.1.5664-2df3434
RSP plugin: RSP plugin

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by xiartic** [comment]
Looks like this issue has been there since V2.3. Is there any reason Project64 isn't using this version of NRage's Input Plugin instead? https://sourceforge.net/projects/nragev20/

It does not have this problem.

**Comment by flagrama** [comment]
Because it's an old version with different problems already fixed in this repository.

**Comment by xiartic** [comment]
Ah, I see. Thanks for the reply. I hope this one eventually gets fixed.

**Comment by Squall-Leonhart** [comment]
the issue claimed in this bug simply doesn't exist.

**Comment by xiartic** [comment]
You're actually correct! I tried the latest nightly "Project64-Dev-4.0.0-5966-0503f32" and the issue is gone. Therefore I'll be closing this because the problem has been fixed.
