### ISSUE TITLE
problem with wave race 64 US rom v1.1

### ISSUE THREAD

**Issue by IAMRGG** [project64/project64#2298]
### Expected behavior?

i expect to see the wave effect but its missing or broken

### Actual behavior?

i don't see the wave effect in the game. i have the problem since september more o less. the rom works normally but that effect is broken. on the japanese rom or europe rom the effect is correct. 

### Steps to reproduce the problem

1.load rom
2.the game starts normally
3.
4.
5.
...

### Error messages?

no error messages appear

### What game were you playing?

Title:

Nintendo 64 game or Nintendo 64 Disk Drive:

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
Save type: (attach game save or save state here)

Original or modified ROM?:(attach patch if applicable here)
Wave race 64 US v1.1

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version) pj64 dev-4.0059660503f32

OS: (include version and OS build number using WinVer): windows 10 22H2

CPU: i7 3770

RAM:32gb

Graphics: radeon rx580 8gb

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): gliden64 rev.f431466
Audio plugin:pj64 audio plugin
Input plugin:raphnetraw for pj64 v1.07
RSP plugin: included plugin

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
1.0, 1.1 or shindo edition?

**Comment by Squall-Leonhart** [comment]
Disable Register Caching or Advanced Block linking, either one will restore the effect.

**Comment by IAMRGG** [comment]
Squall-Leonhart you are GOD. the wave effect is fixed. THANKS

**Comment by Squall-Leonhart** [comment]
keep this open, theres still a  bug here.

**Comment by IAMRGG** [comment]
what's the bug??? maybe the speed of emulation??? i've noticed a drop of FPS when 4 motorbikes are running at the same time. works like slow motion.

**Comment by Squall-Leonhart** [comment]
the bug is in the recompiler, the optimizations shouldn't break games.

**Comment by IAMRGG** [comment]
Aaaaah ok ok. then i keep open the issue until everything will be ok
________________________________
De: Squall Leonhart ***@***.***>
Enviado: Friday, November 4, 2022 8:34:18 AM
Para: project64/project64 ***@***.***>
Cc: IAMRGG ***@***.***>; State change ***@***.***>
Asunto: Re: [project64/project64] problem with wave race 64 US rom v1.1 (Issue #2298)


the bug is in the recompiler, the optimizations shouldn't break games.

**Comment by Squall-Leonhart** [comment]
Caused by compiler optimizations, as outlined by https://github.com/project64/project64/issues/2300

**Comment by project64** [comment]
https://github.com/project64/project64/commit/e3aa2514c1458b366d191eed7372e9a680e58231 should fix wave race

**Comment by IAMRGG** [comment]
on the new build wave race, goldeneye and perfect dark works fine!!! no problems. thanks
