### ISSUE TITLE
Goldeneye Black Screen or crash [Bug]: 

### ISSUE THREAD

**Issue by Tasosgemah** [project64/project64#2301]
### Expected behavior?

Game loads

### Actual behavior?

Game crashes with emulation error message in version 3.0.1
Game shows black screen in version 4.0 DEV

### Steps to reproduce the problem

Just load the game

### Specifications and build details

OS: Windows 10 64bit

CPU: i5 4670

RAM: 16GB

Graphics: GTX 1060

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE):
Audio plugin:
Input plugin:
RSP plugin:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
duplicate #2300 
incomplete bug report

**Comment by Tasosgemah** [comment]
3.0.1 public still makes Goldeneye crash though.
