### ISSUE TITLE
[Bug]: Cruis'n USA v1.0 not working correctly

### ISSUE THREAD

**Issue by xiartic** [project64/project64#2303]
### Expected behavior?

This game seems to have problems running with both stable & nightly releases.

### Actual behavior?

Cruis'n USA hangs after the controller screen in both stable 3.0.1 and dev 4.0.0-6016-989827c.

Video of Cruis'n USA:

https://user-images.githubusercontent.com/78692485/201761745-1cace8a7-82a9-413c-8c76-b1c6c2a91ca0.mp4

### Steps to reproduce the problem

1. Try to play Cruis'n USA
2. 
3.
4.
5.
...

### What game were you playing?

Title: Cruis'n USA

Nintendo 64 game or Nintendo 64 Disk Drive: Nintendo 64

### Specifications and build details

Project64 3.0.1-5664-2df3434

OS: Windows 11 Home 21H2

CPU: Intel Core i5-3350P

RAM: 8 GB DDR3

Graphics: Nvidia Geforce GTX 1060

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin: GLideN64 rev. f431466 HLE
Audio plugin: Project64 audio plugin 3.0.1-5664-2df3434
Input plugin: Project64 input plugin 3.0.1-5664-2df3434
RSP plugin: RSP plugin 3.0.1-5664-2df3434

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Cruis'n USA has no issues getting in game with U 1.2, you need to specify the region and rom version as some issues are specific to a specific version of the game.

Exotica is another SP Dram not in RDRAM issue.

**Comment by xiartic** [comment]
I tried (U) v1.0 and it would not get further than the controller screen. Looks like (U) v1.1 and v1.2 work fine.

**Comment by Squall-Leonhart** [comment]
i don't get a freeze, i get a pak access error instead on 1.0

**Comment by xiartic** [comment]
Interesting. Is the hash of your ROM: A4E241B2535D6A54B62D08AF53CA83B0?

**Comment by Squall-Leonhart** [comment]
Freeze is due to PJ64 Inputs memory pak emulation.

~~My suspicion is the pak size is emulated to be too large for the 1.0 variant, 1.1 and 1.2 have support for larger pak sizes and rumble pak respectively~~

**Comment by Squall-Leonhart** [comment]
letting nrage have the emulator handle the save also freezes

if you run 1.1 or 1.2, these will have created the pak file and 1.0 will load the emulator handled mpk.

**Comment by Squall-Leonhart** [comment]
~~Actually, it looks like 1.0 assumes that the mempak has already been formated previously, where as 1.1 and 1.2 can handle an unformatted mempak.~~

**Comment by Squall-Leonhart** [comment]
1.0 does some really sus things in its mempak handling, but i found a fix that looks like it works without breaking anything.

**Comment by xiartic** [comment]
Can confirm Cruis'n USA working with Project64-Dev-4.0.0-6022-8eecb0c.

**Comment by xiartic** [comment]
Squall's memory pak fix made this game work properly.
