### ISSUE TITLE
[Bug]: Donkey Kong 64 does not boot past opening logos

### ISSUE THREAD

**Issue by Superjustinbros** [project64/project64#2308]
### Expected behavior?

When booting the game, it goes to the opening logos, then to the DK Rap sequence, then the title screen with one of five demo sequences playing in the background.

### Actual behavior?

The game does not continue to the DK Rap, and locks on a black screen.

### Steps to reproduce the problem

1. Launch the Donkey Kong 64 ROM
2. Wait until the "Presented in Dolby Surround" screen ends; the freeze occurs when the DK Rap should start.
...

### Error messages?

No error message is provided by the emulator.

### What game were you playing?

Title:Donkey Kong 64

Nintendo 64 game or Nintendo 64 Disk Drive: Nintendo 64 game

ROM information: 
![image](https://user-images.githubusercontent.com/4167951/202887295-bbc1abe8-6658-41a0-b661-748e04e708d8.png)

Save type:
[Donkey Kong 64 (U).pj.zip](https://github.com/project64/project64/files/10048939/Donkey.Kong.64.U.pj.zip)

Original or modified ROM?: Original

### Specifications and build details

Project64: Dev 4.0.0.6016-989827c

OS: Windows 7

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): GLideN64 rev.f431466 (Graphics HLE checked)
Audio plugin: Project64 Dev 4.0.0.6016-989827c
Input plugin: Project64 Dev 4.0.0.6016-989827c
RSP plugin: Project64 Dev 4.0.0.6016-989827c

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Yes it does.

![image](https://user-images.githubusercontent.com/1098176/202899513-6a06708f-cf6e-415f-a42e-a700d42df390.png)

**Comment by Squall-Leonhart** [comment]
Another #2300  but this time specifically the register caching setting.
