### ISSUE TITLE
[Feature request]: Android App Icon Colors

### ISSUE THREAD

**Issue by soundsnow** [project64/project64#2349]
### Request box

Android 12: you can change wallpaper, OS will auto-detect its color
Android 13: you can pick your favorite colors
Android 14: I don't have any device installed Android 14

![image116](https://user-images.githubusercontent.com/109885044/222360865-82a2786d-eef5-48d2-91c1-d6c40dee5780.png)

### Reason box

Google added this for Android

### Examples

?.png

**Comment by project64** [comment]
if you have an improvement you can always make a pull request with how you think it should be done
