### ISSUE TITLE
[Feature request]: Android delete selected save or state files

### ISSUE THREAD

**Issue by soundsnow** [project64/project64#2351]
### Request box

delete files with checkbox

I remember some emulators support this
Mupen64Plus AE delete all data
DuckStation delete states, delete/format/new memory card
AetherSX2 delete states, delete/format/new memory card
MasterEmu delete wipe all states
WonderDroid delete states/daves
GBCC delete saves

### Reason box

I don't know much about pj64 because my Android can't run armeabi-v7a project64

### Examples

o

**Comment by DerekTurtleRoe** [comment]
@soundsnow I know you might just be trying to help or just trying to get your feedback in, but opening issues with very little information or reasoning is more harmful than helpful. You have opened several issues with very little information, and some of them outright have nothing to do with this project. Please don't spam the project pages. You can post in the discussions section if you want to discuss things.
