### ISSUE TITLE
[Bug]: The game Turok 3 freezes on the x64 version of the emulator.

### ISSUE THREAD

**Issue by SatanNintendo** [project64/project64#2352]
### Expected behavior?

The emulator should open the game and not freeze.

### Actual behavior?

When I start playing "Turok 3", the game season starts to hang, at the very beginning, it happens on the x64 version of PJ64. I tried to run the emulator on Windows 7 and Windows 11.

### Steps to reproduce the problem

1. I'm launching the emulator.
2. Setting up plugins.
3. Opening the game.
4.
5.
...

### Error messages?

When running any game, the 64-bit version reports an error.

### What game were you playing?

Title:

Nintendo 64 game or Nintendo 64 Disk Drive:

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
Save type: (attach game save or save state here)

Original or modified ROM?:(attach patch if applicable here)

Original Turok 3 Game.

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)

I'm used: Project64 Git (2023.02.28) Dev-4.0.0-6085-ea70218d-x64

OS: (include version and OS build number using WinVer): Windows 7 x64 Ultimate & Windows 11 Pro x64

CPU: Intel Core i7 2600K

RAM: 16GB

Graphics: Palit GeForce GTX 1050 Ti DUAL OC (4GB)

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): Project64-Video
Audio plugin: Project64-Audio
Input plugin: Project64-Input
RSP plugin: RSP 1.7

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by project64** [comment]
the 64bit version does not full work which is why it is not included in any release. A lot of work still needs to be done in the x64 version
