### ISSUE TITLE
[Jabo D3D] Graphic config not saving

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#236]
Rom Database settings in Jabo's D3D plugin such as _Override aspect, Emulated Width, Emulated Height_ and _Direct3D Clear Mode_  don't seem to be saved when modified to the Project64.cfg file.

Steps to reproduce:
-Make sure you have "Hide advanced settings" unchecked in the Emu Settings
-Right click any ROM in the Browser > GFX Plugin > Rom Settings...

The only parameter that gets saved is the "Direct3D Pipeline".
You can check in the cfg file that only the "Direct3D8-Direct3DPipe=1" parameter is being written while the rest aren't.

This is a regression from Project64 1.7.0.50 beta, where the parameters 

Aspect Correction=X
ClearvFrame=X
Resolution Height=X
Resolution Width=X

were at least being written to the RDB but not to the Project64.cfg file for some reason.

The other parameters such as Brightness, Anisotropic filtering, Antialasing, Filtering, Aspect Radio, etc... work completely fine and are being written to the CFG file.

**Comment by Frank-74** [comment]
Also, Clear Frame, Resolution Height/Width are the only settings to be saved per game using Jabo's D3D8 1.6.1.  They're saved in the root folder Project64.rdb.  The rest of the options are global, and are saved in the registry key : HKEY_CURRENT_USER\Software\JaboSoft\Project64 DLL\Direct3D8 1.6.1.

**Comment by Fanatic-64** [comment]
Related to this, would it be possible to make settings like "Copy framebuffer to RDRAM" configurable from the RDB? The current setting "Primary Frame Buffer=" doesn't seem to do anything.

**Comment by cxd4** [comment]
Primary Frame Buffer was an option in the 1.5.2 version of Project64 Jabo's Direct3D6 plugin.  It was removed in Direct3D8, though the RDB setting I guess was kept in case of places where the RDB/GameFAQ referred people to fix graphics issues using an older version of Jabo's plugin.

**Comment by cxd4** [comment]
I didn't see this issue for some reason, even though, it was started 13 days ago.

Keep in mind that any control over Jabo's plugins has to be done through whatever complications were added to the plugin specs in case of closed-source plugins.  (In other words, in short of gaining the approval of a closed-source plugin to go through the plugin specs more often than to do its own thing, there is really no practical way to control closed-source design.)

**Comment by Fanatic-64** [comment]
Well, that's why I'm asking, to see if it's possible to add that setting via the plugin spec.

**Comment by cxd4** [comment]
Btw oddMLan, pj64 after 1.7.0.50 uses the CFG file now instead of the RDB file, which uses an entirely different structure.  As Jabo's plugins are no longer maintained, the 1.6.1 plugin released by Jabo elsewhere is the newest version, so it was not really desirable to convert registry keys to configs through artificial spec communications for options that weren't really accuracy related or no longer maintained.

**Comment by Frank-74** [comment]
Wondering if using the wrapper made for 1.6 by Shunyuan to use Jabo's 1.7 D3D8, would use the RDB in the root folder for 1.6 plugins in 2.2.  Then we could use Jabo 1.7 with an RDB in the root folder.  And the Clear Frame=2 setting will then work for Perfect Dark for example.

**Comment by LegendOfDragoon** [comment]
@Frank-74 , iirc shun's wrapper used registry.

**Comment by Frank-74** [comment]
Well then, would moving the Project64.rdb out of the config folder and back into the root folder, solve 1.7 not being able to read the RDB for Clear Frame setting?

I'm sure Jabo's 1.7 reads the settings from the RDB, but no longer works in 2.+, it worked in 1.7 though.

**Comment by project64** [comment]
maybe we need another rdb file in the root directory for jabo's plugin

for the setting system, I allow the config file to be able to be changed but for older versions of jabos plugin if he does not use the settngs, then I think he might just be trying to load the file directly and expecting it to be in the root directory

**Comment by Fanatic-64** [comment]
Jabo's 1.7 plugins load settings from the RDB and CFG files, wherever they are configured to be. CFG settings override RDB settings.
Jabo's 1.6 plugins load settings from the RDB file in the Project64 root folder, and from the registry. Registry settings (user-configured) override RDB settings.

If we are keeping the Jabo 1.6 plugins, we should have a Project64.rdb file in the emulator's root folder with the relevant settings (or have the installer create a Symbolic Link with that name that points to Config/Project64.rdb).

**Comment by oddMLan** [comment]
>maybe we need another rdb file in the root directory for jabo's plugin

Sounds like a good way to declutter the main RDB. IMO, the RDB should be plugin-agnostic and should just have parameters pertaining core options and ROM information.

Also, since this was done for PJ64Glide already, and most agree that Jabo's plugins aren't the most adequate anymore and therefore should no longer be the default, this seems like the logical next step.

My understanding is that Jabo's 1.7+ plugins let Project64 do the handling of the RDB instead of using the registry/directly editing the RDB file, I guess redirecting those calls to a file should be possible, but only for his 1.7+ plugins, right?

Since I'm guessing this is not possible for his 1.6/1.6.1 plugins that use the old handling method, I guess they would just fail to read and save the configuration if this change is done... unless you make the current Project64.rdb dummy have an actual configuration that could be read from there for the 1.6/1.6.1 plugins?

IMO, is not worth the hassle just for a couple of fixes more that the 1.6.1 version had over the 1.7 plugins. The people that for some reason would prefer to use Jabo's D3D 1.6 or 1.6.1 should stick to an older version that supports it.

**Comment by Makaque** [comment]
Has anyone discovered anything new about this issue since 2015? 
Is there at least a workaround for Jabo's 1.7 plugin? I've tried copying the RDB to the root folder and adding Clear Frame=2 to The Legend of Zelda -Ocarina of Time (U) (V1.0) but the plugin did not load from there.
