### ISSUE TITLE
[Bug]: "Keyboard: ???" using a Direct-Input Controller. 

### ISSUE THREAD

**Issue by zmarotrix** [project64/project64#2362]
### Expected behavior?

When I click on a button to bind it in N-Rage, it should allow me to press the button to bind it.

### Actual behavior?

When I click on a button to bind it, it displays "Keyboard: ???" Immediately and does not allow me to bind anything at all. 

![image_2023-05-09_123557321](https://github.com/project64/project64/assets/3902321/88f2080a-52e3-4aec-b5db-2c313ba72876)

![image_2023-05-09_123939226](https://github.com/project64/project64/assets/3902321/b8c86f62-0787-45e6-a402-9f3a20f30ed5)

### Steps to reproduce the problem

1. Open N-Rage settings
2. Click a button too bind
3. Sometimes I can bind the first button
4. Any time I attempt to bind another button, it only says "Keyboard: ???" as soon as I press the button

### Error messages?

None.

### What game were you playing?

This will happen regardless of game launched or not. 

### Specifications and build details

Project64: Literally any. I've been experiencing this across nightly builds for the last several years. 

OS: Windows 10 64-bit build 19044

CPU: Intel i9-13900kf

RAM: 32GB @6400hz

Graphics: Nvidia RTX 3080 10GB

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): GLideN64 
Audio plugin: Default
Input plugin: N-Rage Default a & N-Rage 2.3c both tested to the same result. 
RSP plugin: Default

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by furtabs** [comment]
Try using this version of N-Rage and report back https://drive.google.com/file/d/1chKraibA-bfbZ4wKK0-YyKWsN3KS2NOJ/view?usp=sharing
