### ISSUE TITLE
[Bug]: Paper Mario stop working while playing version 3.0

### ISSUE THREAD

**Issue by tcvduc** [project64/project64#2368]
### Expected behavior?

Working smoothly. 

### Actual behavior?

The video graphic stop working, the audio work as normal.

### Steps to reproduce the problem

1. I met small yellow star 
2. It guild me the double jump skill by press the `A` button
3. After I pressed the `A` button then the Video Graphic stop working. 
<img width="798" alt="1" src="https://github.com/project64/project64/assets/44729657/b5cfa406-9f29-4555-bea1-b659d0a52dad">

### Error messages?
- It stop working at there after I press the `A` button

<img width="801" alt="1" src="https://github.com/project64/project64/assets/44729657/712d3313-472b-451f-a7b8-aaa747221674">

### What game were you playing?

Title: Paper Mario

Nintendo 64 game

ROM information: Paper Mario (U) [V2].z64
Save type: [Paper Mario (U).pj1.zip](https://github.com/project64/project64/files/11829340/Paper.Mario.U.pj1.zip)

### Specifications and build details

Project64: Version 3.0

OS: Window

Graphics: Project 64 Video Plugin 3.0.1.5664-2df-343

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): Project 64 Video Plugin 3.0.1
Audio plugin: Project 64 Audio Plugin 3.0.1
Input plugin: Project 64 Input Plugin 3.0.1
RSP plugin: Project 64 RSP Plugin 3.0.1

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by flagrama** [comment]
Which version of Windows?

**Comment by tcvduc** [comment]
> Which version of Windows?

Window 11: Version 22H2 (OS Build 22621.1848)

**Comment by tcvduc** [comment]
You can see through this video for more clearly
Youtube Link:  https://youtu.be/C7077CI_mxU

**Comment by flagrama** [comment]
Windows 11 does funky memory-related stuff that breaks battles in Paper Mario in older versions. Try out a development version instead.

**Comment by tcvduc** [comment]
Which development version? The Project 64 or The Paper Mario ? Can I get the Link ?

**Comment by tcvduc** [comment]
I download the Project Dev Version 4.0.0 and it's work, thank you very much.
