### ISSUE TITLE
Pokemon Crystal rom doesnt work when i load it into project64 trough pokemon stadium 2

### ISSUE THREAD

**Issue by ExGuestCJ** [project64/project64#2372]
### Expected behavior?

the game working

### Actual behavior?

it softlocks when i start the gb/gbc game

### Steps to reproduce the problem

select a pokemon .gb or .gbc rom and .sav file of the same game, then activate the transfer pak using the n rage plugin, then start pokemon stadium 2, then find the option in the mode slect menu to play the game boy games, then start the game

### Specifications and build details

OS: windows 8.1
Project64-3.0.1-5664-2df3434

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE):project64 video
Audio plugin:azimer's audio 0.70 wip 10
Input plugin:n rage
RSP plugin:default rsp plugin

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Pokemon Tower has only ever worked with full LLE and Interpretter configuration.

**Comment by ExGuestCJ** [comment]
it loaded but there is only audio and the audio is very slow

**Comment by ExGuestCJ** [comment]
> Pokemon Tower has only ever worked with full LLE and Interpretter configuration.

also what do you mean by that?
