### ISSUE TITLE
[Bug]: Shorcuts not working on fullscreen

### ISSUE THREAD

**Issue by LuismaSP89** [project64/project64#2374]
### Expected behavior?

The shotcuts must work even if you're using fullscreen.

### Actual behavior?

The shortcuts for switching to the rumble pack / memory pack are not working in fullscreen (Used with the key + or -) this was tested using project 64 latest dev builds & Nrage plugin.

This shortcuts only work if the emulator is running in a windows. It's not working even if we use an emulated fullscreen. This worked fine in the past.

### Steps to reproduce the problem

1.Open a game in fullscreen (I use turok 2 for example, since this game has a rumble feature and you need to switch the packs after loading the savegame)
2.Press "+" or "-" keys to switch the rumble / memory pack
3. Nothing happens
4. Exit fullscreen & try again, works perfectly.

### What game were you playing?

Title: Any title.

### Specifications and build details

Project64:  Dev-4.0.0-6151-353ef5e (32 bit build)

OS: Windows 11
 
CPU: i5 13600KF

RAM: 32 GB DDR5

Graphics: RTX 4070

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): GlideN64
Audio plugin: Project64 audio plugin
Input plugin: Nrage 2.0
RSP plugin: Default RSP plugin of the project64

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
nrage shortcuts work fine in fullscreen.

actual issue is that you are using keys that have a pre-existing binding for fullscreen mode in  the emulator itself.

![image](https://github.com/project64/project64/assets/1098176/05f11032-93d6-4cd7-a396-3970e7a5cca1)


Emulator bindings take precedent over Plugin.

**Comment by LuismaSP89** [comment]
> nrage shortcuts work fine in fullscreen.
> 
> actual issue is that you are using keys that have a pre-existing binding for fullscreen mode in the emulator itself.
> 
> ![image](https://user-images.githubusercontent.com/1098176/252697316-05f11032-93d6-4cd7-a396-3970e7a5cca1.png)
> 
> Emulator bindings take precedent over Plugin.

Sadly that is not the problem on this case. I have "*" and "/" keys for increasing game speed and speed display on that section. I checked also for every single emulator shortcut in case there is + or - but nope, this keys are only used for Nrage, and they work, but not in fullscreen. When the project64 is on running on small window it works, but not in fullscreen. Please try it yourself and set the keys as following:

![imagen](https://github.com/project64/project64/assets/12205048/f6d161f3-1383-46eb-aa6c-7241f428bc67)

Then, if you press the keys on fullscreen, nothing happens, if you switch to a windowed screen, you can see "switching packs" as following:

![imagen](https://github.com/project64/project64/assets/12205048/2ca70a64-2aaa-407c-ac77-3d05789db4c1)

**Comment by Frank-74** [comment]
It's working here in full screen using the latest dev-6151 zip.  I removed + and - from Project64 Game running full screen hotkeys, and in NRage assigned '=' to insert mempak, and '-' to insert rumble pak.  For some reason Project64's hotkeys registers '+' when hitting the '=' key.  Whereas NRage registers '=' being pressed.  The plus sign is 'SHIFT' + '=' on my keyboard.

Why are you using an old version of the project64 nrage input plugin and not the one that comes with build 6151?

**Comment by LuismaSP89** [comment]
If you are talking about the screenshot of nrage 2.5.3 that's because I downloaded a lot of nrage versions from older project64 versions in order to test it, and maybe I taked the screenshot of one of these by mistake, but yes, I'm using also the latest nrage version that comes with the latest project64 dev build.

**Comment by Frank-74** [comment]
It's working here using GLideN64, GLideN64 stutters and flickers while the 'Switching paks...' message appears in full screen.

**Comment by LuismaSP89** [comment]
Ok, I'm sorry, yes, indeed it works, but the message of the "switching packs" is not shown for me on fullscreen, I don't know the reason. But seems the packs take like 3-4 seconds for switching, if I press the button immediately to go ingame on the turok2  after selecting the rumble pack, it doesn't work. I need to wait like 3 seconds after switching to the rumble pack and then press a key to load the game, otherwise is not working.

So, the main issue here is that the "switching packs" message is not shown on fullscreen, that's the reason I didn't saw that the packs take that time to switch.

**Comment by Squall-Leonhart** [comment]
the message is printed as an overlay,

 it has never worked in true fullscreen mode because we don't have access to the gfx plugins renderer directly, the plugin controls the fullscreen mode not the emulator.

it can be presented on the presentation optimized FSO mode however.

**Comment by LuismaSP89** [comment]
@Squall-Leonhart Ok, then, I'm going to close this. Thanks a lot for helping
