### ISSUE TITLE
[Bug]: Visual bugs in super smash bros 64 (this happens with jabo plugin)

### ISSUE THREAD

**Issue by selvagoat** [project64/project64#2380]
### Expected behavior?

the images of the items that spawns ingame must be medium sized so we can see them and the shield when used should appear too not disappear 

### Actual behavior?

the shield should show perfectly and the items that spawns should also be in the right image size (this happens with jabo plugin)

### Steps to reproduce the problem

1.just play any match use the shield and you'll see it doesn't even appear it's like you're using it but you don't see it.
2.the items, you wait for them to spawn and you'll see how small they are
3. btw it always happens so dont worry

### Error messages?

no errors

### What game were you playing?

Title: Super Smash Bros 64. (U).z64

Nintendo 64 game or Nintendo 64 Disk Drive: Nintendo 64 game

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
Save type: (attach game save or save state here)

Original or modified ROM?: original

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)

OS: (include version and OS build number using WinVer):

CPU:

RAM:

Graphics:

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): Jabo's Direct3d 1.7.0.57-ver5
Audio plugin: Jabo's Directsound 1.7.0.7
Input plugin: N-Rage for project64
RSP plugin: rsp plugin

### Copyright Compliance

- [x] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Jabo is closed source and end of development/support.
