### ISSUE TITLE
[Bug]: Downloads page on pj64-emu.com website not working

### ISSUE THREAD

**Issue by dftf-stu** [project64/project64#2390]
### Expected behavior?

It should take users to a page with the heading "Project64 - Windows Downloads", which then has these options:

Public Releases >>
Development Versions >>
Source code

According to The Wayback Machine, the page was working as of their [most-recent index](https://web.archive.org/web/20231003232816/https://www.pj64-emu.com/windows-downloads), on 3 October

### Actual behavior?

This is what I currently see when I try to visit [the Windows Downloads page](https://www.pj64-emu.com/windows-downloads):

![Project64-Website-Down-1](https://github.com/project64/project64/assets/83965343/22115cd9-1b5e-4a44-ab5e-4e8b1e280f96)

And if I attempt to go direct to the [Development Releases page](https://www.pj64-emu.com/nightly-builds) via a bookmark I have, then I see this:

![Project64-Website-Down-2](https://github.com/project64/project64/assets/83965343/3206a6a9-5a69-4a9b-af2d-d12b546a2bcd)

### Steps to reproduce the problem

1. Go to the [https://www.pj64-emu.com](https://www.pj64-emu.com) website in a browser
2. Click "DOWNLOADS" at the top of the page

**NOTE**: I have tested this on both my laptop (on home Internet), and my smartphone (on mobile data) and can replicate the issue on both-devices, suggesting the issue is not my-side

### Error messages?

Error messages can be seen in the two screenshots provided -- or by simply visiting the website yourself and then clicking on the "DOWNLOADS" link at the top

### What game were you playing?

This section is not-applicable to this type of issue

### Specifications and build details

Website: pj64-emu.com
Registrar: GoDaddy.com
Domain created: 2007-03-21
Domain expires: 2025-03-21
Domain last updated: 2023-03-22
IP address: 52.24.234.69
Page with issue: https://www.pj64-emu.com/windows-downloads
Page with issue: https://www.pj64-emu.com/nightly-builds

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Not applicable to this type of issue

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
working here, force refresh with shift+f5

**Comment by project64** [comment]
@dftf-stu not expected behavior, thank you for telling me.

The server was out of HD space, I cleaned out the logs (2gb). 

I am going to have to cull some of the auto uploads in the nightly releases, it is currently taking up 5.2 gb of storage
