### ISSUE TITLE
V-Rally Edition 99 issues

### ISSUE THREAD

**Issue by DimMan88** [project64/project64#2397]
### Expected behavior?

Expected to run smoothly with my pc specs, as I remember in older projects 64 (1.6 etc) v-rally 99 was running smoothly. Even with older system.

### Actual behavior?

Cannot run in Glide. It pops up cpp error.
I manage to run with the project64 plugin but it is laggy.

### Steps to reproduce the problem

1.run v-rally 99 with glide
2. Run v-rally 99 with project64 graphics plugin . You will see low fps.
3.
4.
5.
...

### What game were you playing?

V-rally edition 99 european version.

### Specifications and build details

Tried latest stable version 3.0.1 of project64 and the latest dev version (Dev-4.0.0-6298-de1288b)

Windows 10 Pro 22H2

CPU: i7 12700k

RAM: 32gb gskill ddr5 5200mhz

Graphics: amd rx6650xt oc 8gb pcie4.0

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): glide64, project64
Audio plugin: default 
Input plugin: default 
RSP plugin: default 

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
> Cannot run in Glide. It pops up cpp error.

PJ64 doesn't ship with a Glide based plugin, and if you're placing on yourself it needs a  glide wrapper.

**Comment by DimMan88** [comment]
> > Cannot run in Glide. It pops up cpp error.
> 
> PJ64 doesn't ship with a Glide based plugin, and if you're placing on yourself it needs a glide wrapper.

Wrong. I didn't installed any third-party plugins. It came with Project64.
![1](https://github.com/project64/project64/assets/71668463/092d096b-2e26-48e9-9e86-4c4fc44cd502)
![Στιγμιότυπο οθόνης 2023-12-02 181442](https://github.com/project64/project64/assets/71668463/4686696f-0176-484d-a436-d57e4693fb7f)
![Στιγμιότυπο οθόνης 2023-12-02 181732](https://github.com/project64/project64/assets/71668463/b492d8f5-e2dd-4e8b-adaa-0740be5dd08c)

**Comment by DimMan88** [comment]
Just deleted all the project 64 installations. 

Did a clean install of project64 and now it works with Glide64 and Project64 plugins with low fps and sometimes it stucks after the PRESS START screen.

**Comment by Squall-Leonhart** [comment]
Thats **not** a glide based plugin, the naming is contrarian.

**Comment by DimMan88** [comment]
> Thats **not** a glide based plugin, the naming is contrarian.

anyway. 
Now tried some older versions. The same.

The game is unplayable so far.

**Comment by DimMan88** [comment]
Found the solution to another emu. 

Rosalie's Mupen GUI. 

Fast, Smooth without any problem. and crystal clear with the same GlideN64.

**Comment by Squall-Leonhart** [comment]
Can't reproduce this reported issue anyhow, probably a bug with the radeon driver. as usual.
