### ISSUE TITLE
Cannot join Discord channels

### ISSUE THREAD

**Issue by DimMan88** [project64/project64#2398]
### Expected behavior?

-

### Actual behavior?

As rules says, I OKed the rules and message the bot but my message is not sent so I cannot view the channels. 

### Steps to reproduce the problem

cannot join discord

### Specifications and build details

-

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

-

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by flagrama** [comment]
This is not relevant to the repository. Don't open bug reports for stuff unrelated to the application. You can use Discussions for that.

**Comment by DimMan88** [comment]
There is no other way to communicate for this.

**Comment by flagrama** [comment]
I literally just told you to use https://github.com/project64/project64/discussions
