### ISSUE TITLE
[Feature request]: Interactive Table of Contents

### ISSUE THREAD

**Issue by Nicmorris1820** [project64/project64#2423]
### Request box

Project64 currently has no table of contents on the readme.  I propose to make an interactive table of contents that will take the user to the desired heading. 

### Reason box

An interactive table of contents keeps users from leaving the repository because they get frustrated trying to find information.  User retention is good for development purposes.  Each new user is a potential contributor.

### Examples

<img width="860" alt="Screen Shot 2024-05-22 at 8 12 33 PM" src="https://github.com/project64/project64/assets/102493952/089dd3fc-4566-4fb7-8a13-c218411f7a10">

**Comment by DerekTurtleRoe** [comment]
@Nicmorris1820 I can work on this a bit tonight, thanks for the suggestion! 😄
