### ISSUE TITLE
Audio issue with Top Gear Rally (U) 32bit Engine Cpu Recompiler

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#249]
The audio is messed up when I enable 32bit Engine, with Cpu recompiler. I assume it's a recompiler issue since, 32bit Engine + Cpu interpreter doesn't have the same issue.

**Comment by dsx-** [comment]
dont enable 32bit engine for this game

32bit engine + cpu interpreter sounds completely broken for me though?

**Comment by LegendOfDragoon** [comment]
>dont enable 32bit engine for this game

I figured it would be better to just disable 32 bit engine.

>32bit engine + cpu interpreter sounds completely broken for me though?

For me it's not completely broken, but the sound is different. Idk how I didn't notice ;/ . I think it still might be a good idea to investigate, since it's worse on recompiler in 32 bit engine.

**Comment by Frank-74** [comment]
Best I can get at the moment is:
Counter Factor=1
VIRefresh=1500
AiCountPerBytes=300
32bit	=No

Sounds best with Azimer 0.7 DS8 WIP4.

**Comment by LegendOfDragoon** [comment]
I agree that Azimer 0.70 DS8 WIP4 has the best audio for this game. Why do you have Fixed Audio timing on though?

**Comment by Frank-74** [comment]
Fixed Audio on and Sync Audio off, stops the audio from disappearing every now and then for no apparent reason.  AI at 300 is the only value I could get the car engine to not cut in and out every second or so, its still a little glitchy.

**Comment by LegendOfDragoon** [comment]
Ah, you're right about the audio disappearing.

**Comment by dsx-** [comment]
what sound do you get with recompiler + 32bit engine? enabling 32bit engine barely sounds any different for me than without

**Comment by Frank-74** [comment]
With 32bit engine, it sounds thin and harsh.  It sounds like playback is in a lower sample/bit rate.

**Comment by dsx-** [comment]
yeah thats what i get, was wondering if dragoon gets the same thing

**Comment by Frank-74** [comment]
I've been messing with the VI values to try and get the music channels playing back in time.  Around 1630-1700, but then the car engine keeps crapping out.  There should be sweet spot for VI's somewhere.

**Comment by dsx-** [comment]
there probably isn't a sweet spot honestly, all of top gear rally's audio processing is done on the cpu and no one has figured it out in the last 14 years i've been investigating this game

**Comment by LegendOfDragoon** [comment]
@dsx- What audio plugin are you using? It's certainly noticeable for me.

>With 32bit engine, it sounds thin and harsh. It sounds like playback is in a lower sample/bit rate.

this sounds like what I'm hearing.

**Comment by Frank-74** [comment]
Okay, improvement using Shunyuan's HLE audio 1.8.2u1.

AiCountPerBytes=300
ViRefresh=1640

Edit HLEAudio.lua with notepad and add these lines to the Top Gear Rally section.
>		SetPlaybackSetting(K_HighQualityAudio, K_TRUE);
		SetPlaybackSetting(K_SyncGameToAudioMode, K_SyncMode_2);

**Comment by LegendOfDragoon** [comment]
Is that with Fixed Audio timing enabled? I know his sounds decent with it enabled, but terrible without it.

**Comment by Frank-74** [comment]
Yes, Fixed Audio enabled.  The VIRefresh value still needs tweaking.  It starts to develop a stutter after a while.  Try the default 1500 and compare it against 1650.

The fixed audio and sync audio options in pj64 2.x can be set in the HLEAudio.lua script.
```
	SetPlaybackSetting(K_FixedAudioTiming, K_TRUE);
	SetPlaybackSetting(K_SyncViaAudio, K_FALSE);

**Comment by LegendOfDragoon** [comment]
How long does the sound last for you guys, when FAT is disabled? I'm determined to get it working w/o FAT. It seems like a good portion of the problem is the audio plugins, rather than the core.

**Comment by Frank-74** [comment]
Start the game, let it run until the demo race starts.  As soon as the lights appear at the start, sound is gone.

**Comment by LegendOfDragoon** [comment]
That's with Azimer's 0.70 DS8 WIP4 right? I suspect the problem are the audio plugins, because some plugins seem to last longer than others.
