### ISSUE TITLE
Rom size of 7zip rom

### ISSUE THREAD

**Issue by harlayzhou** [project64/project64#255]
The rom size in the rom list show "0.0 MBit" that if the rom compress with 7zip.

**Comment by vgturtle127** [comment]
I don't believe 7z is supported in Project64. As far as I can recall, anyway.

I remember trying even ZIP and RAR files and having them give me trouble. I usually decompress my ROMs for emulation.

**Comment by cxd4** [comment]
Yeah I never compress them either.  Everything in the ROM browser for me is uncompressed.

**Comment by harlayzhou** [comment]
![1](https://cloud.githubusercontent.com/assets/8403754/7333545/848af768-eba5-11e4-8403-150e3bde940d.png)

**Comment by vgturtle127** [comment]
I thought zlib didn't support 7z files?

Maybe Project64 recognizes the file type, but doesn't support it? Not sure what to think, I'd have to look into it.

We may be moving from zlib to 7z anyway, so maybe after that it won't matter?

**Comment by harlayzhou** [comment]
@vgturtle127 Project64 support 7z files correctly, you can try it yourself.
It just the display problem.

**Comment by vgturtle127** [comment]
Alright, the problem is probably fairly simple, or just a really small bug.

Once we move everything over to 7z, it will most likely be fixed. I will look into it once my dev machine is up and running.

**Comment by death-droid** [comment]
Project 64 implements the LZMA SDK so yes it supports the .7z file format. Zilmar only did the leg work to upgrade the SDK before to get it to run, so things such as the rom size are probably drawbacks of the upgrade. Probably an easy fix

**Comment by vgturtle127** [comment]
Is it the latest LZMA SDK? Like 9.28/15.00? Or is it an older version?

**Comment by death-droid** [comment]
Fairly sure where using the latest non beta release of the SDK, so 9.20. Looking at the changelogs the newer versions just basicly fix bugs so no major loss in using the older version.

**Comment by MofoMan2000** [comment]
@death-droid I'm still having this issue in a build of PJ64 from May 25 2015, from a fresh GIT checkout. Can someone please verify it was fixed?

**Comment by death-droid** [comment]
I can verify its showing the correct size still.

**Comment by MofoMan2000** [comment]
Ah, got it. I had to refresh the ROM browser first.
