### ISSUE TITLE
Problems in when the eeprom file does not exist.

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#260]
Reading eeprom if the eep file does not exist, data are  0x00.
![crv2_1](https://cloud.githubusercontent.com/assets/11252775/6580050/640a8a54-c791-11e4-973d-8eaa6429b62b.jpg)

fixed
![crv2](https://cloud.githubusercontent.com/assets/11252775/6580053/6cb5b0d4-c791-11e4-8c49-d1cd32929dbf.jpg)

**Comment by project64** [comment]
your fix is merged, can we close this ?

**Comment by Nekokabu** [comment]
ok, closed:)
