### ISSUE TITLE
Dialog is not view correctly in non English Windows.

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#271]
Dialog is not view correctly in non English Windows.

![dialog](https://cloud.githubusercontent.com/assets/11252775/6643451/ad7234ca-c9ef-11e4-80ec-9bcd419cc609.jpg)

Enable "Use System Font", so good.
![dialog2](https://cloud.githubusercontent.com/assets/11252775/6643492/f2e663be-c9ef-11e4-8c3b-5a8f1a31d8fb.jpg)

**Comment by MELERIX** [comment]
is already reported here: https://github.com/project64/project64/issues/190

**Comment by Nekokabu** [comment]
It is another issue.

**Comment by MELERIX** [comment]
oh I see, is related with this: https://github.com/project64/project64/pull/272

**Comment by Nekokabu** [comment]
yes!

**Comment by Nekokabu** [comment]
thanks :)

**Comment by cxd4** [comment]
I like how the title of the issue is:  _Dialog is not view correctly [...]_ (Internet-style "can haz cheeseburger" meme grammar), and when I look at the person who named it, I see a cute kitty cat in the avatar XD.

**Comment by Nekokabu** [comment]
i love google translate ;)
