### ISSUE TITLE
duplicating Advanced options

### ISSUE THREAD

**Issue by MELERIX** [project64/project64#275]
1 - Open Project64.
2 - go to "Options" menu -> "Settings".
3 - Unselect "Hide Advanced Settings"
4 - click "Reset All" button.
5 - Unselect "Hide Advanced Settings" again.
6 - click "Reset All" button again.

and repeat steps 3 to 6 every time you want and you will see this...

![Text](http://i.imgur.com/pWaQckg.png)

**Comment by project64** [comment]
ok https://github.com/project64/project64/commit/f7750c0dd0ae28fef99f49e8eac7e0bcd8133098 should fix it

**Comment by MELERIX** [comment]
yes, now is working fine, thank you ;)
