### ISSUE TITLE
"File -> Open Rom" option does not work with 7z files.

### ISSUE THREAD

**Issue by MELERIX** [project64/project64#277]
the first problem is that it does not detect 7z files in the folder you are exploring, and if you select "All files (.)" and then you try to open a rom in 7z format, you will see the following error:

![Text](http://i.imgur.com/iEs9ofV.png)

**Comment by project64** [comment]
Does zip work fine, I can not remember.

What would you expect happen if it you opened a 7z file that had multiple images in it, just run one of those, the first one it finds ?

**Comment by MELERIX** [comment]
> Does zip work fine, I can not remember.

yes, with zip files works fine.

> What would you expect happen if it you opened a 7z file that had multiple images in it, just run one of those, the first one it finds ?

the same behavior that we currently have with zip files I guess.

btw, I think that 7zip lib can deal with .zip and 7z files, so maybe you can consider remove the old Zip lib completely.

**Comment by project64** [comment]
we could, tho my attention would be elsewhere for awhile, if you like you can create an issue for removing zlib and just using the 7z code. Not sure how big a change that is.

**Comment by MELERIX** [comment]
Fixed in: https://github.com/project64/project64/commit/24cd36481209d1fafcac351689e24a97e238ab2a
