### ISSUE TITLE
Default settings cause garbled speech in TWINE

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#28]
(This issue assumes all default Jabo plugins.)

The speech in 007 - The World is not Enough is quite a PITA. No settings seem to provide perfect
speech + framerate.
#1-With the recently introduced default of Sync Using Audio ON, Fixed Audio Timing OFF, the game runs at a steady 30 DL/s without audio crackling, but the speech sounds garbled like in PJ64 1.6.
#2-With Sync Using Audio OFF, Fixed Audio Timing ON, the game runs at a steady 30 DL/s with correct speech, but the audio goes slightly fast and crackles. This was default PJ64 1.7 setting.
#3-With both Sync Using Audio and Fixed Audio Timing ON (a), or with the above (#2) setting + Sync Game to Audio ON in the sound plugin (b), the audio and speech sound correct, but the game runs at 28-29 DL/s.
#4-Let's not even talk about both Sync Using Audio and Fixed Audio Timing OFF. Vi Refresh 2200 also royally screws the audio.
#3 seems to be closest to the real N64. We should pick one of the poisons above and edit the settings in the RDB to reflect that choice. Also worth noting is that settings #1 and #3a allow for PFR\* , while #2 and #3b allow the user to easily pick their poison via Sync Game to Audio, but do not allow PFR*.

*PFR: Perfect Forwards Reproducibility, a term I just coined for the problem of being able to replicate the exact same game behavior from a set of key strokes, for online sync and TAS recording support.

(Please ignore the links to other issues that were created automatically.)

**Comment by cxd4** [comment]
No. 3 sounds the best combination to me of the 4, so I'd probably just pick that, except yeah, it rockets off my VI/s from 60 to some other weird values in-game.

I'm sure pull requests to the RDB would be happily accepted, except that I guess you can't do another pull request without either learning branches or discarding your currently open one about the plugins / support files.  I would just discard at as I'm almost positive that @project64 has no intention of merging it directly.

**Comment by Frank-74** [comment]
#1 with Azimer's DS8 Audio v0.70 WIP 4 is perfect.  Just make sure you don't have the XAudio2 version in the plugins folder, it conflicts with the DS8 dll.  DS8 is more stable as of the WIP 4.

**Comment by AmbientMalice** [comment]
What about the problem of enabling Fixed Audio timing causing games to judder?

The games with garbled audio all use Factor 5's M.O.R.T sound compression tech. Resident Evil 2, Rugrats, Tarzan, Elmo, TWINE, and a few others. (Tragic that such useful tech was not made more easily available to third part N64 developers.)

http://www.ign.com/articles/1998/01/28/raising-the-speech-factor

There's also games that have garbled music, such as San Francisco Rush 2049, where enabling fixed audio timing KINDA fixes the music but, per usual, causes horribly juddering.

**Comment by LegendOfDragoon** [comment]
When Fixed Audio Timing is enabled, you have to tweak the Ai per byte setting and Vi Refresh.

>To be honest, the entire audio setup for PJ64 is really, really funky. I'm a big defender of plugin-based emulator design, but in this particular case it has caused a great deal of problems.

The problem is not the plugin-based emulator design. Mupen64 handles audio just fine. Even 1964 handles at least certain games better, for audio.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon You certainly have a point there. I just think we need to ensure that not only does the audio for these games work out of the box, but that every audio plugin bundled with PJ64 handles their audio. Otherwise you've got too many complicating factors.

**Comment by LegendOfDragoon** [comment]
Just wondering, but why would you want to use different audio plugins for 1 game? After I do a certain amount of testing, I generally stick to what I like.

Also can you name scenarios where different audio plugins would need different settings?

Ya, it can get complicated when you have all these different options and plugins. I think once audio is handled better in the core, this won't be as big of an issue.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon For example, take Resident Evil 2. Most plugins require fixed audio timing (and, with that, different AI\VI settings to avoid judder) for the voices to play. Except that if you force Azimer's DS8 Audio v0.70 WIP 4 into HLE mode, the audio seems perfect.

Personally, I'd like to see the number of audio plugins PJ64 comes with pared down, or at least one listed as "(Recommended)". Is there any particular reason PJ64 is still using Azimer's 0.40 beta 2?

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon For example, take Resident Evil 2. Most plugins require fixed audio timing (and, with that, different AI\VI settings to avoid judder) for the voices to play. Except that if you force Azimer's DS8 Audio v0.70 WIP 4 into HLE mode, the audio seems perfect.

Well, if my assumption is correct, the reason Azimer's works good is because of an option called "Emulate Audio Interface". If you disable it, I bet you'll need fixed audio timing, just like the other plugins. Although I think Jabo's audio sync is usually good too, aside from framerate issues in certain games.

With an emulator that handles audio better, the need for "Emulate Audio Interface" is non-existent. I really like the way Mupen64 0.5 handles audio. Apollo does a good job as well. I can't say the issue won't be a problem in the future (assuming audio is eventually improved), but certainly less than currently.

>Personally, I'd like to see the number of audio plugins PJ64 comes with pared down, or at least one listed as "(Recommended)". Is there any particular reason PJ64 is still using Azimer's 0.40 beta 2?

zilmar probably never bothered updating plugins for years. I'd imagine the default plugins are the ones recommended.

**Comment by Fanatic-64** [comment]
>Is there any particular reason PJ64 is still using Azimer's 0.40 beta 2?
Where did you download PJ64 from?

**Comment by project64** [comment]
there was a versions of azimers audio plugin in the source control that I recently removed, he may be referring to that. 

At the moment the only audio plugin I release with pj64 is jabo's. It would be really good with azimer wanted to look at the audio code and improve it and use his audio plugin as the default.

Actually I would like pj64 to just use open source plugins if it was possible, which is one of the reasons I replace jabo's input plugin.

**Comment by LegendOfDragoon** [comment]
I'm not a big fan of Fixed Audio Timing, but it does a decent job on Musyx games, so I think this issue can be closed now. I didn't hear any garbled speech, the last time I tested that game with FAT on.

**Comment by Fanatic-64** [comment]
TWINE currently doesn't have garbled speech. Closing.
