### ISSUE TITLE
stereoscopic 3d

### ISSUE THREAD

**Issue by MatthewHunter1983** [project64/project64#289]
I have a black screen in background of ocarina of time while using iZ3D.exe last version 1_13(5443) and running in stereoscopic 3d (it displays correctly with stereo disabled). it DOES work correctly with 3d disabled.  but the 3d looks awesome otherwise 100% of the time. super impressed with development/speed in this emulator. while I am happy to report far less crashes, I am unsure if this is because of recent development or because I installed "all-in-one runtimes intaller" graphics packages updates. the framebuffer effects i am referring to here DO work correctly with the 1964 r146 emulator and the "1964video n64 video plugin community version" graphics plugin with IZ3D stereo 3D enabled. but 1964 has no widescreen hacks :( so it's either 3d w/ pj64 glitched start menu in widescreen, or 3d w/ 1964 barely working start menu effects and various other glitches not present in pj64 and no widescreen. I know 3dtv's haven't really taken off (probably because of all the middleware/configuration required to begin to see decent results--though I LOVE mine) but 3d VR headsets are and perhaps there is a solution applicable to all stereoscopy hardware.

the problem with iZ3D (the only stereo solution i have found for N64 emulation after much experimenting with tridef and nvidia's 3d vision and various other n64 emulators) is that it only runs in windows 7. it WILL not install in windows 8.1 or 10 technical preview, as I have described in elaborate detail on the last 2 posts of this forum:

http://forum.iz3d.com/viewtopic.php?p=41027&sid=5d9179f51a7c572ab253e7d9196cf038

perhaps someone could help figure out how to patch iz3d for new OSs but that project is dead and is probably the worst possible solution. as stated, this game is freaking sweet in 3d, and the widescreen patches in project 64 are freaking sweet. it would be far superior to have it in 3d AND widescreen. maybe someone could implement some stereoscopy within project64 like the newest revisions of dolphin.exe wii/gamecube emulator have added recently so we can abandon windows 7 (please <3). dolphin has various stereoscopy options in d3d mode, and even a side by side format in opengl that doesn't require 3d vision (or even a 3dtv if you cross your eyes or use a wheatstone mirror stereoscope and 2 lcd's lol) ... anyways, it might be cool to implement side by side into glide. but interlaced which only seems to be possible on d3d is best to get the highest resolution.

p.s. totally applicable here: as I mentioned in the dolphin forums, directx12 HAS been released on windows 10 technical preview build 9926 (out right now) and has far better management of multiple cores and a 25% performance increase... if anyone wrote an application in directx12. I am running it right now when I type directxdiag.exe into windows search it's listed there and running.

anyways, I am beyond happy to see such prolific development on this emulator in recent months, and I hope that I live to see the day that one of these stereoscopy solutions is implemented. thanks! <3

**Comment by AmbientMalice** [comment]
Jabo's plugin is closed source, so nothing can be done there. GLideN64 is an upcoming plugin that will feature its own widescreen hack, last I checked. But I don't know about 3D support. I also don't know whether Glide64 supports 3D.

**Comment by MatthewHunter1983** [comment]
still getting black screen in start menu on this game in 3d mode as described above. wish there could somehow be a fix, everything else looks perfect and it is utterly gorgeous in stereoscopic 3d.

**Comment by oddMLan** [comment]
This is an issue with the plugins, not related to the core, and its implementation relies purely on the plugins' side.

Very doubtful this will get implemented as
1) Jabo's D3D8 is closed source and consequently no one can add a stereo 3d mod.
2) No one here has really touched the core PJ64Glide graphics code except to do small fixes and implement some alternate cases for Android.

You're better off asking for support @ https://github.com/gonetz/GLideN64/ , since it's the only plugin being semi-actively developed in the current N64 scene.

Please close this issue.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened

**Comment by AloKhine** [comment]
Hi, the best possibilities to play with your 3d Vision is [here](http://helixmod.blogspot.com/2018/08/nintendo-64-jabos-direct3d-plugin-dx11.html) as far as I know
