### ISSUE TITLE
Game settings error

### ISSUE THREAD

**Issue by Predator82Germany** [project64/project64#29]
When I right-click a game in the browse window & choose game settings this occurs error-window
![game settings](https://cloud.githubusercontent.com/assets/6679921/5892497/28c68f62-a4c1-11e4-8ea6-f5e8b51c684d.jpg)

**Comment by LegendOfDragoon** [comment]
I think maybe it's the graphics plugin you're using. What gfx plugin is that?

I've never seen this error before.

**Comment by cxd4** [comment]
Neither have I.

Usually if Project64 crashed when I went "Edit Game Settings" like he said, the EXE would just, shut down point blank, without showing any error or messages.  In this case it sounds like the guy got some more info about the crashing from wx.

Though I have no idea what `./src/common/string.cpp` is.

**Comment by Fanatic-64** [comment]
Are you beta testing GLideN64?

**Comment by Predator82Germany** [comment]
Gfx plugin is Glide64 Final
This error happens too when I choose options - settings to look after the plugins
May happens at other points too
But Project64 did not close if I choose yes or no but after that he shows the right window

**Comment by twostars** [comment]
Looks like a multibyte character in something that it doesn't like.

**Comment by project64** [comment]
wxstring is inside the plugin, so I suspect there is nothing I can do in the project64 source base that can fix this issue.

**Comment by Predator82Germany** [comment]
Why thenonly I have this problem?
Use Glide64 Final, Jabo DSound 1.7.0.7, N-Rage 2.3c & RSP 1.7.0.9

**Comment by twostars** [comment]
@Predator82Germany: Are there any special characters in any of your paths (ROM? plugin?)? I'd assume that's what's causing it, and the plugin is handling it incorrectly.

**Comment by Predator82Germany** [comment]
C:\Users\WC\Desktop\Project 64 2.1.0.1 is my path for emulator
Rom path is E:\Emulation\Nintendo\64\Roms\No-Intro Romset
All others are set on default

**Comment by cxd4** [comment]
Glide64 does have a lot of localization stuff in it.  I'm not sure but wasn't that removed from PJGlide64?

Any way to reproduce this happening with pjglide?

Why is ProcessRDPList in the call stack of that error message anyway?  Glide64 is a HLE plugin not a LLE plugin, so why would it be calling that if you had RSP set to HLE?

**Comment by Predator82Germany** [comment]
You´re right, with PJGlide64 it didn´t happen
Then it´s a Glide64 fail
Can be closed
