### ISSUE TITLE
Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou!

### ISSUE THREAD

**Issue by theboy181** [project64/project64#290]
not supported in PJ64, but is loading in Mupen64.

unsupported OPcode?

**Comment by theboy181** [comment]
Ganbare Goemon - Mononoke Sugoroku too

**Comment by AmbientMalice** [comment]
Crash is caused by 32bit memory being enabled. Will test Ganbare Goemon - Mononoke Sugoroku.

https://github.com/project64/project64/pull/291

**Comment by AmbientMalice** [comment]
Goemon - Mononoke Sugoroku crash was also caused by 32 bit mode.

https://github.com/project64/project64/pull/292

**Comment by theboy181** [comment]
closing assuming that the RDB gets updated.
