### ISSUE TITLE
Quake 64 missing enemy triangles

### ISSUE THREAD

**Issue by cxd4** [project64/project64#3]
First reported by angrylion to be a (albeit entirely different, and unrelated to this) bug with my RSP plugin.
The RSP interpreter/recompiler plugin with Project64 also has a different LLE graphics bug here.

With the Project64 RSP plugin, it is missing some triangles in the enemy's body:
![nqke0004](https://cloud.githubusercontent.com/assets/1396303/5850220/32bd1c0c-a1bf-11e4-8d64-a1e5fdf6fcae.png)

With my RSP plugin (also ziggy's port of MAME LLE), the result is correct:
![nqke0000](https://cloud.githubusercontent.com/assets/1396303/5850236/6456dba4-a1bf-11e4-8b7a-6bbe6ec7fec1.png)

To the best of our knowledge this is not a CPU core/VR4300 issue and is only a RSP issue.
I am self-assigning myself this one and plan to investigate it myself.

Here is the Project64 saved state that angrylion sent me via e-mail all those months ago just in case somebody else feels like looking at it:
https://dl.dropboxusercontent.com/u/16494013/n64/Quake%2064%20%28U%29.pj.zip

**Comment by project64** [comment]
is this comparing the rsp plugin with a different one?
just trying to understand if it is a RSP/RDP/r4300 issue

also making sure it is a recompiler/interepter issue if it is RSP

**Comment by cxd4** [comment]
The comparison is Project64's RSP plugin to my own, and ziggy's MAME RSP.

The issue happens only on Project64 RSP 1.7.0.9 Interpreter, or RSP 1.7.0.9 Recompiler.  It does not happen with other RSP plugins.

**Comment by cxd4** [comment]
This is now fixed in the interpreter side.

Interestingly enough, the recompiler part of RSP 1.7.0.9 still has some similar (although slightly more extreme variation) graphics bugs in the exact spot of the game.  There may be one or more [un-]related defects in the recompiler code, so technically I think I should leave this issue open rather than close it right away.

**Comment by project64** [comment]
should be fixed in the recompiler now to.

Comparing MFC2	A1, $v2 [2] (A68)
to LLV	$v1 [0], 0x0000 (A1) (A6C)
Swapped A68 and A6C

which was wrong

fixed in https://github.com/project64/project64/commit/1e1249903dca205956255ab311c4864cce1a2d4a

**Comment by cxd4** [comment]
yep beat me to it
