### ISSUE TITLE
Indy Racing 2000 Core Issues.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#310]
This game doesn't work with Interpreter, and only works with Recompiler if Register Caching is disabled.

edit:
Enabling FAT will allow the game to run with Reg Caching enabled, and also Interpreter.

**Comment by LegendOfDragoon** [comment]
Works fine for me with register caching. Same with interpreter.

I don't think it's a core issue. It's just an issue with certain audio plugins, afaik. Jabo's (with audio sync on) & Azimer's both work fine (without FAT enabled). It has to do with AI emulation.

**Comment by AmbientMalice** [comment]
I'm unable to get to the main menu using Interpreter without FAT, regardless of which audio plugin I use. FAT fixes it, though. Reminds me of Aidyn Chronicles, which refuses to boot without FAT.

Also, the game has some weird framebuffer stuff going on. Normally, the game will simply crash the emulator if you try to start a race with framebuffer enabled with Glide64. But enabling CPU framebuffer writes displays what looks to be an ingame crash.
![glide64_indy_racing_2000_02](https://cloud.githubusercontent.com/assets/10704701/6800362/74b3275c-d269-11e4-947c-b4b3f0725353.png)

**Comment by LegendOfDragoon** [comment]
>I'm unable to get to the main menu using Interpreter without FAT, regardless of which audio plugin I use. FAT fixes it, though.

Could be undefined behavior, or it's a recent regression. I'll try testing on latest version, later today perhaps. I'm using a build that's about 2 weeks old. For me, I only have issues when using audio plugins like zilmar's audio, 1964 audio, or Jabo's (with audio sync disabled).

**Comment by theboy181** [comment]
>Reminds me of Aidyn Chronicles, which refuses to boot without FAT.

This seems to boot and run for me with FAT disabled.

**Comment by AmbientMalice** [comment]
>[Aidyn Chronicles] seems to boot and run for me with FAT disabled. 

Ah, I goofed. It has a problem with certain audio plugins. Shunyuan's, for example, which produces this error without FAT.
![glide64_aidyn_chronicles_01](https://cloud.githubusercontent.com/assets/10704701/6816273/99fb4760-d2dc-11e4-889e-f73036cb5719.png)

I'll make a pull request to disable FAT for the game.

**Comment by cxd4** [comment]
i guess if pj64 had audio plugin code included in the repository this "issue" would be more subject to fixing

Until then I guess it's just RDB controversies and the assumption that probably people use Jabo's dsound.

**Comment by AmbientMalice** [comment]
@cxd4 The game is "fixed" for the time being, I'll close the issue.
