### ISSUE TITLE
Possible fix for Jabo D3D8 plugin on Intel HD Graphics

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#314]
There is a known issue in which Jabo's graphics plugin, on computer with Intel HD Graphics (or GMA, or Iris Pro), often doesn't render "decal" textures (such as shadows, pathways on the floor, etc), or renders them with z-fighting.

On the PJ64 forums, some members discussed an aparent solution for the problem: http://forum.pj64-emu.com/showthread.php?t=4948 It involves using a program to force Direct3D 8 applications to use a 24-bit z-buffer. I went to test it myself and can also confirm that it works.

So I was wondering, Jabo's plugin is closed source, but could it be possible to force it (or D3D8 plugins in general) to use a 24-bit z-buffer from Project64.exe? I know it sounds rather hackish, but there's no apparent detrimental effects to it, and computers with Intel IGPs amount to a large percentage of currently sold PCs, so it would be nice to have Jabo's plugin working correctly on those PCs.

**Comment by cxd4** [comment]
Goodbye, GitHub Issues.  It was nice knowing you.

**Comment by Fanatic-64** [comment]
I would actually go ahead and delete this issue, but I still think it may be somewhat useful for zilmar, so I'm not going to affect others for the sake of pleasing you. If he doesn't like it, he can remove it.

**Comment by cxd4** [comment]
Well, at least you're not like, downright serious about it I guess.  That's a relief.

Dunno how you'd expect it would be useful for mr. zilmar though.  What could be useful to him is if he had control over Jabo's plugins, although he does not.  Tell you what this could be useful for:  Get Intel to fix their stupid drivers so this hack util wouldn't be needed.  But then, I suppose that would mean "fixing" and then "un-fixing" this issue by statically linking the DirectX driver access code needed to do the hack on pj64's side internally, only to remove the dependency in the end once Intel got their act together.

And actually no, he can't remove it.  GitHub issues aren't vBulletin threads--they're not deleted; they're either opened or closed.

**Comment by Fanatic-64** [comment]
I'm actually on my way to register on the Intel support forums to pester them about this issue.

Remove/close, I just took a liberty with my terminology. Besides I haven't looked for a Delete button in issues.

**Comment by cxd4** [comment]
Well I doubt I need to say this, but if I were him I'd have probably just closed issues like this.

The reason he doesn't is probably because it looks assy if he closes the issues without gaining the explicit approval of the issue starter (which in this case would be you).  It's just a negative impression when the person in total power and control over a project does all the closing...it just looks not as bad when the issue starter himself is happy and closes the issue himself, rather than necessarily forcing the repo owner to close it.

**Comment by LegendOfDragoon** [comment]
@Fanatic-64 you're free to close this issue, if you'd like :smile:

**Comment by Fanatic-64** [comment]
Closing as I'm opening a new issue to deal with the problem.
