### ISSUE TITLE
ROMs don't close properly

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#316]
When opening a ROM, and then closing it by pressing F12 (not closing the emulator), the title of the previously opened ROM stays in the Title Bar, and when opening the Options menu, the section for the settings for that ROM is still there.

Those things should probably be cleared when closing the ROM.

**Comment by Frank-74** [comment]
At the moment, its the only way for a plugin change to succeed after ending emulation.  By using the Options menu, config game plugin setting.

After ending emulation and changing plugin with Edit Game Settings, the game starts without your plugin change.

**Comment by project64** [comment]
well it is end emulation, not close rom .. the rom and all settings are still there, so you can do end emulation/start emulation.

would you prefer an option for close rom instead of end emulation?

**Comment by Fanatic-64** [comment]
I had forgoten about the option to end emulation without closing ROM.

Maybe you could add an option to press Shift+F12 to close the ROM?

**Comment by project64** [comment]
maybe a feature for 2.3

**Comment by cxd4** [comment]
For what purpose?

If you just need to free up memory you would close Project64.
If you just need to free the ROM to play a different ROM, you would open a different ROM.

That being said, I don't really find the differentiation between "emulation" (start and end) versus ROM (start and end) to be intuitive myself.  Emulation mostly ends when execution ends...whether the cart is still stuck in the N64 control deck doesn't seem emulation-related to me.  However this is something of a matter of personal opinion, so I wouldn't want to make an issue out of that.

**Comment by MELERIX** [comment]
also the VI/s remain visible even when the ROM was already closed.

**Comment by MelchiorGaspar** [comment]
this may be similar/related...

ex: 
- I start PJ64, 
- then I load a rom, Aidyn Chronicles - The First Mage (U)(v1.1).z64
- it loads the memory graphics cache

- I close the rom shortly there after.... I go to start same rom again )probably same if i chose a different rom too..)  it freezes during the mem cache loading.... I can close the GUI but PJ64 exe remains in task manager till I kill the process.

**Comment by cxd4** [comment]
>as I am running XP64 I cannot use VS as it was too much trouble for me so I cannot compile PJ64 ;_;

@MelchiorGaspar are you able to run Visual Studio Community, 2013 on XP 64-bit?
That is where the issues have been with PJ64 on XP, but VS2008 builds should have worked fine.

Sorry, yeah there are way too many dependencies at the moment to compile with MinGW, just VS2008 or 2013.

**Comment by MelchiorGaspar** [comment]
no the newest I could install was 2010 but it would crash on load so it was not functional on XP
so vs2013 c.ed will not even launch the installer...

VS2008 PJ64 builds work on XP...


but from the destruction of all my custom File type associations for programming src files last time I tried I won't even risk trying to install vs again ;_; >_<

**Comment by MELERIX** [comment]
@MelchiorGaspar I'm wondering why you are suing XP64 ? if you can run XP64, then you can perfectly run Windows 7 SP1 64 bits.

**Comment by MelchiorGaspar** [comment]
drivers, the last support driver were for Vista64
http://www.asus.com/Motherboards/P5NSLI/HelpDesk_Download/

I prefer XP the look and feel and IT  NOT BLOATWARE... ;_;
XP64 uses around 200MB to 300MB ion startup and nott he 1GB monster that is 
Win7 (prefetch enabled, Superfetch (enabled for OS only, disabled for general apps)

I have 7 Ultimate 64bit on an old laptop given to me a couple of years ago...
the only programs that have made it bearable are as follows
- Types  -- File Type Association Editor   
    http://ystr.github.io/apps/types/
    http://ystr.github.io/apps/types/new.rss  <-- changelog

-  Agent Ransack  --  Version History  http://www.mythicsoft.com/agentransack/history
   I disable the Win7 inline search system and use this when I need it saves on system resources.

- http://www.eventlogxp.com/  
in place of the OVER BLOATED windows Event viewer on the newer windows..

just to name a few... plus others...

tough i have been able to find enough  Win7 Drivers that will work I tried it on an old HDD.. not sure it was having internet connection issues... and it did have the net drivers for 
Marvell Yukon Gigabit NIC
Marvell uses a kind of universal driver for its NICs ^_^

**Comment by Lithium64** [comment]
@MelchiorGaspar It will work fine on Windows 7, the OS will handle chipset drivers you will only need install audio and gpu drivers.

**Comment by MelchiorGaspar** [comment]
no no those won't do, those are for Intel...

.. I have an 
- ASUS Mobo P5NSLI  (w/ Nvidia nForce Chipset)
- SoundMAX AD1986A ADI 

I already have all the right drivers...
http://www.asus.com/Motherboards/P5NSLI/specifications/
http://www.techspot.com/drivers/driver/file/information/17264/

nvm these might work... I will hold on to them and see the next time I try out 7 on that old HDD
the driver I current have are as follows...
- SoundMAX Audio Drivers (AD1986A)(v5.10.2.6110)(Win2K to XP)_64bit
- SoundMAX Audio Drivers (AD1986A)(v6.10.02.6585)(WinVista to Win7)
- SoundMAX Audio Drivers (AD1986A)(v6.10.02.6620)(WinVista to Win7)  <<-- Link u posted.


plus I found these for XP...
https://downloadcenter.intel.com/download/18658/Audio-SoundMAX-Audio-Driver
SoundMAX Audio Drivers (AD1986A)(v5.10.01.6610)(Win2K to XP)_32bit
SoundMAX Audio Drivers (AD1986A)(v5.10.02.6610)(Win2K to XP)_64bit

UPDATES!!! OH YAhh!  crossing my fingers they work wish me luck loi ;D
going to try them out now

**Comment by MELERIX** [comment]
@MelchiorGaspar chipset drivers for that MB will be installed automatically in Windows 7, and the audio maybe will be installed from Windows Update.

**Comment by MelchiorGaspar** [comment]
but Windows update does not always he most up to date drivers.. ;D
 as a PC Enthusiast and etc, I know the innards of a PC intimately ;D loi

**Comment by MELERIX** [comment]
I know, just letting you know that if you can't find the audio drivers maybe Windows update will install them for you.

**Comment by MelchiorGaspar** [comment]
no good those drivers were as I originally thought, Intel motherboards so it would not install at all ;_;


mine:
HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_1043818F

supported:
HdAud1986, HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_8086A101
HdAud1986, HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_8086A201
HdAud1986, HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_8086A301
HdAud1986, HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_8086A401
HdAud1986, HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_8086A501
HdAud1986, HDAUDIO\FUNC_01&VEN_11D4&DEV_1986&SUBSYS_8086A601

**Comment by Fanatic-64** [comment]
Now THAT is worthy of "Goodbye, GitHub Issues. It was nice knowing you".

http://forum.pj64-emu.com/forumdisplay.php?f=9

**Comment by oddMLan** [comment]
>Maybe you could add an option to press Shift+F12 to close the ROM?
Why not F13 instead?

**Comment by LegendOfDragoon** [comment]
Has this been fixed?

**Comment by oddMLan** [comment]
>Has this been fixed?
Last time I checked, no. That was like 3 weeks ago though.

**Comment by cxd4** [comment]
Install the F13 key into your keyboard device.

(issue closed)

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
