### ISSUE TITLE
OpenGL v-sync option

### ISSUE THREAD

**Issue by theboy181** [project64/project64#330]
Could Pj64 add a feature that would allow the V-sync function work for OpenGL plugins?
I was talking about the feature for GLiden64 with Gonetz, and he had the following to say.

>Mupen64Plus build has V-Sync option. Please check is it work for you.

>V-Sync is tricky. It's not core OpenGL feature. Actual implementation is platform dependent, thus I did not want to bother with it. Mupen64Plus takes care about graphics context creation on itself, so it was free for me to add V-Sync for that emulator.

I don't feel that using Mupen is an option for v-sync.

any thoughts?

**Comment by project64** [comment]
I have never used mupen, what is it, what would be needed in the core to change for this?

**Comment by cxd4** [comment]
First, Project64 does not use the Mupen64Plus plugin system.  Unless I'm missing something and OpenGL context creation is being done within Project64.exe itself and not left up to the plugins as it should be left up to them, this question has little to no relevance to Project64, or any emulator with a sane plugin system implementation for that matter.

Second, the terminology is misleading.  A vertical sync refers to essentially the swapping of buffers (usually just a front and a back buffer, called "double-buffering").  What you and Gonetz were really talking about was controlling the *swap interval*:
https://www.opengl.org/wiki/Swap_Interval

Controlling the buffer swap interval is done only via hardware/driver-specific extensions to WGL or GLX which must be loaded as function pointers at run-time.  OpenGL is not a video DAC API or a refresh rate controller; it has to be done outside of the OpenGL server and within the context handling it.

**Comment by cxd4** [comment]
If a plugin updates the pixels in the Project64 emulator window, it already does vertical synching.  (Hopefully you knew that's what "v-sync" meant.)  So unless we have some practical comparison or example on the basis of this suggestion, I'm not seeing the issue here.

**Comment by theboy181** [comment]
Here is some context

https://github.com/gonetz/GLideN64/issues/331#issuecomment-86645138

**Comment by cxd4** [comment]
Okay.

On Project64, do you use PJ64 Glide64 or Jabo's Direct3D8?

**Comment by project64** [comment]
actually has nothing to do with project64 .. there is nothing we do as the core does not touch or use any of the chosen gfx api. It is all up to the plugin to implement it. Since mupen is doing some opengl gonetz can leave it up to the emu to do that.

Does it work correctly on mupen, if so I am sure gonetz can add the same method if he chooses to
