### ISSUE TITLE
PJ64 Memory Usage

### ISSUE THREAD

**Issue by MELERIX** [project64/project64#335]
Project64 2.2.0.2 consume high memory after having choosen the ROMs directory (ROMs are in 7zip format), for first time.

PJ64 eats around 200-300mb of RAM.

**Comment by project64** [comment]
depending on how many files you have the 7zip file it can take that much memory to extract the zips

**Comment by MELERIX** [comment]
well, I have 22 roms and the folder size is 264mb so it makes sense that PJ64 consume a similar amount of memory when extracts the roms.

the trouble is that when the operation has finished, it still continue using the same amount of memory for several minutes, like if PJ64 is not capable to clean the memory instantly after finish that operation.

**Comment by oddMLan** [comment]
#418 I wonder if updating the libs would alleviate the issue.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
