### ISSUE TITLE
Plugins should be able to register hotkeys

### ISSUE THREAD

**Issue by project64** [project64/project64#336]
glide has some hotkeys to change effects (https://github.com/project64/project64/pull/334) when I configure the emu you should be able to set/change/see the hotkeys from the shortcut menu

**Comment by cxd4** [comment]
Maybe useful, though I was hoping there would be a way to prevent key stroke messages from listening in on Project64::Glide64 if the window wasn't currently active e.g. typing in a different window, that way there wouldn't be a need to change the keyboard shortcut at all to begin with.

I don't know how any of these plugin classes or spec extensions, optional/required in the spec etc. so couldn't comment beyond that.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
