### ISSUE TITLE
PJ64 v2.2.0.3, titlebar, savestate loading issue etc

### ISSUE THREAD

**Issue by MelchiorGaspar** [project64/project64#343]
OK SOMETHING IS F'D UP IN PJ64 v2.2.0.3....  

I update my files, and redo the config for the plugins

Options --> Settings --> plugins (I rename the files so it shows their version #)

I go to launch SW - Shadows of the Empire (U)(v1.2)
title bar thinks its "Hybrid Heaven (U)"

but SW - SotE does load only problem is it thinks its "Hybrid Heaven (U)"
 so it trys to load  Hybrid Heaven (U)'s SAVESTATE!! WT* @_@ <_<

so  I try loading Hybrid Heaven (U) and it save state loads fine....

i try running it through WinDbg... 1MB log file most of which are endless SIGSEGVs

(3ac.810): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
78cce667 8b3c03          mov     edi,dword ptr [ebx+eax] ds:002b:5b659af8=????????

that was the first one, before which is a LOT of NULLs 122,487 to be exact!... (padding?)
before the NULLs 
F:\EmulatorsRoms\N64_PJ64_Beta\Plugin\Input\PJ64_NRage_Input_v2.4.0.4.dll

and i didn't reach rom finally loading... just init.
here is the log file in a 7zip archive to save space
https://www.dropbox.com/s/lgj8udo1kd1tiv7/PJ64_windbg.log.7z?dl=0
PJ64_windbg.log.7z
compressed   :  2.30 KB (2,360 bytes)
uncompressed: 1.12 MB (1,181,192 bytes)
Log file SHA1:  20F7480BAF252709EF99B848D8612C91F878E20B

**Comment by MelchiorGaspar** [comment]
PJ64 saves
https://www.dropbox.com/s/eaox8flodthsb03/PJ64%20-%20saves.7z?dl=0

**Comment by MelchiorGaspar** [comment]
using the updated config, lang, plugins from the v2.2.0.3_rc1 archive, I tested the exes for this bug,
- v2.2.0.2  -- not present
- v2.2.0.3  -- present
conclusion main exe contains bug...

**Comment by MelchiorGaspar** [comment]
![pj64 v2 2 0 3_title savestate bug](https://cloud.githubusercontent.com/assets/1712842/6889443/0db60890-d664-11e4-80d3-c60af2497908.png)
![pj64 v2 2 0 3_title savestate bug_ss-load](https://cloud.githubusercontent.com/assets/1712842/6889445/123846b2-d664-11e4-8f1a-fbc671cf6726.png)

**Comment by MelchiorGaspar** [comment]
weird... I tried again loading v2.2.0.3 exe.. tried loading
- Aidyn Chronicles - The First Mage (U)(v1.1).z64     -- no issue... Savestate loads fine

- GoldenEye 007.z64 
-- savestate taken in v2.2.0.x is not loading...
     hangs at 1-4 fps blank screen, with 50% to 80% CPU usage


- Hybrid Heaven (U)[!].v64                                           -- no issue...  Savestate loads fine

- Star Wars - Shadows of the Empire (U)(v1.2).z64    -- bug occurs... O_o <_<

**Comment by cxd4** [comment]
Evidently related:  https://github.com/project64/project64/issues/225

**Comment by Predator82Germany** [comment]
Corrupted ROM?

**Comment by MelchiorGaspar** [comment]
no it was differently Project64.cfg corruption

**Comment by MelchiorGaspar** [comment]
the thing is it didn't show up when running v2.2.0.2 vs v2.2.0.3

**Comment by LegendOfDragoon** [comment]
I'm pretty sure this is fixed now @MelchiorGaspar .

**Comment by MelchiorGaspar** [comment]
It was definitely Project64.cfg corruption!.....

I manually started with a fresh ini and manually copied over the setting blocks from my old but clean settings file...

that and I think some one made a fix, cleaning up what was causing the corruption from a code standpoint.
