### ISSUE TITLE
Rebinding keyboard shortcuts are pretty bugged

### ISSUE THREAD

**Issue by ImSpecial** [project64/project64#350]
So I gave the recent release of PJ64 a go today and the first thing I did was strip all the default shortcuts in order to change them more to my liking, only I couldn't because even though they weren't it said they are still in use. Some examples, Changed Esc (which was fullscreen) to Pause game but couldn't, wanted to change Save/Load States to F1 and F4 respectively but couldn't, also I moved Turbo to my Tab key (originally F4) but Tab also acted as some "Mouse Lock/Unlock" shortcut, can this be removed so the Tab key can be used for other things?

**Comment by AmbientMalice** [comment]
Are you running PJ64 with administrative permissions?

**Comment by ImSpecial** [comment]
Yuppers.

**Comment by cxd4** [comment]
The Tab mouse lock/unlock thing is within the N-Rage 2.3 plugin which I do not use.  If you use some versions of N-Rage input then you might have to go into the config to deactivate the "Mouse Lock/Unlock" keyboard assignment to Tab within the NRage configuration itself.

It is quite an annoying default to have however.

**Comment by cxd4** [comment]
I see that NRage for PJ64 is still using an INI file actually not a RDB file...surprising.

**Comment by naqaden** [comment]
Keyboard shortcuts can be manually edited in Config/Project64.sc3

It seems this bug is caused by P64 looking for conflicts with default keys instead of current assignments. One workaround is to erase the contents of Project64.sc3 which will erase all defaults. Consider making a backup!

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
