### ISSUE TITLE
Ms. Pac-Man:  Maze Madness, Address Error exception

### ISSUE THREAD

**Issue by cxd4** [project64/project64#352]
For those of you who know how to play the game, here's my mempak I saved:
https://dl.dropboxusercontent.com/u/16494013/n64/MS.mpk

If you don't know how to play the game, try loading this saved state and waiting a few seconds:
https://dl.dropboxusercontent.com/u/16494013/n64/Ms.%20Pac-Man%20Maze%20Madness%20%28U%29.pj.zip

![pacmanae](https://cloud.githubusercontent.com/assets/1396303/6985855/a300118a-da05-11e4-8e13-48495d1b6719.png)

RDB settings:
![pacmandb](https://cloud.githubusercontent.com/assets/1396303/6985863/af730d96-da05-11e4-984c-34cbcb4603c3.png)

Loading the saved state on Project64's RSP plugin might not work if you have LLE graphics or LLE audio due to the way that the RSP timer is being handled, so either use HLE graphics or load the saved state with my RSP DLL.  It was created however with LLE graphics and audio, which did not prevent the "Address Error" MIPS exception at all.  Neither does disabling "Use TLB" or "Fixed Audio Timing" as well as all the factory default RDB settings I had to begin with before trying to figure out why the end of this level kept crashing.  If you use the re-compiler, you will obviously get a different, more generic error message.

**Comment by cxd4** [comment]
If you reproduce without loading the saved state (boot ROM, load from mempak then start the level on your own), it's something of a two-thirds chance you will get this Address Error crash before reaching the end of the level, at random/unpredictable parts during the level.  The only *guaranteed* point of the level where it's always crashed for me 100% of the time, fixed audio or no fixed audio, is at the very end on level complete, so that is why I made the saved state at that point.

**Comment by oddMLan** [comment]
Reproduced and confirmed. Weird game, weird issue.
I remember a lot of time ago I messed with the CF and that somehow triggered other errors, most frequently near the end of a level, but they weren't fatal, levels could be completed successfully.

PD: Why RSP Audio Signal?

**Comment by cxd4** [comment]
It might happen on a genuine N64 which might make this a non-issue, other than how all of the emulators are failing to recover from it.  At the moment I'm running Linux so can really only debug this issue on Mupen64 now, but I'll see if I can't use that to debug where in the interpreter life-cycle the Address Error exception arises.

>PD: Why RSP Audio Signal?

I doubt I needed it.  I was probably just flipping all the RDB settings en masse to see if anything fixed.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
