### ISSUE TITLE
Brazilian translation plus problem with settings window

### ISSUE THREAD

**Issue by Felipefpl** [project64/project64#353]
Hi, here is my updated translation http://www.4shared.com/archive/S39gVh0Pba/Brazilian_Portuguese_Project64.html and i wanted to report that pj64 needs a new settings 50% bigger or more than it is now, i had to cut several words to make room for translations because of the small size.

**Comment by cxd4** [comment]
I tried to download your translation for you, but can't figure out that nest of payware download servers.

Either find a way to do the pull request or commit these changes on Git yourself, or find a better upload method.

**Comment by AmbientMalice** [comment]
I recommend something like MEGA or Sendspace.

**Comment by Felipefpl** [comment]
cxd4 - you dont need to pay or register to download anything, just click at the "Download" button at the side of "Share" button, then on next screen click on "Free Download" and that's it. No need to save it in any other server. Ppl download files from me without problems.

**Comment by cxd4** [comment]
>just click at the "Download" button at the side of "Share" button, then on next screen click on "Free Download" and that's it.

That it ain't for me.

Once I click "Free Download" it starts to ask me to either:
* Download with Facebook
* Download with Twitter
* Download with Google+
* Download with Instagram

None of those are viable options for me, for the following reasons:
* Facebook sucks.
* Twitter sucks.
* Google and Google+ both suck.
* Instagram sucks.  Even though I have no idea what it is and haven't even heard of it before except like twice or thrice, but whatever it is I'm pretty sure without looking it sucks.

None of those should be a requirement to downloading your file, nor should I have to register an account somewhere.  There are plenty of sites that offer a free download way more directly than that without the need for registration to anything, so find one or use one of AmbientMalice's suggestions.

**Comment by Felipefpl** [comment]
well, only you have this problem, lots of ppl downloaded my files without complaint so i'll keep it like this.

**Comment by Felipefpl** [comment]
well, only you have this problem, lots of ppl downloaded my files without complaints about things, they didnt need to download through them so i'll keep it like this.

**Comment by Felipefpl** [comment]
Well, only you have this problem, lots of ppl downloaded my files without complaints about things, they didnt need to download through them so i'll keep it like this. Also, i tested the download myself to ensure there werent any problems.

**Comment by cxd4** [comment]
Then you're going to have to wait for someone to back you up on that claim, because you refuse to upload this file in a convenient and accessible way or to do the PR yourself.

**Comment by Felipefpl** [comment]
Sorry, i admit i was intolerant, here is the file in another server http://ge.tt/api/1/files/7pgKalD2/0/blob?download

I dont understand why the download doesnt work, just clicking on free download would bring the dialog box with the options to open/save the file...

**Comment by cxd4** [comment]
Works much better, thanks.

Why the other download didn't work?  Could be different browsers (tried a couple), could be different plugins or absence of plugin, could be that nobody else minded to download through those other affiliations, could be that if you have an American IP address or something you have to go through them, could be that people either didn't mind going through third-party download or had an account there and got the direct download quicker.  All I know is that didn't work out for me.

I filed the pull request with your modified language file here:
https://github.com/project64/project64/pull/355

**Comment by Felipefpl** [comment]
cxd4 - no idea, i use opera with adblock plus and i dont get any requests to download from google, twitter, etc and ppl here from brazil never reported any problems to me and my files were downloaded dozens of times already.

Thanks for submitting my file and sorry again for my behaviour.

**Comment by LegendOfDragoon** [comment]
Please close if resolved :) .

**Comment by cxd4** [comment]
His commit was never merged.  It was manually re-done by Lithium64 because they had some disagreements over which proper grammar is better grammar.

> i wanted to report that pj64 needs a new settings 50% bigger or more than it is now, i had to cut several words to make room for translations because of the small size.

And I guess that was why he filed the actual issue.

**Comment by oddMLan** [comment]
Please close since #148 #150 #301 have been merged and superseded this.
@project64
