### ISSUE TITLE
64DD games not working.

### ISSUE THREAD

**Issue by theboy181** [project64/project64#360]
unable to play 64dd games.

**Comment by oddMLan** [comment]
Haha, good one!

**Comment by AmbientMalice** [comment]
64DD games are already running on MESS. It's really a matter of drastically rewriting PJ64's rom handling to handle DD files, and also hope they actually run on PJ64.

**Comment by theboy181** [comment]
Was reading some comments over at dev64. They are wondering ehen hle dd64 will be a reality.

**Comment by vgturtle127** [comment]
This is probably something larger in scope then just an "issue". This would be more like a feature request.

I'm not sure which method of emulation MESS uses for the N64DD, but Project64 can already run the IPL, so really I can't see why with some work and some research we can't put something together. :smiley:

**Comment by Fanatic-64** [comment]
The N64DD has it's own co-processor and some other stuff, it sure wouldn't be trivial to emulate, and the actual device is needed to reverse-engineer it, and I doubt zilmar owns one.

**Comment by cxd4** [comment]
>This is probably something larger in scope then just an "issue". This would be more like a feature request.

Agreed.
N64 emulation issue implies there is an issue with emulating the N64.
Project64 issue implies there is an issue with Project64's N64 emulation.

In this case neither is true, but I guess it's worth presuming that the objective is simply to raise a constant reminder that N64 emulation isn't enough in all cases.  I personally have not at all looked at DD hardware so would know less about it than any end user would, but I imagine somebody would probably care to implement it later down the road.

**Comment by vgturtle127** [comment]
Actually, I believe the co-processor inside the DD is the exact same MIPS R4000i CPU the N64 uses (if I'm not mistaken). I think there might be another chip for reading the magneto-optical disks, but other than that I think it mainly relies on the N64 for everything else.

I don't think you would actually need one to reverse-engineer it, you could just look at the MESS driver and see how it works. I'm not saying it would be a quick 10 minutes of work or anything, but it would most likely be easier than we think, with most of the heavy lifting already done (games dumped and an open-source emulator available). Just my two cents. :smile:

**Comment by cxd4** [comment]
Main CPU that N64 uses is a modified R4300i, the VR4300.  The R4000 was the subset and superset to the co-processor that the RCP used for the RSP.

But yeah.  Think I last looked at MAME a few years ago when I was fetching updates to the software renderer z64 LLE used which was way older MAME, never thought about any 64DD stuff.

**Comment by vgturtle127** [comment]
@cxd4 Oh YEAH! I forgot about that.

I'm kind of surprised more emulators haven't added support already, since most of them borrw code from MESS all the time. :open_mouth:

**Comment by LuigiBlood** [comment]
64DD doesn't have a co-processor, and the only thing it does is disk reading/writing operations, and Real-Time Clock. And there's an IPL ROM that Project64 does not really support: You can run the development IPL4ROM, but it's not the retail one. You need to run the retail one.

(The disks are magnetic and not magneto-optical, by the way.)

**Comment by theboy181** [comment]
@LuigiBlood 

Have you had time to get the retail ROM working in PJ. ?

**Comment by LuigiBlood** [comment]
Sorry but I'm so unfamiliar with PJ64's code to really do anything useful by now.
Not to mention from someone I know, getting all 64DD games to work will need some serious changes. Something I am definitely not good at. I'll probably do something on CEN64 but for now I'm busy on other things.

**Comment by vgturtle127** [comment]
@LuigiBlood Thanks for the clarifications, I'm going to change my documentation and update some source files now. :smile: 

I already have a build of CEN64 that can run the Randnet disk. Unfortunately, some other stuff isn't done and nothing else boots. And the Randnet disk has many bugs and glitches. And crashes mostly. And most N64 games don't boot for some reason. Still needs a lot of work. Although, I haven't tried Ura Zelda... :laughing: 

I forgot to mention, I don't have the RTC emulated either, which causes boot error messages when you don't have a disk inserted. You then have to set the time, I believe. Unfortunately, it crashes. :cry: 

It takes code from mupen64-ui-disk-drive from an old build on BitBucket. I downloaded it a long time ago, and it was recently deleted by the author for some reason. :confused: 

Anyway, Project64's file loading would have to be overhauled, as well as some of the N64DD-specific stuff would have to be figured out in the Project64 codebase. And you would need to be able to run retail and development disks (most of the retail games and prototypes amount to the same number, so both are important).

**Comment by LuigiBlood** [comment]
You may port MESS' code as every games actually works (some have some problems, like Talent Studio, and Randnet requires a modem cart). I own a development disk dump, but I don't know if I can share it for now, sorry. All depends on the guy who dumped it.
But development 64DD doesn't have an IPL included (IPL4ROM is a cartridge, and runs in the usual cart space), and the ID_REG just shows 0x00040000 instead of 0x00030000.

**Comment by vgturtle127** [comment]
@LuigiBlood Thanks, Luigi! Good to know.

**Comment by LuigiBlood** [comment]
Okay apparently, from the words of Zoinkity, Mario Artist Talent Studio uses unknown microcode. I guess that won't be emulated easily.

**Comment by theboy181** [comment]
@LuigiBlood are there any games that we could currently emulate, or do they each have their own set of challenges?

**Comment by vgturtle127** [comment]
They definitely have their own. F-Zero X Expansion uses F-Zero cart, Doshin the Giant expansion uses another 64DD game, Artist series uses unemulated hardware, and some features of the Randnet software and Artist communication kit will require further research.

**Comment by alpharulesirulee** [comment]
also there is f-zero x expansion kit translated

**Comment by LuigiBlood** [comment]
Yes. We know. I manage the site where you can find it lol

**Comment by alpharulesirulee** [comment]
also can you do f-zero x expansion kit (PAL)

**Comment by vgturtle127** [comment]
@alpharulesirulee It isn't that easy. As far as I know, you would basically have to do the same thing Zoinkity did with the other ROM images. This is complicated and technical, but basically you would have convert the DD game and N64 game into a single image, and then on top of that port over all the languages and what not. Might be more difficult for a PAL game. It may also have some weird bugs involving the PAL 50/49.97Hz refresh rate, due to the DD game using the Japanese 60/59.97Hz refresh rate.

I don't know, maybe @LuigiBlood  can explain better.

**Comment by LuigiBlood** [comment]
F-Zero X Expansion Kit into F-Zero X US required a lot of hacks. To the point that making a US Expansion Kit is somehow harder.
And anyway, why would you make a PAL version of it? It's not like with a flashcart you cannot play US games on a PAL console.

**Comment by LuigiBlood** [comment]
Well, now, true 64DD games are working: https://github.com/LuigiBlood/project64/tree/64dd_2
I'm not doing a pull request yet, have to polish that up and also solve the problem that is writing to disk that's somehow not in the right spot, which is rather annoying.

At this point, only 64DD dumps format used by MAME are supported (conversion is needed). At this point there's no UI for it, so it automatically searches for a file called DMPJ.ndd inside Config folder.

I haven't thought this through, but I thought of adding a path to the IPL in the options, perhaps even if you load the 64DD IPL it automatically puts it in the settings, or something like that. Also thought of right clicking a ROM in the ROM browser with an option like "Play Game with Disk"...

**Comment by vgturtle127** [comment]
@LuigiBlood Super exciting stuff, dude!

When you say dump format used by MAME, you mean the .ndd files, right?

Or is there some weird conversion you have to do still with the files in order to run them on Project64?

**Comment by LuigiBlood** [comment]
At this time of writing, you need to use ddconvert to convert 64DD dumps just like for MAME.
That said I'm trying to do the conversion with PJ64 itself so there's no need to do anything.

**Comment by vgturtle127** [comment]
@LuigiBlood Dang, I will just wait for that! Dude, you are so awesome! :+1:

**Comment by alpharulesirulee** [comment]
the rdb for 64dd don't work on pj64 1.6 or 1.4 even it says it works lol pj64 2.x works

**Comment by LuigiBlood** [comment]
They will never work on 1.6 and before that version. Don't even try.

**Comment by theboy181** [comment]
Should this be closed now ? I have heard that there has been implimented

**Comment by LuigiBlood** [comment]
Yes it is implemented. Mario Artist Communication Kit is for some reason crashing Project64 but everything else is booting.

**Comment by theboy181** [comment]
Great work!! Thanks!!!

**Comment by vgturtle127** [comment]
@LuigiBlood Do you know why Mario Artist Communication Kit isn't booting? That seems to be a bit odd. I know it was doing it before all the other code was added, but you could get it to run with Angrylion's RDP...

**Comment by LuigiBlood** [comment]
@vgturtle127 It was somehow solved. I don't know which commit but it's solved. Every disks boots just fine.
Before, even with angrylion it didn't boot at all.

**Comment by vgturtle127** [comment]
@LuigiBlood Boy, N64 emulation is weird. :laughing:

**Comment by xXGucciferXx** [comment]
Still not working. It always hangs up at the startup sequence.

**Comment by LuigiBlood** [comment]
Did you load the zip file directly? If you did: Don't do that, extract the ROM.

**Comment by edgaras1002** [comment]
what do u mean by That...

**Comment by Mikl666111** [comment]
hi devs, i'd like to point out a small issue i just found: the IPL files needed for 64dd emulation can't be found on folders whose path has a "·" on them by the main emulator yet for other files there's no issue if their paths have that symbol

**Comment by Mikl666111** [comment]
exactly as luigiblood said: the "open rom" window shows that the same compressed formats work for dd images as they do for regular roms yet they do not (that does not happen when opening a combo rom). please devs fix that as to avoid future confussion as it took me a while to figure that out and try what happend if i unzipped my dd images

**Comment by Squall-Leonhart** [comment]
> hi devs, i'd like to point out a small issue i just found: the IPL files needed for 64dd emulation can't be found on folders whose path has a "·" on them by the main emulator yet for other files there's no issue if their paths have that symbol

will be resolved with 4.0 and its unicode path fixes.
