### ISSUE TITLE
Sin & Punishment (J) [T] - missing settings in Glide64.rdb

### ISSUE THREAD

**Issue by baptiste0602** [project64/project64#367]
Could you please add settings for Sin & Punishment (J) [T] ? As you did in Project64.rdb.

**Comment by cxd4** [comment]
Made a commit for it to probably end up merged.
https://github.com/cxd4/project64/commit/9d7303483787f53e9b3c2a91f6ed0ce1cb54b5d8

If you try this updated RDB, is your issue fixed?
https://raw.githubusercontent.com/cxd4/project64/yo_glide_i_herd_u_liek_translated_games/Config/Glide64.rdb

**Comment by baptiste0602** [comment]
Sure, i use these seetings. Thanks for the commit.

**Comment by cxd4** [comment]
Seems to have taken a while sorry, but it's merged now:  https://github.com/project64/project64/commit/b54e03b85d2474b00d3415a6d7b069319676bcf9

I'm guessing if that was done right then it satisfies this issue, which can be closed then.

**Comment by baptiste0602** [comment]
Thanks and no problem for the delay, you do that on your free time :)
