### ISSUE TITLE
Missing [ALECK 64] Titles in RDB

### ISSUE THREAD

**Issue by theboy181** [project64/project64#369]
UPDATED:

[6D9D1FE4-84D10BEA-C:4A]
Counter Factor=1
Good Name=Eleven Beat : World Tournament (J) [ALECK64]
Status=Compatible
RDRAM Size=8
Save Type=4kbit Eeprom

[315C7466-3A453265-C:4A]
Counter Factor=1
Good Name=Star Soldier : Vanishing Earth (J) [ALECK64]
Status=Compatible
RDRAM Size=8
Save Type=4kbit Eeprom

[D5356BAC-97AE69D2-C:4A]
Counter Factor=1
Good Name=Magical Tetris Challenge Featuring Mickey (J) [ALECK64]
Status=Compatible
RDRAM Size=8
Save Type=4kbit Eeprom

[B57D4EB4-345E09E5-C:0]
Counter Factor=1
Good Name=Guru - Kuru Kuru Fever (J) [ALECK64]
Status=Compatible
RDRAM Size=8
Save Type=4kbit Eeprom

[D52FE29D-8EA6A759-C:0]
Counter Factor=1
Good Name=Donchan Puzzle Hanabi de Doon! (J) [ALECK64]
Status=Compatible
RDRAM Size=8
Save Type=4kbit Eeprom

[90AF8D2C-E1AC1B37-C:0]
Counter Factor=1
Good Name=Tower & Shaft (J) [ALECK64]
Status=Unsupported 
RDRAM Size=8
Save Type=4kbit Eeprom

[2F57C9F7-F1E29CA6-C:4A]
Good Name=Vivid Dolls (J) [ALECK64]
Status=Compatible
Core Note=LLE may be required on some GFX plugins
Counter Factor=1
RDRAM Size=8
Save Type=4kbit Eeprom

**Comment by theboy181** [comment]
UPDATE: SAVING

[B57D4EB4-345E09E5-C:0]
Counter Factor=1
Good Name=Guru - Kuru Kuru Fever (J) [ALECK64]
Status=Compatible
Core Note=CIC not Emulated
RDRAM Size=8
**SaveChip=0**
Sync Audio=0

[D52FE29D-8EA6A759-C:0]
Counter Factor=1
Good Name=Donchan Puzzle Hanabi de Doon! (J) [ALECK64]
Status=Compatible
Core Note=CIC not Emulated
RDRAM Size=8
**SaveChip=0**
Sync Audio=0

**Comment by LegendOfDragoon** [comment]
Ok I added the games and submitted a PR #413 .
