### ISSUE TITLE
Tower & Shaft not loading

### ISSUE THREAD

**Issue by theboy181** [project64/project64#371]
Loads in Mupen64 and 1964, but not PJ64.

Break point found at 
.\N64 System\Mips\Memory Virtual Mem.cpp
1941

**Comment by cxd4** [comment]
It's a regression in emulated TLB since after 1.6, discussed originally at:  https://github.com/project64/project64/issues/61

**Comment by LegendOfDragoon** [comment]
I'm not sure if TLB is the problem / only problem. Because in 1964 I can run that game with TLB off, but in PJ64 2.2 I cannot. Tried interpreter and that didn't work.

**Comment by LegendOfDragoon** [comment]
This game seems to work in 1.7.0.50 so something happened between then and 2.1

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
