### ISSUE TITLE
Cannot access settings in v2.2.0.3 (Wine)

### ISSUE THREAD

**Issue by GB-CG** [project64/project64#373]
![project64-2 1_and_2 2 0 3](https://cloud.githubusercontent.com/assets/11931125/7124781/b4342830-e223-11e4-8c7e-2e97a1f84658.png)

So I'm using project64 on Mac with Winebottler and while everything in v2.1 functions perfectly, the settings on v2.2 are not showing up on the right panel. Maybe Wine is not recognizing something in v2.2. Or I missed something in the wine config settings.

**Comment by Frank-74** [comment]
Don't know what to suggest, as I don't know why your getting this problem.  In the meantime maybe if you just copy the 2.1 exe over the 2.2 and use that for now.  2.2 has updated RDB and plugins and lots of language fixes.  Just use the 2.1 exe on the 2.2 install, and you should be ok.

**Comment by AmbientMalice** [comment]
This likely occured after the UI rewrites. There was some refactoring a little while ago.

**Comment by project64** [comment]
the panels should be created with CreateWindowW instead of CreateWindowA for better handling of UTF8.

I have no idea why winebottler has an issue with it

**Comment by GB-CG** [comment]
Ok, so as Frank-74 suggested, I've copied the 2.1.exe into my 2.2 folder, and launch 2.1 and I tried __Glide64 2.0.0.5__ and it crashes with this message:
![screen shot 2015-04-14 at 23 20 25](https://cloud.githubusercontent.com/assets/11931125/7149822/3c1b1204-e30a-11e4-9e8f-6fa677f8dce6.png)

The next thing I did was going into 2.1.exe settings, change to v2.2 default plugins, quit v2.1, launch v2.2 and the settings are saved and the game ran...but it still didn't fix the missing panel.

Also, I copied the __Glide64 2.0.0.5__ along with the new plugins into v2.1 and tested Body Harvest for example, and it works at full speed. (still can't cross bridges properly though, _Jabo's 1.7_ kind of fixes that)

I'm curious, I've tested my 360 pad with __N-Rage For PJ64: 2.4.0.4__ using the Xinput button and I get the message: _No Mempak specified; please configure plugin_

I turned off Xinput and applied my 360 buttons and it works. How come? The Left-Trigger sometimes acts like it's holding down all the time, so what I did was click 'Clear Controller' and re-apply, and it's back to normal.

**Comment by baptiste0602** [comment]
> I'm curious, I've tested my 360 pad with N-Rage For PJ64: 2.4.0.4 using the Xinput button and I get the message: No Mempak specified; please configure plugin
I got the same problem. Even if mempak are created per game now, you still need to configure a default mempak in the nrage configuration. Maybe it's planned to remove this behaviour in future pj64 versions.
I also remarked that mempak are created for every game were "default save type" is configured even if the game don't use mempak. No problem for game when specific save type is configured. @project64 do you want a new issue for that ?

**Comment by oddMLan** [comment]
Did you try reporting this to the Wine development team?

**Comment by GB-CG** [comment]
@oddMLan Not yet, but I read that Linux users have reported the same problem too, so I'm guessing they've aware of it, but it's probably in a very long queue of wine issues.

**Comment by austin987** [comment]
it's a known issue, yes:
https://bugs.winehq.org/show_bug.cgi?id=38651

**Comment by sheepdestroyer** [comment]
I can confirm that I hit this bug on Fedora 23 and Wine 1.9.6
I get this : 
````
[sheepdestroyer@sheepora 0.0.0.436-Win32] $ ./Project64.exe 
fixme:winediag:start_process Wine Staging 1.9.6 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ntdll:EtwEventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x401123, 0x50f090, 0x50f0a8
fixme:ntdll:EtwEventSetInformation 2, 0x4fbe60, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_dll Loader redirect from L"wined3d.dll" to L"wined3d-csmt.dll"
fixme:winediag:wined3d_dll_init Please note that the experimental wined3d CSMT patchset has been disabled in this
fixme:winediag:wined3d_dll_init version of Wine Staging. Check out the release notes for further information.
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ntdll:EtwEventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x7a1123, 0x7ea6e0, 0x7ea6f8
fixme:ntdll:EtwEventSetInformation 2, 0x7e7378, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ntdll:EtwEventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x802493, 0x83c050, 0x83c068
fixme:ntdll:EtwEventSetInformation 2, 0x8394d0, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:resource:DestroyAcceleratorTable other process handle 0x1?
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ntdll:EtwEventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0xa81123, 0xb7cb50, 0xb7cb68
fixme:ntdll:EtwEventSetInformation 2, 0xb6f510, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister 0: stub
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
````

**Comment by GB-CG** [comment]
I think I'll close this since it's really an Wine issue.

Anyway, thank you for your responses.
