### ISSUE TITLE
Mia Hamm Soccer 64 never boots in RSP recompiler.

### ISSUE THREAD

**Issue by cxd4** [project64/project64#38]
Mia Hamm Soccer 64 never boots without RSP interpreter, regardless of R4300 CPU settings.

Not much more I can say...pretty easy to reproduce; just try loading the ROM.  I have to forcefully shutdown the EXE, as it seems to be stuck in an infinite loop within the RSP compiler thread rather than the main CPU, I guess.

It might coincide with recompiler bugs in some other games.

**Comment by LegendOfDragoon** [comment]
Lol I must have fixed that problem on my end, before it was even discovered xD. Instruction reordering is to blame. So when zilmar accepts my pull request, I'll push another pull request to fix it.

**Comment by cxd4** [comment]
Nice.  Then if your pull request is merged and fixes the issue I will close.

**Comment by Fanatic-64** [comment]
For the record this game is also:
Michael Owen's WLS 2000
RTL World League Soccer 2000
Telefoot Soccer 2000

A great example of video game badge engineering.

**Comment by cxd4** [comment]
Evidently resolved as of the merged pull request https://github.com/project64/project64/pull/45.
