### ISSUE TITLE
Airborder (J) missing from RDB

### ISSUE THREAD

**Issue by theboy181** [project64/project64#380]
I would love to add these to the RDB, but I think that I need more information on the proper reasoning for files names, info on RDB settings and what they do, and where they are needed.

Here is Airborder 64 (J)

[F255D6F1-B65D6728-C:4A]
Counter Factor=1
Good Name=Աюް^ж4 [Airboarder 64 (J)]
Status=Compatible

[26809B20-39A516A4-C:4A]
Counter Factor=1
Good Name=´±°ÎÞ°ÀÞ°64 [Airboarder 64 (J)]
Status=Compatible

[89A498AE-DE3CD49A-C:50]
Counter Factor=1
Good Name=AIR BOARDER 64 (E) (NTSC)
Screenhertz=60
Status=Compatible

**Comment by project64** [comment]
make a pull request

**Comment by theboy181** [comment]
@project64 PR created..

Please let me know if something doesn't look correct.
