### ISSUE TITLE
RSP Regression (Instruction Reordering.)

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#383]
Battle Ogre 64 is broken by the following commit.

https://github.com/project64/project64/commit/0f1010379f2af13a033b6e1589beaa31426a1996

Forum thread:
http://forum.pj64-emu.com/showthread.php?t=4997

Bear in mind game also needs 32bit mode disabled.

**Comment by LegendOfDragoon** [comment]
Yes I am making a PR soon. Just having issues with local git setup.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon I just saw your forum post. I'll close this as soon as the PR is merged and I've tested it.

**Comment by LegendOfDragoon** [comment]
Ok I submitted the PR. #384

**Comment by AmbientMalice** [comment]
Closing this issue, since it should be fixed now. Good work.
