### ISSUE TITLE
Star Fox (J) (V1.0) FATAL ERROR CRASH

### ISSUE THREAD

**Issue by theboy181** [project64/project64#393]
![capture](https://cloud.githubusercontent.com/assets/9299743/7188853/858c263c-e42f-11e4-94d1-2ef998360a31.PNG)
SAVE FILE: https://www.dropbox.com/s/zanmuiop65xg0pw/Star%20Fox%2064%20%28J%29%20%28V1.0%29.pj.zip?dl=0

This error happens soon as the first hatch opens to spit of the fighter ships.

When I tried start this game with PJ1.7 I got the error "Unknown memory action\n\nEmulation stop"

When I tried to load the state "Break point found at .\N64 System\Mips\System Timing.cpp"

Any thoughts?

**UPDATE**
Turning off TLB seems to fix this part, but might not be the best solution. Turning of "Advanced Link Blocking" on the recompiler seems like the smartest solution, as it only steals a little performance when its disabled.

**Comment by AmbientMalice** [comment]
Yea, ABL causes problems with a few games.

**Comment by theboy181** [comment]
In looking for any docs that explain each setting. I hear that they might be included with the chm file for 1.6.

**Comment by Frank-74** [comment]
@theboy181 There's a file called RDB Info.txt in the 2.2 Config folder that explains all the settings.

**Comment by AmbientMalice** [comment]
I hope you don't mind, but I've made a pull request to disable ABL for SF\LW.
