### ISSUE TITLE
CPU Recompiler regression in Super Smash Bros

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#402]
I was trying to test sync cores, so I can see what recompiler options are needed, and I get sync error right after booting the game. This did not happen in older builds. Not sure when it started though.

**Comment by project64** [comment]
probably here https://github.com/project64/project64/commit/72b12dda85b8329d13b7afe8d5320878be977175 where protect memory is turned off

**Comment by LegendOfDragoon** [comment]
I tried testing protect memory and that got me the error too.

**Comment by cxd4** [comment]
https://github.com/project64/project64/commits/72b12dda85b8329d13b7afe8d5320878be977175/Config/Project64.rdb
```
$ cd project64
$ git checkout 2085717
```

Or try checkout on even older commit numbers until it compiles to something that doesn't have the issue (or it was just the RDB file itself that was the issue).

Or try downloading legacy 1.7/2.0 RDB files.

**Comment by LegendOfDragoon** [comment]
I am soo lost! Keep getting weird results. I will definitely try setting up a new folder and test a few builds. I'm not even sure if it's a regression anymore, but something is definitely wrong.

**Comment by LegendOfDragoon** [comment]
I've tried testing again and kinda got random results. I don't think there's a regression. What I do know is that certain plugins cause the sync error to happen on boot. For instance, Lemmy's DX9 plugin and Rice Video always have a sync error in SSB (likely many other games if not all).

I'm wondering if I should open an issue related to those 2 D3D plugins. Not sure whether it's PJ64's fault or the GFX plugins.

Just to be safe, I think I'll use the "No Sound" plugin while debugging from now on.

**Comment by cxd4** [comment]
>Lemmy's DX9

no such thing

**Comment by LegendOfDragoon** [comment]
>no such thing

Meant LemD3D9

**Comment by cxd4** [comment]
no such thing

**Comment by cxd4** [comment]
A good game, but the correct answer was:

DirectX 9 didn't even exist when Lemmy did graphics.
