### ISSUE TITLE
Quake64 is slow

### ISSUE THREAD

**Issue by SatanNintendo** [project64/project64#41]
The Game Quake64 working very slow.

**Comment by cxd4** [comment]
My 1.90 GHz CPU seems to think personally that it is quite fast, at least through the first mission anyway (hanging below 60 VI/s with default RDB settings).

Please explain where it is slow or with which plugins...is it a HLE deficiency in PJGlide64?  (I don't have that plugin installed so haven't been able to check.)  If we can't see any confirmation or a saved state, ways to reproduce, or anyone else's corroboration that something is not working at full speed then it might be hard to look at this as an issue.

**Comment by SatanNintendo** [comment]
Sorry for my english, my PC: Win 7 x64, Nvidia GeForce 570 GTX, 8GB RAM, Intel i7 4 Cores Processor, 3.40 hz, and i make video for problem on my PC, look please: https://www.youtube.com/watch?v=rBOsxNmO28k

**Comment by project64** [comment]
was this your build or Did you get it from some where else? It looks a look a little like it is a debug build, instead of a release build?

is it set to re-compiler?

**Comment by SatanNintendo** [comment]
I downloaded this assembly with emucr.
Surprisingly, I put in game 8mb settings memory instead of 4mb, game began to work with normal speed, even when I put back on 4 Mb, speed all the same was in norm.
