### ISSUE TITLE
config folder issue

### ISSUE THREAD

**Issue by shinra358** [project64/project64#414]
I have this emu set to here: E:\Users\*my name*\My Documents\Games\CONSOLE\EMULATORS\NINTENDO\Nintend o64\Project64

But everytime I use this emu, it saves the config folder here: E:\Users\*my name* Jr\My Documents\Games\CONSOLE\EMULATORS\NINTENDO

instead of in the emu folder.

This has been happening since 2.0 first appeared. Maybe even 1.7 if I remember correctly. Didn't do this in 1.6.  There is also another config folder inside of the root folder. But the one that is misplaced holds all of the emu's settings.

**Comment by Lithium64** [comment]
You probably are running emucr build, just delete your .cfg file on project64 config folder.

**Comment by shinra358** [comment]
Yes, I am. Is there a buildbot or something for the official compiles? Deleting it only makes it return when the emu is launched again.

**Comment by baptiste0602** [comment]
Maybe this solution work : don't copy Project64.cfg (and Project64.cfg.development) when you unzip the emucr build.

**Comment by shinra358** [comment]
Ah, had to add this in the .cfg in the default section: .\Config\Project64.cfg for the config file path. They had it like: ..\..\Config\Project64.cfg
