### ISSUE TITLE
Replace zlib with 7-Zip code

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#418]
This would broaden compatibility with various versions and types of file formats and add additional file format support, including 7z, RAR, and many more.

Zilmar said to create an issue, so I did. :smile: 

I'm not sure if you guys use a modified version of zlib, but if you just used a stock zlib configuration, then that would make it even easier to migrate.

This also could potentially improve CPU and RAM usage when unpacking compressed ROMs into memory (and may also fix some bugs in that regard).

**Comment by vgturtle127** [comment]
I heard from @death-droid that you use the LZMA SDK, which is essentially 7-Zip, but I'm not sure if there is a difference between the implementation now, and the newest version on the 7-Zip website, so the issue will continue to be up until we can verify the version and configuration of all file handling and archive support, and then we can try to adjust or change things from there.

**Comment by death-droid** [comment]
Essentially 7-Zip is just a program that implements the LZMA sdk, zlib and unrar. Among other libraries.

**Comment by vgturtle127** [comment]
When you say essentially it implements zlib, you mean it just has the same functionality, right?

Because I thought zlib could compress executable and binary data as well as compress using usual zip compression. I didn't think 7-Zip could do that.

It is also released under a non GPL compatible license.

But if you were just generalizing, then wouldn't using 7-Zip still be a marked improvement over zlib in terms of features and compatibility?

**Comment by i30817** [comment]
How is portability? I've read in passing that some people had to adjust the 7zip sdk code to actually compile in linux (i think it was maxcso code).

**Comment by cxd4** [comment]
7Z format never worked right out of the box for me on Linux.  I can create 7z-zipped archives, just can't open them without installing additional software.  Probably just lz/lzma, gz, xz and gzip compression were the ones that worked (both create and open) out of the box.

**Comment by i30817** [comment]
Well, yeah, but that is not much of a issue when you can just apt-get install 7zip. I'm much more worried about a gnarly 7zip source sdk not compiling in arm 64 linux or whatever.

**Comment by vgturtle127** [comment]
The SDK has Linux support, p7Zip is built upon the SDK much like 7-Zip on Windows. At least as far as I know.

If 7z doesn't work for you on Linux, I'm not sure what to tell you, I would think it would work the same as on Windows, just unpack. But of course, it is never that simple when I want to decompress something. :laughing: 

I know p7zip has x86 support, but I'm not sure about ARM. Why would we need ARM support though? Are you thinking about porting Project64 over to Android or something? :laughing:

**Comment by cxd4** [comment]
uh

**Comment by i30817** [comment]
Tbh i'd love p64 on linux ;) not holding my breath though.

**Comment by cxd4** [comment]
Well I'm sure 7-zip has libraries for Linux without a doubt; I meant by "out of the box", it requires me to apt-get install something, which I typically lack Internet for.  It's more of a Windows thing anyway afaik, just happens to be supported on Linux.

What I posted wasn't in opposition.  If I was trying to create an argument against supporting 7-zip format within Project64 code I would have to argue against 98% of the rest of how things are done worse beyond something like that.  7z is fine.

**Comment by vgturtle127** [comment]
In summary, I would just like for us to not have to update two libraries all the time. It would allow more time for N64 stuff. Which is the fun stuff. :smiley: 

If you are talking about lack of internet, I believe the only way 7-Zip distributes the file is on the website, not on a Linux repo. Just FYI.

If we use 7z we can also add RAR support for multiple archives. :smile:

**Comment by i30817** [comment]
If you're thinking about solid archives a detail of that is that all the previous files must be extracted in order before extracting a file in the end of a archive, so it's actually a really bad idea.

**Comment by vgturtle127** [comment]
Oh, no I was referring that often there are bugs with loading multi-game archives. Such as WinZip archives with older versions of WinZip, some versions of PK-zip, etc.

**Comment by cxd4** [comment]
>In summary, I would just like for us to not have to update two libraries all the time.

Well then again if it was my project I probably wouldn't support either zip or 7zip since that would be fewer dependencies to the emulator since zip/7zip has nothing to do with N64 emu.

**Comment by death-droid** [comment]
To be honest it would be a fair bit of work to change things over to any new archive handler. And personally I don't think its worth the pay off. We support the more popular standards in compression which is probably more than enough. Probably better time spent polishing up what we currently have then trying to implement new stuff. 
The only real big compression where missing is rar and I don't see that as being used as much as it once was.

What exactly is sticking out as missing or not functioning right with the current system anyway?

**Comment by i30817** [comment]
Lots of emulator projects - thankfully imo - are merging support for compressed formats. PBP for psx emulators and CSO for ps2 and PSP for example.
Major problems occur when the format supposedly supports something but the emulators just don't bother implementing in !windows, like epsxe and pcsxr which supposedly support PBP now... as long as you never need to change disc on a multidisc-pbp in linux (which they implemented with a popup in windows and is downright missing in gtk).

**Comment by vgturtle127** [comment]
@cxd4 Yeah, I know what you mean. Compressed archives are not really meant for this kind of use. But it is fairly common for people to want ROM's to take up less space, or organize them by game or whatever. I always use uncompressed ROM's personally, but that is just my personal preference.

@death-droid Nothing is wrong with the current system, except that we are using two different compression libraries that provide mostly the same functionality. I'm not talking about adding new functionality or switching to a different library, I am talking about getting rid of zlib and just updating the current 7z library to the latest version. This won't take much effort at all, just taking zlib stuff and replacing it with 7z. By doing this, we (with minimal effort) will add some speed and fix some bugs. We will also get some new features we could add if we wanted (such as the aforementioned RAR support, although only RAR 4.0 and below archives).

@i30817 Yeah, I find it odd that that most projects (PCSX-Reloaded, Desmume, etc) have really crappy Mac ports and many missing features on Linux. It seems like keeping them all the same would be easier, and make more sense instead of letting individual ports get to the point where you have to re-write them (PCSXR, many NES emulators, etc).

Somebody (most likely me in the future I suppose) should create a library for emulator that provides file handling, archive and compression support, patching support, and other stuff like that in a nice, simple to use, fast way. Seems simple enough with most of that stuff being open-source. Man, I really need to get my dev machine running. Ugh.

On a somewhat-related note, I have a large number of test archives created using various software, does anybody know of any specific things that aren't supported in Project64? I am testing everything I can and so far Project64 seems to handle stock stuff but anything to janky and it doesn't like it.

**Comment by cxd4** [comment]
>I always use uncompressed ROM's personally, but that is just my personal preference.

I used to compress all my ROMs.  Looking back this may be better on file system read latencies (easier on the disk drive to import Resident Evil 2 zipped than the full uncompressed 64M), but I do a lot of loading and unloading so get impatient waiting for the full ROM to load.  Which I think is what takes up most of the time, therefore the simplest, plainest solution to me seems to be no compression at all.  Can't convince everyone of that though.

**Comment by vgturtle127** [comment]
Me neither, but you know. People will ask. :eyes:

**Comment by AmbientMalice** [comment]
>RAR never seems to compress smaller than 7z in my experience so I would never care about rar.

In some circles I've encountered, 7-Zip has been viewed with some suspicion about its reliability. In the past, there have been some really nasty regressions. That's one reason, I think, Winrar is still so popular.

**Comment by vgturtle127** [comment]
I'm sure they were using an alpha build or something. 7-Zip tends to stay in alpha for a long time, and people get the latest version because the stable version hasn't been updated or because it doesn't work on their OS. They forget it is still an alpha (or beta sometimes). At least, Igor has said that is usually the problem.

**Comment by vgturtle127** [comment]
@project64 How do you feel about this now? I feel like 7-zip and zlib may be acting redundantly at times.

Could we just use 7-zip, or do we have to use zlib and 7-zip to get all the features we want?
