### ISSUE TITLE
The internal name of Japanese rom

### ISSUE THREAD

**Issue by harlayzhou** [project64/project64#427]
![fuurai](https://cloud.githubusercontent.com/assets/8403754/7433901/8f163662-f068-11e4-81d7-f9eddf31a12f.png)
A lot of Japanese rom using Shift-JIS encoding for the name.
Should be convert to UTF-8 at non Japanese system.
![save](https://cloud.githubusercontent.com/assets/8403754/7433903/9377293c-f068-11e4-89dd-bd66bb6192d0.png)
The save file also should be convert to UTF-8 at non Japanese system that like the right one.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
