### ISSUE TITLE
Log files grow too big

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#430]
Just had an issue with d3d_syslog.txt growing to 3 Gb in size with one error.
!- Unknown pixel fmt = 6, siz = 0, millions of times.

Can it be changed to only write to the log if the last error is different to the previous error?
Maybe have time start-end for error?

**Comment by project64** [comment]
as this is in jabos closed source plugin, nothing can be done

**Comment by Frank-74** [comment]
Thumbs down for closed source. :-1:
