### ISSUE TITLE
(Regression) Rogue Squadron Missing Audio.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#448]
Rogue Squadron's audio seems to break and go mute upon reaching the main menu with all plugins.

Worked here - https://github.com/project64/project64/tree/9984bed37cc64f4d2a38e9f5fbd159a4a5be718d

But seems broken after the BOOL business.

**Comment by Azimer** [comment]
Does this happen with all settings?  FAT=0?  FAT>0?  Which graphics plugins?  PJ64 default RSP?  I'd like to test and take a look at some point tomorrow, see if I can help isolate the regression.

**Comment by AmbientMalice** [comment]
Seems to happen regardless of settings. Using HatCat's RSP interpreter, since the game freezes with CPU recompiler.

**Comment by LegendOfDragoon** [comment]
@AmbientMalice what's the latest commit you've tested? I can't seem to reproduce your issue. It must be fixed :smile: . Unless changing compiler settings make the issue not happen?

**Comment by AmbientMalice** [comment]
@LegendOfDragoon I tested with the latest commit - https://github.com/project64/project64/commit/fefc5b9e17c82d1b60c27f0b9dac0c2398c17582 built using Visual Studio 2013. Problem occurs on both Recompiler and Interpreter.

**Comment by LegendOfDragoon** [comment]
Weird, I really cannot reproduce it.  @AmbientMalice , does it happen with FAT disabled?

**Comment by AmbientMalice** [comment]
To my embarrassment, it turns out this was caused by the save file that I'd been using to skip the longwinded intro sequence. For some reason, all the audio was muted. I can only assume save corruption, because I've never touched the game's audio settings before.

I'm sorry for taking up valuable time.
