### ISSUE TITLE
Audio delayed on rom start.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#449]
Settings are fixed audio on, sync using audio off, audioresetonload on, AI=0.  Plugins default except for newest Azimer's XA2.  Goldeneye is a good example, the sound is delayed switching screens.

However, opening Options > Settings and clicking Ok, fixes it.

**Comment by Frank-74** [comment]
I've done lots of testing and here are my results.  Incidentally, I used only FAT=0, all default settings except audio plugin change.

The test was start Goldeneye, click 'A' to get to the mission select screen.  Press 'B' after hearing the close door sound on switching screen.  When sound is delayed, its noticeable on the close door sound after pressing 'A'.  Press (F2) to pause and unpause, check again pausing up to 5 times.  Rinse and repeat with different audio plugin.  ALL plugins run with HLE Audio setting OFF in Project64.

This list has approximate delays between pressing 'A' and hearing the close door sound.
Azimer's XA2 0.7 = Delay sometimes up to 3/4 of a second, happens often.
Azimer's DS8 0.7 = Same as above!
Azimer's HLE 0.60 = Same as above!
Azimer's HLE 0.56 = Delay sometimes 1/4 to 1/3 of a second, happens less frequent, but plugin is slow compared to 0.7 versions which are virtually instant when in sync (10ms).
Jabo's DirectSound 1.7.0.7 = No variation, consistent, but again slow slow compared to Azimer's 0.7.

**Comment by Frank-74** [comment]
Same delays with Windows 8.1.  Just tested with new build of Azimer's WIP6.

It has nothing to do with AudioResetOnLoad.  Only FAT=0.

**Comment by Frank-74** [comment]
Found a couple of hidden settings for Jabo's 1.7+ DSound plugins, which go in the Project64.cfg under the [DSound] section.

BufferSize=1 for 100 samples, 8 for 800 samples etc.
SoftwareBuffer=1 for default, 0 for hardware.

Increasing the buffersize causes more delay in the audio, but fixes crackling.

Wondering if @LegendOfDragoon could find the default 100 samples buffer size in Jabo's DSound, so it can be hexed to a different value?

**Comment by LegendOfDragoon** [comment]
Jabo's audio plugin appears to be packed. So idk what I could do. Honestly, I often edit values at runtime, since I'm often tweaking numbers.

**Comment by Frank-74** [comment]
PEiD detects the packer as UPX 0.80 - 1.24.

**Comment by cxd4** [comment]
You have to disassemble the protection code and hack one of the instructions so that it doesn't fool the unpacker, then finish decompressing it to get the original compiled Jabo plugins.


But I don't really care about doing that because I'm not mudlord.

**Comment by Frank-74** [comment]
This problem is not a Project64 issue, as it only happens with Azimer's.  So i'll close it here.

Anyway, best way to reproduce delay in Azimer's is, start goldeneye, goto missions selection, make a cup of tea, come back 5-10 minutes later, press B then A and the sound will have drifted a second behind the video.

**Comment by LegendOfDragoon** [comment]
>PEiD detects the packer as UPX 0.80 - 1.24.

Ok, looks like unpacking wasn't difficult. How did you know it multiplied by 100? I found a function the * 100, but can't really tell if it affects what you're trying to modify. After unpacking, the address of the code you might be interested in, starts at 10001073 and ends at 10001081.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
There's a sticky post by Smiff in the Alpha Testing forum section.  BufferSize=n is in unit of 100 samples, not ms, can be positive or negative.  It works, as using buffersize=16, and the audio is delayed well over a second.  I want to make the buffer size multiple smaller, 32 or 64.

Could you send me the unpacked plugin?

**Comment by LegendOfDragoon** [comment]
>There's a sticky post by Smiff in the Alpha Testing forum section. BufferSize=n is in unit of 100 samples, not ms, can be positive or negative. It works, as using buffersize=16, and the audio is delayed well over a second. BufferSize=-16 and you'll get nasty sound. I want to make the buffer size multiple smaller, 32 or 64.

I see. Sounds like a good idea to lower the multiplier.

>Could you send me the unpacked plugin?

@Frank-74 Here's Jabo 1.7.0.7. Let me know if you have any questions.
https://www.dropbox.com/s/5t6mmjill44xlk0/Jabo_Dsound.dll?dl=0

**Comment by Frank-74** [comment]
Disassembled the section you mentioned.  It would be better to try and find Jabo's default buffer size and edit that instead.  Instead of messing with the multiplier.
```
:10001073 8D0C40                  lea ecx, dword ptr [eax+2*eax]
:10001076 8D14C8                  lea edx, dword ptr [eax+8*ecx]
:10001079 03D2                    add edx, edx
:1000107B 8D442408                lea eax, dword ptr [esp+08]
:1000107F 03D2                    add edx, edx
:10001081 6601542414              add word ptr [esp+14], dx
```

**Comment by LegendOfDragoon** [comment]
>Disassembled the section you mentioned. It would be better to try and find Jabo's default buffer size and edit that instead. Instead of messing with the multiplier.

If I understand correctly, the buffer size = 832 + the value of dx.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Found the buffer word value (832) at offset 0x1049.  Changed from 40 03 to 20 00, and its the same as doing BufferSize=-8.  Thanks for your help.
