### ISSUE TITLE
Hydro Thunder broken

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#451]
Hydro Thunder can't boot with the latest version from github
works with Project64 2.1

**Comment by LegendOfDragoon** [comment]
The game needs RSP audio signal enabled. Not sure why someone disabled it in the RDB.

**Comment by AmbientMalice** [comment]
>Not sure why someone disabled it in the RDB.

Me being stupid, most likely.

**Comment by Azimer** [comment]
This is the place where I see Hydro Thunder changed.  https://github.com/project64/project64/commit/acbd18500e3f7bd7c7d2fc6223f8c6a053ad0011

**Comment by LegendOfDragoon** [comment]
#454 fixed the problem, I believe. @purplemarshmallow , please test :smile: .

**Comment by purplemarshmallow** [comment]
works with RSP audio signal
