### ISSUE TITLE
Twisted Edge - Extreme Snowboarding - No sound

### ISSUE THREAD

**Issue by ghost** [project64/project64#466]
This is no sound any emulators and plugins.
However, Custom UltraHLE Alpha is partial sound support. I can hear some noise. Please download it here.

binary http://uoalpha.hiroimon.com/files/Alpha20070903bin.rar
source http://uoalpha.hiroimon.com/files/Alpha20070903src.rar

**Comment by LegendOfDragoon** [comment]
Good find! Hopefully we can find out more :smile: !

**Comment by death-droid** [comment]
@Azimer might be interested in this

**Comment by LegendOfDragoon** [comment]
Did anyone test this out?

**Comment by Azimer** [comment]
Sadly no. :( I am interested if I could get some time to take a look.

**Comment by LegendOfDragoon** [comment]
@exhalatio how do you get this working? The emulator crashes for me. What plugins are you using?

**Comment by Azimer** [comment]
How did you get it to work?  I just spins for me.  Do I need a glide wrapper?

**Comment by LegendOfDragoon** [comment]
>How did you get it to work? I just spins for me. Do I need a glide wrapper?

It's zilmar spec, so I use Jabo's D3D 1.6.1. The initial problem I had was that full screen was really buggy for me, so I got it working after I figured out how to turn it off by default. I had to run GL2Ideal_Config.exe and uncheck the box for fullscreen.

**Comment by Azimer** [comment]
Thanks I was doing it wrong.  I am sure it's an bug causing the sound to appear.  There is no recognizable sound coming from the noise to tell me it's any closer to playing back audio as what I've been able to manage so far.

**Comment by LegendOfDragoon** [comment]
Lol I was wrong about before. Seems like the only plugin it actually accepts are input plugins ;/ .

>There is no recognizable sound coming from the noise to tell me it's any closer to playing back audio as what I've been able to manage so far.

Guess I got my hopes up :disappointed: . Thanks for looking into it.

**Comment by exhalatio** [comment]
Thank you for looking into the problem. I hope that the appropriate sound is played too.

**Comment by LegendOfDragoon** [comment]
I decided to see what i can figure out. For some reason in this game, *AudioInfo.AI_DRAM_ADDR_REG always = 003F2000, so when I looked at the RDRAM address, it's all 0's. So I looked around in nearby memory and saw what I believed to be some audio data, so I hack the audio plugin to not read from AI_DRAM_ADDR_REG  and just always assume the address is always 003EC000 instead. This gave glitched sound (be very careful, because some of the noises are potentially ear damaging if your volume is loud enough or are wearing ear phones). Be sure to use fixed audio timing as well. But at least with this, some of the sound is recognizable to an extent.

Kinda seems weird how nearby memory has some audio data, yet AI_DRAM_ADDR_REG never changes. I wonder if the audio data is written to the wrong memory location or if AI_DRAM_ADDR_REG is not the correct addresss.

**Comment by exhalatio** [comment]
If you changed AI_DRAM_ADDR_REG address to 003F4000, you can hear all of the sound.
Be sure to use fixed audio timing and disable 32bit engine.

**Comment by LegendOfDragoon** [comment]
@exhalatio Legit! I coulda sworn I tried 3f4000 before. Guess not. I already had 32bit engine disabled. I guess that's not the default setting? I guess the RDB could use some tweaking then.

**Comment by exhalatio** [comment]
Thanks to your help.
I guess the RDB changed default setting.

BTW, SW V0,0x0000 (T4) opecode seems write AI_DRAM_ADDR_REG.
I guess that silly idea. but If write AI_DRAM_ADDR_REG, the T9 register looks always = 803F4000. So tweaking SW T9,0x0000(T4), we can get the sound.
Until we Implement accurate emulation...

Game Fixes
(USA)
Cheat0=81051840 AD99
(Eur)
Cheat0=81051960 AD99
(Japan)
Cheat0=81052760 AD99

**Comment by LegendOfDragoon** [comment]
Yeah no problem. Thanks for your help as well!

I am intrigued at how T9 = 803F4000. I wish I had a good debugger. Not sure if I want to use Nemu's debugger, Pj64 1.6's, or maybe even 1964 0.85's. I'll have to look into it some day.

**Comment by Azimer** [comment]
Interesting...  Oddly I can get some kind of sound out of 1.6 but not 2.2.  Good find and gives us more to look at anyway to determine what exactly is going on.

**Comment by AmbientMalice** [comment]
I'm currently preparing a huge RDB cleanup PR, and I was wondering whether adding this hack would be acceptable. Or would it be preferable to add it as a separate PR? Or perhaps not add it at all?

**Comment by LegendOfDragoon** [comment]
I would hold off on it. It hasn't been tested enough, imo.

**Comment by AmbientMalice** [comment]
>It hasn't been tested enough, imo.

Fair enough. I will fix the incorrectly set 32 bit mode, though.

I've been testing. Voices are distorted. Music has a choppy quality, but it does sound okayish. I wonder whether certain plugins or improvements to Azimer's would provide better results, since this is a BOSS game after all. I tested with Jabo 1.7 and a few Azimer builds.

**Comment by project64** [comment]
maybe add it as a cheat entry for now as a separate pull request to make it easier to test

**Comment by AmbientMalice** [comment]
>maybe add it as a cheat entry for now as a separate pull request to make it easier to test

I'll do that.

**Comment by LegendOfDragoon** [comment]
@exhalatio have you tried using Project 1.6's or 1964 0.85's debugger? I'll try them both today and see if I can find any leads.

>I've been testing. Voices are distorted. Music has a choppy quality, but it does sound okayish. I wonder whether certain plugins or improvements to Azimer's would provide better results, since this is a BOSS game after all.

It certainly does make a difference. At first I thought the bad audio was maybe due to the workaround, but I guess it's like Top Gear and requires a certain audio plugin and very good performance.

**Comment by exhalatio** [comment]
>@exhalatio have you tried using Project 1.6's or 1964 0.85's debugger? I'll try them both today and see if I can find any leads.

I've used the nemu64.
I can not building Project 1.6's and 1964 0.85's debugger build.
I tried this cheat in the Project 1.6 and 1964, sound does not seem to be output. Weird.

**Comment by LegendOfDragoon** [comment]
I just tried 1.6's debugger. Could not solve the mystery. I got the sound to output with your GS code, but it's not as good as pj64 2.2 + fixed audio timing.

**Comment by LegendOfDragoon** [comment]
Lol i was going to say that this issue can be closed, but i just tested and am getting no audio with Project64 Audio.

**Comment by Frank-74** [comment]
The hack was removed when zilmar took azimer's lle.  It can be put back in at sometime.

It had this in aziaudio's main.cpp:
`cpp
	bLockAddrRegister = false;
	const u16 cart_ID = 0x0000
		| (AudioInfo.HEADER[BES(0x3C)] << 8)
		| (AudioInfo.HEADER[BES(0x3D)] << 0)
		;
	switch (cart_ID)
	{
	case 'SB': /* Twisted Edge Extreme Snowboarding */
		bLockAddrRegister = true;
		break;
		/* any other experiments to play with game overrides...not that hacks should be necessary */
	}
.........
EXPORT void CALL AiLenChanged(void) 
{
	if (snd == NULL)
		return;
	if (bLockAddrRegister == true)
	{
		if (LockAddrRegisterValue == 0)
			LockAddrRegisterValue = *AudioInfo.AI_DRAM_ADDR_REG;
		snd->AI_LenChanged(
			(AudioInfo.RDRAM + (LockAddrRegisterValue & 0x00FFFFF8)),
			*AudioInfo.AI_LEN_REG & 0x3FFF8);
	}
	else
	{
		snd->AI_LenChanged(
			(AudioInfo.RDRAM + (*AudioInfo.AI_DRAM_ADDR_REG & 0x00FFFFF8)),
			*AudioInfo.AI_LEN_REG & 0x3FFF8);
	}
}
```

**Comment by oddMLan** [comment]
What about implementing MAME's fix instead (which eventually got ported to Mupen64Plus):

https://github.com/mupen64plus/mupen64plus-core/pull/343/commits/2170d5e0c9ed3c12e487eb1c5425798712b6dac8

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
