### ISSUE TITLE
Adware in the installer

### ISSUE THREAD

**Issue by dsx-** [project64/project64#468]
friends of mine who seem like intelligent people are still getting adware on their computer even after saying no to all the prompts

remove this shit, fucking hell

**Comment by AmbientMalice** [comment]
I install the emulator dozens of times a week, and have never gotten any adware installed. The problem, however, is that the prompts are extremely confusing -- likely deliberately so. (And for the record, that part of the installer is controlled by a third party.)

**Comment by dsx-** [comment]
yeah its misleading bullshit to make money or whatever

**Comment by MELERIX** [comment]
I made this few time ago: https://github.com/project64/project64/pull/354

**Comment by cxd4** [comment]
Nobody in a position to be able to do anything about it has inclination of removing the installer's random-ad sourcing.

I recommend compiling from source, as compiling source code concerns nothing with programmer knowledge prerequisites and in an ideal world is no harder than learning how to use Microsoft Word to open and save changes to a text document / Word document.  If compiling Project64 is such a tech-savvy and elite experience then so is all the other hundreds of random gigabytes of Microshit that ships with your operating system.

Past that, there's a command-line param to call the exe in a batch file to void the installer out, or you can keep clicking No/Cancel and exit the installer, restart it until it comes up with an ad where canceling and restarting the next time skips the ad.  (Mysteriously that's what happened to me.)

**Comment by dsx-** [comment]
yeah i'm gonna whine at zilmar about it

yeah they can compile from source, but the fact is that users are being provided with an installer, and having it full of SHIT is still a dick move

either provide a clean installer or provide no installer at all, this is my view

**Comment by cxd4** [comment]
I would say, provide no installer at all.  The best software is always simplest--it's not a matter of "free" in terms of money, but purity and socially free engineering.

Of course there also are people who wouldn't agree to that--they would say every proper piece of Windows application programming should have some form of installer (at least a zip) and that using the latest optimizing compilers to build the software from the beautiful C principles used to describe it is a thing of restriction and forcing users to be programmers.  So, those are the people who would be proud to use arbitrary installer applications or even risk having to dodge malware and would rather go through that than my "no installer at all" philosophy or build from source.

**Comment by JunielKatarn** [comment]
Sorry for the spam, but I believe I found an alternative to the installer and building from source (after having downloaded, installed and lost 5GB of storage to Visual Studio):

https://github.com/project64/project64/pull/354#issuecomment-146863715

**Comment by YellowOnion** [comment]
Don't click skip, skip is lies...

Jesus fucking Christ, .sys files? so basically I have a root kit now?

![image](https://cloud.githubusercontent.com/assets/364160/12081319/80d03618-b2da-11e5-9dce-6788bf807d4c.png)

**Comment by MELERIX** [comment]
@YellowOnion no, it's just Adware, use this: https://toolslib.net/downloads/viewdownload/1-adwcleaner/

**Comment by YellowOnion** [comment]
@MELERIX .sys files would make it a rootkit, its *also* adware, these are not mutually exclusive terms.

And if you note, the screenshot is from MalwareBytes, which is working fine, as show by the fact that it found .sys files.

**Comment by AmbientMalice** [comment]
No, a sys file doesn't make it a rootkit. Nor does Malwarebytes identify it as such.

**Comment by LegendOfDragoon** [comment]
Adware is gone, so this can be closed :smile: .

**Comment by dsx-** [comment]
ADWARE REMOVED
THIS IS A GLORIOUS DAY
PROJECT64 SAVED
RESULTINGLY, DSX RETURNS

**Comment by project64** [comment]
it is also removed completely from the site as well, not just the source

**Comment by cxd4** [comment]
haha, what?  there was adware on the site?
