### ISSUE TITLE
SSB slows down to < 2 VI/s on re-compiler.

### ISSUE THREAD

**Issue by cxd4** [project64/project64#47]
When using the VR4300 (main CPU) recompiler, Project64's speed takes a nosedive at this point in _Super Smash Bros._:
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6w1yA1Z2ZpECrmjj9AsaFtA1W4NVq.jpg

It's consistently reproducible.  HLE / LLE gfx and RSP recompiler / interpreter do not affect the issue at all.  Here is a HLE screenshot, to contrast with the LLE plugin screenshot above, same issue at the same exact spot:
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6w1yMs9sC74LYm2iBIpprttwSnRqR.jpg

I have found only one fix (well two if you count switching to the interpreter):
Go into the RDB settings and uncheck "Start changed" from the re-compiler methods.
Whether you uncheck PI DMA, Protect Memory, or any of the other 4 techniques has no effect.

**Comment by cxd4** [comment]
Oh, and you don't need a saved state.

Just boot up the ROM and wait for the demo to play up to that screen without hitting the START button.

**Comment by project64** [comment]
the default settings should be just protect mode enabled, start changed should not be set ?

**Comment by cxd4** [comment]
It would seem I was using the 1.6 unofficial RDB, in place of the 2.0 one.  So all this time I haven't even been using everyone else's RDB settings.

This could actually explain why I was the only one to be able to reproduce some of Smasher's build issues back on the forum--this one here with SSB is one of them.  He did give self-conflicting info sometimes, so I guess I was just using an outdated/blank RDB same as him.

Before I close the issue, isn't it still an issue that the game slows down to 2 VI/s with "Start changed" set?  It doesn't crash, just slows down temporarily.  If there is no way to stop it from slowing down that badly, without nullifying the optimization, then I will close the issue, otherwise technically it still sounds like an issue?

**Comment by project64** [comment]
it is just a different detection method .. maybe there is a way to to improve start changed  but not sure. It was just causing things to keep recompiling for some reason

**Comment by cxd4** [comment]
Then maybe the right opportunity to debug "Start changed" just hasn't presented itself yet.

Maybe it would be better off isolating it as an issue in a game currently unsupported by the RDB.  In the worst case scenario, the only fix to the problem with "Start changed" is one which nullifies the effectiveness of its optimizations in the first place, in which case the issue is a null point.  Either way, the name of this issue is no longer accurate due to the updated RDB file's intervention.

**Comment by LegendOfDragoon** [comment]
Does Super Smash Bros actually need Protect Memory enabled? I disabled it, due to the issues I found ;/ . Same with games like Mickey's Speedway USA.

Idk if it's bad to do this, but I usually only enable options that are required (as in it crashes / is bugged otherwise). So for Super Smash Bros, out of the Self Mod Methods, I only have PI DMA enabled.

**Comment by project64** [comment]
I am not totally sure, most likely, but I am not totally sure.

Would be nice is there was a proper history of the changes, so there could be a comment why a change was made. I guess we can do that more now that we are using git, when changes are made it can be done with a comment as why it was changed.

**Comment by cxd4** [comment]
No I don't think it does need _Protect Memory_.

In fact I just finished beating the game in 1P Story Mode 2 times this morning, with all of the self-mod code methods turned off except for just Cache and PI DMA (and in LLE gfx, too).  I just didn't feel like pointing that out because I don't really care that much about the RDB / recompiler settings.
