### ISSUE TITLE
Debugger problems

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#474]
Debugger breaks the VI's syncing to 50 or 60VI's.

When starting Project64 with the debugger enabled and then opening Perfect Dark, VI's drop to 20 on the memory expansion screen.  Then on the rotating Rare logo they drop again to 10VI's.

It has nothing to do with logging.  As I can enable logging and then disable the debugger, close Project64, reopen and run, VI's are back to normal, holding at 60, and its still writing logs.

Debugger does something strange to VI rate.  And it only happens when starting Project64 with the debugger already enabled.  Starting without the debugger enabled, enable debugger, run game, its fine.

Its a pain in the backside constantly having to disable/enable the debugger.

**Comment by Frank-74** [comment]
This doesn't happen anymore.  Not sure what fixed it.

**Comment by project64** [comment]
was this x86 code logging ?

**Comment by Frank-74** [comment]
Haven't any idea.  When the framerate dropped, it was locked at 20 VI's, then locked at 10 VI's with the rotating rare logo.  It didn't just struggle and hover at the lower speed, it was rock steady 20/10 VI's.  It was like a syncing error or something.
It only happened with the debugger already enabled when starting Project64.exe.

Now it works fine, locked at 60 VI's with debugger enabled all the time.
