### ISSUE TITLE
Space Invaders: Fatal error at demo mode

### ISSUE THREAD

**Issue by Nes-player4Life** [project64/project64#485]
Error
Fatal error: Stopping emulation 
Message shown at the menu screen once demo mode starts emulator crashes. No error code.
Error not present in 1.6.

**Comment by AmbientMalice** [comment]
This is an interesting bug. Happens with interpreter mode and also interpreter RSP.

**Comment by cxd4** [comment]
Any idea when in between 1.6 and 2.2 (or 2.3 or whatever the current version is) this issue began?

**Comment by Nes-player4Life** [comment]
@cxd4 No I don't.

**Comment by Frank-74** [comment]
With debugger enabled, I get `Break point found at .\N64System\Mips\MemoryVirtualMem.cpp 603`
```cpp
    if (PAddr >= 0x10000000 && PAddr < 0x16000000)
    {
        g_Notify->BreakPoint(__FILE__, __LINE__);
```
Removing the breakpoint and the game continues to demo mode without a crash.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
