### ISSUE TITLE
Add Chinese Ocarina of Time ROM

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#486]
The only problem with adding it is I'm not sure what version of the game this version is based off of. I would have assumed the Japanese version, but it looks like it may be based off of the 1.2 NTSC release ROM. Apart from that, it is the standard Ocarina of Time, except in Chinese. It has all the same problems and glitches when you run it as the normal ROMs do.

How would I go about creating the RDB entry for this? I have this so far:

[693BA2AE-B7F14E9F-C:45] *This is from the Ocarina of Time US 1.2 ROM
Good Name=The Legend of Zelda - Ocarina of Time (Chinese)
Internal Name=THE LEGEND OF ZELDA
Status=Compatible
Core Note=
Plugin Note=
32bit=No
AiCountPerBytes=100
Cheat0=801DAE8B 0002
CheatPlugin0=Jabo's Direct3D8,Glide64 For PJ64
Culling=1
Emulate Clear=1
SMM-Cache=0
SMM-FUNC=0
SMM-PI DMA=0
SMM-Protect=1
SMM-TLB=0
Self Texture=1

Here are hashes of the ROM if you need them:

CRC32: 5C8E5553
MD5: A04EBD753276C52E95E25AF7683DA32D
SHA-1: 2BA3F3C6C06C9B60AC851D1D54AC88DA1F239F3A
SHA-256: B0DBCEBB5C17BC2C08710F1AB1AC6D4E397BE8A3149637BF69146963C9BA3C28
SHA-512: 4D9F80711097F98BB374B0E28010C8D6AB6153DD2DFEB1F336052440CFFFA8DC8F18CF3210EB362963A3FB62ED0C4CE0ADBCC40068DB339D13274BADC29187B0

**Comment by dsx-** [comment]
probably the ique release

**Comment by Sintendo** [comment]
I doubt it. AFAIK, no iQue titles have been dumped. GoodN64 says it's "Zelda no Densetsu - Toki no Ocarina (J) (V1.0) [T+Chi.02_madcell].z64", so it's probably a fan translation.

**Comment by vgturtle127** [comment]
I know for a fact it isn't an iQue release, as those ROM images are encrypted and haven't been decrypted AFAIK. I'm looking into though.

"Fan translation" isn't the word I would use. More like unofficial translation for Chinese people. More out of necessity than anything else (since video games and consoles are somewhat hard to get, mostly due to the fact that they were banned for a long time, and also that China has strict import/export rules. Also, a thousand other things. But basically emulators and ROMs are pretty much all China has ATM.

**Comment by vgturtle127** [comment]
@project64 Is there a way I can easily add this to the RDB so I can close this?
