### ISSUE TITLE
Heiwa Pachinko World 64 (J) freeze

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#537]
Heiwa Pachinko World 64 (J) freeze 2.0.0.X or higher.
I checked 1.7.51.51, 2.0.0.2, 2.0.0.11 and 2.0.0.14.
state is here.
http://nekokabu.s7.xrea.com/heiwa.pj.zip

1.7.51.51 and 2.0.0.2 are OK.
It is displayed menu after push A button.
![heiwa](https://cloud.githubusercontent.com/assets/11252775/8651668/45456e32-29b5-11e5-9b61-7934eafd387e.jpg)

2.0.0.11 and 2.0.0.14. are BAD.
freeze after push A button.
*Latest git also bad

I'm looking for source code between 2.0.0.2-2.0.0.11 .

**Comment by cxd4** [comment]
I don't know anything about those version numbers.

If you set everything to HLE (graphics and audio) does it still freeze?

If you disable "Limit FPS" or hit F4, does the VI/s counter continue to update after it freezes?

**Comment by AmbientMalice** [comment]
Changing to CPU interpreter makes the menu appear. But it seems to freeze afterwards? Not really sure how this game is meant to work.

**Comment by cxd4** [comment]
I could say the same thing about most Japanese games. :D

**Comment by LegendOfDragoon** [comment]
I was hoping this issue was related to #371 , but it doesn't seem to be, since it doesn't work in 2.0.0.2.

@Nekokabu , if you want to compile / look at older versions of 2.x and 1.7, you can just dig deep in the commit history. For example https://github.com/project64/project64/commits/master?page=35 has 2.0.0.2 - 2.0.0.4.

I'm preoccupied testing / fixing other things, but hopefully this issue can be tracked down :smile: .

**Comment by Nekokabu** [comment]
>If you disable "Limit FPS" or hit F4, does the VI/s counter continue to update after it freezes?
over 1700 VI/s and Only BGM is played.

>@Nekokabu , if you want to compile / look at older versions of 2.x and 1.7, you can just dig deep in the commit history. For example https://github.com/project64/project64/commits/master?page=35 has 2.0.0.2 - 2.0.0.4.
Thanks!
I tested old commits, the cause is this
Half life: Update if hard loop checking value
https://github.com/project64/project64/commit/e848cbcded9c377dc16ff8bf544f5cc5485b0801

I do not understand the contents of this function.
but it works when you modify this line.
-	m_HalfLine = (DWORD)(NextViTimer / g_System->ViRefreshRate());
+	m_HalfLine = (DWORD)(*g_NextTimer / g_System->ViRefreshRate());

thanks!

**Comment by LegendOfDragoon** [comment]
@Nekokabu I'm glad you have tracked down the issue. Unfortunately I don't understand that function too well either. I may try debugging it today though, to see what is happening.
