### ISSUE TITLE
(Regression) Audio Mutes When Changing\Reloading Game. (Jabo Only.)

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#541]
Starting a game, closing it, and then starting it again is usually enough to trigger the problem.

**Comment by LegendOfDragoon** [comment]
Jabo's audio? I think I recently noticed that too. Doesn't seem to affect all audio plugins though.

**Comment by AmbientMalice** [comment]
>Jabo's audio?

Yep.

**Comment by LegendOfDragoon** [comment]
All I know so far is that the regression happened sometime between 2.1 and now. I don't think it affects any other plugins though.

**Comment by AmbientMalice** [comment]
>All I know so far is that the regression happened sometime between 2.1 and now

It doesn't happen in 2.2. It doesn't happen in a build from a month of so ago. Likely happened within the past few weeks. And I'm gonna take a wild stab in the dark.

https://github.com/project64/project64/commit/03dae91dc8b486fe420bd9d460c7b4733df3902a

**Comment by LegendOfDragoon** [comment]
Good guess. I came to the same conclusion actually. This is one of those unfortunate situations. I'd need to add redundant code to fix this "issue".

**Comment by AmbientMalice** [comment]
Yet another reason to migrate away from Jabo's audio plugin as soon as Azimer's is an acceptable replacement. I'll leave this issue open to hopefully deter others from reporting it.

**Comment by LegendOfDragoon** [comment]
I had a fun debugging session :smile: .

Anyway, I think I found a decent solution. But I need to know how @project64 wants to deal with private variables and functions.

**Comment by cxd4** [comment]
So ask. :P

**Comment by LegendOfDragoon** [comment]
I changed my mind on how to approach this problem anyway :smile: . I'll submit a PR in the near future.

**Comment by LegendOfDragoon** [comment]
@AmbientMalice can you check and see if this issue is resolved?

**Comment by AmbientMalice** [comment]
Seems fixed. I haven't done extensive testing, though.
