### ISSUE TITLE
Make CMemoryLabel::AsciiToHex marginally more efficient

### ISSUE THREAD

**Issue by JMarlin** [project64/project64#549]
Kind of a silly issue, but I saw a super minor thing I could improve upon and thought I'd jump on it.

Converting from a monolithic switch to a slightly smarter range check can reduce a worst case of 22 comparisons down to 5.

**Comment by JMarlin** [comment]
Reopening due to incorrect case conversion math

**Comment by cxd4** [comment]
whoops forgot about this though I think I remember your changes being merged, unless there was something else you left the issue open for?

**Comment by JMarlin** [comment]
Nope, if everything looks good to you then this is clear to be closed.

**Comment by cxd4** [comment]
Okay.  Anything else to apply this issue to in other sources @project64 or is this the end?

**Comment by JMarlin** [comment]
I haven't looked at it in a while, but I believe this same method was duplicated elsewhere in the codebase and perhaps the whole thing could use a good search-and-replace, but I don't know when I'd have time to get around to it so at the moment, on my end, I'm going to be calling this the end.

**Comment by JMarlin** [comment]
Shit. Did not mean to hit close

**Comment by cxd4** [comment]
I think you're right but forgot exactly the other locations.

The RSP plugin and 3 or 4 other copies of the same function you improved throughout the Project64 core project.  Maybe you can find them by right-clicking the `AsciiToHex` function and doing "Find All References" in Visual Studio.

**Comment by JMarlin** [comment]
Not using VS, but I'm sure I can grep it just the same

**Comment by cxd4** [comment]
Ah, cool!

Yeah I've been trying to get PJ to compile without Visual Studio for some time now (or at least without Visual Studio Professional, to start out with).  Of course on a couple occasions I just commit changes on Linux anyway, but it's nice to actually be able to compile, run and test without having Windows installed.

**Comment by tony971** [comment]
I've been able to compile with community for months.

**Comment by cxd4** [comment]
That just required specifying a "Microsoft account".

Then after that they use those to track where your wife and kids live along with what sorts of other "free" products you're interested in so they can sell you teh r*mz.
