### ISSUE TITLE
issues with jabo gfx

### ISSUE THREAD

**Issue by dsx-** [project64/project64#557]
this commit:

https://github.com/project64/project64/commit/e5c2df4dbc1f97ff9bd61513d48e6dd89a02847a

1. breaks software rendering with jabo's direct3d8
2. causes the plugin to give access violation errors with some games (software rendering off) (mario tennis is one, but there are others, i have witnessed this error a lot in my testing for the upcoming wiki)

i guess you could say "lol glide is better anyways" but the point is these problems didnt exist until this commit

EDIT:

This commit also stops 1.6 plugins from loading at all.

**Comment by cxd4** [comment]
onice!

**Comment by cxd4** [comment]
All 3 of those things you mentioned seem introduced by removing this line:
```
<DataExecutionPrevention>false</DataExecutionPrevention>
```

You can toggle Data Execution Prevention on or off through the GUI for the linker settings as shown in this screenshot:
![dep_orly](https://cloud.githubusercontent.com/assets/1396303/9027141/3f8eee66-3917-11e5-81b5-71de20bc12c7.png)

Having this setting switched on appears to be what causes both the crashing and failure to load any of Jabo's 1.6[.1] plugins.

**Comment by LegendOfDragoon** [comment]
Yup I noticed that enabling DEP has issues with Jabo's plugins so I always disable it for n64 emulators.

**Comment by dsx-** [comment]
wow amazing

good to know

**Comment by Waksack2** [comment]
I'm playing and uploading Super Smash Bros 64 matches on YouTube with no picture! How did I change the Glide64 settings with no picture? That should be a issue!

https://www.youtube.com/watch?v=9TNIQLOyYxo
https://www.youtube.com/watch?v=k3dwOA6le9Y

**Comment by cxd4** [comment]
I guess the only genuine "fix" to this issue would be within the Jabo plugin.

I'm not sure whether it's a good idea to set DEP compatibility off in the solution since maybe an internal fix to plugins causing the incompability would have been preferable.  So maybe the only solutions are disable DEP on your local machine or don't use the Direct3D8 1.7 plugin by Jabo...probably the 1.6.1 plugin is safer.

**Comment by Frank-74** [comment]
Wondering if reading/writing to the registry is what makes the 1.6 plugins fail with DEP.  As the 1.7 plugin is selectable and useable, but none of the previous versions, 1.6.1, 1.5.2 show up in the list of plugins.  If so, a patch could be made for pre Jabo 1.7 plugins that removes all calls to reading/writing the registry..

**Comment by cxd4** [comment]
Hmm possibly, though in theory it could also be one of the other differences between Gfx 1.4 specs (unique to 1.7 graphics plugins) versus 1.3 and earlier (which 1.6[.1] uses).

**Comment by Frank-74** [comment]
In VS2008 solution, DEP is turned off.
![capturedep](https://cloud.githubusercontent.com/assets/11056843/10236230/25f841b0-689b-11e5-8088-57d5edc4e30e.PNG)
So it should be turned off in the other solutions.

**Comment by cxd4** [comment]
I wonder why it's off for 2008 but on for 2013 then.

Must be some bug in the automatic solution upgrader death-droid used a while back or something.

**Comment by Frank-74** [comment]
I thought you knew, I'm just following up your reason for this issue.  Your comment on this line note, which removes turning off DEP.
https://github.com/project64/project64/commit/e5c2df4dbc1f97ff9bd61513d48e6dd89a02847a#diff-3be6e524e625daf896ca023972f86002L32

**Comment by cxd4** [comment]
Just forgot it.  Memory goes way up and down sometimes.

I imagine that it was something zilmar ended up implicitly removing.  I doubt he would mind having a pull request disabling DEP for that as well.

**Comment by LegendOfDragoon** [comment]
Did DEP end up getting disabled?

**Comment by oddMLan** [comment]
Is this actual? @dsx-

**Comment by dsx-** [comment]
yes this issue is real, not sure if DEP has been disabled yet

**Comment by LegendOfDragoon** [comment]
DEP has been disabled.

**Comment by dsx-** [comment]
sick, closing this
