### ISSUE TITLE
Issue/request: Allow to add more variants in codes with variables

### ISSUE THREAD

**Issue by OldGnashburg** [project64/project64#558]
There is a C & B-Buttons Item Modifier Code for both Zelda 64 Games. Each code for each button has a two character variable. And since each item changes as a character goes up (00 -> 01, or 1C -> 1D) you'll eventually have a lot of variables. In fact, too many for the code to save all of them. In fact it just deletes all of the variables beyond it's limit. So I request that we allow for a code to have more variables so a person could potentially have every variable from 0000 to FFFF saved for a single code.

**Comment by Waksack2** [comment]
I'm playing and uploading Super Smash Bros 64 matches on YouTube with no picture! How did I change the Glide64 settings with no picture? That should be a issue!  
https://www.youtube.com/watch?v=9TNIQLOyYxo
https://www.youtube.com/watch?v=k3dwOA6le9Y

**Comment by cxd4** [comment]
>So I request that we allow for a code to have more variables so a person could potentially have every variable from 0000 to FFFF saved for a single code.

@OldGnashburg : Wouldn't it then be pretty hard to select one of the many code modifier inputs between 0000 to FFFF though?  You would still have to scroll through 65,536 potential items just for the one you want.  At which point, you may as well just type the 16-bit hex you actually want and not have to worry about overflowing the cheats list buffer or further arbitrating the limit.

**Comment by OldGnashburg** [comment]
Sorry I took a while to respond. I am not necessarily saying I would want to input every value from 0000 to FFFF because the variables only go from 00 to FF.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
