### ISSUE TITLE
Aleck64 Updated CARTHACK ROMS no longer load

### ISSUE THREAD

**Issue by theboy181** [project64/project64#561]
![capture](https://cloud.githubusercontent.com/assets/9299743/9267146/e5310d14-41fe-11e5-8a0a-69a2faa1a74b.PNG)

**Comment by LegendOfDragoon** [comment]
Is this still the case?

**Comment by theboy181** [comment]
Yes

**Comment by oddMLan** [comment]
Is this still actual? I tried Kuru Kuru Fever [ALECK64] and it ran without issues.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
