### ISSUE TITLE
BattleTanx (U) SP DMA errors

### ISSUE THREAD

**Issue by cxd4** [project64/project64#57]
After a lot of complicated troubleshooting with the Evangelion SP DMA errors, which happened with RSP audio ucode in LLE from various saved states on various emulators' interpreter cores, we ran into very consistent, very easy-to-find problem with _BattleTanx_:
1.  load ROM
2.  press START
3.  "New Game"
4.  If you get tired of waiting for the stupid cinematics you can just keep pressing A.
5.  SP DMA read error!  No saved state necessary.
6.  only happens with LLE gfx, audio could be HLE doesn't matter

The fascinating thing is that when the SP DMA errors start varies...sometimes it starts right after you press START button to get through the menu, sometimes it happens after you begin a new game.  Interpreters shouldn't be giving random/unpredictable results like this though I would have thought?  Then again I'm not really a R4300 person.

**Comment by cxd4** [comment]
Depending on whether or not project64 is able to associate this with any core CPU/interpreter faults within pj64 itself, I will most likely end up self-assigning this as a RSP interpreter bug with unimplemented SP DMA.  I don't even have this implemented in my own RSP plugin actually....

**Comment by LegendOfDragoon** [comment]
Honestly, I don't even press a button. I just disable frame limiter and the error happens early on in the intro. The error happens on 1964 1.1 as well.

**Comment by project64** [comment]
>  Interpreters shouldn't be giving random/unpredictable results like this though I would have thought?

yes, they should be consistent if all the input is the same, if you eeprom is different, or you start pressing keys timing and code paths will be different. Also if fixed audio timing is not on then that can also cause inconstancy.

**Comment by cxd4** [comment]
Okay in that case new steps to reproduce:
1.  load ROM
2.  just sit there without pressing START button until SP DMA :)

Seems to be consistent every time this time, with no key presses on my part, and I have just turned on Fixed Audio Timing anyway.

So I guess that means the ROM really is attempting to SP DMA an unmapped RCP memory address...it's a shame because if I "fix" this SP DMA error in pj64 RSP interpreter, there will be few error messages left to interrupt emulation in case the RSP ucode gets corrupted by the CPU recompiler or something (causing ear-damaging audio)...I guess invalid RSP opcode would be one of the only error messages left.  So in a way, I actually don't want to fix this issue in RSP interpreter, because having that SP DMA error message can save us from having ear wrecks (not completely though in my experience -.-).

Still got to do whatever's necessary to fix.

**Comment by oddMLan** [comment]
Confirmed and reproduced.
LLE GFX and Recompiler/Interpreter RSP. Happens a few seconds after the intro if you don't press start.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
