### ISSUE TITLE
Missing audio - Windows 10

### ISSUE THREAD

**Issue by tony971** [project64/project64#571]
The only time I get audio with Windows 10 is using Jabo's LLE audio, the first time running emulation. As soon as emulation ends, the audio disappears until PJ64 is restarted. Jabo's HLE doesn't output audio ever and neither does AziAudio (HLE or LLE). Running in compatibility mode does nothing.

**Comment by cxd4** [comment]
The only audio with Jabo's DirectSound is LLE.  There's no HLE code for that.

So if it's a device issue (dsound vs. XAudio2) then I don't think HLE vs. LLE matters.

**Comment by tony971** [comment]
@LegendOfDragoon seems to think that this commit 8c48ba4f7057d7ee92a3d783014c8ad0b1647179 is the one causing BSODs on Windows. By the title of it, it could be the same thing messing with the audio.

**Comment by AmbientMalice** [comment]
There's a bug in Jabo's audio plugin that interferes with an improvement to PJ64. https://github.com/project64/project64/issues/541

**Comment by tony971** [comment]
AziAudio's issue was caused by missing this DX runtime: http://www.microsoft.com/en-us/download/details.aspx?id=8109 and the Jabo's stuff is a duplicate of #541

**Comment by LegendOfDragoon** [comment]
@tony971 is that issue with Jabo's audio fixed for you now?

**Comment by tony971** [comment]
It looks like it. I was able to end emulation, start it again, and still have sound. But I got the BSOD when I tried running a different ROM. I was running in compatibility mode for Windows 7 at the time.
