### ISSUE TITLE
Input plugins - Plugging and Unplugging controllers

### ISSUE THREAD

**Issue by Ownasaurus** [project64/project64#575]
Hello again :). I am trying to add code to plug or unplug a controller. For the default input plugin with 2.2, N-Rage 2.4.0.3, the following code works.

```
// force all 4 controllers to be plugged in
    for (int i = 0; i < 4; i++)
    {
        m_PluginControllers[i].Present = TRUE;
    }
```

For other input plugins I have tried, such as N-Rage's Direct Input 8 V2 1.83, the code above does not seem to do anything. The only clear difference I have found is that in CControl_Plugin::Initiate, the more modern plugin takes the "else if (m_PluginInfo.Version >= 0x0101)" fork whereas the older plugin does not.  Any suggestions on how to programatically plug in or unplug a controller with code for other input plugins?

Thanks,
Owna

**Comment by cxd4** [comment]
May be related to the different plugin spec PJ64-NRage uses?

First there's #1.0 which is the only zilmar spec for controller plugins available reliably.

There's #1.1 which was always skipped over and never officially implemented in PJ64.  Only Mupen64 for Linux seems to really require writing controller plugins in this spec, as #1.0 is unavailable there.

Then there's #1.2 which is private to Project64 plugin specs, so first-party PJ64 plugins use it.

Sometime ago I roughly drafted the differences between the 3 here:
https://github.com/cxd4/rcp64/blob/master/contr.h#L286

Maybe it has something to do with your issue, maybe not.

**Comment by Ownasaurus** [comment]
I still cannot figure this out

    if (m_PluginInfo.Version == 0x0100)
    	{

              ...

		    InitiateControllers_1_0((HWND)RenderWindow->m_hMainWindow,m_PluginControllers);

    		if (m_PluginControllers[1].Present == TRUE)
    		{
    			MessageBox(NULL, "Controller 2 is now present.", " ", NULL);
    		}
    		else MessageBox(NULL, "Controller 2 is NOT present.", " ", NULL);

Regardless of whether or not the controller is checked as plugged in in the GUI, the messagebox appears "Controller 2 is NOT present."

So it seems to be completely ignoring these variables for older plugins (in this case nrage v2 1.83), and that is why overriding their values is having no effect.

I suppose whether or not they are plugged in must be controlled by some other part of code.  Not sure if this is by error on purpose.  Will continue to look into it.  Let me know if anybody else finds anything too!

**Comment by cxd4** [comment]
NRage v2 1.83 uses version 1.0 of the controller plugin specs.

New PJ64 N-Rage that comes with Project64 uses specs version 1.2.

That was why I was hypothesizing that potentially it could be plugin versions?

**Comment by Ownasaurus** [comment]
Yes but I figured they would both control m_PluginControllers in the same manner since the rest of the code seems to rely on that same data structure regardless of the version number.

Boy was I wrong.

Looking at the source code of NRage v2 1.83, it looks like it keeps its own pointer to the controller data and changes it as it pleases.  Overcoming this could be messy.

**Comment by cxd4** [comment]
Have you tried NRage 2.1 rc3?
http://sourceforge.net/projects/nragev20/files/Nrage%20v2/NRage%20DInput8%20V2.1/

**Comment by Ownasaurus** [comment]
I had not; just did now.

The controller plugin code in the OP works just as well for the 2.1 you linked above as it does for the 2.4 bundled with P64 2.2. (AKA it works perfectly)

**Comment by Waksack2** [comment]
I'm playing and uploading Super Smash Bros 64 matches on YouTube with no picture! How did I change the Glide64 settings with no picture? That should be a issue!

https://www.youtube.com/watch?v=9TNIQLOyYxo
https://www.youtube.com/watch?v=k3dwOA6le9Y

**Comment by SwinglesMan** [comment]
^ does this mean it works now or no?

**Comment by Squall-Leonhart** [comment]
1.83 used DI7
2.x use DI8

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
