### ISSUE TITLE
G.A.S.P!! Fighter's NEXTream crash with recompiler

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#583]
At the title screen the game crashes with recompiler after you press start. Protect memory seems to fix the problem

**Comment by purplemarshmallow** [comment]
If I enable protect memory should the other self mod methods be disabled?

**Comment by cxd4** [comment]
Um possibly.  They're all just different techniques.

Normally to know for sure you would run with "Synchronise Cores" to prove that it's as stable as the interpreter, but if you can disable absolutely everything except just "Protect Memory" and still play the whole game IMO that's good enough for me.

**Comment by purplemarshmallow** [comment]
I haven't tested with "Synchronise Cores" but if I enable just "Protect Memory" the crash is gone and the game seems to run stable.
