### ISSUE TITLE
Temporaly disable Fixed Audio Timing when the Frame Limiter is disabled

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#589]
In order to be able to fast forward thru the game.
Currently, with FAT enabled, you're forced to play the game at normal speed, even when turning off the Frame Limiter.

**Comment by AmbientMalice** [comment]
This risks causing problems for games that *need* Fixed Audio Timing. Also, I'm pretty sure unlocking the frame limiter still works with FAT. What audio plugin are you using?

**Comment by LegendOfDragoon** [comment]
@oddMLan , sounds like you have sync audio enabled. Either through the plugin or the emulator.

**Comment by cxd4** [comment]
@oddMLan, "Prevent Buffer Overruns" seems to be what is doing it for me.

**Comment by oddMLan** [comment]
You're right
This issue only seems to affect Azimer's Audio Plugin, not Jabo's Audio.

*Jabo's Audio Plugin*
Sync Audio (core option) ON = unlocked fps
Sync Audio (Jabo's setting) ON = locked fps
Fixed Audio Timing ON  = unlocked fps
Both FAT and Sync Audio (core) ON = unlocked fps

*Azimer's Audio Plugin*
Sync Audio (core) ON = unlocked fps
Sync Audio (force old school audio sync) = always locked, but fluctuating between 59-61 fps
Fixed Audio Timing ON = locked fps (same as above)
Both FAT and Sync Audio (core) ON = locked fps (same as above)

But if the goal is to make Azimer's the default audio plugin in the future, I think either Azimer or Zilmar need to change their code behavior.

**Comment by cxd4** [comment]
Right, so in other words "Sync Audio" has nothing to do with this, unless you noobishly left a setting like that on from within Jabo's DirectSound while you were using that.  But I assumed you were smarter than that and that it was just PBO within AziAudio doing it.

**Comment by LegendOfDragoon** [comment]
>But if the goal is to make Azimer's the default audio plugin in the future, I think either Azimer or Zilmar need to change their code behavior.

You can simply disable PBO.

**Comment by oddMLan** [comment]
Right, disabling PBO does it.
Then, I'll close this and make it an issue for Azimer's plugin.

**Comment by cxd4** [comment]
Glad you posted that. :P I was almost about the post the issue myself.

And yeah, PBO should be "fixed" if possible as disabling it sounds terrible.  Would make more sense for sound quality to keep PBO enabled and that Fixed Audio is what should be disabled.
