### ISSUE TITLE
AI Shougi 3 "causing texture errors"

### ISSUE THREAD

**Issue by cxd4** [project64/project64#59]
I guess this has been known about in the RDB file for quite a while.
![aishougi](https://cloud.githubusercontent.com/assets/1396303/6090631/1b2887e8-ae4e-11e4-972a-6baa148aca02.png)

But 1964 0.8.5, 0.9.9, 1.? support it just fine, so why can't we have a solution in Project64 sometime?
![aishougi_fixed](https://cloud.githubusercontent.com/assets/1396303/6090639/3daf0e5e-ae4e-11e4-99a0-df58c9d72288.png)

Also, unintended rhyming.  ("file..while"; "fine..sometime"...idk lmao I swear I didn't mean that)

**Comment by exhalatio** [comment]
1964 is fixed from PI DMA odd length to an even length.
to checked dma.cpp Peripheral Interface DMA Write section.

**Comment by cxd4** [comment]
Good eye.  So according to schibo it is a corner case with unaligned PI DMA write.

I will experiment with his experiment.  He seems uncertain about the change himself, but it's been done in 1964 since at least 1964 0.7.0 (AI Shougi 3 works fine there too).

**Comment by LegendOfDragoon** [comment]
I think this is great, to implement good parts from other emulators :) . Thanks @exhalatio . How did you know, btw?

**Comment by exhalatio** [comment]
My pleasure @LegendOfDragoon .
Someone says schibo is leave a comment in source code, so I can find it :) .

**Comment by cxd4** [comment]
>I think this is great, to implement good parts from other emulators :) .

Well, whatever.  It's a mixed blessing I guess.  It would only be arrogance for me to try to isolate the issue on my own, as I would most likely not have guessed it was related to the PI registers until it was too late.
