### ISSUE TITLE
The MSVC 2013 build file skips building x64 plugins

### ISSUE THREAD

**Issue by tony971** [project64/project64#614]
From what I can tell (talking to @cxd4 ), the plugins will build in x64. The build file just isn't doing it.

**Comment by cxd4** [comment]
Well no, but there is a finished package to have all the basic plugins ported.
https://github.com/cxd4/project64/releases/tag/v1.0

**Comment by cxd4** [comment]
And yes the Project64 plugins do build in x64, but you haven't asked the solution file to build them.  Not that it really matters since most of those plugins aren't really in the category of Project64 anyway.

So not really any issue here.

**Comment by tony971** [comment]
So shouldn't the solution be updated to build what can be built? Or wait for Glide 64 to build first?

**Comment by cxd4** [comment]
I imagine that would mean you update the solution to build it.

There's also the Debug x64 build mode, which zilmar pre-configured to build N-Rage & RSP.

**Comment by JunielKatarn** [comment]
#687 fixed it. I think this issue can be closed.
