### ISSUE TITLE
Improving French Translation

### ISSUE THREAD

**Issue by Watilin** [project64/project64#618]
I want to improve the french translation, especially the overall consistency, and I'd like to debate about which accurate terms to choose and to stick to. Here is a non exhaustive list of such terms.

(By the way, let me know if there is a better place to talk about this kind of stuff.)

In **bold**, what seems to be the current consensus. Discuss if you disagree ;)

English Term | Possible Translations | Example .Lang Entries
-------------|-----------------------|----------------------
Save State | état, **sauvegarde d'état**, sauvegarde rapide | 125, 127, 129
Slot | slot (keep english term), **emplacement** | 191, 220
Input | input (keep english term), entrée, contrôle, **contrôleur** | 424, 2007
Directory | dossier, **répertoire** | 402, 485
Core | **noyau**, cœur (depends on context) | 501, 502, 542
Cheat | **cheat** (keep english term), triche, code triche | 11, 130
Reset | **réinitialiser** (config menus), relancer, **redémarrer** (actual emulation) | 121, 340, 720, 1100
Recursion | (see below) | 485

Also, there are some technical or vague terms I'm almost sure the current translation can be improved, but since I have no idea what these terms mean, I can't find a better translation.

**Current consensus** here seems to be don't translate.

Technical Term | Example Entry
---------------|--------------
Advanced Block Linking | 505
PI DMA | 511
TLB unmapping | 514
Fast SP | 530
Display lists | 701
LUT | 2026
Byte-swapping image | 2036

Here are the terms I'd really like someone to explain them to me.

Term | Entry
-----------|------
Quantity digit | 1016
Counter factor | 525
Failed to load word | 2009

About 485, “Use Directory Recursion”: I cannot find any satisfying translation to this, so I propose to alter the meaning and use “Utiliser également les sous-dossiers” (or “sous-répertoires”) which translates back to “Also use sub folders”. This is way more understandable in my opinion.

Now comes the spaaace problem. As you may know, the french language takes more space than the english one. Words are often longer, and sentences often use more words. I already noticed buttons and dialogs where the end of the text is clipped. Other translations may suffer this problem as well. Is there any planned work on fixing this? Just asking.

We might work this around by using abbreviations, but we need to be careful with this. A good example is the reset button in config dialogs (entry 720). The current translation states “Redémarrer la page”, which overflows. Likely to prevent such overflow, entry 1100 has been translated “raz” which is an abbreviation of “remettre à zéro”, but I've never seen this in any other software. Users may not understand it, and it looks colloquial to me.

Mentioning all contributors of the file French.pj.Lang:
@BenjaminSiskoo @cxd4 @death-droid @project64

**Comment by cxd4** [comment]
Well I don't know French, but @LuigiBlood does.

Any changes I have made to `French.pj.Lang` were related to how the other language changes are connected / stuff like consistency.  And yeah there is an IRC on Freenode we hang at, though I'm also content to talk this type of thing here.

Instead of "Also use sub folders", I would think "Also [check/read/scan/look in?] sub-folders" or sub-directories.  But yeah that sounds more clear than "directory recursion".

**Comment by LuigiBlood** [comment]
My choices would rather be:
- Sauvegarde Rapide
- Emplacement
- Contrôles
- Dossier
- Codes Triche
- Réinitialiser
- "Utiliser également les sous-dossiers" is fine by me.

I would rather suggest to leave the very technical terms to English, actually.

**Comment by Watilin** [comment]
Ok, I'm actually trying too hard with technical terms. The point is, maybe they need to be accompanied with a short description in english, and the descriptions would then be translated into other languages.

I'll make a pull request in half a day to provide more material to discuss on.

**Comment by BenjaminSiskoo** [comment]
Hello, 

Thanks for your advices. Here my thoughts :

Save State --> état, sauvegarde d'état, sauvegarde rapide --> entre sauvegarde d'état et sauvegarder l'état, c'est plus un choix de lisibilité. Sur toutes mes traductions, j'utilise Sauvegarder l'Etat. C'est une histoire de goût Par contre, sur certains émulateurs (je ne sais plus lesquels), il ya un distinguo entre Save State et QuickSave. Je pense que Sauvegarde rapide, ne serait pas approprié. 
Slot --> Emplacement est bien plus parlant à mon avis.
Input -->  input (keep english term), entrée, contrôle --> Plugin Contrôleur ?
Core --> noyau, cœur (depends on context) --> Pas de préf particulières. 
Cheat --> cheat (keep english term), triche, code triche --> Tout dépend de la place que j'ai pour la traduction. Pour un anglophobe, je pense que cheat est entrée dans la culture et reste compréhensible. Mais là aussi pas de préf.
Reset -->  réinitialiser, relancer, redémarrer --> il dépend du contexte, mais le plus souvent redémarrer semble bien correspondre. D'ailleurs de nombreux logiciels utilisent rédemarrer plus que réinitialiser par ex. Encore une question de goût.
Pour la récursivité, j'aime bien ta proposition. Le terme récursif est approprié mais moins parlant pour une partie des gens. 

Pour les autres termes techniques, là je suis pas à l'aise.

**Comment by Watilin** [comment]
> en tout les cas, ca me fait plaisir le retour :)

De rien ;)

> sur certains émulateurs (je ne sais plus lesquels), il ya un distinguo entre Save State et QuickSave. Je pense que Sauvegarde rapide, ne serait pas approprié.

J'en prends note.

> D'ailleurs de nombreux logiciels utilisent rédemarrer plus que réinitialiser par ex

Ok quand il s'agit de redémarrer l'émulation, mais à propos des boutons reset dans les menus de config ? Là il s'agit plutôt de *réinitialiser* la config à mon avis.

Pour « Core » ça dépend vraiment du contexte, et j'aurais pu placer ça dans les termes techniques. J'ai pris les entrées 501 et 502 comme exemples car ils montrent bien mon hésitation :

* 501 “Core Defaults” : il me semble qu'il s'agit du noyau de l'application, et dans ce cas le terme « noyau » est adapté ;
* 502 “CPU core style” : associé à CPU il pourait s'agir de cœur de processeur, mais comme le processeur de la N64 n'est pas multi-cœur, je ne sais pas vraiment de quoi parle cette entrée.

Je vais tâcher de tenir à jour mon premier message pour indiquer les propositions retenues.

**Comment by BenjaminSiskoo** [comment]
Pour les boutons, tu as tout à fait raison, j'ai fait une recherche rapide concernant la réinitialisation.
"Remettre un système informatique ou une application dans son état initial". Bien vu, je pourrais améliorer mes autres traductions à l'avenir :)

encore une fois remarque judicieuse pour les core.  

Quel plaisir d'échanger :)

**Comment by Watilin** [comment]
There are still a couple translations that doesn't satisfy me, and I'll be glad if someone explains to me what these terms mean.

Term | Entry
-------|-------
Counter factor | 525
Quantity digit | 1016
Failed to load word | 2009
byte-swapping image | 2036

The latter is especially important because it is regulary seen by the user: when a ROM is loaded but not launched, this message appears in the status bar.

You may have noticed that I didn't really consider the space problem in my PR. This is because I plan to make the text boxes/buttons flexible. If you think this is impossible, please let me know.

**Comment by cxd4** [comment]
Byte-swapping refers to correcting the byte order.

If you load a V64-dumped ROM (typically has `*.v64` file extension) then its byte order has to be converted from BA,DC to AB,CD.

Counter factor is some internal timer thing that I never needed to research.

never heard of quantity digit

**Comment by Watilin** [comment]
Ok, so the actual byte-swapping occurs only for a (normally) short moment, but the message stays because there is nothing else to display in the status bar. I probably got a little confused by that. Thanks anyway :)

Quantity digit is related to cheats, but I couldn't see it in the cheat window.

**Comment by Watilin** [comment]
Ready to open a new PR if my latest commit makes nobody scream :)

**Comment by BenjaminSiskoo** [comment]
Seems nice. Ok to me :)
