### ISSUE TITLE
Imediate hang in super mario star road and other hacks

### ISSUE THREAD

**Issue by Ember2528** [project64/project64#63]
Whenever you run a Mario64 hack the emulator shows a black screen and goes between 25 and 1 VI/s

**Comment by theboy181** [comment]
Sounds like its missing an RDB entry. Have you tried creating one using hacks that do work?

**Comment by theboy181** [comment]
Its working fine. just change the settings to 8MB for this ROM. For some reason pixel accurate plugins do not show video so use jabo or rice.

**Comment by Ember2528** [comment]
You where so thank you and I'm closing the issue
