### ISSUE TITLE
Taz Express missing letters

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#633]
I think this is a bug in the PJ64 core or in the RSP. Looks correct with Nemu64. I used GLideN64 with both emulators.
![gliden64_taz_express_000](https://cloud.githubusercontent.com/assets/7283660/10116121/2a96bdd6-6428-11e5-9eb1-15b816fa545f.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/10116122/2d0e12a8-6428-11e5-8447-63a4c4e0fb63.jpg)

**Comment by LegendOfDragoon** [comment]
I doubt the issue is the RSP. How did you get it working in Nemu? I just get a black screen.

**Comment by purplemarshmallow** [comment]
You need the latest ini you can download it from here: https://github.com/purplemarshmallow/Nemu64/releases

You have to select Debug -> disable audio HLE (2) and press ctrl+R
it's written in the comments section in the ini

**Comment by LegendOfDragoon** [comment]
Alright, thanks. Got it to work. Looks like the issue is the core.

**Comment by LegendOfDragoon** [comment]
Does M64p have this issue?

**Comment by purplemarshmallow** [comment]
Yes. This plus other bugs

**Comment by LegendOfDragoon** [comment]
I suspect the difference might be how the emulator handles the DPC registers. For instance, I noticed that in Nemu, DPC_STATUS_REG = 0x88, in my 1964 fork DPC_STATUS_REG = 0x80, and in Project64 2.2 DPC_STATUS_REG = 0.

**Comment by LegendOfDragoon** [comment]
Does it work in CEN64?

**Comment by purplemarshmallow** [comment]
Cen64 gives me this:
The "T" is missing
![taz](https://cloud.githubusercontent.com/assets/7283660/22261946/3047ba0c-e26f-11e6-806e-1126d2163beb.jpg)

**Comment by oddMLan** [comment]
Taz is saying _his_ game is not designed for use on emulators 😛

**Comment by project64** [comment]
DPC_STATUS_REG = 0x88 
cbuf ready and start gclk

I have no idea what those even are

**Comment by cxd4** [comment]
It's just like cen to omit letters necessary for grammatically correct English words.  lol somebody needs to PR some fixes to that emu's grammar it's almost as bad as pj's

>DPC_STATUS_REG = 0x88
cbuf ready and start gclk

What are you referencing with that?

**Comment by loganmc10** [comment]
I looked into this, it is caused by unaligned PI DMA access.

The cart address must be 2-byte aligned and the dram address must be 8-byte aligned.

Taz Express does a PI DMA Write with an unaligned cart address, stripping off the unaligned bit (~0x1) makes the letters show up

**Comment by loganmc10** [comment]
I assume that fixing this might break some of those SM64 ROM hacks that I've heard depend on emulators allowing unaligned DMA's? I could be wrong about that though.

**Comment by AmbientMalice** [comment]
>I assume that fixing this might break some of those SM64 ROM hacks that I've heard depend on emulators allowing unaligned DMA's? I could be wrong about that though.

You could add a special mode for romhacks, but sooner or later those romhacks are going to be unplayable on any emulator with anything approaching accuracy.

**Comment by purplemarshmallow** [comment]
@loganmc10 thanks for bringing light into this!

**Comment by project64** [comment]
https://github.com/project64/project64/commit/f0c9ea887e62712e411133e3b3c9e4629db5d9fe

should fix it as @loganmc10  suggested, thank you

**Comment by purplemarshmallow** [comment]
fixed
