### ISSUE TITLE
Coverity scans

### ISSUE THREAD

**Issue by tony971** [project64/project64#634]
These have been used as a QA for a few emulation projects, PCSX2 being the most recent. They're pretty useful for fixing bugs/cleaning code bases. Take a look at PCSX2's results. https://scan.coverity.com/projects/pcsx2-pcsx2

**Comment by cxd4** [comment]
You're welcome to start a scan if you want, but I personally am not registering personal information of myself to them just to see their opinion on code "cleanliness" in Project64.

As many disagreements as I have with the way PJ64 is written, it doesn't mean they share most of my agreements or my disagreements.  I'm not interested in little religious wars about coding style and the people who think there should just be one right way.  I'm sure they have many good suggestions as well as not-as-good ones; I'm not up to the task of asking them.

**Comment by oddMLan** [comment]
https://www.viva64.com/en/b/0600/ think it's relevant and https://www.viva64.com/en/examples/

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
