### ISSUE TITLE
(x64) Unimplemented core function

### ISSUE THREAD

**Issue by tony971** [project64/project64#641]
Trying to boot Rat Attack or Razor Freestyle Scooter will earn you a nice 

```
Break point at N64 System\Interpreter\Interpreter Ops.cpp 1307
```

**Comment by LegendOfDragoon** [comment]
That's cpu core, not RSP.

**Comment by cxd4** [comment]
```c

	if (!g_MMU->SW_VAddr(Address,_GPR[m_Opcode.rt].UW[0])) 
	{
		if (bHaveDebugger()) 
		{
			g_Notify->BreakPoint(__FILEW__,__LINE__);
		}
```
This breakpoint that you have run into is optional.  It can be skipped by temporarily disabling "Enable Debugger" in the PJ64 advanced settings.  Maybe the results will be more or less like what you see with the 32-bit build of Project64.

_Rat Attack_ I know for sure has known TLB support issues with Project64.  Whether 32- or 64-bit build is being used makes no solution to that question.

**Comment by LegendOfDragoon** [comment]
is this stil an issue?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
