### ISSUE TITLE
(x64) V-Rally Edition 99 error

### ISSUE THREAD

**Issue by tony971** [project64/project64#642]
```
02
DP Reserved Command
```

Right at boot.

**Comment by cxd4** [comment]
That comes from the RDP interpreter loop, but not the core.

It means some CPU settings or other bug has caused the game to exceed the command buffer cache for queuing the DP instructions.  You should either try testing with a different 64-bit graphics plugin or try the game on 32-bit Project64 to see if that also has the issue.  Um, I don't have this game.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
