### ISSUE TITLE
Rainbow effect in pasue menu.

### ISSUE THREAD

**Issue by theboy181** [project64/project64#65]
Legend of Zelda OOT 1.2

When using HATS RSP and HATS RDP and you press start to the menu, sometimes rainbow colors occur in the frame.

![capture](https://cloud.githubusercontent.com/assets/9299743/6101312/eeb71dac-afd6-11e4-9426-f56916c50e43.PNG)

**Comment by theboy181** [comment]
Seems to get sorted out when disable game fixes enabled.Should I close this?

**Comment by Fanatic-64** [comment]
You can see there that the first row of TexRects is rendered normally, like in GLideN64. That's caused by the memory code fix.

The issue is being discussed here: https://github.com/project64/project64/issues/20

**Comment by cxd4** [comment]
That's the depth buffer, not the color/frame buffer.

I guess that's what the GameShark cheat codes...swaps which pixel buffer VI_ORIGIN_REG ends up ultimately pointing to?  Swaps what is written...the frame buffer contents or the Z buffer contents?  Well either way it's a hack for a reason, so I don't see it as much of an issue.

It is more-or-less a duplicate of #20 though, which probably should also be closed.  The only reason it's open is probably just because zilmar hasn't implemented the exclusion of non-Jabo plugins to not have the cheat applied.

**Comment by theboy181** [comment]
Thank for the explanation..

**Comment by oddMLan** [comment]
> I guess that's what the GameShark cheat does...swaps which pixel buffer VI_ORIGIN_REG ends up ultimately pointing to? Swaps what is written...the frame buffer contents or the Z buffer contents?

Nope. But according to what zilmar wrote in emutalk ten years ago...
> basicly look to find a location it was in during waiting for the screen to appear, then do analysis on the mips code around it to see what it was doing .. it appeared to be part of a function .. (hack the source) to set a break point at the calling of the function .. found the function was kept being called .. so it was not stalling in the function .. found then when looked at the calling location it was in a loop, calling this function and that it called it 0xf0 times .. this value was not hardcode .. but located in memory .. I tried modifieing the value in memory and found that it did impove things .. so I wrote a gameshark code to do that modification of memory.

**Comment by cxd4** [comment]
Sure, looks impressive homie.  Guess that's supposed to make a bunch of non-Dolphin developers get all competitive with each other or something.

Except for one thing worth pointing out:  He said 240 "times".  He's saying he caused the looped block to not have 240 iterations; you're falsely equating that to cycles out of absolutely no understanding of the actual situation.  (And if you were to ask zilmar, he would say he knows little to nothing about graphics whatsoever.  I'm not sure if you asked him 12 years ago, his opinion would differ.)  Therefore what he said does not contradict the Z-buffer versus color buffer observation in theboy's screenshot, but rather generalizes it to a simple matter of not iterating a loop as many times.

**Comment by oddMLan** [comment]
Oh no, it wasn't my intention to sound like I was "refuting" your argument, but was meant to provide more info about what the cheat does. But now that I re-read my post, it indeed sounds like that. I actually was meaning to change "nope" with "not exactly" but either way my post was poorly worded and just shows how little I know about the matter and that I should avoid taking someone else's word as correct (Smiff said that one bit about "reducing the number of cycles going into the menu from 240 to 2"; I understood it like that too so I just copied what he said).

**Comment by cxd4** [comment]
yeah Smiff mostly was a tester, I don't really know anything else about him in that department

But 320x240 scanlines != 320x240 cycles so pretty sure he made that part up out of guessing.
