### ISSUE TITLE
CN64System::StartEmulationThread, thread priority not being set

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#660]
~~In the source it looks like its supposed to set the thread priority to above normal.  But it stays at normal.~~

I have a problem with any thread priority below highest.  Wiggling the mouse slows down the VI's.
I have to set the priority to highest in task manager every time I start Project64.exe.

**Comment by Frank-74** [comment]
Also it causes a problem with Azimer's audio.  From the 0.7 readme.
```
5.1.Q - Why do I hear some pops in some parts of the game?
5.1.A - I have noticed through my own testing that during certain parts of a game, the game uses the
        emulated processor power to the point where it can not perform at a constant 60/50FPS if even
        for a moment.  This neglect will cause the constant stream of audio to the plugin to be halted
        for that brief popping period.  It is not a problem with the Audio plugin and nothing can be
        done to accommodate.  You can try setting the emulator to High priority to eliminate the turn
        around time for the emulator to preempt any process during its waitstate.  It seems to have
        helped me
```

**Comment by Frank-74** [comment]
Apparently, Windows 8 requires the header Processthreadsapi.h.

**Comment by Frank-74** [comment]
I've found the problem with 'Process Hacker 2'.  The thread CN64System is being set to priority normal, or rather the default, as its not being set for CN64System thread.  Using Process Hacker 2, if I manually set just the CN64System thread to highest, there is no lag in VI's or clicks/pops from the audio.

**Comment by Frank-74** [comment]
Don't know how to set the priority in the source.  Here is the details of the thread priority.  I need to set CN64System::StartEmulationThread to Highest or Time Critical.
![threadpriority](https://cloud.githubusercontent.com/assets/11056843/10381224/e4db3af4-6e10-11e5-972c-e972df5782fa.PNG)

**Comment by Frank-74** [comment]
I've just managed to fix it.

In N64Class.cpp:
```cpp
void CN64System::StartEmulationThread (  ThreadInfo * Info ) 
{
	SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_HIGHEST );
```

**Comment by AmbientMalice** [comment]
Good job.

**Comment by JunielKatarn** [comment]
@Frank-74 Are  you planning to submit a PR for this?
It should be interesting to test possible performance gains in lower-end machines.

**Comment by Frank-74** [comment]
@JunielKatarn PR already done here.  https://github.com/project64/project64/pull/661

**Comment by JunielKatarn** [comment]
Nice :+1:

**Comment by Frank-74** [comment]
New PR here. https://github.com/project64/project64/pull/664

Made it an application option.  To turn on you need to add EmulationTimeCritical=1 under the [default] section in Project64.cfg.
