### ISSUE TITLE
Non-compresed savestates are semi-broken (ramdom blackscreen while loading)

### ISSUE THREAD

**Issue by md500** [project64/project64#667]
While saving with F5 it takes the savestate but if i want load a savestate it 
blackscreens the emulator(i dont know if are referenced to native saving which work 
perfectly with this game) but i hearing the sound.This sometimes happens with "Banjo 
Tooie (E) (!)" (other games not tested).

PD: Sorry for my english,and sorry if this issue are been reported already.

**Comment by LegendOfDragoon** [comment]
What video plugin are you using?

**Comment by md500** [comment]
Jabo direct3D8 1.6.1. Same issue with Glide64 2.0.0.9999 and Jabo Direct3D8 1.7.0.57-ver5. Audio plugin is Azimer HLE audio v0.56 WIP 2,tried with Jabo Directsound 1.7.0.7, same issue.

**Comment by LegendOfDragoon** [comment]
@md500 , do you mind testing other games too?

**Comment by md500** [comment]
Yes.I tried with Banjo-Kazooie,The Legend of Zelda Ocarina of time/Majora`s mask(it shows a blackscreen with a yellow(_) in the screen)Tetrisphere,.I hearing the sound as happens for the first game,including background effects sound fx.I dont know if happens in all games.one curiosity is what compressed savestates include a .pj(x).dat file in the zip,so i thinking if no .pj.dat file does not exits.the savestates could no be loaded or you can implementent .pj(x).dat file in the .pj(x) file itself,while saving.
