### ISSUE TITLE
Request: Preferred controllers

### ISSUE THREAD

**Issue by tony971** [project64/project64#668]
Currently, if you use a controller and then boot Project64 without it plugged, it will un-map everything. Plugging in the controller and restarting PJ64 still leaves it un-mapped. Granted, you can use local profiles to get the configuration back, but it would be nice to see a sort of "if plugged" pecking order for configurations. E.g. "If controller A is plugged, use configuration for controller A. If not, check for controller B. If neither controllers A or B are plugged, use keyboard configuration."

**Comment by AmbientMalice** [comment]
Honestly, it shouldn't be unmapping controls if the controller is absent anyway. Old versions of Nrage never did that.

IMO, N-Rage should have keyboard inputs and controller inputs separate with presets. That you a user can just plug in a 360 controller and it will work, with GC-style N64 controls.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
