### ISSUE TITLE
Configure ability regresion

### ISSUE THREAD

**Issue by theboy181** [project64/project64#67]
ScreenHertz= XX doesn't work any longer in the RDB

I like to use this to OC the VI's for testing purposes. Was this change on purpose? Can we please add it back in?

Thanks

**Comment by project64** [comment]
it should be better calculated now, tho the value in the rdb/cfg file should over ride the calculation, I need to look at why it no longer does.

**Comment by cxd4** [comment]
http://forum.pj64-emu.com/showthread.php?t=4685

recent regression...?

**Comment by death-droid** [comment]
Fixed, can be closed now

**Comment by theboy181** [comment]
Great stuff!!!
