### ISSUE TITLE
Branch instruction on delay slot.

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#670]
Mario Tennis has Branch instruction on delay slot.

images are mario tennis 64 (J)
![marioteninis_1](https://cloud.githubusercontent.com/assets/11252775/10416619/7127e9aa-7058-11e5-9e5b-3d6fb56a4a95.jpg)
![marioteninis](https://cloud.githubusercontent.com/assets/11252775/10416620/74cfc23a-7058-11e5-8aaa-144a01a01579.jpg)

pj64 can properly emulate this?

**Comment by exhalatio** [comment]
BTW, disabling the Advanced block linking to avoid 8002b894 opcode due branched in 8002B888 opcode.
Nemu64 is also always branched in 8002B888 opcode.
![mariotennis64](https://cloud.githubusercontent.com/assets/7089513/10419162/8a4f1d1c-70a9-11e5-8eaa-8260bd172ac4.png)

**Comment by project64** [comment]
It is an invalid operation, now advanced block linking is trying to follow a lot of different code paths to make the code more efficient, this can allow it to follow code that is never actually executed. If you run as interpter/disable advanced block linking does it actually hit there. 

Is this message shown when debugger is disabled?

**Comment by Nekokabu** [comment]
@exhalatio PJ64 is also so,I confirmed it by using the cheat code.
Cheat0=8102B894 1000,8102B896 FFFF

@project64 This warning is no longer displayed. thanks:)
>Is this message shown when debugger is disabled.?
Yes, but In order to find a bug, debugger is enabled.
