### ISSUE TITLE
Request: Video Dumping

### ISSUE THREAD

**Issue by thecoreyburton** [project64/project64#671]
I often go between several different emulators depending on the purpose of my activities. My favorite is Project 64, though it lacks a frame-accurate video dumping method at the moment. I want to dump videos in lossless rgb (lagarith would be my preference) and use this emulator, but at the moment my only option is something like Fraps, which even in the best circumstances drops a frame here or there. Is this something that is possible?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
