### ISSUE TITLE
subscreen delay

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#674]
subscreen delay affects these games: Paper Mario, Zelda OOT, Doubutsu no mori
The game checks if the background is drawn but how exactly? 

In Zelda OOT and Doubutsu no mori the depth buffer and the subscreen background are stored at the same address? Maybe depth buffer also plays a role?

In Zelda OOT there are CPU reads from the colorbuffer and there are CPU reads and writes from and to Link's portrait in the equipment subscreen. Why does the CPU need to read/write here? Related with the subscreen delay?

These are the known solutions:
-use angrylion's plugin
-fill colorbuffer with white color (hack and this breaks the subscreen background in Paper Mario)
-use a cheat code (hack and this breaks framebuffer effects)

This does not work
-Jabo's software renderer
-Glide64 with hardware framebuffer emulation disabled

**Comment by LegendOfDragoon** [comment]
I would like to look into this, sometime this week. Do you know the address of the buffer in zelda? I have a few ideas to try out.

**Comment by project64** [comment]
I believe the CPU is looking to see if the gfx has finished processing ..

**Comment by purplemarshmallow** [comment]
It should be possible to get rid of this "copy white to RDRAM" hack. Would be nice since this hack breaks the pause menu background in Paper Mario

The pixel coverage area is mostly white. A hardware renderer could just copy white pixels there by default. More accurate than nothing and good enough to fix subscreen delays.
But I don't fully understand how it can be implemented. How can I find out at which address in RDRAM the pixel coverage is stored? The current copy white hack just copies white pixels everywhere
![zelda](https://cloud.githubusercontent.com/assets/7283660/21681877/8e684066-d351-11e6-8a10-26119024edd0.png)

**Comment by project64** [comment]
with out a per game hack, how would zelda be fixable unless all the writes were to rdram?

**Comment by LegendOfDragoon** [comment]
I think it would be easier to first debug with GLideN64. Too bad I never managed to compile it.. Maybe someone can port the copy white pixels code to Glide64. After I find the address, I can debug angrylion's and see what the real results look like.

Been a while since I looked at coverage, I'll have to review that.

**Comment by project64** [comment]
copyWhiteToRDRAM is the function, it just copies white to the image each frame

**Comment by LegendOfDragoon** [comment]
oh wow, I see now. That is odd how filling it with white can fix the delay. For some reason, I was thinking it was a different buffer. Guess I can focus on debugging Angrylion's now.

**Comment by purplemarshmallow** [comment]
>with out a per game hack, how would zelda be fixable unless all the writes were to rdram?

I don't think it's fixable without writing to RDRAM. But I think the copy white hack can be improved so it writes white pixels to RDRAM but only where pixel coverage is stored on real hardware. Then it can be enabled for all roms without negative side effects.

**Comment by purplemarshmallow** [comment]
@LegendOfDragoon I think the game must be using pixel coverage as color buffer at some point and that's why the copy white hack works

**Comment by LegendOfDragoon** [comment]
Iirc, the game checks upper bits of each byte in the color buffer and compares it with some other value. Maybe I should try out that fork of pj64 that supports debugging. Too bad it requires cpu interpreter for debugging though ;/ .

**Comment by cxd4** [comment]
>Too bad it requires cpu interpreter for debugging though ;/ .

...what does that matter?  Nobody using Project64 educated on the difference between compilers and interpreters even uses the debugger for playing their games.

**Comment by cxd4** [comment]
(switches Visual Studio solution to compile as Debug instead of Release)

(steps through the debooger in MSVS)

"lol too bad it requires turning off code optimizations"

**Comment by LegendOfDragoon** [comment]
>...what does that matter?

It's less convenient to debug when I'm unable to run full speed. In games I normally play, I suppose I can just use save states, but it will be a hassle for games I don't normally play. I like to disable frame limiter to skip through parts of the game.

Anyway, I'll just use that PJ64 fork as a last resort. Usually other methods are good enough for debugging.

>"lol too bad it requires turning off code optimizations"

Lol I've honestly said that to myself before. I only resort to compile as Debug, when I believe it's absolutely necessary.

**Comment by cxd4** [comment]
Debugging is slower, but last I built it not that much slower.

It might or might not be considered full speed, but for me using the debugger in zilmar's RSP interpreter it was fast enough to play around with anyway on the rare occasion that you need to debug something.

In either case, good luck getting a debugger to work with the recompiler and not just the interpreter.  I have no idea how Nemu64 did it, but in principle it sounds impossible while having an optimized recompiler.

**Comment by Frank-74** [comment]
Has anyone tried this project64 debugger fork?
http://origami64.net/showthread.php?tid=549&pid=5199#pid5199

**Comment by LegendOfDragoon** [comment]
Fortunately I haven't ever needed to use the RSP debugger that often :smile: .

Sure you can optimize the interpreter, but that won't be easy to significantly speed up, if it's even possible. I do think the interpreter ought to be sped up anyway, because PJ64 is too slow with Synchronize Cores. I know it's not trivial to implement a debugger for a recompiler, but it's worth the investment imo.

>Has anyone tried this project64 debugger fork?

Haven't tried it yet, but that was the one I was referring to. He has the source on github. It even lets you set breakpoints for DMA, iirc. Might be useful for figuring out a good way to detect SMC.

**Comment by cxd4** [comment]
Debugger is not supposed to be written for speed.  (...well, it's not supposed to be written to bring your frame rate down to 1 or 2 VI/s either, but still) Your debugger needs to be bug-free, stable, clean code, not fast.  If you write your debugger for speed you lose the ability to keep it error-free.

Game play should be written for speed.  Game monkey play N64.  Game monkey see PC.  Game monkey download illegal files on PC.  Game monkey expect his PC to work as smoothly as a N64.  Game monkey see debugger.  Game monkey not give damn how fast debug window opens, closes and steps.

Yes the recompiler needs a debugger to debug recompiler-exclusive things like the x86 cache etc.  It doesn't need to be able to debug anything that the stable interpreter is already well-equipped to thoroughly and completely debug.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
