### ISSUE TITLE
wxWidgets error.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#675]
Using default plugins and settings, start F1 Racing Championship (E) (M5), and when the video starts (in wrong aspect ratio), open Settings.

![wxerror](https://cloud.githubusercontent.com/assets/11056843/10563290/52f68ee0-757c-11e5-9688-afbf1a460388.PNG)

Seems to only happen after Jabo writes a d3d syslog.

**Comment by Frank-74** [comment]
Happens also after adding a cheat.  So its not just a Jabo problem.

**Comment by JunielKatarn** [comment]
What exactly is wxWidgets used for?
Only GUI window elements?

**Comment by Frank-74** [comment]
@JunielKatarn 
I think only the UI, zilmar will have to confirm for certain.

Its a recent regression.  Wasn't getting this error a few weeks ago.

I using Windows 8.1.

**Comment by cxd4** [comment]
I always got this error just by having AziAudio.dll and Glide64 final both installed to the Plugin subfolder, regardless of which plugins were currently selected.  But I can't remember what I did to fix it--probably just deleted Glide.

**Comment by Frank-74** [comment]
#783 fixes these errors.

**Comment by oddMLan** [comment]
Fixed with the removal of wxWidgets 68a8ed03696f3365430d8cca14d5084100165cd0
please close
