### ISSUE TITLE
Triple Play 2000 not working. 

### ISSUE THREAD

**Issue by theboy181** [project64/project64#677]
Game has issues, but comments say playable. Turned of 32bit Engine fixes GFX, but the camera goes crazy.

**Comment by Frank-74** [comment]
Also CPU Interpreter hangs at EA Sports logo on startup.

**Comment by Lithium64** [comment]
@theboy181 the camera works fine here

**Comment by Frank-74** [comment]
Works perfectly with Glide.  Jabo has missing graphics in stadium.

Glide64 for PJ64:
![glide64_triple_play_2000_01](https://cloud.githubusercontent.com/assets/11056843/20608904/2f60ce60-b27e-11e6-83d7-a562205deb0d.png)

**Comment by LegendOfDragoon** [comment]
@theboy181 is this still an issue? Please test :smile: .

**Comment by theboy181** [comment]
Not sure what was fixed, but this seems to be working for me now.. Thanks!
