### ISSUE TITLE
(x32) Glide64 build errors

### ISSUE THREAD

**Issue by tony971** [project64/project64#679]
https://gist.github.com/anonymous/39257d3fcaedbd664881

**Comment by cxd4** [comment]
None of your line numbers match the actual code from the first error message:
https://github.com/project64/project64/blob/master/Source/Glide64/3dmath.cpp#L239

So I think the rest of us can agree that you haven't pulled correctly to the updated code.
```shell
git pull https://github.com/project64/project64.git
```

**Comment by tony971** [comment]
Ahh I had merged pull reqests on my own before pulling. I thought that I had undone the changes but I guess I was wrong.
