### ISSUE TITLE
call ID_CURRENT_SAVE_DEFAULT is not translated

### ISSUE THREAD

**Issue by project64** [project64/project64#683]
"Save Slot (%s) selected" this text should be translated ... maybe the code needs a way to replace variables .. like should the translated string have %s works fine here but not good if I need to add 2 params

**Comment by cxd4** [comment]
Don't know the details but it looks like it could still be legible if it said "Save Slot %i selected", instead of "Save Slot (%s) selected".  That way if it was just %i (or %d or %u) then the decimal wouldn't need a second multi-language param since it would be the same in all languages.

**Comment by project64** [comment]
more in languages like c# you o $1 for the first param $2 for the second. This is for the string to be translated where sometimes the sentence structure is reversed

**Comment by cxd4** [comment]
I would just let the language file author move the `%i` around to accompany sentence structure.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
