### ISSUE TITLE
Some dialogs doesn't show OK. [Project64 v2.2.0.3]

### ISSUE THREAD

**Issue by Hiro5** [project64/project64#685]
In this image:

![smallbugs](https://cloud.githubusercontent.com/assets/12958627/10715391/bbe83766-7b15-11e5-9826-c16c95e4414d.jpg)

To the left dialog:
You can see the English dialog "About config files"
It shows
"A:" instead of "Author:"
"V:" instead of "Version:"
"D:" instead of "Date:"
And in the "Current Language" section, it only shows the first char of the author, version and date.

And in the dialog to the right, it's the Spanish "Preferences" dialog.
it shows the label "Estado del CPU:" wrong... I think that label it's too small that some languages cannot show it properly.
The same happens with the "Reiniciar página" button.

Please, check that :)

**Comment by cxd4** [comment]
IIRC @MELERIX was working on the translations fitting in the dialog better.

**Comment by MELERIX** [comment]
yes, I'm still waiting for this pull to be committed first: https://github.com/project64/project64/pull/542

and then I can update spanish file to match it, and also fix others related things.

**Comment by project64** [comment]
with #542 the branch has conflicts that must be resolved, so I can not just merge it.

**Comment by MELERIX** [comment]
I see, ok, I'll make a new patch later ;)

**Comment by MELERIX** [comment]
this can be closed now, it is fixed in: https://github.com/project64/project64/commit/3be6bfc7b98d9a9f5cadf8091f98d2832f9eb7d7

proof:
![shortcut](https://cloud.githubusercontent.com/assets/1040116/10833462/c5b0866e-7e70-11e5-8651-2cd6aa0729b1.png)
