### ISSUE TITLE
_Resident Evil 2_ unplayable on RSP compiler

### ISSUE THREAD

**Issue by cxd4** [project64/project64#69]
_Resident Evil 2_ currently requires a RSP interpreter plugin.

RAM CFB capture when using RSP 1.7.0.9 "recompiler":
![nree](https://cloud.githubusercontent.com/assets/1396303/6129066/837d0f68-b109-11e4-9423-4bd2b7466a6f.png)

CFB capture with properly done RSP:
![nree_fix](https://cloud.githubusercontent.com/assets/1396303/6129399/4566d1e8-b10c-11e4-8b85-92a5609b1a78.png)

**Comment by cxd4** [comment]
In my personal experience, that looks like VRCP/VRCPL is broken in the recompiler.  It usually produces that rainbow stretching of the triangle slopes and coordinates, but I can't say for sure.  Perhaps it is a recent regression from @LegendOfDragoon commits, but I can't confirm since unmodified RSP 1.7.0.9 from beta package just crashes at this part of the game without interpret.

**Comment by project64** [comment]
what does  properly done RSP mean? Is that the interpeter? Different RSP plugin, screen shot from a real n64 :P

**Comment by LegendOfDragoon** [comment]
How does it look with 1.7.0.9 RSP Interpreter? I assume you used your own RSP for the 2nd pic.

Anyway, if it's a problem with VRCP/VRCPL, the recompiler just calls a cheat function, so the interpreter would need to be fixed. I've been browsing the microcode for RE2 LLE gfx and I must say it looks interesting.

**Comment by cxd4** [comment]
*sigh*

If it's an interpreter, it's properly done.  I checked both my RSP interpreter and RSP 1.7.0.9, RSP 1.7.0.3 interpreters for the second pic--they all give the same result so I was referring to multiple RSP interpreters when I said that, not only mine.

But yes you're basically right project64 since I don't have a real N64 anymore, let alone a RE2 cartridge so do not have a real N64 screenshot (like we need one to see the recompiler's issue here).

However I've had someone give me real N64 screenshots before--plug in their GameShark Pro / ActionReplay and dump the RDRAM from the game while it was running, send it to me, then I would extract the frame buffer and do a binary compare of the entire file to my angrylion plugin's emulated RDRAM capture...complete match for all bytes 100%.  So I have previously confirmed and verified exact pixel-accuracy to real N64 results before, but yeah, not with this particular game.

**Comment by cxd4** [comment]
> How does it look with 1.7.0.9 RSP Interpreter?

see above post, I didn't think to upload a saved state since it's easy to just boot ROM, press START, "New Game", first in-game action scene where you can move around

> I assume you used your own RSP for the 2nd pic.

I test multiple different RSP plugins all the time.  I take not only opportunities to find bugs in RSP recompiler, but to see if my own interpreter has a bug that PJ64 RSP interpreter doesn't, or vice versa.  Recompiler just happened to be the odd one out in this case when I went to file the report

Okay so maybe it's not a VRCP* issue then.  Still that looks just like a inverse/inverse root bug I used to have with my RSP.

**Comment by cxd4** [comment]
For those of you who might be curious, here is one of several Mario64 tests I ran:
https://dl.dropboxusercontent.com/u/16494013/n64/n64_vs_emulator.png

I might be backwards on this (can't fully remember without checking irc logs), but I **think** the upper-left and lower-right screenshot is when running in an emulator, like Project64, with my angrylion RDP, and the upper-right and lower-left screenshot is taken from a genuine Nintendo 64 by means of a GameShark device to dump the 8 MB RDRAM (from which I then took my own procedures to manually extract the CFB).

It's not an exact match in that case obviously since I had to guess around with Mario's angle and facing the sky with my limited keyboard range (therefore I was not able to open up both screenshots in a hex editor and do a Compare/Contrast to see if all RGBA bytes are a perfect match in this particular case), but you can see the same precise artifacts in both the real N64 screenshot and the emulated screenshot with my RSP/pj64 RSP interpreter + angrylion RDP.

**Comment by LegendOfDragoon** [comment]
Well I can't seem to reproduce this problem. What version of RE2 are you testing? I tried v 1.1.

**Comment by cxd4** [comment]
Yes, (U) V1.1 .

I can try sending you a DLL over IRC later I guess; right now I need to file a new issue on getting the solution to build with VS2013 on my current laptop.

**Comment by theboy181** [comment]
I don't seem to have an issue with this game using RSP 1.7.0.9 that came with PJ64's current build.  I'm using AL's GFX Plugin and everything looks OK to me. Looks fine on static interpreter too?
How are you producing that bug?

**Comment by cxd4** [comment]
I see the error all the time, inside or outside of doing a screenshot/CFB capture.  In fact @LegendOfDragoon now sees it after I sent him my build of the RSP plugin over IRC.  I figured his build may have had some local fixes which caused it to not have the issue, so he was working on fixing it.

Though it's curious you don't see the issue with the official RSP 1.7.0.9 plugin that comes with the latest official release of Project64 2.1?  Because I can't even get in-game without crashing on that build, unless it's set to Interpreter.  Are you sure RSP is set to recompiler in the Debugger menu?

Also I can try sending you the latest build like I did with RPGMaster if you caught on IRC today.

>How do I capture RAM CFB anyway?

unreleased feature I had implemented locally in the angrylion plugin, in the next release there should be a button to dump RDRAM as a binary pixel-map and a program I wrote to view entire RDRAM as 1-, 2-, 4-, 8-, 16-, 32-, 64- or 128-bit-per-pixel raster picture.

**Comment by cxd4** [comment]
nub fail tho

**Comment by cxd4** [comment]
Ah, crap.  Maybe I wasn't supposed to close this.

@theboy181 and myself later found out that this RSP recompiler issue was nonexistent after trying again to build it from the latest project64 source, which caused me to think I was falling behind the repo master due to keeping all my pull requests open.

Turns out I wasn't hallucinating this.  This issue DOES happen if you build with MSVC2008 (which theboy181 and @LegendOfDragoon never seem to do), just not if you build with MSVC2013.  So I guess this would be a fine example of "undefined behavior".

On a whim I want to leave this issue closed since MSVC 2013 is newer than 2008, but on a whim I also want to re-open it since zilmar releases officially from VS2008 builds I think (plus undefined behavior of this type is definitely a hindrance)...so I think I will go back to this being open.

**Comment by theboy181** [comment]
Good find. Knew you weren't crazy.

**Comment by cxd4** [comment]
https://github.com/project64/project64/pull/100
