### ISSUE TITLE
Multiple "3rd Party" folders for 7-zip?

### ISSUE THREAD

**Issue by cxd4** [project64/project64#693]
I had noticed there are two "3rd Party" folders for 7-zip things.

One of them is `project64\Source\3rd Party\7zip`.
The other is `project64\Source\Project64\3rd Party`, which is empty except 3 7-zip files.

Could this be an unintended duplication similar in some way to https://github.com/project64/project64/issues/673 ?

Not really a big deal, just that when there is a MinGW script to port Project64 outside of MSVC it's nice to not add multiple "3rd Party" folders.

**Comment by oddMLan** [comment]
^ this

**Comment by cxd4** [comment]
Appears to have been taken care of by zilmar quite some long time ago.

Needed to make sure I only have one 3rdParty dir to choose from including for GlideHQ here....

**Comment by oddMLan** [comment]
The files are still under Project64-core

**Comment by cxd4** [comment]
Oh I guess I was really just looking for things like ZLIB while making the GlideHQ script.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
