### ISSUE TITLE
Plugins not initialized

### ISSUE THREAD

**Issue by tony971** [project64/project64#703]
Not sure if it's only with executables built with VS2015, but plugins fail to initialize on ROM load.

**Comment by JunielKatarn** [comment]
Same here.
Tested with a clean build, right from master branch, latest commit (as of this writing).

This bug was introduced within the last 48 hours.

**Comment by JunielKatarn** [comment]
I just verified it also desn't work with VS2008.
It's safe to assume it's not VS version-dependent.

**Comment by cxd4** [comment]
lol.
Which is why I wonder When did all of these regressions pop up out of the blue??

But even if I spend my time isolating and fixing it, zilmar is busy restructuring much of the entire Project64 core-UI modulation.  I just figured it's safer to wait for that first then start touching the core again.

**Comment by JunielKatarn** [comment]
I'm sure it shouldn't be too hard to track, but I'm busy at the moment.
If no one fixes it before, I might take a look over the weekend. (Any volunteers? XD)

**Comment by cxd4** [comment]
If time goes on then one of us fixes it in the end.

tony why don't you play around with `git checkout #######` and re-build from each GitHub commit hash number and isolate it?  As you seem to have a lot of time for testing.

**Comment by JunielKatarn** [comment]
@tony971: I would start with the latest commit available 3 days ago (meaning, pushed to the main repo, NOT commit date).

Then, do a binary search approach. Shouldn't take that long :P

**Comment by Frank-74** [comment]
Maybe test before/after this commit 3 days ago?
https://github.com/project64/project64/commit/0144305c6a50e88158c09c76a56126ae8f5f3449

**Comment by aschwant** [comment]
This is fixed with #713.
