### ISSUE TITLE
MSVC 2013 cannot compile:  missing #include "afxres.h"

### ISSUE THREAD

**Issue by cxd4** [project64/project64#71]
```
Error	1	error RC1015: cannot open include file 'afxres.h'.	C:\Users\no\project64\Source\RSP\RSP.rc	10
Error	2	error RC1015: cannot open include file 'afxres.h'.	C:\Users\no\project64\Source\Glide64\Glide64.rc	10
Error	3	error RC1015: cannot open include file 'afxres.h'.	C:\Users\no\project64\Source\Project64\User Interface\UI Resources.rc	10
Error	4	error MSB6006: "cmd.exe" exited with code 2.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170
```

```
1>------ Build started: Project: Glide64, Configuration: Release Win32 ------
2>------ Build started: Project: RSP, Configuration: Release Win32 ------
2>RSP.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.
2>  
1>Glide64.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.
1>  
3>------ Build started: Project: Project64, Configuration: Release Win32 ------
3>User Interface\UI Resources.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.
3>  
4>------ Build started: Project: Project64Setup, Configuration: Release Win32 ------
4>  Performing Custom Build Tools
4>  Inno Setup 5 Command-Line Compiler
4>  Copyright (C) 1997-2011 Jordan Russell. All rights reserved.
4>  Portions Copyright (C) 2000-2011 Martijn Laan
4>  Inno Setup Preprocessor
4>  Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.
4>  
4>  Compiler engine version: Inno Setup 5.4.3 (u)
4>  
4>  [ISPP] Preprocessing.
4>  [ISPP] Preprocessed.
4>  
4>  Parsing [Setup] section, line 7
4>  Parsing [Setup] section, line 8
4>  Parsing [Setup] section, line 9
4>  Parsing [Setup] section, line 10
4>  Parsing [Setup] section, line 11
4>  Parsing [Setup] section, line 12
4>  Parsing [Setup] section, line 13
4>  Parsing [Setup] section, line 14
4>  Parsing [Setup] section, line 15
4>  Parsing [Setup] section, line 16
4>  Parsing [Setup] section, line 17
4>  Parsing [Setup] section, line 18
4>  Parsing [Setup] section, line 19
4>  Parsing [Setup] section, line 20
4>  Error in C:\Users\no\project64\Source\Installer\Installer.iss: The [Setup] section must include an AppVersion or AppVerName directive.
4>  Compile aborted.
4>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 2.
========== Build: 0 succeeded, 4 failed, 12 up-to-date, 0 skipped ==========
```

So I got 12 to succeed; 4 of the modules fail to build.
I know that the RSP plugin and Project64.exe failed to build, PJGlide64 too I guess.

Here's the interesting thing:  It compiles just fine at my desktop computer at home, on MSVC 2013.  It's only **here**, on my laptop, that it fails to compile and find `afxres.h`.  I wonder if it's something particular to my installation of Community Edition of VS2013.

I'll try to solve this issue myself when I get home to figure out why it works on my home desktop copy, unless somebody else has some hints to interject for me which might help.

**Comment by cxd4** [comment]
Update:  I asked RPGMaster to try right-clicking the #include on his local copy of VS2013 and to pick "Open Document".

According to him the file was opened from:
`<AIO> C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include`

So it is not a part of project64 source base, but something my exact installation on this particular computer is missing.

**Comment by cxd4** [comment]
yep ... file is definitely missing from my computer.

closest I have to that file path is:
`C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include`

Shouldn't my installation of VS2013 Community Edition be the same as everyone else's though?  I don't get it.

welp time to head home and compile there

**Comment by cxd4** [comment]
Found a cause and a solution.

I guess it's caused from using free versions of Visual Studio.  I'm not sure if it's only Express-tied or if it applies to other free things like VS Community 2013, but I'm going to take a stab in the dark and guess that most people here don't use Community if they don't currently need to.

Here is the solution:
a) Install non-free VS2013
b) http://discuss.cocos2d-x.org/t/3-0rc1-cannot-open-include-file-afxres-h-in-vs2013-express/12652

According to this, we can just edit the three `.rc` files to replace `#include "afxres.h"` with `#include "WinResrc.h"` and one define.  I've tested it myself and it compiles just fine...so I think I will just send a pull request for this change if nobody else beats me to it.

Otherwise if this approach is objected to for any reason then tell me now and I can just close this pull request as an error on my free installation's side.

**Comment by oddMLan** [comment]
I have the non-free version of VS2013 (Professional) and still got the missing "afxres.h" error.

I think is cause old versions of Visual Studio (prior to 2010) used afxres.h and newer versions use "windows.h" and "WinResrc.h" instead.

**Comment by cxd4** [comment]
So compare `#if (_MSC_VER < 0x ...` something for MSVC 2010...if I can find any evidence online of what you said that older versions need afxres.h and newer versions need windows.h and/or WinResrc.h then I can make it detect the version of MSVC being used to compile pj64 to minimize the chance of an unresolved include.

**Comment by oddMLan** [comment]
Found the problem.

It is not that older versions use afres.h and newer don't; is just that when you install VS20XX you have to keep **_Microsoft Foundation Classes for C++_** checked in the optional features section.

![msstudio](https://cloud.githubusercontent.com/assets/7278372/6182240/820e52ae-b2fd-11e4-8ee5-dc5335ac0850.png)

If you already installed VS you just have to execute the installer again and it will let you modify the install options (or if you deleted the installer, download it again then run it).

I installed the required libraries and now I can find the file _afxres.h_ at  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afxres.h

**Comment by oddMLan** [comment]
You don't need to uninstall and reinstall, just execute the installer again and it will let you update your installation to add just the required libraries. The process itself takes a couple of minutes (definitely not as much as installing it from scratch).

And Microsoft Visual Studio 2013 Community does come with MFC libraries. Well I haven't installed it myself, but according to this screenshot. http://i.imgur.com/1Rbrj8H.png

But yeah I agree that it would be better avoid using these additional libraries and use windows.h instead.

**Comment by cxd4** [comment]
I'll take your word for it.

I'll still send a pull request to make this step an optional non-necessity though.
