### ISSUE TITLE
[RSP] Pokemon Stadium (J) unknown memory action

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#711]
CN64System::RunRSP unknown memory action. Happens after the intro before the title screen appears. Correct with cxd4 RSP

**Comment by LegendOfDragoon** [comment]
Does it happen with project 64's rsp interpreter?

**Comment by purplemarshmallow** [comment]
I tested it again. I compiled the RSP plugin again to have the latest version. No more error. Someone already fixed this bug. Nice work
