### ISSUE TITLE
(x64 Debug) Exception caught - all games

### ISSUE THREAD

**Issue by tony971** [project64/project64#717]
Running x64 debug versions of pj64 and all plugins. Loading a game results in the following error:

```
Exception caught
File: N64 System\N64 Class.cpp
Line: 390
```

**Comment by vgturtle127** [comment]
Do you have any 32-bit plugins in your 64-bit Project64 directory?

**Comment by tony971** [comment]
32 bit plugins wouldn't be listed as options to use for the 64 bit builds. I couldn't even if I wanted to.

**Comment by tony971** [comment]
Wait. You saw this issue and thought I might be using the stable version for the other one? At some point you have to assume that the computer is plugged in, man.

**Comment by vgturtle127** [comment]
Well, you stated in this one that you were using a debug x64 build. You may have been using different versions for all I know. I'm not sitting at your computer, you may have reasons to run different versions. I have 32 and 64-bit latest versions and many plugins. I keep various stable PJ64 releases and development releases of plugins in various directories to test different setups and what not.

I wasn't trying to offend your intelligence or anything, I am asking so I can best understand the problem.

**Comment by oddMLan** [comment]
I cannot reproduce this with the current x64 version.
