### ISSUE TITLE
Character corruption in Rom Browser

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#731]
File name in Japanese are not correct
![pj64](https://cloud.githubusercontent.com/assets/11252775/11020347/5709d98e-8660-11e5-9f2e-94251335e1f2.jpg)

![pj64_2](https://cloud.githubusercontent.com/assets/11252775/11020373/5b85d1ec-8661-11e5-8fc3-bbdb1c3e21a6.jpg)

**Comment by Frank-74** [comment]
ROM name (Internal Name) is not using UTF.
![romnameerror](https://cloud.githubusercontent.com/assets/11056843/11316925/363dbbba-9012-11e5-855b-3049255c273e.PNG)
![saveerror3](https://cloud.githubusercontent.com/assets/11056843/11316930/6771aeb2-9012-11e5-9336-0a185d50dccf.PNG)

**Comment by Nekokabu** [comment]
I think ToUTF16 () is wrong.

**Comment by Nekokabu** [comment]
change CP_UTF8 -> CP_THREAD_ACP in MultiByteToWideChar in ToUTF16.
ROM Browser is so good, but GUI is BAD.
![pj64_3](https://cloud.githubusercontent.com/assets/11252775/11443418/652b5452-9560-11e5-9088-e3ec3f9886b2.jpg)

**Comment by MELERIX** [comment]
is this related ? https://github.com/project64/project64/issues/427

**Comment by Frank-74** [comment]
@MELERIX Yes, probably.

**Comment by Nekokabu** [comment]
if change Windows regional settings,  Japanese filenames are recognised.

**Comment by oddMLan** [comment]
I think this still needs to be addressed. Roms with Japanese filenames are not recognized by the Rom Browser if Windows regional settings are not set to Japanese. And if the Rom internal name is using japanese characters, it shows up as a garbled mess.
