### ISSUE TITLE
error in f-zero x japan and europe

### ISSUE THREAD

**Issue by alpharulesirulee** [project64/project64#732]
Fatal error stopping emulation after car selection!! help!! mupen64++ only works on japan version!!
And europe gives me an error after clicking time trial 

Project64k 0.13

**Comment by project64** [comment]
is this the case with the current source, or just with some other version?

**Comment by alpharulesirulee** [comment]
just project64k


Rom name: F-Zero X Japan from emuparadise with new title screen unlocked by master

**Comment by project64** [comment]
we have no way to support projec64k here, this is just about tracking bugs in the current source in github

**Comment by alpharulesirulee** [comment]
thank you

**Comment by alpharulesirulee** [comment]
project64 1.6 2.x are the only version that worked
