### ISSUE TITLE
"Binary files a/Project64.sln and b/Project64.sln differ"

### ISSUE THREAD

**Issue by cxd4** [project64/project64#735]
Can't speak for everyone else, but typically what happens when I pull from upstream master, it complains that the new commits I am downloading would conflict with changes to files like `Project64.sln`.

Well the problem with that, is that Git won't show me my "changes" to Project64.sln so that I can undo them and continue the pull and move on with the next pull request.

Why, you ask?  Because it thinks Project64.sln is a binary, non-text file for some reason.

**Comment by project64** [comment]
when I look at the file it is encoded as UTF-16 (LE)
maybe if it was changed to utf-8 it still might work and git will treat it as a text file

**Comment by cxd4** [comment]
I tried deleting the BOM to make it ANSI, no UTF at all but I guess `git diff` continues to see it as a binary file until I make at least one commit.  I guess I could try sending a pull request to make it utf-8.

Does it really have to be a UTF-encoded file?  The .sln seems to just be ASCII text to me.

**Comment by project64** [comment]
no idea, i just useally leave it the way VS created it. I guess I just prefer utf8 over ansi, takes the same amount of space 99% of the time just is clear the file format.

**Comment by cxd4** [comment]
For my projects, I convert all my .sln and .rc resource VS files to ANSI.  I see Azimer did this also.

I had to make them ANSI because with Unicode/UTF-16 .rc files, MinGW parser stalls into a permanent loop from which it never escapes to be able to finish compiling the resource script because it expects ANSI text.  Although I have never tested utf-8 before...

But for the purpose of experiment I'll begin by first attempting a commit that makes them UTF-8.  If there are no issues with Git then I'll leave it at that without making it ANSI.
