### ISSUE TITLE
Killer Insticnt health bars not working in PJ64 (work in Mupen64)

### ISSUE THREAD

**Issue by theboy181** [project64/project64#75]
![capture](https://cloud.githubusercontent.com/assets/9299743/6174795/13cb02c6-b2a6-11e4-90f2-56dce32d9e84.PNG)

**Comment by LegendOfDragoon** [comment]
I don't seem to have this problem.

**Comment by cxd4** [comment]
What's he referring to?  Something about how the green bars are checkered or the like?

I never played this game growing up so don't really know what anything was meant to look like.

**Comment by LegendOfDragoon** [comment]
Ya, he's referring to the green bars I think. They aren't checkered on my end, regardless of gfx plugin (tried all 3 LLE ones).

**Comment by cxd4** [comment]
theboy181:  If you disable "32 Bit Engine" in the RDB, the green bars should work correctly?
Does that solve your issue?

**Comment by theboy181** [comment]
Yes this fixed the issue thank you. However the RDB has this set to 32 by default. Maybe we could have that changed? I have adopted the RDB from PJ64 forum and I am unsure if it has been modified and now inaccurate though. is this on by default on your RDB?

**Comment by project64** [comment]
Do a pull request for the rdb to turn off 32bit

**Comment by cxd4** [comment]
He's probably on the same level as retroben in measure of confidence to being able to use the GitHub web interface to edit the RDB file online and send a pull request, so I went ahead to do it for him.
I need the extra practice with branches anyway.

**Comment by theboy181** [comment]
Hate to reopen this issue, but using recompiler and turning off 32-bit doesn't seem to fix the issue anymore. However, using Interpreter does.

Can you have another look and see what might be causing this?

**Comment by AmbientMalice** [comment]
@theboy181 did some testing. This problem has existed since at least 1.6, so it's not a recent regression, if a regression at all.

Disabling Register Caching fixes it in all versions, with a slight performance hit. (Very minor compared to Interpreter.)

On that note, Register Caching caused a lot of problems with 1.6 according to this list http://www.pj64-emu.com/known-issues/issues-with-cpu-core/register-caching-doesnt-work-for-some-games/ Yet it is almost universally enabled for 2.2 - testing might be needed there.

**Comment by AmbientMalice** [comment]
@project64 should I make a pull to disable register caching for Killer Instinct or should this be left until a "proper" solution is found?

**Comment by theboy181** [comment]
Kinda a workaround. I'm sure it will get sorted soon.

**Comment by LegendOfDragoon** [comment]
>@project64 should I make a pull to disable register caching for Killer Instinct or should this be left until a "proper" solution is found?

I think it's better to be left until register caching is fixed.

**Comment by theboy181** [comment]
was register caching fixed? teh bars R!
