### ISSUE TITLE
Opening controller settings crashes emulator

### ISSUE THREAD

**Issue by tony971** [project64/project64#750]
And after you restart from crashing, opening any plugin settings will crash the emulator.

**Comment by tony971** [comment]
Combine this bug with #668 and Project64 becomes unusable.

**Comment by Frank-74** [comment]
Opening Configure Controller immediately crashes/closes Project64 2.2.0.841 here.  No error, just disappears.

**Comment by Frank-74** [comment]
Doesn't crash after opening a rom.  Only crashes before any rom has been started.

**Comment by vgturtle127** [comment]
I know this sounds stupid, but have you guys tried a fresh download of Project64? And what version are you guys using, the latest stable or the latest from source?

**Comment by tony971** [comment]
Freshly built with new configs. Stable is not stable. Anyone who uses stable would report to the forums (most likely).

**Comment by Frank-74** [comment]
I tested latest from Github and latest from the alpha section of the forum.  Zilmar's buildbot.
http://forum.pj64-emu.com/forumdisplay.php?f=10

Just open/close a rom first before touching the controller settings.  No crashing then.  That's the only way around it at the moment.

**Comment by vgturtle127** [comment]
@tony971 It might seem like a stupid question, but I have to ask it. Also, this is Project64. It is a little more complicated than "is your modem turned on". :laughing: 

Anyway, does this happen with 32 and 64-bit versions?

**Comment by Frank-74** [comment]
The only error written into the .log is this.
> 2015/11/15 03:28:14.230 03564: Error  : WinMain: Exception caught (File: ".\main.cpp" Line: 60)

https://github.com/project64/project64/blob/master/Source/Project64/main.cpp#L60

**Comment by vgturtle127** [comment]
Huh, that's weird. It isn't even going to a useful spot in the source. What was the last version that worked? I haven't had the issue, but then I haven't built a new version in a week or so...

**Comment by Frank-74** [comment]
There have been 100+ commits in the past 10 days or so, massive code cleanup is in progress.  I'm guessing to prepare for a new public release.  I've been holding back on trying to do anything while this is happening.  As current source is very much a work in progress.  Too many cooks spoil the broth and all that...

**Comment by vgturtle127** [comment]
Oh, maybe that is causing some issues. Hopefully they are temporary, especially if we are going to be releasing a new public stable release. I'm excited though. :smile:

**Comment by cxd4** [comment]
History shows it can be revealing issues that have always existed.  A couple memory issues with plugins and 64-bit have always been in the code, but the EXE just lucked out and didn't crash in terms of pure chance.  Now that things are being restructured for a command-line version of the PJ64 core, the memory allocation is drastically different which reveals many hidden mistakes in the code that have always been there, like crashes.

**Comment by project64** [comment]
ok https://github.com/project64/project64/commit/9e10486e2c103dd776d841c4bf577599d478fa81 I think fixes thos

**Comment by Frank-74** [comment]
Yes, it is fixed now.
