### ISSUE TITLE
When plugin changed and game is loaded, load the new plugin

### ISSUE THREAD

**Issue by project64** [project64/project64#757]
When a game is loaded, but not running (ie end emulation), and the game settings change where the plugin should change. Make sure that the plugin does change then and there and you can configure the correct plugins.

If the setting of not auto starting is set this is a good way to test.

**Comment by Frank-74** [comment]
Note:
Changing plugins via Options/Settings/Config:Game works ok.  Plugins change.

Right-clicking game in rom browser and selecting Edit Game Settings doesn't change plugins on re-loading game after end emulation.

I did make an issue before for this.
https://github.com/project64/project64/issues/196

**Comment by project64** [comment]
I have some other things to do for the next few weeks, so probably will not be changing the source like I did lately, but when I get back to working on the source I will test this and and step through to work out what is going on here.

**Comment by oddMLan** [comment]
>Note:
After end emulation, changing plugins via Options/Settings/Config:Game works ok. Plugins change.
Right-clicking game in rom browser and selecting Edit Game Settings doesn't change plugins on re-loading game after end emulation.

Reproduced and confirmed.

**Comment by Frank-74** [comment]
@project64 
This is fixed now.
