### ISSUE TITLE
Indiana Jones gfx issues in CPU core

### ISSUE THREAD

**Issue by cxd4** [project64/project64#76]
I was able to reproduce the findings of Ambient_Malice at this thread spot:
http://forum.pj64-emu.com/showthread.php?p=59953#post59953

I wasn't able to change RDB settings so far in a way that would fix it, and it apparently hasn't had the issues on 1964 0.8.5 interpreter or Mupen64Plus.  So I will have to try testing older versions of this repository to see as of which commit may have broken this (unless the issue goes back further than GitHub itself >.< hopefully not).

**Comment by exhalatio** [comment]
Does mtc0 opcode revert to 1964 0.8.5, the GFX seem to be fixed anyway?

**Comment by cxd4** [comment]
You suppose it may be an interpreter bug with MTC0 on the main CPU then?
Or I am simply not following.

**Comment by LegendOfDragoon** [comment]
Could be. 1964 0.85's code looks a lot different for that instruction. I'm very intrigued.

**Comment by exhalatio** [comment]
Yes I suppose a bug is in the MTC0 on main CPU.
I don't understand technical thing , but it seems there is a bug in The status register.

**Comment by project64** [comment]
why do you think it might be in MTC0?

**Comment by LegendOfDragoon** [comment]
@exhalatio probably studied emulator core code well. @project64 , you should take a look at 1964 0.85's source. You'll see that it implements that instruction quite differently.

**Comment by project64** [comment]
in what way did they handle it differently?

**Comment by AmbientMalice** [comment]
Filed a MTC0 error report for Supercross 2000 in LLE mode that might be relevant.

https://github.com/project64/project64/issues/104

**Comment by exhalatio** [comment]
FixFpuLocations have two Routines, if forced as 1st routine work well.
This game does not seem to hit the (STATUS_REGISTER & STATUS_FR) of == 0 conditions.

**Comment by AmbientMalice** [comment]
What about Battle for Naboo? Since both games seem to share the same bugs.

**Comment by exhalatio** [comment]
Yeah, Battle for Naboo also seems to work well.
![naboo](https://cloud.githubusercontent.com/assets/7089513/6320800/7a625c2c-bb2b-11e4-8c3f-406d60d23700.jpg)

**Comment by AmbientMalice** [comment]
The radar and skybox are broken. (Yes, I'm pointing out the obvious, but they work on other emus.)

Good work, anyway.

**Comment by LegendOfDragoon** [comment]
Pretty sure he's using Jabo 1.7.0.57 though :P .

@exhalatio , is that picture with default source or did you modify source? I never really played this game, other than checking to see if it boots with my RSP version.

**Comment by AmbientMalice** [comment]
Ah. Jabo. Its existence had momentarily slipped my mind.

I'm curious whether the environments flicker, and whether the game is stable in dynarec. (Since m64p has flickering problems and issues with dynarec.)

How soon can/will these changes be added to the source?

**Comment by exhalatio** [comment]
@LegendOfDragoon.@AmbientMalice It's little modify (cheats) the source code. 
You will confirm in project64\Source\Project64\N64 System\Mips\Register Class.cpp

void CRegisters::FixFpuLocations ( void ) {	
//	if ((STATUS_REGISTER & STATUS_FR) == 0) {
		for (int count = 0; count < 32; count ++) {
			m_FPR_S[count] = &m_FPR[count >> 1].F[count & 1];
			m_FPR_D[count] = &m_FPR[count >> 1].D;
		}
//	} else {
//		for (int count = 0; count < 32; count ++) {
//			m_FPR_S[count] = &m_FPR[count].F[1];
//			m_FPR_D[count] = &m_FPR[count].D;
//		}
//	}
}

**Comment by LegendOfDragoon** [comment]
Nice. Thanks a lot! @exhalatio  How did you figure this out?

**Comment by exhalatio** [comment]
Calling the FixFpuLocations from Status of mtc0.
The FixFpuLocations, There are two different methods.
I was forcibly how to handle in anticipation that there is a bug in one.
Surprisingly it has been fixed GFX.

**Comment by LegendOfDragoon** [comment]
Nice! That was very creative.

**Comment by cxd4** [comment]
So does this mean `(STATUS_REGISTER & STATUS_FR)` bit wasn't set when it was supposed to be?
Or it just means the } else { part (handling when `STATUS_FR` not set) just has a bug.

Because it appears most likely the former.  `STATUS_FR` should have been set in this game but missed?

**Comment by AmbientMalice** [comment]
To everyone involved with this fix and fixes to come. To you, personally.
![bless your heart](https://cloud.githubusercontent.com/assets/10704701/6362644/3bc3f122-bcdb-11e4-9330-5914b764af2f.jpg)

**Comment by AmbientMalice** [comment]
@exhalatio what's the plan when it comes to adding this fix to the source? In its current form, will it break anything? I've noticed some strange behavior in games where textures disappear when running in LLE mode using Ziggy's, but I haven't done enough testing using clean builds.

**Comment by project64** [comment]
when it comes to fixing this .. I want to write a test rom for the n64 and see if I can work out how it actually works on a real n64

**Comment by exhalatio** [comment]
I'll be send a Pull Request.
Thank you for waiting.

**Comment by cxd4** [comment]
That is a temporary fix, maybe for the short term.  Commenting out the broken code doesn't fix the broken code, just gets around it.  Not saying this because as if the pull request is bad at all, just emphasizing this to folks that's all.

The actual behavior at that stage of the operation is still unknown.  Maybe it's documented somewhere, but I'm really not a R4300 person, more a RSP person so don't know.

**Comment by project64** [comment]
until I know how the real n64 works I am not sure about the pull request, but keep it there is reminds me that it needs to get done and I am less likely to forget about it.

**Comment by exhalatio** [comment]
Yeah, that is a temporary fix too inaccurate, but seemed to be waiting for the fixed...

In mupen64 plus, it seems to switch the 32bit-64bit mode into Fpu before modifying the Fpu Locations. Maybe need it.

**Comment by Frank-74** [comment]
This fix seems to break Shadow Man (U).  It doesn't boot with this fix.

**Comment by AmbientMalice** [comment]
Shadow Man doesn't boot for me, either.

**Comment by AmbientMalice** [comment]
Interestingly, it also seems to have broken the Turok games, (different dev despite being published by Acclaim) and also Hydro Thunder in HLE, but not LLE.

**Comment by LegendOfDragoon** [comment]
@project64 The key difference between Project64 and 1964 is the way each emulator handles mtc0 when the FR bit changes.

In here https://github.com/project64/project64/blob/aea724b81a6148fbe9a30ab8bea80a49efdc9155/Source/Project64-core/N64System/Mips/RegisterClass.cpp#L376 it writes to m_FPR[count].F[1] where as 1964 would write to m_FPR[count].F[0]. Aside from that, the shuffling is different. In 1964, when it switches between the modes, the upper half of the 64bit register is preserved, so when it switches to 32bit mode from 64, then switches back to 64 the upper half will be restored to what it was before it switched to 32 bit mode. When switching from 32bit mode to 64bit, it moves the upper half of the 16 64-bit FPR registers into the lower half of the odd number 64-bit FPR registers. 

Doing these changes may "fix"  Star Wars Battle for Naboo, but I'm not 100% this is how it should be done. I'd personally go with how 1964 did it for now, since that is what makes the most sense to me, after reading the VR4300 manual. One problem I've encountered in 1964 and Mupen, is that Rogue Squadron appears to be buggier. I noticed both have this issue where the lighting in some parts of the game look buggy. It could be an unrelated issue, such as timing, but who knows.

One other thing I like about 1964's floating point code, is the fact that it doesn't use pointers for the floating point registers in 1964 1.1. It just assumes that the FR bit will never change for that specific portion of code. It may be questionable to do for games that switch modes a lot, but I think most games do not. It would be a nice option to implement for the recompiler, if floating point instructions significantly impact the performance. I'd even consider doing it, just to see if it gives a noticeable speed improvement.

**Comment by project64** [comment]
I been wanting to write to write some tests on a real n64 to see what happens, but it just not has happened yet and I been focused on trying to get an android version of project64.

**Comment by cxd4** [comment]
That, and whatever recompiler trick is deserved here for this FP thing, would be deserved even more for the ARM recompiler on Android which actually would have a higher chance of needing a recompiler.  And the two recompilers would have to be separate code bases.  And working on x86 won't help that.

**Comment by oddMLan** [comment]
Is this still a milestone for Project64 2.2... which, already was released? :P

**Comment by Frank-74** [comment]
Should the condition be if ((STATUS_REGISTER | STATUS_FR) == 0)?
Is the test supposed to be checking if both STATUS_REGISTER and STATUS_FR are zero?

Because if ((STATUS_REGISTER & STATUS_FR) == 0), will be true if either or both are zero.

**Comment by theboy181** [comment]
I cant seem to get Indy to boot - what settings and plugins are needed?

**Comment by Frank-74** [comment]
@theboy181 
Default settings with latest master.  I used z64gl and the (E) region carrot unreleased version of Indy.

**Comment by AmbientMalice** [comment]
@theboy181 The US version can be a little fickle about booting. PAL version tends to boot more consistently. You need either z64gl or GLideN64.

**Comment by theboy181** [comment]
AL RDP is a no go?

**Comment by AmbientMalice** [comment]
Angrylion's will work fine, but expect it to be slow. Especially in high resolution mode.

**Comment by project64** [comment]
AL is good for testing, but nice to see the core more fixed

**Comment by theboy181** [comment]
Got it booting now, and tested against several RSPs and RDPs. Seems to have different crashes if you let the demo roll.  unsure if its RSP or emulator related..
