### ISSUE TITLE
Save (F5) and Load (F7) broken plus weird restart of ROM.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#767]
Any game, save and load is broken.

For example on saving in GoldenEye, the name at the bottom is corrupted.
![saveerror](https://cloud.githubusercontent.com/assets/11056843/11233643/ed5d99b2-8db7-11e5-9ec2-1d83b14940b9.PNG)
And trying to load, results in Unknown memory action, Emulation stopped.

Clicking ok on the error box and it goes back to the rom browser, frozen.  Wait a minute and it will unfreeze then the game will restart in the background!  Rom browser visible only, but Goldeneye audio is running, just no display.  Clicking End emulation stops it.

It has saved GoldenEye 007 (U).pj.zip in the Save folder.

**Comment by Frank-74** [comment]
Saving in a (J) game, example Doraemon 3 - Nobita no Machi SOS!.
![saveerrorj](https://cloud.githubusercontent.com/assets/11056843/11233945/12a019a4-8dbb-11e5-9229-784d6ae833f6.PNG)
But no restart on load.  Just Unknown memory action.

**Comment by Frank-74** [comment]
Maybe because of this?
https://github.com/project64/project64/pull/755

**Comment by Frank-74** [comment]
Restarting ROM after Unknown memory action, runs rom without the render window.

Just tested with lates 2.2.0.941.

**Comment by Frank-74** [comment]
![saveerror3](https://cloud.githubusercontent.com/assets/11056843/11257716/72253e96-8e4b-11e5-9d22-f1a0db98bb48.PNG)

**Comment by cxd4** [comment]
I need to finish replacing Windows 7 on my laptop with Windows XP 64-bit so that I can sort through all the legacy Git versions until I find a version of Git that will work for you.  Makes tracking breaking commits way, way easier and more effortless than downloading repo branches through GitHub.

**Comment by Frank-74** [comment]
I'm on Windows 8.1 32-bit (X86).

**Comment by cxd4** [comment]
Solution:  `git checkout #######`, where ####### is GitHub's 7-digit commit number.

I don't know if there's a graphical interface for it; I just type it in the terminal interface to Git.

It's like time travel.  You just have to hit F7 or Ctrl+Shift+B or w/e in Visual Studio to re-compile the snapshot of the earlier history of the repository.  In fact it's even easier (not to mention more precise) than repeatedly downloading pre-compiled binaries from the Alpha Forum build bot because you don't have to mess with extracting the EXE/plugins to the correct folder or cut and paste compiled binaries.

Yeah GitHub won't show diffs for large changes, but Git itself has no limit for that when running `git diff` on disk (or using `git --amend` through the GUI to Git to show the diffs).

**Comment by Frank-74** [comment]
Buildbot version 624 broke Load State: https://github.com/project64/project64/commit/0144305c6a50e88158c09c76a56126ae8f5f3449
Buildbot version 623 Load State works but status bar text is (null).

**Comment by cxd4** [comment]
lol...if that's the commit that caused this issue then I think all of us are out of luck.

Like 85% of that commit is neutral (spacing, replacing DWORD with uint32_t, etc.) stuff that can't possibly have caused the issue.  But there is still so much mixing of questionable C++ clean-ups that there's really no way to judge the whole remaining 15% either.

**Comment by Frank-74** [comment]
Its probably a stdstr replaced wth std::string that's responsible.

**Comment by cxd4** [comment]
No break-point exceptions either it seems, except with 64-bit Project64.

With 32-bit Project64 there is no exception because it silently calls MemoryFilter but fails anyway.
With 64-bit it cannot even attempt MemoryFilter so the breakpoint throws at this line:
https://github.com/project64/project64/blob/master/Source/Project64/N64%20System/Mips/Memory%20Virtual%20Mem.cpp#L2379

Too bad I prefer not having STD's so am in no position to follow `std::anything` in this code.

**Comment by Frank-74** [comment]
@Nekokabu has fixed these issues before, so I hope he has time to look at this.

**Comment by Frank-74** [comment]
And the commit that broke the status bar Save text is here: https://github.com/project64/project64/commit/81fdcb93737983c0a198186eda953fbe3bb5dd8f
Warning, so many changes it may crash your Firefox.

**Comment by Frank-74** [comment]
Tried building the parent commit at this tree: https://github.com/project64/project64/tree/a2a8eccbcab029bb3492ba8921fe19bfcc687b7c
But there are build errors in the vs2008 solution.

**Comment by cxd4** [comment]
I don't have VS2008 anymore so can't test.  (It was 2008 Professional, so the trial expired.)

I guess that means zilmar probably has moved on to building primarily with VS2013 Community.

**Comment by cxd4** [comment]
It's better to have some people testing the build with older compilers, though.

Newer versions of MSVC generally just add in new toleration for syntax valid in newer standards.  In principle your code is more portable when it's verified working under older compilers with less toleration.

**Comment by Frank-74** [comment]
Latest vs2008 solution works fine, its just some trees that are in between buildbot releases fail.

I noticed in latest that some files have been moved but not updated in the solution though, e.g. Settings.h, clicking on that in VS2008 and it cannot be found.

**Comment by Frank-74** [comment]
Maybe this would help?
' 2
down vote
	

A 'trick' to using TCHAR in Windows along with the STL strings that I prefer to use is to define my own tstring type:

typedef std::basic_string<TCHAR> tstring;

Then, I use tstring instead of std::string everywhere. This way, if you compile using "Multi-Byte character set" for character set it is equal to std::string and when you compile using "Unicode character set" it is equal to std::wstring.

The great thing is that this avoids the need to copy it to a TCHAR array, and you can directly use its c_str() property with _tprintf and all other functionality in the TCHAR.h header.'

**Comment by Frank-74** [comment]
I've fixed the Save State/Load State status bar text.

Just the Load State Unknown memory action to fix now.  Its probably a similar problem of not using wide strings.  Ctrl+L to load a state works without an Unknown memory action.

**Comment by Frank-74** [comment]
Fixed Save State (F7).  https://github.com/project64/project64/pull/771
