### ISSUE TITLE
Project 64 doesn't pause with GLideN64 configure graphics

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#772]
Opening Configure Graphics Plugin with GLideN64 doesn't pause emulation.

Shouldn't Project64 force CPU Pause when selecting configure options?

Or is GLideN64 not doing something it should?

**Comment by cxd4** [comment]
Not sure.  I always disable Project64's "Pause emulation when window inactive?" option and have yet to try testing the GlideN64 plugin.  I usually hate it and get distracted when Project64 pauses automatically if I switch windows.

**Comment by tony971** [comment]
For me, it takes a second to pause and then never un-pauses once the window is closed.

**Comment by AmbientMalice** [comment]
GLideN64 has a number of problems with PJ64. For example, if you press F12 while fullscreen, the resolution doesn't get reset to desktop.

**Comment by LegendOfDragoon** [comment]
I don't think pausing after opening config is normal behavior to begin with, unless "Pause emulation when window inactive?" is enabled. So this issue can probably be closed :smile: .

**Comment by AmbientMalice** [comment]
>I don't think pausing after opening config is normal behavior to begin with, unless "Pause emulation when window inactive?" is enabled.

That happens to be the default behavior. GLideN64 is behaving incorrectly. For example, if you make PJ64 "always on top", it breaks GLideN64's configuration window because the window gets stuck behind PJ64's.
