### ISSUE TITLE
End Emulation > Start any game causes crash

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#776]
I've just downloaded the new Alpha v2.2-971 and tested.

I extracted and ran Project64, selected ROM directory, turned off hide advanced settings, started GoldenEye.  On first run its ok.

Then End Emulation, restart GoldenEye, Project64 crashes during Rare logo.  Sometimes no crash error, just closes.

Does the same in my previous builds, but I never noticed it before.

Also, not sure if its related, but another problem is restarting a game after an error/end emulation.  It restarts without the render window.  Going full screen works, but exiting full screen shows the ROM browser again.

**Comment by Frank-74** [comment]
Debug log after ROM has been restarted.
```
2015/11/22 22:36:44.735 06640: Debug  : CPlugin::RomOpened(Control): After Rom Open
2015/11/22 22:36:45.364 06640: Error  : CRecompiler::ClearRecompCode_Virt: Delete Table (16AC618): Index = 524288
2015/11/22 22:37:02.665 06672: Debug  : CMainGui::~CMainGui: Start
2015/11/22 22:37:02.668 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - start
2015/11/22 22:37:02.671 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 1
2015/11/22 22:37:02.672 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 3
2015/11/22 22:37:02.674 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 4
2015/11/22 22:37:02.676 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - Done
2015/11/22 22:37:02.678 06672: Debug  : CMainGui::~CMainGui: Done
2015/11/22 22:37:02.682 06672: Debug  : CMainGui::~CMainGui: Start
2015/11/22 22:37:02.696 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - start
2015/11/22 22:37:02.698 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 1
2015/11/22 22:37:02.700 06672: Debug  : CRomBrowser::SaveRomListColoumnInfo: Start
2015/11/22 22:37:02.703 06672: Debug  : CRomBrowser::SaveRomListColoumnInfo: Done
2015/11/22 22:37:02.705 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 2
2015/11/22 22:37:02.707 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 3
2015/11/22 22:37:02.709 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - 4
2015/11/22 22:37:02.711 06672: Debug  : CMainGui::MainGui_Proc: WM_DESTROY - Done
2015/11/22 22:37:02.719 06672: Debug  : CMainGui::~CMainGui: Done
2015/11/22 22:37:02.722 06672: Error  : WinMain: Exception caught (File: ".\main.cpp" Line: 60)
```

**Comment by Frank-74** [comment]
Reading through source, found a spelling error in Gui Class.cpp.
https://github.com/project64/project64/blob/master/Source/Project64/User%20Interface/Gui%20Class.cpp#L941

**Comment by cxd4** [comment]
lol...I hate it when he does that.

**Comment by Frank-74** [comment]
This is a really annoying bug to find.

Any game crashes at 17-18 seconds after restarting the game.  Why on earth would it wait 18 seconds to just crash with no apparent reason.

Even with frame limiter off, its still 18 seconds real time, and crash or close.

**Comment by cxd4** [comment]
Well when I get the Git repository installed on my Internet-free laptop I will try to check.

In the meantime if it's any less distraction I've fixed that pasta typo -- https://github.com/project64/project64/pull/777/files .

>Any game crashes at 17-18 seconds after restarting the game. Why on earth would it wait 18 seconds to just crash with no apparent reason.

Now that sounds like a state machine property in the VM that is not being reset (maybe like global variables if I remember zilmar's walkthrough of getting me to use VS debugger to isolate global variables).

Does it matter if you switch to Interpreter?

**Comment by Frank-74** [comment]
Interpreter doesn't make a difference.

Just built the debug, and it runs with Sync Cores.  Memory leaks galore!  Over 2400 lines in Project64_d.leak.csv.  I rename debug build to Project64_d.exe.

**Comment by Frank-74** [comment]
No memory leaks when opening Project64, start game, end emulation, close Project64.

Only happens on restarting the same game.  (Any game you choose).

**Comment by cxd4** [comment]
Ah, that's a handy dandy find.

Some of those when I look up in the source are the C++ allocations from `new` so are probably never being de-allocated by Project64 upon certain conditions met by re-starting the exact same game as you do.

In that case with 2 GB RAM filled up, it should return a NULL or fail to allocate memory, but there is no checking guard in place so it attempts to allocate memory from a pointer that isn't allocated?  Which is definitely one reason why you would keep getting crashes.  I could probably reproduce it too on my 3 GB machine as browsers tend to eat it all up.

**Comment by Frank-74** [comment]
Important!

Just discovered this also happens starting a different game.

I tried opening Body Harvest, but accidentally clicked Castlevania.  End emulation, start Body Harvest, 18 seconds later, Project64 closes.

**Comment by Frank-74** [comment]
I've tracked the build responsible for this issue.

v2.2-897 http://forum.pj64-emu.com/showthread.php?t=5355

```
    [Project64] more fix up of Reg Info.cpp (commit: 2f3998d9a6c93c04a6caa9d0702dde4566afdb06)
    [Project64] fix up spaces in CN64System::StartEmulationThread (commit: 8aa5b6ef470f26203b384fcbd37824cfd5174c1c)
    [Project64] Add ability to monitor Game Cpu Running to Gui (commit: 7d7026c33d8726be747d0410f04661a3063bc28e)
    [Project64] Get N64 Class.cpp to use standard types (commit: 3024d7c524fccb06a5cef15fbc54476f4dcc60da)
```

**Comment by cxd4** [comment]
It's one of those bottom two commits you linked to then.

If I have enough time today I can get Internet on my laptop but have it booted up into Windows instead to test building through the changes within those two commits to see when your issue happens.

**Comment by Frank-74** [comment]
I'm pretty certain its the third one. https://github.com/project64/project64/commit/7d7026c33d8726be747d0410f04661a3063bc28e

**Comment by cxd4** [comment]
Alright, now I'm just going to run checkouts from this snapshot to make sure of that:
https://github.com/project64/project64/commits/3024d7c524fccb06a5cef15fbc54476f4dcc60da

**Comment by cxd4** [comment]
Actually, it appears to be the fourth of those from which I can reproduce this issue, not the third.

Now for what change...well I did post a few comments criticizing that commit so maybe I have a clue.
