### ISSUE TITLE
Glide64/Debug Settings UI crashes

### ISSUE THREAD

**Issue by JunielKatarn** [project64/project64#781]
This happens at least since commit f994f38e754d899bc86e36f3a910948321577159.

Steps to reproduce:
1. Build the Debug/Win32 profile.
2. Start Project 64
3. Set the GFX plugin to "Glide64 (Debug)"
4. Open Options/Configure Graphics Plugin...

The application will crash.
Note: this does not happen if Glide64/Release is used.

**Comment by Frank-74** [comment]
I get this message when running debug build with Glide64(debug).  This is with the updated wx_3.0 build.

![glide64debug](https://cloud.githubusercontent.com/assets/11056843/11403985/9ac2a19e-9397-11e5-910c-98bc126f58d2.PNG)

**Comment by JunielKatarn** [comment]
I only found a commit where the issue exists. I didn't mean that is the one that introduces it.

Because such commit is older than my wx3 branch, I can tell it is also not responsible.

The issue is happening in both wx 2.8 AND 3.0

**Comment by oddMLan** [comment]
Is this still an issue with the recent removal of wxWidgets from the project? 68a8ed03696f3365430d8cca14d5084100165cd0

**Comment by JunielKatarn** [comment]
@LegendOfDragoon Yep, resolved.
