### ISSUE TITLE
Window never focuses when launching process.

### ISSUE THREAD

**Issue by cxd4** [project64/project64#787]
Am I the only one who finds that double-clicking to start the EXE doesn't show Project64?  (I typically test only 64-bit builds...I figure everyone else is having 32-bit ones shoved down their throats, so we have a balance there.)

It still shows up in my taskbar, so all I have to do is click that every time I double-click the EXE to show the ROM browser.  But it's still rather annoying because out of habit I'm used to the UI popping up immediately after launching the EXE, and if it doesn't, I wait for a minute or two assuming Microsoft Security Essentials is blocking it or something, only to finally realize it's just sitting there in my taskbar.

**Comment by Murdock304** [comment]
Running win10, v2.2 32-bit the pj64 window does appear with focus or 'on top', though the latest 32-bit build (2.2.09999) from git does appear behind the explorer window (no focus).

**Comment by cxd4** [comment]
I'm unsure of 2.2.9999's meaning but can probably test 32-bit build instead when I have time to.

Plain v2.2 official release I am sure is old enough by far to not have this subtle regression.

**Comment by Frank-74** [comment]
It opens on top here.  Windows 8.1.  Current git 32-bit build.

**Comment by Murdock304** [comment]
2.2.0.9999 is the version that shows up from the git repo.

![image](https://cloud.githubusercontent.com/assets/16063481/11474127/bf032fa4-973b-11e5-9967-824a9c44a059.png)

**Comment by oddMLan** [comment]
Cannot reproduce.
