### ISSUE TITLE
RSP Recompiler Instruction Re-ordering causes graphical issues in a few games

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#8]
Enabling Instruction Re-ordering in RSP recompiler caused graphical issues in Yoshi's Story, SD Hiryuu, and Quake II. Simply disabling the option fixes the problem.

I haven't really debugged to figure out what causes these bugs, since I honestly don't see a point in reordering instructions, when the recompiler doesn't use register caching.

Is there a real benefit to instruction reordering, while there's no register caching? If so, then I will try seeing if I can fix it. Otherwise, I'll just continue to keep it disabled.

**Comment by cxd4** [comment]
There is a benefit to the ordering of the instructions.

On a CPU of Intel's nature, you can typically achieve higher performance beyond simply measuring the cycles or independent latency of each operation compiled--often times you can get a better throughput by ordering instructions of alternating units and types (like on the RSP, how you can execute 2 instructions in one cycle if scalar opcodes are interleaved with vector ones).

But Azimer and Jabo would know more about it.

**Comment by LegendOfDragoon** [comment]
Makes sense. I sorta forgot about the fact that Jabo implemented some HLE code, so there is a point to using it.

I just felt that without HLE code or register caching, it wasn't worth the effort, since it just makes the recompiler even more error prone. I didn't pay enough attention to Jabo's HLE code, so I'll have to go analyze that and figure out what went wrong.

**Comment by LegendOfDragoon** [comment]
Looks like zilmar fixed it +1: . Tested SD Hiryuu and is no longer bugged with instruction reordering enabled.

**Comment by project64** [comment]
Yoshi's Story as well ?

**Comment by LegendOfDragoon** [comment]
Oh my bad, I think the problem with Yoshi's Story was something else. Either way, the graphical issues I saw in the original RSP 1.7.0.9 are gone now, for Yoshi's Story.
