### ISSUE TITLE
The sound is not working properly

### ISSUE THREAD

**Issue by kirous** [project64/project64#81]
Rather, I want to tell you what they're bringing in GIT version, there are mistakes, like the case of sound that PLUGINS Jabo's Direct Sound does not work. I have run the game JAMES BOND 007, only the sound is worse. As the speed that certain games that lower FPS and are delayed. As for DONKEY KONG both the graphics and speed.

Hopefully they can fix that problem

**Comment by LegendOfDragoon** [comment]
Please add more details. List all games you know of, where you encountered new issues.

**Comment by oddMLan** [comment]
No offense but I can't properly comprehend what you're trying to say.  Your profile says you're from Lima, Perú (if I'm not wrong)... so maybe it would be better if you post what you intended to say in Spanish so I can translate it, as I speak Spanish natively.

**Comment by LegendOfDragoon** [comment]
I can understand his english :) .

@kirous. Are you using the same game settings as before?

**Comment by oddMLan** [comment]
I think this is no longer an issue as per the merge of #881 and #882 

This ticket should be closed.
If @kirous has anything to say after it gets closed, it can be reopened.

@project64 
@cxd4, you can close bugs too, right?

**Comment by cxd4** [comment]
OP=tl;dr would close, but only "contributors" with write-access can do that.

I think project64 does the right thing by giving nobody right access; I prefer the pull request model.  Though this means nobody but him can close issues.

**Comment by LegendOfDragoon** [comment]
>I think project64 does the right thing by giving nobody write access; I prefer the pull request model.

I agree. I think it's better that way.

**Comment by LegendOfDragoon** [comment]
@project64 I think this issue can be closed.

**Comment by project64** [comment]
I can close them, also the person opening can to, but what @LegendOfDragoon does and just tags me and asks me to close works as well (as long as I am active)
