### ISSUE TITLE
Rayman 2 counter factor timing issue

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#827]
This problem is known for a long time. Very old versions of PJ64 also have this bug. I tested with the latest version from git and no difference. Even fixed audio timing does not help.

In the Cave of Bad Dreams the boss misses a jump. This has bad consequences. You get stuck and can't finish the level because the boss is missing. The only known workaround is to set the counter factor temporarily to 5.
Here's a savestate:
https://drive.google.com/file/d/0B7Y6r4SpC_QQN2YtTmZoTVNTaTQ/view?usp=sharing

Would be great to get rid of the counter factor. But I'm not sure how hard it would be.

Counter factor 2(default): The boss misses the jump. You get stuck
![gliden64_rayman_2_000 2](https://cloud.githubusercontent.com/assets/7283660/11744485/12ed603e-a011-11e5-8abe-fdc7a2dcd066.jpg)

Counter factor 5: The boss lands properly. You can finish the level. But the framerate is terrible.
![gliden64_rayman_2_000](https://cloud.githubusercontent.com/assets/7283660/11744507/3cdf59ec-a011-11e5-8312-45376198690b.jpg)

**Comment by AmbientMalice** [comment]
Counter Factor 1 seems to work, as well? I'm not 100% sure, though, since I only tried a dozen or so times.

**Comment by weinerschnitzel** [comment]
Counter Factor is very useful, not just for older machines. My laptop does not play full speed at CF1, so I would not want to see it removed. CF1 should use normal timings, and it does fix this issue. The RDB should be updated to reflect this.

Would be cool if CF could be changed on-the-fly via cheat, then we could enjoy full speed, as well as having timing sensitive issues taken care of. Or maybe to use a cheat that affects that character's jump timing that is activated when using CF2, like how Subscreen delay cheat is used by plugin.

**Comment by purplemarshmallow** [comment]
Yes CF 1 seems to work as well. But this possibly needs more testing. Not sure if the rest of the game works correctly with CF 1. Maybe it can be used.

>CF1 should use normal timings

What are "normal" timings? With normal you mean accurate and like real hardware? I don't think CF 1 is accurate. There must be a reason why CF 2 is the default setting for all games and not CF 1.

>Or maybe to use a cheat that affects that character's jump timing that is activated when using CF2, like how Subscreen delay cheat is used by plugin.

You think having timing inaccuracies in the core and hacking around it with cheat codes is a good idea? I disagree. But I don't know how difficult and demanding it is to emulate this accurately.

Also I dislike the subscreen delay cheat it's very bad. It breaks framebuffer emulation. GLideN64 has a better subscreen hack but it does not work properly in Paper Mario. A better solution is needed. But that's offtopic

**Comment by weinerschnitzel** [comment]
I know what you mean. I only hold this idea to support "hacks on hacks" because Counter Factor is a hack itself. I think it is as necessary as HWFBE.

Explanation from 1964:
>1964 does not emulate the timing of the N64 to cycle-accuracy. For this reason, the CF is a hack which has been added to 1964 so that the user can customize the timing rate. The Counter Factor is so named because there is a register called COUNT which is constantly incremented as the Nintendo64 runs. This register is used by the operating system of a game to control cyclic events and thread switching. In a multithreaded operating system, the OS needs to know how much processing time to give to different threads, and the COUNT register is used to compute elapsed time. So, changing the behavior of the COUNT register via CFs will give you different results. For example, you will notice that as you increase the CF, video may be choppier because producing graphics (display lists) is given a lower thread priority than other running processes. The "factor" is a multiple which increases the Program Clock by a factor of n (1-8), specified by the user. The default is CF3, which is reasonable for most ROMs. If you have a very fast machine (above Pentium III 600 MHz), CF1 will be a more enjoyable experience with smoother frame rates for many ROMs.

**Comment by AmbientMalice** [comment]
>I think CF2 is the default simply for speed and good results.

It's really not that simple. A fair few games are given a specific counter factor not to make them run smoother, but to prevent bugs. The whole affair is horribly hacky, however. I don't think there's any satisfactory solution for Turok 1, for example, which, IIRC, freezes on a certain level without a high counter factor value.

**Comment by weinerschnitzel** [comment]
I suppose better COUNT calculation from real HW tests would be necessary, like mudlord mentioned in #791

I wonder if the CF hack will work better or be needed at all if COUNT is better tracked.

**Comment by purplemarshmallow** [comment]
>I think it is as necessary as HWFBE.

I don't think HWFBE is necessary. I dislike it. Framebuffers can be copied it RDRAM. Software rendering is also possible. But that's offtopic here again.

>1964 does not emulate the timing of the N64 to cycle-accuracy. For this reason, the CF is a hack which has been added to 1964 so that the user can customize the timing rate.

I hope cycle-accuracy is not needed to get rid of the counter factor. This would be bad news.


>The whole affair is horribly hacky, however. I don't think there's any satisfactory solution for Turok 1, for example, which, IIRC, freezes on a certain level without a high counter factor value.

I don't know about Turok 1. But I think CF 1 causes audio crackles in many games. And maybe also timing issues. I hope it's possible to have better COUNT calculation without having cycle accuracy.

**Comment by exhalatio** [comment]
I think this game should be run 30fps / 60vi.
However, CF2 is little fast, CF1 is too fast and CF3 is little slow.
If adjusted by the CF, it seems CF3 is good results.

**Comment by AmbientMalice** [comment]
IMO, CF3 runs far too poorly. I own Rayman 2 on a real N64, and it is nowhere near that jerky. It's kinda hard to know whether CF2 or CF1 are closer to the game's true speed.

**Comment by purplemarshmallow** [comment]
CF2 can't be used because you get stuck in the Cave of Bad Dreams. CF3 looses too many frames. I'll wait a bit. If no one disagrees I'll make a pull request and set it to 1.

**Comment by exhalatio** [comment]
I agree with CF1.
