### ISSUE TITLE
Add support for overclocking the N64's CPU

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#829]
I think adding support for overclocking/underclocking will make Project64 a much more attractive emulator. People will no longer need to go to 1964 for overclocking/underclocking.

This helps in many games, like GoldenEye, Perfect Dark, Conker's Bad Fur Day, Banjo-Kazooie, and more.

Body Harvest actually gets way better than I would have imagined. I wish the original console played like this!

Anyway, 1964 added it, and you can view that source here:

https://code.google.com/p/emu-1964/source/checkout

I will open this issue to remind ourselves about it, and so we can discuss implementation.

I think we should add 0.25x, 0.5x, 0.75x, 1x, 2x, 3x, 4x, 5x, and 6x overclocking/underclocking.

93.75MHz is the original speed of the NEC VR4300 in the N64, so 1964 must be rounding to 100MHz for the default speed (and all the other speeds as well).

The speeds should actually be:

0.25x = 23.4375MHz
0.50x = 46.875MHz
0.75x = 70.3125MHz
1x = 93.75MHz
2x = 187.50MHz
3x = 281.25MHz
4x = 375.00MHz
5x = 468.75MHz
6x = 562.50MHz

We could also have a custom speed setting so you could set your own speed.

Another idea is to just have a custom speed setting instead of using predefined values.

Also, has anybody ever tried to overclock other parts of the RCP? Just curious.

Tell me what you guys think. :smile:

**Comment by wfowler1** [comment]
Do we seriously not already have a bug open for this?

Whatever, putting my support behind this 100%. I'd love to play Perfect Dark at 60 fps without using 1964.

**Comment by vgturtle127** [comment]
@wfowler1 Well, we don't know how stable it will be until we implement it.

Also, a few  games have bugs with the CPU (or more accurately, either the recompiler or interpreter), so that may be an issue.

Most people will support it I would think, but I would rather get @project64 and @cxd4 behind it as well...

**Comment by wfowler1** [comment]
That's true, and technically it's a speedhack. I think it's a given that it can cause problems. But it's an option that can enhance the experience of playing many games. There could be a disclaimer on the option explaining the problems it can cause, like Dolphin has.

**Comment by vgturtle127** [comment]
@wfowler1 Yeah, we already kind of have that in some plugins for stuff about compatibility and the such, so that would fit in with the emulator.

**Comment by AmbientMalice** [comment]
I have a number of problems with this. Firstly, tampering with a real N64's clock rate causes way more problems than it cures. Secondly, the games people want to "overclock" such as Perfect Dark, should most certainly not be overclocked. Tampering with Perfect Dark's timings using either Counter Factor or 1964's "overclocking" feature messes up the music engine. PJ64 has a bigger problem currently with game timings being incorrect. Screwing with things further to try and make games run faster seems shortsighted. Also, since it doesn't actually work on a real N64--it almost always just makes games run too fast--there are some practical concerns about how useful this is.

**Comment by vgturtle127** [comment]
@AmbientMalice It depends on what you mean by "doesn't work". I understand what you're saying though.

This would just be an option, though. We could even hide it unless you had advanced options and the debugger activated.

**Comment by wfowler1** [comment]
Right. I'm not worried about it causing problems if it defaults to "off", especially if we provide ample warning to anyone who stumbles on the option and thinks about turning it on. If it's clearly labeled, and clearly indicated that it can cause problems, and anyone reporting problems with it will be ignored, then why not? It does have the potential to enhance the experience of many games.

**Comment by theboy181** [comment]
I have played with oc and 1964 and it's not a real solution to solving the low FPS. What I have observed is that the code in goldeneye forces the fps to drop to 40 in certain scenarios. When you OC the game it goes to 60 fps but the game speeds up too. 

The real fix for these games are going to be by hacking the rom and hopefully understanding modifications the developers used.

**Comment by theboy181** [comment]
http://tasvideos.org/GameResources/N64/MarioKart64/Patches.html

Here is something that MK64 developers added to make multiplayer play better when in 4 player mode. 

I have a feeling that goldeneye reduces the fps to 40 fps and the game speed, and input lag change as well. 
From what I observed using no video plugin was that the game on the first level will reduce to 40 in till you kill the guards in each area. I'm positive tht the game is watching the variable of number of guards. So if I can lock that number I may be able to prove it. 

Just need skilled cheat code make like retroben to waste his time on it. Too bad it's not banjo kazooie.

**Comment by vgturtle127** [comment]
@theboy181 I know overclocking isn't a "real solution", but I still think it is a desirable feature to have. I actually prefer when the games run at a faster frame rate AND run faster in general. *shrug*

If everybody is mostly against it though, I can close the issue or keep it open and we can see about it after all the cleanups and my testing. :question:

**Comment by theboy181** [comment]
I would like to see OC too. I'm just wanting to let people know that the real fix is going to be hacking the game. 

OC could help other areas of gaming for sure

**Comment by LegendOfDragoon** [comment]
I think figured out a game hack is step 1 to solving certain timing issues. Once you figure out how the game works, it's easier to come up with a solution for better timing.

I may attempt implementing OC if zilmar really wants me to :smile: . I'm disappointed @vgturtle127 did not include me :sweat_smile: ! 

>OC could help other areas of gaming for sure

Definitely. After playing around with OC recently, I can see why some people want it.

>Body Harvest actually gets way better than I would have imagined. I wish the original console played like this!

Body Harvest seems fine w/o overclocking. Can you explain what you encountered? Body Harvest runs good on PJ64, from my testing. The only issue I have with Body Harvest is performance, but that's because I'm running Angrylion's.

**Comment by vgturtle127** [comment]
@LegendOfDragoon I'm sorry if you felt left out. :wink: 

I noticed Body Harvest was really slow with many enemies and explosions and stuff using pretty much any graphics plugin. That was commits ago, though. I will check Project64 and see if it works better. I was also using an older version of GlideN64 and Azimer's audio, so that could be a potential performance hole as well.

**Comment by LegendOfDragoon** [comment]
@vgturtle127 I don't think updated binaries will make a significant difference. Prolly has more to do with settings. But maybe I just didn't notice the issue. I may try doing more tests this week, perhaps. What counter factor are you using?

**Comment by vgturtle127** [comment]
@LegendOfDragoon Well, I didn't change it. So whatever the default is, I'm using that. I didn't think about messing around with those settings, so maybe I should try that.

You are probably right about the binaries not mattering much, but I thought I would test just in case. You never know with emulators. :smile:

**Comment by LegendOfDragoon** [comment]
@vgturtle127 i think this issue has been solved. Please test and let us know :smile: .

**Comment by project64** [comment]
it should, if not I can re-open it

**Comment by vgturtle127** [comment]
@LegendOfDragoon @project64 Oh, I thought this was only an experimental branch, not merged into master! I will definitely check it out! Thanks, guys! 😃
