### ISSUE TITLE
Rayman 2 Sssssam is missing

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#830]
At the end of the "The Marshes of Awakening" level in the cutscene Sssssam is missing. 

This one leaves me clueless. I tried different counter factors, CPU interpreter, angrylion's plugin and PJ64 1.6 nothing seems to help. But maybe I need to test from the beginning and not just load a savestate? I found a video on youtube and it shows Sssssam and also has the miscolored lum bug from Jabo's plugin so PJ64 was used in the video. https://youtu.be/a95roWtmrjc?t=9m20s
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQOXVUT1ROYkZNU28/view?usp=sharing
![1](https://cloud.githubusercontent.com/assets/7283660/11793548/8b21192c-a2ac-11e5-9696-7a9231351356.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/11793443/eccda7ae-a2ab-11e5-9168-46274b634404.jpg)

**Comment by AmbientMalice** [comment]
Could you post the memory pak file? Assuming it hasn't been overwritten with data past this level?

**Comment by purplemarshmallow** [comment]
I did more tests. I started a new game and played the first 3 levels. Sssssam appeared in the cutscene. The problem seems to be my mempack. https://drive.google.com/file/d/0B7Y6r4SpC_QQZ1R0U0RrdDhhNHM/view?usp=sharing

**Comment by purplemarshmallow** [comment]
I'll close this and open it again if I can reproduce it with a fresh mempack
