### ISSUE TITLE
ROM information crash

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#836]
There is a bug where Project64 crashes if you use ROM information many times.

Tested with Project64 latest 32-bit git version, and it happens on 64-bit as well.

It doesn't display an error message or anything, it just exits with no warning.

I have many ROMs, so maybe that plays into it?

**Comment by project64** [comment]
I have cleaned up some of the code related to the rom information dialog (https://github.com/project64/project64/commit/230cc4612fda2c0573721ab356f9270db93a98d1)

With the crash is it on the first time, 5th time, 100 time, a specific file ?

**Comment by vgturtle127** [comment]
@project64 Never a specific file, always after about the 10th ROM or so...

**Comment by project64** [comment]
@vgturtle127  if you do the same file 20 times do you see it? Or got to be different roms

**Comment by vgturtle127** [comment]
@project64 If I do the same one everything is fine, about 10 separate ROMs make it crash.

**Comment by LegendOfDragoon** [comment]
@vgturtle127 is this still an issue?

**Comment by vgturtle127** [comment]
@LegendOfDragoon Yes, most of the crashes that happen in the ROM browser are still an issue. The crashes happen more frequently with the debugger enabled.

Also, the 64-bit version crashes more than the 32-bit version does. 😞

**Comment by vgturtle127** [comment]
@project64 I will make a new issue with some of my new findings.
