### ISSUE TITLE
Debugger crashes

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#837]
Tested on Project64 git version, 32-bit and 64-bit.

The following items cause a crash when you have no ROM loaded:
- Debugger>RSP>RSP Commands
- Debugger>RSP>RSP Registers (this crashes even with a ROM)
- Debugger>RSP>RSP Code dump
- Debugger>RSP>RSP DMEM dump
- Debugger>r4300i>r4300i Registers (doesn't do anything, but I suppose that makes more sense than crashing)
- Debugger>Profile>Profile Code

Some of the options do nothing (which is sort of what they should do), but I would recommend greying them out like other options (like Memory and Breakpoint, for example) when no ROM is loaded.

Probably some simple error/exception handling magic or greying out options will fix this problem. I hope, anyway.

Adding a select and deselect all option to App Logging would be nice. :smile: 

I use that on the rare occasion I need it (WinBack).

That's all I have encountered. Please tell me if I can provide more information.

**Comment by LegendOfDragoon** [comment]
@vgturtle127 is this still an issue with the latest version?

**Comment by vgturtle127** [comment]
@LegendOfDragoon 

64-bit version:
1. Yes and no, sometimes it crashes, sometimes it just shows null values as the RSP commands
2. Yes - crashes with typical "x has stopped working"
3. Yes - crashes with no messages
4. Yes - crashes with no messages
5. Doesn't do anything - not sure if improvements could be made there or not
6. Option no longer there, instead there is record execution times, which crashes with no error messages

32-bit version:

1. Yes and no, same as x64
2. Yes, same as x64, except the RSP registers dialog box shows up, but then crashes
3. Yes, same as x64
4. Yes, same as x64
5. Doesn't do anything
6. Same as x64

It should be noted the 32-bit and 64-bit versions both crash randomly after these crashes occur.

I'm using the latest commit and the latest stable version to test and the problems persist. 😕

**Comment by vgturtle127** [comment]
@project64 I am going to make a new issue with all the bugs I have found, there are quite a few that I think are linked together.
