### ISSUE TITLE
ROM browser bug

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#838]
Clicking the Good Name tab to sort makes it so the Bad Rom? listings all show up first, instead of being based off of the file name (therefore putting it in the correct location in the list).

It appears about 10 unique games make it crash, not the same one 10 times. If that make sense?

Tested on latest Project64 (git version) both 32-bit and 64-bit.

**Comment by cxd4** [comment]
Are you saying the ROM browser crashes because of sorting about 10 unique games?

**Comment by project64** [comment]
bad rom string is stored now as like #123# that is then translated on display, the problem is that value is used for sorting not the translated value, so it is just in the wrong position

**Comment by vgturtle127** [comment]
@cxd4 Yeah. The ROM browser will crash after asking for ROM information for about 10 or more unique games, usually crashing when you ask for ROM information soon after the 10th game or so.

@project64 So it is a bug, and I'm not crazy?

**Comment by project64** [comment]
I am no sure about the crashing .. but I did fix up the sorting of good names (https://github.com/project64/project64/commit/1d2572c2c296f4ba174c4fb6d9387b5998faff23)

**Comment by cxd4** [comment]
http://www.cplusplus.com/reference/cstdlib/qsort/

**Comment by oddMLan** [comment]
Is this still an issue?

**Comment by vgturtle127** [comment]
@oddMLan As far as I know, none of the ROM browser bugs have been fixed in terms of the crashing and such, but the issue of naming conventions is fixed, so I will close this.
