### ISSUE TITLE
Sometimes games stay loaded even though the user selected "end emulation"

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#843]
This has happened to me a bunch during some initial testing, basically a game will stay loaded, and the only way to clear it out is to change plugins, exit the application, or start/stop emulation multiple times.

Tested on latest Project64 git 32-bit and 64-bit.

**Comment by project64** [comment]
that is by design ... you can have a game loaded and be able to change it's setting then start emulation .. so start/stop emulation is different from load/unload a rom .. tho I do not think there is any options to unload a rom

**Comment by vgturtle127** [comment]
Well, what I mean is it won't let you run another ROM until you forcefully unload it, I guess.

The issue is that after I end emulation of a game sometimes, if I try to emulate a new game, it won't load correctly until I end emulation of the new game and restart the emulation. Either that, or I can close Project64 and start it again.

What happens when it won't load correctly is it will show a black screen, but the r4300i/GFX/Alist will all be changing. So the new game is loaded and running, but you can't see or hear it.

This doesn't change when you try different plugins, so I assume it has something to do with the emulator.

I hope that better explains the issue.

**Comment by oddMLan** [comment]
duplicate #316
