### ISSUE TITLE
Language selection dialog (startup) shows incorrect characters.

### ISSUE THREAD

**Issue by JunielKatarn** [project64/project64#855]
![image](https://cloud.githubusercontent.com/assets/4507319/12015475/7b326560-ad02-11e5-80e7-353a1f9f3651.png)

Seems caused by recent character/string-handling changes.

**Comment by tony971** [comment]
The language selector shouldn't be translated, imo. Each language should be listed in its native format. Seeing the Chinese equivalent of "English" won't help me pick my language.

**Comment by project64** [comment]
should be fixed in https://github.com/project64/project64/commit/008dec1f59a9e25b871ab674d8b1edce7901bcc5

**Comment by JunielKatarn** [comment]
Solved.
