### ISSUE TITLE
Splitting Out Jabo's D3D Settings from RDB

### ISSUE THREAD

**Issue by project64** [project64/project64#856]
@AmbientMalice and @vgturtle127 were talking about removing jabo's D3D settings from the RDB. We could split it out like I did for glide settings.

When the d3d plugin registers settings these are the ones it registers:
Direct3D8-ForceFilter
Direct3D8-2xSai
Direct3D8-Brightness
Direct3D8-DesiredAspect
Direct3D8-Direct3DPipe
Resolution Width
Resolution Height
ClearvFrame
Aspect Correction

So I can match any starting with "Direct3D8-" and manually look for the 4 other ones.

interestingly there are options in the rdb that might have applied to 1.6 plugin, but not used now, I am not sure, things like: Emulate Clear, Culling, Self Texture

**Comment by vgturtle127** [comment]
I will gladly work on this, I just need permission and any direction you would like me to go. :smile:

**Comment by project64** [comment]
I figured lets discuss it first which is why I created the issue here.

code wise if you look at Source\Project64-core\Settings\SettingType\SettingsType-RomDatabase.cpp and look at how m_GlideSetting is used then you should get a good idea how it should be done. Just need a new file to read from.

As I do not have the source for jabo's plugin I have no idea if he now goes out side of the emu to read settings, but as long as it goes through the emu then it is all good to redirect them.

**Comment by tony971** [comment]
You could go the way of GLideN64 and have an ini for the plugin, specifically. The RDB should only have universally needed settings.

**Comment by Frank-74** [comment]
Culling is an option I still use.  1.7+ Jabo uses the .cfg and .rdb from Config folder.  Latest 1.6.1 reads only the RDB in emulator folder.

**Comment by vgturtle127** [comment]
@project64 Outside of the emulator? What do you mean?

@tony971 Isn't that already how it works kind of? I mean, Glide and GlideN64 do. And if the emulator's have their own (Mupen64, 1964, Nemu64, Mupen64Plus, Project64) what is left? :laughing: 

@Frank-74 You mean when you use Jabo's plugin, you use the culling options? Is culling an RDB entry that effects multiple plugins? That is pretty much what I want to know, all the exclusively Jabo-specific entries in the RDB that are possible, like Culling and Self Texture.

**Comment by Frank-74** [comment]
@vgturtle127 Culling in rdb only works with Jabo.  Its not switchable from the plugin, only the rdb.  And all the games that need it for Jabo have it in the rdb.  Removing it will make Jabo much slower for games that need it.  Culling puts a limit on the draw distance.  Why remove it anyway?  Its not hurting anything else.

**Comment by AmbientMalice** [comment]
Culling is one of those weird options that should have been enabled by default and disabled per-game. Having an entry for every other game bloats the file. It's ugly. But without Jabo's source, there's no real way to fix that.

**Comment by cxd4** [comment]
>The RDB should only have universally needed settings.

@tony971 I imagine this wasn't exactly your intended point behind that, but, technically there's no such thing as "universally needed settings".  Just about the whole point of "the" RDB file in existence is just to set optional per-game stuff to tweak speed/hacks/interpreter vs. recompiler assumptions/preferences.

**Comment by vgturtle127** [comment]
@cxd4 What he said. :laughing: 

So Glide64 has it's own RDB, right? Does that mean that the default RDB is only used when another plugin is chosen?

**Comment by cxd4** [comment]
Sir, the correct word is "its".
http://its-not-its.info/

**Comment by vgturtle127** [comment]
@cxd4 Funnily enough, the keyboard I bough some Christmases ago I bought because it was waterproof. However, the keyboard is a bit dreadful for typing. Here is what that last sentence looked like before I fixed it:

> Howevr, the keybpard isabit dreadfu;l for tyoing.

I think I need a new keyboard. lol

**Comment by LMLB** [comment]
In case anyone finds it helpful, these are the different Jabo D3D-specific options present in the RDB right now, as far as I can tell:

- Aspect Correction
- Clear Frame
- Culling
- Direct3D8-Direct3DPipe
- Emulate Clear
- Primary Frame Buffer
- Resolution Height
- Resolution Width
- Self Texture

**Comment by project64** [comment]
If jabo's plugin is just going through the settings engine I can easily move those out. Early versions like the 1.6 plugins read the file directly, which is why it wants a version in the root dir instead of config dir. I guess with out the source it is hard to double check.

**Comment by oddMLan** [comment]
Wonder what Jabo's up to these days. I also wonder what he would think if he knew that Project64 is much more open now, and progress has been being accomplished a lot faster than before, rather than being in  
the seemingly dead state that at the time Project64 was when he decided to leave. It's such a shame he cut ties with everyone though, and for @project64 who worked more closely with him... welp

**Comment by Frank-74** [comment]
I tried to message Jabo after the 1.6.1 release, never got a reply.
Wanted him to fix the bug when it creates a new Project64.rdb in the root folder.
All that's needed to fix, is to create a new line at the top of the file.  Then settings save without becoming corrupted.
Would be amazing to see him come back, for a 2.x release of Jabo D3D, with all the new ucodes from GLideN64.

**Comment by theboy181** [comment]
@Frank-74 why not try and contact him again?

**Comment by cxd4** [comment]
no u

**Comment by theboy181** [comment]
:shakes head:

**Comment by cxd4** [comment]
>>Sir, the correct word is "its".

>@cxd4 I think I need a new keyboard. lol

Well I understand you're trolling and all, but typing _it's_ instead of _its_ has nothing to do with bad keyboards.  The `'` apostrophe comes nowhere close to any of the letters I, T, or S.

**Comment by cxd4** [comment]
>I will gladly work on this, I just need permission and any direction you would like me to go. 😄

You could start by learning C I guess.

**Comment by vgturtle127** [comment]
@cxd4 Actually, the reason I said I needed a new keyboard was that at the time I was using a keyboard that had really closely placed keys and when you pushed on one often you would get multiple key presses, but it wouldn't recognize all of them. Anyway, I got a new one. Heh.

> You could start by learning C I guess

Are people really still giving me crap about that? 😆

**Comment by cxd4** [comment]
Actually, the reason I said that _it's_ vs _its_ has nothing to do with bad keyboards is because down syndrome has nothing to do with actually feeling down.

>Are people really still giving me crap about that? 😆

O my bad.  Didn't know that was a nerve point from other people advising that; I just said that from my own personal suggestions box.  Just thought it'd go a long way to actually touching things written in C; that's all.

**Comment by vgturtle127** [comment]
@cxd4 It's fine, no harm done. 😄 

@project64 You still want to separate the Direct3D stuff, right?

**Comment by project64** [comment]
yes still good to do, will do it sometime

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
