### ISSUE TITLE
Spiderman Menu LLE GFX issue with Zilmar RSP

### ISSUE THREAD

**Issue by theboy181** [project64/project64#858]
![capture](https://cloud.githubusercontent.com/assets/9299743/12081653/c12d18a8-b234-11e5-9646-4c2b07239c48.PNG)

Screen flashes menu data from previous screen. Using CDX4 Int the issue wasn't present.

**Comment by LegendOfDragoon** [comment]
That's a weird bug. I cannot reproduce on my end.

**Comment by theboy181** [comment]
Copying the contents from the PJ64 folder minus the plugin and other folders to a different directory and back fixed the issue.
