### ISSUE TITLE
Super Mario 64 LLE gfx issues with PJ64 RSP

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#864]
happens with both PJ64 RSP interpreter and recompiler. z64gl and GLideN64 LLE work correctly with cxd4's interpreter

z64gl
![1](https://cloud.githubusercontent.com/assets/7283660/12171902/afe9ae78-b54d-11e5-9513-d042724c5412.jpg)

GLideN64 LLE
![gliden64_super_mario_64_001](https://cloud.githubusercontent.com/assets/7283660/12171906/bbf4d4b8-b54d-11e5-9fc6-3972a77edbaa.jpg)

**Comment by LegendOfDragoon** [comment]
I cannot reproduce the issue with z64gl. What does it look like, with Angrylion's?

**Comment by purplemarshmallow** [comment]
No angrylion's plugin looks ok. Jabo's plugin also has problems. Some geometry is flickering. I compiled the latest RSP from git. No problems with cxd4's interpreter.
![super mario 64 u snap0000](https://cloud.githubusercontent.com/assets/7283660/12185121/71de8418-b599-11e5-953b-2f01d1e8cc2c.jpg)

**Comment by LegendOfDragoon** [comment]
Can you upload the binary for the RSP?

**Comment by purplemarshmallow** [comment]
https://drive.google.com/file/d/0B7Y6r4SpC_QQVllYODk0TjBEWms/view?usp=sharing

**Comment by LegendOfDragoon** [comment]
I'm still not able to reproduce the issue. Hopefully we can hear feedback from others.

**Comment by LegendOfDragoon** [comment]
I'm wondering if this is a core issue. Can you try testing with cpu interpreter?

**Comment by purplemarshmallow** [comment]
cpu interpreter does not help. Still the same bug

**Comment by vgturtle127** [comment]
@purplemarshmallow @LegendOfDragoon I knew about the rest of those problems, except for the fact that LLE graphics were broken in Super Mario 64.

Let me test it today with the latest build and see what I can come up with.

Have both of you tried modifying the per-game settings (counter factor, etc.)?

**Comment by purplemarshmallow** [comment]
I'm testing with the default settings.
Yes changing the counter factor from 2 to 1 fixes the problem. So it's a timing realted bug

**Comment by LegendOfDragoon** [comment]
Weird, I still couldn't reproduce the issue on counter factor 2. But I just realized that I haven't tried the latest exe. I did test with latest rsp though.

My guess is that it has to do with the semaphore lock or mfc0 exit code. Did you have LLE audio enabled as well?

**Comment by vgturtle127** [comment]
@purplemarshmallow Oh, OK. Sorry, just have to ask. :smile: 

@LegendOfDragoon I can't seem to get it to reproduce either. Except on my setup, I get flickering textures, but not shadows like Jabo's does. Debugging, am I right? lol

**Comment by purplemarshmallow** [comment]
I use LLE audio and Jabo's audio plugin

**Comment by purplemarshmallow** [comment]
This seems to be the same problem as #1021. The solution from #1021 fixes this problem as well

Changing the counter factor does not fix it it can only reduce the problem. I can't believe nobody except me can reproduce this.

**Comment by cxd4** [comment]
My solution from 1021 may fix the problem, but it really is just a quick fix to delete the hack.

Deleting the hack is fine, but it's because of that check that World Driver etc. even work in LLE gfx.  A real fix might be to raise the timeout comparator from 10 to something higher like 100 or even something extremely high like 64000 for maximum stability, but the latter is bound to exponentiate the intermission times in-between task resets and make the ROM way slower than 1 VI/s.

**Comment by purplemarshmallow** [comment]
Is it true that the real problem here is the plugin spec? On real hardware the CPU writes into flags but the plugin spec does not allow it? So hacks are used to bypass this problem. What would be needed to get rid of this limitation?

**Comment by cxd4** [comment]
The closest behavior to real hardware would be to multi-thread the RSP interpreter to run in parallel to an analogous, separate thread for the R4300 core in emulators like Project64, but there are other theoretical approaches that don't involve hacks--generally all of which involve extending the plugin spec.

**Comment by LegendOfDragoon** [comment]
>but there are other theoretical approaches that don't involve hacks

What ideas do you have in mind?

**Comment by vgturtle127** [comment]
@cxd4 Would these changes break compatibility with any plugins? Just curious.

**Comment by LegendOfDragoon** [comment]
>Is it true that the real problem here is the plugin spec?

Not really. Main issue is lack of cycle accuracy. That's probably why the sound is awful in Pokemon Stadium 2 GB Tower. The spec already provides a way for the RSP plugin to run for X amount of cycles. Cycle counting is a non-trivial task.

**Comment by cxd4** [comment]
The spec provides that, but no emulators implement it.  That part of `DoRspCycles` goes ignored.
