### ISSUE TITLE
Duplicate config files in repo

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#865]
So I just noticed these files are all the same:

/Bin/Debug/Project64.cfg
/Bin/Debug64/Project64.cfg
/Bin/Release/Project64.cfg
/Bin/Release64/Project64.cfg

They are identical, and the Project64.cfg.development is basically a copy as well, except it has more of the options filled in.

My thought was we could just have either the development and the stock in the same /Config directory, or we could just have the development config and use a script or something to move it and update/change it.

I just hate to have a bunch of duplicate files that we might have to move around, update separately, etc. Feel free to discuss, comment, etc.

**Comment by project64** [comment]
have a look at the files you are looking at, yes they are the same, but they basically tell the binary to use the config file in /config so that the oonfig/rdb/etc all use the same dir. 

Those files should never be updated

**Comment by vgturtle127** [comment]
So when you build binaries, they must go to whatever directory you are building for (like debug x64 or something), then basically whatever you have built resides entirely in that directory, right?

**Comment by project64** [comment]
yes I have 4 types of binaries they each go to there own dir.
Debug 32bit, Release 32bit, Debug 64bit and Release 64bit

I do not want to mix binary files together so each is seperate. I also want that you can compile and run with out having to move/setup config files so i have the base config to use a shared dir. I also want all the base main distributed files like the rdb to live in only one location.

**Comment by vgturtle127** [comment]
Ah, OK. I will close this. :smile:
