### ISSUE TITLE
[Feature Request] Adding PJ64 wiki links into PJ64?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#885]
I just noticed the existence of this wiki, and I assume it's official. I was wondering whether it might be possible to add support for PJ64's wiki into the emulator itself. Suppose you click on a game. It displays a window with options such as "Boot game" and "Go to wiki page" (for selected game). Or even just have a link to the PJ64 wiki under the "Help" menu.

http://pj64wiki.com/index.php

**Comment by LegendOfDragoon** [comment]
It was made by dsx I believe.

**Comment by cxd4** [comment]
I don't think it is official.  @dsx- wasn't font of GitHub markdown-derived Wiki so used MediaWiki or whatever to create that project.  As far as "official" wiki goes I'm really not sure what zilmar's preferences are...GitHub, external, maybe custom on the main site, maybe no wiki at all.  You could try asking dsx about his wiki but I don't think he's around now.

My personal preference is GitHub wiki, but it doesn't have some special media features and such.

Incidentally, there is also:

* https://github.com/project64/project64/wiki
* https://github.com/project64/web-site/wiki

**Comment by AmbientMalice** [comment]
Dsx's wiki seems fairly well designed. Modelled after the Dolphin wiki, by the looks of it. But if he's not around, that's a problem. I think the problem with a github wiki lies in the fact github is code focused. It doesn't seem oriented towards a game compatibility list, at least in its current form. PJ64 needs a wiki that is easy to navigate, and relatively simple to parse. Trivia at bottom, main details in body, with specific issues listed. There are a shitload of minor problems that need to be listed in such a wiki. The real problem with PJ64's inbuilt RDB list is you can't list the many, many issues games have.

**Comment by dsx-** [comment]
Correct, GitHub wiki is not suitable. Feel free to continue my wiki. I put a lot of information on it already. It is designed to bring Project64 into the modern era. A user-friendly and user-focused wiki made by the users for the users. The problem is that a lot of people here have the attitude of "screw the retarded users" and prefer to push their own agenda and use Project64 as a personal playground rather than serving the people (not accusing anyone in particular but this is the vibe I get, and most of the reason why I left). I put a lot of time and effort into starting a great MediaWiki for the userbase and it would be great to come back and have more people on-board to help finish an already extremely detailed project.

**Comment by AmbientMalice** [comment]
@dsx- I'd be happy to sign up and continue working on your wiki. But I think it is up to @project64 as to whether the wiki should be directly referenced in PJ64 and stuff like that.

The more people reading the wiki, and educating themselves on the status of various games -- especially the ones they're playing, the better.

**Comment by cxd4** [comment]
>I think the problem with a github wiki lies in the fact github is code focused.

They're just Markdown text scripts really.  Something about the same level of code as BB forum scripting for board posts--nothing specific to GitHub, code, or "programmers land".

**Comment by cxd4** [comment]
http://pj64wiki.com/index.php?title=Superman

haha...you people out of your mind?

Ain't no combination of plugins going to save that "game" from unplayability.  All of those GFX/Audio/Input/RSP things should be 0 stars.  Game looks better with the Basic CFB plugin by zilmar.

**Comment by dsx-** [comment]
hahahaha

**Comment by dsx-** [comment]
thanks @AmbientMalice for your wiki contributions. I notice you added that the audio in WDC is wrong. This is pretty disappointing, I leave for a few months and someone manages to break the audio for this game both in pj64 and in azimer's plugin. the sound is identical to the n64 console when FAT is disabled and using an older version of azimer's plugin (0.70 WIP 4), so this needs to be fixed.

**Comment by LegendOfDragoon** [comment]
I believe it works fine in the DS8 version of Azimer's with FAT off. So it would be better to use the newer one, than 0.70 WIP 4.

**Comment by dsx-** [comment]
where can i find the ds8 version of wip 6

**Comment by LegendOfDragoon** [comment]
http://www.emucr.com/2015/12/azimers-hle-audio-plugin-git-20151224.html

**Comment by dsx-** [comment]
already tried that, only includes xa2

**Comment by dsx-** [comment]
tried compiling myself as well, cant figure out how to get ds8

**Comment by LegendOfDragoon** [comment]
in common.h you can comment out #define USE_XAUDIO2 to compile the DS8 version.

**Comment by dsx-** [comment]
cheers! ok audio is good, never mind

**Comment by purplemarshmallow** [comment]
>http://pj64wiki.com/index.php?title=Superman

>haha...you people out of your minds?

>Ain't no combination of plugins going to save that "game" from unplayability. All of those GFX/Audio/Input/RSP things should be 0 stars. Game looks better with the Basic CFB plugin by zilmar.

PJ64+GLideN64 works for me only websites are flickering. Needs better emulation of CPU fb writes.

**Comment by cxd4** [comment]
Looks even better if you close your eyes.

**Comment by vgturtle127** [comment]
@cxd4 As I said in my audit issue, the prototype is WAY BETTER. Has anybody else played it? It worked fine the last time I tried it...

**Comment by dsx-** [comment]
thanks for your wiki additions @vgturtle127 ! @project64 will have no choice but to approve of this wiki.

**Comment by vgturtle127** [comment]
@dsx- Sure. I also contribute to the PCSX2, Dolphin, 3dbrew, wiibrew, dsibrew, etc. Wikis, so it isn't hard to get into doing this Wiki. :smile:

**Comment by oddMLan** [comment]
This wiki should be officialized! Mediawiki is very powerful, and very easy to contribute to. I agree that the Github wiki is not suitable at all for game catalog information or emulation issues. Bugs can be referenced within the wiki itself. Just like PCSX2 and Dolphin's wikis.

The Github wiki should be used for advanced user, not intended for the end user information and tips, like compilation guides and tips, hell, I think the "RDB Info.txt" file is the perfect place for that.

>Just have a link to the PJ64 wiki under the "Help" menu.

I very much agree with this.

**Comment by cxd4** [comment]
I still don't see any difference between the two, other than GitHub wiki really just using markdown syntax like any comments on these issues use (and really being just a Git repository essentially).

Though the debate on differences, if any, between MediaWiki vs. GitHub wiki have become moot in the case of Project64, as zilmar has closed off write-access to the wiki for his repository for security reasons.  Therefore the MediaWiki one by dsx is the only remaining option.  I meant to register; I just haven't gotten to it.

**Comment by JunielKatarn** [comment]
@dsx- Would you consider using an OAuth plugin for your wiki, so we can use our GitHub accounts?
Not very important, but it would be one less password to manage.

**Comment by dsx-** [comment]
i'll look into it
