### ISSUE TITLE
FIFA Soccer 64 core broken.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#886]
Does anyone know when this issue (no sound and opcode errors) emerged?

**Comment by LegendOfDragoon** [comment]
Which one?

**Comment by AmbientMalice** [comment]
>Which one?

I'm not sure what you mean. Game is "FIFA Soccer 64". Game is listed as "broken, use older PJ64". Basically the game has no audio and crashes when you start a match.

**Comment by LegendOfDragoon** [comment]
Ya sorry, I had a different fifa game so I was confused. I found the rom and will test it out.

**Comment by vgturtle127** [comment]
@AmbientMalice @LegendOfDragoon This game has more than a few issues. I believe most of them stem from the CPU, not the graphics or RSP or anything like that. There are issues with that as well, I believe. But some CPU bugs are prevalent.

Mupen64Plus has a hard time running it as well I believe? I would have to check that.

**Comment by Lithium64** [comment]
This game game work's fine on mupen64plus

**Comment by vgturtle127** [comment]
@Lithium64 What version are you using?

**Comment by Lithium64** [comment]
@vgturtle127 2.5

**Comment by vgturtle127** [comment]
@Lithium64 With the new dynamic recompiler or the old one? I am also using Mupen64Plus-Qt.

**Comment by Lithium64** [comment]
@vgturtle127 old one

**Comment by vgturtle127** [comment]
@Lithium64 Huh, I tried with both and it didn't work for me. I better do some cleanup and try again. :smile:

**Comment by exhalatio** [comment]
I did it. You set VI refresh rate to 3000 (two times) and turn off Register caching. 
It works in 2.2.

**Comment by AmbientMalice** [comment]
>turn off Register caching

Won't that absolutely destroy performance?

**Comment by LegendOfDragoon** [comment]
Turning off register caching is a bad idea for multiple reasons. I was able to get sound on VI refresh rate 2504 and counter factor 2.

However, there's a recompiler bug that needs to be fixed. No combination of options I've tried, fix it. I'll try debugging it today.

**Comment by Lithium64** [comment]
@LegendOfDragoon Even on interpreter this game crash

**Comment by LegendOfDragoon** [comment]
@Lithium64 as I said before, I believe it's a timing issue. Tweaking the timing settings make it "work" better. Counter Factor 2 with a high Vi refresh rate seems to work good. I will make a PR to improve a few games soon, but will hold off on changing RDB settings for this game, until more testing is done.

**Comment by LegendOfDragoon** [comment]
Since I fixed the cpu recompiler bug, I'd like someone to test this game. @exhalatio is onto something. I myself generally only tweak CF, but this time, tweaking Vi refresh is what makes the difference. I think CF 2 and VI refresh 2504 works good, let me know what you guys think.

**Comment by AmbientMalice** [comment]
>VI refresh 2504

How did you arrive at this value? Guesswork? Trial and error? Or is there something logical behind it?

**Comment by LegendOfDragoon** [comment]
@AmbientMalice after exhalatio said VI refresh 3000 worked, I just kept going lower until I found the minimum value that worked, since 3000 is probably too high.

**Comment by dsx-** [comment]
hmm this is an interesting issue. glad to see the game working though, hasn't worked since pj64 1.1 or 1.2, can't remember. this also brings the number of project64's unsupported official n64 games to zero!

**Comment by AmbientMalice** [comment]
Been testing. Seems fairly good to me. I did hear one or two announcer comments that sounded a tad clipped at the end, but it's possible sound samples were shaved down to save space.

**Comment by AmbientMalice** [comment]
So is everyone okay with me making a PR to change the VI settings?

**Comment by vgturtle127** [comment]
@AmbientMalice Sure, I have no problem with that. Not that my opinion matters since it isn't my project. :laughing: 

Just make sure you do it so we don't have to go back and change more stuff in the RDB. :wink:

**Comment by Lithium64** [comment]
@AmbientMalice why you close this PR?
