### ISSUE TITLE
N-Rage tab bug.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#887]
N-Rage misbehaves, for example, when switching Controller tabs while a tab other than "Controls" is selected. The page resets to "controls" while the tab doesn't.

![buggy](https://cloud.githubusercontent.com/assets/10704701/12376403/a8b46834-bd3e-11e5-8231-2618f4a3b161.JPG)

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
