### ISSUE TITLE
Wipeout (E) status.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#893]
I've been going through the RDB updating game compatibility for Glide64 and streamlining some stuff. Now I'm a bit puzzled about Wipeout 64. It is currently written up as:

Status=Region issue (core)
Core Note=use (U) ROM (see GameFAQ)

But I found this online.

> I did not remember when i was buying this game,that this game seems to have issues :(
> I mean this is otherwise a good game but seem to have a problems..
> I barely got to start of the Challenges when on my 3rd retry on time challenges..The screen freezed!!
> Tried resetting..Nothing.Music played but picture was stuck...Had to turn off the power..
> Same thing happened on the race challenges..power off..
> Set a record on lower class track..Save failed..I had one game saved on that controller pak(Yes offial one like all five that I have)..tried this on others..Game simply refused to save if there was other game/games on them..
> Had to swap games to test controller paks..Those were fine..Then pins,cart etc..I did save on the pak that I erased(Had to have a first slot empty?)
> I guess this is PAL version problem?

http://s9.zetaboards.com/Nintendo_64_Forever/topic/7452719/1/

So... I'm thinking that maybe this is a problem with the game itself and not an emulator problem? I was thinking I should perhaps rewrite it as "Bugged version" or something like that, plus also put some mention of this in the wiki down the track.

**Comment by Lithium64** [comment]
@AmbientMalice I found the below info on gameFAQ

"(E) region may have an issue where controls fail after winning race - not sure of cause, use the (U) ROM."

**Comment by AmbientMalice** [comment]
Any information about what emulator was used? I'm a little wary about how much hearsay ends up creeping into PJ64. For example, the whole "banana fairy" bug in DK64 I've never actually seen evidence of.

**Comment by Lithium64** [comment]
@AmbientMalice Probably PJ64 1.6

**Comment by Frank-74** [comment]
I had Wipeout (E) for my N64 back in the day.  And it used to freeze also.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
