### ISSUE TITLE
PJ64 RDB update feedback.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#894]
I'm working on a big RDB cleanup with the goal of treating Glide64 as the default plugin and also correcting outdated information and some typos. But here are some ideas that I think might be divisive so I wanted some feedback.

Replace "[video]" with "[Glide64]" when describing major issues relevant to Glide64. Very minor issues (for example, the poorly aligned text in Castlevania: LoD) will be left for the Wiki. A major issue would be "[Glide64] combat simulator crash." I'm thinking Perfect Dark should be downgraded from Compatible to "Plugin Issues", since only GLideN64 runs it anywhere near satisfactorily. People can consult the Wiki for plugin recommendations and workarounds for the crash in question.

"Core Issue: High system requirements" will be removed. Once upon a time, the CPU load of games like Perfect Dark was a concern, but nowdays, the big performance problem is almost always the video plugin.

Anything relating to Jabo will be stripped out, but actual Jabo code entries will be left, and in some cases fixed. (For example, Jabo culling is inconsistently enabled for various versions of some games.)

**Comment by vgturtle127** [comment]
I have been working on a new RDB locally for a while. How far along are you?

**Comment by AmbientMalice** [comment]
About three quarters done. I'll be making a PR within the next day or so, I think. The major problem is fixing a lot of unstable or incorrectly configured games  keep popping up, and I've been correcting their settings as I go. Many of these games have been configured wrong for years now.

**Comment by vgturtle127** [comment]
@AmbientMalice Oh. I guess I wasn't much help then. :laughing: 

Is there anything else that needs to be done to the RDB?

**Comment by AmbientMalice** [comment]
It's not really that simple. Once I make the PR, feel free to look over the changes. Likely I've made mistakes. Likely I've missed stuff. I may know a lot, but I don't know everything.

**Comment by vgturtle127** [comment]
@AmbientMalice OK. I will. You may not know everything, but you know enough that I would probably trust that you did a good job with the RDB.

**Comment by dsx-** [comment]
going through the rdb changes now

- dark rift: should still be issues (plugin), the slowdown during character intros with all gfx plugins remains
- nascar 99 and 2000: should still be issues (plugin), splitscreen multiplayer still doesnt work
- nintama game gallery: should still be issues (plugin); framebuffer on, nothing works // framebuffer off, game runs VERY slow

imo, "high system requirement" should remain for games that need LLE gfx.

other than that, nice job!

**Comment by AmbientMalice** [comment]
>imo, "high system requirement" should remain for games that need LLE gfx.
Are they *really* high system requirements, though? Take Last Legion UX. It runs at 190VIs on Jabo's during gameplay on my PC. It runs at 280VIs on the new z64gl fork. At what point do the games stop being considered "high system requirements" in the modern context? I get your point, of course.

As for your other points, I'll take care of them.

**Comment by LegendOfDragoon** [comment]
I barely get around 60 VI/s in game with z64gl for Last Legion. Although I get around 160 VI /s with Jabo's.

**Comment by AmbientMalice** [comment]
>I barely get around 60 VI/s in game with z64gl for Last Legion.

There must be an incompatibility between your PC, likely your GPU, and z64gl. Bad driver seems likely, especially on Windows. Have you tried enabling force_swap? It usually just makes things slower, but in some cases it can help.

**Comment by LegendOfDragoon** [comment]
I suppose I could test it on mupen64 0.5 on linux. I tried enabling force_swap and didn't see a noticeable difference.

**Comment by dsx-** [comment]
> Are they really high system requirements, though? Take Last Legion UX. It runs at 190VIs on Jabo's during gameplay on my PC. It runs at 280VIs on the new z64gl fork. At what point do the games stop being considered "high system requirements" in the modern context? I get your point, of course.

yeah i guess you're right, the only game that runs pretty slow here is rogue squadron (partly because of CF=1)

**Comment by vgturtle127** [comment]
@dsx- And because of its bonkers, batshit insane programming. :laughing:

**Comment by cxd4** [comment]
>There must be an incompatibility between your PC, likely your GPU, and z64gl. Bad driver seems likely, especially on Windows.

He has some kind of integrated Intel graphics controller.

Those are usually pretty infamous for quickly testing their OpenGL driver support but apparently focusing on their Microsoft DirectX support.  Normally he'd be better off compiling Mesa with the Wayland accelerator into an open-source opengl32.dll for Windows except compiling Mesa3D on Windows is hard.

Normally only ATI Radeon and NVIDIA GeForce were recommended IIRC for N64 stuff, but it appears Intel got better over the years just by focusing on Direct3D.

**Comment by purplemarshmallow** [comment]
Newer intel GPUs have better OpenGL drivers. With a newer intel GPU there is no problem. Even GLideN64 works. But there is a window/fullscreen switching bug with many plugins.

@AmbientMalice 
The Glide64 compatibility list has information about which games need "read every frame" for a certain effect. Is it a good idea to copy the comments from there and add them to Project64.rdb?
https://github.com/gonetz/glidehqplusglitch64/blob/master/Glide64/Help/Glide64%20compatibility%20list.html

**Comment by AmbientMalice** [comment]
>The Glide64 compatibility list has information about which games need "read every frame" for a certain effect. Is it a good idea to copy the comments from there and add them to Project64.rdb?

IMO, no. It will drastically bloat the notes. That's why the Perfect Dark entry lists the splitscreen flicker, but not the missing pause menu background.

I'm hoping very hard that PJ64 will implement framebuffer notification support which will erase the performance issues. Mupen supports. 1964 supports. PJ64 is stuck with extremely expensive per-frame, full-frame copies. It's the single biggest problem with PJ64 currently, IMO. Per-frame isn't disabled because of slow PCs. It's disabled because it brings 3Ghz+ machines to their knees for certain games -- especially the ones that need it.

**Comment by purplemarshmallow** [comment]
Yes I agree. With Glide64 + Mupen this works very well no slowdown at all in most cases

**Comment by cxd4** [comment]
>Newer intel GPUs have better OpenGL drivers. With a newer intel GPU there is no problem. Even GLideN64 works. But there is a window/fullscreen switching bug with many plugins.

1.  It isn't new.  Not in his case, certainly.
2.  Intel I have read announced they will be removing the "deprecated" functions from their OpenGL drivers for at least Linux, while NVIDIA and even ATI have not yet removed any support for these functions from their drivers.  They have the wrong attitude with OpenGL support and may do whatever they have to in order to decrease their losses in the process, but are more likely in Microsoft's pocket.

**Comment by oddMLan** [comment]
Is this still being worked on?

**Comment by vgturtle127** [comment]
@oddMLan I am working on a crap ton of RDB stuff, if that helps.

**Comment by AmbientMalice** [comment]
>Is this still being worked on?

I made the PR in question, so I'll close this.

**Comment by purplemarshmallow** [comment]
Maybe it be a good idea to remove all [video] HLE not supported entries. Glide64 now supports LLE. Most games are very buggy though.
