### ISSUE TITLE
Major League Baseball Featuring Ken Griffey, Jr Glide64 crash.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#895]
This game has problems with most plugins, but it seems to be crashing with Glide64. Can someone else test and report?

**Comment by exhalatio** [comment]
I was tested in Glide64 it will crash, too.
It will solved https://github.com/project64/project64/blob/aea724b81a6148fbe9a30ab8bea80a49efdc9155/Source/Project64-core/MemoryExceptionFilter.cpp#L148-L160 to add <B>case 0x41: ReadPos += 5; break;</B> in this part.

**Comment by LegendOfDragoon** [comment]
It probably should be case 0x41:  ReadPos += 1; break;. The crash is actually caused by Glide64 though, so I'm looking into a fix.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
