### ISSUE TITLE
Fushigi no Dungeon - Fuurai no Shiren 2 stuttering

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#897]
Not sure what's wrong with this game. It spits out debugger errors with the recompiler, and it stutters regardless of settings, even when showing high idle values.

**Comment by exhalatio** [comment]
I guess this game is access to the SRAM every time, so frequent disk access has caused this problem.
I tested set native save directory locale to HDD and SSD. If I set locale to HDD, will severely stuttering than SSD.

**Comment by AmbientMalice** [comment]
That does make some sense considering the worst stutter happens every time you take a step.

**Comment by AmbientMalice** [comment]
I was initially confused as to how an N64 game would get away with constant save writes without burning out, but then I remembered this game uses battery-backed SRAM, meaning it can be rewritten to infinitely. Would it be possible to store the constantly updating save in ram and flush to HDD every so often?

Seems to me this game could be dangerous for Everdrives.

**Comment by vgturtle127** [comment]
@AmbientMalice Especially if you are logging stuff like that to a log file. :laughing: 

Is this the only game that abuses SRAM? This could be an interesting game to test in emulators and in real hardware...

**Comment by LegendOfDragoon** [comment]
Is this fixed?

**Comment by Frank-74** [comment]
Yes, forced flushing sra (and mempak, eeprom) to disk has been removed.  Now windows handles it.
