### ISSUE TITLE
Is there any documentation for Glide64's hacks?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#899]
I'm not referring to the the obvious, fairly well documented game-specific hacks, but rather the ini hacks that range from vague to plain "what does this actually do and why does it look orphaned"?

Like "fix_tex_coord". What does it do? Or "increase_texrect_edge" and "decrease_fillrect_edge" and "force_quad3d" and "useless_is_useless". I can sort of guess what some of them do based on context and others by following the trail through the source, but it'd be nice to have some solid documentation because while Glide64 is a bit of a mess, there is some potential for improvement just by enabling the right tweaks for the right games.

**Comment by vgturtle127** [comment]
@AmbientMalice Are the hacks specific to emulators, plugins, or graphics API's? I thought it had it's own RDB because it had so many hacks for itself?

Maybe @gonetz can enlighten us? :wink:

**Comment by gonetz** [comment]
Glide64 self documenting source code is your only hope ;)

* "increase_texrect_edge" - always increase lower right texrect coordinate by 1. Used to fix black splits in 2D images.

* "decrease_fillrect_edge" - always decrease lower right fillrect coordinate by 1. Don't remember why.

* "force_quad3d" - Glide64 does not separate line and triangle ucodes. Sometimes quad command detected as line one. This option force the command to be quad3d. I don't remember, which games need it.

*  "fix_tex_coord" ? Most likely some game-specific hack.

* "useless_is_useless" - my favorite. It is frame buffer emulation related. I can't explain its purpose or how it works.

**Comment by vgturtle127** [comment]
@gonetz Thanks for the clarification.

useless_is_useless is also my favorite. But if it deals with the framebuffer, that is scary territory! :fearful:
