### ISSUE TITLE
Ogre Battle 64 (J) 1.1 confirmed bad?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#907]
[0375CF67-56A93FAA-C:4A]
Good Name=Ogre Battle 64 - Person of Lordly Caliber (J) (V1.1)
Internal Name=OgreBattle64
Core Note=old [!] ROM is bad

Can anyone shed any light on the Japanese version of this game? If it's Japanese 1.1, where is 1.0? Why exactly was the rom deemed bad? What is the checksum of a validly dumped rom?

**Comment by Lithium64** [comment]
Why does it say "old [!] ROM is bad"? 
This is just a warning that this ROM has been re-dumped (was previously thought good, known now that it's not). If you have not re-scanned with a newer version of GoodN64 you should do so. MD5 hash of the good ROM is E944911491569B9E4DAA03A00832D332 old bad ROM is 8E8113F5FC761C1690EDD0BC680FD3BA

**Comment by AmbientMalice** [comment]
Well, then, that means PJ64 only has the good (J) rom in its RDB. So do we need to mention the existence of a bad dump that won't actually show up in the rom browser anyway?

**Comment by vgturtle127** [comment]
@AmbientMalice I can confirm there was never a 1.0 Japanese cartridge, or at least not one that was dumped. The US got a 1.0 release. The Japanese got the game first, so I'm not sure what is up with that. Unless the 1.0 hasn't been dumped yet, I think it is either:

1. A screw up from the developer/publisher/Nintendo
2. 1.0 was never dumped and is extremely rare/hard to tell the difference between the two
3. Version number screw up somewhere
4. The person/group who dumped the game originally messed up
5. Maybe a "we messed up the cartridge, send in yours and get a free replacement" thing happened? That happened with Turok, so it isn't unheard of.
