### ISSUE TITLE
Nascar 1999 & Nascar 2000 memory pak bug

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#914]
The following error only appears the first time you boot the game. Once the mem pak file for that game is created, the error doesn't display. Perhaps these games boot faster than normal and try to read the mem pak before it's ready?

![glide64_nascar_2000_01](https://cloud.githubusercontent.com/assets/10704701/12439553/687f3c80-bf7d-11e5-8f79-cefa6d1560f2.png)

**Comment by death-droid** [comment]
Hmmm this seems odd, as the emulator should be generating the mpak file before any read or write commands are processed.

**Comment by AmbientMalice** [comment]
If I create a blank mem pak in PJ64 1.6, and boot the game, there's no such error message. The error message seems directly tied to PJ64 2.2+'s new memory pak handling, where it creates the game-specific mem pak at boot.

**Comment by death-droid** [comment]
Ahhh cheers :) Will definitely have to look into that then! Thanks for the heads up

**Comment by vgturtle127** [comment]
@AmbientMalice WHen you say boot faster than normal, you mean normal compared to other games, or games on real hardware?

**Comment by death-droid** [comment]
Tested this some more, latest commit i pushed actually loads up all the mempaks before the game even loads And yet it still occurs, are you sure this is not the standard behavior of the game on the real hardware?

**Comment by AmbientMalice** [comment]
@death-droid Without the real game on real hardware, I've no way of knowing. There's zero mention of any such error occuring on real hardware that I can find on the internet.

All I know it is error didn't start occuring until PJ64's mempak handling was changed. There doesn't seem to be any data written by Nascar to the mempak on boot, looking at the save page manager. PJ64 boots the game without complaint. Maybe this is somehow related to PJ64's issue with releasing control of files? When the file is created, maybe the emulator isn't gaining proper read/write permissions temporarily?

**Comment by death-droid** [comment]
Hmm will have to look into it further then at some point.
The code however should be working as intended.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
