### ISSUE TITLE
N64 CRC vs MD5 vs Internal Name

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#916]
There's currently a bit of a problem in how Project 64 identifies roms. Basically, any rom that shares the same CRC gets treated as the same game.

This means that Turok 1.1 and 1.2 can't be distinguished. This means that the Mini Racers prototype and the PATCHED Mini Racers prototype with fixed textures can't be distinguished. Yes, the blame for Mini Racers falls upon the people who failed to recalculate the CRC of the rom before releasing the fixed version into the wild. But it would be ideal if we could have some way of distinguishing games that share a CRC but have different checksums or a different internal name. Even internal name detection would fix the Mini Racers case, since hack patch changed the internal name.

**Comment by project64** [comment]
MD5 is slow to calculate, you have to read the whole file where the crc you can just open the file and read 8 bytes .. 

now you could do something where you have a crc to md5 and have all the settings based on md5 and if there is a 1-1 mapping of crc to md5 just look up the matching crc and use that .. if there are multiple md5 then you would have to calc the md5 of the file you are talking about.

I have some thoughts on using md5 for storing the save data ..

**Comment by vgturtle127** [comment]
@AmbientMalice @project64 This is definitely an issue, I have probably 20 or so copies of the same game sometimes, including bad dumps and overdumps and stuff like that. Usually they are seen as the same, which annoys me a bit since if you don't have the file name option in the ROM browser selected it just shows the same internal name. :disappointed:

**Comment by cxd4** [comment]
If they're seen as the same ROM, even if they're not, I think they're closely enough to exact binaries that the same RDB settings should almost always be used for both anyway.  So I don't see the problem.

**Comment by vgturtle127** [comment]
@cxd4 I think it should detect bad ROMs, and maybe hacked headers or maybe trained/overdumps as well. I agree that the same game should probably have the same settings (like 1.0 and 1.1 of the same game), but the bad dumps and possibly other similar ROMs should be recognized as not playable or unsupported. Good dumps should always have the same settings as long as they are official versions, revisions, or other complete dumps. Just not the bad dumps, etc.

**Comment by cxd4** [comment]
> it should detect bad ROMs,

No such thing unless you can deem the ROM "invalid" by some means, or if the header doesn't contain accurate information like if the CRC fields are wrong or out of date.

> bad dumps

Bad "dumps" implies more of a piracy issue than an emulation/accuracy issue.

If it's supported by the genuine hardware, it should be supported by an emulator of said h/w.

**Comment by AmbientMalice** [comment]
This primarily concerns the rom browser's ability to detect what a rom actually is. Which version, what region, etc.

**Comment by cxd4** [comment]
Region and version are always detected by means of the ROM header.  The entire rest of the ROM could still be a "bad dump"--the header itself is still the accurate source of information.

**Comment by AmbientMalice** [comment]
"Bad dumps" aren't a huge concern for me. PJ64 treating two slightly different roms as the same due to a shared CRC is.

**Comment by cxd4** [comment]
That effectively would mean that one of said ROMs is a bad dump.
The only other way a shared CRC would exist besides that is hacks neglecting to sync the CRC.

And as I mentioned, if the CRCs are the same and everything else is still mostly the same, it still is probably the same ROM enough to the point of the RDB settings being equally accurate configurations for both.  That is the point after all, behind why you would care if PJ64 treats them as the same or different:  The RDB file?  Which would still have the same settings for both "almost" identical ROMs.  So I don't imagine the issue here.

**Comment by AmbientMalice** [comment]
>That effectively would mean that one of said ROMs is a bad dump.
The only other way a shared CRC would exist besides that is hacks neglecting to sync the CRC.

Turok: Dinosaur Hunter 1.1 and 1.2 share the same CRC. And yes, Mini Racers was lazy hackers neglecting to fix the CRC.

>So I don't imagine the issue here.

The rom browser is the problem. Just as save wiping is the problem with using Internal Name for saves. The rom browser can't distinguish between games that share a CRC.

**Comment by cxd4** [comment]
The ROM browser?  Yes it most certainly can really.

Unless GoodN64 mis-recorded the Turok games, then you should see a different byte at 0x3F (64th byte from the top of the ROM image, big-endian/z64) between Turok 1.1 and Turok 1.2.  The ROM browser would be able to use this to know if a ROM image is release 1 or release 2, although GoodN64 falsely distorts the genuine versioning system as "1.x".

**Comment by vgturtle127** [comment]
@cxd4 To clarify what I mean by bad dumps, I mean bad dumps as labeled by GoodN64. Also known as confirmed bad dumps. Overdumps and hacked headers still work in Project64 most of the time, so I take it back that they should be unsupported. Trained ROMs work alright as well, so they should be "supported" as well, I suppose.

I am truly stumped as to how to tackle this situation, but I do wish there was an elegant solution. I hate having multiple dumps that I know are bad labeled good, and dumps I know are good labeled as unknown or bad.

**Comment by cxd4** [comment]
I know what you meant from the get-go but still do not see any relevance.

What GoodN64 does has nothing to do with N64 emulation.  You're talking about Project64 here and then you're talking about GoodN64.  It's almost like apples and oranges.  GoodN64 is essentially a piracy database of how to identify exact copies of particular software.  What does that have to do with emulation?

**Comment by vgturtle127** [comment]
@cxd4 OK, never mind. I suppose my point doesn't matter anyway.

I am just trying to say there may be more accurate ways of detecting a ROM.

**Comment by cxd4** [comment]
Correct--those are things that the actual hardware itself would manage.

A database of software dumps that are known to be detected as "recognized" isn't really the same thing as accurately detecting a ROM.  Any ROM that performs on the genuine console would still be a valid ROM, regardless of what things like good tools or GoodN64 thinks.

**Comment by vgturtle127** [comment]
@cxd4 I find it odd every N64 emulator does this with a database, when many other systems don't have such a limitation...

**Comment by AmbientMalice** [comment]
Most emulators don't have a rom browser. They use their database, and yes, they often have a database, for other purposes.

PCSX2 has a database.
Dolphin has a folder full of ini files with "settings". (We don't call them hacks, oh, no, they're "settings".)

But the data for these is lifted from game titles on disc, which is usually far more specific than stuff on cartridges.

**Comment by vgturtle127** [comment]
@AmbientMalice Yeah, that always bothered me. :cry: 

Who ever thought game databases and game-specific hacks were a good way to do things? :laughing: 

No offense to anybody, I mean to be fair it works with PCSX2, Dolphin, and Project64. The emulators function. I just worry about maintainability.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
