### ISSUE TITLE
Shunyuan HLE Audio causes a fatal error when loading game. 

### ISSUE THREAD

**Issue by Yui12** [project64/project64#917]
I don't know if anyone could do anything about it, but I'll just post this issue here just in case. If nothing can be done about it, then whatever. Just putting this here. It doesn't matter what game I try! I'm using the latest git of Project 64 and the last version of the plugin. Oh and yes, I do know that there is aziaudio I can use instead, but I currently have an issue that I've open up about the volume slider not working on git for the plugin. I'm still waiting for a reply about the fact that I can't change backends with aziauido to fix the problem since there all greyed out and empty, but that is another story that has nothing to do with this sound plugin here.

![untitled](https://cloud.githubusercontent.com/assets/13986398/12471597/e9ceda76-bfb3-11e5-85b6-a7bf4cecbdf7.png)

**Comment by AmbientMalice** [comment]
Out of curiosity, why aren't you using Jabo's audio? It currently has the best all-round compatibility. Azimer's is good, but it keeps losing sync currently. Shunyuan's HLE audio plugin is a fake HLE audio plugin that runs audio through an RSP interpreter. It gets very good results for a handful of games, mainly BOSS ones.

**Comment by AmbientMalice** [comment]
Anyhow, on the topic of your problem specifically, I think the plugin relied on a PJ64 bug that was fixed some time ago. I'm not sure there's a fix short of rebreaking PJ64 specifically for the plugin.

**Comment by Yui12** [comment]
Because Jabo as cracking in some games.

**Comment by AmbientMalice** [comment]
Which games is Jabo's audio crackling in? Are you sure you're using the latest git?

**Comment by Yui12** [comment]
The popping is very mild though. You can deal with it, but it's it's kind of irritating sometimes. After retesting it, it seems to be slightly better than Jabo 1.6. It was only a few games that had this problem. I was basing this off the past when it seemed worse. The current version is not as bad, so nevermind. Like I said, if the Shunyuan plugin can't be fixed, and if it relied on a bug for it to even work, then this plugin is dead and not worth talking about no longer unless you still use an older version of PJ64. All I care about now is wondering why I can't switch to Xaudio2 on Azi's plugin which is another issue I open up on that Git.

**Comment by Azimer** [comment]
@AmbientMalice - "Azimer's is good, but it keeps losing sync currently."  Can I get more details?  Report an issue so it can be fixed or point to where it's been reported.  First I've seen of this.

**Comment by AmbientMalice** [comment]
@Azimer Last I tested, if you leave GoldenEye idling in the menus, the "chonk" menu transition sounds will fall behind within a few minutes.

**Comment by AmbientMalice** [comment]
>After retesting it, it seems to be slightly better than Jabo 1.6. It was only a few games that had this problem. I was basing this off the past when it seemed worse. The current version is not as bad, so nevermind.

Basically, PJ64 has switched to a new audio timing method. It's way better than before, but it still does have some problems. I think PJ64 needs to switch to Azimer's as soon as the plugin is mature and stable enough.

**Comment by Yui12** [comment]
I'm going to pretty much close this issue because no one seems to use this plugin these days, and the current versions of Project 64 so far has almost no issues with Jabo's audio plugin due to the new timing. Just still waiting for a fix for Azi audio when it comes to the volume slider, but no hurry for that right now. The plugin works on 1.6, but stopped working sometimes according to a bug fix.

**Comment by LegendOfDragoon** [comment]
Btw Shunyuan's seems to work now.

**Comment by Yui12** [comment]
Oh really? Well Jabo seems to work better than before anyway with the new timing. Back in 1.6, Jabo had issues with many games due to crackling.
