### ISSUE TITLE
Rat Attack Recompiler Multiplayer Crash

### ISSUE THREAD

**Issue by dsx-** [project64/project64#919]
Well known issue since Project64 1.3 but I figured I'd put it here anyway if someone wants to investigate why multiplayer works only on the CPU interpreter and not the recompiler.

**Comment by AmbientMalice** [comment]
I think it's been mentioned before somewhere that this game has TLB issues.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
