### ISSUE TITLE
[Feature Request] Moving some items from Advanced to Basic mode.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#923]
I was wondering whether it would be better to have stuff like the frame limiter accessable in basic mode. Because there's a lot of people pressing F4 and nothing happens for them. Also, maybe Show CPU Usage should be moved to Basic Mode?

**Comment by vgturtle127** [comment]
@AmbientMalice Yeah, I think the frame limiter is a basic feature, not an advanced feature. Show CPU usage should also be moved to basic mode, as this has no effect on anything and is only for informational purposes (much like the VI/Alist/etc.).

Also, what about #445 ?

**Comment by MELERIX** [comment]
the info menu about config files/rdb/translations should also be moved to basic interface instead of advanced.

**Comment by vgturtle127** [comment]
@MELERIX :+1: Agreed. :smile:

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
