### ISSUE TITLE
2 Problems with Show CPU Usage

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#924]
1st problem is when rsp broke = false .

2nd problem is when it calls ProcessRDPList in Write32DPCommandRegisters.

In these 2 scenarios, the results are wrong because it's not using the right task .

**Comment by vgturtle127** [comment]
@LegendOfDragoon So how is performance calculated? Is it FPS-based, VI-based, based on the CPU, or is there some magic involved?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
