### ISSUE TITLE
Glide64's rainbow textures.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#927]
I'm puzzling over these. They affect a number of games (Perfect Dark, GoldenEye, and Winback come to mind. They also randomly affect 2D games with bright rainbow seams And they were actually once half fixed, but the source code for the fix was never released.

![glide64_perfect_dark_01](https://cloud.githubusercontent.com/assets/10704701/12530175/5bec78d8-c221-11e5-960c-4a94fc253b7c.png)

https://github.com/AmbientMalice/glidehqplusglitch64/issues/181#issuecomment-84800810

gonetz stated this in the thread:

> I see the problem. Something is wrong with texture loading. You may use 
> attached build as a temporal remedy until I find a general solution.
> Also, you have LOD calculation enabled by default. This is not good, especially 
> for Perfect Dark.

And then he uploaded this custom DLL. https://storage.googleapis.com/google-code-attachments/glidehqplusglitch64/issue-181/comment-11/Glide64.rar I've tried it, and it works. Not perfectly, but well enough. For some reason, the hacky fix was never merged nor was the issue properly resolved.

**Comment by vgturtle127** [comment]
@AmbientMalice Is it fixed in GlideN64 or Project64 Glide64?

**Comment by AmbientMalice** [comment]
GlideN64 is completely unrelated. It's based on gln64, not Glide64. All the major releases of Glide64 are affected as far as I know. At least the ones 2009-2012.

**Comment by vgturtle127** [comment]
@AmbientMalice Oh, yeah. I keep forgetting that. Not sure why. :stuck_out_tongue_closed_eyes: 

How does LOD calculation affect the textures when you enable/disable it? With or without the fix?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
