### ISSUE TITLE
[Glide64] Fullscreen res shoud default to current res

### ISSUE THREAD

**Issue by project64** [project64/project64#929]
if no fullscreen res has been set, then set the res to the current display

**Comment by cxd4** [comment]
That definitely makes life easier.

**Comment by vgturtle127** [comment]
@cxd4 I'll say. :laughing:

**Comment by Frank-74** [comment]
Has this already been done?

Glide64 sets fullscreen res to 1366x768, my laptop's current resolution, on first running.

**Comment by project64** [comment]
most likely, I think I did all the code for this, unless there is issues
