### ISSUE TITLE
Star Wars Episode I - Racer (J) screen text

### ISSUE THREAD

**Issue by Nekokabu** [project64/project64#931]
Japanese text are displayed correctly.
![pj_6fd2fa0f4a21e2f8dc22f6e548fd8620a67aeaee](https://cloud.githubusercontent.com/assets/11252775/12550828/8cbd7244-c3a9-11e5-8ba0-71e6e3ba5378.jpg)

After this commit( https://github.com/project64/project64/commit/dc65c0a0756858945571e5a37a5eb2386d25e3c6 )
not correctly.
![pj_dc65c0a0756858945571e5a37a5eb2386d25e3c6_2](https://cloud.githubusercontent.com/assets/11252775/12612788/9ec42fba-c538-11e5-9dcd-9c802d415e90.jpg)

*2016/1/27
Update a screenshot

**Comment by 173210** [comment]
It's a merging commit and has two parents. Which has the bug, a0ac5d6d33038e7c338f8a2381d0a6fa5a04bd23 or 3172a3d1d43d5d1d3d42adcc63673a6d4fd1342a?

**Comment by Nekokabu** [comment]
https://github.com/project64/project64/commit/a0ac5d6d33038e7c338f8a2381d0a6fa5a04bd23 is OK, 
https://github.com/project64/project64/commit/3172a3d1d43d5d1d3d42adcc63673a6d4fd1342a is wrong.

**Comment by 173210** [comment]
So the bug is in #739?

**Comment by Nekokabu** [comment]
maybe

**Comment by cxd4** [comment]
I don't see any difference between those screenshots.  They're both showing the same Japanese text as far as I can tell (except for paused/resumed, new menu from after RomOpen etc.).

Furthermore I also don't see what controller plugin spec changes have to do with language translations.

**Comment by exhalatio** [comment]
I tested jabo and Glide64 displayed correctly on last commit.
However, GlideN64 is not correctly. https://github.com/gonetz/GLideN64/issues/510
Do you use any video plugins?

**Comment by vgturtle127** [comment]
@cxd4 No, @Nekokabu is right. The kanji is not the same. There are minute differences, just look closely. The character before the number 4, for example.

**Comment by cxd4** [comment]
That's not even kanji, silly.  That's primarily katakana IIRC.

And there is no number 4 in his original screenshot besides the text "Project64".  If he was referring to Japanese text inside the ROM and not the Project64 translations and GUI he should have just taken bitmap screenshots of the game and not the whole emulator window.

**Comment by cxd4** [comment]
@Nekokabu : If you are correct in pinpointing my N-Rage Controller 1.1/1.2 plugin specs commit as the "cause" behind your problem, then I venture to say that you need to update your local copy of PJ64 N-Rage Input plugin with the new changes from the source.  Your PJ64 N-Rage may be outdated and may be using the older plugin spec where zilmar thought he needed to pass CONTROL_INFO as a pointer instead of the whole struct.

**Comment by 173210** [comment]
Obviously he is referring to ROM emulation. The later picture is not comprehensive at all (I can read Japanese)

**Comment by vgturtle127** [comment]
@cxd4 Good catch. Not sure why I got the two confused. :confounded: 

I know he didn't have the number 4 in the original screenshot, that's what I was trying to point out. :wink: 

Basically, I was saying if you look at the character before the number 4 in the second screenshot, it changes from the first screenshot to the second screenshot. I hope that is more clear. :smile:

**Comment by cxd4** [comment]
I'm used to this guy posting translation/language file/GUI issues with Project64's window so I'm not really accustomed to screenshots by him of anything else that isn't the window UI itself.

**Comment by vgturtle127** [comment]
@cxd4 Understood, everybody makes mistakes. :smiley:

**Comment by cxd4** [comment]
>I know he didn't have the number 4 in the original screenshot, that's what I was trying to point out. :wink:

No he did have it:  It was in front of "Project6" like I said.

It would have gone without saying if you meant 4 inside the ROM, and not 4 inside the Project64 window UI, that you would have meant 4 in both screenshots (like "Project64"), not only one of them.  You could have just said to the left of the word "RACER" in the game.

**Comment by vgturtle127** [comment]
@cxd4 Yeah, I could have been more clear. I need to work on that, I guess. :blush:

**Comment by theboy181** [comment]
What settings are you using? What plugins? I tested and it seems OK on this end. However, a While ago I noticed that the intro would change based on the audio plugin I had selected. It would play an alternate intro where Subalbu would be the racer.

**Comment by vgturtle127** [comment]
@theboy181 You mean Sebulba? :laughing: 

What commit are you using? What plugins are you using? Behavior is the same for me...

**Comment by Nekokabu** [comment]
Everyone I'm sorry.
This was not a bug in Project64 and specific commit.
It will think GlideN64 bugs.

**Comment by vgturtle127** [comment]
@Nekokabu It's OK, dude. Everybody makes mistakes. :smile:
