### ISSUE TITLE
Glover 2 SP_DRAM_ADDR_REG not in RDRAM space

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#938]
When using LLE gfx and the PJ64 RSP it keeps spamming this error once per frame. Even if the debugger is disabled. The game still works however. Can this warning be disabled or is there something going wrong on PJ64's side?

**Comment by cxd4** [comment]
Print the value of Rsp_Info.SP_DRAM_ADDR_REG.

If it's a garbage address like `0x01000000` or greater, then I think you have encountered the occasional R4300 CPU re-compiler corruption that sends the wrong data to RAM which then forwards corrupt stuff to the RSP's cache.  Might not even be a RSP bug.

**Comment by LegendOfDragoon** [comment]
It appears to be a garbage address. It tried cpu interpreter + rsp interpreter and it still happened.

**Comment by cxd4** [comment]
A4001000 would be a legitimate address, as only the low 24 bits matter and the A4 is intended.

**Comment by purplemarshmallow** [comment]
When the message pops up *Rsp_Info.SP_DRAM_ADDR_REG is ```0xFFFFFFFF```
Tested with cpu interpreter + rsp interpreter

**Comment by cxd4** [comment]
That definitely is a garbage address.

If it isn't from a bug in the emulator--but actually happens on the real console as well--then that would mean SP_DMA_READ reads from unmapped memory which should result in reading 0, and that SP_DMA_WRITE writes to unmapped memory which should result in a null operation that does nothing.

**Comment by vgturtle127** [comment]
@purplemarshmallow @cxd4 @LegendOfDragoon Is it a little endian ROM or a big endian ROM you guys are using?

**Comment by purplemarshmallow** [comment]
I don't think this can make a difference. PJ64 supports everything converts it when starting emulation and if byte order is wrong then it does not work at all.

The rom is .v64 this usually means it's byte-swapped

**Comment by vgturtle127** [comment]
@purplemarshmallow Oh, OK. I had an issue with Glover 2 a while back and I thought converting the ROM to another format seemed to work for me. There were more than few issues then, though. I remember it kept locking up the emulator.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
