### ISSUE TITLE
Incorrect Fullscreen Rendering

### ISSUE THREAD

**Issue by tony971** [project64/project64#943]
Using a fresh-built Project64 with no existing configs, GLideN64 fails to enter/exit fullscreen properly. Entering fullscreen fails to stretch the resolution across the entire screen. So unless you run fullscreen at your monitor's resolution, the image is placed in a corner with black space taking up the rest of the screen. Exiting fullscreen reduces the display area back down to the windowed resolution but fullscreen stays in effect, also resulting in large areas of black on screen. The only way to exit fullscreen properly is to go back to the windows login screen and enter the desktop again.

I built Project64 on commit c452353 and used the latest git versions of GLideN64, Aziaudio, and HatCat's RSP.

**Comment by tony971** [comment]
Edit: I need to run Glide64 before GLideN64 for each instance of Project64 for things to work properly.

**Comment by Lithium64** [comment]
@tony971 Are you using Intel GPU drivers? if your answer is yes, Intel OpenGL drivers has a bug that cause similar errors on GlideN64.

**Comment by cxd4** [comment]
This sounds like that thing you told me months ago about how Glide64 full-screen was giving you issues and, my angrylion GL fork was giving you an error on switch to full-screen saying "Conflicting monitor resolutions detected.  Perhaps you have more than one output device?" and you found it was some kind of driver bug on your end or something.

**Comment by tony971** [comment]
This is a different computer, @cxd4 . But it might be Intel drivers. This is a Microsoft Surface Book with an nvidia gpu in the base. I have no idea when it seizes command. I assumed that whenever the top half was docked, but it might be a power saving feature to only turn it on during heavy load.

**Comment by vgturtle127** [comment]
@tony971 Surface Book? Do you have it plugged into the wall when you are testing?

Also, do you have GeForce Experience installed?

**Comment by tony971** [comment]
Okay so I found out that it switches between integrated and discreet graphics on a program by program basis. I overruled the default to make it run pj64 with the nvidia card. Now Glide64 and GlideN64 both behave in the same incorrect manner. If I set the fullscreen resolution to 640x480, the monitor's resolution will change, but the graphics will only be displayed in the upper left quadrant of the screen. The rest of the screen has a lower-resolution version of my desktop showing. This is similar behavior to my other Windows 10 machine with nvidia graphics.

**Comment by tony971** [comment]
If I set the fullscreen resolution to my monitor's resolution, then the full screen is used. But it drags my computer to a crawl since my monitor's resolution is 3000x2000.

**Comment by JunielKatarn** [comment]
I think this behavior is because of the high DPI resolution of the Surface
Book's monitor.

It does some scaling to avoid having too small fonts or icons, so it
emulates a different resolution. Project64 is not hiDPI-aware.

I have seen the same behavior on a Retina MacBook Pro.

On Saturday, 30 January 2016, Tony <notifications@github.com> wrote:

> If I set the fullscreen resolution to my monitor's resolution, then the
> full screen is used. But it drags my computer to a crawl since my monitor's
> resolution is 3000x2000.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/project64/project64/issues/943#issuecomment-177205694>
> .
>


-- 
- Julio

**Comment by Oowoon** [comment]
I also have experienced this bug before, word-for-word on the description. I'm running Windows 10 Home Version 1511 on a rig that was more or less upgraded from Windows 8. 

My build is a gaming laptop that's a few years old, and historically, PJ64 hasn't regressed like this until recently. I also have a Nvidia Card that runs as a dedicated GPU alongside a Intel HD Processor. (And I have everything launching globally via the Nvidia GPU, which is a Geforce GTX 670m)

I'm not certain whether it's a high-DPI issue on my end, as my laptop screen hasn't changed. the max resolution is 1920x1080, additionally. I had a friend do a similar test after this began to become an issue, and this issue seemingly didn't appear for him on his AMD card which is also on the same version of Windows 10 as me. (Build Number 10586.63, at present)

Thus, this makes me think that it could be problem either with the Nvidia GPU and Windows 10, or possibly some part of Project64's code in relation to the two. I'd have to run more tests to be certain.  I can't seem to weasel my way out of this problem short of an emergency shutdown, as the nature of the bug prevents me from closing Project64 with the black screen that affects the Desktop as well as the CTRL+Alt+Del function, nonwithstanding that emulator doesn't have a keybinding that can stop the emulation (Unless there's some trick to this that I'm not aware of)

I'll run one again after I apply the most recent Driver update and Windows Update and see if the issue persists on the latest PJ64 build.

**Comment by project64** [comment]
is there an actual change needed for project64? Or is this more of just how GLideN64 is using OpenGL since project64 does not do anything directly with handling gfx.

**Comment by tony971** [comment]
This also happens with Glide64. I'm unable to get either plugin to render fullscreen correctly. Both of them render to the upper left quadrant of the screen after changing my monitor's resolution.

**Comment by JunielKatarn** [comment]
@project64 
The Project64 Windows application IS actually HiDpi-aware. But that means windows, text and dialogs.
That was fixed with a trivial setting in the VCXPROJ build files.
Glide64 needs to be made High-dpi-aware too. This might be non-trivial, though.

**Comment by tony971** [comment]
Would this change also have to happen in GLideN64? @purplemarshmallow @gonetz

**Comment by gonetz** [comment]
What does "high-dpi-aware" mean for graphics plugin? Do you want the plugin to automatically select highest available resolution for fullscreen?

**Comment by tony971** [comment]
No, my fullscreen resolution is set to 640x480. The issue is that it changes my monitor's resolution but only renders in the upper left quadrant of the screen. The rest of the screen is my normal desktop.

**Comment by tony971** [comment]
If i set the fullscreen resolution to my native resolution (3000x2000), then it renders correctly. However, this is too performance heavy to actually use. I just want to use fullscreen resolutions other than native and have it render on the whole screen.

**Comment by gonetz** [comment]
I guess it is work for your graphics drivers or monitor settings. GLideN64 just asks OS to create GL context in fullscreen with given resolution. How this context is created and how it will be displayed is out of plugin's responsibility.

**Comment by tony971** [comment]
Other applications with Qt frontends render correctly with different fullscreen resolutions. mGBA, for example, goes to fullscreen perfectly.

**Comment by gonetz** [comment]
Is QT frontend really count? Please check Mupen64Plus version of GLideN64.

**Comment by tony971** [comment]
Okay I tried the same build on my 1080p desktop. Same issue. I think the problem resides somewhere in project64's config files. I was able to change its behavior by replacing my config folder (the one in the app's base directory with the rdb files) with an old version. I'm not sure which one changed the behavior and I'm not able to reproduce it.

**Comment by gonetz** [comment]
What about mupen64plus? Does it work correct?

**Comment by tony971** [comment]
mupen64plus works fine. Judging by the fact that this happens in multiple plugins for Project64 on multiple computers, it's a Project64 issue.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
