### ISSUE TITLE
XInput 360 default bindings

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#951]
I notice that the Xinput setting doesn't have any default controls set. So I was wondering whether PJ64 should have some so that people can simply plug in their controllers and use the emulator.

![360](https://cloud.githubusercontent.com/assets/10704701/12643465/06b2bcde-c608-11e5-9c14-f58860dfda9b.JPG)

Here's my logic -- basically everything on the 360 controller has a general enough equivalent except for the Z trigger. The N64 L and R reflect the 360's left and right shoulder buttons. But the L button is rarely used. So I propose binding it to the left analogue trigger. This means that right shoulder is "R" and left shoulder is "Z", which is quite comfortable for most N64 scenarios. Want to reload your gun in Rainbow 6? Turn on the map in Turok 2? Press the "L" button, which is the left analogue trigger, or L2 to some.

edit:
A crude way to achieve this would be to stick a premade XInput Controller 1 Config.xcc into the Config folder, which raises another problem: how is PJ64 handling multiple controllers? I only have one 360 controller. If someone has four of them, how are they supposed to assign them?

**Comment by tony971** [comment]
I know that mupen64plus has quite a catalog of default settings for various controllers. I have no idea how difficult it would be to port it to n-rage

https://github.com/mupen64plus/mupen64plus-input-sdl/blob/master/data/InputAutoCfg.ini

**Comment by vgturtle127** [comment]
@AmbientMalice I have more than a few controllers. A collection, really. SO if I can help create some default profiles, I'd be more than willing to test and write profiles for various controllers.

**Comment by FeedbackFox** [comment]
I know this is a bit late, but this is the top google result for ''project 64 xinput profile'' so I'm gonna post it anyway. For those looking, here's my default config for xinput controllers:
[Xinput config.zip](https://github.com/project64/project64/files/1839193/Xinput.config.zip)

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened

**Comment by KiwiChris-xx** [comment]
thanks @FeedbackFox config file works
