### ISSUE TITLE
[Recompiler] Unhandled Opcodes for 64DD support

### ISSUE THREAD

**Issue by LuigiBlood** [project64/project64#953]
So with 64DD IPL ROM on Recompiler, when it is about to boot a 64DD game, this error appears. (I need to mention that Fixed Audio timing is off, else it doesn't even reach that point.)

![image](https://cloud.githubusercontent.com/assets/952602/12649545/5263739a-c5df-11e5-88e8-67d967624001.png)

EDIT:
Happy_:
> In the IPL, the write to the Cause register occurs as it is preparing to start the disk program.  After writing Cause, it will also write to the Count and Compare registers.

**Comment by LuigiBlood** [comment]
This is the cause, I believe: https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Recompiler/RecompilerOps.cpp#L5476

**Comment by LuigiBlood** [comment]
This pull request fixes the issue: https://github.com/project64/project64/pull/958

**Comment by Giggybytes** [comment]
IMG]http://i67.tinypic.com/5d2djt.png[/IMG]

What?

**Comment by LuigiBlood** [comment]
Has nothing to do with this issue though.
