### ISSUE TITLE
break point errors

### ISSUE THREAD

**Issue by MelchiorGaspar** [project64/project64#954]
getting this Breakpoint ERROR when Loading a save state.
![projet64_exceptions6](https://cloud.githubusercontent.com/assets/1712842/12650211/efdbc558-c5af-11e5-87f9-67fc11b5948e.jpg)

```
    if (Entries != sizeof(m_TimerDetatils) / sizeof(m_TimerDetatils[0]))
    {
ln333 g_Notify->BreakPoint(__FILE__, __LINE__);
        return;
    }
```

and this breakpoint error if I load a save.  but if I disable the debugger in options --> Advanced this error does not happen. but if I load a savestate instead I get a different blank error.
![project64_exceptions7](https://cloud.githubusercontent.com/assets/1712842/12650322/6616e388-c5b0-11e5-8e15-b5abe1b49c1e.jpg)

```
      default:
          if (bHaveDebugger())
          {
ln2246        g_Notify->BreakPoint(__FILE__, __LINE__);
          }
          m_MemLookupValue.UW[0] = PAddr & 0xFFFF;
          m_MemLookupValue.UW[0] = (m_MemLookupValue.UW[0] << 16) | m_MemLookupValue.UW[0];
```

**Comment by LuigiBlood** [comment]
Is your save state older than the 64DD support implementation?
I'm thinking that my 64DD Timing may have something to do with the first error.

**Comment by MelchiorGaspar** [comment]
yeah, I recreated the save state by loading the save first  then redoing the savestate and it loaded(F7).

This still only works if the Debugger is off, if If I try to load a ingame save while the debugger is on I get the 2nd break point.

**Comment by cxd4** [comment]
The second one is to be expected.

The first of those errors is the bug of interest here.
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/SystemTiming.cpp#L319-L335

**Comment by project64** [comment]
it means that some of the timings can be wrong, so code needs to be added to the load state to deal with new timers.

**Comment by LegendOfDragoon** [comment]
@project64 , I take it that older save states will not ever be supported? If that's the case, then I guess this issue and 947 can be closed.

**Comment by project64** [comment]
@LegendOfDragoon it just needs to handle the difference in timers, I will look at it once the 64dd is more settled and what is going on with the timers

**Comment by LuigiBlood** [comment]
I don't think the 64DD emulation will change that much other than allowing disk swapping and saving, which we have to think about.

**Comment by MelchiorGaspar** [comment]
outdated savestates was only half the issue the other breakpoint occurred when the debugger was enabled and trying to load a save

**Comment by LegendOfDragoon** [comment]
I believe this is now fixed. Old save states now seem to work fine for me. Please test.

**Comment by MelchiorGaspar** [comment]
I found the debugger option will not enable so I cannot test that breakpoint error.... or I should say it will not save as enabled but does seem to enable for this instance of PJ64....

I found when attempting to load a save for Aidyn Chronicles, I got a breakpoint error after enabling the Debugger I got this.
![pj64 v2 3 0 208 _breakpoint-error_memoryvirtualmem cpp ln708 _](https://cloud.githubusercontent.com/assets/1712842/17634516/099ceaa8-60a1-11e6-8410-c6d6d2f499ff.png)

**Comment by LegendOfDragoon** [comment]
Can you upload the save state? I'd like to test it out.

**Comment by MelchiorGaspar** [comment]
The save state works fine... its the actual ingame save that gets a breakpoint when the debugger is enabled... I can upload the save file if u want.


[AIDYN_CHRONICLES_Cont_1.mpk.zip](https://github.com/project64/project64/files/417100/AIDYN_CHRONICLES_Cont_1.mpk.zip)

savestate u wanted:
[Aidyn Chronicles - The First Mage (U) (V1.1).pj.zip](https://github.com/project64/project64/files/417101/Aidyn.Chronicles.-.The.First.Mage.U.V1.1.pj.zip)

**Comment by LegendOfDragoon** [comment]
@MelchiorGaspar this issue should be fixed now.

**Comment by MelchiorGaspar** [comment]
ok hope so I'll have to test it out on the next dev build if its in it.

**Comment by LegendOfDragoon** [comment]
@MelchiorGaspar can you test the latest release?

**Comment by MelchiorGaspar** [comment]
I tried out PJ64 v2.3.2.202.. 
enabled the debugger... 
and loaded the in-game save for 
Aidyn Chronicles - The First Mage (U)(v1.1).z64
.... save loaded fine without a breakpoint crash...
so I guess this can be closed now
