### ISSUE TITLE
Loading save state stops sound.

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#955]
Whenever I load a save state, the sound stops.

**Comment by AmbientMalice** [comment]
Which game? Which version of PJ64? This issue should have been fixed.

**Comment by LegendOfDragoon** [comment]
@twarnercool2 what audio plugin are you using?

**Comment by twarnercool2** [comment]
I'm using the newest verison off here. I am using Azimer v70 plug in.

**Comment by LegendOfDragoon** [comment]
Yup, figured it was because of Azimer's plugin. If you're using the XA2 version, that's a known bug in the audio plugin. It has already been reported to Azimer, but I suggest you close this issue since it's not Project64's fault.

**Comment by twarnercool2** [comment]
Ok,sounds good.
