### ISSUE TITLE
"Play game with disk" doesn't display on menu

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#962]
This option should appear on the menu
![bug](https://cloud.githubusercontent.com/assets/10705488/12700384/c65dc67a-c7be-11e5-8ad4-6a8bc08bc42b.png)

**Comment by AmbientMalice** [comment]
I thought LuigiBlood removed that option, and everything is opened as a rom or something?

**Comment by vgturtle127** [comment]
@AmbientMalice I'm unaware of such a change if it exists. It should probably be an option in the right-click menu and should be added to the file menu also (if it hasn't been removed or changed), though.

@LuigiBlood may know how to best handle this.

**Comment by LuigiBlood** [comment]
"Play Game with Disk" is ONLY when you right click a ROM on the ROM Browser.

**Comment by Lithium64** [comment]
@LuigiBlood Thank you, I understand now.

**Comment by vgturtle127** [comment]
@LuigiBlood But there still isn't a way to open N64DD games with the file menu. It is possible to disable the ROM browser, so if somebody has that disabled they can't run N64DD stuff. I still think we should add an option to the file menu. I just think it would be more logical. Also, I test with and without the ROM browser, so also more convenient for everybody. Just an idea.

**Comment by AmbientMalice** [comment]
IMO, people should be using the rom browser if they want to play N64 DD games with expansion disks.

**Comment by vgturtle127** [comment]
@AmbientMalice Yeah, but there are bugs with the ROM browser. And also, the performance when you have many ROMs in the ROM browser is kind of bad...

**Comment by AmbientMalice** [comment]
>Yeah, but there are bugs with the ROM browser.

Such as?

>And also, the performance when you have many ROMs in the ROM browser is kind of bad...

I have around 400-500 roms in my browser, and haven't experienced any performance issues.

**Comment by vgturtle127** [comment]
@AmbientMalice I get random crashes and hangs, at least on my machine. :confused: 

I have slightly more than that, around 3400 ROMs. :wink: 

I speculated before about the causes, but I really don't know. Nothing SHOULD be wrong, but something is...
