### ISSUE TITLE
"Donkey kong 64" polygon tearing

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#966]
At random points, "Donkey kong 64" models stretch out a little bit.

**Comment by vgturtle127** [comment]
@twarnercool2 You should probably provide more information than that. Things like:

* Project64 version
* Plugins and versions
* OS version
* ROM version
* Settings used
* Computer specifications
* Maybe a screenshot or video?

**Comment by Isotarge** [comment]
This is likely a duplicate of #791

**Comment by LegendOfDragoon** [comment]
@twarnercool2 can you close this? It's a duplicate, as Isotarge mentioned.
