### ISSUE TITLE
[Glide64] On android with out SDL

### ISSUE THREAD

**Issue by project64** [project64/project64#969]
I am trying to work out how to do open gl es on android for glide64, looking at mupen ae code it creates it and interacts using SDL. If I can I want to do Project64 with out using SDL.

Following this tutorial http://www.learnopengles.com/calling-opengl-from-android-using-the-ndk/ I am able to get opengl calls in the jni to change the color of the screen using a GLSurfaceView for the game window.

Now I do not know if this is the best way for a n64 emu to be structured, the GLSurfaceView is either continually calling onDrawFrame and expects the frame to be called (or when told to). So it is pulling to the jni. Where with the emu, we are trying to push the screen on a dlist call. So it is not seeming to mesh properly.

I had the thought that the plugin could render to a texture then with onDrawFrame it just renders that texture to the surface.

I have not done anything with opengl so I have no idea if this is a good idea, if I should be using GLSurfaceView, if there is some way that is a lot better for an emu, if I do use GLSurfaceView what is the best way to link to the current drawing code. 

What do you think @purplemarshmallow @gonetz? Any suggestions, best way to handle this?

**Comment by purplemarshmallow** [comment]
>I had the thought that the plugin could render to a texture then with onDrawFrame it just renders that texture to the surface.

I know that's how plugins like GLideN64 and z64gl work on Desktop. They render to a texture and then display this texture if the emulator calls UpdateScreen. That's a good design. But I fear I can't help a lot here. I never looked into Android development. Not sure about Android.

But I have to say this I'm not sure if it's a good idea to make another android port of Glide64. I tested both Glide64 and GLideN64 on my phone with Mupen64plus AE and GLideN64 works better. Glide64's framebuffer emulation is very incomplete on android needs some effort to get it fully working. I don't think that's so easy the fact that you are working on a wrapper for Glide code does not make it easier. With GLideN64 framebuffer emulation with GLES2 is almost as good as on Windows and compatibility is much higher. And there is a GLES3 mode for high end devices like the Nvidia Shield. Speed is about the same but Glide64 sometimes seems to be a bit slower

**Comment by retrobenny** [comment]
In my experience testing the 2.0 variant,there is a number of glitches and issues such as Banjo-Tooie having a black screen when no HUD elements are onscreen and glitchy shadows in Conker,the 3.0 and 3.1 variants work fine,but are obviously a bit slower.
Their Glide64mk2 plugin has missing polygon chunks while the recent test port of libretro's Android Glide64 does not have missing chunks,yet has its own issues currently which originate in the normal libretro Glide64 on the Android version.
Just adding some info to help,hopefully the Mupen64Plus AE devs will respond and help in some way. :)
