### ISSUE TITLE
Pokémon Stadium 1 and 2 are crashing

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#97]
Since the Project64 2.1, i'm having crashes on Pokemon Stadium 1 and 2, to fix these crashes i'm using the interpreter. Now in the latest build of Emucr on Pokémon Stadium 1 the crash only happens with Glide64, but on Pokémon Stadium 2 crashes still happen on Pokemon selection screen before the battles with every video plugin.

**Comment by Lithium64** [comment]
Pokemon Stadium 1 crash with Glide64 Final
https://www.youtube.com/watch?v=E0EdsTEYLdo

Pokemon Stadium 2 crash with Glide64 Final
https://www.youtube.com/watch?v=0FHhYCKd7Co

Pokemon Stadium 2 crash with Jabo's Direct3D 8 1.7
https://www.youtube.com/watch?v=0LncCNvIDX4

**Comment by cxd4** [comment]
It works if you have Cache, PI DMA, or "Start changed".

Your issue was that "Protect memory" does nothing (neither does "TLB unmapping").  I'm not even sure that needs to be set in the RDB.  It's like most of the RDB entries just lazily default to "Protect memory" being set, everything else un-set, when a lot of games don't even need it.

**Comment by project64** [comment]
actually I never lazily set it to protected memory .. the only time I ever do is if running the interpeter and the recompiler at the same time they get out of sync and protect memory helps that. While the error maybe invisible to the user it can manifest latter as something strange.

**Comment by cxd4** [comment]
But *exclusively* protect memory?  Because often times protect memory can be disabled in exchange for a different compiler method being enabled.  You only set protect memory when it was the only checkbox out of the 5 that fixed the asynchronicity between interpret and compile?

**Comment by project64** [comment]
if you are going to test the other settings work, run with sync core on.

**Comment by Lithium64** [comment]
@cxd4 @project64 I did several tests and the only thing that worked has been to use the FuncFind = 2 on Pokémon Stadium 2

Glide64 only works fine with Pokémon Stadium 1 and 2 using the interpreter

**Comment by exhalatio** [comment]
@Lithium64 Glide64 works turn off Advanced Block linking have Recompiler.

**Comment by cxd4** [comment]
I don't have Glide64 so didn't really care.
I just followed your video here @Lithium64 :

>Pokemon Stadium 2 crash with Jabo's Direct3D 8 1.7
https://www.youtube.com/watch?v=0LncCNvIDX4

You're supposed to turn on either PI DMA or Cache.  I have no more crash at that spot in your video.

But yeah, recompilers all suck.  Just use the interpreter if you want. :P No problem with me.

**Comment by Lithium64** [comment]
@cxd4 Turn on Cache worked for Jabo's plugin

**Comment by Lithium64** [comment]
I managed to fix all the problems with the games, they are now working well with all plugins.

I will make a pull request with the fixes

**Comment by Lithium64** [comment]
The reason for the bug on this game is ABL, it need to be turned off for the game run fine
