### ISSUE TITLE
"Gaunlet legends" missing lots of textures in Jabo, and crashes in Glide64/GlideN64

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#982]
Screenshot; http://imgur.com/Uk9T4Mt

Project64 version: I am using the latest version of project 64 git

ROM version: The rom is an American one

Plugins and versions: I tried using Gliden64(latest version), Glide64, and Jabo. Jabo is the only one that goes to the actually game. Glide64/GlideN64 crashes at various times.

Settings used: Basic settings.

**Comment by cxd4** [comment]
Force legacy pixel pipeline gets textures showing up in Jabo.

I've used Glide64 with this game plenty of times before.  That it crashes now is news to me that I would have to boot into Windows to check, but that Jabo's plugin has issues with or without the default settings changed cannot be helped.

**Comment by vgturtle127** [comment]
@cxd4 GLideN64 runs the game fine, as far as I know. I haven't checked older builds, though.

@twarnercool2 What version of GlideN64 did you try?

**Comment by twarnercool2** [comment]
I tried the version that comes with Project 64.

**Comment by vgturtle127** [comment]
That's Glide64, not GlideN64. GlideN64 stable builds can be downloaded here:

https://github.com/gonetz/GLideN64/releases

Development builds can be downloaded here:

http://www.emucr.com/search/label/GLideN64?&max-results=12

**Comment by cxd4** [comment]
GlideN64 isn't relevant here, though, because the first-party plugin here is Glide64.

>@cxd4 GLideN64 runs the game fine, as far as I know. I haven't checked older builds, though.

Well, why would that interest me?  I just said it works fine on Glide64, so there's not much reason to just not be using that instead if it already works.  You could make issues about GlideN instead, but they wouldn't really be well-fitted here for project64, now, would they?  Because the source control here applies Glide64.

**Comment by vgturtle127** [comment]
@cxd4 I was just saying as far as I know, most plugins run the game without issues, so I think he may have some local issue.

And also, I just ran the game fine on Glide64, which is somewhat odd...Not sure what his issue could be...

**Comment by purplemarshmallow** [comment]
Glide64 has missing gfx it makes the game unplayable. Only the intro looks correct. GLideN64 only works in LLE and runs very slow

**Comment by LegendOfDragoon** [comment]
Which HLE plugins show the health bar?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
