### ISSUE TITLE
"Body harvest" collision detection is broken

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#983]
Project64 version: I am using the latest version of project 64 git

ROM version: The rom is an American one

Plugins and versions: I tried using Gliden64(latest version), Glide64, and Jabo.  Collision detection is broken for all versions

Settings used: Basic settings.

Description: I can walk through houses and various other things.

**Comment by purplemarshmallow** [comment]
The CPU checks auxiliary buffers. For now only angrylion's plugin works correctly

**Comment by LegendOfDragoon** [comment]
It seems to require accurate results because even z64 is bugged. Too bad I can't debug GLideN64 since I only have OGL2.1.

**Comment by LegendOfDragoon** [comment]
The video plugin needs to support accurate Depth Buffer emulation.

**Comment by Frank-74** [comment]
Latest GLideN64 has fixed the clipping issue mostly.  Game is now fully playable.  Tested up to America level.  Completed Greece and Java without issues.
https://github.com/gonetz/GLideN64/issues/1364#issuecomment-287617539

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
