### ISSUE TITLE
Crashes when launched in steam

### ISSUE THREAD

**Issue by AndyOHart** [project64/project64#988]
When I try play a ROM I have added to Steam, individually as a ROM or by running Project64 in Steam and selecting the ROM, it crashes with the error:

Exception caught:
File: \N64 System\N64 Class.cpp
Line: 384

From looking at the code it seems the system isn't active or something?
Not sure really but it works fine outside of Steam, crash just happens when I try play any ROM through Steam

**Comment by vgturtle127** [comment]
#990 will hopefully fix some of the issues.

**Comment by vgturtle127** [comment]
@AndyOHart Also, you should report these kinds of things to Valve, they may have some way to help fix some of the issues. They probably aren't aware of all the issues with controller input and latency with emulators. I don't have Steam account, so I can't get access to support or anything, unfortunately.

**Comment by AndyOHart** [comment]
Ok will do

**Comment by vgturtle127** [comment]
@AndyOHart If you get a response, you should post it here, I would be interested in what they have to say.

**Comment by AndyOHart** [comment]
They just published an update to make it play nicer with 3rd party apps and launchers so hopefully that means it will work better

**Comment by AndyOHart** [comment]
Shit sorry accidently closed the issue

**Comment by vgturtle127** [comment]
@AndyOHart DO they have a changelog or something? Where did you hear that? I always thought they were against stuff like that since they couldn't control it? :laughing:

**Comment by AndyOHart** [comment]
Yeah sure, http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/907842849554681945

I might of read into it wrong or something ha, I'm not the most technical, but I saw on the Neogaf thread people were saying it would help with launchers

**Comment by vgturtle127** [comment]
@AndyOHart It looks like what they meant was in regards to shortcuts within Steam. The other controller stuff is for the Steam controller, it looks like.

Has anybody else reported latency or input issues with emulators launched through Steam that you know of?

**Comment by PFCKrutonium** [comment]
Other than PJ64 I have had no issues, and Valve isn't against it, they just don't explicitly support it.

**Comment by vgturtle127** [comment]
@PFCKrutonium Alright, good to know. I wonder if Mupen64Plus has these issues? TOo bad it won't run N-Rage...

**Comment by PFCKrutonium** [comment]
What stops Mupen from using N-Rage?

**Comment by vgturtle127** [comment]
@PFCKrutonium Mupen64Plus doesn't use the Zilmar plugin API anymore, and N-Rage was only ever released as a Zilmar plugin as far as I know.

**Comment by vgturtle127** [comment]
@AndyOHart Has this been fixed for you in newer builds? I would like this to be closed if so...

**Comment by AndyOHart** [comment]
Yeah it was to do with the controller plugin I used from what I remember, think it was NRage caused issues. I just changed that to another and it worked. I can try again on the newest builr to see it it works ?

**Comment by cxd4** [comment]
Yeah, don't use any older PJ64 N-Rage's.  They lack sync with the fixed plugin specs.

Older PJ64 N-Rage's (I would say compiled over 3 months ago) need to be run on analogously older builds of the core executable, which had an incompatible definition of one of the plugin spec functions from what was stated in the public spec that other emulators used.

Shortest way to put it is have a newly compiled PJ64 N-Rage when running newly-compiled PJ64.

**Regular**,, non-PJ64 brand N-Rage (v1.83, v2.1 rc3, ... before 2.3 I think) are not affected by this issue and can be used with whatever sub-revision of Project64 v2.x, as they use a smaller, previous release of the plugin specs and have nothing to do with this.

So is that everything to do with the issue you were having then?

**Comment by AndyOHart** [comment]
Ah I understand. Yeah basically don't have the issue anymore and I'm running P64 fine through steam with my Steam Controller :-)

**Comment by cxd4** [comment]
Had the issue myself after committing the "fix" causing these discrepancies.

It revolves around whether the initiation of the plugin passes (from the core) and interprets (within the plugin) a (32- or 64-bit) pointer to a struct, or the whole struct binary being pushed itself.  (The trick is both the core and the plugin sending vs. expecting this creates 4 possible combinations, of which 2 are broken and undefined results.)

So sometimes starting emulation with a old-core new-plugin or new-core old-plugin had a random graphics glitch here or there, or missing text like Nekokabu found, or sometimes nothing at all wrong with the game.  Random glitches or lack thereof really, just a side effect of fixing the spec.

**Comment by AndyOHart** [comment]
Ah right I getcha, interesting stuff. I'm a happy man now anyway

**Comment by vgturtle127** [comment]
@AndyOHart Then would you *pretty please* close the issue? :wink:

**Comment by AndyOHart** [comment]
Of course :-)

**Comment by vgturtle127** [comment]
@AndyOHart Thanks, buddy. :smile:

**Comment by AndyOHart** [comment]
No worries :-)
